/* ── Daram Bomb Game — extra question bank · Chapter A2: الْفِعْلُ (العامل) ──
   Anki sub-decks 2.1.1–2.1.6 turned into MCQs. Game-only; see 1-muqaddimah.js
   for the conventions (correct:0, choices shuffled by game.js at render).   */

window.DARAM_COURSES = window.DARAM_COURSES || [];

window.DARAM_COURSES.push({
  id: 'bank-fil',
  num: 'A2',
  titleAr: 'الْفِعْلُ الْعَامِلُ',
  titleEn: 'Bank — The governing verb',
  sections: [

    /* ═══ 1. اللازم والمتعدي وأفعال القلوب والتحويل ═══ */
    {
      id: 'bank-fil-lazim',
      title: 'اللازم والمتعدي وأفعال القلوب والتحويل',
      steps: [
        { t: 'mcq', q: 'What are the two types of **عامل فعل**?', choices: ['القياسي — governed by a consistent rule · السماعي — no rule, dependent on transmission', 'اللازم · المتعدي', 'التام · الناقص', 'المتصرف · الجامد'], correct: 0,
          why: 'This is the top-level split of the governing verb; اللازم/المتعدي is a sub-division **inside** القياسي.' },
        { t: 'mcq', q: 'What does the **قياسي** verb do grammatically?', choices: ['Puts its فاعل (or نائبه) in رفع, and the مفاعيل and الحال in نصب', 'Puts its اسم in رفع and its خبر in نصب', 'Puts both its فاعل and its مخصوص in رفع', 'Governs nothing at all'], correct: 0,
          why: 'The second option describes the أفعال الناقصة, the third أفعال المدح والذم — both سماعي.' },
        { t: 'mcq', q: 'Define **الفعل اللازم** and give its other names.', choices: ['One whose effect does not pass its فاعل to a مفعول به (﴿ولا هم يحزنون﴾) — also فعل قاصر and فعل غير متعد', 'One whose effect passes to a مفعول به — also فعل واقع and فعل مجاوز', 'One that needs a خبر to complete its meaning', 'One restricted to the ماضي form'], correct: 0,
          why: 'قاصر (“falling short”) and غير متعد name the same limitation from two angles.' },
        { t: 'mcq', q: 'Can the effect of a **لازم** verb reach anything beyond its فاعل?', choices: ['Yes — anything except a مفعول به, e.g. the مفعول فيه and الحال: جلس الطالبُ أمامَ المعلمِ متأدباً', 'No — nothing at all beyond the فاعل', 'Yes, but only through a حرف جر', 'Only in poetry'], correct: 0,
          why: 'اللزوم bars **one** thing: a direct object. Adverbs and circumstantials are unaffected.' },
        { t: 'mcq', q: 'Define **الفعل المتعدي** and give its other names.', choices: ['One whose effect passes to a مفعول به — also فعل واقع and فعل مجاوز', 'One whose effect stops at the فاعل — also فعل قاصر', 'One that takes two مفعولين only', 'One derived from a ثلاثي مجرد'], correct: 0,
          why: 'واقع = it **falls upon** the object; مجاوز = it **crosses over** to it.' },
        { t: 'mcq', q: 'In which two ways can a verb be **متعديا**?', choices: ['بنفسه (﴿أذهب عنا الحزن﴾) · بواسطة حرف جر (﴿ذهب الله بنورهم﴾)', 'بالتصريف · بالإسناد', 'بالتضعيف · بالهمزة', 'باللفظ · بالمحل'], correct: 0,
          why: 'The same root ذهب shows both routes — intransitive alone, transitive through the باء.' },
        { t: 'mcq', q: 'What is the object of a verb made transitive **by a حرف جر** called?', choices: ['مفعول به بواسطة حرف الجر — also متعلق بمعنى المفعول به, or مفعول به غير صريح', 'مفعول مطلق', 'مفعول فيه', 'نائب فاعل'], correct: 0,
          why: 'It is an object in meaning but not “outright” (صريح) in form, since a preposition intervenes.' },
        { t: 'mcq', q: 'Which verb is cited as being transitive **both** بنفسه and بحرف جر?', choices: ['هدى — ﴿اهدنا الصراطَ المستقيم﴾ vs ﴿وهداه إلى صراطٍ مستقيم﴾', 'ذهب', 'جلس', 'حزن'], correct: 0,
          why: 'Both constructions are Qurʾānic, which is why هدى is the standard illustration.' },
        { t: 'mcq', q: 'What are the three **أضرب** of the متعدي verb?', choices: ['Transitive to one مفعول · to two مفعولين · to three مفاعيل', 'بنفسه · بحرف جر · بالتضمين', 'قياسي · سماعي · ملحق', 'تام · ناقص · جامد'], correct: 0,
          why: 'Counted by **how many** objects it reaches, ﴿خلق السموات والأرض﴾ being the one-object case.' },
        { t: 'mcq', q: 'The verbs taking **two objects** divide into which two kinds?', choices: ['Those whose مفعولان are NOT originally مبتدأ وخبر (﴿وهديناهما الصراط المستقيم﴾) · those whose مفعولان ARE (﴿وما أظن الساعةَ قائمةً﴾)', 'Those taking أن and those not', 'Those transitive بنفسه and those بحرف جر', 'Those that are قياسي and those سماعي'], correct: 0,
          why: 'The giving-type verbs (أعطى، منح، وهب، كسا) join two unrelated nouns; the heart-verbs join a subject to its predicate.' },
        { t: 'mcq', q: 'What are the two kinds of double-object verb **called**?', choices: ['فعل جارحة (objects not originally مبتدأ وخبر) · فعل قلب or فعل تحويل (objects originally مبتدأ وخبر)', 'فعل قاصر · فعل مجاوز', 'فعل تام · فعل ناقص', 'فعل قياسي · فعل سماعي'], correct: 0,
          why: 'جارحة = of the limbs (a physical transaction); قلب = of the heart (a mental judgement).' },
        { t: 'mcq', q: 'May the objects of the **giving-type** double-object verb be deleted?', choices: ['Yes — the first (﴿وإنك لتهدي إلى صراط مستقيم﴾), the second (﴿هداهم الله﴾), or both (﴿أعطى كل شيء خلقه ثم هدى﴾)', 'No, never', 'Only the second may be deleted', 'Only both together may be deleted'], correct: 0,
          why: 'All three patterns are attested — a freedom the heart-verbs do **not** fully share.' },
        { t: 'mcq', q: 'What are the two groups of **أفعال القلوب**?', choices: ['أفعال اليقين (certainty) · أفعال الظن, also called أفعال الرجحان', 'أفعال التحويل · أفعال الشروع', 'أفعال الرجاء · أفعال المقاربة', 'أفعال المدح · أفعال الذم'], correct: 0,
          why: 'Certainty vs preponderant opinion — the two grades of inner conviction.' },
        { t: 'mcq', q: 'List the **أفعال القلوب of اليقين** (7).', choices: ['وجد، ألفى، رأى، علم، عرف، درى، تعلَّم', 'ظن، حسب، زعم، جعل، حجا، عد، وهب', 'صيّر، رد، ترك، تخذ، جعل، وهب', 'عسى، اخلولق، حرى، كاد، كرب، أوشك'], correct: 0,
          why: 'Note تعلَّم here means “know for certain”, not “learn”.' },
        { t: 'mcq', q: 'List the **أفعال القلوب of الظن/الرجحان** (8).', choices: ['ظن، حسب، زعم، جعل، حجا، عد، وهب، خال', 'وجد، ألفى، رأى، علم، عرف، درى، تعلَّم', 'كان، أصبح، أضحى، أمسى، ظل، بات، صار، ليس', 'نعم، بئس، ساء، حبذا، لا حبذا'], correct: 0,
          why: 'جدل point: جعل and وهب appear on this list **and** among أفعال التحويل, in different senses.' },
        { t: 'mcq', q: '﴿وَإِنْ وَجَدْنَا أَكْثَرَهُمْ لَفَاسِقِينَ﴾ — what is وجد here?', choices: ['فعل قلب of اليقين, taking two objects', 'فعل قلب of الظن', 'فعل تحويل', 'A one-object verb meaning “to find/come upon”'], correct: 0,
          why: 'Meaning “we knew them for certain to be…”, not physical finding — hence two objects.' },
        { t: 'mcq', q: '﴿وَيَحْسَبُونَ أَنَّهُمْ مُهْتَدُونَ﴾ — what category is حسب?', choices: ['فعل قلب of الظن (الرجحان)', 'فعل قلب of اليقين', 'فعل تحويل', 'فعل جارحة'], correct: 0,
          why: 'They **suppose** wrongly — mere preponderant opinion, so الظن.' },
        { t: 'mcq', q: '﴿وَجَعَلُوا الْمَلَائِكَةَ … إِنَاثًا﴾ — what is جعل here?', choices: ['فعل قلب of الظن — they **supposed** the angels female', 'فعل تحويل — they transformed them', 'A one-object verb meaning “created”', 'فعل شروع'], correct: 0,
          why: 'They could not actually transform angels; the verb reports a false belief, so it is a heart-verb here.' },
        { t: 'mcq', q: 'State the rule of **الاختصار** vs **الاقتصار** for deleting objects of أفعال القلوب.', choices: ['الاختصار (deleting both with evidence for what is meant) is allowed — ﴿الذين كنتم تزعمون﴾ i.e. تزعمونهم شركائي; الاقتصار (deleting one with no evidence) is not', 'Both are allowed freely', 'Both are forbidden', 'الاقتصار is allowed, الاختصار is not'], correct: 0,
          why: 'A bare ظننتُه is the forbidden case: it leaves the hearer with no way to recover the judgement.' },
        { t: 'mcq', q: 'What does **ألم تر** mean?', choices: ['ألم تعلم, carrying also a sense of التعجب — sight being the strongest cause of knowledge', 'Literally “did you not look”, with no further sense', 'أخبرني', 'ألم تسمع'], correct: 0,
          why: 'A metonymy: the sense of sight stands in for knowledge, with astonishment layered on.' },
        { t: 'mcq', q: '﴿أَرَأَيْتَ مَنِ اتَّخَذَ إِلَٰهَهُ هَوَاهُ﴾ — what does أرأيت mean?', choices: ['أخبرني (“tell me”) in astonishing situations — its مرفوع pronoun varies: أرأيتِ، أرأيتم', 'ألم تعلم', 'Did you literally see him', 'A form of التعجب on the pattern أفعل به'], correct: 0,
          why: 'It is a request for information about something remarkable, not a question about eyesight.' },
        { t: 'mcq', q: 'What is the كاف in **أرأيتك / أرأيتكم**?', choices: ['كاف الخطاب, added for توكيد الخطاب — the مرفوع pronoun stays fixed as تَ and only the كاف varies', 'A مفعول به pronoun', 'A كاف of comparison', 'A حرف جر attached to the object'], correct: 0,
          why: 'The tell-tale sign: أرأيتكِ، أرأيتكم — the تَ never changes, so it cannot be tracking the addressee.' },
        { t: 'mcq', q: 'What happens when a **قلب** verb is used in a non-قلب sense?', choices: ['It takes only one object — ﴿لا تعلمون شيئا﴾ = لا تعرفون · ظننت زيدا = اتهمته · رأيت زيدا = أبصرته', 'It still takes two objects', 'It becomes a فعل ناقص', 'It becomes intransitive entirely'], correct: 0,
          why: 'The two-object behaviour belongs to the **mental judgement** sense; drop that and the verb reverts to one object.' },
        { t: 'mcq', q: 'Define **أفعال التحويل** and list them (6).', choices: ['Verbs bearing the sense of صيَّر (to transform): صيّر، رد، ترك، تخذ/اتخذ، جعل، وهب', 'Verbs of certainty: وجد، ألفى، رأى، علم، عرف، درى', 'Verbs of commencement: جعل، أخذ، طفق، علق، أنشأ', 'Verbs of hope: عسى، اخلولق، حرى'], correct: 0,
          why: 'Their two objects are also originally مبتدأ وخبر, which is why they are grouped with أفعال القلوب.' },
        { t: 'mcq', q: '﴿وَاتَّخَذَ اللهُ إِبْرَاهِيمَ خَلِيلًا﴾ — classify the verb.', choices: ['فعل تحويل (بمعنى صيّر), with مفعولان: إبراهيم and خليلا', 'فعل قلب of اليقين', 'فعل جارحة', 'A one-object verb meaning “took”'], correct: 0,
          why: 'A real change of state is effected, so تحويل rather than a mere mental judgement.' },
        { t: 'mcq', q: 'What happens when a **تحويل** verb is used in a non-تحويل sense?', choices: ['It takes only one object — ﴿تركت ملة قوم﴾ · ﴿ثم يُرد إلى ربه﴾ = يُصار · ﴿وجعل لكم السمع﴾ = خلق', 'It keeps both objects', 'It becomes ناقصا', 'It requires أن before its second object'], correct: 0,
          why: 'Same principle as the heart-verbs: the extra object rides on the special sense.' },
        { t: 'mcq', q: 'Describe the verb taking **three** objects.', choices: ['It is always a فعل قلب (e.g. أرى); its second and third objects are originally مبتدأ وخبر — ﴿يريهم الله أعمالَهم حسراتٍ عليهم﴾', 'It is always a فعل تحويل', 'It is always a فعل جارحة', 'It may be any transitive verb with a زائدة باء'], correct: 0,
          why: 'The first object is the person made to see; the remaining two are the judgement conveyed to them.' },
        { t: 'mcq', q: 'What may stand in place of (**يسد مسد**) the two objects of a قلب verb?', choices: ['The اسم المؤول (﴿واعلموا أن الله مع المتقين﴾) or a جملة (﴿والله يشهد إن المنافقين لكاذبون﴾)', 'A شبه جملة only', 'A مصدر صريح only', 'Nothing — the two objects are obligatory in form'], correct: 0,
          why: 'This substitution is the doorway to the next topic, التعليق.' },
      ],
    },

    /* ═══ 2. التعليق والإلغاء ═══ */
    {
      id: 'bank-fil-taliq',
      title: 'التعليق والإلغاء',
      steps: [
        { t: 'mcq', q: 'Define **التعليق**.', choices: ['A جملة stands in place of the two objects of a قلب verb, which then operates on it محلا but not لفظا', 'Cancelling the verb’s operation both لفظا and محلا', 'Deleting one of the two objects', 'Fronting the objects before the verb'], correct: 0,
          why: '“Suspension” touches only the **wording**; the clause still occupies the objects’ grammatical position.' },
        { t: 'mcq', q: 'What is the clause standing in place of the suspended verb’s objects called?', choices: ['جملة معلَّق عنها العمل', 'جملة ملغاة', 'جملة معترضة', 'جملة صغرى'], correct: 0,
          why: 'Literally: the clause **from which** the (verbal) operation has been suspended.' },
        { t: 'mcq', q: 'Besides أفعال القلوب, which verbs admit **التعليق**?', choices: ['Verbs resembling them — any verb indicating إخبار or استفهام: ﴿ليبلوكم أيكم أحسن عملا﴾ · ﴿سلهم أيهم بذلك زعيم﴾', 'Only أفعال التحويل', 'Only the أفعال الناقصة', 'No others — التعليق is exclusive to أفعال القلوب'], correct: 0,
          why: 'Informing and asking both involve a mental content, which is what التعليق attaches to.' },
        { t: 'mcq', q: 'Can a verb taking only **one** object be suspended (معلَّقا)?', choices: ['Yes, when the following clause opens with an استفهام — ﴿فلينظر أيها أزكى طعاما﴾', 'No — التعليق needs two objects', 'Yes, but only after a نفي', 'Only if the verb is a فعل قلب'], correct: 0,
          why: 'The interrogative’s claim to first position is what blocks the verb, whatever its object count.' },
        { t: 'mcq', q: 'Which list gives the **معلِّقات** (suspenders of the verb’s wording-level operation)?', choices: ['إنْ النافية · ما النافية · لام الابتداء · اللام المزحلقة · لعل · حرف/اسم الاستفهام · لام جواب القسم', 'حروف الجر · حروف العطف · حروف النداء', 'أن · أنّ · كي · لن · إذن', 'قد · السين · سوف · لم · لن'], correct: 0,
          why: 'Seven items, and the pattern behind them: each has a claim to the head of its clause, so the verb cannot reach past it.' },
        { t: 'mcq', q: '﴿وَسَيَعْلَمُ الَّذِينَ ظَلَمُوا أَيَّ مُنْقَلَبٍ يَنْقَلِبُونَ﴾ — why is أي منقلب not the object of سيعلم?', choices: ['الاستفهام has the right of first position (له صدر الكلام), so nothing before it may govern it — it is منصوب by the following ينقلبون', 'Because سيعلم is ملغى here', 'Because أي is مبني and takes no إعراب', 'Because the جملة is إنشائية'], correct: 0,
          why: 'The interrogative’s صدارة is the engine of the whole التعليق chapter.' },
        { t: 'mcq', q: 'Define **الإلغاء**.', choices: ['Cancelling the operation of the قلب verb both لفظا and محلا', 'Cancelling it لفظا only, keeping the محل', 'Deleting the verb itself', 'Deleting both objects with contextual evidence'], correct: 0,
          why: 'Contrast with التعليق, where the محل survives. Here nothing survives.' },
        { t: 'mcq', q: 'When is **إعمال** of the قلب verb preferred, and when **إلغاء**?', choices: ['إعمال when the verb falls between its two objects (محمداً علمتُ صادقاً) · إلغاء when it comes after them (محمدٌ صادقٌ علمتُ)', 'إعمال when it comes last · إلغاء when it comes first', 'إعمال always · إلغاء never', 'إلغاء when the objects are pronouns · إعمال otherwise'], correct: 0,
          why: 'Position decides: a verb trailing behind its content has already lost its grip on it.' },
      ],
    },

    /* ═══ 3. الأفعال الناقصة ═══ */
    {
      id: 'bank-fil-naqisa',
      title: 'الأفعال الناقصة',
      steps: [
        { t: 'mcq', q: 'Define **السماعي** verb and list its three أقسام.', choices: ['One with no consistent rule, dependent on transmission: الأفعال الناقصة · أفعال المدح والذم · صيغ التعجب', 'One with a consistent rule: اللازم · المتعدي · الجامد', 'One restricted to the ماضي: ليس · ما دام · عسى', 'One that governs nothing: الحرف · الجملة · شبه الجملة'], correct: 0,
          why: 'These three أقسام are the whole remainder of the verb chapter.' },
        { t: 'mcq', q: 'What do the **أفعال الناقصة** do grammatically?', choices: ['Enter on مبتدأ وخبر, putting the first in رفع (اسمها) and the second in نصب (خبرها)', 'Put both their فاعل and مخصوص in رفع', 'Put their فاعل in رفع and their مفاعيل in نصب', 'Put their اسم in نصب and their خبر in رفع'], correct: 0,
          why: 'Careful with the last option — the reversal (نصب the اسم, رفع the خبر) is إنّ وأخواتها, not كان.' },
        { t: 'mcq', q: 'Why is the **فعل ناقص** called “deficient”?', choices: ['Its meaning is incomplete without its خبر — unlike the فعل التام, which is complete with its فاعل alone', 'Because it lacks a ماضي form', 'Because it cannot be conjugated', 'Because it has no فاعل at all'], correct: 0,
          why: 'كان زيدٌ says nothing until the خبر arrives; ضرب زيدٌ already reports an event.' },
        { t: 'mcq', q: 'What are the four **أضرب** of الأفعال الناقصة?', choices: ['كان وأخواتها · أفعال الرجاء · أفعال المقاربة · أفعال الشروع', 'كان وأخواتها · أفعال القلوب · أفعال التحويل · أفعال المدح', 'اليقين · الظن · التحويل · الشروع', 'القياسي · السماعي · الملحق · الجامد'], correct: 0,
          why: 'أفعال القلوب and التحويل belong to the **قياسي** transitive verb, not here.' },
        { t: 'mcq', q: 'How many are **كان وأخواتها**, and which list is right?', choices: ['Thirteen — كان، أصبح، أضحى، أمسى، ظل، بات، صار، ما برح، ما انفك، ما زال، ما فتئ، ما دام، ليس', 'Ten — كان، أصبح، أمسى، ظل، بات، صار، ما زال، ما دام، ليس، عسى', 'Thirteen — the same list with عاد, غدا and راح in place of the ما-verbs', 'Eight — كان، أصبح، أضحى، أمسى، ظل، بات، صار، ليس'], correct: 0,
          why: 'آض، عاد، غدا، راح are counted by **some** as additions — they are not part of the core thirteen.' },
        { t: 'mcq', q: 'Which set of time-meanings does **كان** carry?', choices: ['الماضي المنقطع · الماضي المتجدد · الحال (بمعنى ما زال) · الاستقبال', 'الماضي only', 'الحال and الاستقبال only', 'الماضي and الأمر'], correct: 0,
          why: '﴿وكان الإنسان عجولا﴾ is the present sense; ﴿كانت لهم جنات الفردوس نزلا﴾ the future one.' },
        { t: 'mcq', q: 'What two further meanings can **كان** carry?', choices: ['الانبغاء (﴿ما كان لنا أن نشرك بالله﴾) · القدرة (﴿وما كان لنفس أن تموت إلا بإذن الله﴾)', 'التعجب · الرجاء', 'المقاربة · الشروع', 'المدح · الذم'], correct: 0,
          why: 'Both go beyond tense entirely: “it is not fitting” and “it is not possible”.' },
        { t: 'mcq', q: 'When may the **نون of يكون** be deleted?', choices: ['When مجزوم, not followed by a ساكن, and with no attached نصب pronoun — ﴿لم نكُ من المصلين﴾', 'Whenever it is مجزوم, without further condition', 'Only in poetry', 'Only when followed by a ساكن'], correct: 0,
          why: 'Hence ﴿لم يكن الذين كفروا﴾ (following ساكن) and لم أكنْه (attached pronoun) both keep the نون.' },
        { t: 'mcq', q: 'What nuance does **deleting the نون** of يكن add?', choices: ['تقليل — diminution: ﴿ولم يكُ شيئا﴾', 'توكيد — emphasis', 'استمرار — continuity', 'تعجب — wonder'], correct: 0,
          why: 'A shortened form for a diminished thing — form matching meaning.' },
        { t: 'mcq', q: 'When may **كان together with its اسم** be deleted?', choices: ['After the شرط إن and لو — «التمس ولو خاتماً من حديد» · إن خيراً فخير; occasionally elsewhere: ﴿فآمنوا خيراً لكم﴾', 'Never', 'Only after ليس', 'Only when the خبر is a جملة'], correct: 0,
          why: 'The tell-tale is a bare منصوب after إن/لو with no visible governor.' },
        { t: 'mcq', q: 'What does **أصبح** indicate?', choices: ['The اسم being described by the خبر at morning — ﴿فأصبح في المدينة خائفا يترقب﴾ (غدا can carry the same sense)', 'Mid-morning (الضحى)', 'Evening', 'Night'], correct: 0,
          why: 'The time-verbs each pin the predication to a slice of the day; أصبح takes the morning.' },
        { t: 'mcq', q: 'Match أضحى، أمسى، ظل، بات to their times.', choices: ['أضحى = الضحى (mid-morning) · أمسى = evening · ظل = daytime · بات = night', 'أضحى = morning · أمسى = night · ظل = evening · بات = daytime', 'أضحى = night · أمسى = mid-morning · ظل = morning · بات = evening', 'All four mean simply “became”, with no time'], correct: 0,
          why: '﴿والذين يبيتون لربهم سجدا وقياما﴾ fixes بات to the night.' },
        { t: 'mcq', q: 'What contraction occurs in **ظل**?', choices: ['One of its two لامs is deleted — ﴿ظلت عليه عاكفا﴾ from ظللت', 'Its ظاء is turned into a ضاد', 'Its final لام is doubled', 'Its فاء is dropped in the مضارع'], correct: 0,
          why: 'A relief from the awkward doubled لام before a moving تاء.' },
        { t: 'mcq', q: 'What does **صار** indicate?', choices: ['Transformation — of essence (صار الخمرُ خلاً) or of attributes (صار المذنبُ متقياً)', 'Continuation', 'Negation of the present', 'Nearness of occurrence'], correct: 0,
          why: 'Both grades count as تحول: the thing itself changes, or only its description does.' },
        { t: 'mcq', q: 'Can **كان** and the time-verbs come in the sense of **صار**?', choices: ['Yes — ﴿وكان من الكافرين﴾ · ﴿فأصبحتم بنعمته إخوانا﴾ · ﴿ظل وجهه مسودا﴾', 'No — صار is unique in that sense', 'Only كان can', 'Only أمسى and بات can'], correct: 0,
          why: 'The time element recedes and pure transformation remains.' },
        { t: 'mcq', q: 'Which **other** verbs come in the sense of صار?', choices: ['ارتد (﴿فارتد بصيرا﴾) · عاد (﴿أو لتعودن في ملتنا﴾) · استحال', 'قام · قعد · جلس', 'ظن · حسب · زعم', 'نعم · بئس · ساء'], correct: 0,
          why: 'Each already carries a notion of turning into a new state.' },
        { t: 'mcq', q: 'What do **ما برح، ما انفك، ما زال، ما فتئ** indicate?', choices: ['الاستمرار — continuation: ﴿لن نبرح عليه عاكفين﴾ · ﴿فما زلتم في شك﴾ · ﴿تالله تفتأ تذكر يوسف﴾', 'Transformation', 'Negation of the present', 'Commencement of an act'], correct: 0,
          why: 'Each is a negation of ceasing, so the net sense is “still, continuously”.' },
        { t: 'mcq', q: 'What two restrictions apply to **ما زال** and its three companions?', choices: ['They are ناقص التصرف (ماضٍ and مضارع only) · they work as ناقص only after a نهي, نفي or دعاء', 'They occur only in the ماضي · they need أن in their خبر', 'They must be preceded by قد · their خبر must be a جملة', 'They cannot be تامة · they cannot take a ضمير'], correct: 0,
          why: 'Hence the ما in ما زال is not decoration: without the preceding negation the verb is not one of the sisters.' },
        { t: 'mcq', q: 'When may the **نفي before ما زال** be deleted?', choices: ['After القسم, when the verb is a مضارع negated by لا — يمينُ الله أبرحُ قاعداً (= لا أبرح)', 'Whenever the sentence is a خبر', 'After إن الشرطية', 'Never'], correct: 0,
          why: 'The oath makes the negation recoverable, so the لا may go unsaid.' },
        { t: 'mcq', q: 'Distinguish **زال يزال** from **زال يزول**.', choices: ['زال يزال = the ناقص verb (of ما زال) · زال يزول = a تام verb, مصدر زوال — ﴿أن تزولا﴾', 'They are the same verb with two مضارع forms', 'زال يزال is تام · زال يزول is ناقص', 'زال يزول means “to continue” and زال يزال means “to cease”'], correct: 0,
          why: 'Two distinct roots that collapse in the ماضي — the مضارع is what separates them.' },
        { t: 'mcq', q: 'What does **ما دام** indicate?', choices: ['Delimiting what precedes it by the duration of the predication — ﴿وأوصاني بالصلاة والزكاة ما دمت حيا﴾', 'Continuation without limit', 'Negation of the present', 'Transformation'], correct: 0,
          why: '“For as long as”: the earlier clause is bounded by the ما دام clause.' },
        { t: 'mcq', q: 'Can **ما alone** stand in place of ما دام?', choices: ['Yes — «والله في عون العبد ما كان العبد في عون أخيه», frequently before لم: «ما لم يعجل»', 'No', 'Only in the Qurʾān', 'Only if دام is understood as an أمر'], correct: 0,
          why: 'The ما المصدرية الظرفية already carries the “as long as” sense on its own.' },
        { t: 'mcq', q: 'What does **ليس** indicate?', choices: ['نفي الحال — negation of the present: ﴿ليس عليك هداهم﴾', 'نفي الماضي', 'نفي الاستقبال', 'الاستمرار'], correct: 0,
          why: 'Its default reach is the present moment, whatever context may add.' },
        { t: 'mcq', q: 'Which of the sisters are **completely غير متصرف**?', choices: ['ما دام and ليس — the ماضي form only', 'ليس and ما زال', 'ما دام and ما فتئ', 'كان and صار'], correct: 0,
          why: 'ما زال and company are **ناقص** التصرف (two forms); these two are frozen entirely.' },
        { t: 'mcq', q: 'Which sisters can **never** be تامة?', choices: ['ما زال، ما فتئ، ليس', 'ما دام، ليس', 'كان، صار، أصبح', 'None — all can be تامة'], correct: 0,
          why: 'The تام use means “sufficing with its فاعل” — ﴿حين تمسون وحين تصبحون﴾, ﴿ما دامت السموات والأرض﴾.' },
        { t: 'mcq', q: 'May the **خبر** of a ناقص verb come between the verb and its اسم?', choices: ['Yes — ﴿كان حقاً علينا نصرُ المؤمنين﴾', 'No, never', 'Only if the خبر is a شبه جملة', 'Only if the اسم is a pronoun'], correct: 0,
          why: 'حقاً is the fronted خبر; نصرُ المؤمنين, arriving last, is the اسم.' },
        { t: 'mcq', q: 'May the **معمول of the خبر** precede the ناقص verb itself?', choices: ['Yes — ﴿أهؤلاء إياكم كانوا يعبدون﴾', 'No', 'Only with ليس', 'Only when the خبر is deleted'], correct: 0,
          why: 'إياكم is the object of يعبدون, yet it has run ahead of كانوا.' },
        { t: 'mcq', q: 'Which four verbs do **some** count among the أفعال الناقصة in addition?', choices: ['آض، عاد، غدا، راح', 'ظن، حسب، زعم، خال', 'جعل، أخذ، طفق، أنشأ', 'نعم، بئس، ساء، حبذا'], correct: 0,
          why: 'Each can carry the sense of “became”, which is why the addition is arguable.' },
      ],
    },

    /* ═══ 4. أفعال الرجاء والمقاربة والشروع ═══ */
    {
      id: 'bank-fil-raja',
      title: 'أفعال الرجاء والمقاربة والشروع',
      steps: [
        { t: 'mcq', q: 'What are the **أفعال الرجاء** and what do they express?', choices: ['عسى، اخلولق، حرى — hope (الرجاء): ﴿عسى أن ينفعنا أو نتخذه ولدا﴾', 'كاد، كرب، أوشك — nearness', 'جعل، أخذ، طفق — commencement', 'نعم، بئس، ساء — praise and blame'], correct: 0,
          why: 'Three verbs only, and عسى is by far the most used.' },
        { t: 'mcq', q: 'Which three meanings does **عسى** carry?', choices: ['الترجي in what is loved · الإشفاق from what is disliked · التعليل', 'الترجي · التوكيد · التعجب', 'المقاربة · الشروع · الاستمرار', 'اليقين · الظن · التحويل'], correct: 0,
          why: '﴿فهل عسيتم إن توليتم أن تفسدوا في الأرض﴾ is the إشفاق (dread) case, not hope.' },
        { t: 'mcq', q: 'What separates **عسى** from **لعل**?', choices: ['عسى carries المقاربة (nearness of occurrence); لعل does not', 'لعل is a verb, عسى a particle', 'عسى expresses dread only', 'لعل governs نصب, عسى does not govern at all'], correct: 0,
          why: 'Both express hope, but عسى adds that the thing is close at hand.' },
        { t: 'mcq', q: 'What is the predominant sense of **عسى when attributed to Allah**?', choices: ['Certainty (اليقين) — the “hope” is on the addressee’s side: ﴿عسى أن يبعثك ربك مقاما محمودا﴾', 'Mere possibility', 'Dread (الإشفاق)', 'Causation (التعليل)'], correct: 0,
          why: 'Hope implies uncertainty, which cannot attach to God — so the word is read as a promise.' },
        { t: 'mcq', q: 'What do **اخلولق** and **حرى** mean?', choices: ['اخلولق = صار خليقا (became apt) · حرى = صار حريا (became worthy)', 'اخلولق = became distant · حرى = became near', 'Both mean “nearly happened”', 'Both mean “began”'], correct: 0,
          why: 'Both report fitness for the thing hoped for rather than the hope itself.' },
        { t: 'mcq', q: 'What is the rule for **أن** in the خبر of the أفعال الرجاء?', choices: ['Frequent (يكثر) with عسى · obligatory (يجب) with اخلولق and حرى', 'Obligatory with all three', 'Forbidden with all three', 'Obligatory with عسى · forbidden with the other two'], correct: 0,
          why: 'Note the three grades used across this whole chapter: يكثر · يقل · يجب.' },
        { t: 'mcq', q: 'Can the **أفعال الرجاء be تامة**?', choices: ['Yes — ﴿عسى أن يبعثك ربك مقاما محمودا﴾, with the اسم مؤول as فاعل', 'No, never', 'Only اخلولق can', 'Only in the مضارع'], correct: 0,
          why: 'With the مؤول noun serving as فاعل, no خبر is needed and the verb is complete.' },
        { t: 'mcq', q: 'What are the **أفعال المقاربة** and what do they express?', choices: ['كاد، كرب، أوشك — nearness of the خبر’s occurrence: ﴿وكادوا يقتلونني﴾', 'عسى، اخلولق، حرى — hope', 'جعل، أخذ، طفق، علق، أنشأ — commencement', 'صيّر، رد، ترك — transformation'], correct: 0,
          why: 'Nearness, not hope and not beginning: the act almost happened.' },
        { t: 'mcq', q: 'Both عسى and كاد include المقاربة — how do they differ?', choices: ['عسى indicates it على سبيل الرجاء (by way of hope) · كاد and its sisters على سبيل الحصول (by actual approach to occurrence)', 'عسى is nearer than كاد', 'كاد expresses hope, عسى certainty', 'There is no difference'], correct: 0,
          why: 'One is an attitude toward the event, the other a fact about how close it came.' },
        { t: 'mcq', q: 'What does **affirmed كاد** indicate, versus **negated كاد**?', choices: ['Affirmed: the act did not occur but came close (﴿وكادوا يقتلونني﴾) · negated: it did not occur and did not even come close — a stronger negation (﴿ولا يكاد يسيغه﴾)', 'Affirmed: the act occurred · negated: it nearly occurred', 'Both mean the act occurred', 'Both mean the act was hoped for'], correct: 0,
          why: 'The famous inversion: negating كاد negates the nearness itself, not just the act.' },
        { t: 'mcq', q: 'What is the rule for **أن** in the خبر of أفعال المقاربة?', choices: ['Frequent (يكثر) with أوشك · rare (يقل) with كاد and كرب', 'Obligatory with all three', 'Forbidden with all three', 'Frequent with كاد · rare with أوشك'], correct: 0,
          why: 'And the reason is the next question — أن points to the future.' },
        { t: 'mcq', q: 'Why does **أن** suit the أفعال الرجاء and أوشك but not كاد and كرب?', choices: ['أن indicates the future; الرجاء verbs and أوشك are far from occurrence, so it fits — كاد and كرب are close to occurrence', 'Because كاد and كرب are غير متصرف', 'Because أن cannot follow a ماضي', 'Because كاد and كرب already contain أن in meaning'], correct: 0,
          why: 'A neat semantic fit: distance in time calls for the futurity marker.' },
        { t: 'mcq', q: 'May the **خبر of أفعال المقاربة** be deleted?', choices: ['Yes, when context supplies it — من عجل أخطأ أو كاد (i.e. أو كاد يخطئ)', 'No, never', 'Only with أوشك', 'Only if أن is present'], correct: 0,
          why: 'The preceding clause already names the act, so repeating it would be redundant.' },
        { t: 'mcq', q: 'What is the **تصرف** of أفعال الرجاء والمقاربة?', choices: ['ناقص التصرف, confined to the ماضي — except كاد (﴿يكاد البرق يخطف أبصارهم﴾) and أوشك («يوشك أن يعمهم الله بعقاب»), which have مضارع forms', 'Fully متصرفة', 'Confined to the مضارع', 'Confined to the أمر'], correct: 0,
          why: 'Two exceptions worth memorising, both attested in Qurʾān and ḥadīth.' },
        { t: 'mcq', q: 'What are the **أفعال الشروع** and what do they express?', choices: ['جعل، أخذ، طفق، علق، أنشأ — commencement of the act: ﴿وطفقا يخصفان عليهما من ورق الجنة﴾', 'كاد، كرب، أوشك — nearness', 'عسى، اخلولق، حرى — hope', 'صيّر، رد، ترك، جعل — transformation'], correct: 0,
          why: 'جعل appears here too — in yet another sense (“set about doing”).' },
        { t: 'mcq', q: 'Are the **أفعال الشروع** genuinely سماعية?', choices: ['No — they are قياسية, listed with the سماعي verbs only because they resemble the أفعال الناقصة in operation', 'Yes, entirely سماعية', 'Half of them are سماعية', 'They are neither — they do not govern'], correct: 0,
          why: 'A placement of convenience, worth noticing so the classification is not misread.' },
        { t: 'mcq', q: 'What two restrictions bind the **أفعال الشروع**?', choices: ['They occur in the ماضي only · their خبر must be a جملة فعلية with a مضارع stripped of أن', 'They occur in the مضارع only · their خبر must contain أن', 'They must follow a نفي · they cannot be تامة', 'They take two objects · they cannot be deleted'], correct: 0,
          why: 'أن would push the act into the future, contradicting the very idea of having **started**.' },
        { t: 'mcq', q: 'What umbrella name is sometimes given to عسى وأخواتها, كاد وأخواتها and طفق وأخواتها together?', choices: ['أفعال المقاربة', 'أفعال الناسخة', 'أفعال القلوب', 'أفعال التحويل'], correct: 0,
          why: 'The name of one sub-group is stretched to cover all three — a common source of confusion.' },
      ],
    },

    /* ═══ 5. أفعال المدح والذم ═══ */
    {
      id: 'bank-fil-madh',
      title: 'أفعال المدح والذم',
      steps: [
        { t: 'mcq', q: 'What do **أفعال المدح والذم** do grammatically?', choices: ['They express praise or blame and put **both** their فاعل and their مخصوص in رفع', 'They put the فاعل in رفع and the مخصوص in نصب', 'They put their اسم in رفع and their خبر in نصب', 'They govern nothing'], correct: 0,
          why: 'Two مرفوعات in one clause is the signature of this construction.' },
        { t: 'mcq', q: 'List the five **أفعال المدح والذم**.', choices: ['نعم · حبذا · بئس · ساء · لا حبذا', 'نعم · بئس · ساء · كبر · حسن', 'نعم · بئس · عسى · كاد · طفق', 'حبذا · لا حبذا · نعم · بئس · أفعل به'], correct: 0,
          why: 'Praise: نعم، حبذا. Blame: بئس، ساء، لا حبذا.' },
        { t: 'mcq', q: 'Are the **أفعال المدح والذم** متصرفة?', choices: ['No — غير متصرفة; only the تاء may attach: نعمت، ساءت', 'Yes, fully', 'Only نعم and بئس are', 'They have ماضٍ and مضارع only'], correct: 0,
          why: 'Frozen verbs: no مضارع, no أمر, only the feminine tāʾ.' },
        { t: 'mcq', q: 'What is **annexed (ملحق)** to the أفعال المدح والذم?', choices: ['Any verb on the pattern فعُل — originally so (﴿وحسنت مرتفقا﴾) or converted to it (كتُب زيدٌ = what a writer!)', 'Any verb taking two objects', 'Any فعل ناقص', 'Any verb preceded by ما التعجبية'], correct: 0,
          why: 'The فعُل pattern itself carries an inherent sense of appraisal.' },
        { t: 'mcq', q: 'When is **تأنيث** of أفعال المدح والذم permitted?', choices: ['When the فاعل is feminine (نعم/نعمت المرأة فاطمة) or when the مخصوص is feminine (نعمت جزاء المتقين الجنة)', 'Only when the فاعل is feminine', 'Only when the مخصوص is feminine', 'Never'], correct: 0,
          why: 'Either of the two مرفوعات can trigger it — which is why both cases are listed.' },
        { t: 'mcq', q: 'What are the three permitted forms of the **فاعل of نعم and بئس**?', choices: ['A noun with لام الجنس (﴿نعم العبد﴾) · a noun annexed to such (﴿نعم أجر العاملين﴾) · a ضمير مستتر explained by a تمييز (﴿وساءت مصيرا﴾)', 'A pronoun · a proper name · a demonstrative', 'A مصدر · an اسم فاعل · an اسم مفعول', 'Only a noun with أل'], correct: 0,
          why: 'The third is the trickiest: the visible منصوب is a تمييز, not the فاعل itself.' },
        { t: 'mcq', q: 'What may occur immediately after نعم and بئس in place of the usual فاعل?', choices: ['The word ما — ﴿إن تبدوا الصدقات فنعمّا هي﴾', 'The word من', 'A حرف جر', 'A جملة فعلية'], correct: 0,
          why: 'فنعمّا = فنعم ما: the ما stands in for the generic subject of praise.' },
        { t: 'mcq', q: 'When may the **مخصوص** be deleted?', choices: ['When the context indicates it — ﴿نعم المولى ونعم النصير﴾ (i.e. هو)', 'Never', 'Always, obligatorily', 'Only after حبذا'], correct: 0,
          why: 'The preceding verse names Allah, so the specified subject need not be repeated.' },
        { t: 'mcq', q: 'A **منصوب** appears before or after the مخصوص of حبذا — how is it parsed?', choices: ['حال if مشتق (حبذا راكباً زيدٌ) · تمييز if جامد (حبذا رجلاً زيدٌ)', 'Always a حال', 'Always a تمييز', 'مفعول به in both cases'], correct: 0,
          why: 'Derived vs frozen is the deciding test — the same test used across the منصوبات.' },
        { t: 'mcq', q: 'How else can the **تمييز of حبذا** be expressed?', choices: ['With the حرف جر من — حبذا زينب من معلمة', 'With أل', 'With the باء', 'With إضافة to the مخصوص'], correct: 0,
          why: 'مِن التبيينية does the same work the منصوب تمييز would do.' },
        { t: 'mcq', q: 'Can **يا** enter upon حبذا?', choices: ['Yes, upon حب — يا حبذا محمد من جار', 'No', 'Only upon لا حبذا', 'Only if the مخصوص is deleted'], correct: 0,
          why: 'The يا intensifies rather than genuinely calls.' },
        { t: 'mcq', q: 'What is the rule for **ذا after حب**?', choices: ['It stays invariably singular masculine regardless of the مخصوص — حبذا رجالاً الأنصار · حبذا بنتاً فاطمة', 'It agrees with the مخصوص in gender and number', 'It agrees in gender only', 'It agrees in number only'], correct: 0,
          why: 'حبذا has fused into a fixed formula, so ذا no longer behaves as a live demonstrative.' },
      ],
    },

    /* ═══ 6. صيغ التعجب ═══ */
    {
      id: 'bank-fil-tajub',
      title: 'صيغ التعجب',
      steps: [
        { t: 'mcq', q: 'What are **صيغ التعجب** and what are their two أضرب?', choices: ['Forms expressing wonder: قياسي and سماعي', 'Forms expressing praise: مدح and ذم', 'Forms expressing nearness: مقاربة and شروع', 'Forms expressing hope: رجاء and ترجي'], correct: 0,
          why: 'Same قياسي/سماعي split that organised the whole verb chapter.' },
        { t: 'mcq', q: 'What are the three **قياسي** forms of التعجب?', choices: ['ما أفعله (﴿فما أصبرهم على النار﴾) · أفعل به (﴿أسمع بهم وأبصر﴾) · فعُل (﴿كبرت كلمة تخرج من أفواههم﴾)', 'سبحان الله · الاستفهام · النداء', 'نعم · بئس · حبذا', 'عسى · كاد · طفق'], correct: 0,
          why: 'The second list is the **سماعي** set — a favourite swap in exam questions.' },
        { t: 'mcq', q: 'What are the two views on **ما in ما أفعله**?', choices: ['That it is استفهامية · that it is نكرة موصوفة meaning شيء عظيم', 'That it is نافية · that it is موصولة', 'That it is زائدة · that it is كافة', 'That it is شرطية · that it is مصدرية'], correct: 0,
          why: 'On the second reading ما أصبره ≈ “something tremendous made him patient”.' },
        { t: 'mcq', q: 'Explain the derivation of **أفعِلْ به**.', choices: ['Its origin is the ماضي أفعَلَ, recast in the أمر form; the باء was then added to the فاعل, since attaching a فعل أمر to an overt فاعل is قبيح', 'It is an original أمر form with a زائدة باء for emphasis only', 'It is derived from the مضارع', 'It is a frozen expression with no derivation'], correct: 0,
          why: 'The باء is there to smooth an ungrammatical pairing, not to add meaning.' },
        { t: 'mcq', q: 'What happens to verbs whose **فاعل takes a زائدة باء**?', choices: ['The sense of التعجب seeps into them (يتشرب) — ﴿وكفى بنا حاسبين﴾ · بحسبك زيد', 'They become intransitive', 'They lose their فاعل entirely', 'They become غير متصرف'], correct: 0,
          why: 'A borrowed flavour from أفعل به, whose باء is the same device.' },
        { t: 'mcq', q: 'May the باء enter the فاعل of the **فعُل** pattern of wonder?', choices: ['Yes — حسُن بزيد', 'No', 'Only in the Qurʾān', 'Only if the verb is converted to فعُل rather than original'], correct: 0,
          why: 'The فعُل appraisal pattern accepts the same زائدة باء.' },
        { t: 'mcq', q: 'From which verbs may **صيغ التعجب** be formed?', choices: ['Only from the فعل ثلاثي مجرد', 'From any verb whatever', 'Only from the رباعي', 'Only from the مزيد فيه'], correct: 0,
          why: 'The tight templates ما أفعله / أفعل به have no room for augmentation.' },
        { t: 'mcq', q: 'What is the rule on **إعلال of the عين** in صيغ التعجب?', choices: ['It is not permitted — ما أطوله وأطول به, not ما أطاله nor أطل به', 'It is obligatory', 'It is permitted optionally', 'It applies only to أفعل به'], correct: 0,
          why: 'The form is preserved intact so the template stays recognisable.' },
        { t: 'mcq', q: 'What is the rule on **إدغام in أفعل به**?', choices: ['No إدغام — أبرِرْ به, unlike ما أفعله where it occurs: ما أبرّه', 'إدغام is obligatory in both', 'إدغام is forbidden in both', 'إدغام is optional in أفعل به'], correct: 0,
          why: 'The أمر shape blocks the merger; the ما أفعله shape allows it.' },
        { t: 'mcq', q: 'Which are the **سماعي** expressions of التعجب mentioned?', choices: ['سبحان الله (﴿قال سبحانك…﴾) · الاستفهام (﴿كيف تكفرون بالله﴾) · النداء (﴿يا بشرى هذا غلام﴾)', 'ما أفعله · أفعل به · فعُل', 'نعم · بئس · حبذا', 'كاد · أوشك · طفق'], correct: 0,
          why: 'Three ordinary constructions pressed into service for wonder, by transmission rather than rule.' },
      ],
    },
  ],
});
