/* ── Daram Bomb Game — extra bank · Chapter A7: الْمَعْمُولُ وَغَيْرُ الْمَعْمُولِ ──
   Anki sub-decks 3.01–3.20 turned into MCQs. Game-only; conventions as in
   1-muqaddimah.js (correct:0, game.js shuffles the choices at render).      */

window.DARAM_COURSES = window.DARAM_COURSES || [];

window.DARAM_COURSES.push({
  id: 'bank-mamul',
  num: 'A7',
  titleAr: 'الْمَعْمُولُ وَغَيْرُ الْمَعْمُولِ',
  titleEn: 'Bank — The governed and the ungoverned',
  sections: [

    /* ═══ 01. مقدمة ═══ */
    {
      id: 'bank-mm-muq',
      title: 'المعمول وغير المعمول — مقدمة',
      steps: [
        { t: 'mcq', q: 'What are the five **مسائل** of the introduction to المعمول?', choices: ['Nouns: some معمول, some not · verbs: likewise · clauses: likewise · أشباه الجمل: **all** معمول · حروف: **all** غير معمول', 'All five categories are partly معمول', 'Nouns and verbs are entirely معمول; the rest are not', 'Only nouns can be معمول'], correct: 0,
          why: 'Three partials and two absolutes — the two absolutes are the ones to memorise.' },
        { t: 'mcq', q: 'Which category is **entirely معمول**, and which **entirely غير معمول**?', choices: ['شبه الجملة is entirely معمول · الحروف are entirely غير معمول', 'The reverse', 'Both are entirely معمول', 'Both are entirely غير معمول'], correct: 0,
          why: 'Quasi-clauses always occupy a slot; particles never take a case.' },
        { t: 'mcq', q: 'What are the two kinds of **اسم** here?', choices: ['الصريح (the noun itself: الصوم) and المؤول (a حرف مصدري plus its clause: أن تصوموا)', 'المعرفة and النكرة', 'الجامد and المشتق', 'المفرد and المركب'], correct: 0,
          why: 'The same division opened the whole book in the المقدمة.' },
        { t: 'mcq', q: 'Define **المعمول بالأصالة**.', choices: ['That in which the عامل operates directly, without an intermediary', 'That in which the عامل operates through its متبوع', 'That which governs but is not governed', 'That which has no محل من الإعراب'], correct: 0,
          why: 'Direct governance — as against the تابع, which is governed second-hand.' },
        { t: 'mcq', q: 'Define **المعمول بالتبعية**, and what is it called?', choices: ['That in which the عامل operates through its متبوع — it is called a تابع (pl. توابع)', 'That governed directly — called أصل', 'That which governs nothing — called عاطل', 'That with no محل — called مستأنفة'], correct: 0,
          why: 'Five kinds of تابع follow later in this chapter.' },
        { t: 'mcq', q: 'Into how many أقسام does the noun’s **معمول بالأصالة** divide, and with how many members?', choices: ['Three — المرفوع (8), المنصوب (12), المجرور (2)', 'Three — 8, 8, 4', 'Two — المرفوع (8) and المنصوب (12)', 'Four, adding المجزوم'], correct: 0,
          why: 'Twenty-two positions in all; jazm belongs to verbs, not nouns.' },
        { t: 'mcq', q: 'Which list gives the eight **المرفوعات**?', choices: ['الفاعل · نائب الفاعل · المبتدأ · الخبر · اسم الأفعال الناقصة · اسم الحروف المشبهة بليس · خبر الحروف المشبهة بالفعل · خبر لا لنفي الجنس', 'الفاعل · نائب الفاعل · المبتدأ · الخبر · اسم إنّ · خبر كان · اسم لا · التمييز', 'المفعولات الخمسة · الحال · التمييز · المستثنى', 'المجرور بالحرف · المجرور بالإضافة'], correct: 0,
          why: 'Note the mirror: it is the **اسم** of كان and ليس-likes but the **خبر** of إنّ-likes and لا.' },
        { t: 'mcq', q: 'How many **المنصوبات** are there?', choices: ['Twelve — the five مفاعيل، الحال، التمييز، المستثنى، خبر الناقصة، خبر المشبهة بليس، اسم المشبهة بالفعل، اسم لا لنفي الجنس', 'Eight', 'Ten', 'Fourteen'], correct: 0,
          why: 'Five objects plus three free منصوبات plus four ناسخ-related positions.' },
        { t: 'mcq', q: 'What are the two **المجرورات**?', choices: ['المجرور بحرف الجر · المجرور بالإضافة', 'المجرور بالتبعية · المجرور بالأصالة', 'التمييز · المستثنى', 'المضاف · المضاف إليه'], correct: 0,
          why: 'Only two ways for a noun to be lowered.' },
      ],
    },

    /* ═══ 02. الفاعل ونائب الفاعل ═══ */
    {
      id: 'bank-mm-fail',
      title: 'الفاعل ونائب الفاعل',
      steps: [
        { t: 'mcq', q: 'Define the **فاعل**.', choices: ['That to which a complete active verb (﴿فقست قلوبُهم﴾) — or something with such a verb’s meaning (﴿والقاسيةِ قلوبُهم﴾) — is attributed', 'That upon which the action falls', 'That to which a passive verb is attributed', 'The first noun after a ناسخ'], correct: 0,
          why: 'Note “complete” — a فعل ناقص has an اسم, not a فاعل.' },
        { t: 'mcq', q: 'In what three ways may the فاعل be **مجرورا لفظا** while مرفوع محلا?', choices: ['By إضافة to its مصدر (﴿كذكرِكم آباءَكم﴾) · by a redundant مِن (﴿ما جاءنا من بشيرٍ﴾) · by a redundant باء (﴿وكفى باللهِ وكيلا﴾)', 'By a حرف جر أصلي only', 'By إضافة only', 'It can never be مجرورا'], correct: 0,
          why: 'Two of the three involve a redundant preposition, whose جر is only skin-deep.' },
        { t: 'mcq', q: 'Parse **بالله** in ﴿وَكَفَىٰ بِاللهِ وَكِيلًا﴾.', choices: ['الله is the فاعل of كفى — مجرور لفظا by the redundant باء, مرفوع محلا', 'It is a مفعول به', 'It is a تمييز', 'It is a حال'], correct: 0,
          why: 'وكيلا is the تمييز; the divine name is the agent of “sufficing”.' },
        { t: 'mcq', q: 'What is the **default order** of فاعل and مفعول به?', choices: ['The فاعل precedes — ﴿وورث سليمانُ داوودَ﴾', 'The مفعول precedes', 'Either, with no default', 'The مفعول must always precede'], correct: 0,
          why: 'Departures from it need a licence, which the next questions supply.' },
        { t: 'mcq', q: 'When is it **obligatory** to put the فاعل before the مفعول به?', choices: ['When otherwise a detached pronoun would be needed where attachment is possible (ضربتُ زيدا, not ضرب زيدا أنا) · and when ambiguity would result with no case marks (زار موسى عيسى)', 'Whenever the object is definite', 'Whenever the verb is transitive', 'It is never obligatory'], correct: 0,
          why: 'Both reasons are practical: avoid a clumsy pronoun, avoid an unreadable sentence.' },
        { t: 'mcq', q: 'When is the ambiguous **زار موسى عيسى** order nonetheless allowed?', choices: ['When a قرينة resolves it — معنوية (أكل الكمثرى موسى) or لفظية (نصرتْ موسى سلمى)', 'Never', 'Always', 'Only in poetry'], correct: 0,
          why: 'A pear cannot eat; a feminine verb ending points to سلمى.' },
        { t: 'mcq', q: 'Do these ordering rules apply to the **اسم of كان** and its sisters?', choices: ['Yes — ﴿فما زالت تلك دعواهم﴾', 'No', 'Only to كان itself', 'Only in the negative'], correct: 0,
          why: 'The اسم/خبر pair behaves like فاعل/مفعول for ordering purposes.' },
        { t: 'mcq', q: 'Give a Qurʾānic example of the مفعول به **permissibly** preceding the فاعل.', choices: ['﴿ولقد جاء آلَ فرعونَ النذرُ﴾', '﴿وإذ ابتلى إبراهيمَ ربُّه﴾', '﴿لعنهم اللهُ﴾', '﴿فأيَّ آيات الله تنكرون﴾'], correct: 0,
          why: 'The other three are cases where it is **obligatory**, not merely permitted.' },
        { t: 'mcq', q: 'When **must** the مفعول به precede the فاعل?', choices: ['When a pronoun in the فاعل refers to the object (﴿وإذ ابتلى إبراهيمَ ربُّه﴾) · when the object is an attached pronoun (﴿لعنهم اللهُ﴾) · when the object demands صدر الكلام (﴿فأيَّ آيات الله تنكرون﴾)', 'When the object is definite', 'When the verb is passive', 'It is never obligatory'], correct: 0,
          why: 'The first avoids الإضمار قبل الذكر — a pronoun preceding what it refers to.' },
        { t: 'mcq', q: 'Define **نائب الفاعل**.', choices: ['That to which a complete passive verb (﴿وجُمع الشمسُ والقمر﴾) — or its equivalent in meaning (﴿ذلك يومٌ مجموعٌ له الناسُ﴾) — is attributed', 'That to which an active verb is attributed', 'That upon which the action falls', 'The noun after a ناسخ'], correct: 0,
          why: 'Exact parallel to the فاعل definition, with “passive” in place of “active”.' },
        { t: 'mcq', q: 'Can a **شبه جملة** serve as نائب الفاعل?', choices: ['Yes — ﴿وجيء يومئذ بجهنمَ﴾, where the جار ومجرور stands as نائب الفاعل', 'No', 'Only a ظرف can', 'Only in poetry'], correct: 0,
          why: 'The one position in which a quasi-clause is مرفوع محلا.' },
      ],
    },

    /* ═══ 03. المبتدأ ═══ */
    {
      id: 'bank-mm-mubtada',
      title: 'المبتدأ',
      steps: [
        { t: 'mcq', q: 'What are the two kinds of **مبتدأ**?', choices: ['A noun stripped of any لفظي governor and predicated about (﴿محمدٌ رسول الله﴾) · a governing noun raising an overt noun after a نفي or استفهام (﴿أراغبٌ أنت عن آلهتي﴾)', 'A definite noun and an indefinite noun', 'A noun and a clause', 'A مشتق and a جامد'], correct: 0,
          why: 'The second type is the one that needs no خبر at all.' },
        { t: 'mcq', q: 'What is the **مبتدأ المكتفي بمرفوعه**?', choices: ['The governing-noun type that suffices with its مرفوع and takes no خبر — أراغبٌ أنت', 'A مبتدأ whose خبر is deleted', 'A مبتدأ that is indefinite', 'A مبتدأ preceded by لام الابتداء'], correct: 0,
          why: 'Its مرفوع does the predicate’s work, so no separate خبر is needed.' },
        { t: 'mcq', q: 'Which **لام** may enter upon the مبتدأ?', choices: ['لام الابتداء — ﴿ولَعبدٌ مؤمن خير من مشرك﴾', 'لام الجحود', 'لام التقوية', 'لام العاقبة'], correct: 0,
          why: 'The same lām that, pushed off by إنّ, becomes the المزحلقة.' },
        { t: 'mcq', q: 'What is the **default definiteness** of the مبتدأ, and when may it be indefinite?', choices: ['Default معرفة; a نكرة is allowed only if informative — by being specified (مخصوصة) or general (عام), etc.', 'Default نكرة; a معرفة needs a justifier', 'Either freely', 'It must always be معرفة'], correct: 0,
          why: 'An unspecified indefinite subject conveys nothing worth predicating about.' },
        { t: 'mcq', q: 'How can an indefinite مبتدأ be **specified by إضافة**?', choices: ['لفظا («خمسُ صلواتٍ كتبهن الله») or تقديرا (﴿كلٌّ يعمل على شاكلته﴾ = كل أحد)', 'Only لفظا', 'Only تقديرا', 'It cannot be'], correct: 0,
          why: 'Even a **notional** annexation is enough to license it.' },
        { t: 'mcq', q: 'How can an indefinite مبتدأ be **specified by description**?', choices: ['لفظا (﴿ولَعبدٌ مؤمنٌ خير من مشرك﴾) or تقديرا (﴿وطائفةٌ قد أهمتهم أنفسُهم﴾ = طائفة منهم)', 'Only لفظا', 'Only تقديرا', 'It cannot be'], correct: 0,
          why: 'Same two grades as with إضافة.' },
        { t: 'mcq', q: 'When is a **general (عام)** indefinite allowed as مبتدأ?', choices: ['After a negation (ما أحدٌ خيرا من أحد إلا بالتقوى) or a question (﴿أإلهٌ مع الله﴾)', 'After a command', 'After a conditional', 'Never'], correct: 0,
          why: 'Negation and interrogation confer generality, which supplies the needed benefit.' },
        { t: 'mcq', q: 'Besides specification and generality, when else may the مبتدأ be indefinite?', choices: ['When its خبر is a preceding شبه جملة (﴿وفوق كل ذي علم عليمٌ﴾) · after إذا الفجائية («فإذا رجلٌ قاعد») · when it is a supplication (﴿سلامٌ عليكم﴾، ﴿ويلٌ لكل همزة﴾)', 'Only when definite in meaning', 'Only in poetry', 'There are no further cases'], correct: 0,
          why: 'Three further licences, each with its own logic.' },
        { t: 'mcq', q: 'Give an example of **permissible deletion** of the مبتدأ.', choices: ['Saying رسولُنا in answer to من محمد ﷺ؟ — i.e. هو رسولنا', '﴿فصبرٌ جميل﴾', 'نعم الطالب المجتهدُ', 'الحمد لله الحميدُ'], correct: 0,
          why: 'The other three are cases of **obligatory** deletion.' },
        { t: 'mcq', q: 'Where is deletion of the مبتدأ **frequent**?', choices: ['After فاء الجواب (﴿من عمل صالحا فلنفسه﴾ = فعملُه لنفسه) and after القول (﴿وقالوا أساطيرُ الأولين﴾ = هي أساطير)', 'After a negation and a question', 'Before a نعت مقطوع', 'After لولا'], correct: 0,
          why: 'Frequent, not obligatory — a middle grade between the two extremes.' },
        { t: 'mcq', q: 'In which four places is deletion of the مبتدأ **obligatory**?', choices: ['Before a نعت مقطوع to رفع (الحمد لله الحميدُ) · when the جواب القسم indicates it (في ذمتي لأقولنَّ الصدق) · when the خبر is a مصدر standing in for its verb (﴿فصبرٌ جميل﴾) · when the خبر is the مخصوص of praise/blame (نعم الطالب المجتهدُ)', 'After فاء الجواب and after القول', 'After a question and a negation', 'There are no obligatory cases'], correct: 0,
          why: 'Four fixed constructions where restoring the subject would spoil the idiom.' },
      ],
    },

    /* ═══ 04. الخبر ═══ */
    {
      id: 'bank-mm-khabar',
      title: 'الخبر',
      steps: [
        { t: 'mcq', q: 'Define the **خبر**.', choices: ['That which is predicated of the مبتدأ — ﴿محمد رسولُ الله﴾', 'That which is predicated about', 'That which governs the مبتدأ', 'The second noun after a ناسخ'], correct: 0,
          why: 'The مسند, in the terminology of the المقدمة.' },
        { t: 'mcq', q: 'Can the خبر be **multiple**?', choices: ['Yes — ﴿وهو الغفورُ الودودُ﴾', 'No', 'Only if joined by a coordinator', 'Only in poetry'], correct: 0,
          why: 'Two predicates for one subject, with no conjunction needed.' },
        { t: 'mcq', q: 'What is the **default order** of مبتدأ and خبر?', choices: ['The خبر follows the مبتدأ, but may precede it — ﴿لنا أعمالُنا﴾', 'The خبر must always follow', 'The خبر must always precede', 'There is no default'], correct: 0,
          why: 'Fronting is common when the خبر is a شبه جملة.' },
        { t: 'mcq', q: 'In which three cases is deletion of the **خبر obligatory**?', choices: ['When the جواب القسم indicates it (﴿لَعمرُك إنهم لفي سكرتهم يعمهون﴾) · after لولا (﴿ولولا رهطُك لرجمناك﴾) · when the مبتدأ has a conjunct joined by an explicit واو المعية (﴿فإنكم وما تعبدون…﴾)', 'After a question and after إذا الفجائية', 'After فاء الجواب and after القول', 'It is never obligatory'], correct: 0,
          why: 'لولا is the easiest to remember: its predicate is always the understood موجود.' },
        { t: 'mcq', q: 'Where is deletion of the خبر **permissible** with an indicator?', choices: ['In answer to a question (﴿ليقولن اللهُ﴾) and after إذا الفجائية (خرجت فإذا الأسدُ)', 'After لولا', 'When the جواب القسم indicates it', 'Never'], correct: 0,
          why: 'Both have a clear contextual clue supplying the missing predicate.' },
        { t: 'mcq', q: 'When does the خبر **agree** with the مبتدأ?', choices: ['When the خبر contains a hidden pronoun (﴿إنهم هم المفسدون﴾ — unlike ﴿نحن فتنة﴾) and when the مبتدأ is a demonstrative (﴿فذانك برهانان من ربك﴾)', 'Always', 'Never', 'Only in gender'], correct: 0,
          why: 'A hidden pronoun inside the predicate forces it to match its referent.' },
        { t: 'mcq', q: 'When may the **فاء** enter upon the خبر?', choices: ['When the مبتدأ includes the meaning of a condition', 'Whenever the خبر is a clause', 'Whenever the مبتدأ is indefinite', 'Never'], correct: 0,
          why: 'The فاء is the answer-linker; it needs a condition to answer.' },
        { t: 'mcq', q: 'In which cases does the مبتدأ carry conditional meaning, licensing the فاء?', choices: ['After أمّا · a relative noun · a noun described by a relative with a verb or ظرف · an indefinite described by a verb or ظرف · annexed to such an indefinite · كل annexed to an indefinite', 'Only after أمّا', 'Only with a relative noun', 'Only when the مبتدأ is definite'], correct: 0,
          why: 'e.g. ﴿الذين خسروا أنفسهم فهم لا يؤمنون﴾ and كلُّ يتيمٍ فله في قلبي رأفة.' },
      ],
    },

    /* ═══ 05. بقية المرفوعات ═══ */
    {
      id: 'bank-mm-marfuat',
      title: 'بقية المرفوعات',
      steps: [
        { t: 'mcq', q: 'Give the example of the **اسم of the أفعال الناقصة** (the fifth مرفوع).', choices: ['﴿وكان اللهُ عليما حكيما﴾ — الله is the مرفوع اسم كان', '﴿إن اللهَ رحيمٌ﴾', '﴿ما هذا بشرا﴾', 'لا عملُ مراءٍ مقبولٌ'], correct: 0,
          why: 'The اسم is raised, the خبر (عليما حكيما) put in نصب.' },
        { t: 'mcq', q: 'Give the examples of the **اسم of the حروف المشبهة بليس** (the sixth مرفوع).', choices: ['﴿ما هذا بشرا﴾ · لا شيءٌ مشابها لله', '﴿وكان اللهُ عليما حكيما﴾', '﴿إن اللهَ رحيمٌ﴾', '﴿ولات حينَ مناص﴾'], correct: 0,
          why: 'Like ليس: the first noun raised, the second put in نصب.' },
        { t: 'mcq', q: 'Give the example of the **خبر of the حروف المشبهة بالفعل** (the seventh مرفوع).', choices: ['إن اللهَ رحيمٌ — رحيم being its مرفوع خبر', '﴿وكان اللهُ عليما حكيما﴾', '﴿ما هذا بشرا﴾', '﴿ولات حين مناص﴾'], correct: 0,
          why: 'Here it is the **خبر** that is raised, the اسم being in نصب — the mirror of كان.' },
        { t: 'mcq', q: 'Where may the **لام المزحلقة** enter?', choices: ['The خبر of إنّ (﴿وإنك لَعلى خلق عظيم﴾) · the delayed اسم of إنّ (﴿إن في ذلك لَعبرة﴾) · the ضمير الفصل between its اسم and خبر (﴿إن هذا لَهو القصص الحق﴾)', 'The خبر only', 'The اسم only', 'Only on a verb'], correct: 0,
          why: 'Three landing places, all after إنّ.' },
        { t: 'mcq', q: 'Give an example of the **خبر of لا لنفي الجنس** (the eighth مرفوع).', choices: ['لا عملُ مراءٍ مقبولٌ — مقبول being its مرفوع خبر', '﴿فلا رفثَ ولا فسوقَ ولا جدالَ في الحج﴾', '﴿ما هذا بشرا﴾', '﴿إن اللهَ رحيمٌ﴾'], correct: 0,
          why: 'The اسم (عمل) is منصوب by annexation; the خبر is raised.' },
        { t: 'mcq', q: 'What is the **predominant form of the خبر of لا لنفي الجنس**?', choices: ['A شبه جملة — ﴿فلا رفث ولا فسوق ولا جدال في الحج﴾', 'A single derived noun', 'A verbal clause', 'A nominal clause'], correct: 0,
          why: 'في الحج is the predicate for all three negated nouns.' },
        { t: 'mcq', q: 'When is the خبر of لا لنفي الجنس **frequently deleted**?', choices: ['When it is general, like موجود — ﴿لا ضير﴾ i.e. لا ضير موجود عليكم', 'When the اسم is مضاف', 'When لا is repeated', 'It is never deleted'], correct: 0,
          why: 'A general predicate adds nothing, so it is dispensed with.' },
      ],
    },

    /* ═══ 06. المفعول المطلق ═══ */
    {
      id: 'bank-mm-mutlaq',
      title: 'المفعول المطلق',
      steps: [
        { t: 'mcq', q: 'Why is the **مفعول المطلق** so named?', choices: ['Because its name is unrestricted by a preposition, unlike مفعول به، فيه، له، معه', 'Because it may be deleted freely', 'Because it can be dual or plural', 'Because it needs no عامل'], correct: 0,
          why: 'The other four objects each carry a preposition in their very name.' },
        { t: 'mcq', q: 'What counts as a **مفعول مطلق**?', choices: ['The مصدر of a preceding عامل (﴿ورتل القرآن ترتيلا﴾) or the مصدر of a verb of the same meaning (﴿وتبتل إليه تبتيلا﴾)', 'Any منصوب after a verb', 'Only the مصدر of the exact verb used', 'Any مصدر in the sentence'], correct: 0,
          why: 'Same meaning suffices; the root need not match exactly.' },
        { t: 'mcq', q: 'What may **stand in place of the مصدر** as مفعول مطلق?', choices: ['اسم المصدر · its صفة · its ضمير · الإشارة · what indicates its number · what indicates its type · كل/بعض/أي annexed to it', 'Only its صفة', 'Only its number', 'Nothing may substitute for it'], correct: 0,
          why: 'Seven substitutes — e.g. رجع القهقرى (type) and ﴿ولا تبسطها كلَّ البسط﴾.' },
        { t: 'mcq', q: 'What can serve as the **عامل of the مفعول المطلق**?', choices: ['A verb (﴿ورتل القرآن ترتيلا﴾) · a مصدر (﴿جزاؤكم جزاءً موفورا﴾) · a مشتق (﴿والصافات صفًّا﴾)', 'A verb only', 'A مصدر only', 'A particle'], correct: 0,
          why: 'Any of the شبه فعل governors will do.' },
        { t: 'mcq', q: 'What are the three **أنواع** of مفعول مطلق?', choices: ['للتوكيد · للنوع (manner) · للعدد (number of times)', 'للتوكيد · للتخصيص · للتعليل', 'متصل · منقطع · مفرغ', 'حقيقي · سببي · مؤكد'], correct: 0,
          why: 'Emphasis, manner, count — three jobs for one construction.' },
        { t: 'mcq', q: 'How is the **مفعول مطلق للنوع** formed?', choices: ['By إضافة (﴿ظنَّ السوء﴾) · by صفة (﴿فتحا مبينا﴾) · by إشارة (ذلك الاجتهاد) · by لام العهد (الاجتهادَ)', 'Only by صفة', 'Only by إضافة', 'By tanwīn alone'], correct: 0,
          why: 'Four devices, all of which narrow the bare مصدر to a particular manner.' },
        { t: 'mcq', q: 'What conditions bind the **مفعول مطلق للتأكيد**?', choices: ['Indefinite, undescribed, not مضاف, not ending in تاء الوحدة, and neither dual nor plural', 'Definite and described', 'Always dual or plural', 'Always مضاف'], correct: 0,
          why: 'Any of these additions would turn it into النوع or العدد.' },
        { t: 'mcq', q: 'Which type of مفعول مطلق may be made **dual or plural**?', choices: ['Only the مصدر of العدد — سجدتين', 'Only التوكيد', 'Only النوع', 'All three'], correct: 0,
          why: 'Counting is the one job that requires number.' },
        { t: 'mcq', q: 'In which cases does the مفعول المطلق **substitute for its verb**?', choices: ['As a command (﴿وبالوالدين إحسانا﴾) · a prohibition (صبرا لا جزعا) · a supplication (﴿بُعدا للقوم الظالمين﴾) · confirming the sentence’s content (﴿هم المؤمنون حقا﴾) · detailing its outcome (﴿فإما منًّا بعد وإما فداء﴾)', 'Only as a command', 'Only as a supplication', 'It never substitutes for its verb'], correct: 0,
          why: 'Five cases — the same list that governs obligatory deletion of its عامل.' },
        { t: 'mcq', q: 'Give examples of **مصادر مسموعة** used as مفعول مطلق in place of the verb.', choices: ['﴿سبحانك﴾ · ﴿معاذ الله﴾ · ﴿حجرا محجورا﴾ · لبيك · غفرانك', 'صبرا لا جزعا · أجرأةً على المعاصي', 'هنيئا لك · سالما غانما', 'مرحبا · أهلا وسهلا'], correct: 0,
          why: 'Fixed idioms whose verbs are never restored.' },
      ],
    },

    /* ═══ 07. المفعول به، فيه، له، معه ═══ */
    {
      id: 'bank-mm-mafaeel',
      title: 'المفعول به · فيه · له · معه',
      steps: [
        { t: 'mcq', q: 'Define the **مفعول به**.', choices: ['That upon which the action falls — ﴿اعبدوا ربَّكم﴾', 'That in which the action occurs', 'That for whose sake the action occurs', 'That along with which the action occurs'], correct: 0,
          why: 'The other three definitions belong to فيه، له، معه respectively.' },
        { t: 'mcq', q: 'What is the **default position** of the مفعول به, and when may it precede the verb?', choices: ['Default: after the verb and فاعل; it may precede the verb permissibly — ﴿إياك نعبد﴾', 'It must always follow', 'It must always precede', 'Only pronouns may precede'], correct: 0,
          why: 'Fronting for emphasis is the standard reading of ﴿إياك نعبد﴾.' },
        { t: 'mcq', q: 'When **must** the مفعول به precede the verb?', choices: ['When it is among what demands صدر الكلام — الشرط (﴿أيًّا ما تدعوا﴾) · الاستفهام (﴿فأيَّ آيات الله تنكرون﴾), including كم الخبرية (﴿وكم أرسلنا من نبي في الأولين﴾)', 'Whenever it is definite', 'Whenever it is a pronoun', 'It is never obligatory'], correct: 0,
          why: 'The صدارة rule again — the same principle that drives التعليق.' },
        { t: 'mcq', q: 'Define the **مفعول فيه**, and what is it called?', choices: ['That in which the action occurs, of place or time — called the ظرف: أحسني إلى أمك أبدًا', 'That upon which the action falls — called the object', 'That for whose sake the action occurs — called المفعول لأجله', 'That along with which the action occurs'], correct: 0,
          why: 'A container of the act, whether temporal or spatial.' },
        { t: 'mcq', q: 'What are the two kinds of **ظرف الزمان**?', choices: ['مبهم — unspecified time (أبد، حين، وقت، زمان) · محدود — specified time (ساعة، يوم، ليلة، أسبوع، شهر، سنة، عام)', 'ماضٍ and مستقبل', 'لغو and مستقر', 'حقيقي and مجازي'], correct: 0,
          why: 'The vague/definite split, which recurs for place.' },
        { t: 'mcq', q: 'What إعراب is permitted in the **ظرف الزمان** (both kinds)?', choices: ['Either نصب by an implied preposition or جر by an overt one — ﴿يراك حين تقوم﴾ / ﴿إلى حين﴾ · ﴿يومَ القيامة﴾ / ﴿ليوم القيامة﴾', 'نصب only', 'جر only', 'رفع or نصب'], correct: 0,
          why: 'Time adverbs are freer than place adverbs — see the محدود place rule below.' },
        { t: 'mcq', q: 'What are the two kinds of **ظرف المكان**?', choices: ['مبهم — the six directions and measures like ميل، فرسخ · محدود — a specified place', 'قريب and بعيد', 'لغو and مستقر', 'داخلي and خارجي'], correct: 0,
          why: 'Directions and distances are inherently vague; a named place is not.' },
        { t: 'mcq', q: 'What إعراب rules apply to the **ظرف المكان المبهم**?', choices: ['Both نصب by an implied preposition (﴿لمن خلفك آية﴾) and جر by an overt one (﴿من خلفهم ذرية ضعافا﴾)', 'نصب only', 'جر only', 'It cannot be an adverb'], correct: 0,
          why: 'Same freedom as the time adverb.' },
        { t: 'mcq', q: 'What إعراب rules apply to the **ظرف المكان المحدود**?', choices: ['Normally جر by an overt preposition (﴿لا تفسدوا في الأرض﴾); نصب only when derived from the verb (﴿مقاعدَ للسمع﴾) or with verbs of entering, dwelling and alighting (﴿يدخلون الجنةَ﴾)', 'Freely نصب or جر', 'نصب only', 'It cannot be an adverb at all'], correct: 0,
          why: 'This is the one adverb type that is genuinely restricted.' },
        { t: 'mcq', q: 'What may **stand in place of the مفعول فيه**?', choices: ['The مصدر (﴿وإدبارَ النجوم﴾) · what is annexed to the time (﴿بعضَ يوم﴾) · what indicates number (﴿ثلاثَ ليال﴾)', 'Only a مصدر', 'Only a number', 'Nothing may substitute'], correct: 0,
          why: 'Parallel to the substitutes for the مفعول المطلق.' },
        { t: 'mcq', q: 'Define the **مفعول له** and its other name.', choices: ['That for whose sake the action occurs (﴿صبروا ابتغاءَ وجه ربهم﴾) — also المفعول لأجله', 'That in which the action occurs — also الظرف', 'That along with which it occurs — also المصاحب', 'That upon which it falls — also المنفعل'], correct: 0,
          why: 'It answers “why?”, not “where/when?”.' },
        { t: 'mcq', q: 'What are the conditions for the **نصب of the مفعول له without the لام**?', choices: ['It must be a مصدر · قلبي (of the heart) · sharing the verb’s فاعل · and sharing the verb’s time', 'Only that it be a مصدر', 'Only that it be definite', 'There are no conditions'], correct: 0,
          why: 'Fail any one and the لام is required — e.g. سافرت إلى مكة للحج (not قلبي).' },
        { t: 'mcq', q: 'Can a **مصدر مؤول** be a مفعول له?', choices: ['Yes, with an implied مضاف — ﴿وألقى في الأرض رواسي أن تميد بكم﴾ i.e. كراهةَ أن تميد بكم', 'No', 'Only after a negation', 'Only with the لام'], correct: 0,
          why: 'Without كراهة the sense would invert: the mountains prevent the swaying.' },
        { t: 'mcq', q: 'Define the **مفعول معه**.', choices: ['That along with which the action occurs — يفنى المال ويبقى ابنُ آدم وعملَه', 'That in which the action occurs', 'That for whose sake it occurs', 'That upon which it falls'], correct: 0,
          why: 'The wāw here means “with”, not “and”.' },
        { t: 'mcq', q: 'What is the **condition for the مفعول معه**?', choices: ['It must be preceded by a sentence containing a verb or a quasi-verb — أنا سائرٌ والنهرَ, unlike كل امرئ وشأنه', 'It must be definite', 'It must follow a negation', 'There is no condition'], correct: 0,
          why: 'No verbal force, no accompaniment reading.' },
        { t: 'mcq', q: 'When is **نصب of the مفعول معه obligatory**?', choices: ['When coordination is impossible — «بُعثت والساعةَ كهاتين», since one cannot conjoin to an attached مرفوع pronoun without a detached one', 'Always', 'Never', 'Only after a negation'], correct: 0,
          why: 'With the عطف route closed, only the accompaniment reading remains.' },
        { t: 'mcq', q: 'When are **both نصب and عطف** permitted after the wāw?', choices: ['Whenever coordination is possible — حضر الأب وولدَه / وولدُه', 'Never', 'Only with pronouns', 'Only in poetry'], correct: 0,
          why: 'Two readings, two cases, both sound.' },
      ],
    },

    /* ═══ 08. الحال ═══ */
    {
      id: 'bank-mm-hal',
      title: 'الحال',
      steps: [
        { t: 'mcq', q: 'Define the **حال**.', choices: ['That which clarifies the state of the فاعل (﴿وادعوه مخلصين له الدين﴾), the مفعول به (﴿أرسلناك بالحق بشيرا ونذيرا﴾), or something else (﴿إلى الله مرجعكم جميعا﴾)', 'That which removes ambiguity from a vague noun', 'That in which the action occurs', 'That which is excluded from a ruling'], correct: 0,
          why: 'A state, not a specification — the second option defines التمييز.' },
        { t: 'mcq', q: 'What is the **owner of the حال** called?', choices: ['صاحب الحال, also ذو الحال — every حال must have one', 'المنعوت', 'المبدل منه', 'المؤكَّد'], correct: 0,
          why: 'A state with nobody in it is not a state.' },
        { t: 'mcq', q: 'What is the **default order** of ذو الحال and the حال?', choices: ['ذو الحال precedes the حال', 'The حال precedes', 'There is no default', 'They must be adjacent in either order'], correct: 0,
          why: 'Fronting the حال is one of the licences for an indefinite owner.' },
        { t: 'mcq', q: 'What is the **default definiteness of ذو الحال**?', choices: ['معرفة; it may be نكرة only with a مسوغ', 'نكرة; it may be معرفة only with a justifier', 'Either freely', 'It must always be معرفة'], correct: 0,
          why: 'Mirror image of the حال itself, whose default is indefinite.' },
        { t: 'mcq', q: 'Which list gives the **مسوغات** for an indefinite ذو الحال?', choices: ['The حال precedes it (رأيت راكبا رجلًا) · it is a نكرة غير محضة · after a negation · after quasi-negation (نهي/استفهام) · the حال is joined by a wāw', 'Only after a negation', 'Only when the حال precedes', 'There are none'], correct: 0,
          why: 'Five licences — e.g. ﴿وما أهلكنا من قرية إلا ولها كتاب معلوم﴾.' },
        { t: 'mcq', q: 'Can ذو الحال be indefinite **without** a مسوغ?', choices: ['Rarely, yes — «صلى رسول الله ﷺ قاعدا وصلى وراءه رجالٌ قياما»', 'No, never', 'Yes, freely', 'Only in poetry'], correct: 0,
          why: 'رجالٌ has no justifier, yet قياما describes it.' },
        { t: 'mcq', q: 'What is the **default definiteness of the حال itself**, and how is وحده explained?', choices: ['Default نكرة; in ﴿إذا دُعي الله وحدَه كفرتم﴾, وحده is interpreted as منفردا or موحَّدا', 'Default معرفة; وحده is an exception', 'Either freely', 'It must be definite'], correct: 0,
          why: 'The apparent definite is read as an indefinite participle in disguise.' },
        { t: 'mcq', q: 'What is the **default of the مفرد حال** regarding derivation?', choices: ['It should be an اسم مشتق', 'It should be جامد', 'It should be a مصدر', 'It should be a number'], correct: 0,
          why: 'A state is naturally expressed by a participle.' },
        { t: 'mcq', q: 'When may the حال be **جامدة but interpreted as مشتق**?', choices: ['Indicating تشبيه (بدا وجهه قمرا) · مفاعلة (بعته يدا بيد) · ترتيب (﴿والملك صفا صفا﴾)', 'When described', 'When it is a number', 'When it indicates origin'], correct: 0,
          why: 'The last three belong to the **uninterpreted** جامدة list below.' },
        { t: 'mcq', q: 'When may the حال be **جامدة without** interpretation as مشتق?', choices: ['When described (﴿قرآنا عربيا﴾ — the حال الموطئة) · when a number (﴿أربعين ليلة﴾) · when indicating origin (﴿خلقتَ طينا﴾) · when indicating a derivative (﴿من الجبال بيوتا﴾)', 'When indicating comparison', 'When indicating reciprocity', 'Never'], correct: 0,
          why: 'Four cases where a frozen noun stands as a state in its own right.' },
        { t: 'mcq', q: 'Distinguish the **حال المتنقلة** from the **حال اللازمة**.', choices: ['متنقلة (the default) — a changing state (﴿وجاءوا أباهم عشاءً يبكون﴾) · لازمة (also ثابتة/دائمة) — a fixed one (﴿وخلق الإنسان ضعيفا﴾)', 'The reverse', 'Both are default', 'Both are fixed'], correct: 0,
          why: 'Weakness is constitutive of man; weeping is momentary.' },
        { t: 'mcq', q: 'Distinguish the **حال المؤسسة** from the **حال المؤكدة**.', choices: ['مؤسسة (also مبينة) — adds a meaning beyond the عامل (﴿ولا تمش في الأرض مرحا﴾) · مؤكدة — merely confirms it (﴿ولا تعثوا في الأرض مفسدين﴾)', 'The reverse', 'Both add new meaning', 'Both merely confirm'], correct: 0,
          why: 'عثا already means to spread corruption, so مفسدين adds nothing new.' },
        { t: 'mcq', q: 'Distinguish **المحكية · المقارنة · المقدرة**.', choices: ['محكية — past (﴿وقد بلغني الكبر﴾) · مقارنة — simultaneous (﴿وجاءوا أباهم عشاء يبكون﴾) · مقدرة — future (﴿فادخلوها خالدين﴾)', 'محكية — future · مقارنة — past · مقدرة — simultaneous', 'All three are simultaneous', 'محكية — simultaneous · مقارنة — future · مقدرة — past'], correct: 0,
          why: 'They enter Paradise before abiding in it, so خالدين is مقدرة.' },
        { t: 'mcq', q: 'What is the **حال الموطئة**?', choices: ['The جامدة حال described by a مشتق — ﴿إنا أنزلناه قرآنا عربيا﴾, as against the مقصودة', 'A حال that confirms its عامل', 'A حال describing something connected to its owner', 'A حال whose owner is indefinite'], correct: 0,
          why: '“Paving the way”: قرآنا is a stepping-stone to the real descriptor عربيا.' },
        { t: 'mcq', q: 'Distinguish **مترادفة** from **متداخلة** among multiple أحوال.', choices: ['مترادفة — one owner with several states («حفاةً عراةً غرلا») · متداخلة — the second describes a pronoun inside the first (﴿…أجمعين ۝ خالدين فيها…﴾)', 'The reverse', 'Both describe one owner directly', 'Both are nested'], correct: 0,
          why: 'Parallel vs nested — the same distinction made for أنعات.' },
        { t: 'mcq', q: 'Distinguish the **حال الحقيقية** from the **حال السببية**.', choices: ['حقيقية — clarifies the state of its owner himself · سببية — clarifies the state of something connected to him (﴿خُشَّعا أبصارُهم يخرجون من الأجداث﴾)', 'The reverse', 'Both describe the owner directly', 'Both describe something connected'], correct: 0,
          why: 'The same حقيقي/سببي split runs through the نعت chapter.' },
      ],
    },

    /* ═══ 09. التمييز ═══ */
    {
      id: 'bank-mm-tamyiz',
      title: 'التمييز',
      steps: [
        { t: 'mcq', q: 'Define **التمييز**.', choices: ['That which removes ambiguity from an ambiguous single word or an ambiguous attribution', 'That which clarifies the state of the فاعل', 'That which is excluded from a preceding ruling', 'That in which the action occurs'], correct: 0,
          why: 'Two kinds of vagueness, hence the two kinds of تمييز.' },
        { t: 'mcq', q: 'What are the categories of the **مفرد المبهم** (تمييز of a single word)?', choices: ['Number (صريح ﴿أحد عشر كوكبا﴾ or مبهم ﴿كم آتيناهم من آية﴾) · measure by instrument (كيل، وزن، مساحة) · quasi-measure · things treated like measures · the تمييز’s derivative (خاتم فضةً)', 'Only number and measure', 'Only measure', 'Only the derivative case'], correct: 0,
          why: 'Five categories, all of them vague **words** rather than vague statements.' },
        { t: 'mcq', q: 'What are the two kinds of تمييز of the **نسبة المبهمة**?', choices: ['غير محول (لله درُّه فارسا) and محول — transformed from a فاعل, a مفعول به, or a مبتدأ', 'حقيقي and سببي', 'صريح and مبهم', 'مفرد and مركب'], correct: 0,
          why: 'The محول kind can be “rewound” into a plainer sentence.' },
        { t: 'mcq', q: 'Give the Qurʾānic examples of the **محول** تمييز.', choices: ['From فاعل: ﴿واشتعل الرأسُ شيبا﴾ · from مفعول به: ﴿وفجرنا الأرضَ عيونا﴾ · from مبتدأ: ﴿أنا أكثر منك مالا﴾', 'From فاعل: ﴿وفجرنا الأرض عيونا﴾ · from مفعول: ﴿واشتعل الرأس شيبا﴾', 'All three are ﴿أنا أكثر منك مالا﴾', 'None of these are محول'], correct: 0,
          why: 'Each rewinds: اشتعل شيبُ الرأس · فجرنا عيونَ الأرض · مالي أكثر من مالك.' },
        { t: 'mcq', q: 'What is the **default definiteness of the تمييز**?', choices: ['نكرة', 'معرفة', 'Either freely', 'It must be مضافا'], correct: 0,
          why: 'A definite specifier would beg the question it is meant to answer.' },
        { t: 'mcq', q: 'Why is the تمييز listed among the **منصوبات** if it can be مجرور?', choices: ['تغليبا — by predominance; it may in fact be مجرور: ﴿في ستةِ أيامٍ﴾', 'Because it is always منصوب', 'Because جر is anomalous', 'Because it has no محل'], correct: 0,
          why: 'Classification by the majority case, with the minority acknowledged.' },
        { t: 'mcq', q: 'How is the تمييز of the **explicit numbers** parsed?', choices: ['مجرور by إضافة — plural for 3–10 (﴿ثلاثةَ أيامٍ﴾), singular for 100 (﴿مائةَ عامٍ﴾) and 1000 (﴿كألفِ سنةٍ﴾) · منصوب singular for 11–99 (﴿أحد عشر كوكبًا﴾)', 'Always منصوب singular', 'Always مجرور plural', 'Always مجرور singular'], correct: 0,
          why: 'Three sub-rules, of which the 11–99 نصب is the odd one out.' },
        { t: 'mcq', q: 'How is the تمييز of **كم الاستفهامية** parsed?', choices: ['منصوب singular (كم يومًا لبثت؟); it may be deleted with an indicator (﴿كم لبثتم﴾)', 'مجرور by a redundant مِن', 'مجرور by إضافة', 'مرفوع'], correct: 0,
          why: 'The interrogative kam takes نصب; the reportative one does not.' },
        { t: 'mcq', q: 'How is the تمييز of **كم الخبرية** parsed?', choices: ['مجرور by a redundant مِن — overt (﴿كم من فئة قليلة غلبت فئة كثيرة﴾) or implied (كم ملوكٍ باد ملكُهم)', 'منصوب singular', 'مرفوع', 'مجرور by إضافة to كم'], correct: 0,
          why: 'The redundant مِن is the signature of the reportative kam.' },
        { t: 'mcq', q: 'What is the **default form of the تمييز of كم الخبرية**, and what variations are allowed?', choices: ['Default: singular, indefinite, adjacent; pluralisation, definition and separation are all allowed — and the overt مِن becomes obligatory on separation (﴿كم أهلكنا قبلهم من القرون﴾)', 'It admits no variation', 'It must always be plural', 'It must always be separated'], correct: 0,
          why: 'Once separated, only the overt preposition can still link them.' },
        { t: 'mcq', q: 'Can the تمييز be merely **confirmatory (مؤكد)**?', choices: ['Yes — غير مفسر: ﴿إن عدة الشهور عند الله اثنا عشر شهرا﴾', 'No', 'Only with كم', 'Only with measures'], correct: 0,
          why: 'اثنا عشر is already unambiguous; شهرا adds emphasis, not clarification.' },
      ],
    },

    /* ═══ 10. المستثنى ═══ */
    {
      id: 'bank-mm-mustathna',
      title: 'المستثنى',
      steps: [
        { t: 'mcq', q: 'Define the **المستثنى**.', choices: ['That which is excluded from the ruling of what precedes it', 'That which removes ambiguity', 'That which clarifies a state', 'That which confirms a preceding noun'], correct: 0,
          why: 'Exclusion from a ruling already stated.' },
        { t: 'mcq', q: 'What are the three **أركان of الاستثناء**?', choices: ['المستثنى منه (القوم) · أداة الاستثناء (إلا) · المستثنى (زيدا)', 'المستثنى · الأداة · الحكم', 'المتصل · المنقطع · المفرغ', 'الأداة · الحرف · الفعل'], correct: 0,
          why: 'In جاء القوم إلا زيدا, all three are present.' },
        { t: 'mcq', q: 'Distinguish **التام** from **غير التام**.', choices: ['تام (also غير مفرغ) — the مستثنى منه is mentioned · غير تام (مفرغ) — it is not; this occurs only after a negation or quasi-negation, and the أداة becomes a particle of حصر and does not govern (ما محمدٌ إلا رسولٌ)', 'The reverse', 'Both mention the مستثنى منه', 'Neither mentions it'], correct: 0,
          why: 'In the مفرغ case, parse the noun by its role in the sentence, ignoring إلا.' },
        { t: 'mcq', q: 'What are the two kinds of **الاستثناء التام**?', choices: ['متصل — the excluded is of the same genus (﴿ثم توليتم إلا قليلا منكم﴾) · منقطع — it is not, and إلا then means استدراك (﴿فسجدوا إلا إبليس﴾)', 'موجب and غير موجب', 'مفرغ and غير مفرغ', 'صريح and مؤول'], correct: 0,
          why: 'Iblīs was not one of the angels, hence منقطع.' },
        { t: 'mcq', q: 'What must the **مستثنى منه** be?', choices: ['A معرفة (جاء القوم إلا أحمد) or an informative نكرة (ما جاء أحدٌ إلا أحمد) — unlike جاء قومٌ إلا خالدا', 'Always indefinite', 'Always a plural', 'There is no requirement'], correct: 0,
          why: 'Excluding from a vague indefinite conveys nothing.' },
        { t: 'mcq', q: 'What are the **أدوات الاستثناء**, by category?', choices: ['حرف: إلا (the chapter’s origin) and حاشا · فعل: خلا، عدا، ما خلا، ما عدا، ليس، لا يكون · اسم: غير، سوى', 'All of them are حروف', 'All of them are أفعال', 'حرف: إلا only · اسم: غير only'], correct: 0,
          why: 'Three word-classes, which is why the case of the excluded noun varies so much.' },
        { t: 'mcq', q: 'What is the status of **خلا and عدا**?', choices: ['Verbs according to most, prepositions according to some; ما خلا and ما عدا are verbs by consensus', 'Prepositions by consensus', 'Nouns by consensus', 'Verbs by consensus'], correct: 0,
          why: 'The ما forces the verbal reading, since ما المصدرية needs a verb.' },
        { t: 'mcq', q: 'What must the **مستثنى itself** be?', choices: ['A معرفة (إلا زيدا) or a specified نكرة (إلا رجلا مريضا / إلا رجلَ سوء) — unlike جاء القوم إلا رجلا', 'Always indefinite', 'Always definite', 'There is no requirement'], correct: 0,
          why: 'Excluding “a man” from “the people” leaves the hearer none the wiser.' },
        { t: 'mcq', q: 'How is the مستثنى parsed in a **تام متصل** exception in **affirmative** speech?', choices: ['منصوب — ﴿فشربوا منه إلا قليلا منهم﴾', 'بدل from the مستثنى منه', 'مجرور', 'مرفوع'], correct: 0,
          why: 'No choice here; the بدل option belongs to non-affirmative speech.' },
        { t: 'mcq', q: 'How may the مستثنى be parsed in a **تام متصل** exception in **non-affirmative** speech?', choices: ['Two options — نصب (﴿إلا امرأتَك﴾) or بدل from the مستثنى منه (﴿ما فعلوه إلا قليلٌ منهم﴾)', 'نصب only', 'بدل only', 'جر only'], correct: 0,
          why: 'Both readings are Qurʾānic.' },
        { t: 'mcq', q: 'How is the مستثنى parsed when it **precedes the مستثنى منه**?', choices: ['منصوب — وما لي إلا آلَ أحمدَ شيعةٌ', 'بدل', 'مرفوع', 'مجرور'], correct: 0,
          why: 'The بدل reading needs something already stated to substitute for.' },
        { t: 'mcq', q: 'How is the مستثنى parsed after a **verb of exception**?', choices: ['منصوب على المفعولية — ألا كل شيء ما خلا اللهَ باطل', 'مجرور', 'مرفوع', 'It is a بدل'], correct: 0,
          why: 'A verb takes an object, so خلا/عدا put the noun in نصب.' },
        { t: 'mcq', q: 'How are **غير** and what follows it parsed?', choices: ['غير takes whatever إعراب the مستثنى would take after إلا; what follows غير is مجرور by إضافة', 'Both are منصوب', 'غير is always منصوب', 'Both are مجرور'], correct: 0,
          why: 'غير absorbs the exception’s case and passes جر to its complement.' },
        { t: 'mcq', q: 'How is the مستثنى parsed in the **استثناء المنقطع**?', choices: ['منصوب — ﴿فسجدوا إلا إبليسَ﴾', 'مرفوع as a بدل', 'مجرور', 'Either نصب or بدل'], correct: 0,
          why: 'With no genus-relation there is nothing to be a بدل from.' },
        { t: 'mcq', q: 'What is distinctive about **حاشا**?', choices: ['It combines exclusion with exoneration (تنزيه), and the excluded noun after it is مجرور — كل بني آدم خطاؤون حاشا الأنبياءِ', 'It puts the excluded noun in نصب', 'It is a verb by consensus', 'It is restricted to negative sentences'], correct: 0,
          why: 'Not just “except” but “far be it from”.' },
        { t: 'mcq', q: 'What is the **original function of غير**, and its secondary use?', choices: ['Originally description (﴿لا تدخلوا بيوتا غيرَ بيوتكم﴾); secondarily exception (جاء الأولاد غيرَ زيد)', 'Originally exception; secondarily description', 'Only exception', 'Only description'], correct: 0,
          why: 'And إلا runs the opposite way — see the next question.' },
        { t: 'mcq', q: 'What is the **original function of إلا**, and its secondary use?', choices: ['Originally exception; secondarily description, meaning غير — الناس هلكى إلا العالمون · ﴿لو كان فيهما آلهةٌ إلا اللهُ لفسدتا﴾', 'Originally description; secondarily exception', 'Only exception', 'Only description'], correct: 0,
          why: 'The two words swap roles — a neat symmetry worth remembering.' },
        { t: 'mcq', q: 'In ﴿لَوْ كَانَ فِيهِمَا آلِهَةٌ إِلَّا اللهُ لَفَسَدَتَا﴾, what is إلا doing?', choices: ['It is a صفة meaning غير — “gods other than Allah”, not an exception', 'It is an exception, with الله excluded', 'It is a particle of restriction', 'It is redundant'], correct: 0,
          why: 'The رفع on الله gives it away: an exception would call for نصب.' },
      ],
    },

    /* ═══ 11. بقية المنصوبات ═══ */
    {
      id: 'bank-mm-mansubat',
      title: 'بقية المنصوبات',
      steps: [
        { t: 'mcq', q: 'Give the example of the **خبر of the أفعال الناقصة** (the ninth منصوب).', choices: ['﴿إنه كان صديقا نبيا﴾', '﴿ما هذا بشرا﴾', 'إن اللهَ رحيم', 'لا عملَ مراءٍ مقبول'], correct: 0,
          why: 'The اسم of كان is the hidden pronoun; صديقا نبيا is the doubled predicate.' },
        { t: 'mcq', q: 'Can the **خبر of كان precede its اسم**?', choices: ['Yes — ليس سواءً عالمٌ وجهولٌ', 'No', 'Only with ليس', 'Only in poetry'], correct: 0,
          why: 'سواءً is the fronted predicate; the two nouns after it are the اسم.' },
        { t: 'mcq', q: 'Can the **خبر of كان precede the verb itself**?', choices: ['Yes (قائما كان زيد) — except with verbs beginning with ما المصدرية or ما النافية', 'No', 'Yes, without exception', 'Only when the اسم is a pronoun'], correct: 0,
          why: 'ما دام and ما زال keep their ما at the front, blocking anything before it.' },
        { t: 'mcq', q: 'Give examples of the **خبر of the حروف المشبهة بليس** (the tenth منصوب).', choices: ['ما: ﴿ما هذا بشرا﴾ · لا: لا شيءٌ مشابها لله · لات: ﴿ولات حينَ مناص﴾', 'إن: ﴿إن الله رحيم﴾', 'كان: ﴿إنه كان صديقا نبيا﴾', 'لا النافية للجنس: لا عملَ مراءٍ مقبول'], correct: 0,
          why: 'Three particles, each with its own restrictions from the earlier chapter.' },
        { t: 'mcq', q: 'Give an example of the **اسم of the حروف المشبهة بالفعل** (the eleventh منصوب).', choices: ['إن اللهَ رحيم — الله being its منصوب اسم', '﴿ما هذا بشرا﴾', '﴿إنه كان صديقا نبيا﴾', '﴿ولات حين مناص﴾'], correct: 0,
          why: 'اسم منصوب, خبر مرفوع — the reverse of كان.' },
        { t: 'mcq', q: 'When is the **اسم of لا لنفي الجنس منصوبا لفظا**?', choices: ['When مضاف (لا عملَ مراءٍ مقبول) or شبيه بالمضاف (لا عاصيًا أمَّه وأباه ناجحٌ)', 'When مفرد', 'Always', 'Never'], correct: 0,
          why: 'The مفرد case is built, not overtly inflected.' },
        { t: 'mcq', q: 'How is the اسم of لا لنفي الجنس **built when مفرد**?', choices: ['منصوب محلا, built on fatḥa for singular/broken plural, on fatḥa or kasra for the sound feminine plural, and on the yāʾ for dual and sound masculine plural', 'Always built on fatḥa', 'Always built on ḍamma', 'It is never built'], correct: 0,
          why: 'لا رجلَ · لا مسلماتَ/مسلماتِ · لا رجلين، لا مسلمِين.' },
        { t: 'mcq', q: 'What happens when **لا لنفي الجنس enters upon a معرفة**?', choices: ['It must be repeated — ﴿لا الشمسُ ينبغي لها أن تدرك القمر ولا الليلُ سابق النهار﴾', 'It governs as normal', 'The construction is invalid', 'The noun is put in نصب'], correct: 0,
          why: 'A definite cannot be a whole genus, so the negation is reframed.' },
        { t: 'mcq', q: 'When لا is repeated without separation, **how many ways** may its noun be parsed?', choices: ['Five — both on fatḥa · first fatḥa + second مرفوع · first fatḥa + second منصوب · both مرفوع · first مرفوع + second fatḥa', 'Two', 'Three', 'Only one'], correct: 0,
          why: 'e.g. لا حولَ ولا قوةٌ · لا حولَ ولا قوةً · ﴿لا بيعٌ فيه ولا خلةٌ﴾.' },
        { t: 'mcq', q: 'Can the **اسم of لا be deleted**?', choices: ['Yes — لا عليك, i.e. لا بأسَ عليك', 'No', 'Only when repeated', 'Only if definite'], correct: 0,
          why: 'The بأس is understood from the idiom.' },
      ],
    },

    /* ═══ 12. المجرورات ═══ */
    {
      id: 'bank-mm-majrurat',
      title: 'المجرورات',
      steps: [
        { t: 'mcq', q: 'What are the two **مجرورات**?', choices: ['المجرور بحرف الجر (﴿بالقسطِ﴾) and المجرور بالإضافة (﴿أجيب دعوةَ الداعِ﴾)', 'المجرور بالتبعية and بالأصالة', 'التمييز and المستثنى', 'المضاف and المضاف إليه'], correct: 0,
          why: 'Only two routes into جر for a noun.' },
        { t: 'mcq', q: 'Can the **تمييز be مجرورا**?', choices: ['Yes — ﴿في ستةِ أيامٍ﴾, مجرور by إضافة', 'No', 'Only after كم الخبرية', 'Only in poetry'], correct: 0,
          why: 'Which is why it is listed among the منصوبات only تغليبا.' },
        { t: 'mcq', q: 'What can a **redundant preposition** do to case?', choices: ['Put in جر لفظا what is مرفوع or منصوب محلا — ﴿وكفى باللهِ وكيلا﴾ (فاعل) · ﴿أن نشرك بالله من شيءٍ﴾ (مفعول به)', 'Nothing at all', 'Put a منصوب into رفع', 'Put a مجرور into نصب'], correct: 0,
          why: 'The surface case and the underlying position come apart.' },
      ],
    },

    /* ═══ 13. النعت ═══ */
    {
      id: 'bank-mm-nat',
      title: 'التوابع: النعت',
      steps: [
        { t: 'mcq', q: 'Define the **معمول بالتبعية** and its name.', choices: ['That in which the عامل operates through its متبوع — called a تابع', 'That governed directly', 'That which governs but is not governed', 'That which has no محل'], correct: 0,
          why: 'Second-hand governance, transmitted through the followed word.' },
        { t: 'mcq', q: 'List the five types of **توابع**.', choices: ['النعت · البدل · عطف البيان · المعطوف بحرف العطف · التأكيد', 'النعت · الحال · التمييز · البدل · التأكيد', 'النعت · البدل · التمييز · المستثنى · العطف', 'النعت · الخبر · الحال · البدل · العطف'], correct: 0,
          why: 'الحال and التمييز are منصوبات بالأصالة, not followers.' },
        { t: 'mcq', q: 'What are the other names of **النعت** and its متبوع?', choices: ['النعت is also the صفة; its متبوع is the منعوت or الموصوف', 'النعت is also البدل; its متبوع is the مبدل منه', 'النعت is the تأكيد; its متبوع is the مؤكَّد', 'النعت is عطف البيان; its متبوع is the معطوف عليه'], correct: 0,
          why: 'Two names for the descriptor, two for the described.' },
        { t: 'mcq', q: 'What can serve as a **نعت**?', choices: ['A مشتق with verbal meaning, or what resembles it — the demonstrative, ذو and its variants, a non-mīmī مصدر, the relative-adjective, relative pronouns beginning with همزة الوصل, and number nouns', 'Only a مشتق', 'Any noun whatever', 'Only a demonstrative'], correct: 0,
          why: 'Note the exclusion: مَن and ما are relatives but do **not** serve as نعت.' },
        { t: 'mcq', q: 'Define the **نعت الحقيقي** and its agreement rules.', choices: ['It indicates a meaning in the متبوع itself, its فاعل being a hidden pronoun; it follows the متبوع in إعراب, definiteness, gender and number — ﴿وقال رجلٌ مؤمنٌ﴾', 'It indicates a meaning in something connected to the متبوع, following it in إعراب and definiteness only', 'It agrees in gender only', 'It never agrees'], correct: 0,
          why: 'Four points of agreement — the maximum.' },
        { t: 'mcq', q: 'Define the **نعت السببي** and its agreement rules.', choices: ['It indicates a meaning in something connected to the متبوع, its فاعل being an overt noun after it; it follows the متبوع in إعراب and definiteness **only** — ﴿من هذه القريةِ الظالمِ أهلُها﴾', 'It agrees in all four respects', 'It agrees in gender and number only', 'It never agrees'], correct: 0,
          why: 'Its gender and number track its own overt agent (أهلُها), not the described noun.' },
        { t: 'mcq', q: 'What must the **نعت السببي** contain, and what may substitute for it?', choices: ['A pronoun returning to the منعوت — أل may stand in for it: ﴿شديد العقاب﴾ i.e. شديد عقابُه', 'A demonstrative', 'A number', 'Nothing is required'], correct: 0,
          why: 'The definite article does the linking work the pronoun would have done.' },
        { t: 'mcq', q: 'Can the **منعوت be deleted**?', choices: ['Yes, with the نعت standing in its place — ﴿واعملوا صالحا﴾ i.e. عملا صالحا', 'No', 'Only if it is indefinite', 'Only in poetry'], correct: 0,
          why: 'The descriptor is enough to recover the described.' },
      ],
    },

    /* ═══ 14. البدل وعطف البيان ═══ */
    {
      id: 'bank-mm-badal',
      title: 'البدل وعطف البيان',
      steps: [
        { t: 'mcq', q: 'Define **البدل**, and what is its متبوع called?', choices: ['A تابع with no intervening conjunction which is itself intended by the ruling; its متبوع is the مبدل منه', 'A تابع with a conjunction; its متبوع is the معطوف عليه', 'A تابع not intended by the ruling; its متبوع is the معطوف عليه', 'A تابع confirming its متبوع; its متبوع is the مؤكَّد'], correct: 0,
          why: '“Intended by the ruling” is what separates it from عطف البيان.' },
        { t: 'mcq', q: 'What are the four kinds of **بدل**?', choices: ['بدل الكل (﴿صراطَ الذين أنعمت عليهم﴾) · بدل البعض (﴿من آمن منهم﴾) · بدل الاشتمال (﴿قتالٍ فيه﴾) · بدل الغلط (رأيت زيدا عمرا)', 'الكل · البعض · الاشتمال · المطابق', 'المتصل · المنقطع · المفرغ · الغلط', 'الحقيقي · السببي · المؤكد · المبين'], correct: 0,
          why: 'المطابق is another name for بدل الكل, not a fifth kind.' },
        { t: 'mcq', q: 'What are the other names of **بدل الكل**?', choices: ['بدل المطابق and بدل العين من العين', 'بدل البعض and بدل الاشتمال', 'بدل الغلط', 'عطف البيان'], correct: 0,
          why: 'Substitute and substituted refer to the very same thing.' },
        { t: 'mcq', q: 'Define **بدل البعض** and **بدل الاشتمال**, and their shared condition.', choices: ['البعض — its referent is part of the متبوع’s · الاشتمال — its referent is an attribute or connected aspect of it · both require a pronoun returning to the مبدل منه, which may be deleted (﴿من استطاع إليه سبيلا﴾ i.e. منهم)', 'Neither requires a linking pronoun', 'Only بدل البعض requires one', 'Both must be definite'], correct: 0,
          why: 'The deleted منهم in the ḥajj verse is the standard illustration.' },
        { t: 'mcq', q: 'What is the status of **بدل الغلط** in eloquent speech?', choices: ['It does not occur in فصيح speech; the correction is made with بل instead — رأيت زيدا بل عمرا', 'It is the most common kind', 'It is required after a negation', 'It is used only in the Qurʾān'], correct: 0,
          why: 'A slip of the tongue is not a rhetorical device.' },
        { t: 'mcq', q: 'Define **عطف البيان**.', choices: ['A تابع with no conjunction which is NOT intended by the ruling but clarifies its متبوع (﴿كفارة طعامُ مسكين﴾); its متبوع is the معطوف عليه', 'A تابع joined by a conjunction', 'A تابع intended by the ruling', 'A تابع confirming its متبوع'], correct: 0,
          why: 'No conjunction — despite the name عطف.' },
        { t: 'mcq', q: 'What is the difference in **meaning** between البدل and عطف البيان?', choices: ['The بدل is itself intended by the ruling; عطف البيان is not — it comes only as a clarifier and specifier', 'The reverse', 'There is no difference in meaning', 'The بدل requires a conjunction'], correct: 0,
          why: 'One replaces, the other merely explains.' },
        { t: 'mcq', q: 'What is the difference in **إعراب** between البدل and عطف البيان?', choices: ['Most of what can be عطف بيان can also be بدل الكل — except that the بدل is conceived as replacing its متبوع in position; so in يا زيدُ الحارثُ, الحارث must be عطف بيان, since يا الحارث is impossible', 'They are parsed identically in every case', 'The بدل must always be definite', 'عطف البيان must be indefinite'], correct: 0,
          why: 'The test: can the follower stand in the leader’s place? If not, it is عطف بيان.' },
      ],
    },

    /* ═══ 15. العطف بحرف العطف ═══ */
    {
      id: 'bank-mm-atf',
      title: 'العطف بحرف العطف',
      steps: [
        { t: 'mcq', q: 'Define the **المعطوف بحرف العطف** and its other name.', choices: ['A تابع joined by a conjunction (﴿أطيعوا الله ورسولَه﴾); its متبوع is the معطوف عليه, and this عطف is called عطف النسق', 'A تابع with no conjunction, called عطف البيان', 'A تابع confirming its متبوع, called التأكيد', 'A تابع describing its متبوع, called النعت'], correct: 0,
          why: 'النسق = the ordered sequence produced by the conjunction.' },
        { t: 'mcq', q: 'What are the three **أقسام of العطف**?', choices: ['على اللفظ (the default) · على المحل · على المعنى (also على التوهم)', 'على الأصل · على الفرع · على النيابة', 'حقيقي · سببي · مؤكد', 'متصل · منقطع · مفرغ'], correct: 0,
          why: 'e.g. ليس زيد بقائمٍ ولا جالسٍ (لفظ) vs ولا جالسًا (محل).' },
        { t: 'mcq', q: 'What is required when conjoining to an **attached مرفوع pronoun**?', choices: ['It must first be emphasised with a detached pronoun (﴿اذهب أنتَ وأخوك﴾) — unless something separates them (﴿يدخلونها ومن صلح من آبائهم﴾)', 'The preposition must be repeated', 'Nothing is required', 'The conjunction must be الواو'], correct: 0,
          why: 'The attached pronoun is too light to bear a conjunct on its own.' },
        { t: 'mcq', q: 'What is required when conjoining to an **attached مجرور pronoun**?', choices: ['The preposition must be repeated — ﴿لها وللأرضِ﴾', 'A detached pronoun must be added', 'Nothing is required', 'The conjunct must be definite'], correct: 0,
          why: 'Different pronoun, different repair — repeat the جار, not the pronoun.' },
        { t: 'mcq', q: 'What is **قطع المعطوف**, and when is it allowed?', choices: ['Cutting the conjunct off from the إعراب of the معطوف عليه, for praise or blame — ﴿والموفون بعهدهم إذا عاهدوا والصابرين في البأساء والضراء﴾', 'Deleting the conjunction', 'Deleting the conjunct', 'Repeating the conjunction'], correct: 0,
          why: 'والصابرين breaks the رفع sequence deliberately, to single them out for praise.' },
      ],
    },

    /* ═══ 16. التأكيد ═══ */
    {
      id: 'bank-mm-tawkid',
      title: 'التأكيد',
      steps: [
        { t: 'mcq', q: 'Define **التأكيد**, its other name and its متبوع.', choices: ['That which confirms its متبوع in what is attributed to it (جاء الأمير نفسُه) or confirms inclusion of every member (جاء الرجال كلُّهم); also التوكيد, and its متبوع is the مؤكَّد', 'That which describes its متبوع; its متبوع is the منعوت', 'That which replaces its متبوع; its متبوع is the مبدل منه', 'That joined by a conjunction; its متبوع is the معطوف عليه'], correct: 0,
          why: 'Two jobs: removing doubt about the attribution, and blocking a partial reading.' },
        { t: 'mcq', q: 'What are the two kinds of **تأكيد**?', choices: ['اللفظي and المعنوي', 'الحقيقي and السببي', 'الكل and البعض', 'المتصل and المنقطع'], correct: 0,
          why: 'By repetition of wording, or by a fixed set of emphasising words.' },
        { t: 'mcq', q: 'How is **لفظي** emphasis done with a **verb**?', choices: ['By repeating the verb itself — قام قام زيد', 'By adding نفس', 'By adding كل', 'By adding a detached pronoun'], correct: 0,
          why: 'The simplest case: say it twice.' },
        { t: 'mcq', q: 'How is لفظي emphasis done with an **overt noun**?', choices: ['By repeating the same word (﴿والسابقون السابقون﴾) or a synonym (﴿ضيقا حرجا﴾)', 'Only by repeating the same word', 'Only by a synonym', 'By adding نفس or عين'], correct: 0,
          why: 'Synonym-repetition counts as لفظي, not معنوي.' },
        { t: 'mcq', q: 'How is لفظي emphasis done with **pronouns**?', choices: ['Detached: repeat the same word (إياك إياك أردت) · attached مرفوع: repeat with a detached مرفوع (ذهبتُ أنا) · attached منصوب: with a detached مرفوع or منصوب (أكرمتك أنتَ / إياك) · attached مجرور: with a detached مرفوع or by repeating the جار والمجرور (مررت بك أنت / بك بك)', 'Always by repeating the same pronoun', 'Always with a detached مرفوع', 'Pronouns cannot be emphasised'], correct: 0,
          why: 'Four pronoun types, four repair strategies.' },
        { t: 'mcq', q: 'How is لفظي emphasis done with **particles**?', choices: ['A non-governing response particle: repeat it alone (لا لا أشركُ بالله) · other particles: repeat with whatever attached to the مؤكد (﴿أنكم إذا متم… أنكم مخرجون﴾), not إنَّ إنَّ زيدا قائم', 'Always repeat the particle alone', 'Particles cannot be emphasised', 'Always repeat with the whole clause'], correct: 0,
          why: 'A governing particle cannot stand twice without its noun.' },
        { t: 'mcq', q: 'How is لفظي emphasis done with a **sentence**?', choices: ['By repeating the first sentence (﴿فإن مع العسر يسرا ۝ إن مع العسر يسرا﴾), sometimes with ثم (﴿كلا سيعلمون ۝ ثم كلا سيعلمون﴾)', 'By adding كل', 'By adding a detached pronoun', 'Sentences cannot be emphasised'], correct: 0,
          why: 'Whole-clause repetition, with or without a linking ثم.' },
        { t: 'mcq', q: 'Which is preferred: **التأسيس or التأكيد**?', choices: ['التأسيس أولى من التأكيد — a new meaning is preferable to emphasis', 'التأكيد is preferred', 'They are equal', 'It depends on the sentence type'], correct: 0,
          why: 'An interpretive principle: prefer the reading that adds content.' },
        { t: 'mcq', q: 'Define **التأكيد المعنوي** and list its words.', choices: ['Emphasis by specific words annexed to a pronoun agreeing with the مؤكد — نفس، عين، كلا، كلتا، كل', 'Emphasis by repeating the word', 'Emphasis by a synonym', 'Emphasis by a detached pronoun'], correct: 0,
          why: 'Five words, each requiring an agreeing pronoun.' },
        { t: 'mcq', q: 'What are **كلا and كلتا** used for?', choices: ['The dual only — جاء الرجلان كلاهما · ورأيت البنتين كلتيهما', 'The plural only', 'The singular only', 'Any number'], correct: 0,
          why: 'Masculine dual and feminine dual respectively.' },
        { t: 'mcq', q: 'How are **نفس and عين** used across numbers?', choices: ['Singular: نفسُه وعينُه · dual: أنفسُهما وأعينُهما (plural forms) · plural: أنفسُهم وأعينُهم', 'They are invariable', 'Dual takes نفساهما', 'They are used for the dual only'], correct: 0,
          why: 'Note the dual takes the **plural** form of the emphasiser.' },
        { t: 'mcq', q: 'What is required when emphasising an **attached مرفوع pronoun** with نفس or عين?', choices: ['It must first be emphasised لفظيا with a detached pronoun — الأمير ينظف المسجد هو نفسُه', 'Nothing further is required', 'A preposition must be repeated', 'It cannot be emphasised'], correct: 0,
          why: 'Same principle as conjoining to an attached مرفوع pronoun.' },
        { t: 'mcq', q: 'If **نفس and عين are combined**, what is the order?', choices: ['عين comes after نفس — جاء زيد نفسُه عينُه', 'نفس after عين', 'Either order', 'They cannot be combined'], correct: 0,
          why: 'A fixed sequence.' },
        { t: 'mcq', q: 'Can نفس and عين take a **redundant باء**?', choices: ['Yes — جاء الرجل بنفسِه', 'No', 'Only نفس can', 'Only in poetry'], correct: 0,
          why: 'One of the five قياسي positions of the redundant bāʾ (التأكيد المعنوي).' },
        { t: 'mcq', q: 'What role do **أجمع، جمعاء، أجمعون، جُمَع** play?', choices: ['Emphasis (﴿لأغوينهم أجمعين﴾) — and they may reinforce كل (﴿فسجد الملائكة كلُّهم أجمعون﴾)', 'They are أحوال', 'They are توابع for description', 'They are تمييز'], correct: 0,
          why: 'They can stand alone or stack onto كل.' },
        { t: 'mcq', q: 'What is the function and إعراب of **جميع**?', choices: ['It conveys the sense of emphasis but is parsed as a حال مؤكدة — ﴿خلق لكم ما في الأرض جميعا﴾', 'It is a تأكيد معنوي', 'It is a تمييز', 'It is a بدل'], correct: 0,
          why: 'Meaning and parsing part company here.' },
        { t: 'mcq', q: 'Which **further followers of أجمع** are mentioned?', choices: ['أكتع and أبصع', 'أجمعون and جُمَع', 'نفس and عين', 'كلا and كلتا'], correct: 0,
          why: 'Reinforcers stacked after أجمع for maximum emphasis.' },
      ],
    },

    /* ═══ 17. خاتمة التوابع + غير المعمول ═══ */
    {
      id: 'bank-mm-khatima-tawabi',
      title: 'خاتمة التوابع · غير المعمول من الاسم والفعل',
      steps: [
        { t: 'mcq', q: 'May the تابع follow the **لفظ or the محل** of its متبوع?', choices: ['Either — the لفظ (ما أنا بكاذبٍ ولا خادعٍ) or the محل (﴿هل من خالقٍ غيرُ الله﴾, غير following the رفع position of خالق)', 'The لفظ only', 'The محل only', 'Neither — it must match the case exactly'], correct: 0,
          why: 'The redundant مِن lowers خالق in wording only; its position is رفع.' },
        { t: 'mcq', q: 'Can the تابع follow the محل the متبوع had **before a ناسخ** entered?', choices: ['Yes — ﴿أن اللهَ بريءٌ من المشركين ورسولُه﴾, ورسوله following the رفع the divine name had before أنّ', 'No', 'Only after كان', 'Only in poetry'], correct: 0,
          why: 'A third layer: current wording, current position, and the pre-ناسخ position.' },
        { t: 'mcq', q: 'What is the **غير معمول among nouns**?', choices: ['اسم الفعل — ﴿قل هلمَّ شهداءَكم﴾: it governs but is not governed', 'The مضاف إليه', 'The تمييز', 'The منادى'], correct: 0,
          why: 'The one noun class that takes no case of its own.' },
        { t: 'mcq', q: 'In what way can the **verb be معمول**?', choices: ['Only بالأصالة — verbs have no معمول بالتبعية category, since they are not توابع', 'Both بالأصالة and بالتبعية', 'Only بالتبعية', 'Verbs are never معمول'], correct: 0,
          why: 'The five توابع are all nominal.' },
        { t: 'mcq', q: 'What are the three أقسام of the **معمول verb**?', choices: ['مرفوع — the مضارع free of a ناصب and جازم (يحب الله التوبةَ) · منصوب (﴿يريد الله أن يغفر لكم﴾) · مجزوم (إن تتب تقبلْ توبتك)', 'مرفوع · منصوب · مجرور', 'ماضٍ · مضارع · أمر', 'تام · ناقص · جامد'], correct: 0,
          why: 'Jazm replaces جر on the verbal side.' },
        { t: 'mcq', q: 'Which verbs are **غير معمول**?', choices: ['The ماضي free of governors (آمنت بالله) and the أمر expressed by its form (اتقوا الله)', 'The مضارع and the أمر', 'All verbs are معمول', 'Only the ماضي'], correct: 0,
          why: 'Both are مبني with no governor acting on them.' },
        { t: 'mcq', q: 'What is the status of the **أمر باللام** and the **نهي**?', choices: ['Both are معمول — مجزوم: لِيذهبْ محمد إلى المسجد · ولا يكسلْ عن الصلاة', 'Both are غير معمول', 'The أمر باللام is معمول but the نهي is not', 'Both are منصوب'], correct: 0,
          why: 'The particle supplies a governor that the bare imperative form lacks.' },
      ],
    },

    /* ═══ 18. الجملة المعمولة ═══ */
    {
      id: 'bank-mm-jumla-mamula',
      title: 'الجملة المعمولة (ذات المحل)',
      steps: [
        { t: 'mcq', q: 'What is the **معمول sentence** called?', choices: ['الجملة التي لها محل من الإعراب', 'الجملة المستأنفة', 'الجملة الابتدائية', 'الجملة المعترضة'], correct: 0,
          why: 'Having a grammatical position is exactly what makes it governed.' },
        { t: 'mcq', q: 'In which two positions is a sentence **مرفوعة بالأصالة**?', choices: ['خبر المبتدأ (﴿والله يحب المحسنين﴾) and خبر إنّ (﴿إن الله يحب المحسنين﴾)', 'المفعول به and الحال', 'المضاف إليه and جواب الشرط', 'النعت and البدل'], correct: 0,
          why: 'Both are predicate slots, hence رفع.' },
        { t: 'mcq', q: 'In which four positions is a sentence **منصوبة بالأصالة**?', choices: ['المفعول به (﴿قال الله هذا يومُ ينفع الصادقين صدقُهم﴾) · المفعول له (﴿لعلكم تفلحون﴾) · الحال (طاف رسول الله ﷺ بالبيت وهو يلبي) · خبر الفعل الناقص (﴿كانوا يعملون﴾)', 'خبر المبتدأ · خبر إنّ · الحال · النعت', 'المضاف إليه · جواب الشرط · البدل · العطف', 'الصلة · المعترضة · التفسيرية · جواب القسم'], correct: 0,
          why: 'The last option lists clauses with **no** محل at all.' },
        { t: 'mcq', q: 'What is the clause functioning as **مفعول به of a verb of saying** called?', choices: ['مقول, مقول القول, or مقولة', 'الجملة التعليلية', 'الجملة التفسيرية', 'الجملة المعترضة'], correct: 0,
          why: 'Three names for the same reported speech.' },
        { t: 'mcq', q: 'What is the clause functioning as **مفعول له** called?', choices: ['الجملة التعليلية — ﴿واتقوا الله لعلكم تفلحون﴾', 'مقول القول', 'الجملة التفسيرية', 'الجملة الحالية'], correct: 0,
          why: 'It supplies the reason for the action.' },
        { t: 'mcq', q: 'In which three cases is the **wāw of the جملة حالية obligatory**?', choices: ['The clause has no pronoun linking to the owner (﴿ونحن عصبةٌ﴾) · it is nominal beginning with the owner’s pronoun (﴿وأنتم سكارى﴾) · it is a مضارع clause with قد (﴿وقد تعلمون أني رسول الله﴾)', 'After a coordinator · after إلا · before أو', 'Whenever the clause is verbal', 'It is never obligatory'], correct: 0,
          why: 'Without a linking pronoun, only the wāw can attach the clause to its owner.' },
        { t: 'mcq', q: 'In which cases is the wāw of the جملة حالية **prohibited**?', choices: ['After a coordinator · when the clause confirms the preceding one · a ماضي clause after إلا · a ماضي clause before أو · an affirmative مضارع clause without قد · a مضارع clause negated by ما · a مضارع clause negated by لا', 'The three obligatory cases', 'Whenever the clause is nominal', 'It is never prohibited'], correct: 0,
          why: 'Seven cases — e.g. ﴿ولا تمنن تستكثر﴾ and ﴿وما لي لا أعبد الذي فطرني﴾.' },
        { t: 'mcq', q: 'What are the wāw rules for a حال مضارع clause **negated by لم**?', choices: ['Both are allowed — with the wāw (﴿قل أوحي إليَّ ولم يوحَ إليه شيء﴾) or without it (﴿لم يمسسهم سوءٌ﴾)', 'The wāw is obligatory', 'The wāw is prohibited', 'The clause cannot be a حال'], correct: 0,
          why: 'A genuine free choice, unlike the ما and لا cases.' },
        { t: 'mcq', q: 'What is **preferred** for a حال clause negated by **لمّا**?', choices: ['The wāw — ﴿ولمّا يعلمِ اللهُ الذين جاهدوا منكم﴾', 'Omitting the wāw', 'Either equally', 'The clause cannot be a حال'], correct: 0,
          why: 'Preference rather than obligation.' },
        { t: 'mcq', q: 'What is the rule for a **nominal حال clause not starting with the owner’s pronoun**?', choices: ['Predominantly with the wāw (﴿ولقد نصركم الله ببدر وأنتم أذلةٌ﴾), sometimes without (﴿اهبطوا بعضُكم لبعض عدوٌّ﴾)', 'Always with the wāw', 'Always without', 'It cannot be a حال'], correct: 0,
          why: 'Predominance, with attested exceptions.' },
        { t: 'mcq', q: 'What are the rules for an **affirmative ماضي حال clause**?', choices: ['Predominantly with wāw and قد (﴿وقد هدانِ﴾) · sometimes wāw alone (﴿واتبعك الأرذلون﴾) · sometimes neither (﴿ردت إلينا﴾)', 'Always wāw and قد', 'Always neither', 'It cannot be a حال'], correct: 0,
          why: 'Three grades, decreasing in frequency.' },
        { t: 'mcq', q: 'In which position is a sentence **مجرورة بالأصالة**?', choices: ['As مضاف إليه — ﴿هذا يومُ ينفعُ الصادقين صدقُهم﴾', 'As a خبر', 'As a حال', 'As a جواب الشرط'], correct: 0,
          why: 'Only annexation lowers a clause.' },
        { t: 'mcq', q: 'In which position is a sentence **مجزومة بالأصالة**, and what is required?', choices: ['As the جواب of a jazm-conditional, provided it is linked by a رابطة — the فاء or إذا الفجائية: ﴿من يضلل اللهُ فلا هاديَ له﴾', 'As a خبر, with no requirement', 'As a مضاف إليه', 'Sentences are never مجزومة'], correct: 0,
          why: 'Without the linker, the answer clause has no محل at all.' },
        { t: 'mcq', q: 'When is the **فاء obligatory** in the جواب الشرط?', choices: ['When the answer is nominal · verbal with a frozen verb · a request (أمر/نهي) · an affirmative ماضٍ with قد, overt or implied · negated by ما · a مضارع with a تنفيس particle · negated by لن · opening with كأنما · opening with a conditional particle', 'Only when the answer is nominal', 'Only when the answer is a command', 'It is never obligatory'], correct: 0,
          why: 'Nine cases — the unifying idea is that the answer cannot itself take jazm.' },
        { t: 'mcq', q: 'When is the فاء **optional** in the جواب الشرط?', choices: ['When the answer is a مضارع — affirmative without تنفيس (﴿ومن عاد فينتقم الله منه﴾ vs ﴿يغلبوا مائتين﴾) or negated by لا', 'When the answer is nominal', 'When the answer is a ماضٍ without قد', 'Never'], correct: 0,
          why: 'The مضارع can take jazm itself, so the linker becomes dispensable.' },
        { t: 'mcq', q: 'When is the فاء **prohibited** in the جواب الشرط?', choices: ['When the answer is a ماضٍ without قد — لفظا (﴿إن أحسنتم أحسنتم لأنفسكم﴾) or معنى (لم + مضارع: إن خرجتَ لم أخرجْ)', 'When the answer is nominal', 'When the answer is a command', 'It is never prohibited'], correct: 0,
          why: 'Such an answer is already in jazm position; the فاء would break it.' },
        { t: 'mcq', q: 'What may **replace the فاء** as the answer’s linker?', choices: ['إذا الفجائية — after إن and إذا: ﴿وإن تصبهم سيئة… إذا هم يقنطون﴾', 'الواو', 'ثم', 'Nothing may replace it'], correct: 0,
          why: 'Surprise-إذا performs the same linking work.' },
        { t: 'mcq', q: 'In which three ways is a sentence **معمولة بالتبعية**?', choices: ['As a نعت (﴿يومٌ لا بيعٌ فيه﴾) · as a بدل · as a معطوفة on a clause that has a محل', 'As a خبر · as a حال · as a مفعول به', 'As a صلة · as a معترضة · as a تفسيرية', 'It never is'], correct: 0,
          why: 'The same three follower-roles available to single nouns.' },
        { t: 'mcq', q: 'What conditions apply to the **جملة النعتية**?', choices: ['It must contain a pronoun returning to the منعوت (overt or implied) · and the منعوت must be indefinite — محضة or غير محضة (﴿ملائكةٌ غلاظٌ شدادٌ لا يعصون الله ما أمرهم﴾) — or definite but في حكم النكرة (﴿كمثل الحمار يحمل أسفارا﴾)', 'The منعوت must be definite', 'No pronoun is needed', 'There are no conditions'], correct: 0,
          why: 'A clause describing a definite noun would be a حال, not a نعت.' },
        { t: 'mcq', q: 'From what may a **جملة بدل** be substituted?', choices: ['From a single noun (﴿أفلا ينظرون إلى الإبل كيف خُلقت﴾) or from a clause that has a محل (﴿يسومونكم سوءَ العذاب يذبحون أبناءكم﴾)', 'From a single noun only', 'From a clause only', 'It cannot be a بدل'], correct: 0,
          why: 'Both a word and a clause can be the thing substituted for.' },
        { t: 'mcq', q: 'Give the example of a **clause conjoined to a clause with a محل**.', choices: ['«الصلاةُ نورٌ والصدقةُ برهانٌ» — والصدقة برهان conjoined to a clause that has a محل', '﴿واتقوا الذي أمدكم بما تعلمون ۝ أمدكم بأنعام وبنين﴾', '﴿أفلا ينظرون إلى الإبل كيف خلقت﴾', '﴿يومٌ لا بيعٌ فيه﴾'], correct: 0,
          why: 'The second option is a clause following one with **no** محل — the eighth type in the next section.' },
      ],
    },

    /* ═══ 19. الجملة غير المعمولة ═══ */
    {
      id: 'bank-mm-jumla-ghayr',
      title: 'الجملة غير المعمولة (لا محل لها)',
      steps: [
        { t: 'mcq', q: 'What is the **غير معمولة** sentence called, and how many types?', choices: ['الجملة التي لا محل لها من الإعراب — eight types', 'الجملة ذات المحل — five types', 'الجملة المستأنفة — three types', 'الجملة المعترضة — eight types'], correct: 0,
          why: 'Eight is the number to hold on to.' },
        { t: 'mcq', q: 'Which list gives the **eight** clauses with no محل?', choices: ['الابتدائية · المستأنفة · صلة الموصول · المعترضة · التفسيرية · جواب القسم · جواب الشرط غير الجازم (or الجازم without a linker) · التابعة لما لا محل له', 'الخبر · الحال · المفعول به · المضاف إليه · النعت · البدل · المعطوفة · جواب الشرط', 'الابتدائية · المستأنفة · الصلة · النعت · البدل · الحال · الخبر · التفسيرية', 'Five only: الابتدائية، الصلة، المعترضة، التفسيرية، جواب القسم'], correct: 0,
          why: 'The second option lists clauses that **do** have a محل.' },
        { t: 'mcq', q: 'Define the **جملة الابتدائية**.', choices: ['The sentence with which speech begins — ﴿إنا أنزلناه في ليلة القدر﴾', 'A sentence mid-speech, disconnected in إعراب', 'A relative clause', 'A clause interposed between two connected elements'], correct: 0,
          why: 'Nothing precedes it, so nothing can govern it.' },
        { t: 'mcq', q: 'Define the **جملة المستأنفة**.', choices: ['A sentence occurring mid-speech but disconnected in إعراب from what precedes — conjoined to a clause with no محل (اجتهد زيدٌ ونجح) or not conjoined (﴿وما أبرئ نفسي إن النفس لأمارة بالسوء﴾)', 'The sentence that opens the speech', 'A relative clause', 'A clause explaining what precedes it'], correct: 0,
          why: 'A fresh start in the middle of a discourse.' },
        { t: 'mcq', q: 'Which type does **جواب النداء** belong to?', choices: ['المستأنفة — ﴿يا أيها الناس اعبدوا ربكم﴾ (جواب القسم is likewise listed among المستأنفة)', 'الابتدائية', 'التفسيرية', 'المعترضة'], correct: 0,
          why: 'Grouped together because both start afresh after their opener.' },
        { t: 'mcq', q: 'List the **حروف الاستئناف**.', choices: ['الواو · ثم · حتى · أم المنقطعة · بل الانتقالية · أو بمعنى بل · لكن المجردة عن الواو', 'الفاء · اللام · قد · السين', 'ألا · أما · ها', 'إن · أن · كأن · لكن'], correct: 0,
          why: 'Seven openers, several of them also serving as coordinators elsewhere.' },
        { t: 'mcq', q: 'What relationship holds between **المستأنفة and الابتدائية**?', choices: ['The term المستأنفة may also be applied to the ابتدائية', 'They are mutually exclusive', 'الابتدائية has a محل, المستأنفة does not', 'They are unrelated'], correct: 0,
          why: 'Overlapping terminology — worth knowing so a text using either is not misread.' },
        { t: 'mcq', q: 'Define **صلة الموصول**.', choices: ['The clause forming the relative clause — ﴿اعبدوا ربكم الذي خلقكم﴾, where خلقكم has no محل', 'A clause explaining what precedes', 'A clause interposed between connected elements', 'The answer of an oath'], correct: 0,
          why: 'The موصول and its صلة together fill one slot; the clause alone has none.' },
        { t: 'mcq', q: 'Define the **جملة المعترضة**.', choices: ['A sentence interposed between two connected elements — ﴿فإن لم تفعلوا ولن تفعلوا فاتقوا النار﴾', 'A sentence opening the speech', 'A relative clause', 'The answer of a condition'], correct: 0,
          why: 'ولن تفعلوا sits between the condition and its answer.' },
        { t: 'mcq', q: 'Define the **جملة التفسيرية** and its two forms.', choices: ['A sentence explaining what precedes — with an explanatory particle (﴿وناديناه أن يا إبراهيم﴾) or without (﴿مستهم البأساء والضراء﴾)', 'A clause answering an oath', 'A clause interposed between connected elements', 'A relative clause'], correct: 0,
          why: 'The particle is optional; the explanatory function is what matters.' },
        { t: 'mcq', q: 'What are the three **أركان of القسم**?', choices: ['فعل القسم (usually deleted) · المقسم به (these two forming the قسم) · المقسم عليه (the جواب)', 'The particle · the منادى · the answer', 'The condition · the answer · the linker', 'The oath · the negation · the emphasis'], correct: 0,
          why: 'Verb plus object of the oath, then the content sworn to.' },
        { t: 'mcq', q: 'What indicates a **deleted قسم** before the answer?', choices: ['The لام of the oath (اللام الموطئة للقسم) entering the answer — ﴿ولسوف يعطيك ربك فترضى﴾', 'The particle قد', 'A negation', 'A conditional particle'], correct: 0,
          why: 'The lām is the fingerprint of an unstated oath.' },
        { t: 'mcq', q: 'With what may **جواب القسم** be opened?', choices: ['إن المشددة · إن المخففة · قد · the open lām · ما النافية · لا النافية', 'الفاء · الواو · ثم · حتى', 'ألا · أما · ها', 'إذا الفجائية only'], correct: 0,
          why: 'Six openers, three affirmative and two negative plus the emphatic lām.' },
        { t: 'mcq', q: 'When is **نون التوكيد obligatory** in جواب القسم?', choices: ['When the answer is affirmative and not separated from the lām — ﴿وتالله لأكيدنَّ أصنامكم﴾', 'Always', 'Never', 'Only after a negation'], correct: 0,
          why: 'Affirmative plus adjacency: both conditions must hold.' },
        { t: 'mcq', q: 'When is **نون التوكيد prohibited** in جواب القسم?', choices: ['When the answer is not affirmative (﴿لا يبعث الله من يموت﴾) · when it has no lām (﴿تالله تفتؤا تذكر يوسف﴾) · when it is separated from the lām (﴿ولسوف يعطيك ربك﴾)', 'Only after a negation', 'Only when the lām is absent', 'It is never prohibited'], correct: 0,
          why: 'Exactly the negation of the two conditions above, plus separation.' },
        { t: 'mcq', q: 'When **قسم and شرط combine**, which gets the answer?', choices: ['Whichever came first; the other’s answer is deleted, indicated by the one mentioned', 'The شرط always', 'The قسم always', 'Both get answers'], correct: 0,
          why: 'Order of appearance decides.' },
        { t: 'mcq', q: 'In ﴿لَئِنْ أُخْرِجُوا لَا يَخْرُجُونَ مَعَهُمْ﴾, why is لا يخرجون **not مجزوم**?', choices: ['Because it is the answer of the oath (implied by the lām, which precedes the condition), not the answer of the condition', 'Because لا blocks jazm', 'Because the verb is plural', 'Because the condition is ماضٍ'], correct: 0,
          why: 'The lām on لئن signals a prior oath, which claims the answer.' },
        { t: 'mcq', q: 'When a **قسم precedes a شرط**, what must the verb after the conditional particle be?', choices: ['A ماضٍ — لفظا (والله إن أتيتني لأكرمنك) or معنى (لم + مضارع: والله إن لم تأتني لهجرتُك)', 'A مضارع', 'An أمر', 'There is no restriction'], correct: 0,
          why: 'A مضارع there would demand a jazm answer that the oath has already claimed.' },
        { t: 'mcq', q: 'Which **conditional answers** have no محل من الإعراب?', choices: ['The answer of a non-jazm conditional (﴿ولو شئنا لرفعناه بها﴾) and the answer of a jazm-conditional not linked by فاء or إذا الفجائية (إن تجتهد تنجحْ)', 'All conditional answers have a محل', 'Only the answer of لو', 'Only linked answers'], correct: 0,
          why: 'Jazm on the verb itself is not the same as the clause occupying a slot.' },
        { t: 'mcq', q: 'Define the eighth type, **التابعة لما لا محل له**.', choices: ['A clause following (e.g. conjoined to) a clause that has no محل — ﴿واتقوا الذي أمدكم بما تعلمون ۝ أمدكم بأنعام وبنين﴾, the second أمدكم following the صلة', 'A clause conjoined to one that has a محل', 'A clause explaining what precedes', 'A relative clause'], correct: 0,
          why: 'The follower inherits its leader’s lack of position.' },
      ],
    },

    /* ═══ 20. شبه الجملة ═══ */
    {
      id: 'bank-mm-shibh',
      title: 'شبه الجملة',
      steps: [
        { t: 'mcq', q: 'What is the ruling of **شبه الجملة** regarding العمل?', choices: ['All أشباه الجمل are معمول — none is غير معمول', 'All are غير معمول', 'Some are, some are not', 'They govern rather than being governed'], correct: 0,
          why: 'One of the two absolutes from the chapter’s introduction.' },
        { t: 'mcq', q: 'What are the two types of **ظرف** in the شبه جملة sense?', choices: ['اللغو — attached to a mentioned عامل · المستقر — attached to an obligatorily deleted general عامل (كائن/استقر)', 'المبهم and المحدود', 'الزماني and المكاني', 'الحقيقي and السببي'], correct: 0,
          why: 'The division introduced back in the المقدمة, now put to work.' },
        { t: 'mcq', q: 'In which single position is the **ظرف اللغو مرفوع محلا**?', choices: ['As نائب الفاعل — ﴿وجيء يومئذ بجهنم﴾', 'As خبر المبتدأ', 'As الحال', 'As المفعول به'], correct: 0,
          why: 'One position only, since لغو adverbs are otherwise all منصوب محلا.' },
        { t: 'mcq', q: 'In which seven positions is the **ظرف اللغو منصوب محلا**?', choices: ['المفعول المطلق · به · فيه · له · معه · الحال · التمييز', 'خبر المبتدأ · خبر إنّ · الحال · النعت', 'النعت · البدل · العطف · التأكيد', 'الفاعل · نائب الفاعل · المبتدأ'], correct: 0,
          why: 'The five objects plus حال and تمييز — e.g. ﴿عفا الله عنك﴾ (به) and ﴿تفيض من الدمع﴾ (تمييز).' },
        { t: 'mcq', q: 'In which two positions is the **ظرف المستقر مرفوع بالأصالة**?', choices: ['خبر المبتدأ (إنما العلمُ عند الله) and خبر إنّ (﴿إن الله معنا﴾)', 'الحال and النعت', 'نائب الفاعل and الفاعل', 'المفعول به and المفعول فيه'], correct: 0,
          why: 'Both predicate slots, matching the clause rules.' },
        { t: 'mcq', q: 'In which two positions is the **ظرف المستقر منصوب بالأصالة**?', choices: ['خبر الفعل الناقص (﴿وكنتم على شفا حفرةٍ من النار﴾) and الحال (أسأل اللهَ برجاءِ الفردوس في الجنة)', 'خبر المبتدأ and خبر إنّ', 'المفعول به and المفعول له', 'النعت and البدل'], correct: 0,
          why: 'The two نصب slots a predicate-like phrase can fill.' },
        { t: 'mcq', q: 'How can a **ظرف مستقر be معمول بالتبعية**?', choices: ['As a نعت — ﴿أولئك على هدىً من ربهم﴾, من ربهم being a نعت of هدى', 'As a بدل only', 'As a تأكيد only', 'It never can'], correct: 0,
          why: 'The quasi-clause describes the indefinite noun before it.' },
        { t: 'mcq', q: 'When may a **موصوف be deleted** leaving its صفة (with a شبه جملة)?', choices: ['When the صفة is a ظرف مستقر with مِن or في — ﴿وإن منكم إلا واردُها﴾ i.e. وإن أحدٌ كائنٌ منكم', 'Whenever the موصوف is definite', 'Never', 'Only in poetry'], correct: 0,
          why: 'The verse is unreadable until the omitted أحدٌ كائنٌ is restored.' },
        { t: 'mcq', q: 'How is a **شبه جملة after a معرفة** parsed?', choices: ['As a حال — أسأل اللهَ الفردوسَ في الجنة', 'As a نعت', 'As a بدل', 'As a تمييز'], correct: 0,
          why: 'A definite noun cannot take a نعت that is a quasi-clause.' },
        { t: 'mcq', q: 'How is a **شبه جملة after a نكرة** parsed?', choices: ['As a نعت (أسأل اللهَ بيتا في الجنة) — unless it precedes the noun, in which case it is a حال (أسأل اللهَ في الجنةِ بيتا)', 'Always as a حال', 'Always as a بدل', 'Always as a تمييز'], correct: 0,
          why: 'Position flips the analysis.' },
        { t: 'mcq', q: 'How is a **شبه جملة after a نكرة غير محضة** parsed?', choices: ['Either way — حال or نعت: ﴿وقال رجلٌ مؤمنٌ من آل فرعون﴾', 'حال only', 'نعت only', 'Neither is possible'], correct: 0,
          why: 'A “not purely indefinite” noun sits between the two rules, so both apply.' },
        { t: 'mcq', q: 'What is **المنصوب بنزع الخافض**?', choices: ['A noun put in نصب by removal of a preposition — نصب لفظا (﴿لأقعدنَّ لهم صراطَك المستقيم﴾ = على صراطك) or نصب محلا (﴿أوعجبتم أن جاءكم ذكرٌ من ربكم﴾ = من أن جاءكم)', 'A noun lowered by a redundant preposition', 'A noun raised after a ناسخ', 'An adverb with a deleted general governor'], correct: 0,
          why: 'The preposition goes, and its noun jumps from جر to نصب.' },
        { t: 'mcq', q: 'What is the **removal of the خافض** also called?', choices: ['الحذف · الإيصال · الاتساع', 'التعليق · الإلغاء · الإعمال', 'الترخيم · الندبة · الاستغاثة', 'الإضمار · الإظهار · الإبدال'], correct: 0,
          why: 'Three names for one operation, all used interchangeably in the books.' },
      ],
    },
  ],
});
