/* ── al-Kubrā fī an-Naḥw — المقصد الثاني في المعمول وغير المعمول (pp. 130–145) ──
   Aim Two: the governed and the ungoverned. This slice covers the tail of the
   المرفوعات (المبتدأ · الخبر) and the whole opening of the المنصوبات list:
   المفعول المطلق · به · فيه · له · معه · الحال · التمييز، then the start of
   المستثنى (continues p.146 onward). Reuses shared glyphs from muqaddimah.js.
   مسألة/فائدة commentary boxes & footnotes omitted (p.10-onward rule).           */

const DATA_M2A = [
  { t: 'page', n: '١٣٠' },
  { t: 'h1', ar: 'الْمَقْصِدُ الثَّانِي فِي الْمَعْمُولِ وَغَيْرِ الْمَعْمُولِ', en: 'Aim Two — On the Governed and the Ungoverned (continued)' },

  { t: 'box', label: 'الاتصال', labelEn: 'connectedness', lines: [
    [ { a: 'وَفِي', t: 'wa-fī', e: 'and in' }, { a: 'نَحْوِ', t: 'naḥwi', e: 'the like of' }, { g: ':' },
      { a: 'زَارَ', t: 'zāra', e: 'visited' }, { a: 'مُوسَى', t: 'mūsā', e: 'Mūsā' }, { a: 'عِيسَى،', t: 'ʿīsā', e: 'ʿĪsā' },
      { a: 'وَزَارَتْ', t: 'wa-zārat', e: 'and visited' }, { a: 'هَذِهِ', t: 'hādhihi', e: 'this (f.)' }, { a: 'تِلْكَ', t: 'tilka', e: 'that (f.)' },
      { a: 'لِلِالْتِبَاسِ', t: 'li-l-iltibāsi', e: 'because of the ambiguity' }, ELL ],
    [ { a: 'بِخِلَافِ', t: 'bi-khilāfi', e: 'unlike' }, ELL ],
    [ { a: 'أَكَلَ', t: 'akala', e: 'ate' }, { a: 'الْكُمَّثْرَى', t: 'al-kummathrā', e: 'the pear' }, { a: 'مُوسَى', t: 'mūsā', e: 'Mūsā' },
      { a: 'لِقَرِينَةٍ', t: 'li-qarīnatin', e: 'because of an indicator' }, { a: 'مَعْنَوِيَّةٍ', t: 'maʿnawiyyatin', e: 'that is semantic' } ],
    [ { a: 'أَوْ', t: 'aw', e: 'or' }, { a: 'نَصَرَتْ', t: 'naṣarat', e: 'helped' }, { a: 'مُوسَى', t: 'mūsā', e: 'Mūsā' }, { a: 'سَلْمَى', t: 'salmā', e: 'Salmā' },
      { a: 'لِقَرِينَةٍ', t: 'li-qarīnatin', e: 'because of an indicator' }, { a: 'لَفْظِيَّةٍ', t: 'lafẓiyyatin', e: 'that is verbal' } ],
    [ { a: 'وَهَذَا', t: 'wa-hādhā', e: 'and this' }, { a: 'يَجْرِي', t: 'yajrī', e: 'applies' }, { a: 'فِي', t: 'fī', e: 'to' }, { a: 'اسْمِ', t: 'ismi', e: 'the noun of' },
      { a: 'كَانَ', t: 'kāna', e: 'kāna' }, { a: 'وَأَخَوَاتِهَا،', t: 'wa-akhawātihā', e: 'and its sisters' },
      NAHW, { g: ':' }, OPEN, { a: 'فَمَا', t: 'fa-mā', e: 'so did not', q: 1 }, { a: 'زَالَتْ', t: 'zālat', e: 'cease', q: 1 }, { a: 'تِلْكَ', t: 'tilka', e: 'that', q: 1 }, { a: 'دَعْوَاهُمْ', t: 'daʿwāhum', e: 'their cry', q: 1 }, CLOSE ],
  ] },

  { t: 'line', w: [
    { a: 'الثَّانِي', t: 'ath-thānī', e: 'the second (is)', c: 'red' },
    { a: 'نَائِبُ', t: 'nāʾibu', e: 'the deputy of' }, { a: 'الْفَاعِلِ،', t: 'al-fāʿili', e: 'the agent' },
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' }, { a: 'مَا', t: 'mā', e: 'what' }, { a: 'نُسِبَ', t: 'nusiba', e: 'is attributed' }, { a: 'إِلَيْهِ', t: 'ilayhi', e: 'to it' }, ELL,
  ] },
  { t: 'box', lines: [
    [ { a: 'الْفِعْلُ', t: 'al-fiʿlu', e: 'the verb' }, { a: 'التَّامُّ', t: 'at-tāmmu', e: 'complete' }, { a: 'الْمَجْهُولُ', t: 'al-majhūlu', e: 'whose agent is unknown' }, { a: 'فَاعِلُهُ،', t: 'fāʿiluhu', e: '(passive)' },
      NAHW, { g: ':' }, OPEN, { a: 'وَجُمِعَ', t: 'wa-jumiʿa', e: 'and are joined', q: 1 }, { a: 'الشَّمْسُ', t: 'ash-shamsu', e: 'the sun', q: 1 }, { a: 'وَالْقَمَرُ', t: 'wa-l-qamaru', e: 'and the moon', q: 1 }, CLOSE ],
    [ { a: 'أَوْ', t: 'aw', e: 'or' }, { a: 'مَا', t: 'mā', e: 'what' }, { a: 'بِمَعْنَاهُ،', t: 'bi-maʿnāhu', e: 'is in its sense' },
      NAHW, { g: ':' }, { a: 'ذَلِكَ', t: 'dhālika', e: 'that (is)' }, { a: 'يَوْمٌ', t: 'yawmun', e: 'a day' }, { a: 'مَجْمُوعٌ', t: 'majmūʿun', e: 'gathered' }, { a: 'لَهُ', t: 'lahu', e: 'for which' }, { a: 'النَّاسُ', t: 'an-nāsu', e: 'are the people' } ],
  ] },
  { t: 'box', label: 'مثال', labelEn: 'example', lines: [
    [ { a: 'قَدْ', t: 'qad', e: 'sometimes' }, { a: 'يَكُونُ', t: 'yakūnu', e: 'is' }, { a: 'شِبْهُ', t: 'shibhu', e: 'a quasi-' }, { a: 'الْجُمْلَةِ', t: 'al-jumlati', e: 'clause' },
      { a: 'نَائِبَ', t: 'nāʾiba', e: 'the deputy of' }, { a: 'الْفَاعِلِ،', t: 'al-fāʿili', e: 'the agent' },
      NAHW, { g: ':' }, OPEN, { a: 'وَجِيءَ', t: 'wa-jīʾa', e: 'and is brought', q: 1 }, { a: 'يَوْمَئِذٍ', t: 'yawmaʾidhin', e: 'that day', q: 1 }, { a: 'بِجَهَنَّمَ', t: 'bi-jahannama', e: 'Hell', q: 1 }, CLOSE ],
  ] },

  { t: 'line', w: [
    { a: 'الثَّالِثُ', t: 'ath-thālithu', e: 'the third (is)', c: 'red' },
    { a: 'الْمُبْتَدَأُ،', t: 'al-mubtadaʾu', e: 'the subject (mubtadaʾ)' },
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' }, { a: 'اثْنَانِ', t: 'ithnāni', e: 'two (kinds)' },
  ] },
  { t: 'box', lines: [
    [ { a: 'الْأَوَّلُ', t: 'al-awwalu', e: 'the first' }, { g: ':' }, { a: 'اسْمٌ', t: 'ismun', e: 'a noun' }, { a: 'مُجَرَّدٌ', t: 'mujarradun', e: 'stripped' }, { a: 'عَنْ', t: 'ʿan', e: 'of' },
      { a: 'عَامِلٍ', t: 'ʿāmilin', e: 'a governor' }, { a: 'لَفْظِيٍّ', t: 'lafẓiyyin', e: 'verbal' }, { a: 'مُسْنَدٌ', t: 'musnadun', e: 'predicated' }, { a: 'إِلَيْهِ،', t: 'ilayhi', e: 'about' },
      NAHW, { g: ':' }, OPEN, { a: 'مُحَمَّدٌ', t: 'muḥammadun', e: 'Muḥammad', q: 1 }, { a: 'رَسُولُ', t: 'rasūlu', e: 'is the Messenger of', q: 1 }, { a: 'اللهِ', t: 'Allāhi', e: 'Allah', q: 1 }, CLOSE ],
    [ { a: 'الثَّانِي', t: 'ath-thānī', e: 'the second' }, { g: ':' }, { a: 'اسْمٌ', t: 'ismun', e: 'a noun' }, { a: 'عَامِلٌ', t: 'ʿāmilun', e: 'governing' }, { a: 'رَافِعٌ', t: 'rāfiʿun', e: 'raising' },
      { a: 'لِاسْمٍ', t: 'li-ismin', e: 'an overt' }, { a: 'ظَاهِرٍ', t: 'ẓāhirin', e: 'noun' }, { a: 'بَعْدَ', t: 'baʿda', e: 'after' }, { a: 'نَفْيٍ', t: 'nafyin', e: 'a negation' }, { a: 'أَوِ', t: 'awi', e: 'or' }, { a: 'اسْتِفْهَامٍ،', t: 'istifhāmin', e: 'a question' },
      NAHW, { g: ':' }, OPEN, { a: 'أَرَاغِبٌ', t: 'a-rāghibun', e: 'are you averse', q: 1 }, { a: 'أَنْتَ', t: 'anta', e: 'you', q: 1 }, { a: 'عَنْ', t: 'ʿan', e: 'to', q: 1 }, { a: 'آلِهَتِي', t: 'ālihatī', e: 'my gods', q: 1 }, CLOSE ],
  ] },
  { t: 'box', label: 'مثال', labelEn: 'example', lines: [
    [ { a: 'يُسَمَّى', t: 'yusammā', e: 'is called' }, { a: 'الِاسْمُ', t: 'al-ismu', e: 'the noun' }, { a: 'الْعَامِلُ', t: 'al-ʿāmilu', e: 'that governs' },
      { a: 'الْمُبْتَدَأَ', t: 'al-mubtadaʾa', e: 'the mubtadaʾ' }, { a: 'الْمُكْتَفِيَ', t: 'al-muktafiya', e: 'self-sufficient' }, { a: 'بِمَرْفُوعِهِ،', t: 'bi-marfūʿihi', e: 'through its raised noun' },
      { a: 'أَيْ', t: 'ay', e: 'i.e.' }, { a: 'لَا', t: 'lā', e: 'it has no' }, { a: 'يَكُونُ', t: 'yakūnu', e: '' }, { a: 'لَهُ', t: 'lahu', e: '' }, { a: 'خَبَرٌ', t: 'khabarun', e: 'predicate' } ],
  ] },
  { t: 'box', label: 'دخول لام التوكيد على المبتدأ', labelEn: 'the emphatic lām on the mubtadaʾ', lines: [
    [ { a: 'قَدْ', t: 'qad', e: 'sometimes' }, { a: 'تَدْخُلُ', t: 'tadkhulu', e: 'enters' }, { a: 'لَامُ', t: 'lāmu', e: 'the lām of' }, { a: 'الِابْتِدَاءِ', t: 'al-ibtidāʾi', e: 'inception' },
      { a: 'عَلَى', t: 'ʿalā', e: 'upon' }, { a: 'الْمُبْتَدَأِ،', t: 'al-mubtadaʾi', e: 'the mubtadaʾ' },
      NAHW, { g: ':' }, OPEN, { a: 'وَلَعَبْدٌ', t: 'wa-la-ʿabdun', e: 'and a believing slave', q: 1 }, { a: 'مُؤْمِنٌ', t: 'muʾminun', e: '', q: 1 }, { a: 'خَيْرٌ', t: 'khayrun', e: 'is better', q: 1 }, { a: 'مِنْ', t: 'min', e: 'than', q: 1 }, { a: 'مُشْرِكٍ', t: 'mushrikin', e: 'an idolater', q: 1 }, CLOSE ],
  ] },

  { t: 'page', n: '١٣١' },
  { t: 'box', lines: [
    [ { a: 'الْأَصْلُ', t: 'al-aṣlu', e: 'the norm' }, { a: 'فِي', t: 'fī', e: 'for' }, { a: 'الْمُبْتَدَأِ', t: 'al-mubtadaʾi', e: 'the mubtadaʾ' }, { a: 'أَنْ', t: 'an', e: 'is' }, { a: 'يَكُونَ', t: 'yakūna', e: 'to be' }, { a: 'مَعْرِفَةً،', t: 'maʿrifatan', e: 'definite' },
      { a: 'وَيَجُوزُ', t: 'wa-yajūzu', e: 'and it may' }, { a: 'أَنْ', t: 'an', e: '' }, { a: 'يَكُونَ', t: 'yakūna', e: 'be' }, { a: 'نَكِرَةً', t: 'nakiratan', e: 'indefinite' }, { a: 'مُفِيدَةً', t: 'mufīdatan', e: 'if beneficial' }, { a: 'بِأَنْ', t: 'bi-an', e: 'by' }, { a: 'تَكُونَ', t: 'takūna', e: 'its being' }, ELL ],
    [ { a: 'مَخْصُوصَةً', t: 'makhṣūṣatan', e: 'specified' } ],
    [ { a: 'بِالْإِضَافَةِ', t: 'bi-l-iḍāfati', e: 'by annexation' }, ELL ],
    [ { a: 'لَفْظًا،', t: 'lafẓan', e: 'in wording' }, NAHW, { g: ':' },
      { g: '«' }, { a: 'خَمْسُ', t: 'khamsu', e: 'five' }, { a: 'صَلَوَاتٍ', t: 'ṣalawātin', e: 'prayers' }, { a: 'كَتَبَهُنَّ', t: 'katabahunna', e: 'ordained' }, { a: 'اللهُ', t: 'Allāhu', e: 'Allah' }, { g: '»' } ],
    [ { a: 'أَوْ', t: 'aw', e: 'or' }, { a: 'تَقْدِيرًا،', t: 'taqdīran', e: 'implicitly' }, NAHW, { g: ':' },
      OPEN, { a: 'كُلٌّ', t: 'kullun', e: 'each', q: 1 }, { a: 'يَعْمَلُ', t: 'yaʿmalu', e: 'acts', q: 1 }, { a: 'عَلَى', t: 'ʿalā', e: 'upon', q: 1 }, { a: 'شَاكِلَتِهِ', t: 'shākilatihi', e: 'his manner', q: 1 }, CLOSE,
      { a: 'أَيْ', t: 'ay', e: 'i.e.' }, { a: 'كُلُّ', t: 'kullu', e: 'every' }, { a: 'أَحَدٍ', t: 'aḥadin', e: 'one' } ],
    [ { a: 'أَوْ', t: 'aw', e: 'or' }, { a: 'بِالْوَصْفِ', t: 'bi-l-waṣfi', e: 'by description' }, ELL ],
    [ { a: 'لَفْظًا،', t: 'lafẓan', e: 'in wording' }, NAHW, { g: ':' },
      OPEN, { a: 'وَلَعَبْدٌ', t: 'wa-la-ʿabdun', e: 'and a believing slave', q: 1 }, { a: 'مُؤْمِنٌ', t: 'muʾminun', e: '', q: 1 }, { a: 'خَيْرٌ', t: 'khayrun', e: 'is better', q: 1 }, { a: 'مِنْ', t: 'min', e: 'than', q: 1 }, { a: 'مُشْرِكٍ', t: 'mushrikin', e: 'an idolater', q: 1 }, CLOSE ],
    [ { a: 'أَوْ', t: 'aw', e: 'or' }, { a: 'تَقْدِيرًا،', t: 'taqdīran', e: 'implicitly' }, NAHW, { g: ':' },
      OPEN, { a: 'وَطَائِفَةٌ', t: 'wa-ṭāʾifatun', e: 'while a party', q: 1 }, { a: 'قَدْ', t: 'qad', e: '', q: 1 }, { a: 'أَهَمَّتْهُمْ', t: 'ahammat-hum', e: 'were worried by', q: 1 }, { a: 'أَنْفُسُهُمْ', t: 'anfusuhum', e: 'themselves', q: 1 }, CLOSE,
      { a: 'أَيْ', t: 'ay', e: 'i.e.' }, { a: 'طَائِفَةٌ', t: 'ṭāʾifatun', e: 'a party' }, { a: 'مِنْهُمْ', t: 'minhum', e: 'of them' } ],
    [ { a: 'أَوْ', t: 'aw', e: 'or' }, { a: 'عَامًّا', t: 'ʿāmman', e: 'general' }, { a: 'بِأَنْ', t: 'bi-an', e: 'by' }, { a: 'يَكُونَ', t: 'yakūna', e: 'its being' }, { a: 'بَعْدَ', t: 'baʿda', e: 'after' }, ELL ],
    [ { a: 'النَّفْيِ،', t: 'an-nafyi', e: 'negation' }, NAHW, { g: ':' },
      { a: 'مَا', t: 'mā', e: 'no' }, { a: 'أَحَدٌ', t: 'aḥadun', e: 'one' }, { a: 'خَيْرًا', t: 'khayran', e: 'is better' }, { a: 'مِنْ', t: 'min', e: 'than' }, { a: 'أَحَدٍ', t: 'aḥadin', e: 'another' }, { a: 'إِلَّا', t: 'illā', e: 'except' }, { a: 'بِالتَّقْوَى', t: 'bi-t-taqwā', e: 'by piety' } ],
    [ { a: 'أَوِ', t: 'awi', e: 'or' }, { a: 'الِاسْتِفْهَامِ،', t: 'al-istifhāmi', e: 'a question' }, NAHW, { g: ':' },
      OPEN, { a: 'أَإِلَهٌ', t: 'a-ilāhun', e: 'is there a god', q: 1 }, { a: 'مَعَ', t: 'maʿa', e: 'with', q: 1 }, { a: 'اللهِ', t: 'Allāhi', e: 'Allah', q: 1 }, CLOSE ],
    [ { a: 'وَإِذَا', t: 'wa-idhā', e: 'and when' }, { a: 'كَانَ', t: 'kāna', e: 'is' }, { a: 'خَبَرُهُ', t: 'khabaruhu', e: 'its predicate' }, { a: 'شِبْهَ', t: 'shibha', e: 'a quasi-' }, { a: 'جُمْلَةٍ', t: 'jumlatin', e: 'clause' }, { a: 'مُتَقَدِّمًا', t: 'mutaqaddiman', e: 'placed before' }, { a: 'عَلَيْهِ،', t: 'ʿalayhi', e: 'it' },
      NAHW, { g: ':' }, OPEN, { a: 'وَفَوْقَ', t: 'wa-fawqa', e: 'and above', q: 1 }, { a: 'كُلِّ', t: 'kulli', e: 'every', q: 1 }, { a: 'ذِي', t: 'dhī', e: 'possessor of', q: 1 }, { a: 'عِلْمٍ', t: 'ʿilmin', e: 'knowledge', q: 1 }, { a: 'عَلِيمٌ', t: 'ʿalīmun', e: 'is one more knowing', q: 1 }, CLOSE,
      { a: 'وَنَحْوُ', t: 'wa-naḥwu', e: 'and like' }, OPEN, { a: 'لِكُلِّ', t: 'li-kulli', e: 'for every', q: 1 }, { a: 'أَجَلٍ', t: 'ajalin', e: 'term', q: 1 }, { a: 'كِتَابٌ', t: 'kitābun', e: 'is a decree', q: 1 }, CLOSE ],
    [ { a: 'وَذَهَبَ', t: 'wa-dhahaba', e: 'and held' }, { a: 'بَعْضُهُمْ', t: 'baʿḍuhum', e: 'some of them' }, { a: 'إِلَى', t: 'ilā', e: 'that' }, { a: 'أَنَّهَا', t: 'annahā', e: 'it is' }, { a: 'لَامُ', t: 'lāmu', e: 'the lām of' }, { a: 'قَسَمٍ', t: 'qasamin', e: 'an oath' }, { a: 'مَحْذُوفٍ', t: 'maḥdhūfin', e: 'omitted' } ],
  ] },
  { t: 'box', label: 'جدول: المبتدأ معرفة ونكرة', labelEn: 'Table: the mubtadaʾ, definite and indefinite', lines: [
    [ { a: 'مَعْرِفَةٌ', t: 'maʿrifatun', e: 'definite', c: 'blue' }, { g: ':' }, { a: 'زَيْدٌ،', t: 'zaydun', e: 'Zayd' }, { a: 'الرَّجُلُ', t: 'ar-rajulu', e: 'the man' } ],
    [ { a: 'نَكِرَةٌ', t: 'nakiratun', e: 'indefinite', c: 'blue' }, { a: 'مَخْصُوصَةٌ', t: 'makhṣūṣatun', e: 'specified' }, { g: ':' },
      { a: 'بِالْإِضَافَةِ', t: 'bi-l-iḍāfati', e: 'by annexation' }, { a: 'خَمْسُ', t: 'khamsu', e: '“five' }, { a: 'صَلَوَاتٍ،', t: 'ṣalawātin', e: 'prayers”' },
      { a: 'بِالْوَصْفِ', t: 'bi-l-waṣfi', e: 'by description' }, { a: 'عَبْدٌ', t: 'ʿabdun', e: '“a slave' }, { a: 'مُؤْمِنٌ', t: 'muʾminun', e: 'believing”' } ],
    [ { a: 'نَكِرَةٌ', t: 'nakiratun', e: 'indefinite', c: 'blue' }, { a: 'عَامَّةٌ', t: 'ʿāmmatun', e: 'general' }, { g: ':' },
      { a: 'بَعْدَ', t: 'baʿda', e: 'after' }, { a: 'النَّفْيِ', t: 'an-nafyi', e: 'negation' }, { a: 'مَا', t: 'mā', e: '“no' }, { a: 'أَحَدٌ،', t: 'aḥadun', e: 'one”' },
      { a: 'بَعْدَ', t: 'baʿda', e: 'after' }, { a: 'الِاسْتِفْهَامِ', t: 'al-istifhāmi', e: 'a question' }, { a: 'أَأَحَدٌ', t: 'a-aḥadun', e: '“is anyone”' } ],
    [ { a: 'نَكِرَةٌ', t: 'nakiratun', e: 'indefinite', c: 'blue' }, { a: 'مُفِيدَةٌ', t: 'mufīdatun', e: 'beneficial' }, { g: ':' },
      { a: 'مُتَأَخِّرٌ', t: 'mutaʾakhkhirun', e: 'with a preceding' }, { a: 'عَنِ', t: 'ʿani', e: '' }, { a: 'الْخَبَرِ', t: 'al-khabari', e: 'predicate' }, { a: 'فِي', t: 'fī', e: '“in' }, { a: 'الْبَيْتِ', t: 'al-bayti', e: 'the house' }, { a: 'أَحَدٌ،', t: 'aḥadun', e: 'is someone”' },
      { a: 'بِمَعْنَى', t: 'bi-maʿnā', e: 'meaning' }, { a: 'الدُّعَاءِ', t: 'ad-duʿāʾi', e: 'a prayer' }, { a: 'سَلَامٌ،', t: 'salāmun', e: '“peace”' },
      { a: 'بَعْدَ', t: 'baʿda', e: 'after' }, { a: 'إِذَا', t: 'idhā', e: 'the sudden' }, { a: 'الْفُجَائِيَّةِ', t: 'al-fujāʾiyyati', e: 'idhā' }, { a: 'فَإِذَا', t: 'fa-idhā', e: '“and lo,' }, { a: 'أَحَدٌ', t: 'aḥadun', e: 'someone”' } ],
    [ { a: 'غَيْرُ', t: 'ghayru', e: 'not' }, { a: 'مُفِيدَةٍ', t: 'mufīdatin', e: 'beneficial' }, { g: ':' }, { a: 'رَجُلٌ', t: 'rajulun', e: '“a man”' }, { g: '✗' } ],
  ] },

  { t: 'page', n: '١٣٢' },
  { t: 'box', lines: [
    [ { a: 'وَبَعْدَ', t: 'wa-baʿda', e: 'and after' }, { a: 'إِذَا', t: 'idhā', e: 'the sudden' }, { a: 'الْفُجَائِيَّةِ،', t: 'al-fujāʾiyyati', e: 'idhā' }, NAHW, { g: ':' },
      { a: 'قَوْلُهُ', t: 'qawluhu', e: 'his saying' }, { a: 'ﷺ', t: 'ṣ', e: '(ﷺ)' }, { g: ':' },
      { g: '«' }, { a: 'عَلَوْنَ', t: 'ʿalawna', e: 'we ascended' }, { a: 'السَّمَاءَ', t: 'as-samāʾa', e: 'the nearest' }, { a: 'الدُّنْيَا،', t: 'ad-dunyā', e: 'heaven' }, { a: 'فَإِذَا', t: 'fa-idhā', e: 'and lo,' }, { a: 'رَجُلٌ', t: 'rajulun', e: 'a man' }, { a: 'قَاعِدٌ', t: 'qāʿidun', e: 'seated' }, { g: '»' } ],
    [ { a: 'وَإِذَا', t: 'wa-idhā', e: 'and when' }, { a: 'كَانَتْ', t: 'kānat', e: 'it is' }, { a: 'دُعَاءً،', t: 'duʿāʾan', e: 'a prayer' }, NAHW, { g: ':' },
      OPEN, { a: 'سَلَامٌ', t: 'salāmun', e: 'peace', q: 1 }, { a: 'عَلَيْكُمْ', t: 'ʿalaykum', e: 'be upon you', q: 1 }, CLOSE,
      { a: 'وَنَحْوُ', t: 'wa-naḥwu', e: 'and like' }, OPEN, { a: 'وَيْلٌ', t: 'waylun', e: 'woe', q: 1 }, { a: 'لِكُلِّ', t: 'li-kulli', e: 'to every', q: 1 }, { a: 'هُمَزَةٍ', t: 'humazatin', e: 'slanderer', q: 1 }, { a: 'لُمَزَةٍ', t: 'lumazatin', e: 'backbiter', q: 1 }, CLOSE ],
  ] },
  { t: 'box', label: 'حذف المبتدأ جوازًا', labelEn: 'permissible omission of the mubtadaʾ', lines: [
    [ { a: 'يَجُوزُ', t: 'yajūzu', e: 'it is permitted' }, { a: 'حَذْفُ', t: 'ḥadhfu', e: 'to omit' }, { a: 'الْمُبْتَدَأِ،', t: 'al-mubtadaʾi', e: 'the mubtadaʾ' }, NAHW, { g: ':' },
      { a: 'قَوْلُكَ', t: 'qawluka', e: 'your saying' }, { a: 'رَسُولُنَا،', t: 'rasūlunā', e: '“(he is) our Messenger”' }, { a: 'لِمَنْ', t: 'li-man', e: 'to one who' }, { a: 'سَأَلَكَ', t: 'saʾalaka', e: 'asks you' }, { g: ':' }, { a: 'مَنْ', t: 'man', e: 'who is' }, { a: 'مُحَمَّدٌ', t: 'muḥammadun', e: 'Muḥammad' }, { a: 'ﷺ؟', t: 'ṣ', e: '(ﷺ)?' } ],
    [ { a: 'وَيَكْثُرُ', t: 'wa-yakthuru', e: 'and it is frequent' }, { a: 'حَذْفُ', t: 'ḥadhfu', e: 'to omit' }, { a: 'الْمُبْتَدَأِ', t: 'al-mubtadaʾi', e: 'the mubtadaʾ' }, ELL ],
    [ { a: 'بَعْدَ', t: 'baʿda', e: 'after' }, { a: 'فَاءِ', t: 'fāʾi', e: 'the fāʾ of' }, { a: 'الْجَوَابِ،', t: 'al-jawābi', e: 'the answer' }, NAHW, { g: ':' },
      OPEN, { a: 'مَنْ', t: 'man', e: 'whoever', q: 1 }, { a: 'عَمِلَ', t: 'ʿamila', e: 'does', q: 1 }, { a: 'صَالِحًا', t: 'ṣāliḥan', e: 'righteousness', q: 1 }, { a: 'فَلِنَفْسِهِ', t: 'fa-li-nafsihi', e: 'then for himself', q: 1 }, CLOSE,
      { a: 'أَيْ', t: 'ay', e: 'i.e.' }, { a: 'فَعَمَلُهُ', t: 'fa-ʿamaluhu', e: 'then his deed (is)' } ],
    [ { a: 'وَبَعْدَ', t: 'wa-baʿda', e: 'and after' }, { a: 'الْقَوْلِ،', t: 'al-qawli', e: 'a saying' }, NAHW, { g: ':' },
      OPEN, { a: 'وَقَالُوا', t: 'wa-qālū', e: 'and they said', q: 1 }, { a: 'أَسَاطِيرُ', t: 'asāṭīru', e: 'legends of', q: 1 }, { a: 'الْأَوَّلِينَ', t: 'al-awwalīna', e: 'the ancients', q: 1 }, CLOSE,
      { a: 'أَيْ', t: 'ay', e: 'i.e.' }, { a: 'هِيَ', t: 'hiya', e: 'it (is)' } ],
  ] },
  { t: 'box', label: 'حذف المبتدأ وجوبًا', labelEn: 'obligatory omission of the mubtadaʾ', lines: [
    [ { a: 'يَجِبُ', t: 'yajibu', e: 'it is obligatory' }, { a: 'حَذْفُ', t: 'ḥadhfu', e: 'to omit' }, { a: 'الْمُبْتَدَأِ', t: 'al-mubtadaʾi', e: 'the mubtadaʾ' }, { a: 'فِي', t: 'fī', e: 'in' }, { a: 'أَرْبَعَةِ', t: 'arbaʿati', e: 'four' }, { a: 'مَوَاضِعَ', t: 'mawāḍiʿa', e: 'places' }, { g: ':' } ],
    [ { a: 'الْأَوَّلُ', t: 'al-awwalu', e: 'the first', c: 'red' }, { a: 'النَّعْتُ', t: 'an-naʿtu', e: 'the adjective' }, { a: 'الْمَقْطُوعُ', t: 'al-maqṭūʿu', e: 'cut off' }, { a: 'إِلَى', t: 'ilā', e: 'to' }, { a: 'الرَّفْعِ،', t: 'ar-rafʿi', e: 'the nominative' },
      NAHW, { g: ':' }, { a: 'الْحَمْدُ', t: 'al-ḥamdu', e: 'praise (be)' }, { a: 'لِلهِ', t: 'lillāhi', e: 'to Allah' }, { a: 'الْحَمِيدُ', t: 'al-ḥamīdu', e: 'the Praiseworthy' }, { a: 'أَيْ', t: 'ay', e: 'i.e.' }, { a: 'هُوَ', t: 'huwa', e: 'He (is)' }, { a: 'الْحَمِيدُ', t: 'al-ḥamīdu', e: 'the Praiseworthy' } ],
    [ { a: 'الثَّانِي', t: 'ath-thānī', e: 'the second', c: 'red' }, { a: 'إِنْ', t: 'in', e: 'if' }, { a: 'دَلَّ', t: 'dalla', e: 'points to it' }, { a: 'عَلَيْهِ', t: 'ʿalayhi', e: '' }, { a: 'جَوَابُ', t: 'jawābu', e: 'the answer of' }, { a: 'الْقَسَمِ،', t: 'al-qasami', e: 'the oath' },
      NAHW, { g: ':' }, { a: 'فِي', t: 'fī', e: 'upon' }, { a: 'ذِمَّتِي', t: 'dhimmatī', e: 'my responsibility' }, { a: 'لَأَقُولَنَّ', t: 'la-aqūlanna', e: 'I shall surely tell' }, { a: 'الصِّدْقَ', t: 'aṣ-ṣidqa', e: 'the truth' }, { a: 'أَيْ', t: 'ay', e: 'i.e.' }, { a: 'فِي', t: 'fī', e: 'upon' }, { a: 'ذِمَّتِي', t: 'dhimmatī', e: 'my responsibility (is)' }, { a: 'عَهْدٌ', t: 'ʿahdun', e: 'a pledge' } ],
    [ { a: 'الثَّالِثُ', t: 'ath-thālithu', e: 'the third', c: 'red' }, { a: 'إِنْ', t: 'in', e: 'if' }, { a: 'كَانَ', t: 'kāna', e: 'is' }, { a: 'الْخَبَرُ', t: 'al-khabaru', e: 'the predicate' }, { a: 'مَصْدَرًا', t: 'maṣdaran', e: 'a verbal noun' }, { a: 'نَابَ', t: 'nāba', e: 'standing in' }, { a: 'عَنْ', t: 'ʿan', e: 'for' }, { a: 'فِعْلِهِ،', t: 'fiʿlihi', e: 'its verb' },
      NAHW, { g: ':' }, OPEN, { a: 'فَصَبْرٌ', t: 'fa-ṣabrun', e: 'so patience', q: 1 }, { a: 'جَمِيلٌ', t: 'jamīlun', e: 'is beautiful', q: 1 }, CLOSE, { a: 'أَيْ', t: 'ay', e: 'i.e.' }, { a: 'صَبْرِي', t: 'ṣabrī', e: 'my patience' }, { a: 'أَوْ', t: 'aw', e: 'or' }, { a: 'أَمْرِي', t: 'amrī', e: 'my affair' } ],
    [ { a: 'الرَّابِعُ', t: 'ar-rābiʿu', e: 'the fourth', c: 'red' }, { a: 'إِنْ', t: 'in', e: 'if' }, { a: 'كَانَ', t: 'kāna', e: 'is' }, { a: 'الْخَبَرُ', t: 'al-khabaru', e: 'the predicate' }, { a: 'مَخْصُوصًا', t: 'makhṣūṣan', e: 'specified' }, { a: 'بِالْمَدْحِ', t: 'bi-l-madḥi', e: 'for praise' }, { a: 'أَوِ', t: 'awi', e: 'or' }, { a: 'الذَّمِّ،', t: 'adh-dhammi', e: 'blame' },
      NAHW, { g: ':' }, { a: 'نِعْمَ', t: 'niʿma', e: 'excellent (is)' }, { a: 'الطَّالِبُ', t: 'aṭ-ṭālibu', e: 'the student' }, { a: 'الْمُجْتَهِدُ', t: 'al-mujtahidu', e: 'the diligent' }, { a: 'أَيْ', t: 'ay', e: 'i.e.' }, { a: 'هُوَ', t: 'huwa', e: 'he (is)' }, { a: 'الْمُجْتَهِدُ،', t: 'al-mujtahidu', e: 'the diligent one' } ],
    [ { a: 'وَبِئْسَ', t: 'wa-biʾsa', e: 'and wretched (is)' }, { a: 'الطَّالِبُ', t: 'aṭ-ṭālibu', e: 'the student' }, { a: 'الْكَسُولُ', t: 'al-kasūlu', e: 'the lazy' }, { a: 'أَيْ', t: 'ay', e: 'i.e.' }, { a: 'هُوَ', t: 'huwa', e: 'he (is)' }, { a: 'الْكَسُولُ', t: 'al-kasūlu', e: 'the lazy one' } ],
  ] },
  { t: 'line', w: [
    { a: 'الرَّابِعُ', t: 'ar-rābiʿu', e: 'the fourth (is)', c: 'red' },
    { a: 'الْخَبَرُ،', t: 'al-khabaru', e: 'the predicate' },
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' }, { a: 'مُخْبَرٌ', t: 'mukhbarun', e: 'that which is stated' }, { a: 'بِهِ،', t: 'bihi', e: 'about the subject' },
    NAHW, { g: ':' }, OPEN, { a: 'مُحَمَّدٌ', t: 'muḥammadun', e: 'Muḥammad', q: 1 }, { a: 'رَسُولُ', t: 'rasūlu', e: 'is the Messenger of', q: 1 }, { a: 'اللهِ', t: 'Allāhi', e: 'Allah', q: 1 }, CLOSE,
  ] },
  { t: 'box', label: 'تعدّد الخبر', labelEn: 'multiplicity of the predicate', lines: [
    [ { a: 'قَدْ', t: 'qad', e: 'sometimes' }, { a: 'يَتَعَدَّدُ', t: 'yataʿaddadu', e: 'is multiple' }, { a: 'الْخَبَرُ،', t: 'al-khabaru', e: 'the predicate' },
      NAHW, { g: ':' }, OPEN, { a: 'وَهُوَ', t: 'wa-huwa', e: 'and He is', q: 1 }, { a: 'الْغَفُورُ', t: 'al-ghafūru', e: 'the Forgiving', q: 1 }, { a: 'الْوَدُودُ', t: 'al-wadūdu', e: 'the Loving', q: 1 }, CLOSE ],
  ] },
  { t: 'box', label: 'الترتيب بين المبتدأ والخبر', labelEn: 'order of the mubtadaʾ and predicate', lines: [
    [ { a: 'الْأَصْلُ', t: 'al-aṣlu', e: 'the norm' }, { a: 'فِي', t: 'fī', e: 'for' }, { a: 'الْخَبَرِ', t: 'al-khabari', e: 'the predicate' }, { a: 'أَنْ', t: 'an', e: 'is' }, { a: 'يَكُونَ', t: 'yakūna', e: 'to be' }, { a: 'بَعْدَ', t: 'baʿda', e: 'after' }, { a: 'الْمُبْتَدَأِ،', t: 'al-mubtadaʾi', e: 'the mubtadaʾ' },
      { a: 'وَقَدْ', t: 'wa-qad', e: 'but it may' }, { a: 'يَتَقَدَّمُ،', t: 'yataqaddamu', e: 'precede' }, NAHW, { g: ':' }, OPEN, { a: 'لَنَا', t: 'lanā', e: 'for us are', q: 1 }, { a: 'أَعْمَالُنَا', t: 'aʿmālunā', e: 'our deeds', q: 1 }, CLOSE ],
  ] },
  { t: 'box', label: 'وجوب حذف الخبر', labelEn: 'obligatory omission of the predicate', lines: [
    [ { a: 'وَيَجِبُ', t: 'wa-yajibu', e: 'and it is obligatory' }, { a: 'حَذْفُ', t: 'ḥadhfu', e: 'to omit' }, { a: 'الْخَبَرِ', t: 'al-khabari', e: 'the predicate' }, ELL ],
    [ { a: 'إِنْ', t: 'in', e: 'if' }, { a: 'دَلَّ', t: 'dalla', e: 'points to it' }, { a: 'عَلَيْهِ', t: 'ʿalayhi', e: '' }, { a: 'جَوَابُ', t: 'jawābu', e: 'the answer of' }, { a: 'الْقَسَمِ،', t: 'al-qasami', e: 'the oath' },
      NAHW, { g: ':' }, OPEN, { a: 'لَعَمْرُكَ', t: 'la-ʿamruka', e: 'by your life', q: 1 }, { a: 'إِنَّهُمْ', t: 'innahum', e: 'indeed they', q: 1 }, { a: 'لَفِي', t: 'la-fī', e: 'were in', q: 1 }, { a: 'سَكْرَتِهِمْ', t: 'sakratihim', e: 'their intoxication', q: 1 }, { a: 'يَعْمَهُونَ', t: 'yaʿmahūna', e: 'wandering blindly', q: 1 }, CLOSE,
      { a: 'أَيْ', t: 'ay', e: 'i.e.' }, { a: 'لَعَمْرُكَ', t: 'la-ʿamruka', e: 'by your life (is)' }, { a: 'قَسَمِي', t: 'qasamī', e: 'my oath' } ],
  ] },

  { t: 'page', n: '١٣٣' },
  { t: 'box', lines: [
    [ { a: 'وَفِي', t: 'wa-fī', e: 'and with' }, { a: 'لَوْلَا،', t: 'lawlā', e: 'lawlā' }, NAHW, { g: ':' },
      OPEN, { a: 'وَلَوْلَا', t: 'wa-lawlā', e: 'and were it not for', q: 1 }, { a: 'رَهْطُكَ', t: 'rahṭuka', e: 'your clan', q: 1 }, { a: 'لَرَجَمْنَاكَ', t: 'la-rajamnāka', e: 'we would have stoned you', q: 1 }, CLOSE,
      { a: 'أَيْ', t: 'ay', e: 'i.e.' }, { a: 'وَلَوْلَا', t: 'wa-lawlā', e: 'were it not for' }, { a: 'رَهْطُكَ', t: 'rahṭuka', e: 'your clan' }, { a: 'مَوْجُودٌ', t: 'mawjūdun', e: 'existing' } ],
    [ { a: 'وَإِذَا', t: 'wa-idhā', e: 'and when' }, { a: 'كَانَ', t: 'kāna', e: 'is' }, { a: 'الْمُبْتَدَأُ', t: 'al-mubtadaʾu', e: 'the mubtadaʾ' }, { a: 'مَعْطُوفًا', t: 'maʿṭūfan', e: 'conjoined' }, { a: 'عَلَيْهِ', t: 'ʿalayhi', e: 'to' }, { a: 'بِوَاوٍ', t: 'bi-wāwin', e: 'by a wāw' }, { a: 'هِيَ', t: 'hiya', e: 'that is' }, { a: 'نَصٌّ', t: 'naṣṣun', e: 'explicit' }, { a: 'فِي', t: 'fī', e: 'in' }, { a: 'الْمَعِيَّةِ،', t: 'al-maʿiyyati', e: 'accompaniment' },
      NAHW, { g: ':' }, OPEN, { a: 'فَأَنْتُمْ', t: 'fa-antum', e: 'so you', q: 1 }, { a: 'وَمَا', t: 'wa-mā', e: 'and what', q: 1 }, { a: 'تَعْبُدُونَ', t: 'taʿbudūna', e: 'you worship', q: 1 }, CLOSE ],
  ] },
  { t: 'box', label: 'جواز حذف الخبر', labelEn: 'permissible omission of the predicate', lines: [
    [ { a: 'وَيَجُوزُ', t: 'wa-yajūzu', e: 'and it is permitted' }, { a: 'حَذْفُهُ', t: 'ḥadhfuhu', e: 'to omit it' }, { a: 'فِيمَا', t: 'fīmā', e: 'in what' }, { a: 'سِوَاهُ', t: 'siwāhu', e: 'is other than that' }, { a: 'عِنْدَ', t: 'ʿinda', e: 'given' }, { a: 'الْقَرِينَةِ', t: 'al-qarīnati', e: 'an indicator' }, { a: 'كَمَا', t: 'kamā', e: 'just as' }, { a: 'يُحْذَفُ', t: 'yuḥdhafu', e: 'it is omitted' }, ELL ],
    [ { a: 'فِي', t: 'fī', e: 'in' }, { a: 'جَوَابِ', t: 'jawābi', e: 'the answer of' }, { a: 'الِاسْتِفْهَامِ،', t: 'al-istifhāmi', e: 'a question' },
      NAHW, { g: ':' }, OPEN, { a: 'وَلَئِنْ', t: 'wa-la-in', e: 'and if', q: 1 }, { a: 'سَأَلْتَهُمْ', t: 'saʾaltahum', e: 'you ask them', q: 1 }, { a: 'مَنْ', t: 'man', e: 'who', q: 1 }, { a: 'خَلَقَ', t: 'khalaqa', e: 'created', q: 1 }, { a: 'السَّمَوَاتِ', t: 'as-samāwāti', e: 'the heavens', q: 1 }, { a: 'وَالْأَرْضَ', t: 'wa-l-arḍa', e: 'and the earth', q: 1 }, { a: 'لَيَقُولُنَّ', t: 'la-yaqūlunna', e: 'they will surely say', q: 1 }, { a: 'اللهُ', t: 'Allāhu', e: 'Allah', q: 1 }, CLOSE ],
    [ { a: 'وَبَعْدَ', t: 'wa-baʿda', e: 'and after' }, { a: 'إِذَا', t: 'idhā', e: 'the sudden' }, { a: 'الْفُجَائِيَّةِ،', t: 'al-fujāʾiyyati', e: 'idhā' },
      NAHW, { g: ':' }, { a: 'خَرَجْتُ', t: 'kharajtu', e: 'I went out' }, { a: 'فَإِذَا', t: 'fa-idhā', e: 'and lo,' }, { a: 'الْأَسَدُ،', t: 'al-asadu', e: 'the lion' }, { a: 'أَيْ', t: 'ay', e: 'i.e.' }, { a: 'فَإِذَا', t: 'fa-idhā', e: 'and lo,' }, { a: 'الْأَسَدُ', t: 'al-asadu', e: 'the lion' }, { a: 'مَوْجُودٌ', t: 'mawjūdun', e: 'is present' } ],
  ] },
  { t: 'box', label: 'مطابقة الخبر للمبتدأ', labelEn: 'agreement of predicate with subject', lines: [
    [ { a: 'يُطَابِقُ', t: 'yuṭābiqu', e: 'must agree' }, { a: 'الْخَبَرُ', t: 'al-khabaru', e: 'the predicate' }, { a: 'الْمُبْتَدَأَ', t: 'al-mubtadaʾa', e: 'the mubtadaʾ' }, ELL ],
    [ { a: 'إِذَا', t: 'idhā', e: 'when' }, { a: 'كَانَ', t: 'kāna', e: 'there is' }, { a: 'فِي', t: 'fī', e: 'in' }, { a: 'الْخَبَرِ', t: 'al-khabari', e: 'the predicate' }, { a: 'ضَمِيرٌ', t: 'ḍamīrun', e: 'a pronoun' }, { a: 'مُسْتَتِرٌ،', t: 'mustatirun', e: 'concealed' },
      NAHW, { g: ':' }, OPEN, { a: 'إِنَّهُمْ', t: 'innahum', e: 'indeed they', q: 1 }, { a: 'هُمُ', t: 'humu', e: 'they', q: 1 }, { a: 'الْمُفْسِدُونَ', t: 'al-mufsidūna', e: 'are the corrupters', q: 1 }, CLOSE,
      { a: 'بِخِلَافِ', t: 'bi-khilāfi', e: 'unlike' }, OPEN, { a: 'نَحْنُ', t: 'naḥnu', e: 'we are', q: 1 }, { a: 'فِتْنَةٌ', t: 'fitnatun', e: 'a trial', q: 1 }, CLOSE ],
    [ { a: 'وَإِذَا', t: 'wa-idhā', e: 'and when' }, { a: 'كَانَ', t: 'kāna', e: 'is' }, { a: 'الْمُبْتَدَأُ', t: 'al-mubtadaʾu', e: 'the mubtadaʾ' }, { a: 'اسْمَ', t: 'isma', e: 'a noun of' }, { a: 'إِشَارَةٍ،', t: 'ishāratin', e: 'demonstration' },
      NAHW, { g: ':' }, OPEN, { a: 'فَذَلِكَ', t: 'fa-dhālika', e: 'so these are', q: 1 }, { a: 'بُرْهَانَانِ', t: 'burhānāni', e: 'two proofs', q: 1 }, { a: 'مِنْ', t: 'min', e: 'from', q: 1 }, { a: 'رَبِّكَ', t: 'rabbika', e: 'your Lord', q: 1 }, CLOSE ],
  ] },
  { t: 'box', label: 'تضمّن الخبر الفاء', labelEn: 'the predicate taking the fāʾ', lines: [
    [ { a: 'وَقَدْ', t: 'wa-qad', e: 'and sometimes' }, { a: 'يَتَضَمَّنُ', t: 'yataḍammanu', e: 'contains' }, { a: 'الْمُبْتَدَأُ', t: 'al-mubtadaʾu', e: 'the mubtadaʾ' }, { a: 'مَعْنَى', t: 'maʿnā', e: 'the sense of' }, { a: 'الشَّرْطِ،', t: 'ash-sharṭi', e: 'a condition' },
      { a: 'فَيَصِحُّ', t: 'fa-yaṣiḥḥu', e: 'so it is valid' }, { a: 'دُخُولُ', t: 'dukhūlu', e: 'for the entry of' }, { a: 'الْفَاءِ', t: 'al-fāʾi', e: 'the fāʾ' }, { a: 'عَلَى', t: 'ʿalā', e: 'upon' }, { a: 'الْخَبَرِ', t: 'al-khabari', e: 'the predicate' } ],
    [ { a: 'وَذَلِكَ', t: 'wa-dhālika', e: 'and that' }, { a: 'إِذَا', t: 'idhā', e: 'is when' }, { a: 'كَانَ', t: 'kāna', e: 'is' }, { a: 'الْمُبْتَدَأُ', t: 'al-mubtadaʾu', e: 'the mubtadaʾ' }, ELL, { a: 'بَعْدَ', t: 'baʿda', e: 'after' }, ELL ],
    [ { a: 'أَمَّا،', t: 'ammā', e: 'ammā (as for)' }, NAHW, { g: ':' },
      OPEN, { a: 'فَأَمَّا', t: 'fa-ammā', e: 'as for', q: 1 }, { a: 'ثَمُودُ', t: 'thamūdu', e: 'Thamūd', q: 1 }, { a: 'فَأُهْلِكُوا', t: 'fa-uhlikū', e: 'they were destroyed', q: 1 }, { a: 'بِالطَّاغِيَةِ', t: 'bi-ṭ-ṭāghiyati', e: 'by the overpowering blast', q: 1 }, CLOSE ],
    [ { a: 'أَوِ', t: 'awi', e: 'or' }, { a: 'اسْمَ', t: 'isma', e: 'a noun of' }, { a: 'مَوْصُولٍ،', t: 'mawṣūlin', e: 'relation' }, NAHW, { g: ':' },
      OPEN, { a: 'الَّذِينَ', t: 'alladhīna', e: 'those who', q: 1 }, { a: 'خَسِرُوا', t: 'khasirū', e: 'have lost', q: 1 }, { a: 'أَنْفُسَهُمْ', t: 'anfusahum', e: 'themselves', q: 1 }, { a: 'فَهُمْ', t: 'fa-hum', e: 'so they', q: 1 }, { a: 'لَا', t: 'lā', e: 'do not', q: 1 }, { a: 'يُؤْمِنُونَ', t: 'yuʾminūna', e: 'believe', q: 1 }, CLOSE ],
    [ { a: 'أَوْ', t: 'aw', e: 'or' }, { a: 'مَوْصُوفًا', t: 'mawṣūfan', e: 'qualified' }, { a: 'بِمَوْصُولٍ', t: 'bi-mawṣūlin', e: 'by a relative clause' }, { a: 'بِفِعْلٍ', t: 'bi-fiʿlin', e: 'with a verb' }, { a: 'أَوْ', t: 'aw', e: 'or' }, { a: 'ظَرْفٍ،', t: 'ẓarfin', e: 'adverb' },
      NAHW, { g: ':' }, OPEN, { a: 'إِنَّ', t: 'inna', e: 'indeed', q: 1 }, { a: 'الْمَوْتَ', t: 'al-mawta', e: 'death', q: 1 }, { a: 'الَّذِي', t: 'alladhī', e: 'which', q: 1 }, { a: 'تَفِرُّونَ', t: 'tafirrūna', e: 'you flee', q: 1 }, { a: 'مِنْهُ', t: 'minhu', e: 'from it', q: 1 }, { a: 'فَإِنَّهُ', t: 'fa-innahu', e: 'indeed it', q: 1 }, { a: 'مُلَاقِيكُمْ', t: 'mulāqīkum', e: 'will meet you', q: 1 }, CLOSE ],
    [ { a: 'أَوْ', t: 'aw', e: 'or' }, { a: 'نَكِرَةً', t: 'nakiratan', e: 'an indefinite' }, { a: 'مَوْصُوفَةً', t: 'mawṣūfatan', e: 'qualified' }, ELL ],
    [ { a: 'بِفِعْلٍ،', t: 'bi-fiʿlin', e: 'with a verb' }, NAHW, { g: ':' },
      { a: 'وَلَدٌ', t: 'waladun', e: 'a child' }, { a: 'حَفِظَ', t: 'ḥafiẓa', e: 'who memorized' }, { a: 'الْقُرْآنَ', t: 'al-qurʾāna', e: 'the Qurʾān' }, { a: 'فَلَهُ', t: 'fa-lahu', e: 'he shall have' }, { a: 'أَجْرٌ', t: 'ajrun', e: 'a reward' } ],
  ] },

  { t: 'page', n: '١٣٤' },
  { t: 'box', lines: [
    [ { a: 'أَوْ', t: 'aw', e: 'or' }, { a: 'ظَرْفٍ،', t: 'ẓarfin', e: 'an adverb' }, NAHW, { g: ':' },
      { a: 'وَلَدٌ', t: 'waladun', e: 'a child' }, { a: 'فِي', t: 'fī', e: 'in' }, { a: 'الْفَصْلِ', t: 'al-faṣli', e: 'the classroom' }, { a: 'فَلَهُ', t: 'fa-lahu', e: 'he shall have' }, { a: 'أَجْرٌ', t: 'ajrun', e: 'a reward' } ],
    [ { a: 'أَوْ', t: 'aw', e: 'or' }, { a: 'مُضَافًا', t: 'muḍāfan', e: 'annexed' }, { a: 'إِلَى', t: 'ilā', e: 'to' }, { a: 'نَكِرَةٍ', t: 'nakiratin', e: 'an indefinite' }, { a: 'مَوْصُوفَةٍ', t: 'mawṣūfatin', e: 'qualified' }, { a: 'بِفِعْلٍ', t: 'bi-fiʿlin', e: 'by a verb' }, { a: 'أَوْ', t: 'aw', e: 'or' }, { a: 'ظَرْفٍ،', t: 'ẓarfin', e: 'adverb' },
      NAHW, { g: ':' }, { a: 'أُمُّ', t: 'ummu', e: 'a mother of' }, { a: 'يَتِيمٍ', t: 'yatīmin', e: 'an orphan' }, { a: 'تَأْتِينِي', t: 'taʾtīnī', e: 'who comes to me' }, { a: 'فَلَهَا', t: 'fa-lahā', e: 'she shall have' }, { a: 'مَالٌ', t: 'mālun', e: 'wealth' } ],
    [ { a: 'أَوْ', t: 'aw', e: 'or' }, { a: 'كَلِمَةَ', t: 'kalimata', e: 'the word' }, { a: 'كُلٍّ', t: 'kullin', e: '“every”' }, { a: 'مُضَافٍ', t: 'muḍāfin', e: 'annexed' }, { a: 'إِلَى', t: 'ilā', e: 'to' }, { a: 'نَكِرَةٍ،', t: 'nakiratin', e: 'an indefinite' },
      NAHW, { g: ':' }, { a: 'كُلُّ', t: 'kullu', e: 'every' }, { a: 'يَتِيمٍ', t: 'yatīmin', e: 'orphan' }, { a: 'فَلَهُ', t: 'fa-lahu', e: 'he has' }, { a: 'فِي', t: 'fī', e: 'in' }, { a: 'قَلْبِي', t: 'qalbī', e: 'my heart' }, { a: 'رَأْفَةٌ', t: 'raʾfatun', e: 'compassion' } ],
  ] },
  { t: 'line', w: [
    { a: 'الْخَامِسُ', t: 'al-khāmisu', e: 'the fifth (is)', c: 'red' },
    { a: 'اسْمُ', t: 'ismu', e: 'the noun of' }, { a: 'الْأَفْعَالِ', t: 'al-afʿāli', e: 'the verbs' }, { a: 'النَّاقِصَةِ،', t: 'an-nāqiṣati', e: 'defective (kāna & sisters)' },
    NAHW, { g: ':' }, OPEN, { a: 'وَكَانَ', t: 'wa-kāna', e: 'and Allah is', q: 1 }, { a: 'اللهُ', t: 'Allāhu', e: '', q: 1 }, { a: 'عَلِيمًا', t: 'ʿalīman', e: 'All-Knowing', q: 1 }, { a: 'حَكِيمًا', t: 'ḥakīman', e: 'All-Wise', q: 1 }, CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'السَّادِسُ', t: 'as-sādisu', e: 'the sixth (is)', c: 'red' },
    { a: 'اسْمُ', t: 'ismu', e: 'the noun of' }, { a: 'الْحُرُوفِ', t: 'al-ḥurūfi', e: 'the particles' }, { a: 'الْمُشَبَّهَةِ', t: 'al-mushabbahati', e: 'resembling' }, { a: 'بِلَيْسَ،', t: 'bi-laysa', e: 'laysa' },
    NAHW, { g: ':' }, OPEN, { a: 'مَا', t: 'mā', e: 'not is', q: 1 }, { a: 'هَذَا', t: 'hādhā', e: 'this', q: 1 }, { a: 'بَشَرًا', t: 'basharan', e: 'a human', q: 1 }, CLOSE,
    { a: 'وَلَا', t: 'wa-lā', e: 'and no' }, { a: 'شَيْءٌ', t: 'shayʾun', e: 'thing' }, { a: 'مُشَابِهًا', t: 'mushābihan', e: 'is resembling' }, { a: 'لِلهِ', t: 'lillāhi', e: 'to Allah' },
  ] },
  { t: 'line', w: [
    { a: 'السَّابِعُ', t: 'as-sābiʿu', e: 'the seventh (is)', c: 'red' },
    { a: 'خَبَرُ', t: 'khabaru', e: 'the predicate of' }, { a: 'الْحُرُوفِ', t: 'al-ḥurūfi', e: 'the particles' }, { a: 'الْمُشَبَّهَةِ', t: 'al-mushabbahati', e: 'resembling' }, { a: 'بِالْفِعْلِ،', t: 'bi-l-fiʿli', e: 'the verb (inna & sisters)' },
    NAHW, { g: ':' }, OPEN, { a: 'إِنَّ', t: 'inna', e: 'indeed', q: 1 }, { a: 'اللهَ', t: 'Allāha', e: 'Allah', q: 1 }, { a: 'رَحِيمٌ', t: 'raḥīmun', e: 'is Merciful', q: 1 }, CLOSE,
  ] },
  { t: 'box', label: 'اللام المزحلقة', labelEn: 'the shifted lām', lines: [
    [ { a: 'قَدْ', t: 'qad', e: 'sometimes' }, { a: 'تَدْخُلُ', t: 'tadkhulu', e: 'enters' }, { a: 'اللَّامُ', t: 'al-lāmu', e: 'the lām' }, { a: 'الْمُزَحْلَقَةُ', t: 'al-muzaḥlaqatu', e: 'shifted' }, { a: 'عَلَى', t: 'ʿalā', e: 'upon' }, ELL ],
    [ { a: 'خَبَرِ', t: 'khabari', e: 'the predicate of' }, { a: 'إِنَّ،', t: 'inna', e: 'inna' }, NAHW, { g: ':' },
      OPEN, { a: 'وَإِنَّكَ', t: 'wa-innaka', e: 'and indeed you', q: 1 }, { a: 'لَعَلَى', t: 'la-ʿalā', e: 'are upon', q: 1 }, { a: 'خُلُقٍ', t: 'khuluqin', e: 'a character', q: 1 }, { a: 'عَظِيمٍ', t: 'ʿaẓīmin', e: 'great', q: 1 }, CLOSE ],
    [ { a: 'وَعَلَى', t: 'wa-ʿalā', e: 'and upon' }, { a: 'اسْمِهَا', t: 'ismihā', e: 'its noun' }, { a: 'الْمُؤَخَّرِ،', t: 'al-muʾakhkhari', e: 'when postponed' }, NAHW, { g: ':' },
      OPEN, { a: 'إِنَّ', t: 'inna', e: 'indeed', q: 1 }, { a: 'فِي', t: 'fī', e: 'in', q: 1 }, { a: 'ذَلِكَ', t: 'dhālika', e: 'that', q: 1 }, { a: 'لَعِبْرَةً', t: 'la-ʿibratan', e: 'is a lesson', q: 1 }, CLOSE ],
    [ { a: 'وَعَلَى', t: 'wa-ʿalā', e: 'and upon' }, { a: 'ضَمِيرِ', t: 'ḍamīri', e: 'the pronoun of' }, { a: 'الْفَصْلِ', t: 'al-faṣli', e: 'separation' }, { a: 'الدَّاخِلِ', t: 'ad-dākhili', e: 'coming' }, { a: 'بَيْنَ', t: 'bayna', e: 'between' }, { a: 'اسْمِهَا', t: 'ismihā', e: 'its noun' }, { a: 'وَخَبَرِهَا،', t: 'wa-khabarihā', e: 'and its predicate' },
      NAHW, { g: ':' }, OPEN, { a: 'إِنَّ', t: 'inna', e: 'indeed', q: 1 }, { a: 'هَذَا', t: 'hādhā', e: 'this', q: 1 }, { a: 'لَهُوَ', t: 'la-huwa', e: 'is truly', q: 1 }, { a: 'الْقَصَصُ', t: 'al-qaṣaṣu', e: 'the narration', q: 1 }, { a: 'الْحَقُّ', t: 'al-ḥaqqu', e: 'true', q: 1 }, CLOSE ],
  ] },
  { t: 'line', w: [
    { a: 'الثَّامِنُ', t: 'ath-thāminu', e: 'the eighth (is)', c: 'red' },
    { a: 'خَبَرُ', t: 'khabaru', e: 'the predicate of' }, { a: 'لَا', t: 'lā', e: 'lā' }, { a: 'لِنَفْيِ', t: 'li-nafyi', e: 'of negating' }, { a: 'الْجِنْسِ،', t: 'al-jinsi', e: 'the genus' },
    NAHW, { g: ':' }, { a: 'لَا', t: 'lā', e: 'no' }, { a: 'عَمَلَ', t: 'ʿamala', e: 'deed of' }, { a: 'مُرَاءٍ', t: 'murāʾin', e: 'a show-off' }, { a: 'مَقْبُولٌ', t: 'maqbūlun', e: 'is accepted' },
  ] },
  { t: 'box', label: 'مثال', labelEn: 'example', lines: [
    [ { a: 'الْغَالِبُ', t: 'al-ghālibu', e: 'usually' }, { a: 'فِي', t: 'fī', e: 'for' }, { a: 'خَبَرِهَا', t: 'khabarihā', e: 'its predicate' }, { a: 'أَنْ', t: 'an', e: 'is' }, { a: 'يَكُونَ', t: 'yakūna', e: 'to be' }, { a: 'شِبْهَ', t: 'shibha', e: 'a quasi-' }, { a: 'جُمْلَةٍ،', t: 'jumlatin', e: 'clause' },
      NAHW, { g: ':' }, OPEN, { a: 'فَلَا', t: 'fa-lā', e: 'so no', q: 1 }, { a: 'رَفَثَ', t: 'rafatha', e: 'intimacy', q: 1 }, { a: 'وَلَا', t: 'wa-lā', e: 'nor', q: 1 }, { a: 'فُسُوقَ', t: 'fusūqa', e: 'wickedness', q: 1 }, { a: 'وَلَا', t: 'wa-lā', e: 'nor', q: 1 }, { a: 'جِدَالَ', t: 'jidāla', e: 'dispute', q: 1 }, { a: 'فِي', t: 'fī', e: 'during', q: 1 }, { a: 'الْحَجِّ', t: 'al-ḥajji', e: 'the Ḥajj', q: 1 }, CLOSE ],
    [ { a: 'وَيُحْذَفُ', t: 'wa-yuḥdhafu', e: 'and is omitted' }, { a: 'خَبَرُهَا', t: 'khabaruhā', e: 'its predicate' }, { a: 'كَثِيرًا', t: 'kathīran', e: 'often' }, { a: 'إِنْ', t: 'in', e: 'if' }, { a: 'كَانَ', t: 'kāna', e: 'it is' }, { a: 'عَامًّا', t: 'ʿāmman', e: 'general' }, { a: 'كَالْمَوْجُودِ،', t: 'ka-l-mawjūdi', e: 'like “present”' },
      NAHW, { g: ':' }, { a: 'لَا', t: 'lā', e: 'no' }, { a: 'ضَيْرَ', t: 'ḍayra', e: 'harm' }, { a: 'أَيْ', t: 'ay', e: 'i.e.' }, { a: 'مَوْجُودٌ', t: 'mawjūdun', e: 'is present' }, { a: 'عَلَيْكُمْ', t: 'ʿalaykum', e: 'upon you' } ],
  ] },

  { t: 'h2', c: 'blue', ar: 'الْقِسْمُ الثَّانِي: الْمَنْصُوبُ', en: 'The Second Division — the Accusative (the manṣūb)' },
  { t: 'line', w: [
    { a: 'الْقِسْمُ', t: 'al-qismu', e: 'the division' }, { a: 'الثَّانِي', t: 'ath-thānī', e: 'second' }, { a: 'الْمَنْصُوبُ،', t: 'al-manṣūbu', e: 'the accusative' },
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' }, { a: 'اثْنَا', t: 'ithnā', e: 'twe-' }, { a: 'عَشَرَ', t: 'ʿashara', e: '-lve' }, { g: ':' },
  ] },
  { t: 'h2', c: 'red', ar: 'الْأَوَّلُ: الْمَفْعُولُ الْمُطْلَقُ', en: 'First — the Absolute Object (mafʿūl muṭlaq)' },
  { t: 'line', w: [
    { a: 'الْأَوَّلُ', t: 'al-awwalu', e: 'the first (is)' }, { a: 'الْمَفْعُولُ', t: 'al-mafʿūlu', e: 'the object' }, { a: 'الْمُطْلَقُ،', t: 'al-muṭlaqu', e: 'absolute' },
  ] },
  { t: 'box', label: 'مثال', labelEn: 'example', lines: [
    [ { a: 'يُسَمَّى', t: 'yusammā', e: 'it is called' }, { a: 'مَفْعُولًا', t: 'mafʿūlan', e: 'an object' }, { a: 'مُطْلَقًا', t: 'muṭlaqan', e: 'absolute' }, { a: 'لِأَنَّ', t: 'li-anna', e: 'because' }, { a: 'اسْمَهُ', t: 'ismahu', e: 'its noun' }, { a: 'غَيْرُ', t: 'ghayru', e: 'is not' }, { a: 'مُقَيَّدٍ', t: 'muqayyadin', e: 'restricted' }, { a: 'بِحَرْفِ', t: 'bi-ḥarfi', e: 'by a particle of' }, { a: 'جَرٍّ', t: 'jarrin', e: 'the genitive' },
      { a: 'بِخِلَافِ', t: 'bi-khilāfi', e: 'unlike' }, { a: 'سَائِرِ', t: 'sāʾiri', e: 'the rest of' }, { a: 'الْمَفَاعِيلِ،', t: 'al-mafāʿīli', e: 'the objects' }, NAHW, { g: ':' },
      { a: 'مَفْعُولٌ', t: 'mafʿūlun', e: 'object' }, { a: 'بِهِ', t: 'bihi', e: '(with) it' }, { a: 'وَمَفْعُولٌ', t: 'wa-mafʿūlun', e: 'and object' }, { a: 'فِيهِ', t: 'fīhi', e: '(in) it' }, { a: 'وَمَفْعُولٌ', t: 'wa-mafʿūlun', e: 'and object' }, { a: 'لَهُ', t: 'lahu', e: '(for) it' }, { a: 'وَمَفْعُولٌ', t: 'wa-mafʿūlun', e: 'and object' }, { a: 'مَعَهُ', t: 'maʿahu', e: '(with) it' } ],
  ] },
  { t: 'line', w: [
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' }, { a: 'مَصْدَرٌ', t: 'maṣdarun', e: 'a verbal noun' }, { a: 'بِمَعْنَى', t: 'bi-maʿnā', e: 'in the sense of' }, { a: 'عَامِلٍ', t: 'ʿāmilin', e: 'a governor' }, { a: 'قَبْلَهُ،', t: 'qablahu', e: 'before it' },
  ] },

  { t: 'page', n: '١٣٥' },
  { t: 'box', label: 'مثال', labelEn: 'example', lines: [
    [ { a: 'الْغَالِبُ', t: 'al-ghālibu', e: 'usually' }, { a: 'أَنْ', t: 'an', e: '' }, { a: 'يَكُونَ', t: 'yakūna', e: 'it is' }, { a: 'الْمَفْعُولُ', t: 'al-mafʿūlu', e: 'the object' }, { a: 'الْمُطْلَقُ', t: 'al-muṭlaqu', e: 'absolute' }, { a: 'مَصْدَرَ', t: 'maṣdara', e: 'the verbal noun of' }, { a: 'عَامِلِهِ،', t: 'ʿāmilihi', e: 'its governor' },
      NAHW, { g: ':' }, OPEN, { a: 'وَرَتِّلِ', t: 'wa-rattili', e: 'and recite', q: 1 }, { a: 'الْقُرْآنَ', t: 'al-qurʾāna', e: 'the Qurʾān', q: 1 }, { a: 'تَرْتِيلًا', t: 'tartīlan', e: 'in a measured recitation', q: 1 }, CLOSE ],
    [ { a: 'وَقَدْ', t: 'wa-qad', e: 'and sometimes' }, { a: 'يَكُونُ', t: 'yakūnu', e: 'it is' }, { a: 'مَصْدَرَ', t: 'maṣdara', e: 'the verbal noun of' }, { a: 'فِعْلٍ', t: 'fiʿlin', e: 'a verb' }, { a: 'بِمَعْنَاهُ،', t: 'bi-maʿnāhu', e: 'in its sense' },
      NAHW, { g: ':' }, OPEN, { a: 'وَتَبَتَّلْ', t: 'wa-tabattal', e: 'and devote yourself', q: 1 }, { a: 'إِلَيْهِ', t: 'ilayhi', e: 'to Him', q: 1 }, { a: 'تَبْتِيلًا', t: 'tabtīlan', e: 'with devotion', q: 1 }, CLOSE ],
  ] },
  { t: 'box', label: 'مثال', labelEn: 'example', lines: [
    [ { a: 'وَعَامِلُهُ', t: 'wa-ʿāmiluhu', e: 'and its governor' }, { a: 'يَكُونُ', t: 'yakūnu', e: 'is' }, ELL ],
    [ { a: 'فِعْلًا،', t: 'fiʿlan', e: 'a verb' }, NAHW, { g: ':' },
      OPEN, { a: 'وَرَتِّلِ', t: 'wa-rattili', e: 'and recite', q: 1 }, { a: 'الْقُرْآنَ', t: 'al-qurʾāna', e: 'the Qurʾān', q: 1 }, { a: 'تَرْتِيلًا', t: 'tartīlan', e: 'in a measured recitation', q: 1 }, CLOSE ],
    [ { a: 'أَوْ', t: 'aw', e: 'or' }, { a: 'مَصْدَرًا،', t: 'maṣdaran', e: 'a verbal noun' }, NAHW, { g: ':' },
      OPEN, { a: 'فَإِنَّ', t: 'fa-inna', e: 'then indeed', q: 1 }, { a: 'جَهَنَّمَ', t: 'jahannama', e: 'Hell', q: 1 }, { a: 'جَزَاؤُكُمْ', t: 'jazāʾukum', e: 'is your recompense', q: 1 }, { a: 'جَزَاءً', t: 'jazāʾan', e: 'a recompense', q: 1 }, { a: 'مَوْفُورًا', t: 'mawfūran', e: 'ample', q: 1 }, CLOSE ],
    [ { a: 'أَوْ', t: 'aw', e: 'or' }, { a: 'مُشْتَقًّا،', t: 'mushtaqqan', e: 'a derived noun' }, NAHW, { g: ':' },
      OPEN, { a: 'وَالصَّافَّاتِ', t: 'wa-ṣ-ṣāffāti', e: 'by those ranged', q: 1 }, { a: 'صَفًّا', t: 'ṣaffan', e: 'in ranks', q: 1 }, CLOSE ],
  ] },
  { t: 'box', lines: [
    [ { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' }, ELL ],
    [ { a: 'لِلتَّوْكِيدِ،', t: 'li-t-tawkīdi', e: 'for emphasis' }, NAHW, { g: ':' },
      OPEN, { a: 'وَرَتِّلِ', t: 'wa-rattili', e: 'and recite', q: 1 }, { a: 'الْقُرْآنَ', t: 'al-qurʾāna', e: 'the Qurʾān', q: 1 }, { a: 'تَرْتِيلًا', t: 'tartīlan', e: 'in a measured recitation', q: 1 }, CLOSE ],
  ] },
  { t: 'box', label: 'مثال', labelEn: 'example', lines: [
    [ { a: 'الْمَفْعُولُ', t: 'al-mafʿūlu', e: 'the object' }, { a: 'الْمُطْلَقُ', t: 'al-muṭlaqu', e: 'absolute' }, { a: 'لِلتَّأْكِيدِ', t: 'li-t-taʾkīdi', e: 'for emphasis' }, { a: 'يَكُونُ', t: 'yakūnu', e: 'is' }, { a: 'مُنَكَّرًا', t: 'munakkaran', e: 'indefinite' }, { a: 'غَيْرَ', t: 'ghayra', e: 'not' }, { a: 'مَوْصُوفٍ', t: 'mawṣūfin', e: 'described' }, { a: 'وَلَا', t: 'wa-lā', e: 'nor' }, { a: 'مُضَافٍ،', t: 'muḍāfin', e: 'annexed' },
      { a: 'وَلَا', t: 'wa-lā', e: 'nor' }, { a: 'مَخْتُومٍ', t: 'makhtūmin', e: 'ending' }, { a: 'بِتَاءِ', t: 'bi-tāʾi', e: 'with the tāʾ of' }, { a: 'الْوَحْدَةِ', t: 'al-waḥdati', e: 'unit' }, { a: 'وَلَا', t: 'wa-lā', e: 'nor' }, { a: 'مُثَنًّى', t: 'muthannan', e: 'dual' }, { a: 'وَلَا', t: 'wa-lā', e: 'nor' }, { a: 'مَجْمُوعٍ', t: 'majmūʿin', e: 'plural' } ],
  ] },
  { t: 'box', lines: [
    [ { a: 'أَوْ', t: 'aw', e: 'or' }, { a: 'لِلنَّوْعِ،', t: 'li-n-nawʿi', e: 'for the type' }, { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it' }, { a: 'يَدُلُّ', t: 'yadullu', e: 'indicates' }, { a: 'عَلَى', t: 'ʿalā', e: '' }, { a: 'هَيْئَةِ', t: 'hayʾati', e: 'the manner of' }, { a: 'صُدُورِ', t: 'ṣudūri', e: 'the occurrence of' }, { a: 'الْفِعْلِ،', t: 'al-fiʿli', e: 'the action' }, { a: 'وَيَكُونُ', t: 'wa-yakūnu', e: 'and it is (formed)' } ],
    [ { a: 'بِالْإِضَافَةِ،', t: 'bi-l-iḍāfati', e: 'by annexation' }, NAHW, { g: ':' },
      OPEN, { a: 'وَظَنَنْتُمْ', t: 'wa-ẓanantum', e: 'and you assumed', q: 1 }, { a: 'ظَنَّ', t: 'ẓanna', e: 'the assumption of', q: 1 }, { a: 'السَّوْءِ', t: 'as-sawʾi', e: 'evil', q: 1 }, CLOSE ],
    [ { a: 'أَوِ', t: 'awi', e: 'or' }, { a: 'الصِّفَةِ،', t: 'aṣ-ṣifati', e: 'a description' }, NAHW, { g: ':' },
      OPEN, { a: 'إِنَّا', t: 'innā', e: 'indeed We', q: 1 }, { a: 'فَتَحْنَا', t: 'fataḥnā', e: 'have given you', q: 1 }, { a: 'لَكَ', t: 'laka', e: '', q: 1 }, { a: 'فَتْحًا', t: 'fatḥan', e: 'a victory', q: 1 }, { a: 'مُبِينًا', t: 'mubīnan', e: 'clear', q: 1 }, CLOSE ],
    [ { a: 'أَوِ', t: 'awi', e: 'or' }, { a: 'الْإِشَارَةِ،', t: 'al-ishārati', e: 'a demonstrative' }, NAHW, { g: ':' },
      { a: 'اجْتَهَدَ', t: 'ijtahada', e: 'he strove' }, { a: 'ذَلِكَ', t: 'dhālika', e: 'that' }, { a: 'الِاجْتِهَادَ', t: 'al-ijtihāda', e: 'striving' } ],
    [ { a: 'أَوْ', t: 'aw', e: 'or' }, { a: 'بِلَامِ', t: 'bi-lāmi', e: 'by the lām of' }, { a: 'الْعَهْدِ،', t: 'al-ʿahdi', e: 'reference' }, NAHW, { g: ':' },
      { a: 'اجْتَهَدَ', t: 'ijtahada', e: 'he strove' }, { a: 'الِاجْتِهَادَ', t: 'al-ijtihāda', e: 'the striving' } ],
    [ { a: 'أَوْ', t: 'aw', e: 'or' }, { a: 'لِلْعَدَدِ،', t: 'li-l-ʿadadi', e: 'for number' }, { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it' }, { a: 'يَدُلُّ', t: 'yadullu', e: 'indicates' }, { a: 'عَلَى', t: 'ʿalā', e: '' }, { a: 'عَدَدِ', t: 'ʿadadi', e: 'the count of' }, { a: 'مَرَّاتِ', t: 'marrāti', e: 'the times of' }, { a: 'صُدُورِ', t: 'ṣudūri', e: 'the occurrence of' }, { a: 'الْفِعْلِ،', t: 'al-fiʿli', e: 'the action' },
      NAHW, { g: ':' }, { a: 'سَجَدْتُ', t: 'sajadtu', e: 'I prostrated' }, { a: 'سَجْدَتَيْنِ', t: 'sajdatayni', e: 'two prostrations' } ],
  ] },
  { t: 'box', label: 'مثال', labelEn: 'example', lines: [
    [ { a: 'يَجُوزُ', t: 'yajūzu', e: 'it is permitted' }, { a: 'تَثْنِيَةُ', t: 'tathniyatu', e: 'to dual' }, { a: 'مَصْدَرِ', t: 'maṣdari', e: 'the verbal noun of' }, { a: 'الْعَدَدِ', t: 'al-ʿadadi', e: 'number' }, { a: 'وَجَمْعُهُ', t: 'wa-jamʿuhu', e: 'and to plural it' }, { a: 'بِخِلَافِ', t: 'bi-khilāfi', e: 'unlike' }, { a: 'قَسِيمَيْهِ', t: 'qasīmayhi', e: 'its two counterparts' } ],
  ] },
  { t: 'box', label: 'ما يقوم مقام مصدر الفعل', labelEn: 'what stands in for the verbal noun', lines: [
    [ { a: 'يَقُومُ', t: 'yaqūmu', e: 'stands' }, { a: 'مَقَامَ', t: 'maqāma', e: 'in place of' }, { a: 'مَصْدَرِ', t: 'maṣdari', e: 'the verbal noun of' }, { a: 'الْفِعْلِ', t: 'al-fiʿli', e: 'the verb' }, ELL ],
  ] },

  { t: 'page', n: '١٣٦' },
  { t: 'box', lines: [
    [ { a: 'اسْمُ', t: 'ismu', e: 'the noun of' }, { a: 'الْمَصْدَرِ،', t: 'al-maṣdari', e: 'the verbal noun' }, NAHW, { g: ':' },
      { a: 'نَتَوَضَّأُ', t: 'natawaḍḍaʾu', e: 'we perform ablution' }, { a: 'وُضُوءَ', t: 'wuḍūʾa', e: 'like the ablution of' }, { a: 'رَسُولِ', t: 'rasūli', e: 'the Messenger of' }, { a: 'اللهِ', t: 'Allāhi', e: 'Allah' }, { a: 'ﷺ', t: 'ṣ', e: '(ﷺ)' } ],
    [ { a: 'وَصِفَتُهُ،', t: 'wa-ṣifatuhu', e: 'and its adjective' }, NAHW, { g: ':' },
      OPEN, { a: 'وَاذْكُرْ', t: 'wa-dhkur', e: 'and remember', q: 1 }, { a: 'رَبَّكَ', t: 'rabbaka', e: 'your Lord', q: 1 }, { a: 'كَثِيرًا', t: 'kathīran', e: 'much', q: 1 }, CLOSE ],
    [ { a: 'وَضَمِيرُهُ،', t: 'wa-ḍamīruhu', e: 'and its pronoun' }, NAHW, { g: ':' },
      OPEN, { a: 'فَإِنِّي', t: 'fa-innī', e: 'then indeed I', q: 1 }, { a: 'أُعَذِّبُهُ', t: 'uʿadhdhibuhu', e: 'will punish him', q: 1 }, { a: 'عَذَابًا', t: 'ʿadhāban', e: 'a punishment', q: 1 }, { a: 'لَا', t: 'lā', e: 'not', q: 1 }, { a: 'أُعَذِّبُهُ', t: 'uʿadhdhibuhu', e: 'I punish with it', q: 1 }, { a: 'أَحَدًا', t: 'aḥadan', e: 'anyone', q: 1 }, { a: 'مِنَ', t: 'mina', e: 'of', q: 1 }, { a: 'الْعَالَمِينَ', t: 'al-ʿālamīna', e: 'the worlds', q: 1 }, CLOSE ],
    [ { a: 'وَالْإِشَارَةُ،', t: 'wa-l-ishāratu', e: 'and the demonstrative' }, NAHW, { g: ':' },
      { a: 'اجْتَهَدَ', t: 'ijtahada', e: 'he strove' }, { a: 'ذَلِكَ', t: 'dhālika', e: 'that' }, { a: 'الِاجْتِهَادَ', t: 'al-ijtihāda', e: 'striving' } ],
    [ { a: 'وَمَا', t: 'wa-mā', e: 'and what' }, { a: 'يَدُلُّ', t: 'yadullu', e: 'indicates' }, { a: 'عَلَى', t: 'ʿalā', e: '' }, { a: 'عَدَدِهِ،', t: 'ʿadadihi', e: 'its number' }, NAHW, { g: ':' },
      { a: 'يُصَلِّي', t: 'yuṣallī', e: 'pray' }, { a: 'الْمُسْلِمُونَ', t: 'al-muslimūna', e: 'the Muslims' }, { a: 'خَمْسَ', t: 'khamsa', e: 'five' }, { a: 'مَرَّاتٍ', t: 'marrātin', e: 'times' } ],
    [ { a: 'وَمَا', t: 'wa-mā', e: 'and what' }, { a: 'يَدُلُّ', t: 'yadullu', e: 'indicates' }, { a: 'عَلَى', t: 'ʿalā', e: '' }, { a: 'نَوْعِهِ،', t: 'nawʿihi', e: 'its type' }, NAHW, { g: ':' },
      { a: 'رَجَعَ', t: 'rajaʿa', e: 'he returned' }, { a: 'الْقَهْقَرَى', t: 'al-qahqarā', e: 'walking backwards' } ],
    [ { a: 'وَمَا', t: 'wa-mā', e: 'and what' }, { a: 'يُضَافُ', t: 'yuḍāfu', e: 'is annexed' }, { a: 'إِلَى', t: 'ilā', e: 'to' }, { a: 'الْمَصْدَرِ', t: 'al-maṣdari', e: 'the verbal noun' }, { a: 'مِنْ', t: 'min', e: 'from' }, { a: 'كَلِمَةِ', t: 'kalimati', e: 'the word' }, ELL ],
    [ { a: 'كُلٍّ،', t: 'kullin', e: '“all”' }, NAHW, { g: ':' },
      OPEN, { a: 'وَلَا', t: 'wa-lā', e: 'and do not', q: 1 }, { a: 'تَبْسُطْهَا', t: 'tabsuṭhā', e: 'extend it', q: 1 }, { a: 'كُلَّ', t: 'kulla', e: 'to the utmost of', q: 1 }, { a: 'الْبَسْطِ', t: 'al-basṭi', e: 'extension', q: 1 }, CLOSE ],
    [ { a: 'أَوْ', t: 'aw', e: 'or' }, { a: 'بَعْضٍ،', t: 'baʿḍin', e: '“some”' }, NAHW, { g: ':' },
      { a: 'سَعَيْتُ', t: 'saʿaytu', e: 'I strove' }, { a: 'بَعْضَ', t: 'baʿḍa', e: 'some of' }, { a: 'السَّعْيِ', t: 'as-saʿyi', e: 'the striving' } ],
    [ { a: 'أَوْ', t: 'aw', e: 'or' }, { a: 'أَيٍّ،', t: 'ayyin', e: '“which/what”' }, NAHW, { g: ':' },
      OPEN, { a: 'وَسَيَعْلَمُ', t: 'wa-sa-yaʿlamu', e: 'and will know', q: 1 }, { a: 'الَّذِينَ', t: 'alladhīna', e: 'those who', q: 1 }, { a: 'ظَلَمُوا', t: 'ẓalamū', e: 'did wrong', q: 1 }, { a: 'أَيَّ', t: 'ayya', e: 'what', q: 1 }, { a: 'مُنْقَلَبٍ', t: 'munqalabin', e: 'return', q: 1 }, { a: 'يَنْقَلِبُونَ', t: 'yanqalibūna', e: 'they will return to', q: 1 }, CLOSE ],
  ] },
  { t: 'box', label: 'نيابة المفعول المطلق عن فعله', labelEn: 'the absolute object standing in for its verb', lines: [
    [ { a: 'قَدْ', t: 'qad', e: 'sometimes' }, { a: 'يَنُوبُ', t: 'yanūbu', e: 'stands in' }, { a: 'الْمَفْعُولُ', t: 'al-mafʿūlu', e: 'the object' }, { a: 'الْمُطْلَقُ', t: 'al-muṭlaqu', e: 'absolute' }, { a: 'عَنْ', t: 'ʿan', e: 'for' }, { a: 'فِعْلِهِ،', t: 'fiʿlihi', e: 'its verb' }, { a: 'وَيَقَعُ', t: 'wa-yaqaʿu', e: 'and it occurs (as)' }, ELL ],
    [ { a: 'أَمْرًا،', t: 'amran', e: 'a command' }, NAHW, { g: ':' },
      OPEN, { a: 'وَبِالْوَالِدَيْنِ', t: 'wa-bi-l-wālidayni', e: 'and to parents', q: 1 }, { a: 'إِحْسَانًا', t: 'iḥsānan', e: 'do good', q: 1 }, CLOSE ],
    [ { a: 'وَنَهْيًا،', t: 'wa-nahyan', e: 'and a prohibition' }, NAHW, { g: ':' },
      { a: 'صَبْرًا', t: 'ṣabran', e: 'be patient' }, { a: 'لَا', t: 'lā', e: 'not' }, { a: 'جَزَعًا', t: 'jazaʿan', e: 'anxious' } ],
    [ { a: 'وَدُعَاءً،', t: 'wa-duʿāʾan', e: 'and a supplication' }, NAHW, { g: ':' },
      OPEN, { a: 'بُعْدًا', t: 'buʿdan', e: 'away', q: 1 }, { a: 'لِلْقَوْمِ', t: 'li-l-qawmi', e: 'with the people', q: 1 }, { a: 'الظَّالِمِينَ', t: 'aẓ-ẓālimīna', e: 'wrongdoing', q: 1 }, CLOSE ],
    [ { a: 'وَمُؤَكِّدًا', t: 'wa-muʾakkidan', e: 'and emphasizing' }, { a: 'لِمَضْمُونِ', t: 'li-maḍmūni', e: 'the content of' }, { a: 'الْجُمْلَةِ', t: 'al-jumlati', e: 'the clause' }, { a: 'قَبْلَهُ،', t: 'qablahu', e: 'before it' },
      NAHW, { g: ':' }, OPEN, { a: 'أُولَئِكَ', t: 'ulāʾika', e: 'those', q: 1 }, { a: 'هُمُ', t: 'humu', e: 'are', q: 1 }, { a: 'الْمُؤْمِنُونَ', t: 'al-muʾminūna', e: 'the believers', q: 1 }, { a: 'حَقًّا', t: 'ḥaqqan', e: 'truly', q: 1 }, CLOSE ],
    [ { a: 'وَتَفْصِيلًا', t: 'wa-tafṣīlan', e: 'and detailing' }, { a: 'لِعَاقِبَةِ', t: 'li-ʿāqibati', e: 'the outcome of' }, { a: 'الْجُمْلَةِ', t: 'al-jumlati', e: 'the clause' }, { a: 'قَبْلَهُ،', t: 'qablahu', e: 'before it' },
      NAHW, { g: ':' }, OPEN, { a: 'فَشُدُّوا', t: 'fa-shuddū', e: 'then bind firmly', q: 1 }, { a: 'الْوَثَاقَ', t: 'al-wathāqa', e: 'the bonds', q: 1 }, { a: 'فَإِمَّا', t: 'fa-immā', e: 'then either', q: 1 }, { a: 'مَنًّا', t: 'mannan', e: 'a favor', q: 1 }, { a: 'بَعْدُ', t: 'baʿdu', e: 'afterward', q: 1 }, { a: 'وَإِمَّا', t: 'wa-immā', e: 'or', q: 1 }, { a: 'فِدَاءً', t: 'fidāʾan', e: 'a ransom', q: 1 }, CLOSE ],
    [ { a: 'وَمِنْهَا', t: 'wa-minhā', e: 'and among them are' }, { a: 'مَصَادِرُ', t: 'maṣādiru', e: 'verbal nouns' }, { a: 'مَسْمُوعَةٌ،', t: 'masmūʿatun', e: 'heard (idiomatic)' }, NAHW, { g: ':' },
      OPEN, { a: 'سُبْحَانَكَ', t: 'subḥānaka', e: 'glory be to You', q: 1 }, CLOSE, { a: 'وَ', t: 'wa', e: 'and' }, OPEN, { a: 'مَعَاذَ', t: 'maʿādha', e: 'refuge of', q: 1 }, { a: 'اللهِ', t: 'Allāhi', e: 'Allah', q: 1 }, CLOSE,
      { a: 'وَ', t: 'wa', e: 'and' }, OPEN, { a: 'حِجْرًا', t: 'ḥijran', e: 'a barrier', q: 1 }, { a: 'مَحْجُورًا', t: 'maḥjūran', e: 'forbidden', q: 1 }, CLOSE, { a: 'وَلَبَّيْكَ', t: 'wa-labbayka', e: 'and at Your service' }, { a: 'وَغُفْرَانَكَ', t: 'wa-ghufrānaka', e: 'and Your forgiveness' } ],
  ] },
  { t: 'h2', c: 'red', ar: 'الثَّانِي: الْمَفْعُولُ بِهِ', en: 'Second — the Direct Object (mafʿūl bihi)' },
  { t: 'line', w: [
    { a: 'الثَّانِي', t: 'ath-thānī', e: 'the second (is)' }, { a: 'الْمَفْعُولُ', t: 'al-mafʿūlu', e: 'the object' }, { a: 'بِهِ،', t: 'bihi', e: 'acted upon' },
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' }, { a: 'مَا', t: 'mā', e: 'what' }, { a: 'وَقَعَ', t: 'waqaʿa', e: 'befell' }, { a: 'عَلَيْهِ', t: 'ʿalayhi', e: 'upon it' }, { a: 'الْفِعْلُ،', t: 'al-fiʿlu', e: 'the action' },
    NAHW, { g: ':' }, OPEN, { a: 'اعْبُدُوا', t: 'uʿbudū', e: 'worship', q: 1 }, { a: 'رَبَّكُمْ', t: 'rabbakum', e: 'your Lord', q: 1 }, CLOSE,
  ] },

  { t: 'page', n: '١٣٧' },
  { t: 'box', label: 'تقديم المفعول به', labelEn: 'fronting the direct object', lines: [
    [ { a: 'الْأَصْلُ', t: 'al-aṣlu', e: 'the norm' }, { a: 'فِي', t: 'fī', e: 'for' }, { a: 'الْمَفْعُولِ', t: 'al-mafʿūli', e: 'the object' }, { a: 'بِهِ', t: 'bihi', e: '' }, { a: 'أَنْ', t: 'an', e: 'is' }, { a: 'يَكُونَ', t: 'yakūna', e: 'to be' }, { a: 'بَعْدَ', t: 'baʿda', e: 'after' }, { a: 'الْفِعْلِ', t: 'al-fiʿli', e: 'the verb' }, { a: 'وَالْفَاعِلِ،', t: 'wa-l-fāʿili', e: 'and the agent' },
      { a: 'وَيَتَقَدَّمُ', t: 'wa-yataqaddamu', e: 'and it precedes' }, { a: 'عَلَى', t: 'ʿalā', e: '' }, { a: 'الْفِعْلِ', t: 'al-fiʿli', e: 'the verb' }, ELL ],
    [ { a: 'جَوَازًا،', t: 'jawāzan', e: 'permissibly' }, NAHW, { g: ':' },
      OPEN, { a: 'إِيَّاكَ', t: 'iyyāka', e: 'You alone', q: 1 }, { a: 'نَعْبُدُ', t: 'naʿbudu', e: 'we worship', q: 1 }, CLOSE ],
    [ { a: 'وَوُجُوبًا', t: 'wa-wujūban', e: 'and obligatorily' }, { a: 'إِنْ', t: 'in', e: 'if' }, { a: 'كَانَ', t: 'kāna', e: 'it is' }, { a: 'مِمَّا', t: 'mimmā', e: 'of what' }, { a: 'يَقْتَضِي', t: 'yaqtaḍī', e: 'requires' }, { a: 'صَدْرَ', t: 'ṣadra', e: 'the front of' }, { a: 'الْكَلَامِ،', t: 'al-kalāmi', e: 'the speech' }, { a: 'مِثْلُ', t: 'mithlu', e: 'like' }, ELL ],
    [ { a: 'الشَّرْطِ،', t: 'ash-sharṭi', e: 'the conditional' }, NAHW, { g: ':' },
      OPEN, { a: 'أَيًّا', t: 'ayyan', e: 'whichever', q: 1 }, { a: 'مَا', t: 'mā', e: '', q: 1 }, { a: 'تَدْعُوا', t: 'tadʿū', e: 'you call upon', q: 1 }, CLOSE ],
    [ { a: 'وَالِاسْتِفْهَامِ،', t: 'wa-l-istifhāmi', e: 'and the interrogative' }, NAHW, { g: ':' },
      OPEN, { a: 'فَأَيَّ', t: 'fa-ayya', e: 'then which', q: 1 }, { a: 'آيَاتِ', t: 'āyāti', e: 'signs of', q: 1 }, { a: 'اللهِ', t: 'Allāhi', e: 'Allah', q: 1 }, { a: 'تُنْكِرُونَ', t: 'tunkirūna', e: 'do you deny', q: 1 }, CLOSE,
      { a: 'وَمِنْهُ', t: 'wa-minhu', e: 'and among it is' }, { a: 'كَمِ', t: 'kami', e: 'kam' }, { a: 'الْخَبَرِيَّةِ،', t: 'al-khabariyyati', e: 'the declarative' }, NAHW, { g: ':' },
      OPEN, { a: 'وَكَمْ', t: 'wa-kam', e: 'and how many', q: 1 }, { a: 'أَرْسَلْنَا', t: 'arsalnā', e: 'We sent', q: 1 }, { a: 'مِنْ', t: 'min', e: 'of', q: 1 }, { a: 'نَبِيٍّ', t: 'nabiyyin', e: 'a prophet', q: 1 }, { a: 'فِي', t: 'fī', e: 'among', q: 1 }, { a: 'الْأَوَّلِينَ', t: 'al-awwalīna', e: 'the former peoples', q: 1 }, CLOSE, { a: 'وَغَيْرُهَا', t: 'wa-ghayruhā', e: 'and others' } ],
  ] },
  { t: 'h2', c: 'red', ar: 'الثَّالِثُ: الْمَفْعُولُ فِيهِ', en: 'Third — the Adverbial Object (mafʿūl fīhi)' },
  { t: 'line', w: [
    { a: 'الثَّالِثُ', t: 'ath-thālithu', e: 'the third (is)' }, { a: 'الْمَفْعُولُ', t: 'al-mafʿūlu', e: 'the object' }, { a: 'فِيهِ،', t: 'fīhi', e: 'within which' },
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' }, { a: 'مَا', t: 'mā', e: 'what' }, { a: 'وَقَعَ', t: 'waqaʿa', e: 'occurred' }, { a: 'فِيهِ', t: 'fīhi', e: 'in it' }, { a: 'الْفِعْلُ', t: 'al-fiʿlu', e: 'the action' }, { a: 'مِنَ', t: 'mina', e: 'of' }, { a: 'الْمَكَانِ', t: 'al-makāni', e: 'place' }, { a: 'أَوِ', t: 'awi', e: 'or' }, { a: 'الزَّمَانِ،', t: 'az-zamāni', e: 'time' },
    NAHW, { g: ':' }, { a: 'أَحْسِنِي', t: 'aḥsinī', e: 'be good' }, { a: 'إِلَى', t: 'ilā', e: 'to' }, { a: 'أُمِّكِ', t: 'ummiki', e: 'your mother' }, { a: 'أَبَدًا', t: 'abadan', e: 'always' }, { a: 'فَإِنَّ', t: 'fa-inna', e: 'for indeed' }, { a: 'الْجَنَّةَ', t: 'al-jannata', e: 'Paradise' }, { a: 'تَحْتَ', t: 'taḥta', e: 'is beneath' }, { a: 'قَدَمَيْهَا', t: 'qadamayhā', e: 'her feet' },
  ] },
  { t: 'box', label: 'الظرف', labelEn: 'the adverbial (ẓarf)', lines: [
    [ { a: 'يُسَمَّى', t: 'yusammā', e: 'is called' }, { a: 'الْمَفْعُولُ', t: 'al-mafʿūlu', e: 'the object' }, { a: 'فِيهِ', t: 'fīhi', e: 'within which' }, { a: 'ظَرْفًا', t: 'ẓarfan', e: 'an adverbial (ẓarf)' } ],
  ] },
  { t: 'box', label: 'مثال', labelEn: 'example', lines: [
    [ { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' }, { a: 'قِسْمَانِ', t: 'qismāni', e: 'two divisions' }, { a: 'ظَرْفُ', t: 'ẓarfu', e: 'adverbial of' }, { a: 'زَمَانٍ', t: 'zamānin', e: 'time' }, { a: 'وَظَرْفُ', t: 'wa-ẓarfu', e: 'and adverbial of' }, { a: 'مَكَانٍ', t: 'makānin', e: 'place' } ],
  ] },
  { t: 'box', label: 'ظرف الزمان', labelEn: 'the adverbial of time', lines: [
    [ { a: 'ظَرْفُ', t: 'ẓarfu', e: 'the adverbial of' }, { a: 'الزَّمَانِ', t: 'az-zamāni', e: 'time' }, { a: 'نَوْعَانِ', t: 'nawʿāni', e: 'is two types' }, { g: ':' } ],
    [ { a: 'الْأَوَّلُ', t: 'al-awwalu', e: 'the first', c: 'red' }, { a: 'مُبْهَمٌ،', t: 'mubhamun', e: 'vague' }, { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' }, { a: 'مَا', t: 'mā', e: 'what' }, { a: 'دَلَّ', t: 'dalla', e: 'denotes' }, { a: 'عَلَى', t: 'ʿalā', e: '' }, { a: 'زَمَانٍ', t: 'zamānin', e: 'a time' }, { a: 'غَيْرِ', t: 'ghayri', e: 'not' }, { a: 'مُعَيَّنٍ،', t: 'muʿayyanin', e: 'specified' },
      { a: 'مِثْلُ', t: 'mithlu', e: 'like' }, { a: 'أَبَدٍ', t: 'abadin', e: '“ever”' }, { a: 'وَحِينٍ', t: 'wa-ḥīnin', e: '“a while”' }, { a: 'وَوَقْتٍ', t: 'wa-waqtin', e: '“a time”' }, { a: 'وَزَمَانٍ', t: 'wa-zamānin', e: '“a period”' }, { a: 'وَغَيْرِهَا،', t: 'wa-ghayrihā', e: 'and others' }, { a: 'وَيَجُوزُ', t: 'wa-yajūzu', e: 'and permitted' }, { a: 'فِيهِ', t: 'fīhi', e: 'in it' }, ELL ],
    [ { a: 'النَّصْبُ', t: 'an-naṣbu', e: 'the accusative' }, { a: 'بِحَرْفِ', t: 'bi-ḥarfi', e: 'by a particle of' }, { a: 'جَرٍّ', t: 'jarrin', e: 'the genitive' }, { a: 'مُقَدَّرٍ،', t: 'muqaddarin', e: 'implicit' },
      NAHW, { g: ':' }, OPEN, { a: 'يَرَاكَ', t: 'yarāka', e: 'He sees you', q: 1 }, { a: 'حِينَ', t: 'ḥīna', e: 'when', q: 1 }, { a: 'تَقُومُ', t: 'taqūmu', e: 'you stand', q: 1 }, CLOSE ],
    [ { a: 'وَالْجَرُّ', t: 'wa-l-jarru', e: 'and the genitive' }, { a: 'بِحَرْفِ', t: 'bi-ḥarfi', e: 'by a particle of' }, { a: 'جَرٍّ', t: 'jarrin', e: 'the genitive' }, { a: 'ظَاهِرٍ،', t: 'ẓāhirin', e: 'overt' },
      NAHW, { g: ':' }, OPEN, { a: 'وَمَتِّعُوهُمْ', t: 'wa-mattiʿūhum', e: 'and provide for them', q: 1 }, { a: 'إِلَى', t: 'ilā', e: 'until', q: 1 }, { a: 'حِينٍ', t: 'ḥīnin', e: 'a time', q: 1 }, CLOSE ],
    [ { a: 'الثَّانِي', t: 'ath-thānī', e: 'the second', c: 'red' }, { a: 'مَحْدُودٌ،', t: 'maḥdūdun', e: 'delimited' }, { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' }, { a: 'مَا', t: 'mā', e: 'what' }, { a: 'دَلَّ', t: 'dalla', e: 'denotes' }, { a: 'عَلَى', t: 'ʿalā', e: '' }, { a: 'زَمَانٍ', t: 'zamānin', e: 'a time' }, { a: 'مُعَيَّنٍ،', t: 'muʿayyanin', e: 'specified' },
      { a: 'مِثْلُ', t: 'mithlu', e: 'like' }, { a: 'سَاعَةٍ', t: 'sāʿatin', e: '“hour”' }, { a: 'وَيَوْمٍ', t: 'wa-yawmin', e: '“day”' }, { a: 'وَلَيْلَةٍ', t: 'wa-laylatin', e: '“night”' }, { a: 'وَأُسْبُوعٍ', t: 'wa-usbūʿin', e: '“week”' }, { a: 'وَشَهْرٍ', t: 'wa-shahrin', e: '“month”' }, { a: 'وَسَنَةٍ', t: 'wa-sanatin', e: '“year”' }, { a: 'وَعَامٍ', t: 'wa-ʿāmin', e: '“year”' }, { a: 'وَغَيْرِهَا،', t: 'wa-ghayrihā', e: 'and others' }, { a: 'وَيَجُوزُ', t: 'wa-yajūzu', e: 'and permitted' }, { a: 'فِيهِ', t: 'fīhi', e: 'in it' }, ELL ],
  ] },
];

if (typeof module !== 'undefined') { module.exports = { DATA_M2A }; }
