/* ── al-Kubrā fī an-Naḥw — المقصد الأول · الباب الأول في الفعل (pp. 22–25) ──
   النوع الأول: القياسي — the intransitive verb (lāzim) and the transitive verb (mutaʿaddī)
   through the verbs of the heart (af'āl al-qulūb: yaqīn & ẓann).
   Reuses shared glyphs from muqaddimah.js. مسألة/فائدة commentary boxes & footnotes omitted.   */

const DATA_M1_BAB1 = [
  { t: 'page', n: '٢٢' },

  { t: 'h1', ar: 'الْبَابُ الْأَوَّلُ فِي الْفِعْلِ', en: 'The First Chapter — On the Verb' },
  { t: 'line', w: [
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
    { a: 'نَوْعَانِ', t: 'nawʿāni', e: 'two types' }, { g: ':' },
  ] },

  /* ── Type 1: the regular (qiyāsī) verb ── */
  { t: 'h2', c: 'green', ar: 'النَّوْعُ الْأَوَّلُ: الْقِيَاسِيُّ', en: 'First type — the regular verb (al-qiyāsī)' },
  { t: 'line', w: [
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it' },
    { a: 'يَرْفَعُ', t: 'yarfaʿu', e: 'puts in the nominative' },
    { a: 'الْفَاعِلَ', t: 'al-fāʿila', e: 'the doer (fāʿil)' },
    { a: 'أَوْ', t: 'aw', e: 'or' },
    { a: 'نَائِبَهُ', t: 'nāʾibahu', e: 'its deputy (nāʾib al-fāʿil)' },
    { a: 'وَيَنْصِبُ', t: 'wa-yanṣibu', e: 'and puts in the accusative' },
    { a: 'الْمَفَاعِيلَ', t: 'al-mafāʿīla', e: 'the objects (mafāʿīl)' },
    { a: 'وَالْحَالَ', t: 'wal-ḥāla', e: 'and the circumstantial (ḥāl)' },
  ] },
  { t: 'box', label: 'معنى القياسي', labelEn: 'Meaning of qiyāsī', lines: [
    [
      { a: 'الْقِيَاسِيُّ', t: 'al-qiyāsiyyu', e: 'the regular (qiyāsī)' },
      { a: 'مَا', t: 'mā', e: 'is what' },
      { a: 'لَهُ', t: 'lahu', e: 'has' },
      { a: 'قَاعِدَةٌ', t: 'qāʿidatun', e: 'a rule' },
      { a: 'مُطَّرِدَةٌ', t: 'muṭṭaridatun', e: 'consistent (always applicable)' },
    ],
  ] },
  { t: 'line', w: [
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
    { a: 'قِسْمَانِ', t: 'qismāni', e: 'two divisions' }, { g: ':' },
  ] },

  { t: 'h2', c: 'blue', ar: 'الْقِسْمُ الْأَوَّلُ: الْفِعْلُ اللَّازِمُ', en: 'First division — the intransitive verb (al-fiʿl al-lāzim)' },
  { t: 'line', w: [
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
    { a: 'الَّذِي', t: 'alladhī', e: 'that which' },
    { a: 'لَا', t: 'lā', e: 'does not' },
    { a: 'يَتَجَاوَزُ', t: 'yatajāwazu', e: 'pass' },
    { a: 'أَثَرُ', t: 'atharu', e: 'the effect of' },
    { a: 'فَاعِلِهِ', t: 'fāʿilihi', e: 'its doer' },
    { a: 'إِلَى', t: 'ilā', e: 'to' },
    { a: 'الْمَفْعُولِ', t: 'al-mafʿūli', e: 'an object' },
    { a: 'بِهِ،', t: 'bihi', e: '(direct)' },
    NAHW, { g: ':' }, OPEN,
    { a: 'وَلَا', t: 'wa-lā', e: 'nor', q: 1 },
    { a: 'هُمْ', t: 'hum', e: 'will they', q: 1 },
    { a: 'يَحْزَنُونَ', t: 'yaḥzanūna', e: 'grieve', q: 1 },
    CLOSE,
  ] },

  /* ── the transitive verb ── */
  { t: 'page', n: '٢٣' },
  { t: 'h2', c: 'blue', ar: 'الْقِسْمُ الثَّانِي: الْفِعْلُ الْمُتَعَدِّي', en: 'Second division — the transitive verb (al-fiʿl al-mutaʿaddī)' },
  { t: 'line', w: [
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
    { a: 'الَّذِي', t: 'alladhī', e: 'that which' },
    { a: 'يَتَجَاوَزُ', t: 'yatajāwazu', e: 'passes' },
    { a: 'أَثَرُ', t: 'atharu', e: 'the effect of' },
    { a: 'فَاعِلِهِ', t: 'fāʿilihi', e: 'its doer' },
    { a: 'إِلَى', t: 'ilā', e: 'to' },
    { a: 'الْمَفْعُولِ', t: 'al-mafʿūli', e: 'the object' },
    { a: 'بِهِ', t: 'bihi', e: '(direct)' },
  ] },
  { t: 'box', label: 'المتعدّي بنفسه وبواسطة حرف الجر', labelEn: 'Transitive directly or via a preposition', lines: [
    [
      { a: 'يَكُونُ', t: 'yakūnu', e: 'the verb is' },
      { a: 'الْفِعْلُ', t: 'al-fiʿlu', e: '' },
      { a: 'مُتَعَدِّيًا', t: 'mutaʿaddiyan', e: 'transitive' },
      ELL,
    ],
    [
      { a: 'بِنَفْسِهِ،', t: 'bi-nafsihi', e: 'by itself' },
      NAHW, { g: ':' }, OPEN,
      { a: 'الْحَمْدُ', t: 'al-ḥamdu', e: 'Praise', q: 1 },
      { a: 'لِلهِ', t: 'li-llāhi', e: 'be to Allah', q: 1 },
      { a: 'الَّذِي', t: 'alladhī', e: 'who', q: 1 },
      { a: 'أَذْهَبَ', t: 'adhhaba', e: 'removed', q: 1 },
      { a: 'عَنَّا', t: 'ʿannā', e: 'from us', q: 1 },
      { a: 'الْحَزَنَ', t: 'al-ḥazana', e: 'grief', q: 1 },
      CLOSE,
    ],
    [
      { a: 'وَبِوَاسِطَةِ', t: 'wa-bi-wāsiṭati', e: 'and by means of' },
      { a: 'حَرْفِ', t: 'ḥarfi', e: 'a particle of' },
      { a: 'جَرٍّ،', t: 'jarrin', e: 'genitive (a preposition)' },
      NAHW, { g: ':' }, OPEN,
      { a: 'ذَهَبَ', t: 'dhahaba', e: 'took away', q: 1 },
      { a: 'اللهُ', t: 'Allāhu', e: 'Allah', q: 1 },
      { a: 'بِنُورِهِمْ', t: 'bi-nūrihim', e: 'their light', q: 1 },
      CLOSE,
    ],
    [
      { a: 'وَحِينَئِذٍ', t: 'wa-ḥīnaʾidhin', e: 'and then' },
      { a: 'يُسَمَّى', t: 'yusammā', e: 'is called' },
      { a: 'الْمَفْعُولُ', t: 'al-mafʿūlu', e: 'the object' },
      { a: 'بِهِ', t: 'bihi', e: '' },
      { a: 'مَفْعُولًا', t: 'mafʿūlan', e: 'an object' },
      { a: 'بِهِ', t: 'bihi', e: '' },
      { a: 'بِوَاسِطَةِ', t: 'bi-wāsiṭati', e: 'by means of' },
      { a: 'حَرْفِ', t: 'ḥarfi', e: 'the particle of' },
      { a: 'الْجَرِّ', t: 'al-jarri', e: 'genitive' },
      { a: 'أَوْ', t: 'aw', e: 'or' },
      { a: 'مُتَعَلِّقًا', t: 'mutaʿalliqan', e: 'an attached one (mutaʿalliq)' },
      { a: 'بِمَعْنَى', t: 'bi-maʿnā', e: 'with the sense of' },
      { a: 'الْمَفْعُولِ', t: 'al-mafʿūli', e: 'the object' },
      { a: 'بِهِ', t: 'bihi', e: '' },
      { a: 'أَوْ', t: 'aw', e: 'or' },
      { a: 'مَفْعُولًا', t: 'mafʿūlan', e: 'an object' },
      { a: 'بِهِ', t: 'bihi', e: '' },
      { a: 'غَيْرَ', t: 'ghayra', e: 'not' },
      { a: 'صَرِيحٍ', t: 'ṣarīḥin', e: 'explicit' },
    ],
  ] },
  { t: 'line', w: [
    { a: 'وَالْفِعْلُ', t: 'wal-fiʿlu', e: 'and the verb' },
    { a: 'الْمُتَعَدِّي', t: 'al-mutaʿaddī', e: 'transitive' },
    { a: 'ثَلَاثَةُ', t: 'thalāthatu', e: 'is three' },
    { a: 'أَضْرُبٍ', t: 'aḍrubin', e: 'kinds' }, { g: ':' },
  ] },

  { t: 'h2', c: 'green', ar: 'الضَّرْبُ الْأَوَّلُ: الْمُتَعَدِّي إِلَى مَفْعُولٍ وَاحِدٍ', en: 'First kind — transitive to one object' },
  { t: 'line', w: [
    NAHW, { g: ':' }, OPEN,
    { a: 'خَلَقَ', t: 'khalaqa', e: 'He created', q: 1 },
    { a: 'السَّمَاوَاتِ', t: 'as-samāwāti', e: 'the heavens', q: 1 },
    { a: 'وَالْأَرْضَ', t: 'wal-arḍa', e: 'and the earth', q: 1 },
    CLOSE,
  ] },

  { t: 'h2', c: 'green', ar: 'الضَّرْبُ الثَّانِي: الْمُتَعَدِّي إِلَى مَفْعُولَيْنِ', en: 'Second kind — transitive to two objects' },
  { t: 'line', w: [
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
    { a: 'اثْنَانِ', t: 'ithnāni', e: 'two' }, { g: ':' },
  ] },
  { t: 'line', w: [
    { a: 'الْأَوَّلُ', t: 'al-awwalu', e: 'the first' },
    { a: 'فِعْلٌ', t: 'fiʿlun', e: 'a verb' },
    { a: 'لَيْسَ', t: 'laysa', e: 'whose' },
    { a: 'مَفْعُولَاهُ', t: 'mafʿūlāhu', e: 'two objects were not' },
    { a: 'مُبْتَدَأً', t: 'mubtadaʾan', e: 'subject' },
    { a: 'وَخَبَرًا', t: 'wa-khabaran', e: 'and predicate' },
    { a: 'فِي', t: 'fī', e: 'in' },
    { a: 'الْأَصْلِ،', t: 'al-aṣli', e: 'origin' },
    NAHW, { g: ':' }, OPEN,
    { a: 'وَهَدَيْنَاهُمَا', t: 'wa-hadaynāhumā', e: 'and We guided them both', q: 1 },
    { a: 'الصِّرَاطَ', t: 'aṣ-ṣirāṭa', e: 'the path', q: 1 },
    { a: 'الْمُسْتَقِيمَ', t: 'al-mustaqīma', e: 'straight', q: 1 },
    CLOSE,
  ] },

  { t: 'page', n: '٢٤' },
  { t: 'line', w: [
    { a: 'الْمَفْعُولُ', t: 'al-mafʿūlu', e: '[one may drop] the object' },
    { a: 'الْأَوَّلُ،', t: 'al-awwalu', e: 'first' },
    NAHW, { g: ':' }, OPEN,
    { a: 'وَإِنَّكَ', t: 'wa-innaka', e: 'and indeed you', q: 1 },
    { a: 'لَتَهْدِي', t: 'la-tahdī', e: 'surely guide', q: 1 },
    { a: 'إِلَى', t: 'ilā', e: 'to', q: 1 },
    { a: 'صِرَاطٍ', t: 'ṣirāṭin', e: 'a path', q: 1 },
    { a: 'مُسْتَقِيمٍ', t: 'mustaqīmin', e: 'straight', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'أَوِ', t: 'awi', e: 'or' },
    { a: 'الْمَفْعُولُ', t: 'al-mafʿūlu', e: 'the object' },
    { a: 'الثَّانِي،', t: 'ath-thānī', e: 'second' },
    NAHW, { g: ':' }, OPEN,
    { a: 'أُولَئِكَ', t: 'ulāʾika', e: 'those are', q: 1 },
    { a: 'الَّذِينَ', t: 'alladhīna', e: 'whom', q: 1 },
    { a: 'هَدَاهُمُ', t: 'hadāhumu', e: 'has guided', q: 1 },
    { a: 'اللهُ', t: 'Allāhu', e: 'Allah', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'أَوْ', t: 'aw', e: 'or' },
    { a: 'كِلَاهُمَا،', t: 'kilāhumā', e: 'both of them' },
    NAHW, { g: ':' }, OPEN,
    { a: 'أَعْطَى', t: 'aʿṭā', e: 'He gave', q: 1 },
    { a: 'كُلَّ', t: 'kulla', e: 'each', q: 1 },
    { a: 'شَيْءٍ', t: 'shayʾin', e: 'thing', q: 1 },
    { a: 'خَلْقَهُ', t: 'khalqahu', e: 'its form', q: 1 },
    { a: 'ثُمَّ', t: 'thumma', e: 'then', q: 1 },
    { a: 'هَدَى', t: 'hadā', e: 'guided', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'الثَّانِي', t: 'ath-thānī', e: 'the second' },
    { a: 'فِعْلٌ', t: 'fiʿlun', e: 'a verb' },
    { a: 'مَفْعُولَاهُ', t: 'mafʿūlāhu', e: 'whose two objects (were)' },
    { a: 'مُبْتَدَأٌ', t: 'mubtadaʾun', e: 'subject' },
    { a: 'وَخَبَرٌ', t: 'wa-khabarun', e: 'and predicate' },
    { a: 'فِي', t: 'fī', e: 'in' },
    { a: 'الْأَصْلِ،', t: 'al-aṣli', e: 'origin' },
    NAHW, { g: ':' }, OPEN,
    { a: 'وَمَا', t: 'wa-mā', e: 'and not', q: 1 },
    { a: 'أَظُنُّ', t: 'aẓunnu', e: 'do I think', q: 1 },
    { a: 'السَّاعَةَ', t: 'as-sāʿata', e: 'the Hour', q: 1 },
    { a: 'قَائِمَةً', t: 'qāʾimatan', e: 'will occur', q: 1 },
    CLOSE,
  ] },

  { t: 'h2', c: 'plain', ar: 'أَفْعَالُ الْقُلُوبِ', en: 'The verbs of the heart (af‘āl al-qulūb)' },
  { t: 'line', w: [
    { a: 'أَفْعَالُ', t: 'afʿālu', e: 'the verbs of' },
    { a: 'الْقُلُوبِ', t: 'al-qulūbi', e: 'the heart' },
    { a: 'اثْنَانِ', t: 'ithnāni', e: 'are two [kinds]' },
  ] },
  { t: 'line', w: [
    { a: 'الْأَوَّلُ', t: 'al-awwalu', e: 'the first' },
    { a: 'مَا', t: 'mā', e: 'those that' },
    { a: 'تَدُلُّ', t: 'tadullu', e: 'denote' },
    { a: 'عَلَى', t: 'ʿalā', e: '' },
    { a: 'الْيَقِينِ،', t: 'al-yaqīni', e: 'certainty (yaqīn)' },
    { a: 'وَهِيَ', t: 'wa-hiya', e: 'and they are' }, { g: ':' },
  ] },
  { t: 'line', w: [
    { a: 'وَجَدَ،', t: 'wajada', e: 'wajada (to find / deem)' },
    NAHW, { g: ':' }, OPEN,
    { a: 'وَإِنْ', t: 'wa-in', e: 'and indeed', q: 1 },
    { a: 'وَجَدْنَا', t: 'wajadnā', e: 'We found', q: 1 },
    { a: 'أَكْثَرَهُمْ', t: 'aktharahum', e: 'most of them', q: 1 },
    { a: 'لَفَاسِقِينَ', t: 'la-fāsiqīna', e: 'defiantly disobedient', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'وَأَلْفَى،', t: 'wa-alfā', e: 'and alfā (to find)' },
    NAHW, { g: ':' }, OPEN,
    { a: 'أَلْفَوْا', t: 'alfaw', e: 'they found', q: 1 },
    { a: 'آبَاءَهُمْ', t: 'ābāʾahum', e: 'their fathers', q: 1 },
    { a: 'ضَالِّينَ', t: 'ḍāllīna', e: 'astray', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'وَرَأَى،', t: 'wa-raʾā', e: 'and raʾā (to deem)' },
    NAHW, { g: ':' }, OPEN,
    { a: 'إِنَّهُمْ', t: 'innahum', e: 'indeed they', q: 1 },
    { a: 'يَرَوْنَهُ', t: 'yarawnahu', e: 'see it', q: 1 },
    { a: 'بَعِيدًا', t: 'baʿīdan', e: 'far off', q: 1 },
    { a: 'وَنَرَاهُ', t: 'wa-narāhu', e: 'but We see it', q: 1 },
    { a: 'قَرِيبًا', t: 'qarīban', e: 'near', q: 1 },
    CLOSE,
  ] },

  { t: 'page', n: '٢٥' },
  { t: 'line', w: [
    { a: 'وَعَلِمَ،', t: 'wa-ʿalima', e: 'and ʿalima (to know for certain)' },
    NAHW, { g: ':' }, OPEN,
    { a: 'وَيَعْلَمُونَ', t: 'wa-yaʿlamūna', e: 'and they know', q: 1 },
    { a: 'أَنَّهُ', t: 'annahu', e: 'that it', q: 1 },
    { a: 'الْحَقُّ', t: 'al-ḥaqqu', e: 'is the truth', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'وَعَرَفَ،', t: 'wa-ʿarafa', e: 'and ʿarafa (to know)' },
    NAHW, { g: ':' },
    { a: 'عَرَفْتُ', t: 'ʿaraftu', e: 'I knew' },
    { a: 'مُحَمَّدًا', t: 'Muḥammadan', e: 'Muḥammad' },
    { a: 'ﷺ', t: 'ṣallā-llāhu ʿalayhi wa-sallam', e: '(ﷺ)' },
    { a: 'نَبِيًّا', t: 'nabiyyan', e: 'to be a prophet' },
  ] },
  { t: 'line', w: [
    { a: 'وَدَرَى،', t: 'wa-darā', e: 'and darā (to know)' },
    NAHW, { g: ':' }, OPEN,
    { a: 'وَمَا', t: 'wa-mā', e: 'and not', q: 1 },
    { a: 'أَدْرِي', t: 'adrī', e: 'do I know', q: 1 },
    { a: 'مَا', t: 'mā', e: 'what', q: 1 },
    { a: 'يُفْعَلُ', t: 'yufʿalu', e: 'will be done', q: 1 },
    { a: 'بِي', t: 'bī', e: 'with me', q: 1 },
    { a: 'وَلَا', t: 'wa-lā', e: 'nor', q: 1 },
    { a: 'بِكُمْ', t: 'bikum', e: 'with you', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'وَتَعَلَّمْ،', t: 'wa-taʿallam', e: 'and taʿallam (= know for sure!)' },
    NAHW, { g: ':' },
    { a: 'تَعَلَّمْ', t: 'taʿallam', e: 'know!' },
    { a: 'شِفَاءَ', t: 'shifāʾa', e: 'that the cure of' },
    { a: 'النَّفْسِ', t: 'an-nafsi', e: 'the soul' },
    { a: 'قَهْرَ', t: 'qahra', e: 'is subduing' },
    { a: 'عَدُوِّهَا', t: 'ʿaduwwihā', e: 'its enemy' },
  ] },
  { t: 'line', w: [
    { a: 'الثَّانِي', t: 'ath-thānī', e: 'the second' },
    { a: 'مَا', t: 'mā', e: 'those that' },
    { a: 'تَدُلُّ', t: 'tadullu', e: 'denote' },
    { a: 'عَلَى', t: 'ʿalā', e: '' },
    { a: 'الظَّنِّ،', t: 'aẓ-ẓanni', e: 'preponderant opinion (ẓann)' },
    { a: 'وَيُسَمَّى', t: 'wa-yusammā', e: 'and are called' },
    { a: 'أَفْعَالَ', t: 'afʿāla', e: 'the verbs of' },
    { a: 'الرُّجْحَانِ،', t: 'ar-rujḥāni', e: 'probability (rujḥān)' },
    { a: 'وَهِيَ', t: 'wa-hiya', e: 'and they are' }, { g: ':' },
  ] },
  { t: 'line', w: [
    { a: 'ظَنَّ،', t: 'ẓanna', e: 'ẓanna (to think)' },
    NAHW, { g: ':' }, OPEN,
    { a: 'الَّذِينَ', t: 'alladhīna', e: 'those who', q: 1 },
    { a: 'يَظُنُّونَ', t: 'yaẓunnūna', e: 'think', q: 1 },
    { a: 'أَنَّهُمْ', t: 'annahum', e: 'that they', q: 1 },
    { a: 'مُلَاقُو', t: 'mulāqū', e: 'will meet', q: 1 },
    { a: 'رَبِّهِمْ', t: 'rabbihim', e: 'their Lord', q: 1 },
    { a: 'وَأَنَّهُمْ', t: 'wa-annahum', e: 'and that they', q: 1 },
    { a: 'إِلَيْهِ', t: 'ilayhi', e: 'to Him', q: 1 },
    { a: 'رَاجِعُونَ', t: 'rājiʿūna', e: 'will return', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'وَحَسِبَ،', t: 'wa-ḥasiba', e: 'and ḥasiba (to reckon)' },
    NAHW, { g: ':' }, OPEN,
    { a: 'وَيَحْسَبُونَ', t: 'wa-yaḥsabūna', e: 'and they reckon', q: 1 },
    { a: 'أَنَّهُمْ', t: 'annahum', e: 'that they', q: 1 },
    { a: 'مُهْتَدُونَ', t: 'muhtadūna', e: 'are guided', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'زَعَمَ،', t: 'zaʿama', e: 'zaʿama (to claim)' },
    NAHW, { g: ':' }, OPEN,
    { a: 'زَعَمَ', t: 'zaʿama', e: 'claimed', q: 1 },
    { a: 'الَّذِينَ', t: 'alladhīna', e: 'those who', q: 1 },
    { a: 'كَفَرُوا', t: 'kafarū', e: 'disbelieved', q: 1 },
    { a: 'أَنْ', t: 'an', e: 'that', q: 1 },
    { a: 'لَنْ', t: 'lan', e: 'never', q: 1 },
    { a: 'يُبْعَثُوا', t: 'yubʿathū', e: 'will they be raised', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'وَجَعَلَ،', t: 'wa-jaʿala', e: 'and jaʿala (to deem)' },
    NAHW, { g: ':' }, OPEN,
    { a: 'وَجَعَلُوا', t: 'wa-jaʿalū', e: 'and they made', q: 1 },
    { a: 'الْمَلَائِكَةَ', t: 'al-malāʾikata', e: 'the angels', q: 1 },
    { a: 'الَّذِينَ', t: 'alladhīna', e: 'who', q: 1 },
    { a: 'هُمْ', t: 'hum', e: 'are', q: 1 },
    { a: 'عِبَادُ', t: 'ʿibādu', e: 'servants of', q: 1 },
    { a: 'الرَّحْمَنِ', t: 'ar-raḥmāni', e: 'the Most Merciful', q: 1 },
    { a: 'إِنَاثًا', t: 'ināthan', e: 'females', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'وَحَجَا،', t: 'wa-ḥajā', e: 'and ḥajā (to suppose)' },
    { a: 'وَعَدَّ،', t: 'wa-ʿadda', e: 'and ʿadda (to count / deem)' },
    { a: 'وَوَهَبَ،', t: 'wa-wahaba', e: 'and wahaba (to suppose)' },
    { a: 'وَخَالَ', t: 'wa-khāla', e: 'and khāla (to imagine)' },
  ] },

  /* ── omitting the objects of heart-verbs ── */
  { t: 'page', n: '٢٦' },
  { t: 'box', label: 'حذف مفعولي أفعال القلوب', labelEn: 'Omitting both objects of heart-verbs', lines: [
    [
      { a: 'يَجُوزُ', t: 'yajūzu', e: 'permitted is' },
      { a: 'الِاخْتِصَارُ', t: 'al-ikhtiṣāru', e: 'abridging (dropping both)' },
      { a: 'فِي', t: 'fī', e: 'in' },
      { a: 'مَفْعُولَيْ', t: 'mafʿūlay', e: 'the two objects of' },
      { a: 'أَفْعَالِ', t: 'afʿāli', e: 'the verbs of' },
      { a: 'الْقُلُوبِ،', t: 'al-qulūbi', e: 'the heart' },
      { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
      { a: 'الْحَذْفُ', t: 'al-ḥadhfu', e: 'omission' },
      { a: 'بِدَلِيلٍ', t: 'bi-dalīlin', e: 'with an indicator' },
      { a: 'عَلَى', t: 'ʿalā', e: 'of' },
      { a: 'الْمَحْذُوفِ،', t: 'al-maḥdhūfi', e: 'the omitted' },
      NAHW, { g: ':' }, OPEN,
      { a: 'أَيْنَ', t: 'ayna', e: 'Where are', q: 1 },
      { a: 'شُرَكَائِيَ', t: 'shurakāʾiya', e: 'My partners', q: 1 },
      { a: 'الَّذِينَ', t: 'alladhīna', e: 'whom', q: 1 },
      { a: 'كُنْتُمْ', t: 'kuntum', e: 'you used to', q: 1 },
      { a: 'تَزْعُمُونَ', t: 'tazʿumūna', e: 'claim', q: 1 },
      CLOSE,
      { a: 'أَيْ', t: 'ay', e: 'i.e.' },
      { a: 'تَزْعُمُونَهُمْ', t: 'tazʿumūnahum', e: 'you claim them' },
      { a: 'شُرَكَائِي', t: 'shurakāʾī', e: 'My partners' },
    ],
    [
      { a: 'وَلَا', t: 'wa-lā', e: 'and not' },
      { a: 'يَجُوزُ', t: 'yajūzu', e: 'permitted' },
      { a: 'الِاقْتِصَارُ', t: 'al-iqtiṣāru', e: 'restricting (dropping one)' },
      { a: 'فِي', t: 'fī', e: 'in' },
      { a: 'حَذْفِ', t: 'ḥadhfi', e: 'omitting' },
      { a: 'أَحَدِ', t: 'aḥadi', e: 'one of' },
      { a: 'مَفْعُولَيْ', t: 'mafʿūlay', e: 'the two objects of' },
      { a: 'أَفْعَالِ', t: 'afʿāli', e: 'the verbs of' },
      { a: 'الْقُلُوبِ،', t: 'al-qulūbi', e: 'the heart' },
      { a: 'وَهُوَ', t: 'wa-huwa', e: 'which is' },
      { a: 'الْحَذْفُ', t: 'al-ḥadhfu', e: 'omission' },
      { a: 'بِغَيْرِ', t: 'bi-ghayri', e: 'without' },
      { a: 'دَلِيلٍ،', t: 'dalīlin', e: 'an indicator' },
      NAHW, { g: ':' },
      { a: 'ظَنَنْتُ', t: 'ẓanantu', e: '“I thought…” (alone)' },
    ],
  ] },

  /* ── transformation verbs ── */
  { t: 'page', n: '٢٧' },
  { t: 'box', label: 'أفعال التحويل', labelEn: 'The transformation verbs (afʿāl al-taḥwīl)', lines: [
    [
      { a: 'أَفْعَالُ', t: 'afʿālu', e: 'the verbs of' },
      { a: 'التَّحْوِيلِ', t: 'at-taḥwīli', e: 'transformation' },
      { a: 'مَا', t: 'mā', e: 'are those' },
      { a: 'تَكُونُ', t: 'takūnu', e: 'that carry' },
      { a: 'بِمَعْنَى', t: 'bi-maʿnā', e: 'the sense of' },
      { a: 'صَيَّرَ،', t: 'ṣayyara', e: 'ṣayyara (to render)' },
      { a: 'وَهِيَ', t: 'wa-hiya', e: 'and they are' }, { g: ':' },
    ],
    [
      { a: 'صَيَّرَ،', t: 'ṣayyara', e: 'ṣayyara (to render)' },
      NAHW, { g: ':' },
      { a: 'صَيَّرَ', t: 'ṣayyara', e: 'he turned' },
      { a: 'عَذْبَ', t: 'ʿadhba', e: 'the sweet of' },
      { a: 'الشَّرَابِ', t: 'ash-sharābi', e: 'drink' },
      { a: 'مُرًّا', t: 'murran', e: 'bitter' },
    ],
    [
      { a: 'وَرَدَّ،', t: 'wa-radda', e: 'and radda (to turn into)' },
      NAHW, { g: ':' }, OPEN,
      { a: 'وَدَّ', t: 'wadda', e: 'Wished', q: 1 },
      { a: 'كَثِيرٌ', t: 'kathīrun', e: 'many', q: 1 },
      { a: 'مِنْ', t: 'min', e: 'of', q: 1 },
      { a: 'أَهْلِ', t: 'ahli', e: 'the People of', q: 1 },
      { a: 'الْكِتَابِ', t: 'al-kitābi', e: 'the Book', q: 1 },
      { a: 'لَوْ', t: 'law', e: 'that', q: 1 },
      { a: 'يَرُدُّونَكُمْ', t: 'yaruddūnakum', e: 'they could turn you', q: 1 },
      { a: 'مِنْ', t: 'min', e: 'from', q: 1 },
      { a: 'بَعْدِ', t: 'baʿdi', e: 'after', q: 1 },
      { a: 'إِيمَانِكُمْ', t: 'īmānikum', e: 'your faith', q: 1 },
      { a: 'كُفَّارًا', t: 'kuffāran', e: 'into disbelievers', q: 1 },
      CLOSE,
    ],
    [
      { a: 'وَتَرَكَ،', t: 'wa-taraka', e: 'and taraka (to leave as)' },
      NAHW, { g: ':' }, OPEN,
      { a: 'فَتَرَكَهُ', t: 'fa-tarakahu', e: 'and left it', q: 1 },
      { a: 'صَلْدًا', t: 'ṣaldan', e: 'bare', q: 1 },
      CLOSE,
    ],
    [
      { a: 'وَتَخِذَ', t: 'wa-takhidha', e: 'and takhidha' },
      { a: 'وَاتَّخَذَ،', t: 'wa-ttakhadha', e: 'and ittakhadha (to take as)' },
      NAHW, { g: ':' }, OPEN,
      { a: 'وَاتَّخَذَ', t: 'wa-ttakhadha', e: 'and Allah took', q: 1 },
      { a: 'اللهُ', t: 'Allāhu', e: 'Allah', q: 1 },
      { a: 'إِبْرَاهِيمَ', t: 'ibrāhīma', e: 'Ibrāhīm', q: 1 },
      { a: 'خَلِيلًا', t: 'khalīlan', e: 'as an intimate friend', q: 1 },
      CLOSE,
    ],
    [
      { a: 'وَجَعَلَ،', t: 'wa-jaʿala', e: 'and jaʿala (to render)' },
      NAHW, { g: ':' }, OPEN,
      { a: 'فَجَعَلْنَاهُ', t: 'fa-jaʿalnāhu', e: 'and We made it', q: 1 },
      { a: 'هَبَاءً', t: 'habāʾan', e: 'dust', q: 1 },
      { a: 'مَنْثُورًا', t: 'manthūran', e: 'scattered', q: 1 },
      CLOSE,
    ],
    [
      { a: 'وَوَهَبَ،', t: 'wa-wahaba', e: 'and wahaba (to make)' },
      NAHW, { g: ':' },
      { a: 'وَهَبَنِيَ', t: 'wahabaniya', e: 'may He make me' },
      { a: 'اللهُ', t: 'Allāhu', e: 'Allah' },
      { a: 'فِدَاءً', t: 'fidāʾan', e: 'a ransom' },
      { a: 'لِلْعِلْمِ', t: 'lil-ʿilmi', e: 'for knowledge' },
    ],
  ] },

  /* ── transitive to three objects ── */
  { t: 'h2', c: 'green', ar: 'الضَّرْبُ الثَّالِثُ: الْمُتَعَدِّي إِلَى ثَلَاثَةِ مَفَاعِيلَ', en: 'Third kind — transitive to three objects' },
  { t: 'line', w: [
    { a: 'وَلَا', t: 'wa-lā', e: 'and it is not' },
    { a: 'يَكُونُ', t: 'yakūnu', e: '' },
    { a: 'إِلَّا', t: 'illā', e: 'except' },
    { a: 'فِعْلَ', t: 'fiʿla', e: 'a verb of' },
    { a: 'قَلْبٍ،', t: 'qalbin', e: 'the heart' },
    { a: 'وَالْمَفْعُولُ', t: 'wal-mafʿūlu', e: 'and the object' },
    { a: 'الثَّانِي', t: 'ath-thānī', e: 'second' },
    { a: 'وَالثَّالِثُ', t: 'wath-thālithu', e: 'and third' },
    { a: 'يَكُونَانِ', t: 'yakūnāni', e: '(both) were' },
    { a: 'مُبْتَدَأً', t: 'mubtadaʾan', e: 'subject' },
    { a: 'وَخَبَرًا', t: 'wa-khabaran', e: 'and predicate' },
    { a: 'فِي', t: 'fī', e: 'in' },
    { a: 'الْأَصْلِ،', t: 'al-aṣli', e: 'origin' },
    NAHW, { g: ':' }, OPEN,
    { a: 'كَذَلِكَ', t: 'kadhālika', e: 'thus', q: 1 },
    { a: 'يُرِيهِمُ', t: 'yurīhimu', e: 'will show them', q: 1 },
    { a: 'اللهُ', t: 'Allāhu', e: 'Allah', q: 1 },
    { a: 'أَعْمَالَهُمْ', t: 'aʿmālahum', e: 'their deeds', q: 1 },
    { a: 'حَسَرَاتٍ', t: 'ḥasarātin', e: 'as regrets', q: 1 },
    { a: 'عَلَيْهِمْ', t: 'ʿalayhim', e: 'upon them', q: 1 },
    CLOSE,
  ] },

  { t: 'h2', c: 'plain', ar: 'مَا يَسُدُّ مَسَدَّ الْمَفْعُولَيْنِ', en: 'What stands in for the two objects' },
  { t: 'line', w: [
    { a: 'قَدْ', t: 'qad', e: 'sometimes' },
    { a: 'يَسُدُّ', t: 'yasuddu', e: 'fills' },
    { a: 'مَسَدَّ', t: 'masadda', e: 'the place of' },
    { a: 'مَفْعُولَيْ', t: 'mafʿūlay', e: 'the two objects of' },
    { a: 'أَفْعَالِ', t: 'afʿāli', e: 'the verbs of' },
    { a: 'الْقُلُوبِ', t: 'al-qulūbi', e: 'the heart' }, { g: ':' },
  ] },
  { t: 'line', w: [
    { a: 'الِاسْمُ', t: 'al-ismu', e: 'the noun' },
    { a: 'الْمُؤَوَّلُ،', t: 'al-muʾawwalu', e: 'interpreted (an + clause)' },
    NAHW, { g: ':' }, OPEN,
    { a: 'وَاعْلَمُوا', t: 'wa-ʿlamū', e: 'and know', q: 1 },
    { a: 'أَنَّ', t: 'anna', e: 'that', q: 1 },
    { a: 'اللهَ', t: 'Allāha', e: 'Allah', q: 1 },
    { a: 'مَعَ', t: 'maʿa', e: 'is with', q: 1 },
    { a: 'الْمُتَّقِينَ', t: 'al-muttaqīna', e: 'the God-conscious', q: 1 },
    CLOSE,
  ] },
  { t: 'page', n: '٢٨' },
  { t: 'line', w: [
    { a: 'أَوِ', t: 'awi', e: 'or' },
    { a: 'الْجُمْلَةُ،', t: 'al-jumlatu', e: 'the sentence' },
    NAHW, { g: ':' }, OPEN,
    { a: 'وَاللهُ', t: 'wallāhu', e: 'and Allah', q: 1 },
    { a: 'يَشْهَدُ', t: 'yashhadu', e: 'bears witness', q: 1 },
    { a: 'إِنَّ', t: 'inna', e: 'that', q: 1 },
    { a: 'الْمُنَافِقِينَ', t: 'al-munāfiqīna', e: 'the hypocrites', q: 1 },
    { a: 'لَكَاذِبُونَ', t: 'la-kādhibūna', e: 'are surely liars', q: 1 },
    CLOSE,
  ] },

  { t: 'h2', c: 'plain', ar: 'التَّعْلِيقُ', en: 'Suspension of governance (taʿlīq)' },
  { t: 'line', w: [
    { a: 'إِذَا', t: 'idhā', e: 'when' },
    { a: 'سَدَّتِ', t: 'saddati', e: 'fills' },
    { a: 'الْجُمْلَةُ', t: 'al-jumlatu', e: 'a sentence' },
    { a: 'مَسَدَّ', t: 'masadda', e: 'the place of' },
    { a: 'مَفْعُولَيْ', t: 'mafʿūlay', e: 'the two objects of' },
    { a: 'فِعْلِ', t: 'fiʿli', e: 'a verb of' },
    { a: 'الْقَلْبِ', t: 'al-qalbi', e: 'the heart' },
    { a: 'لَمْ', t: 'lam', e: 'it does not' },
    { a: 'يَعْمَلْ', t: 'yaʿmal', e: 'govern' },
    { a: 'فِيهَا', t: 'fīhā', e: 'in it' },
    { a: 'لَفْظًا', t: 'lafẓan', e: 'in form' },
    { a: 'بَلْ', t: 'bal', e: 'but rather' },
    { a: 'مَحَلًّا،', t: 'maḥallan', e: 'in position' },
    { a: 'وَيُسَمَّى', t: 'wa-yusammā', e: 'and this is called' },
    { a: 'ذَلِكَ', t: 'dhālika', e: '' },
    { a: 'تَعْلِيقًا', t: 'taʿlīqan', e: 'suspension (taʿlīq)' },
  ] },
  { t: 'line', w: [
    { a: 'يُعَلَّقُ', t: 'yuʿallaqu', e: 'is suspended' },
    { a: 'عَمَلُ', t: 'ʿamalu', e: 'the governance of' },
    { a: 'فِعْلِ', t: 'fiʿli', e: 'a verb of' },
    { a: 'الْقَلْبِ', t: 'al-qalbi', e: 'the heart' },
    { a: 'عَنِ', t: 'ʿani', e: 'over' },
    { a: 'الْجُمْلَةِ', t: 'al-jumlati', e: 'the clause' },
    { a: 'بَعْدَهُ', t: 'baʿdahu', e: 'after it' },
    { a: 'إِنْ', t: 'in', e: 'if' },
    { a: 'صُدِّرَتْ', t: 'ṣuddirat', e: 'it begins' },
    { a: 'بِمَا', t: 'bi-mā', e: 'with what' },
    { a: 'لَهُ', t: 'lahu', e: 'has' },
    { a: 'صَدْرُ', t: 'ṣadru', e: 'the lead of' },
    { a: 'الْكَلَامِ،', t: 'al-kalāmi', e: 'speech (clause-initial right)' },
    { a: 'مِثْلُ', t: 'mithlu', e: 'such as' }, { g: ':' },
  ] },
  { t: 'line', w: [
    { a: 'إِنِ', t: 'ini', e: '“in”' },
    { a: 'النَّافِيَةِ،', t: 'an-nāfiyati', e: 'the negating' },
    NAHW, { g: ':' }, OPEN,
    { a: 'وَتَظُنُّونَ', t: 'wa-taẓunnūna', e: 'and you think', q: 1 },
    { a: 'إِنْ', t: 'in', e: 'that not', q: 1 },
    { a: 'لَبِثْتُمْ', t: 'labithtum', e: 'you stayed', q: 1 },
    { a: 'إِلَّا', t: 'illā', e: 'except', q: 1 },
    { a: 'قَلِيلًا', t: 'qalīlan', e: 'a little', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'وَمَا', t: 'wa-mā', e: 'and “mā”' },
    { a: 'النَّافِيَةِ،', t: 'an-nāfiyati', e: 'the negating' },
    NAHW, { g: ':' }, OPEN,
    { a: 'لَقَدْ', t: 'laqad', e: 'certainly', q: 1 },
    { a: 'عَلِمْتَ', t: 'ʿalimta', e: 'you have known', q: 1 },
    { a: 'مَا', t: 'mā', e: 'none', q: 1 },
    { a: 'أَنْزَلَ', t: 'anzala', e: 'sent down', q: 1 },
    { a: 'هَؤُلَاءِ', t: 'hāʾulāʾi', e: 'these', q: 1 },
    { a: 'إِلَّا', t: 'illā', e: 'except', q: 1 },
    { a: 'رَبُّ', t: 'rabbu', e: 'the Lord of', q: 1 },
    { a: 'السَّمَاوَاتِ', t: 'as-samāwāti', e: 'the heavens', q: 1 },
    { a: 'وَالْأَرْضِ', t: 'wal-arḍi', e: 'and the earth', q: 1 },
    { a: 'بَصَائِرَ', t: 'baṣāʾira', e: 'as clear proofs', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'وَلَامِ', t: 'wa-lāmi', e: 'and the lām of' },
    { a: 'الِابْتِدَاءِ،', t: 'al-ibtidāʾi', e: 'inception' },
    NAHW, { g: ':' }, OPEN,
    { a: 'وَلَقَدْ', t: 'wa-laqad', e: 'and certainly', q: 1 },
    { a: 'عَلِمُوا', t: 'ʿalimū', e: 'they knew', q: 1 },
    { a: 'لَمَنِ', t: 'la-mani', e: 'that whoever', q: 1 },
    { a: 'اشْتَرَاهُ', t: 'ishtarāhu', e: 'buys it', q: 1 },
    { a: 'مَا', t: 'mā', e: 'has no', q: 1 },
    { a: 'لَهُ', t: 'lahu', e: 'for him', q: 1 },
    { a: 'فِي', t: 'fī', e: 'in', q: 1 },
    { a: 'الْآخِرَةِ', t: 'al-ākhirati', e: 'the Hereafter', q: 1 },
    { a: 'مِنْ', t: 'min', e: 'any', q: 1 },
    { a: 'خَلَاقٍ', t: 'khalāqin', e: 'share', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'وَلَعَلَّ،', t: 'wa-laʿalla', e: 'and “laʿalla”' },
    NAHW, { g: ':' }, OPEN,
    { a: 'وَمَا', t: 'wa-mā', e: 'and not', q: 1 },
    { a: 'أَدْرِي', t: 'adrī', e: 'do I know', q: 1 },
    { a: 'لَعَلَّهُ', t: 'laʿallahu', e: 'perhaps it is', q: 1 },
    { a: 'فِتْنَةٌ', t: 'fitnatun', e: 'a trial', q: 1 },
    { a: 'لَكُمْ', t: 'lakum', e: 'for you', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'وَالِاسْتِفْهَامِ،', t: 'wal-istifhāmi', e: 'and the interrogative' },
    NAHW, { g: ':' }, OPEN,
    { a: 'وَسَيَعْلَمُ', t: 'wa-sa-yaʿlamu', e: 'and will know', q: 1 },
    { a: 'الَّذِينَ', t: 'alladhīna', e: 'those who', q: 1 },
    { a: 'ظَلَمُوا', t: 'ẓalamū', e: 'did wrong', q: 1 },
    { a: 'أَيَّ', t: 'ayya', e: 'to what', q: 1 },
    { a: 'مُنْقَلَبٍ', t: 'munqalabin', e: 'a return', q: 1 },
    { a: 'يَنْقَلِبُونَ', t: 'yanqalibūna', e: 'they will return', q: 1 },
    CLOSE,
  ] },

  { t: 'page', n: '٢٩' },
  { t: 'line', w: [
    { a: 'وَلَامِ', t: 'wa-lāmi', e: 'and the lām of' },
    { a: 'جَوَابِ', t: 'jawābi', e: 'the answer of' },
    { a: 'الْقَسَمِ،', t: 'al-qasami', e: 'the oath' },
    NAHW, { g: ':' },
    { a: 'وَلَقَدْ', t: 'wa-laqad', e: 'and I surely' },
    { a: 'عَلِمْتُ', t: 'ʿalimtu', e: 'know' },
    { a: 'لَتَأْتِيَنَّ', t: 'la-taʾtiyanna', e: 'that there shall surely come' },
    { a: 'مَنِيَّتِي', t: 'maniyyatī', e: 'my death' },
    { a: 'إِنَّ', t: 'inna', e: 'indeed' },
    { a: 'الْمَنَايَا', t: 'al-manāyā', e: 'the [arrows of] fate' },
    { a: 'لَا', t: 'lā', e: 'do not' },
    { a: 'تَطِيشُ', t: 'taṭīshu', e: 'miss' },
    { a: 'سِهَامُهَا', t: 'sihāmuhā', e: 'their mark' },
  ] },

  { t: 'h2', c: 'plain', ar: 'الْإِلْغَاءُ', en: 'Cancellation of governance (ilghāʾ)' },
  { t: 'line', w: [
    { a: 'الْإِلْغَاءُ', t: 'al-ilghāʾu', e: 'cancellation (ilghāʾ)' },
    { a: 'إِبْطَالُ', t: 'ibṭālu', e: 'is the nullifying of' },
    { a: 'عَمَلِ', t: 'ʿamali', e: 'the governance of' },
    { a: 'فِعْلِ', t: 'fiʿli', e: 'a verb of' },
    { a: 'الْقَلْبِ', t: 'al-qalbi', e: 'the heart' },
    { a: 'اللَّفْظِيِّ', t: 'al-lafẓiyyi', e: 'in form' },
    { a: 'وَالْمَحَلِّيِّ', t: 'wal-maḥalliyyi', e: 'and in position' },
  ] },
  { t: 'line', w: [
    { a: 'يَتَرَجَّحُ', t: 'yatarajjaḥu', e: 'preferred is' },
    { a: 'إِعْمَالُ', t: 'iʿmālu', e: 'applying the governance of' },
    { a: 'فِعْلِ', t: 'fiʿli', e: 'a verb of' },
    { a: 'الْقَلْبِ', t: 'al-qalbi', e: 'the heart' },
    { a: 'إِذَا', t: 'idhā', e: 'when' },
    { a: 'تَوَسَّطَ', t: 'tawassaṭa', e: 'it comes between' },
    { a: 'بَيْنَ', t: 'bayna', e: '' },
    { a: 'مَفْعُولَيْهِ،', t: 'mafʿūlayhi', e: 'its two objects' },
    NAHW, { g: ':' },
    { a: 'مُحَمَّدًا', t: 'Muḥammadan', e: '“Muḥammad' },
    { a: 'عَلِمْتُ', t: 'ʿalimtu', e: 'I knew' },
    { a: 'صَادِقًا', t: 'ṣādiqan', e: 'truthful”' },
  ] },
  { t: 'line', w: [
    { a: 'وَيَتَرَجَّحُ', t: 'wa-yatarajjaḥu', e: 'and preferred is' },
    { a: 'إِلْغَاؤُهُ', t: 'ilghāʾuhu', e: 'cancelling it' },
    { a: 'إِذَا', t: 'idhā', e: 'when' },
    { a: 'تَأَخَّرَ', t: 'taʾakhkhara', e: 'it comes after' },
    { a: 'عَنْ', t: 'ʿan', e: '' },
    { a: 'مَعْمُولَيْهِ،', t: 'maʿmūlayhi', e: 'its two governed terms' },
    NAHW, { g: ':' },
    { a: 'مُحَمَّدٌ', t: 'Muḥammadun', e: '“Muḥammad' },
    { a: 'صَادِقٌ', t: 'ṣādiqun', e: 'is truthful' },
    { a: 'عَلِمْتُ', t: 'ʿalimtu', e: 'I knew”' },
  ] },

  /* ── Type 2: the heard (samāʿī) verb ── */
  { t: 'h2', c: 'green', ar: 'النَّوْعُ الثَّانِي: السَّمَاعِيُّ', en: 'Second type — the heard verb (al-samāʿī)' },
  { t: 'box', label: 'معنى السماعي', labelEn: 'Meaning of samāʿī', lines: [
    [
      { a: 'السَّمَاعِيُّ', t: 'al-samāʿiyyu', e: 'the heard (samāʿī)' },
      { a: 'مَا', t: 'mā', e: 'is what' },
      { a: 'لَيْسَ', t: 'laysa', e: 'has not' },
      { a: 'لَهُ', t: 'lahu', e: 'for it' },
      { a: 'قَاعِدَةٌ', t: 'qāʿidatun', e: 'a rule' },
      { a: 'مُطَّرِدَةٌ،', t: 'muṭṭaridatun', e: 'consistent' },
      { a: 'بَلْ', t: 'bal', e: 'rather' },
      { a: 'يَتَوَقَّفُ', t: 'yatawaqqafu', e: 'it depends' },
      { a: 'عَلَى', t: 'ʿalā', e: 'on' },
      { a: 'السَّمَاعِ', t: 'as-samāʿi', e: 'what is heard (from the Arabs)' },
    ],
  ] },
  { t: 'line', w: [
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
    { a: 'ثَلَاثَةُ', t: 'thalāthatu', e: 'three' },
    { a: 'أَقْسَامٍ', t: 'aqsāmin', e: 'divisions' }, { g: ':' },
  ] },

  { t: 'h2', c: 'blue', ar: 'الْقِسْمُ الْأَوَّلُ: الْأَفْعَالُ النَّاقِصَةُ', en: 'First division — the defective verbs (kāna & its sisters)' },
  { t: 'line', w: [
    { a: 'وَهِيَ', t: 'wa-hiya', e: 'and they are' },
    { a: 'أَفْعَالٌ', t: 'afʿālun', e: 'verbs' },
    { a: 'تَدْخُلُ', t: 'tadkhulu', e: 'that enter' },
    { a: 'عَلَى', t: 'ʿalā', e: 'upon' },
    { a: 'الْمُبْتَدَأِ', t: 'al-mubtadaʾi', e: 'the subject' },
    { a: 'وَالْخَبَرِ،', t: 'wal-khabari', e: 'and the predicate' },
    { a: 'وَتَرْفَعُ', t: 'wa-tarfaʿu', e: 'and raise' },
    { a: 'الْأَوَّلَ', t: 'al-awwala', e: 'the first' },
    { a: 'وَيُسَمَّى', t: 'wa-yusammā', e: 'called' },
    { a: 'اسْمَهَا،', t: 'ismahā', e: 'their noun (ism)' },
    { a: 'وَتَنْصِبُ', t: 'wa-tanṣibu', e: 'and put in the accusative' },
    { a: 'الثَّانِيَ', t: 'ath-thāniya', e: 'the second' },
    { a: 'وَيُسَمَّى', t: 'wa-yusammā', e: 'called' },
    { a: 'خَبَرَهَا', t: 'khabarahā', e: 'their predicate (khabar)' },
  ] },
  { t: 'line', w: [
    { a: 'وَهِيَ', t: 'wa-hiya', e: 'and they are' },
    { a: 'أَرْبَعَةُ', t: 'arbaʿatu', e: 'four' },
    { a: 'أَضْرُبٍ', t: 'aḍrubin', e: 'kinds' }, { g: ':' },
  ] },

  { t: 'h2', c: 'green', ar: 'الضَّرْبُ الْأَوَّلُ: كَانَ وَأَخَوَاتُهَا', en: 'First kind — kāna and its sisters' },
  { t: 'line', w: [
    { a: 'وَهِيَ', t: 'wa-hiya', e: 'and they are' },
    { a: 'ثَلَاثَةَ', t: 'thalāthata', e: 'thir-' },
    { a: 'عَشَرَ', t: 'ʿashara', e: '-teen' }, { g: ':' },
  ] },
  { t: 'line', w: [
    { a: 'الْأَوَّلُ', t: 'al-awwalu', e: 'the first' },
    { a: 'كَانَ،', t: 'kāna', e: 'kāna (to be / was)' },
  ] },

  { t: 'page', n: '٣٠' },
  { t: 'box', label: 'معاني كان', labelEn: 'The meanings of kāna', lines: [
    [
      { a: 'يَدُلُّ', t: 'yadullu', e: 'kāna denotes' },
      { a: 'كَانَ', t: 'kāna', e: '' },
      { a: 'عَلَى', t: 'ʿalā', e: '' },
      ELL,
    ],
    [
      { a: 'الْمَاضِي', t: 'al-māḍī', e: 'the completed past' },
      { a: 'الْمُنْقَطِعِ', t: 'al-munqaṭiʿi', e: '(no longer continuing)' },
      { a: 'عَلَى', t: 'ʿalā', e: 'in the' },
      { a: 'وَجْهِ', t: 'wajhi', e: 'manner of' },
      { a: 'الثُّبُوتِ،', t: 'ath-thubūti', e: 'fixedness' },
      NAHW, { g: ':' }, OPEN,
      { a: 'وَكَانُوا', t: 'wa-kānū', e: 'and they were', q: 1 },
      { a: 'عَلَيْهِ', t: 'ʿalayhi', e: 'over it', q: 1 },
      { a: 'شُهَدَاءَ', t: 'shuhadāʾa', e: 'witnesses', q: 1 },
      CLOSE,
    ],
    [
      { a: 'أَوْ', t: 'aw', e: 'or' },
      { a: 'عَلَى', t: 'ʿalā', e: 'in the' },
      { a: 'وَجْهِ', t: 'wajhi', e: 'manner of' },
      { a: 'الْحُدُوثِ،', t: 'al-ḥudūthi', e: 'occurrence' },
      NAHW, { g: ':' }, OPEN,
      { a: 'وَلَقَدْ', t: 'wa-laqad', e: 'and certainly', q: 1 },
      { a: 'كَانُوا', t: 'kānū', e: 'they had', q: 1 },
      { a: 'عَاهَدُوا', t: 'ʿāhadū', e: 'pledged to', q: 1 },
      { a: 'اللهَ', t: 'Allāha', e: 'Allah', q: 1 },
      { a: 'مِنْ', t: 'min', e: '', q: 1 },
      { a: 'قَبْلُ', t: 'qablu', e: 'before', q: 1 },
      CLOSE,
    ],
    [
      { a: 'وَالْمَاضِي', t: 'wal-māḍī', e: 'and the recurring past' },
      { a: 'الْمُتَجَدِّدِ', t: 'al-mutajaddidi', e: '(repeated)' },
      { a: 'عَلَى', t: 'ʿalā', e: 'in the' },
      { a: 'وَجْهِ', t: 'wajhi', e: 'manner of' },
      { a: 'الِاسْتِمْرَارِ،', t: 'al-istimrāri', e: 'continuity' },
      NAHW, { g: ':' },
      { a: 'كُنْتُ', t: 'kuntu', e: 'I used to' },
      { a: 'أَذْهَبُ', t: 'adhhabu', e: 'go' },
      { a: 'يَوْمًا', t: 'yawman', e: 'daily' },
    ],
    [
      { a: 'أَوْ', t: 'aw', e: 'or' },
      { a: 'عَلَى', t: 'ʿalā', e: 'in the' },
      { a: 'وَجْهِ', t: 'wajhi', e: 'manner of' },
      { a: 'الْعَادَةِ،', t: 'al-ʿādati', e: 'habit' },
      NAHW, { g: ':' }, OPEN,
      { a: 'كَانَا', t: 'kānā', e: 'they both used to', q: 1 },
      { a: 'يَأْكُلَانِ', t: 'yaʾkulāni', e: 'eat', q: 1 },
      { a: 'الطَّعَامَ', t: 'aṭ-ṭaʿāma', e: 'food', q: 1 },
      CLOSE,
    ],
    [
      { a: 'وَالْحَالِ', t: 'wal-ḥāli', e: 'and the present' },
      { a: 'بِمَعْنَى', t: 'bi-maʿnā', e: 'in the sense of' },
      { a: 'مَا', t: 'mā', e: '“mā' },
      { a: 'زَالَ،', t: 'zāla', e: 'zāla” (still is)' },
      NAHW, { g: ':' }, OPEN,
      { a: 'وَكَانَ', t: 'wa-kāna', e: 'and is', q: 1 },
      { a: 'الْإِنْسَانُ', t: 'al-insānu', e: 'man', q: 1 },
      { a: 'عَجُولًا', t: 'ʿajūlan', e: 'ever hasty', q: 1 },
      CLOSE,
    ],
    [
      { a: 'وَالِاسْتِقْبَالِ،', t: 'wal-istiqbāli', e: 'and the future' },
      NAHW, { g: ':' }, OPEN,
      { a: 'كَانَتْ', t: 'kānat', e: 'will be', q: 1 },
      { a: 'لَهُمْ', t: 'lahum', e: 'for them', q: 1 },
      { a: 'جَنَّاتُ', t: 'jannātu', e: 'the Gardens of', q: 1 },
      { a: 'الْفِرْدَوْسِ', t: 'al-firdawsi', e: 'Paradise', q: 1 },
      { a: 'نُزُلًا', t: 'nuzulan', e: 'as a lodging', q: 1 },
      CLOSE,
    ],
    [
      { a: 'وَقَدْ', t: 'wa-qad', e: 'and it may' },
      { a: 'يَدُلُّ', t: 'yadullu', e: 'denote' },
      { a: 'عَلَى', t: 'ʿalā', e: '' },
      { a: 'مَعْنَى', t: 'maʿnā', e: 'the sense of' },
      { a: 'الِانْتِفَاءِ،', t: 'al-intifāʾi', e: 'negation' },
      NAHW, { g: ':' }, OPEN,
      { a: 'مَا', t: 'mā', e: 'it is not', q: 1 },
      { a: 'كَانَ', t: 'kāna', e: '', q: 1 },
      { a: 'لَنَا', t: 'lanā', e: 'for us', q: 1 },
      { a: 'أَنْ', t: 'an', e: 'to', q: 1 },
      { a: 'نُشْرِكَ', t: 'nushrika', e: 'associate', q: 1 },
      { a: 'بِاللهِ', t: 'bi-llāhi', e: 'with Allah', q: 1 },
      { a: 'مِنْ', t: 'min', e: '', q: 1 },
      { a: 'شَيْءٍ', t: 'shayʾin', e: 'anything', q: 1 },
      CLOSE,
    ],
    [
      { a: 'وَمَعْنَى', t: 'wa-maʿnā', e: 'and the sense of' },
      { a: 'الْقُدْرَةِ،', t: 'al-qudrati', e: 'capability' },
      NAHW, { g: ':' }, OPEN,
      { a: 'وَمَا', t: 'wa-mā', e: 'and it is not', q: 1 },
      { a: 'كَانَ', t: 'kāna', e: '', q: 1 },
      { a: 'لِنَفْسٍ', t: 'li-nafsin', e: 'for any soul', q: 1 },
      { a: 'أَنْ', t: 'an', e: 'to', q: 1 },
      { a: 'تَمُوتَ', t: 'tamūta', e: 'die', q: 1 },
      { a: 'إِلَّا', t: 'illā', e: 'except', q: 1 },
      { a: 'بِإِذْنِ', t: 'bi-idhni', e: 'by the leave of', q: 1 },
      { a: 'اللهِ', t: 'Allāhi', e: 'Allah', q: 1 },
      CLOSE,
    ],
  ] },
  { t: 'box', label: 'حذف نون كان', labelEn: 'Dropping the nūn of kāna', lines: [
    [
      { a: 'يَجُوزُ', t: 'yajūzu', e: 'permitted is' },
      { a: 'حَذْفُ', t: 'ḥadhfu', e: 'dropping' },
      { a: 'نُونِ', t: 'nūni', e: 'the nūn of' },
      { a: 'يَكُونُ', t: 'yakūnu', e: 'yakūn,' },
      { a: 'وَتَكُونُ', t: 'wa-takūnu', e: 'takūn,' },
      { a: 'وَأَكُونُ', t: 'wa-akūnu', e: 'akūn,' },
      { a: 'وَتَكُونِ', t: 'wa-takūni', e: 'takūnī' },
      { a: 'إِذَا', t: 'idhā', e: 'when' },
      { a: 'كَانَتْ', t: 'kānat', e: 'it is' },
      { a: 'مَجْزُومَةً،', t: 'majzūmatan', e: 'jussive (majzūm)' },
      { a: 'وَلَيْسَ', t: 'wa-laysa', e: 'and there is not' },
      { a: 'بَعْدَهَا', t: 'baʿdahā', e: 'after it' },
      { a: 'سَاكِنٌ', t: 'sākinun', e: 'a vowelless letter' },
      { a: 'وَلَا', t: 'wa-lā', e: 'nor' },
      { a: 'ضَمِيرُ', t: 'ḍamīru', e: 'a pronoun of' },
      { a: 'نَصْبٍ', t: 'naṣbin', e: 'the accusative' },
      { a: 'مُتَّصِلٌ،', t: 'muttaṣilun', e: 'attached' },
      NAHW, { g: ':' }, OPEN,
      { a: 'لَمْ', t: 'lam', e: 'he was not', q: 1 },
      { a: 'تَكُ', t: 'taku', e: '', q: 1 },
      { a: 'مِنَ', t: 'mina', e: 'among', q: 1 },
      { a: 'الْمُصَلِّينَ', t: 'al-muṣallīna', e: 'those who prayed', q: 1 },
      CLOSE,
      { a: 'بِخِلَافِ', t: 'bi-khilāfi', e: 'unlike' }, OPEN,
      { a: 'لَمْ', t: 'lam', e: 'were not', q: 1 },
      { a: 'يَكُنِ', t: 'yakuni', e: '', q: 1 },
      { a: 'الَّذِينَ', t: 'alladhīna', e: 'those who', q: 1 },
      { a: 'كَفَرُوا', t: 'kafarū', e: 'disbelieved', q: 1 },
      CLOSE,
      { a: 'وَلَمْ', t: 'wa-lam', e: 'and “lam' },
      { a: 'أَكُنْ', t: 'akun', e: 'akun”' },
    ],
  ] },

  /* ── dropping kāna; sisters 2–7 ── */
  { t: 'page', n: '٣١' },
  { t: 'box', label: 'حذف كان', labelEn: 'When kāna may be dropped', lines: [
    [
      { a: 'قَدْ', t: 'qad', e: 'sometimes' },
      { a: 'يُحْذَفُ', t: 'yuḥdhafu', e: 'is dropped' },
      { a: 'كَانَ', t: 'kāna', e: 'kāna' },
      { a: 'مَعَ', t: 'maʿa', e: 'with' },
      { a: 'اسْمِهَا', t: 'ismihā', e: 'its noun' },
      { a: 'بَعْدَ', t: 'baʿda', e: 'after' },
      { a: 'إِنْ', t: 'in', e: 'in' },
      { a: 'وَلَوْ', t: 'wa-law', e: 'and law' },
      { a: 'الشَّرْطِيَّتَيْنِ،', t: 'ash-sharṭiyyatayni', e: 'the two conditionals' },
      NAHW, { g: ':' },
      { a: 'الْتَمِسْ', t: 'iltamis', e: 'seek' },
      { a: 'وَلَوْ', t: 'wa-law', e: 'even if' },
      { a: 'خَاتَمًا', t: 'khātaman', e: 'a ring' },
      { a: 'مِنْ', t: 'min', e: 'of' },
      { a: 'حَدِيدٍ', t: 'ḥadīdin', e: 'iron' },
    ],
    [
      { a: 'وَقَدْ', t: 'wa-qad', e: 'and it may' },
      { a: 'يُحْذَفُ', t: 'yuḥdhafu', e: 'be dropped' },
      { a: 'كَانَ', t: 'kāna', e: 'kāna' },
      { a: 'فِي', t: 'fī', e: 'in' },
      { a: 'غَيْرِهِ،', t: 'ghayrihi', e: 'other cases' },
      NAHW, { g: ':' }, OPEN,
      { a: 'فَآمِنُوا', t: 'fa-āminū', e: 'so believe —', q: 1 },
      { a: 'خَيْرًا', t: 'khayran', e: 'better', q: 1 },
      { a: 'لَكُمْ', t: 'lakum', e: 'for you', q: 1 },
      CLOSE,
    ],
  ] },
  { t: 'line', w: [
    { a: 'الثَّانِي', t: 'ath-thānī', e: 'the second' },
    { a: 'أَصْبَحَ،', t: 'aṣbaḥa', e: 'aṣbaḥa (to be in the morning)' },
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
    { a: 'لِاتِّصَافِ', t: 'li-ttiṣāfi', e: 'for the qualifying of' },
    { a: 'الِاسْمِ', t: 'al-ismi', e: 'the noun' },
    { a: 'بِالْخَبَرِ', t: 'bil-khabari', e: 'by the predicate' },
    { a: 'وَقْتَ', t: 'waqta', e: 'at the time of' },
    { a: 'الصَّبَاحِ،', t: 'aṣ-ṣabāḥi', e: 'morning' },
    NAHW, { g: ':' }, OPEN,
    { a: 'فَأَصْبَحَ', t: 'fa-aṣbaḥa', e: 'and he became', q: 1 },
    { a: 'فِي', t: 'fī', e: 'in', q: 1 },
    { a: 'الْمَدِينَةِ', t: 'al-madīnati', e: 'the city', q: 1 },
    { a: 'خَائِفًا', t: 'khāʾifan', e: 'fearful', q: 1 },
    { a: 'يَتَرَقَّبُ', t: 'yataraqqabu', e: 'and watchful', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'الثَّالِثُ', t: 'ath-thālithu', e: 'the third' },
    { a: 'أَضْحَى،', t: 'aḍḥā', e: 'aḍḥā (to be in the forenoon)' },
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
    { a: 'لِاتِّصَافِ', t: 'li-ttiṣāfi', e: 'for the qualifying' },
    { a: 'الِاسْمِ', t: 'al-ismi', e: 'of the noun' },
    { a: 'بِالْخَبَرِ', t: 'bil-khabari', e: 'by the predicate' },
    { a: 'وَقْتَ', t: 'waqta', e: 'at' },
    { a: 'الضُّحَى،', t: 'aḍ-ḍuḥā', e: 'forenoon' },
    NAHW, { g: ':' },
    { a: 'أَضْحَى', t: 'aḍḥā', e: 'became' },
    { a: 'الرَّجُلُ', t: 'ar-rajulu', e: 'the man' },
    { a: 'عَامِلًا', t: 'ʿāmilan', e: 'working' },
  ] },
  { t: 'line', w: [
    { a: 'الرَّابِعُ', t: 'ar-rābiʿu', e: 'the fourth' },
    { a: 'أَمْسَى،', t: 'amsā', e: 'amsā (to be in the evening)' },
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
    { a: 'لِاتِّصَافِ', t: 'li-ttiṣāfi', e: 'for the qualifying' },
    { a: 'الِاسْمِ', t: 'al-ismi', e: 'of the noun' },
    { a: 'بِالْخَبَرِ', t: 'bil-khabari', e: 'by the predicate' },
    { a: 'وَقْتَ', t: 'waqta', e: 'at' },
    { a: 'الْمَسَاءِ،', t: 'al-masāʾi', e: 'evening' },
    NAHW, { g: ':' },
    { a: 'أَمْسَى', t: 'amsā', e: 'became' },
    { a: 'الرَّجُلُ', t: 'ar-rajulu', e: 'the man' },
    { a: 'كَالًّا', t: 'kāllan', e: 'weary' },
  ] },
  { t: 'line', w: [
    { a: 'الْخَامِسُ', t: 'al-khāmisu', e: 'the fifth' },
    { a: 'ظَلَّ،', t: 'ẓalla', e: 'ẓalla (to be during the day)' },
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
    { a: 'لِاتِّصَافِ', t: 'li-ttiṣāfi', e: 'for the qualifying' },
    { a: 'الِاسْمِ', t: 'al-ismi', e: 'of the noun' },
    { a: 'بِالْخَبَرِ', t: 'bil-khabari', e: 'by the predicate' },
    { a: 'وَقْتَ', t: 'waqta', e: 'during' },
    { a: 'النَّهَارِ،', t: 'an-nahāri', e: 'the daytime' },
    NAHW, { g: ':' }, OPEN,
    { a: 'وَانْظُرْ', t: 'wa-nẓur', e: 'and look', q: 1 },
    { a: 'إِلَى', t: 'ilā', e: 'at', q: 1 },
    { a: 'إِلَهِكَ', t: 'ilāhika', e: 'your god', q: 1 },
    { a: 'الَّذِي', t: 'alladhī', e: 'to which', q: 1 },
    { a: 'ظَلْتَ', t: 'ẓalta', e: 'you remained', q: 1 },
    { a: 'عَلَيْهِ', t: 'ʿalayhi', e: 'devoted', q: 1 },
    { a: 'عَاكِفًا', t: 'ʿākifan', e: 'in worship', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'السَّادِسُ', t: 'as-sādisu', e: 'the sixth' },
    { a: 'بَاتَ،', t: 'bāta', e: 'bāta (to be at night)' },
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
    { a: 'لِاتِّصَافِ', t: 'li-ttiṣāfi', e: 'for the qualifying' },
    { a: 'الِاسْمِ', t: 'al-ismi', e: 'of the noun' },
    { a: 'بِالْخَبَرِ', t: 'bil-khabari', e: 'by the predicate' },
    { a: 'وَقْتَ', t: 'waqta', e: 'during' },
    { a: 'اللَّيْلِ،', t: 'al-layli', e: 'the night' },
    NAHW, { g: ':' }, OPEN,
    { a: 'وَالَّذِينَ', t: 'wa-lladhīna', e: 'and those who', q: 1 },
    { a: 'يَبِيتُونَ', t: 'yabītūna', e: 'spend the night', q: 1 },
    { a: 'لِرَبِّهِمْ', t: 'li-rabbihim', e: 'for their Lord', q: 1 },
    { a: 'سُجَّدًا', t: 'sujjadan', e: 'prostrating', q: 1 },
    { a: 'وَقِيَامًا', t: 'wa-qiyāman', e: 'and standing', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'السَّابِعُ', t: 'as-sābiʿu', e: 'the seventh' },
    { a: 'صَارَ،', t: 'ṣāra', e: 'ṣāra (to become)' },
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
    { a: 'لِتَحَوُّلِ', t: 'li-taḥawwuli', e: 'for the change of' },
    { a: 'الذَّاتِ،', t: 'adh-dhāti', e: 'the essence' },
    NAHW, { g: ':' },
    { a: 'صَارَ', t: 'ṣāra', e: 'became' },
    { a: 'الْخَمْرُ', t: 'al-khamru', e: 'the wine' },
    { a: 'خَلًّا', t: 'khallan', e: 'vinegar' },
  ] },
  { t: 'line', w: [
    { a: 'وَلِتَحَوُّلِ', t: 'wa-li-taḥawwuli', e: 'and for the change of' },
    { a: 'الصِّفَاتِ،', t: 'aṣ-ṣifāti', e: 'attributes' },
    NAHW, { g: ':' },
    { a: 'صَارَ', t: 'ṣāra', e: 'became' },
    { a: 'الْمُذْنِبُ', t: 'al-mudhnibu', e: 'the sinner' },
    { a: 'مُتَّقِيًا', t: 'muttaqiyan', e: 'God-fearing' },
  ] },

  { t: 'h2', c: 'plain', ar: 'مَا يَأْتِي بِمَعْنَى صَارَ', en: 'Verbs that come to mean ṣāra (to become)' },
  { t: 'line', w: [
    { a: 'قَدْ', t: 'qad', e: 'sometimes' },
    { a: 'تَكُونُ', t: 'takūnu', e: 'are' },
    { a: 'كَانَ', t: 'kāna', e: 'kāna,' },
    { a: 'وَأَصْبَحَ', t: 'wa-aṣbaḥa', e: 'aṣbaḥa,' },
    { a: 'وَأَضْحَى', t: 'wa-aḍḥā', e: 'aḍḥā,' },
    { a: 'وَأَمْسَى', t: 'wa-amsā', e: 'amsā,' },
    { a: 'وَظَلَّ', t: 'wa-ẓalla', e: 'ẓalla,' },
    { a: 'وَبَاتَ', t: 'wa-bāta', e: 'and bāta' },
    { a: 'بِمَعْنَى', t: 'bi-maʿnā', e: 'in the sense of' },
    { a: 'صَارَ،', t: 'ṣāra', e: 'ṣāra (became)' },
    NAHW, { g: ':' }, OPEN,
    { a: 'فَسَجَدَ', t: 'fa-sajada', e: 'so prostrated', q: 1 },
    { a: 'الْمَلَائِكَةُ', t: 'al-malāʾikatu', e: 'the angels', q: 1 },
    { a: 'كُلُّهُمْ', t: 'kulluhum', e: 'all of them', q: 1 },
    { a: 'أَجْمَعُونَ', t: 'ajmaʿūna', e: 'together', q: 1 },
    ELL,
    { a: 'وَكَانَ', t: 'wa-kāna', e: 'and he became', q: 1 },
    { a: 'مِنَ', t: 'mina', e: 'of', q: 1 },
    { a: 'الْكَافِرِينَ', t: 'al-kāfirīna', e: 'the disbelievers', q: 1 },
    CLOSE,
  ] },
  { t: 'page', n: '٣٢' },
  { t: 'line', w: [
    { a: 'وَنحو:', t: 'wa-naḥwa', e: 'and e.g.' }, OPEN,
    { a: 'كُنْتُمْ', t: 'kuntum', e: 'you were', q: 1 },
    { a: 'أَعْدَاءً', t: 'aʿdāʾan', e: 'enemies', q: 1 },
    { a: 'فَأَلَّفَ', t: 'fa-allafa', e: 'and He joined', q: 1 },
    { a: 'بَيْنَ', t: 'bayna', e: 'between', q: 1 },
    { a: 'قُلُوبِكُمْ', t: 'qulūbikum', e: 'your hearts', q: 1 },
    { a: 'فَأَصْبَحْتُمْ', t: 'fa-aṣbaḥtum', e: 'and you became', q: 1 },
    { a: 'بِنِعْمَتِهِ', t: 'bi-niʿmatihi', e: 'by His grace', q: 1 },
    { a: 'إِخْوَانًا', t: 'ikhwānan', e: 'brothers', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'وَيَأْتِي', t: 'wa-yaʾtī', e: 'and also comes' },
    { a: 'بِمَعْنَى', t: 'bi-maʿnā', e: 'in the sense of' },
    { a: 'صَارَ', t: 'ṣāra', e: 'ṣāra' },
    { a: 'ارْتَدَّ،', t: 'irtadda', e: ': irtadda (became)' },
    NAHW, { g: ':' }, OPEN,
    { a: 'فَارْتَدَّ', t: 'fa-rtadda', e: 'and he became', q: 1 },
    { a: 'بَصِيرًا', t: 'baṣīran', e: 'seeing', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'وَعَادَ،', t: 'wa-ʿāda', e: 'and ʿāda (became / returned)' },
    NAHW, { g: ':' }, OPEN,
    { a: 'أَوْ', t: 'aw', e: 'or', q: 1 },
    { a: 'لَتَعُودُنَّ', t: 'la-taʿūdunna', e: 'you shall return', q: 1 },
    { a: 'فِي', t: 'fī', e: 'to', q: 1 },
    { a: 'مِلَّتِنَا', t: 'millatinā', e: 'our creed', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'وَاسْتَحَالَ،', t: 'wa-staḥāla', e: 'and istaḥāla (to turn into)' },
    NAHW, { g: ':' },
    { a: 'إِنَّ', t: 'inna', e: 'indeed' },
    { a: 'الْعَدَاوَةَ', t: 'al-ʿadāwata', e: 'enmity' },
    { a: 'تَسْتَحِيلُ', t: 'tastaḥīlu', e: 'turns into' },
    { a: 'مَوَدَّةً', t: 'mawaddatan', e: 'affection' },
  ] },

  { t: 'line', w: [
    { a: 'الثَّامِنُ', t: 'ath-thāminu', e: 'the eighth' },
    { a: 'مَا', t: 'mā', e: 'mā' },
    { a: 'بَرِحَ،', t: 'bariḥa', e: 'bariḥa (to keep on)' },
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
    { a: 'لِلِاسْتِمْرَارِ،', t: 'lil-istimrāri', e: 'for continuity' },
    NAHW, { g: ':' }, OPEN,
    { a: 'قَالُوا', t: 'qālū', e: 'they said', q: 1 },
    { a: 'لَنْ', t: 'lan', e: 'we will never', q: 1 },
    { a: 'نَبْرَحَ', t: 'nabraḥa', e: 'cease', q: 1 },
    { a: 'عَلَيْهِ', t: 'ʿalayhi', e: 'to it', q: 1 },
    { a: 'عَاكِفِينَ', t: 'ʿākifīna', e: 'being devoted', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'التَّاسِعُ', t: 'at-tāsiʿu', e: 'the ninth' },
    { a: 'مَا', t: 'mā', e: 'mā' },
    { a: 'انْفَكَّ،', t: 'infakka', e: 'infakka (to keep on)' },
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
    { a: 'لِلِاسْتِمْرَارِ،', t: 'lil-istimrāri', e: 'for continuity' },
    NAHW, { g: ':' },
    { a: 'مَا', t: 'mā', e: 'has not' },
    { a: 'انْفَكَّ', t: 'infakka', e: 'ceased' },
    { a: 'الْمُذْنِبُ', t: 'al-mudhnibu', e: 'the sinner' },
    { a: 'رَاجِيًا', t: 'rājiyan', e: 'hoping' },
  ] },
  { t: 'line', w: [
    { a: 'الْعَاشِرُ', t: 'al-ʿāshiru', e: 'the tenth' },
    { a: 'مَا', t: 'mā', e: 'mā' },
    { a: 'زَالَ،', t: 'zāla', e: 'zāla (to keep on)' },
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
    { a: 'لِلِاسْتِمْرَارِ،', t: 'lil-istimrāri', e: 'for continuity' },
    NAHW, { g: ':' }, OPEN,
    { a: 'فَمَا', t: 'fa-mā', e: 'and you did not', q: 1 },
    { a: 'زِلْتُمْ', t: 'ziltum', e: 'cease to be', q: 1 },
    { a: 'فِي', t: 'fī', e: 'in', q: 1 },
    { a: 'شَكٍّ', t: 'shakkin', e: 'doubt', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'الْحَادِيَ', t: 'al-ḥādiya', e: 'the elev-' },
    { a: 'عَشَرَ', t: 'ʿashara', e: '-enth' },
    { a: 'مَا', t: 'mā', e: 'mā' },
    { a: 'فَتِئَ،', t: 'fatiʾa', e: 'fatiʾa (to keep on)' },
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
    { a: 'لِلِاسْتِمْرَارِ،', t: 'lil-istimrāri', e: 'for continuity' },
    NAHW, { g: ':' }, OPEN,
    { a: 'تَاللهِ', t: 'ta-llāhi', e: 'By Allah', q: 1 },
    { a: 'تَفْتَأُ', t: 'taftaʾu', e: 'you will not cease', q: 1 },
    { a: 'تَذْكُرُ', t: 'tadhkuru', e: 'remembering', q: 1 },
    { a: 'يُوسُفَ', t: 'Yūsufa', e: 'Yūsuf', q: 1 },
    CLOSE,
  ] },
  { t: 'box', label: 'عمل هذه الأربعة', labelEn: 'When these four operate', lines: [
    [
      { a: 'هَذِهِ', t: 'hādhihi', e: 'these' },
      { a: 'الْأَرْبَعَةُ', t: 'al-arbaʿatu', e: 'four (bariḥa, infakka, zāla, fatiʾa)' },
      { a: 'نَاقِصَةُ', t: 'nāqiṣatu', e: 'are deficient in' },
      { a: 'التَّصَرُّفِ', t: 'at-taṣarrufi', e: 'conjugation' },
      { a: 'فَيَأْتِي', t: 'fa-yaʾtī', e: 'so there comes' },
      { a: 'مِنْهَا', t: 'minhā', e: 'from them' },
      { a: 'الْمَاضِي', t: 'al-māḍī', e: 'the past' },
      { a: 'وَالْمُضَارِعُ', t: 'wal-muḍāriʿu', e: 'and present' },
      { a: 'لَا', t: 'lā', e: 'only' },
      { a: 'غَيْرُ،', t: 'ghayru', e: '' },
      { a: 'وَلَا', t: 'wa-lā', e: 'and they do not' },
      { a: 'تَعْمَلُ', t: 'taʿmalu', e: 'operate' },
      { a: 'إِلَّا', t: 'illā', e: 'unless' },
      { a: 'إِذَا', t: 'idhā', e: '' },
      { a: 'تَقَدَّمَهَا', t: 'taqaddamahā', e: 'preceded by' },
      { a: 'نَهْيٌ', t: 'nahyun', e: 'a prohibition' },
      { a: 'أَوْ', t: 'aw', e: 'or' },
      { a: 'نَفْيٌ', t: 'nafyun', e: 'negation' },
      { a: 'أَوْ', t: 'aw', e: 'or' },
      { a: 'دُعَاءٌ', t: 'duʿāʾun', e: 'supplication' },
    ],
  ] },

  /* ── sisters 12–13; kāna-family rules ── */
  { t: 'page', n: '٣٣' },
  { t: 'box', label: 'زال الناقصة والتامة', labelEn: 'zāla: defective vs. complete', lines: [
    [
      { a: 'زَالَ', t: 'zāla', e: 'zāla' },
      { a: 'وَيَزَالُ', t: 'wa-yazālu', e: 'and yazālu' },
      { a: 'نَاقِصَانِ،', t: 'nāqiṣāni', e: 'are defective' },
      { a: 'وَزَالَ', t: 'wa-zāla', e: 'while zāla' },
      { a: 'وَيَزُولُ', t: 'wa-yazūlu', e: 'and yazūlu' },
      { a: 'فِعْلَانِ', t: 'fiʿlāni', e: 'are verbs' },
      { a: 'تَامَّانِ', t: 'tāmmāni', e: 'complete' },
      { a: 'مَصْدَرُهُمَا', t: 'maṣdaruhumā', e: 'whose verbal-noun is' },
      { a: 'زَوَالٌ،', t: 'zawālun', e: 'zawāl (ceasing)' },
      NAHW, { g: ':' }, OPEN,
      { a: 'إِنَّ', t: 'inna', e: 'indeed', q: 1 },
      { a: 'اللهَ', t: 'Allāha', e: 'Allah', q: 1 },
      { a: 'يُمْسِكُ', t: 'yumsiku', e: 'holds', q: 1 },
      { a: 'السَّمَاوَاتِ', t: 'as-samāwāti', e: 'the heavens', q: 1 },
      { a: 'وَالْأَرْضَ', t: 'wal-arḍa', e: 'and the earth', q: 1 },
      { a: 'أَنْ', t: 'an', e: 'lest', q: 1 },
      { a: 'تَزُولَا', t: 'tazūlā', e: 'they cease', q: 1 },
      CLOSE,
    ],
  ] },
  { t: 'line', w: [
    { a: 'الثَّانِيَ', t: 'ath-thāniya', e: 'the twelf-' },
    { a: 'عَشَرَ', t: 'ʿashara', e: '-th' },
    { a: 'مَا', t: 'mā', e: 'mā' },
    { a: 'دَامَ،', t: 'dāma', e: 'dāma (as long as)' },
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
    { a: 'لِتَوْقِيتِ', t: 'li-tawqīti', e: 'to set the time of' },
    { a: 'مَا', t: 'mā', e: 'what' },
    { a: 'قَبْلَهُ', t: 'qablahu', e: 'precedes it' },
    { a: 'بِمُدَّةِ', t: 'bi-muddati', e: 'by the duration of' },
    { a: 'اتِّصَافِ', t: 'ittiṣāfi', e: 'the qualifying of' },
    { a: 'الِاسْمِ', t: 'al-ismi', e: 'the noun' },
    { a: 'بِالْخَبَرِ،', t: 'bil-khabari', e: 'by the predicate' },
    NAHW, { g: ':' }, OPEN,
    { a: 'وَأَوْصَانِي', t: 'wa-awṣānī', e: 'and He enjoined me', q: 1 },
    { a: 'بِالصَّلَاةِ', t: 'bi-ṣ-ṣalāti', e: 'with prayer', q: 1 },
    { a: 'وَالزَّكَاةِ', t: 'wa-z-zakāti', e: 'and alms', q: 1 },
    { a: 'مَا', t: 'mā', e: 'as long as', q: 1 },
    { a: 'دُمْتُ', t: 'dumtu', e: 'I remain', q: 1 },
    { a: 'حَيًّا', t: 'ḥayyan', e: 'alive', q: 1 },
    CLOSE,
  ] },
  { t: 'box', label: 'ما يقوم مقام ما دام', labelEn: 'What stands for mā dāma', lines: [
    [
      { a: 'قَدْ', t: 'qad', e: 'sometimes' },
      { a: 'تَقُومُ', t: 'taqūmu', e: 'stands' },
      { a: 'كَلِمَةُ', t: 'kalimatu', e: 'the word' },
      { a: 'مَا', t: 'mā', e: 'mā' },
      { a: 'وَحْدَهَا', t: 'waḥdahā', e: 'alone' },
      { a: 'مَقَامَ', t: 'maqāma', e: 'in place of' },
      { a: 'مَا', t: 'mā', e: 'mā' },
      { a: 'دَامَ،', t: 'dāma', e: 'dāma' },
      NAHW, { g: ':' },
      { a: 'وَاللهُ', t: 'wallāhu', e: 'Allah is' },
      { a: 'فِي', t: 'fī', e: 'in' },
      { a: 'عَوْنِ', t: 'ʿawni', e: 'the aid of' },
      { a: 'الْعَبْدِ', t: 'al-ʿabdi', e: 'the servant' },
      { a: 'مَا', t: 'mā', e: 'as long as' },
      { a: 'كَانَ', t: 'kāna', e: 'is' },
      { a: 'الْعَبْدُ', t: 'al-ʿabdu', e: 'the servant' },
      { a: 'فِي', t: 'fī', e: 'in' },
      { a: 'عَوْنِ', t: 'ʿawni', e: 'the aid of' },
      { a: 'أَخِيهِ', t: 'akhīhi', e: 'his brother' },
    ],
    [
      { a: 'وَيَكْثُرُ', t: 'wa-yakthuru', e: 'and it is frequent' },
      { a: 'ذَلِكَ', t: 'dhālika', e: 'that' },
      { a: 'قَبْلَ', t: 'qabla', e: 'before' },
      { a: 'لَمْ،', t: 'lam', e: 'lam' },
      NAHW, { g: ':' },
      { a: 'يُسْتَجَابُ', t: 'yustajābu', e: 'answered is' },
      { a: 'لِأَحَدِكُمْ', t: 'li-aḥadikum', e: 'one of you' },
      { a: 'مَا', t: 'mā', e: 'so long as' },
      { a: 'لَمْ', t: 'lam', e: 'he is not' },
      { a: 'يَعْجَلْ', t: 'yaʿjal', e: 'hasty' },
    ],
  ] },
  { t: 'line', w: [
    { a: 'الثَّالِثَ', t: 'ath-thālitha', e: 'the thir-' },
    { a: 'عَشَرَ', t: 'ʿashara', e: '-teenth' },
    { a: 'لَيْسَ،', t: 'laysa', e: 'laysa (is not)' },
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
    { a: 'لِنَفْيِ', t: 'li-nafyi', e: 'for negating' },
    { a: 'الْحَالِ،', t: 'al-ḥāli', e: 'the present' },
    NAHW, { g: ':' }, OPEN,
    { a: 'لَيْسَ', t: 'laysa', e: 'not', q: 1 },
    { a: 'عَلَيْكَ', t: 'ʿalayka', e: 'upon you is', q: 1 },
    { a: 'هُدَاهُمْ', t: 'hudāhum', e: 'their guidance', q: 1 },
    CLOSE,
  ] },
  { t: 'box', label: 'الأفعال الناقصة التامة', labelEn: 'Defective verbs used as complete', lines: [
    [
      { a: 'الْفِعْلُ', t: 'al-fiʿlu', e: 'the complete verb' },
      { a: 'التَّامُّ', t: 'at-tāmmu', e: '' },
      { a: 'مَا', t: 'mā', e: 'is what' },
      { a: 'يَكْتَفِي', t: 'yaktafī', e: 'suffices' },
      { a: 'بِفَاعِلِهِ', t: 'bi-fāʿilihi', e: 'with its subject' },
      { a: 'وَلَا', t: 'wa-lā', e: 'and does not' },
      { a: 'يَحْتَاجُ', t: 'yaḥtāju', e: 'need' },
      { a: 'إِلَى', t: 'ilā', e: 'a' },
      { a: 'خَبَرٍ،', t: 'khabarin', e: 'predicate' },
      NAHW, { g: ':' },
      { a: 'كَانَتْ', t: 'kānat', e: 'there occurred' },
      { a: 'حَرْبٌ', t: 'ḥarbun', e: 'a war' },
    ],
    [
      { a: 'قَدْ', t: 'qad', e: 'sometimes' },
      { a: 'تَكُونُ', t: 'takūnu', e: 'are' },
      { a: 'كَانَ', t: 'kāna', e: 'kāna' },
      { a: 'وَأَخَوَاتُهَا', t: 'wa-akhawātuhā', e: 'and its sisters' },
      { a: 'تَامَّةً', t: 'tāmmatan', e: 'complete' },
      { a: 'إِلَّا', t: 'illā', e: 'except' },
      { a: 'مَا', t: 'mā', e: 'mā' },
      { a: 'زَالَ', t: 'zāla', e: 'zāla,' },
      { a: 'وَمَا', t: 'wa-mā', e: 'mā' },
      { a: 'فَتِئَ', t: 'fatiʾa', e: 'fatiʾa,' },
      { a: 'وَمَا', t: 'wa-mā', e: 'mā' },
      { a: 'بَرِحَ', t: 'bariḥa', e: 'bariḥa,' },
      { a: 'وَلَيْسَ،', t: 'wa-laysa', e: 'and laysa' },
      NAHW, { g: ':' }, OPEN,
      { a: 'وَإِنْ', t: 'wa-in', e: 'and if', q: 1 },
      { a: 'كَانَ', t: 'kāna', e: 'there is', q: 1 },
      { a: 'ذُو', t: 'dhū', e: 'one in', q: 1 },
      { a: 'عُسْرَةٍ', t: 'ʿusratin', e: 'hardship', q: 1 },
      { a: 'فَنَظِرَةٌ', t: 'fa-naẓiratun', e: 'then postponement', q: 1 },
      { a: 'إِلَى', t: 'ilā', e: 'until', q: 1 },
      { a: 'مَيْسَرَةٍ', t: 'maysaratin', e: 'ease', q: 1 },
      CLOSE,
    ],
    [
      { a: 'وَنحو:', t: 'wa-naḥwa', e: 'and e.g.' }, OPEN,
      { a: 'فَسُبْحَانَ', t: 'fa-subḥāna', e: 'so glory be to', q: 1 },
      { a: 'اللهِ', t: 'Allāhi', e: 'Allah', q: 1 },
      { a: 'حِينَ', t: 'ḥīna', e: 'when', q: 1 },
      { a: 'تُمْسُونَ', t: 'tumsūna', e: 'you reach evening', q: 1 },
      { a: 'وَحِينَ', t: 'wa-ḥīna', e: 'and when', q: 1 },
      { a: 'تُصْبِحُونَ', t: 'tuṣbiḥūna', e: 'you reach morning', q: 1 },
      CLOSE,
    ],
    [
      { a: 'وَنحو:', t: 'wa-naḥwa', e: 'and e.g.' }, OPEN,
      { a: 'خَالِدِينَ', t: 'khālidīna', e: 'abiding', q: 1 },
      { a: 'فِيهَا', t: 'fīhā', e: 'therein', q: 1 },
      { a: 'مَا', t: 'mā', e: 'as long as', q: 1 },
      { a: 'دَامَتِ', t: 'dāmati', e: 'last', q: 1 },
      { a: 'السَّمَاوَاتُ', t: 'as-samāwātu', e: 'the heavens', q: 1 },
      { a: 'وَالْأَرْضُ', t: 'wal-arḍu', e: 'and the earth', q: 1 },
      CLOSE,
    ],
  ] },
  { t: 'box', label: 'توسط الخبر', labelEn: 'The predicate coming in the middle', lines: [
    [
      { a: 'يَجُوزُ', t: 'yajūzu', e: 'permitted is' },
      { a: 'تَوَسُّطُ', t: 'tawassuṭu', e: 'the placing in the middle of' },
      { a: 'الْخَبَرِ', t: 'al-khabari', e: 'the predicate' },
      { a: 'بَيْنَ', t: 'bayna', e: 'between' },
      { a: 'الْفِعْلِ', t: 'al-fiʿli', e: 'the verb' },
      { a: 'النَّاقِصِ', t: 'an-nāqiṣi', e: 'defective' },
      { a: 'وَاسْمِهِ،', t: 'wa-ismihi', e: 'and its noun' },
      NAHW, { g: ':' }, OPEN,
      { a: 'كَانَ', t: 'kāna', e: 'it was', q: 1 },
      { a: 'حَقًّا', t: 'ḥaqqan', e: 'a duty', q: 1 },
      { a: 'عَلَيْنَا', t: 'ʿalaynā', e: 'upon Us', q: 1 },
      { a: 'نَصْرُ', t: 'naṣru', e: 'to help', q: 1 },
      { a: 'الْمُؤْمِنِينَ', t: 'al-muʾminīna', e: 'the believers', q: 1 },
      CLOSE,
    ],
  ] },
  { t: 'box', label: 'تقديم معمول الخبر', labelEn: 'Fronting the predicate’s governed term', lines: [
    [
      { a: 'يَجُوزُ', t: 'yajūzu', e: 'permitted is' },
      { a: 'تَقْدِيمُ', t: 'taqdīmu', e: 'fronting' },
      { a: 'مَعْمُولِ', t: 'maʿmūli', e: 'the governed term of' },
      { a: 'الْخَبَرِ', t: 'al-khabari', e: 'the predicate' },
      { a: 'عَلَى', t: 'ʿalā', e: 'before' },
      { a: 'الْفِعْلِ', t: 'al-fiʿli', e: 'the verb' },
      { a: 'النَّاقِصِ،', t: 'an-nāqiṣi', e: 'defective' },
      NAHW, { g: ':' }, OPEN,
      { a: 'أَهَؤُلَاءِ', t: 'a-hāʾulāʾi', e: 'is it these', q: 1 },
      { a: 'إِيَّاكُمْ', t: 'iyyākum', e: 'you', q: 1 },
      { a: 'كَانُوا', t: 'kānū', e: 'used to', q: 1 },
      { a: 'يَعْبُدُونَ', t: 'yaʿbudūna', e: 'worship', q: 1 },
      CLOSE,
    ],
  ] },

  /* ── kind 2: the verbs of hoping ── */
  { t: 'page', n: '٣٤' },
  { t: 'h2', c: 'green', ar: 'الضَّرْبُ الثَّانِي: أَفْعَالُ الرَّجَاءِ', en: 'Second kind — the verbs of hoping (af‘āl al-rajāʾ)' },
  { t: 'line', w: [
    { a: 'وَهِيَ', t: 'wa-hiya', e: 'and they are' },
    { a: 'مَا', t: 'mā', e: 'those' },
    { a: 'وُضِعَتْ', t: 'wuḍiʿat', e: 'coined' },
    { a: 'لِلدَّلَالَةِ', t: 'lid-dalālati', e: 'to denote' },
    { a: 'عَلَى', t: 'ʿalā', e: '' },
    { a: 'الرَّجَاءِ،', t: 'ar-rajāʾi', e: 'hope' },
  ] },
  { t: 'line', w: [
    { a: 'وَهِيَ', t: 'wa-hiya', e: 'and they are' },
    { a: 'ثَلَاثٌ', t: 'thalāthun', e: 'three' }, { g: ':' },
  ] },
  { t: 'line', w: [
    { a: 'الْأَوَّلُ', t: 'al-awwalu', e: 'the first' },
    { a: 'عَسَى،', t: 'ʿasā', e: 'ʿasā (perhaps / it is hoped)' },
    NAHW, { g: ':' }, OPEN,
    { a: 'عَسَى', t: 'ʿasā', e: 'perhaps', q: 1 },
    { a: 'أَنْ', t: 'an', e: 'that', q: 1 },
    { a: 'يَنْفَعَنَا', t: 'yanfaʿanā', e: 'he will benefit us', q: 1 },
    { a: 'أَوْ', t: 'aw', e: 'or', q: 1 },
    { a: 'نَتَّخِذَهُ', t: 'nattakhidhahu', e: 'we will take him', q: 1 },
    { a: 'وَلَدًا', t: 'waladan', e: 'as a son', q: 1 },
    CLOSE,
  ] },
  { t: 'box', label: 'معاني عسى', labelEn: 'The senses of ʿasā', lines: [
    [
      { a: 'يَتَضَمَّنُ', t: 'yataḍammanu', e: 'ʿasā contains' },
      { a: 'عَسَى', t: 'ʿasā', e: '' },
      { a: 'مَعْنَى', t: 'maʿnā', e: 'the sense of' },
      { a: 'الْمُقَارَبَةِ،', t: 'al-muqārabati', e: 'proximity' },
      { a: 'وَتَدُلُّ', t: 'wa-tadullu', e: 'and denotes' },
      { a: 'عَلَى', t: 'ʿalā', e: '' },
      ELL,
    ],
    [
      { a: 'التَّرَجِّي', t: 'at-tarajjī', e: 'hoping' },
      { a: 'فِي', t: 'fī', e: 'for' },
      { a: 'الْمَحْبُوبِ،', t: 'al-maḥbūbi', e: 'the desired' },
      NAHW, { g: ':' }, OPEN,
      { a: 'عَسَى', t: 'ʿasā', e: 'perhaps', q: 1 },
      { a: 'اللهُ', t: 'Allāhu', e: 'Allah', q: 1 },
      { a: 'أَنْ', t: 'an', e: 'will', q: 1 },
      { a: 'يَعْفُوَ', t: 'yaʿfuwa', e: 'pardon', q: 1 },
      { a: 'عَنْهُمْ', t: 'ʿanhum', e: 'them', q: 1 },
      CLOSE,
    ],
    [
      { a: 'وَالْإِشْفَاقُ', t: 'wal-ishfāqu', e: 'and apprehension' },
      { a: 'مِنَ', t: 'mina', e: 'of' },
      { a: 'الْمَكْرُوهِ،', t: 'al-makrūhi', e: 'the disliked' },
      NAHW, { g: ':' }, OPEN,
      { a: 'فَهَلْ', t: 'fa-hal', e: 'would', q: 1 },
      { a: 'عَسَيْتُمْ', t: 'ʿasaytum', e: 'you perhaps', q: 1 },
      { a: 'إِنْ', t: 'in', e: 'if', q: 1 },
      { a: 'تَوَلَّيْتُمْ', t: 'tawallaytum', e: 'you turned away', q: 1 },
      { a: 'أَنْ', t: 'an', e: '', q: 1 },
      { a: 'تُفْسِدُوا', t: 'tufsidū', e: 'cause corruption', q: 1 },
      { a: 'فِي', t: 'fī', e: 'in', q: 1 },
      { a: 'الْأَرْضِ', t: 'al-arḍi', e: 'the land', q: 1 },
      { a: 'وَتُقَطِّعُوا', t: 'wa-tuqaṭṭiʿū', e: 'and sever', q: 1 },
      { a: 'أَرْحَامَكُمْ', t: 'arḥāmakum', e: 'your ties of kinship', q: 1 },
      CLOSE,
    ],
    [
      { a: 'وَالتَّعْلِيلُ،', t: 'wat-taʿlīlu', e: 'and causation' },
      NAHW, { g: ':' }, OPEN,
      { a: 'عَسَى', t: 'ʿasā', e: 'so that', q: 1 },
      { a: 'أَنْ', t: 'an', e: '', q: 1 },
      { a: 'يَبْعَثَكَ', t: 'yabʿathaka', e: 'your Lord may raise you', q: 1 },
      { a: 'رَبُّكَ', t: 'rabbuka', e: '', q: 1 },
      { a: 'مَقَامًا', t: 'maqāman', e: 'to a station', q: 1 },
      { a: 'مَحْمُودًا', t: 'maḥmūdan', e: 'praiseworthy', q: 1 },
      CLOSE,
    ],
  ] },
  { t: 'line', w: [
    { a: 'الثَّانِي', t: 'ath-thānī', e: 'the second' },
    { a: 'اخْلَوْلَقَ،', t: 'ikhlawlaqa', e: 'ikhlawlaqa (to become likely)' },
    NAHW, { g: ':' },
    { a: 'اخْلَوْلَقَ', t: 'ikhlawlaqa', e: 'came near' },
    { a: 'الْمُسْلِمُونَ', t: 'al-muslimūna', e: 'the Muslims' },
    { a: 'أَنْ', t: 'an', e: 'to' },
    { a: 'يُحَافِظُوا', t: 'yuḥāfiẓū', e: 'maintain' },
    { a: 'عَلَى', t: 'ʿalā', e: '' },
    { a: 'الصَّلَاةِ', t: 'aṣ-ṣalāti', e: 'the prayer' },
  ] },
  { t: 'box', label: 'معنى اخلولق', labelEn: 'Meaning of ikhlawlaqa', lines: [
    [
      { a: 'مَعْنَى', t: 'maʿnā', e: 'the meaning of' },
      { a: 'اخْلَوْلَقَ', t: 'ikhlawlaqa', e: 'ikhlawlaqa is' },
      { a: 'صَارَ', t: 'ṣāra', e: 'became' },
      { a: 'خَلِيقًا', t: 'khalīqan', e: 'fit / likely' },
    ],
  ] },
  { t: 'line', w: [
    { a: 'الثَّالِثُ', t: 'ath-thālithu', e: 'the third' },
    { a: 'حَرَى،', t: 'ḥarā', e: 'ḥarā (to be apt)' },
    NAHW, { g: ':' },
    { a: 'حَرَى', t: 'ḥarā', e: 'is apt' },
    { a: 'الْمُذْنِبُ', t: 'al-mudhnibu', e: 'the sinner' },
    { a: 'أَنْ', t: 'an', e: 'to' },
    { a: 'يَتُوبَ', t: 'yatūba', e: 'repent' },
  ] },
  { t: 'box', label: 'معنى حرى', labelEn: 'Meaning of ḥarā', lines: [
    [
      { a: 'مَعْنَى', t: 'maʿnā', e: 'the meaning of' },
      { a: 'حَرَى', t: 'ḥarā', e: 'ḥarā is' },
      { a: 'صَارَ', t: 'ṣāra', e: 'became' },
      { a: 'حَرِيًّا', t: 'ḥariyyan', e: 'apt' },
    ],
  ] },
  { t: 'box', label: 'أن في خبر أفعال الرجاء', labelEn: 'The particle an in the predicate of hope-verbs', lines: [
    [
      { a: 'يَكْثُرُ', t: 'yakthuru', e: 'frequent is' },
      { a: 'حَرْفُ', t: 'ḥarfu', e: 'the particle' },
      { a: 'أَنْ', t: 'an', e: 'an' },
      { a: 'فِي', t: 'fī', e: 'in' },
      { a: 'خَبَرِ', t: 'khabari', e: 'the predicate of' },
      { a: 'عَسَى،', t: 'ʿasā', e: 'ʿasā' },
      { a: 'وَيَجِبُ', t: 'wa-yajibu', e: 'and obligatory' },
      { a: 'فِي', t: 'fī', e: 'in' },
      { a: 'خَبَرِ', t: 'khabari', e: 'the predicate of' },
      { a: 'اخْلَوْلَقَ', t: 'ikhlawlaqa', e: 'ikhlawlaqa' },
      { a: 'وَحَرَى', t: 'wa-ḥarā', e: 'and ḥarā' },
    ],
  ] },

  /* ── kind 3: the verbs of proximity ── */
  { t: 'page', n: '٣٥' },
  { t: 'box', label: 'تمام أفعال الرجاء', labelEn: 'Hope-verbs used as complete', lines: [
    [
      { a: 'قَدْ', t: 'qad', e: 'sometimes' },
      { a: 'تَكُونُ', t: 'takūnu', e: 'are' },
      { a: 'أَفْعَالُ', t: 'afʿālu', e: 'the verbs of' },
      { a: 'الرَّجَاءِ', t: 'ar-rajāʾi', e: 'hope' },
      { a: 'تَامَّةً،', t: 'tāmmatan', e: 'complete' },
      NAHW, { g: ':' }, OPEN,
      { a: 'عَسَى', t: 'ʿasā', e: 'perhaps', q: 1 },
      { a: 'أَنْ', t: 'an', e: '', q: 1 },
      { a: 'يَبْعَثَكَ', t: 'yabʿathaka', e: 'your Lord will raise you', q: 1 },
      { a: 'رَبُّكَ', t: 'rabbuka', e: '', q: 1 },
      { a: 'مَقَامًا', t: 'maqāman', e: 'to a station', q: 1 },
      { a: 'مَحْمُودًا', t: 'maḥmūdan', e: 'praiseworthy', q: 1 },
      CLOSE,
    ],
  ] },
  { t: 'h2', c: 'green', ar: 'الضَّرْبُ الثَّالِثُ: أَفْعَالُ الْمُقَارَبَةِ', en: 'Third kind — the verbs of proximity (af‘āl al-muqāraba)' },
  { t: 'line', w: [
    { a: 'وَهِيَ', t: 'wa-hiya', e: 'and they are' },
    { a: 'مَا', t: 'mā', e: 'those' },
    { a: 'وُضِعَتْ', t: 'wuḍiʿat', e: 'coined' },
    { a: 'لِلدَّلَالَةِ', t: 'lid-dalālati', e: 'to denote' },
    { a: 'عَلَى', t: 'ʿalā', e: '' },
    { a: 'قُرْبِ', t: 'qurbi', e: 'the nearness of' },
    { a: 'وُقُوعِ', t: 'wuqūʿi', e: 'the occurrence of' },
    { a: 'الْخَبَرِ،', t: 'al-khabari', e: 'the predicate' },
    { a: 'وَهِيَ', t: 'wa-hiya', e: 'and they are' },
    { a: 'ثَلَاثٌ', t: 'thalāthun', e: 'three' }, { g: ':' },
  ] },
  { t: 'line', w: [
    { a: 'الْأَوَّلُ', t: 'al-awwalu', e: 'the first' },
    { a: 'كَادَ،', t: 'kāda', e: 'kāda (almost / to be on the verge)' },
    NAHW, { g: ':' }, OPEN,
    { a: 'وَكَادُوا', t: 'wa-kādū', e: 'and they almost', q: 1 },
    { a: 'يَقْتُلُونَنِي', t: 'yaqtulūnanī', e: 'killed me', q: 1 },
    CLOSE,
  ] },
  { t: 'box', label: 'الفرق بين عسى وكاد', labelEn: 'ʿasā vs. kāda', lines: [
    [
      { a: 'تَدُلُّ', t: 'tadullu', e: 'they denote' },
      { a: 'عَلَى', t: 'ʿalā', e: '' },
      { a: 'مَعْنَى', t: 'maʿnā', e: 'the sense of' },
      { a: 'الْمُقَارَبَةِ', t: 'al-muqārabati', e: 'proximity' },
      ELL,
    ],
    [
      { a: 'عَسَى', t: 'ʿasā', e: 'ʿasā' },
      { a: 'عَلَى', t: 'ʿalā', e: 'by way of' },
      { a: 'سَبِيلِ', t: 'sabīli', e: '' },
      { a: 'الرَّجَاءِ،', t: 'ar-rajāʾi', e: 'hope' },
    ],
    [
      { a: 'وَكَادَ', t: 'wa-kāda', e: 'while kāda' },
      { a: 'وَأَخَوَاتُهَا', t: 'wa-akhawātuhā', e: 'and its sisters' },
      { a: 'عَلَى', t: 'ʿalā', e: 'by way of' },
      { a: 'سَبِيلِ', t: 'sabīli', e: '' },
      { a: 'الْحُصُولِ', t: 'al-ḥuṣūli', e: 'actual occurrence' },
    ],
  ] },
  { t: 'box', label: 'دلالة كاد', labelEn: 'kāda: affirmative vs. negative', lines: [
    [
      { a: 'الْمُثْبَتُ', t: 'al-muthbatu', e: 'the affirmative' },
      { a: 'عَلَى', t: 'ʿalā', e: 'denotes' },
      { a: 'نَفْيِ', t: 'nafyi', e: 'the non-' },
      { a: 'وُقُوعِ', t: 'wuqūʿi', e: 'occurrence of' },
      { a: 'الْفِعْلِ', t: 'al-fiʿli', e: 'the act' },
      { a: 'مَعَ', t: 'maʿa', e: 'with' },
      { a: 'مُقَارَبَةِ', t: 'muqārabati', e: 'nearness of' },
      { a: 'الْوُقُوعِ،', t: 'al-wuqūʿi', e: 'occurrence' },
      NAHW, { g: ':' }, OPEN,
      { a: 'وَكَادُوا', t: 'wa-kādū', e: 'and they almost', q: 1 },
      { a: 'يَقْتُلُونَنِي', t: 'yaqtulūnanī', e: 'killed me', q: 1 },
      CLOSE,
    ],
    [
      { a: 'وَالْمَنْفِيُّ', t: 'wal-manfiyyu', e: 'and the negative' },
      { a: 'عَلَى', t: 'ʿalā', e: 'denotes' },
      { a: 'نَفْيِ', t: 'nafyi', e: 'the non-' },
      { a: 'وُقُوعِ', t: 'wuqūʿi', e: 'occurrence of' },
      { a: 'الْفِعْلِ', t: 'al-fiʿli', e: 'the act' },
      { a: 'مَعَ', t: 'maʿa', e: 'with' },
      { a: 'نَفْيِ', t: 'nafyi', e: 'the non-' },
      { a: 'مُقَارَبَةِ', t: 'muqārabati', e: 'nearness of' },
      { a: 'الْوُقُوعِ،', t: 'al-wuqūʿi', e: 'occurrence' },
      { a: 'فَهُوَ', t: 'fa-huwa', e: 'so it is' },
      { a: 'آكَدُ', t: 'ākadu', e: 'more emphatic' },
      { a: 'فِي', t: 'fī', e: 'in' },
      { a: 'النَّفْيِ،', t: 'an-nafyi', e: 'negation' },
      NAHW, { g: ':' }, OPEN,
      { a: 'يَتَجَرَّعُهُ', t: 'yatajarraʿuhu', e: 'he gulps it', q: 1 },
      { a: 'وَلَا', t: 'wa-lā', e: 'but hardly', q: 1 },
      { a: 'يَكَادُ', t: 'yakādu', e: '', q: 1 },
      { a: 'يُسِيغُهُ', t: 'yusīghuhu', e: 'can swallow it', q: 1 },
      CLOSE,
    ],
  ] },
  { t: 'line', w: [
    { a: 'الثَّانِي', t: 'ath-thānī', e: 'the second' },
    { a: 'كَرَبَ،', t: 'karaba', e: 'karaba (to be about to)' },
    NAHW, { g: ':' },
    { a: 'كَرَبَ', t: 'karaba', e: 'was about to,' },
    { a: 'الْمُؤَذِّنُ', t: 'al-muʾadhdhinu', e: 'the muezzin,' },
    { a: 'يُقِيمُ', t: 'yuqīmu', e: 'to call the iqāma' },
  ] },
  { t: 'line', w: [
    { a: 'الثَّالِثُ', t: 'ath-thālithu', e: 'the third' },
    { a: 'أَوْشَكَ،', t: 'awshaka', e: 'awshaka (to be on the verge)' },
    NAHW, { g: ':' },
    { a: 'مَنْ', t: 'man', e: 'whoever' },
    { a: 'زَرَعَ', t: 'zaraʿa', e: 'sows' },
    { a: 'شَرًّا', t: 'sharran', e: 'evil' },
    { a: 'يُوشِكُ', t: 'yūshiku', e: 'is about' },
    { a: 'أَنْ', t: 'an', e: 'to' },
    { a: 'يَحْصُدَ', t: 'yaḥṣuda', e: 'reap' },
    { a: 'نَدَامَةً', t: 'nadāmatan', e: 'regret' },
  ] },
  { t: 'box', label: 'أن في خبر المقاربة', labelEn: 'The particle an in proximity-verbs', lines: [
    [
      { a: 'يَكْثُرُ', t: 'yakthuru', e: 'frequent is' },
      { a: 'حَرْفُ', t: 'ḥarfu', e: 'the particle' },
      { a: 'أَنْ', t: 'an', e: 'an' },
      { a: 'فِي', t: 'fī', e: 'in' },
      { a: 'خَبَرِ', t: 'khabari', e: 'the predicate of' },
      { a: 'أَوْشَكَ،', t: 'awshaka', e: 'awshaka' },
      { a: 'وَيَقِلُّ', t: 'wa-yaqillu', e: 'and rare' },
      { a: 'فِي', t: 'fī', e: 'in' },
      { a: 'خَبَرِ', t: 'khabari', e: 'the predicate of' },
      { a: 'كَادَ', t: 'kāda', e: 'kāda' },
      { a: 'وَكَرَبَ', t: 'wa-karaba', e: 'and karaba' },
    ],
  ] },

  /* ── kind 4: the verbs of beginning ── */
  { t: 'page', n: '٣٦' },
  { t: 'box', label: 'تصرف أفعال الرجاء والمقاربة', labelEn: 'Conjugation of hope/proximity verbs', lines: [
    [
      { a: 'أَفْعَالُ', t: 'afʿālu', e: 'the verbs of' },
      { a: 'الرَّجَاءِ', t: 'ar-rajāʾi', e: 'hope' },
      { a: 'وَالْمُقَارَبَةِ', t: 'wal-muqārabati', e: 'and proximity' },
      { a: 'نَاقِصَةُ', t: 'nāqiṣatu', e: 'are deficient in' },
      { a: 'التَّصَرُّفِ', t: 'at-taṣarrufi', e: 'conjugation' },
      { a: 'مُلَازِمَةٌ', t: 'mulāzimatun', e: 'bound to' },
      { a: 'لِلْمَاضِي،', t: 'lil-māḍī', e: 'the past' },
      { a: 'إِلَّا', t: 'illā', e: 'except' },
      ELL,
    ],
    [
      { a: 'كَادَ،', t: 'kāda', e: 'kāda' },
      NAHW, { g: ':' }, OPEN,
      { a: 'يَكَادُ', t: 'yakādu', e: 'almost', q: 1 },
      { a: 'الْبَرْقُ', t: 'al-barqu', e: 'the lightning', q: 1 },
      { a: 'يَخْطَفُ', t: 'yakhṭafu', e: 'snatches away', q: 1 },
      { a: 'أَبْصَارَهُمْ', t: 'abṣārahum', e: 'their sight', q: 1 },
      CLOSE,
    ],
    [
      { a: 'وَأَوْشَكَ،', t: 'wa-awshaka', e: 'and awshaka' },
      NAHW, { g: ':' },
      { a: 'يُوشِكُ', t: 'yūshiku', e: 'it is near' },
      { a: 'أَنْ', t: 'an', e: 'that' },
      { a: 'يَعُمَّهُمُ', t: 'yaʿummahumu', e: 'will overtake them' },
      { a: 'اللهُ', t: 'Allāhu', e: 'Allah' },
      { a: 'بِعِقَابٍ', t: 'bi-ʿiqābin', e: 'with punishment' },
    ],
  ] },
  { t: 'h2', c: 'green', ar: 'الضَّرْبُ الرَّابِعُ: أَفْعَالُ الشُّرُوعِ', en: 'Fourth kind — the verbs of beginning (af‘āl al-shurūʿ)' },
  { t: 'line', w: [
    { a: 'وَهِيَ', t: 'wa-hiya', e: 'and they are' },
    { a: 'مَا', t: 'mā', e: 'those' },
    { a: 'وُضِعَتْ', t: 'wuḍiʿat', e: 'coined' },
    { a: 'لِلدَّلَالَةِ', t: 'lid-dalālati', e: 'to denote' },
    { a: 'عَلَى', t: 'ʿalā', e: '' },
    { a: 'الشُّرُوعِ', t: 'ash-shurūʿi', e: 'beginning' },
    { a: 'فِي', t: 'fī', e: 'in' },
    { a: 'الْفِعْلِ،', t: 'al-fiʿli', e: 'the action' },
    { a: 'مِنْهَا', t: 'minhā', e: 'among them' },
    { a: 'جَعَلَ', t: 'jaʿala', e: 'jaʿala,' },
    { a: 'وَأَخَذَ', t: 'wa-akhadha', e: 'akhadha,' },
    { a: 'وَطَفِقَ', t: 'wa-ṭafiqa', e: 'ṭafiqa,' },
    { a: 'وَعَلِقَ', t: 'wa-ʿaliqa', e: 'ʿaliqa,' },
    { a: 'وَأَنْشَأَ،', t: 'wa-anshaʾa', e: 'and anshaʾa' },
    NAHW, { g: ':' }, OPEN,
    { a: 'وَطَفِقَا', t: 'wa-ṭafiqā', e: 'and they both began', q: 1 },
    { a: 'يَخْصِفَانِ', t: 'yakhṣifāni', e: 'fastening', q: 1 },
    { a: 'عَلَيْهِمَا', t: 'ʿalayhimā', e: 'upon themselves', q: 1 },
    { a: 'مِنْ', t: 'min', e: 'from', q: 1 },
    { a: 'وَرَقِ', t: 'waraqi', e: 'the leaves of', q: 1 },
    { a: 'الْجَنَّةِ', t: 'al-jannati', e: 'the Garden', q: 1 },
    CLOSE,
  ] },

  /* ── Division 2: the verbs of praise & blame ── */
  { t: 'page', n: '٣٧' },
  { t: 'h2', c: 'blue', ar: 'الْقِسْمُ الثَّانِي: أَفْعَالُ الْمَدْحِ وَالذَّمِّ', en: 'Second division — the verbs of praise & blame' },
  { t: 'line', w: [
    { a: 'وَهِيَ', t: 'wa-hiya', e: 'and they are' },
    { a: 'مَا', t: 'mā', e: 'those' },
    { a: 'وُضِعَتْ', t: 'wuḍiʿat', e: 'coined' },
    { a: 'لِلدَّلَالَةِ', t: 'lid-dalālati', e: 'to denote' },
    { a: 'عَلَى', t: 'ʿalā', e: '' },
    { a: 'الْمَدْحِ', t: 'al-madḥi', e: 'praise' },
    { a: 'وَالذَّمِّ،', t: 'wadh-dhammi', e: 'and blame' },
    { a: 'وَهِيَ', t: 'wa-hiya', e: 'and they' },
    { a: 'تَرْفَعُ', t: 'tarfaʿu', e: 'raise' },
    { a: 'فَاعِلَهَا', t: 'fāʿilahā', e: 'their doer' },
    { a: 'وَمَخْصُوصَهَا،', t: 'wa-makhṣūṣahā', e: 'and their specified term' },
    { a: 'وَهِيَ', t: 'wa-hiya', e: 'and they are' },
    { a: 'خَمْسَةٌ', t: 'khamsatun', e: 'five' }, { g: ':' },
  ] },
  { t: 'line', w: [
    { a: 'الْأَوَّلُ', t: 'al-awwalu', e: 'the first' },
    { a: 'نِعْمَ،', t: 'niʿma', e: 'niʿma (how excellent)' },
    NAHW, { g: ':' }, OPEN,
    { a: 'وَلَنِعْمَ', t: 'wa-la-niʿma', e: 'and how excellent is', q: 1 },
    { a: 'دَارُ', t: 'dāru', e: 'the home of', q: 1 },
    { a: 'الْمُتَّقِينَ', t: 'al-muttaqīna', e: 'the righteous', q: 1 },
    { g: '۝' },
    { a: 'جَنَّاتُ', t: 'jannātu', e: 'Gardens of', q: 1 },
    { a: 'عَدْنٍ', t: 'ʿadnin', e: 'perpetual residence', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'الثَّانِي', t: 'ath-thānī', e: 'the second' },
    { a: 'حَبَّذَا،', t: 'ḥabbadhā', e: 'ḥabbadhā (how excellent)' },
    NAHW, { g: ':' },
    { a: 'حَبَّذَا', t: 'ḥabbadhā', e: 'how excellent is' },
    { a: 'خَالِدٌ', t: 'khālidun', e: 'Khālid' },
  ] },
  { t: 'line', w: [
    { a: 'الثَّالِثُ', t: 'ath-thālithu', e: 'the third' },
    { a: 'بِئْسَ،', t: 'biʾsa', e: 'biʾsa (how wretched)' },
  ] },
  { t: 'line', w: [
    { a: 'الرَّابِعُ', t: 'ar-rābiʿu', e: 'the fourth' },
    { a: 'سَاءَ،', t: 'sāʾa', e: 'sāʾa (how evil)' },
    NAHW, { g: ':' }, OPEN,
    { a: 'بِئْسَ', t: 'biʾsa', e: 'wretched is', q: 1 },
    { a: 'الشَّرَابُ', t: 'ash-sharābu', e: 'the drink', q: 1 },
    { a: 'وَسَاءَتْ', t: 'wa-sāʾat', e: 'and evil is it', q: 1 },
    { a: 'مُرْتَفَقًا', t: 'murtafaqan', e: 'as a resting place', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'الْخَامِسُ', t: 'al-khāmisu', e: 'the fifth' },
    { a: 'لَا', t: 'lā', e: 'lā' },
    { a: 'حَبَّذَا،', t: 'ḥabbadhā', e: 'ḥabbadhā (how wretched)' },
    NAHW, { g: ':' },
    { a: 'لَا', t: 'lā', e: 'how wretched is' },
    { a: 'حَبَّذَا', t: 'ḥabbadhā', e: '' },
    { a: 'الْكِبْرُ', t: 'al-kibru', e: 'arrogance' },
  ] },
  { t: 'box', label: 'ما يلحق بأفعال المدح والذم', labelEn: 'What is appended to praise/blame verbs', lines: [
    [
      { a: 'يُلْحَقُ', t: 'yulḥaqu', e: 'appended to them is' },
      { a: 'بِأَفْعَالِ', t: 'bi-afʿāli', e: 'the verbs of' },
      { a: 'الْمَدْحِ', t: 'al-madḥi', e: 'praise' },
      { a: 'وَالذَّمِّ', t: 'wadh-dhammi', e: 'and blame' },
      { a: 'مَا', t: 'mā', e: 'whatever' },
      { a: 'كَانَ', t: 'kāna', e: 'is' },
      { a: 'عَلَى', t: 'ʿalā', e: 'on' },
      { a: 'وَزْنِ', t: 'wazni', e: 'the pattern' },
      { a: 'فَعُلَ', t: 'faʿula', e: 'faʿula' },
      ELL,
    ],
    [
      { a: 'أَصَالَةً،', t: 'aṣālatan', e: 'originally' },
      NAHW, { g: ':' }, OPEN,
      { a: 'وَحَسُنَتْ', t: 'wa-ḥasunat', e: 'and good is it', q: 1 },
      { a: 'مُرْتَفَقًا', t: 'murtafaqan', e: 'as a resting place', q: 1 },
      CLOSE,
    ],
    [
      { a: 'أَوْ', t: 'aw', e: 'or' },
      { a: 'حُوِّلَ', t: 'ḥuwwila', e: 'transferred' },
      { a: 'إِلَيْهِ،', t: 'ilayhi', e: 'to it' },
      NAHW, { g: ':' },
      { a: 'كَتُبَ', t: 'katuba', e: 'how good a writer is' },
      { a: 'زَيْدٌ', t: 'zaydun', e: 'Zayd' },
    ],
  ] },
  { t: 'box', label: 'تأنيث فعل المدح والذم', labelEn: 'Feminizing the praise/blame verb', lines: [
    [
      { a: 'إِنْ', t: 'in', e: 'if' },
      { a: 'كَانَ', t: 'kāna', e: 'is' },
      { a: 'الْفَاعِلُ', t: 'al-fāʿilu', e: 'the doer' },
      { a: 'مُؤَنَّثًا،', t: 'muʾannathan', e: 'feminine' },
      NAHW, { g: ':' },
      { a: 'نِعْمَ', t: 'niʿma', e: 'excellent is' },
      { a: 'الْمَرْأَةُ', t: 'al-marʾatu', e: 'the woman' },
      { a: 'فَاطِمَةُ،', t: 'fāṭimatu', e: 'Fāṭima,' },
      { a: 'أَوْ', t: 'aw', e: 'or' },
      { a: 'نِعْمَتِ', t: 'niʿmati', e: 'excellent is' },
      { a: 'الْمَرْأَةُ', t: 'al-marʾatu', e: 'the woman' },
      { a: 'فَاطِمَةُ', t: 'fāṭimatu', e: 'Fāṭima' },
    ],
    [
      { a: 'أَوْ', t: 'aw', e: 'or' },
      { a: 'كَانَ', t: 'kāna', e: 'is' },
      { a: 'الْمَخْصُوصُ', t: 'al-makhṣūṣu', e: 'the specified term' },
      { a: 'مُؤَنَّثًا،', t: 'muʾannathan', e: 'feminine' },
      NAHW, { g: ':' },
      { a: 'نِعْمَتْ', t: 'niʿmat', e: 'excellent is' },
      { a: 'جَزَاءُ', t: 'jazāʾu', e: 'the reward of' },
      { a: 'الْمُتَّقِينَ', t: 'al-muttaqīna', e: 'the righteous —' },
      { a: 'الْجَنَّةُ', t: 'al-jannatu', e: 'Paradise' },
    ],
  ] },

  /* ── rules of niʿma/biʾsa ── */
  { t: 'page', n: '٣٨' },
  { t: 'box', label: 'فاعل المدح والذم', labelEn: 'The doer of the praise/blame verb', lines: [
    [
      { a: 'يَكُونُ', t: 'yakūnu', e: 'is' },
      { a: 'فَاعِلُ', t: 'fāʿilu', e: 'the doer of' },
      { a: 'أَفْعَالِ', t: 'afʿāli', e: 'the verbs of' },
      { a: 'الْمَدْحِ', t: 'al-madḥi', e: 'praise' },
      { a: 'وَالذَّمِّ', t: 'wadh-dhammi', e: 'and blame' },
      { a: 'اسْمًا', t: 'isman', e: 'a noun' },
      ELL,
    ],
    [
      { a: 'مُعَرَّفًا', t: 'muʿarrafan', e: 'made definite' },
      { a: 'بِلَامِ', t: 'bi-lāmi', e: 'by the lām of' },
      { a: 'الْجِنْسِ،', t: 'al-jinsi', e: 'genus' },
      NAHW, { g: ':' }, OPEN,
      { a: 'نِعْمَ', t: 'niʿma', e: 'excellent is', q: 1 },
      { a: 'الْعَبْدُ', t: 'al-ʿabdu', e: 'the servant', q: 1 },
      CLOSE,
    ],
    [
      { a: 'أَوْ', t: 'aw', e: 'or' },
      { a: 'مُضَافًا', t: 'muḍāfan', e: 'annexed' },
      { a: 'إِلَى', t: 'ilā', e: 'to' },
      { a: 'مُعَرَّفٍ', t: 'muʿarrafin', e: 'a definite noun' },
      { a: 'بِلَامِ', t: 'bi-lāmi', e: 'by the lām of' },
      { a: 'الْجِنْسِ،', t: 'al-jinsi', e: 'genus' },
      NAHW, { g: ':' }, OPEN,
      { a: 'نِعْمَ', t: 'niʿma', e: 'excellent is', q: 1 },
      { a: 'أَجْرُ', t: 'ajru', e: 'the reward of', q: 1 },
      { a: 'الْعَامِلِينَ', t: 'al-ʿāmilīna', e: 'the workers', q: 1 },
      CLOSE,
    ],
    [
      { a: 'أَوْ', t: 'aw', e: 'or' },
      { a: 'ضَمِيرًا', t: 'ḍamīran', e: 'a pronoun' },
      { a: 'مُسْتَتِرًا', t: 'mustatiran', e: 'hidden' },
      { a: 'مُفَسَّرًا', t: 'mufassaran', e: 'explained' },
      { a: 'بِتَمْيِيزٍ', t: 'bi-tamyīzin', e: 'by a tamyīz' },
      { a: 'مُحَوَّلٍ', t: 'muḥawwalin', e: 'transferred' },
      { a: 'عَنِ', t: 'ʿani', e: 'from' },
      { a: 'الْفَاعِلِ،', t: 'al-fāʿili', e: 'the doer' },
      NAHW, { g: ':' }, OPEN,
      { a: 'وَسَاءَتْ', t: 'wa-sāʾat', e: 'and evil is it', q: 1 },
      { a: 'مَصِيرًا', t: 'maṣīran', e: 'as a destination', q: 1 },
      CLOSE,
    ],
  ] },
  { t: 'box', label: 'ما بعد نعم وبئس', labelEn: 'mā after niʿma/biʾsa', lines: [
    [
      { a: 'قَدْ', t: 'qad', e: 'sometimes' },
      { a: 'تَقَعُ', t: 'taqaʿu', e: 'comes' },
      { a: 'كَلِمَةُ', t: 'kalimatu', e: 'the word' },
      { a: 'مَا', t: 'mā', e: 'mā' },
      { a: 'بَعْدَ', t: 'baʿda', e: 'after' },
      { a: 'نِعْمَ', t: 'niʿma', e: 'niʿma' },
      { a: 'وَبِئْسَ،', t: 'wa-biʾsa', e: 'and biʾsa' },
      NAHW, { g: ':' }, OPEN,
      { a: 'إِنْ', t: 'in', e: 'if', q: 1 },
      { a: 'تُبْدُوا', t: 'tubdū', e: 'you disclose', q: 1 },
      { a: 'الصَّدَقَاتِ', t: 'aṣ-ṣadaqāti', e: 'charities', q: 1 },
      { a: 'فَنِعِمَّا', t: 'fa-niʿimmā', e: 'then how excellent', q: 1 },
      { a: 'هِيَ', t: 'hiya', e: 'it is', q: 1 },
      CLOSE,
    ],
  ] },
  { t: 'box', label: 'حذف المخصوص', labelEn: 'Dropping the specified term', lines: [
    [
      { a: 'يُحْذَفُ', t: 'yuḥdhafu', e: 'is dropped' },
      { a: 'الْمَخْصُوصُ', t: 'al-makhṣūṣu', e: 'the specified term' },
      { a: 'إِذَا', t: 'idhā', e: 'when' },
      { a: 'دَلَّ', t: 'dalla', e: 'indicates' },
      { a: 'عَلَيْهِ', t: 'ʿalayhi', e: 'it' },
      { a: 'السِّيَاقُ،', t: 'as-siyāqu', e: 'the context' },
      NAHW, { g: ':' }, OPEN,
      { a: 'نِعْمَ', t: 'niʿma', e: 'excellent is', q: 1 },
      { a: 'الْمَوْلَى', t: 'al-mawlā', e: 'the Protector', q: 1 },
      { a: 'وَنِعْمَ', t: 'wa-niʿma', e: 'and excellent is', q: 1 },
      { a: 'النَّصِيرُ', t: 'an-naṣīru', e: 'the Helper', q: 1 },
      CLOSE,
    ],
  ] },

  /* ── ḥabbadhā rules; Division 3: forms of wonder ── */
  { t: 'page', n: '٣٩' },
  { t: 'box', label: 'دخول يا على حبذا', labelEn: 'yā entering ḥabbadhā', lines: [
    [
      { a: 'وَقَدْ', t: 'wa-qad', e: 'and sometimes' },
      { a: 'تَدْخُلُهَا', t: 'tadkhuluhā', e: 'enters it' },
      { a: 'يَا،', t: 'yā', e: 'yā' },
      NAHW, { g: ':' },
      { a: 'يَا', t: 'yā', e: 'O' },
      { a: 'حَبَّذَا', t: 'ḥabbadhā', e: 'how excellent is' },
      { a: 'مُحَمَّدٌ', t: 'muḥammadun', e: 'Muḥammad' },
      { a: 'مِنْ', t: 'min', e: 'as a' },
      { a: 'جَارِ', t: 'jāri', e: 'neighbor' },
    ],
  ] },
  { t: 'box', label: 'لزوم إفراد ذا', labelEn: 'The “dhā” stays singular & masculine', lines: [
    [
      { a: 'تَلْتَزِمُ', t: 'taltazimu', e: 'remains bound,' },
      { a: 'ذَا', t: 'dhā', e: 'the “dhā”,' },
      { a: 'الْإِفْرَادَ', t: 'al-ifrāda', e: 'to the singular' },
      { a: 'وَالتَّذْكِيرَ،', t: 'wat-tadhkīra', e: 'and the masculine' },
      NAHW, { g: ':' },
      { a: 'حَبَّذَا', t: 'ḥabbadhā', e: 'how excellent are' },
      { a: 'رِجَالًا', t: 'rijālan', e: 'as men' },
      { a: 'الْأَنْصَارُ،', t: 'al-anṣāru', e: 'the Anṣār,' },
      { a: 'وَحَبَّذَا', t: 'wa-ḥabbadhā', e: 'and how excellent' },
      { a: 'بِنْتًا', t: 'bintan', e: 'as a daughter' },
      { a: 'فَاطِمَةُ', t: 'fāṭimatu', e: 'Fāṭima' },
    ],
  ] },
  { t: 'h2', c: 'blue', ar: 'الْقِسْمُ الثَّالِثُ: صِيَغُ التَّعَجُّبِ', en: 'Third division — the forms of wonder (ṣiyagh al-taʿajjub)' },
  { t: 'line', w: [
    { a: 'وَهِيَ', t: 'wa-hiya', e: 'and they are' },
    { a: 'مَا', t: 'mā', e: 'those' },
    { a: 'وُضِعَتْ', t: 'wuḍiʿat', e: 'coined' },
    { a: 'لِلدَّلَالَةِ', t: 'lid-dalālati', e: 'to denote' },
    { a: 'عَلَى', t: 'ʿalā', e: '' },
    { a: 'التَّعَجُّبِ،', t: 'at-taʿajjubi', e: 'wonder' },
    { a: 'وَهِيَ', t: 'wa-hiya', e: 'and they are' },
    { a: 'ضَرْبَانِ', t: 'ḍarbāni', e: 'two kinds' }, { g: ':' },
  ] },
  { t: 'h2', c: 'green', ar: 'الضَّرْبُ الْأَوَّلُ: قِيَاسِيٌّ', en: 'First kind — regular (qiyāsī)' },
  { t: 'line', w: [
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
    { a: 'ثَلَاثُ', t: 'thalāthu', e: 'three' },
    { a: 'صِيَغٍ', t: 'ṣiyaghin', e: 'forms' }, { g: ':' },
  ] },
  { t: 'line', w: [
    { a: 'الْأُولَى', t: 'al-ūlā', e: 'the first' },
    { a: 'مَا', t: 'mā', e: 'mā' },
    { a: 'أَفْعَلَهُ،', t: 'afʿalahu', e: 'afʿalahu (how … he is!)' },
    NAHW, { g: ':' }, OPEN,
    { a: 'فَمَا', t: 'fa-mā', e: 'how', q: 1 },
    { a: 'أَصْبَرَهُمْ', t: 'aṣbarahum', e: 'persevering they are', q: 1 },
    { a: 'عَلَى', t: 'ʿalā', e: 'toward', q: 1 },
    { a: 'النَّارِ', t: 'an-nāri', e: 'the Fire', q: 1 },
    CLOSE,
  ] },
  { t: 'box', label: 'إعراب ما أفعله', labelEn: 'Parsing mā afʿalahu', lines: [
    [
      { a: 'فِي', t: 'fī', e: 'regarding' },
      { a: 'مَا', t: 'mā', e: 'mā' },
      { a: 'أَفْعَلَهُ', t: 'afʿalahu', e: 'afʿalahu' },
      { a: 'قَوْلَانِ', t: 'qawlāni', e: 'there are two views' }, { g: ':' },
    ],
    [
      { a: 'الْأَوَّلُ', t: 'al-awwalu', e: 'the first' },
      { a: 'أَنَّهُ', t: 'annahu', e: 'that it is' },
      { a: 'اسْتِفْهَامٌ،', t: 'istifhāmun', e: 'interrogative' },
    ],
    [
      { a: 'الثَّانِي', t: 'ath-thānī', e: 'the second' },
      { a: 'نَكِرَةٌ', t: 'nakiratun', e: 'an indefinite noun' },
      { a: 'مَوْصُوفَةٌ', t: 'mawṣūfatun', e: 'qualified' },
      { a: 'بِمَعْنَى', t: 'bi-maʿnā', e: 'meaning' },
      { a: 'شَيْءٌ', t: 'shayʾun', e: 'a thing' },
      { a: 'عَظِيمٌ', t: 'ʿaẓīmun', e: 'great' },
    ],
  ] },
  { t: 'line', w: [
    { a: 'الثَّانِيَةُ', t: 'ath-thāniyatu', e: 'the second' },
    { a: 'أَفْعِلْ', t: 'afʿil', e: 'afʿil' },
    { a: 'بِهِ،', t: 'bihi', e: 'bihi (how … he is!)' },
    NAHW, { g: ':' }, OPEN,
    { a: 'أَسْمِعْ', t: 'asmiʿ', e: 'how well they will hear', q: 1 },
    { a: 'بِهِمْ', t: 'bihim', e: '', q: 1 },
    { a: 'وَأَبْصِرْ', t: 'wa-abṣir', e: 'and how well they will see', q: 1 },
    CLOSE,
  ] },
  { t: 'box', label: 'إعراب أفعل به', labelEn: 'Parsing afʿil bihi', lines: [
    [
      { a: 'أَفْعِلْ', t: 'afʿil', e: 'afʿil' },
      { a: 'بِهِ', t: 'bihi', e: 'bihi' },
      { a: 'أَصْلُهُ', t: 'aṣluhu', e: 'is originally' },
      { a: 'أَفْعَلَ،', t: 'afʿala', e: 'afʿala' },
      { a: 'فَغُيِّرَ', t: 'fa-ghuyyira', e: 'then changed' },
      { a: 'مِنَ', t: 'mina', e: 'from' },
      { a: 'الْمَاضِي', t: 'al-māḍī', e: 'the past' },
      { a: 'إِلَى', t: 'ilā', e: 'to' },
      { a: 'الْأَمْرِ،', t: 'al-amri', e: 'the command form' },
      { a: 'ثُمَّ', t: 'thumma', e: 'then' },
      { a: 'زِيدَتِ', t: 'zīdati', e: 'was added' },
      { a: 'الْبَاءُ', t: 'al-bāʾu', e: 'the bāʾ' },
      { a: 'فِي', t: 'fī', e: 'to' },
      { a: 'الْفَاعِلِ', t: 'al-fāʿili', e: 'the doer' },
      { a: 'لِأَنَّ', t: 'li-anna', e: 'because' },
      { a: 'إِسْنَادَ', t: 'isnāda', e: 'predicating' },
      { a: 'الْأَمْرِ', t: 'al-amri', e: 'a command' },
      { a: 'إِلَى', t: 'ilā', e: 'to' },
      { a: 'اسْمٍ', t: 'ismin', e: 'an overt noun' },
      { a: 'ظَاهِرٍ', t: 'ẓāhirin', e: '' },
      { a: 'قَبِيحٌ', t: 'qabīḥun', e: 'is ugly' },
    ],
  ] },
  { t: 'line', w: [
    { a: 'الثَّالِثَةُ', t: 'ath-thālithatu', e: 'the third' },
    { a: 'فَعُلَ', t: 'faʿula', e: 'faʿula' },
    { a: 'الْأَصْلِيُّ', t: 'al-aṣliyyu', e: 'original' },
    { a: 'أَوِ', t: 'awi', e: 'or' },
    { a: 'الْمُحَوَّلُ،', t: 'al-muḥawwalu', e: 'transferred' },
    NAHW, { g: ':' }, OPEN,
    { a: 'كَبُرَتْ', t: 'kaburat', e: 'grave is it', q: 1 },
    { a: 'كَلِمَةً', t: 'kalimatan', e: 'as a word', q: 1 },
    { a: 'تَخْرُجُ', t: 'takhruju', e: 'coming out', q: 1 },
    { a: 'مِنْ', t: 'min', e: 'of', q: 1 },
    { a: 'أَفْوَاهِهِمْ', t: 'afwāhihim', e: 'their mouths', q: 1 },
    CLOSE,
  ] },

  /* ── the heard forms of wonder ── */
  { t: 'page', n: '٤٠' },
  { t: 'h2', c: 'green', ar: 'الضَّرْبُ الثَّانِي: سَمَاعِيٌّ', en: 'Second kind — heard (samāʿī)' },
  { t: 'line', w: [
    { a: 'مِنْهَا', t: 'minhā', e: 'among them' },
    ELL,
  ] },
  { t: 'line', w: [
    { a: 'سُبْحَانَ', t: 'subḥāna', e: 'subḥāna' },
    { a: 'اللهِ،', t: 'llāhi', e: 'llāh (glory be to God!)' },
    NAHW, { g: ':' }, OPEN,
    { a: 'قَالَ', t: 'qāla', e: 'he said', q: 1 },
    { a: 'سُبْحَانَكَ', t: 'subḥānaka', e: 'glory be to You', q: 1 },
    { a: 'مَا', t: 'mā', e: 'it is not', q: 1 },
    { a: 'يَكُونُ', t: 'yakūnu', e: '', q: 1 },
    { a: 'لِي', t: 'lī', e: 'for me', q: 1 },
    { a: 'أَنْ', t: 'an', e: 'to', q: 1 },
    { a: 'أَقُولَ', t: 'aqūla', e: 'say', q: 1 },
    { a: 'مَا', t: 'mā', e: 'what', q: 1 },
    { a: 'لَيْسَ', t: 'laysa', e: 'is not', q: 1 },
    { a: 'لِي', t: 'lī', e: 'mine', q: 1 },
    { a: 'بِحَقٍّ', t: 'bi-ḥaqqin', e: 'by right', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'وَالِاسْتِفْهَامُ،', t: 'wal-istifhāmu', e: 'and interrogation' },
    NAHW, { g: ':' }, OPEN,
    { a: 'كَيْفَ', t: 'kayfa', e: 'how', q: 1 },
    { a: 'تَكْفُرُونَ', t: 'takfurūna', e: 'can you disbelieve', q: 1 },
    { a: 'بِاللهِ', t: 'bi-llāhi', e: 'in Allah', q: 1 },
    { a: 'وَكُنْتُمْ', t: 'wa-kuntum', e: 'when you were', q: 1 },
    { a: 'أَمْوَاتًا', t: 'amwātan', e: 'dead', q: 1 },
    { a: 'فَأَحْيَاكُمْ', t: 'fa-aḥyākum', e: 'and He gave you life', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'وَالنِّدَاءُ،', t: 'wan-nidāʾu', e: 'and calling' },
    NAHW, { g: ':' }, OPEN,
    { a: 'يَا', t: 'yā', e: 'O', q: 1 },
    { a: 'بُشْرَى', t: 'bushrā', e: 'good news', q: 1 },
    { a: 'هَذَا', t: 'hādhā', e: 'here is', q: 1 },
    { a: 'غُلَامٌ', t: 'ghulāmun', e: 'a boy', q: 1 },
    CLOSE,
  ] },
];
