/* ── al-Kubrā fī an-Naḥw — المقصد الثاني في المعمول وغير المعمول (pp. 138–150) ──
   Continuation of `maqsad2a.js` (pp. 130–137). Picks up mid-ظرف الزمان and runs
   through: ظرف المكان · المفعول له · المفعول معه · الحال · التمييز · المستثنى ·
   خبر الأفعال الناقصة · خبر الحروف المشبهة بليس · اسم الحروف المشبهة بالفعل ·
   اسم لا لنفي الجنس. Shared glyphs (OPEN/CLOSE/NAHW/ELL) come from muqaddimah.js.
   مسألة/فائدة footnotes at the page foot are omitted (p.10-onward rule).          */

const DATA_M2B = [
  { t: 'page', n: '١٣٨' },
  { t: 'box', lines: [
    [ { a: 'النَّصْبُ', t: 'an-naṣbu', e: 'the accusative' }, { a: 'بِحَرْفِ', t: 'bi-ḥarfi', e: 'by a particle of' }, { a: 'جَرٍّ', t: 'jarrin', e: 'the genitive' }, { a: 'مُقَدَّرٍ،', t: 'muqaddarin', e: 'implicit' },
      NAHW, { g: ':' }, OPEN, { a: 'وَلَا', t: 'wa-lā', e: 'and do not', q: 1 }, { a: 'تُخْزِنَا', t: 'tukhzinā', e: 'disgrace us', q: 1 }, { a: 'يَوْمَ', t: 'yawma', e: 'on the Day of', q: 1 }, { a: 'الْقِيَامَةِ', t: 'al-qiyāmati', e: 'Resurrection', q: 1 }, CLOSE ],
    [ { a: 'وَالْجَرُّ', t: 'wa-l-jarru', e: 'and the genitive' }, { a: 'بِحَرْفِ', t: 'bi-ḥarfi', e: 'by a particle of' }, { a: 'جَرٍّ', t: 'jarrin', e: 'the genitive' }, { a: 'ظَاهِرٍ،', t: 'ẓāhirin', e: 'overt' },
      NAHW, { g: ':' }, OPEN, { a: 'يَجْمَعُكُمْ', t: 'yajmaʿukum', e: 'He will gather you', q: 1 }, { a: 'إِلَى', t: 'ilā', e: 'unto', q: 1 }, { a: 'يَوْمِ', t: 'yawmi', e: 'the Day of', q: 1 }, { a: 'الْقِيَامَةِ', t: 'al-qiyāmati', e: 'Resurrection', q: 1 }, CLOSE ],
  ] },
  { t: 'box', label: 'ظرف المكان', labelEn: 'the adverbial of place', lines: [
    [ { a: 'ظَرْفُ', t: 'ẓarfu', e: 'the adverbial of' }, { a: 'الْمَكَانِ', t: 'al-makāni', e: 'place' }, { a: 'نَوْعَانِ', t: 'nawʿāni', e: 'is two types' }, { g: ':' } ],
    [ { a: 'الْأَوَّلُ', t: 'al-awwalu', e: 'the first', c: 'red' }, { a: 'مُبْهَمٌ،', t: 'mubhamun', e: 'vague' }, { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' }, { a: 'مَا', t: 'mā', e: 'what' }, { a: 'دَلَّ', t: 'dalla', e: 'denotes' }, { a: 'عَلَى', t: 'ʿalā', e: '' }, { a: 'مَكَانٍ', t: 'makānin', e: 'a place' }, { a: 'غَيْرِ', t: 'ghayri', e: 'not' }, { a: 'مُعَيَّنٍ،', t: 'muʿayyanin', e: 'specified' },
      { a: 'مِثْلُ', t: 'mithlu', e: 'like' }, { a: 'الْجِهَاتِ', t: 'al-jihāti', e: 'the directions' }, { a: 'السِّتِّ', t: 'as-sitti', e: 'six' }, { a: 'وَالْمَقَادِيرِ', t: 'wa-l-maqādīri', e: 'and the measures' }, { a: 'كَمِيلٍ', t: 'ka-mīlin', e: 'like “mile”' }, { a: 'وَفَرْسَخٍ،', t: 'wa-farsakhin', e: 'and “league”' },
      { a: 'وَيَجُوزُ', t: 'wa-yajūzu', e: 'and permitted' }, { a: 'فِيهِ', t: 'fīhi', e: 'in it' }, ELL ],
    [ { a: 'النَّصْبُ', t: 'an-naṣbu', e: 'the accusative' }, { a: 'بِحَرْفِ', t: 'bi-ḥarfi', e: 'by a particle of' }, { a: 'جَرٍّ', t: 'jarrin', e: 'the genitive' }, { a: 'مُقَدَّرٍ،', t: 'muqaddarin', e: 'implicit' },
      NAHW, { g: ':' }, OPEN, { a: 'لِتَكُونَ', t: 'li-takūna', e: 'that you may be', q: 1 }, { a: 'لِمَنْ', t: 'li-man', e: 'for those', q: 1 }, { a: 'خَلْفَكَ', t: 'khalfaka', e: 'behind you', q: 1 }, { a: 'آيَةً', t: 'āyatan', e: 'a sign', q: 1 }, CLOSE ],
    [ { a: 'وَالْجَرُّ', t: 'wa-l-jarru', e: 'and the genitive' }, { a: 'بِحَرْفِ', t: 'bi-ḥarfi', e: 'by a particle of' }, { a: 'جَرٍّ', t: 'jarrin', e: 'the genitive' }, { a: 'ظَاهِرٍ،', t: 'ẓāhirin', e: 'overt' },
      NAHW, { g: ':' }, OPEN, { a: 'لَوْ', t: 'law', e: 'if', q: 1 }, { a: 'تَرَكُوا', t: 'tarakū', e: 'they left', q: 1 }, { a: 'مِنْ', t: 'min', e: '', q: 1 }, { a: 'خَلْفِهِمْ', t: 'khalfihim', e: 'behind them', q: 1 }, { a: 'ذُرِّيَّةً', t: 'dhurriyyatan', e: 'offspring', q: 1 }, { a: 'ضِعَافًا', t: 'ḍiʿāfan', e: 'weak', q: 1 }, CLOSE ],
    [ { a: 'الثَّانِي', t: 'ath-thānī', e: 'the second', c: 'red' }, { a: 'مَحْدُودٌ،', t: 'maḥdūdun', e: 'delimited' }, { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' }, { a: 'مَا', t: 'mā', e: 'what' }, { a: 'دَلَّ', t: 'dalla', e: 'denotes' }, { a: 'عَلَى', t: 'ʿalā', e: '' }, { a: 'مَكَانٍ', t: 'makānin', e: 'a place' }, { a: 'مُعَيَّنٍ،', t: 'muʿayyanin', e: 'specified' } ],
    [ { a: 'وَيَجُوزُ', t: 'wa-yajūzu', e: 'and permitted' }, { a: 'فِيهِ', t: 'fīhi', e: 'in it' }, ELL ],
    [ { a: 'الْجَرُّ', t: 'al-jarru', e: 'the genitive' }, { a: 'بِحَرْفِ', t: 'bi-ḥarfi', e: 'by a particle of' }, { a: 'جَرٍّ', t: 'jarrin', e: 'the genitive' }, { a: 'ظَاهِرٍ،', t: 'ẓāhirin', e: 'overt' },
      NAHW, { g: ':' }, OPEN, { a: 'لَا', t: 'lā', e: 'do not', q: 1 }, { a: 'تُفْسِدُوا', t: 'tufsidū', e: 'spread corruption', q: 1 }, { a: 'فِي', t: 'fī', e: 'in', q: 1 }, { a: 'الْأَرْضِ', t: 'al-arḍi', e: 'the earth', q: 1 }, CLOSE ],
    [ { a: 'وَالنَّصْبُ', t: 'wa-n-naṣbu', e: 'and the accusative' }, { a: 'بِحَرْفِ', t: 'bi-ḥarfi', e: 'by a particle of' }, { a: 'جَرٍّ', t: 'jarrin', e: 'the genitive' }, { a: 'مُقَدَّرٍ', t: 'muqaddarin', e: 'implicit' }, { a: 'فِي', t: 'fī', e: 'in' }, { a: 'مَوْضِعَيْنِ', t: 'mawḍiʿayni', e: 'two places' } ],
    [ { a: 'الْأَوَّلُ', t: 'al-awwalu', e: 'the first', c: 'red' }, { a: 'إِذَا', t: 'idhā', e: 'when' }, { a: 'كَانَ', t: 'kāna', e: 'it is' }, { a: 'مُشْتَقًّا', t: 'mushtaqqan', e: 'derived' }, { a: 'مِنَ', t: 'mina', e: 'from' }, { a: 'الْفِعْلِ،', t: 'al-fiʿli', e: 'the verb' },
      NAHW, { g: ':' }, OPEN, { a: 'كُنَّا', t: 'kunnā', e: 'we used to', q: 1 }, { a: 'نَقْعُدُ', t: 'naqʿudu', e: 'sit', q: 1 }, { a: 'مِنْهَا', t: 'minhā', e: 'therein', q: 1 }, { a: 'مَقَاعِدَ', t: 'maqāʿida', e: 'in seats', q: 1 }, { a: 'لِلسَّمْعِ', t: 'li-s-samʿi', e: 'to listen', q: 1 }, CLOSE ],
    [ { a: 'الثَّانِي', t: 'ath-thānī', e: 'the second', c: 'red' }, { a: 'فِي', t: 'fī', e: 'with' }, { a: 'أَفْعَالٍ', t: 'afʿālin', e: 'verbs' }, { a: 'مَخْصُوصَةٍ،', t: 'makhṣūṣatin', e: 'specific' }, { a: 'مِثْلُ', t: 'mithlu', e: 'like' }, ELL ],
    [ { a: 'الدُّخُولِ،', t: 'ad-dukhūli', e: 'entering' }, NAHW, { g: ':' },
      OPEN, { a: 'فَأُولَئِكَ', t: 'fa-ulāʾika', e: 'so those', q: 1 }, { a: 'يَدْخُلُونَ', t: 'yadkhulūna', e: 'will enter', q: 1 }, { a: 'الْجَنَّةَ', t: 'al-jannata', e: 'Paradise', q: 1 }, CLOSE ],
    [ { a: 'وَالسُّكُونِ،', t: 'wa-s-sukūni', e: 'and dwelling' }, NAHW, { g: ':' },
      OPEN, { a: 'اسْكُنْ', t: 'uskun', e: 'dwell', q: 1 }, { a: 'أَنْتَ', t: 'anta', e: 'you', q: 1 }, { a: 'وَزَوْجُكَ', t: 'wa-zawjuka', e: 'and your spouse', q: 1 }, { a: 'الْجَنَّةَ', t: 'al-jannata', e: 'in the Garden', q: 1 }, CLOSE ],
    [ { a: 'وَالنُّزُولِ،', t: 'wa-n-nuzūli', e: 'and alighting' }, NAHW, { g: ':' },
      { a: 'نَزَلَ', t: 'nazala', e: 'he alighted at' }, { a: 'الْمَدِينَةَ', t: 'al-madīnata', e: 'Madīnah' } ],
  ] },
  { t: 'grid',
    cols: ['مُبْهَمٌ · زَمَانٌ', 'مَحْدُودٌ · زَمَانٌ', 'مُبْهَمٌ · مَكَانٌ', 'مَحْدُودٌ · مَكَانٌ'],
    rows: [
      { h: 'حَرْفُ جَرٍّ مُقَدَّرٍ', c: ['حِينًا', 'يَوْمَ الْقِيَامَةِ', 'خَلْفَهُ', '✗'] },
      { h: 'حَرْفُ جَرٍّ ظَاهِرٍ', c: ['إِلَى حِينٍ', 'فِي يَوْمِ الْقِيَامَةِ', 'مِنْ خَلْفِهِ', 'فِي الْأَرْضِ'] },
    ],
    caption: 'Vague adverbials take either an implicit or an overt preposition; a delimited place-adverbial takes only the overt one.' },

  { t: 'page', n: '١٣٩' },
  { t: 'box', label: 'ما يقوم مقام المفعول فيه', labelEn: 'what stands in for the adverbial object', lines: [
    [ { a: 'وَيَقُومُ', t: 'wa-yaqūmu', e: 'and stands' }, { a: 'مَقَامَ', t: 'maqāma', e: 'in the place of' }, { a: 'الْمَفْعُولِ', t: 'al-mafʿūli', e: 'the object' }, { a: 'فِيهِ', t: 'fīhi', e: 'within which' }, ELL ],
    [ { a: 'الْمَصْدَرُ،', t: 'al-maṣdaru', e: 'the verbal noun' }, NAHW, { g: ':' },
      OPEN, { a: 'وَمِنَ', t: 'wa-mina', e: 'and during', q: 1 }, { a: 'اللَّيْلِ', t: 'al-layli', e: 'the night', q: 1 }, { a: 'فَسَبِّحْهُ', t: 'fa-sabbiḥhu', e: 'glorify Him', q: 1 }, { a: 'وَإِدْبَارَ', t: 'wa-idbāra', e: 'and at the setting of', q: 1 }, { a: 'النُّجُومِ', t: 'an-nujūmi', e: 'the stars', q: 1 }, CLOSE ],
    [ { a: 'وَالْمُضَافُ', t: 'wa-l-muḍāfu', e: 'and what is annexed' }, ELL ],
    [ { a: 'إِلَى', t: 'ilā', e: 'to' }, { a: 'الزَّمَانِ،', t: 'az-zamāni', e: 'a time' }, NAHW, { g: ':' },
      OPEN, { a: 'قَالَ', t: 'qāla', e: 'he said', q: 1 }, { a: 'لَبِثْتُ', t: 'labithtu', e: 'I remained', q: 1 }, { a: 'يَوْمًا', t: 'yawman', e: 'a day', q: 1 }, { a: 'أَوْ', t: 'aw', e: 'or', q: 1 }, { a: 'بَعْضَ', t: 'baʿḍa', e: 'part of', q: 1 }, { a: 'يَوْمٍ', t: 'yawmin', e: 'a day', q: 1 }, CLOSE ],
    [ { a: 'وَمَا', t: 'wa-mā', e: 'and what' }, { a: 'يَدُلُّ', t: 'yadullu', e: 'denotes' }, { a: 'عَلَى', t: 'ʿalā', e: '' }, { a: 'الْعَدَدِ،', t: 'al-ʿadadi', e: 'number' }, NAHW, { g: ':' },
      OPEN, { a: 'آيَتُكَ', t: 'āyatuka', e: 'your sign is', q: 1 }, { a: 'أَلَّا', t: 'allā', e: 'that you will not', q: 1 }, { a: 'تُكَلِّمَ', t: 'tukallima', e: 'speak to', q: 1 }, { a: 'النَّاسَ', t: 'an-nāsa', e: 'the people', q: 1 }, { a: 'ثَلَاثَ', t: 'thalātha', e: 'for three', q: 1 }, { a: 'لَيَالٍ', t: 'layālin', e: 'nights', q: 1 }, CLOSE ],
  ] },
  { t: 'h2', c: 'red', ar: 'الرَّابِعُ: الْمَفْعُولُ لَهُ', en: 'Fourth — the Object of Purpose (mafʿūl lahu)' },
  { t: 'line', w: [
    { a: 'الرَّابِعُ', t: 'ar-rābiʿu', e: 'the fourth (is)' }, { a: 'الْمَفْعُولُ', t: 'al-mafʿūlu', e: 'the object' }, { a: 'لَهُ،', t: 'lahu', e: 'for which' },
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' }, { a: 'مَا', t: 'mā', e: 'what' }, { a: 'وَقَعَ', t: 'waqaʿa', e: 'occurred' }, { a: 'لِأَجْلِهِ', t: 'li-ajlihi', e: 'for its sake' }, { a: 'الْفِعْلُ،', t: 'al-fiʿlu', e: 'the action' },
    NAHW, { g: ':' }, OPEN, { a: 'وَالَّذِينَ', t: 'wa-lladhīna', e: 'and those who', q: 1 }, { a: 'صَبَرُوا', t: 'ṣabarū', e: 'were patient', q: 1 }, { a: 'ابْتِغَاءَ', t: 'ibtighāʾa', e: 'seeking', q: 1 }, { a: 'وَجْهِ', t: 'wajhi', e: 'the Face of', q: 1 }, { a: 'رَبِّهِمْ', t: 'rabbihim', e: 'their Lord', q: 1 }, CLOSE,
  ] },
  { t: 'box', label: 'مسألة', labelEn: 'point', lines: [
    [ { a: 'يُسَمَّى', t: 'yusammā', e: 'is called' }, { a: 'الْمَفْعُولُ', t: 'al-mafʿūlu', e: 'the object' }, { a: 'لَهُ', t: 'lahu', e: 'for which' }, { a: 'مَفْعُولًا', t: 'mafʿūlan', e: 'an object' }, { a: 'لِأَجْلِهِ', t: 'li-ajlihi', e: 'for whose sake' } ],
  ] },
  { t: 'box', label: 'شروط نصب المفعول له بلا واسطة اللام', labelEn: 'conditions for taking naṣb without the lām', lines: [
    [ { a: 'وَيُشْتَرَطُ', t: 'wa-yushtaraṭu', e: 'and it is required' }, { a: 'لِنَصْبِهِ', t: 'li-naṣbihi', e: 'for its accusative' }, { a: 'أَنْ', t: 'an', e: 'that' }, { a: 'يَكُونَ', t: 'yakūna', e: 'it be' }, ELL ],
    [ { a: 'مَصْدَرًا،', t: 'maṣdaran', e: 'a verbal noun' }, { a: 'بِخِلَافِ', t: 'bi-khilāfi', e: 'unlike' }, { g: ':' },
      OPEN, { a: 'وَالْأَرْضَ', t: 'wa-l-arḍa', e: 'and the earth', q: 1 }, { a: 'وَضَعَهَا', t: 'waḍaʿahā', e: 'He laid it out', q: 1 }, { a: 'لِلْأَنَامِ', t: 'li-l-anāmi', e: 'for the creatures', q: 1 }, CLOSE ],
    [ { a: 'وَقَلْبِيًّا،', t: 'wa-qalbiyyan', e: 'and of the heart (an inner act)' }, { a: 'بِخِلَافِ', t: 'bi-khilāfi', e: 'unlike' }, { g: ':' },
      { a: 'سَافَرْتُ', t: 'sāfartu', e: 'I travelled' }, { a: 'إِلَى', t: 'ilā', e: 'to' }, { a: 'مَكَّةَ', t: 'makkata', e: 'Makkah' }, { a: 'لِلْحَجِّ', t: 'li-l-ḥajji', e: 'for the ḥajj' } ],
    [ { a: 'وَأَنْ', t: 'wa-an', e: 'and that' }, { a: 'يَكُونَ', t: 'yakūna', e: 'be' }, { a: 'فَاعِلُ', t: 'fāʿilu', e: 'the agent of' }, { a: 'الْفِعْلِ', t: 'al-fiʿli', e: 'the verb' }, { a: 'وَالْمَصْدَرِ', t: 'wa-l-maṣdari', e: 'and of the verbal noun' }, { a: 'مُتَّحِدًا،', t: 'muttaḥidan', e: 'one and the same' },
      { a: 'بِخِلَافِ', t: 'bi-khilāfi', e: 'unlike' }, { g: ':' },
      OPEN, { a: 'وَالْأَنْعَامَ', t: 'wa-l-anʿāma', e: 'and the cattle', q: 1 }, { a: 'خَلَقَهَا', t: 'khalaqahā', e: 'He created them', q: 1 }, { a: 'لَكُمْ', t: 'lakum', e: 'for you', q: 1 }, ELL,
      { a: 'وَالْخَيْلَ', t: 'wa-l-khayla', e: 'and the horses', q: 1 }, { a: 'وَالْبِغَالَ', t: 'wa-l-bighāla', e: 'and the mules', q: 1 }, { a: 'وَالْحَمِيرَ', t: 'wa-l-ḥamīra', e: 'and the donkeys', q: 1 }, { a: 'لِتَرْكَبُوهَا', t: 'li-tarkabūhā', e: 'that you may ride them', q: 1 }, { a: 'وَزِينَةً', t: 'wa-zīnatan', e: 'and as adornment', q: 1 }, CLOSE ],
    [ { a: 'وَأَنْ', t: 'wa-an', e: 'and that' }, { a: 'يَكُونَ', t: 'yakūna', e: 'be' }, { a: 'زَمَنُ', t: 'zamanu', e: 'the time of' }, { a: 'الْفِعْلِ', t: 'al-fiʿli', e: 'the verb' }, { a: 'وَالْمَصْدَرِ', t: 'wa-l-maṣdari', e: 'and of the verbal noun' }, { a: 'وَاحِدًا،', t: 'wāḥidan', e: 'one' },
      { a: 'بِخِلَافِ', t: 'bi-khilāfi', e: 'unlike' }, { g: ':' },
      { a: 'أَرْحَمُ', t: 'arḥamu', e: 'I show mercy to' }, { a: 'وَالِدَيَّ', t: 'wālidayya', e: 'my parents' }, { a: 'كِبَرًا', t: 'kibaran', e: 'in old age' }, { a: 'لِرَحْمَتِهِ', t: 'li-raḥmatihi', e: 'because of his mercy' }, { a: 'إِيَّايَ', t: 'iyyāya', e: 'to me' }, { a: 'صَغِيرًا', t: 'ṣaghīran', e: 'when small' } ],
  ] },
  { t: 'box', label: 'مسألة', labelEn: 'point', lines: [
    [ { a: 'قَدْ', t: 'qad', e: 'sometimes' }, { a: 'يَكُونُ', t: 'yakūnu', e: 'is' }, { a: 'الْمَصْدَرُ', t: 'al-maṣdaru', e: 'the verbal noun' }, { a: 'الْمُؤَوَّلُ', t: 'al-muʾawwalu', e: 'construed (an + verb)' }, { a: 'مَفْعُولًا', t: 'mafʿūlan', e: 'an object' }, { a: 'لَهُ', t: 'lahu', e: 'of purpose' },
      { a: 'بِتَقْدِيرِ', t: 'bi-taqdīri', e: 'by supplying' }, { a: 'الْمُضَافِ،', t: 'al-muḍāfi', e: 'the annexed noun' }, NAHW, { g: ':' },
      OPEN, { a: 'وَأَلْقَى', t: 'wa-alqā', e: 'and He cast', q: 1 }, { a: 'فِي', t: 'fī', e: 'in', q: 1 }, { a: 'الْأَرْضِ', t: 'al-arḍi', e: 'the earth', q: 1 }, { a: 'رَوَاسِيَ', t: 'rawāsiya', e: 'firm mountains', q: 1 }, { a: 'أَنْ', t: 'an', e: 'lest', q: 1 }, { a: 'تَمِيدَ', t: 'tamīda', e: 'it sway', q: 1 }, { a: 'بِكُمْ', t: 'bikum', e: 'with you', q: 1 }, CLOSE,
      { a: 'أَيْ', t: 'ay', e: 'i.e.' }, { a: 'كَرَاهَةَ', t: 'karāhata', e: 'out of dislike' }, { a: 'أَنْ', t: 'an', e: 'that' }, { a: 'تَمِيدَ', t: 'tamīda', e: 'it sway' }, { a: 'بِكُمْ', t: 'bikum', e: 'with you' } ],
  ] },
  { t: 'h2', c: 'red', ar: 'الْخَامِسُ: الْمَفْعُولُ مَعَهُ', en: 'Fifth — the Object of Accompaniment (mafʿūl maʿahu)' },

  { t: 'page', n: '١٤٠' },
  { t: 'line', w: [
    { a: 'الْخَامِسُ', t: 'al-khāmisu', e: 'the fifth (is)' }, { a: 'الْمَفْعُولُ', t: 'al-mafʿūlu', e: 'the object' }, { a: 'مَعَهُ،', t: 'maʿahu', e: 'along with which' },
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' }, { a: 'مَا', t: 'mā', e: 'what' }, { a: 'وَقَعَ', t: 'waqaʿa', e: 'occurred' }, { a: 'مَعَهُ', t: 'maʿahu', e: 'together with it' }, { a: 'الْفِعْلُ،', t: 'al-fiʿlu', e: 'the action' },
    NAHW, { g: ':' }, { a: 'يَفْنَى', t: 'yafnā', e: 'perishes' }, { a: 'الْمَالُ', t: 'al-mālu', e: 'wealth' }, { a: 'وَيَبْقَى', t: 'wa-yabqā', e: 'and there remains' }, { a: 'ابْنُ', t: 'ibnu', e: 'the son of' }, { a: 'آدَمَ', t: 'ādama', e: 'Ādam' }, { a: 'وَعَمَلَهُ', t: 'wa-ʿamalahu', e: 'along with his deeds' },
  ] },
  { t: 'box', label: 'شروط المفعول معه', labelEn: 'conditions for the mafʿūl maʿahu', lines: [
    [ { a: 'يُشْتَرَطُ', t: 'yushtaraṭu', e: 'it is required' }, { a: 'أَنْ', t: 'an', e: 'that' }, { a: 'تَكُونَ', t: 'takūna', e: 'there be' }, { a: 'قَبْلَهُ', t: 'qablahu', e: 'before it' }, { a: 'جُمْلَةٌ', t: 'jumlatun', e: 'a clause' }, { a: 'فِيهَا', t: 'fīhā', e: 'containing' }, { a: 'فِعْلٌ', t: 'fiʿlun', e: 'a verb' }, { a: 'أَوْ', t: 'aw', e: 'or' }, { a: 'شِبْهُ', t: 'shibhu', e: 'a quasi-' }, { a: 'فِعْلٍ،', t: 'fiʿlin', e: 'verb' },
      NAHW, { g: ':' }, { a: 'أَنَا', t: 'anā', e: 'I (am)' }, { a: 'سَائِرٌ', t: 'sāʾirun', e: 'walking' }, { a: 'وَالنَّهْرَ،', t: 'wa-n-nahra', e: 'along with the river' },
      { a: 'بِخِلَافِ', t: 'bi-khilāfi', e: 'unlike' }, { g: ':' }, { a: 'كُلُّ', t: 'kullu', e: 'every' }, { a: 'امْرِئٍ', t: 'imriʾin', e: 'man' }, { a: 'وَشَأْنُهُ', t: 'wa-shaʾnuhu', e: 'and his own affair' } ],
  ] },
  { t: 'box', label: 'مسألة', labelEn: 'point', lines: [
    [ { a: 'يَجِبُ', t: 'yajibu', e: 'it is obligatory' }, { a: 'النَّصْبُ', t: 'an-naṣbu', e: 'the accusative' }, { a: 'إِنْ', t: 'in', e: 'if' }, { a: 'لَمْ', t: 'lam', e: 'not' }, { a: 'يَجُزِ', t: 'yajuzi', e: 'is permitted' }, { a: 'الْعَطْفُ،', t: 'al-ʿaṭfu', e: 'conjunction' },
      NAHW, { g: ':' }, { g: '«' }, { a: 'بُعِثْتُ', t: 'buʿithtu', e: 'I was sent' }, { a: 'وَالسَّاعَةَ', t: 'wa-s-sāʿata', e: 'together with the Hour' }, { a: 'كَهَاتَيْنِ', t: 'ka-hātayni', e: 'like these two' }, { g: '»' } ],
    [ { a: 'وَمَهْمَا', t: 'wa-mahmā', e: 'and whenever' }, { a: 'جَازَ', t: 'jāza', e: 'is permitted' }, { a: 'الْعَطْفُ', t: 'al-ʿaṭfu', e: 'conjunction' }, { a: 'جَازَ', t: 'jāza', e: 'both are permitted' }, { a: 'الْوَجْهَانِ،', t: 'al-wajhāni', e: 'the two ways' },
      NAHW, { g: ':' }, { a: 'حَضَرَ', t: 'ḥaḍara', e: 'came' }, { a: 'الْأَبُ', t: 'al-abu', e: 'the father' }, { a: 'وَوَلَدُهُ', t: 'wa-waladuhu', e: 'and his son' } ],
  ] },
  { t: 'h2', c: 'red', ar: 'السَّادِسُ: الْحَالُ', en: 'Sixth — the Circumstantial Qualifier (ḥāl)' },
  { t: 'line', w: [
    { a: 'السَّادِسُ', t: 'as-sādisu', e: 'the sixth (is)' }, { a: 'الْحَالُ،', t: 'al-ḥālu', e: 'the ḥāl' },
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' }, { a: 'مَا', t: 'mā', e: 'what' }, { a: 'يُبَيِّنُ', t: 'yubayyinu', e: 'clarifies' }, { a: 'هَيْئَةً', t: 'hayʾatan', e: 'the state of' }, ELL,
  ] },
  { t: 'box', lines: [
    [ { a: 'الْفَاعِلِ،', t: 'al-fāʿili', e: 'the agent' }, NAHW, { g: ':' },
      OPEN, { a: 'وَادْعُوهُ', t: 'wa-dʿūhu', e: 'and call upon Him', q: 1 }, { a: 'مُخْلِصِينَ', t: 'mukhliṣīna', e: 'sincere', q: 1 }, { a: 'لَهُ', t: 'lahu', e: 'to Him', q: 1 }, { a: 'الدِّينَ', t: 'ad-dīna', e: 'in religion', q: 1 }, CLOSE ],
    [ { a: 'أَوِ', t: 'awi', e: 'or' }, { a: 'الْمَفْعُولِ', t: 'al-mafʿūli', e: 'the object' }, { a: 'بِهِ،', t: 'bihi', e: 'acted upon' }, NAHW, { g: ':' },
      OPEN, { a: 'إِنَّا', t: 'innā', e: 'indeed We', q: 1 }, { a: 'أَرْسَلْنَاكَ', t: 'arsalnāka', e: 'sent you', q: 1 }, { a: 'بِالْحَقِّ', t: 'bi-l-ḥaqqi', e: 'with the truth', q: 1 }, { a: 'بَشِيرًا', t: 'bashīran', e: 'as a bearer of glad tidings', q: 1 }, { a: 'وَنَذِيرًا', t: 'wa-nadhīran', e: 'and a warner', q: 1 }, CLOSE ],
    [ { a: 'أَوْ', t: 'aw', e: 'or' }, { a: 'غَيْرِهِمَا،', t: 'ghayrihimā', e: 'other than those two' }, NAHW, { g: ':' },
      OPEN, { a: 'إِلَى', t: 'ilā', e: 'to', q: 1 }, { a: 'اللهِ', t: 'Allāhi', e: 'Allah', q: 1 }, { a: 'مَرْجِعُكُمْ', t: 'marjiʿukum', e: 'is your return', q: 1 }, { a: 'جَمِيعًا', t: 'jamīʿan', e: 'all together', q: 1 }, CLOSE ],
  ] },
  { t: 'box', label: 'صاحب الحال', labelEn: 'the subject of the ḥāl', lines: [
    [ { a: 'لَا', t: 'lā', e: 'there is no' }, { a: 'بُدَّ', t: 'budda', e: 'escape' }, { a: 'لِلْحَالِ', t: 'li-l-ḥāli', e: 'for the ḥāl' }, { a: 'مِنْ', t: 'min', e: 'from' }, { a: 'صَاحِبِ', t: 'ṣāḥibi', e: 'an owner of' }, { a: 'حَالٍ،', t: 'ḥālin', e: 'the state' },
      { a: 'وَيُسَمَّى', t: 'wa-yusammā', e: 'and it is called' }, { a: 'ذَا', t: 'dhā', e: 'the possessor of' }, { a: 'حَالٍ', t: 'ḥālin', e: 'a state (dhū l-ḥāl)' } ],
  ] },
  { t: 'box', label: 'تقديم ذي الحال', labelEn: 'fronting the dhū l-ḥāl', lines: [
    [ { a: 'أَصْلُ', t: 'aṣlu', e: 'the norm for' }, { a: 'ذِي', t: 'dhī', e: 'the possessor of' }, { a: 'الْحَالِ', t: 'al-ḥāli', e: 'the state' }, { a: 'أَنْ', t: 'an', e: 'is' }, { a: 'يَكُونَ', t: 'yakūna', e: 'to be' }, { a: 'مُقَدَّمًا', t: 'muqaddaman', e: 'placed before' }, { a: 'عَلَى', t: 'ʿalā', e: '' }, { a: 'الْحَالِ', t: 'al-ḥāli', e: 'the ḥāl' } ],
  ] },
  { t: 'box', label: 'تنكير ذي الحال ومسوّغات تنكيره', labelEn: 'indefiniteness of the dhū l-ḥāl and its licensers', lines: [
    [ { a: 'وَأَصْلُ', t: 'wa-aṣlu', e: 'and the norm for' }, { a: 'ذِي', t: 'dhī', e: 'the possessor of' }, { a: 'الْحَالِ', t: 'al-ḥāli', e: 'the state' }, { a: 'أَنْ', t: 'an', e: 'is' }, { a: 'يَكُونَ', t: 'yakūna', e: 'to be' }, { a: 'مُعَرَّفًا،', t: 'muʿarrafan', e: 'definite' },
      { a: 'وَلَا', t: 'wa-lā', e: 'and it is not' }, { a: 'يَكُونُ', t: 'yakūnu', e: '' }, { a: 'نَكِرَةً', t: 'nakiratan', e: 'indefinite' }, { a: 'إِلَّا', t: 'illā', e: 'except' }, { a: 'بِمُسَوِّغٍ،', t: 'bi-musawwighin', e: 'with a licenser' },
      { a: 'وَمِنَ', t: 'wa-mina', e: 'and among' }, { a: 'الْمُسَوِّغَاتِ', t: 'al-musawwighāti', e: 'the licensers (are)' }, { g: ':' } ],
  ] },

  { t: 'page', n: '١٤١' },
  { t: 'box', lines: [
    [ { a: 'أَنْ', t: 'an', e: 'that' }, { a: 'يَكُونَ', t: 'yakūna', e: 'be' }, { a: 'الْحَالُ', t: 'al-ḥālu', e: 'the ḥāl' }, { a: 'مُقَدَّمًا،', t: 'muqaddaman', e: 'placed first' },
      NAHW, { g: ':' }, { a: 'رَأَيْتُ', t: 'raʾaytu', e: 'I saw' }, { a: 'رَاكِبًا', t: 'rākiban', e: 'riding' }, { a: 'رَجُلًا', t: 'rajulan', e: 'a man' } ],
    [ { a: 'وَأَنْ', t: 'wa-an', e: 'and that' }, { a: 'يَكُونَ', t: 'yakūna', e: 'be' }, { a: 'ذُو', t: 'dhū', e: 'the possessor of' }, { a: 'الْحَالِ', t: 'al-ḥāli', e: 'the state' }, { a: 'نَكِرَةً', t: 'nakiratan', e: 'an indefinite' }, { a: 'غَيْرَ', t: 'ghayra', e: 'not' }, { a: 'مَحْضَةٍ،', t: 'maḥḍatin', e: 'purely so' } ],
    [ NAHW, { g: ':' }, OPEN, { a: 'فِيهَا', t: 'fīhā', e: 'therein', q: 1 }, { a: 'يُفْرَقُ', t: 'yufraqu', e: 'is decided', q: 1 }, { a: 'كُلُّ', t: 'kullu', e: 'every', q: 1 }, { a: 'أَمْرٍ', t: 'amrin', e: 'matter', q: 1 }, { a: 'حَكِيمٍ', t: 'ḥakīmin', e: 'wise', q: 1 }, { g: '۝' }, { a: 'أَمْرًا', t: 'amran', e: 'as a command', q: 1 }, { a: 'مِنْ', t: 'min', e: 'from', q: 1 }, { a: 'عِنْدِنَا', t: 'ʿindinā', e: 'Us', q: 1 }, CLOSE ],
    [ { a: 'وَنَحْوُ', t: 'wa-naḥwu', e: 'and like' }, { g: ':' }, OPEN, { a: 'وَقَدَّرَ', t: 'wa-qaddara', e: 'and He determined', q: 1 }, { a: 'فِيهَا', t: 'fīhā', e: 'therein', q: 1 }, { a: 'أَقْوَاتَهَا', t: 'aqwātahā', e: 'its sustenance', q: 1 }, { a: 'فِي', t: 'fī', e: 'in', q: 1 }, { a: 'أَرْبَعَةِ', t: 'arbaʿati', e: 'four', q: 1 }, { a: 'أَيَّامٍ', t: 'ayyāmin', e: 'days', q: 1 }, { a: 'سَوَاءً', t: 'sawāʾan', e: 'equal', q: 1 }, { a: 'لِلسَّائِلِينَ', t: 'li-s-sāʾilīna', e: 'for those who ask', q: 1 }, CLOSE ],
    [ { a: 'وَأَنْ', t: 'wa-an', e: 'and that' }, { a: 'يَكُونَ', t: 'yakūna', e: 'be' }, { a: 'ذُو', t: 'dhū', e: 'the possessor of' }, { a: 'الْحَالِ', t: 'al-ḥāli', e: 'the state' }, { a: 'بَعْدَ', t: 'baʿda', e: 'after' }, ELL ],
    [ { a: 'نَفْيٍ،', t: 'nafyin', e: 'a negation' }, NAHW, { g: ':' },
      OPEN, { a: 'وَمَا', t: 'wa-mā', e: 'and We did not', q: 1 }, { a: 'أَهْلَكْنَا', t: 'ahlaknā', e: 'destroy', q: 1 }, { a: 'مِنْ', t: 'min', e: '', q: 1 }, { a: 'قَرْيَةٍ', t: 'qaryatin', e: 'any town', q: 1 }, { a: 'إِلَّا', t: 'illā', e: 'except', q: 1 }, { a: 'وَلَهَا', t: 'wa-lahā', e: 'that it had', q: 1 }, { a: 'كِتَابٌ', t: 'kitābun', e: 'a decree', q: 1 }, { a: 'مَعْلُومٌ', t: 'maʿlūmun', e: 'known', q: 1 }, CLOSE ],
    [ { a: 'أَوْ', t: 'aw', e: 'or' }, { a: 'شِبْهِ', t: 'shibhi', e: 'a quasi-' }, { a: 'النَّفْيِ', t: 'an-nafyi', e: 'negation' }, ELL ],
    [ { a: 'كَالنَّهْيِ،', t: 'ka-n-nahyi', e: 'such as prohibition' }, NAHW, { g: ':' },
      { a: 'لَا', t: 'lā', e: 'let not' }, { a: 'يُصَلِّيَنَّ', t: 'yuṣalliyanna', e: 'pray' }, { a: 'أَحَدٌ', t: 'aḥadun', e: 'anyone' }, { a: 'غَافِلًا', t: 'ghāfilan', e: 'heedless' } ],
    [ { a: 'أَوِ', t: 'awi', e: 'or' }, { a: 'الِاسْتِفْهَامِ،', t: 'al-istifhāmi', e: 'interrogation' }, NAHW, { g: ':' },
      { a: 'هَلْ', t: 'hal', e: 'did' }, { a: 'صَلَّى', t: 'ṣallā', e: 'pray' }, { a: 'أَحَدٌ', t: 'aḥadun', e: 'anyone' }, { a: 'جَالِسًا؟', t: 'jālisan', e: 'seated?' } ],
    [ { a: 'أَنْ', t: 'an', e: 'that' }, { a: 'يَكُونَ', t: 'yakūna', e: 'be' }, { a: 'الْحَالُ', t: 'al-ḥālu', e: 'the ḥāl' }, { a: 'مَقْرُونًا', t: 'maqrūnan', e: 'joined' }, { a: 'بِوَاوٍ،', t: 'bi-wāwin', e: 'with a wāw' },
      NAHW, { g: ':' }, OPEN, { a: 'أَوْ', t: 'aw', e: 'or', q: 1 }, { a: 'كَالَّذِي', t: 'ka-lladhī', e: 'like the one who', q: 1 }, { a: 'مَرَّ', t: 'marra', e: 'passed', q: 1 }, { a: 'عَلَى', t: 'ʿalā', e: 'by', q: 1 }, { a: 'قَرْيَةٍ', t: 'qaryatin', e: 'a town', q: 1 }, { a: 'وَهِيَ', t: 'wa-hiya', e: 'while it was', q: 1 }, { a: 'خَاوِيَةٌ', t: 'khāwiyatun', e: 'fallen', q: 1 }, { a: 'عَلَى', t: 'ʿalā', e: 'upon', q: 1 }, { a: 'عُرُوشِهَا', t: 'ʿurūshihā', e: 'its roofs', q: 1 }, CLOSE ],
    [ { a: 'قَدْ', t: 'qad', e: 'sometimes' }, { a: 'يَكُونُ', t: 'yakūnu', e: 'is' }, { a: 'ذُو', t: 'dhū', e: 'the possessor of' }, { a: 'الْحَالِ', t: 'al-ḥāli', e: 'the state' }, { a: 'نَكِرَةً', t: 'nakiratan', e: 'indefinite' }, { a: 'بِغَيْرِ', t: 'bi-ghayri', e: 'without' }, { a: 'مُسَوِّغٍ،', t: 'musawwighin', e: 'a licenser' },
      { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' }, { a: 'قَلِيلٌ،', t: 'qalīlun', e: 'rare' }, NAHW, { g: ':' },
      { a: 'صَلَّى', t: 'ṣallā', e: 'prayed' }, { a: 'رَسُولُ', t: 'rasūlu', e: 'the Messenger of' }, { a: 'اللهِ', t: 'Allāhi', e: 'Allah' }, { a: 'ﷺ', t: 'ṣ', e: '(ﷺ)' }, { a: 'قَاعِدًا', t: 'qāʿidan', e: 'seated' },
      { a: 'وَصَلَّى', t: 'wa-ṣallā', e: 'and prayed' }, { a: 'وَرَاءَهُ', t: 'warāʾahu', e: 'behind him' }, { a: 'رِجَالٌ', t: 'rijālun', e: 'men' }, { a: 'قِيَامًا', t: 'qiyāman', e: 'standing' } ],
  ] },
  { t: 'box', label: 'تنكير الحال', labelEn: 'indefiniteness of the ḥāl', lines: [
    [ { a: 'الْأَصْلُ', t: 'al-aṣlu', e: 'the norm' }, { a: 'فِي', t: 'fī', e: 'for' }, { a: 'الْحَالِ', t: 'al-ḥāli', e: 'the ḥāl' }, { a: 'أَنْ', t: 'an', e: 'is' }, { a: 'تَكُونَ', t: 'takūna', e: 'to be' }, { a: 'نَكِرَةً،', t: 'nakiratan', e: 'indefinite' },
      { a: 'وَفِي', t: 'wa-fī', e: 'and in' }, { a: 'قَوْلِ', t: 'qawli', e: 'the saying of' }, { a: 'اللهِ', t: 'Allāhi', e: 'Allah' }, { g: ':' },
      OPEN, { a: 'إِذَا', t: 'idhā', e: 'when', q: 1 }, { a: 'دُعِيَ', t: 'duʿiya', e: 'is invoked', q: 1 }, { a: 'اللهُ', t: 'Allāhu', e: 'Allah', q: 1 }, { a: 'وَحْدَهُ', t: 'waḥdahu', e: 'alone', q: 1 }, { a: 'كَفَرْتُمْ', t: 'kafartum', e: 'you disbelieve', q: 1 }, CLOSE,
      { a: 'وَحْدَهُ', t: 'waḥdahu', e: '“alone”' }, { a: 'فِي', t: 'fī', e: 'is in' }, { a: 'تَأْوِيلِ', t: 'taʾwīli', e: 'the construal of' }, { a: 'مُنْفَرِدًا', t: 'munfaridan', e: '“being singular”' }, { a: 'أَوْ', t: 'aw', e: 'or' }, { a: 'مُوَحَّدًا', t: 'muwaḥḥadan', e: '“being made one”' } ],
  ] },
  { t: 'box', label: 'اشتقاق الحال', labelEn: 'derivation of the ḥāl', lines: [
    [ { a: 'الْأَصْلُ', t: 'al-aṣlu', e: 'the norm' }, { a: 'فِي', t: 'fī', e: 'for' }, { a: 'الْحَالِ', t: 'al-ḥāli', e: 'the ḥāl' }, { a: 'الْمُفْرَدِ', t: 'al-mufradi', e: 'when a single word' }, { a: 'أَنْ', t: 'an', e: 'is' }, { a: 'تَكُونَ', t: 'takūna', e: 'to be' }, { a: 'اسْمًا', t: 'isman', e: 'a noun' }, { a: 'مُشْتَقًّا', t: 'mushtaqqan', e: 'derived' } ],
    [ { a: 'قَدْ', t: 'qad', e: 'sometimes' }, { a: 'تَكُونُ', t: 'takūnu', e: 'is' }, { a: 'الْحَالُ', t: 'al-ḥālu', e: 'the ḥāl' }, { a: 'جَامِدَةً', t: 'jāmidatan', e: 'non-derived (jāmid)' }, { a: 'مُؤَوَّلَةً', t: 'muʾawwalatan', e: 'construed' }, { a: 'بِالْمُشْتَقِّ', t: 'bi-l-mushtaqqi', e: 'as a derived form' }, { a: 'فِي', t: 'fī', e: 'in' }, { a: 'مَوَاضِعَ', t: 'mawāḍiʿa', e: 'places' }, { g: ':' } ],
    [ { a: 'الْأَوَّلُ', t: 'al-awwalu', e: 'the first', c: 'red' }, { a: 'إِنْ', t: 'in', e: 'if' }, { a: 'دَلَّ', t: 'dalla', e: 'it denotes' }, { a: 'عَلَى', t: 'ʿalā', e: '' }, { a: 'تَشْبِيهٍ،', t: 'tashbīhin', e: 'a simile' },
      NAHW, { g: ':' }, { a: 'بَدَا', t: 'badā', e: 'appeared' }, { a: 'وَجْهُهُ', t: 'wajhuhu', e: 'his face' }, { a: 'قَمَرًا', t: 'qamaran', e: 'like a moon' } ],
    [ { a: 'الثَّانِي', t: 'ath-thānī', e: 'the second', c: 'red' }, { a: 'إِنْ', t: 'in', e: 'if' }, { a: 'دَلَّ', t: 'dalla', e: 'it denotes' }, { a: 'عَلَى', t: 'ʿalā', e: '' }, { a: 'مُفَاعَلَةٍ،', t: 'mufāʿalatin', e: 'reciprocity' },
      NAHW, { g: ':' }, { a: 'بِعْتُهُ', t: 'biʿtuhu', e: 'I sold it to him' }, { a: 'يَدًا', t: 'yadan', e: 'hand' }, { a: 'بِيَدٍ،', t: 'bi-yadin', e: 'to hand' },
      { a: 'وَكَلَّمْتُهُ', t: 'wa-kallamtuhu', e: 'and I spoke to him' }, { a: 'فَاهُ', t: 'fāhu', e: 'his mouth' }, { a: 'إِلَى', t: 'ilā', e: 'to' }, { a: 'فِيَّ', t: 'fiyya', e: 'my mouth' } ],
    [ { a: 'الثَّالِثُ', t: 'ath-thālithu', e: 'the third', c: 'red' }, { a: 'إِنْ', t: 'in', e: 'if' }, { a: 'دَلَّ', t: 'dalla', e: 'it denotes' }, { a: 'عَلَى', t: 'ʿalā', e: '' }, { a: 'تَرْتِيبٍ،', t: 'tartībin', e: 'sequence' },
      NAHW, { g: ':' }, OPEN, { a: 'وَجَاءَ', t: 'wa-jāʾa', e: 'and there comes', q: 1 }, { a: 'رَبُّكَ', t: 'rabbuka', e: 'your Lord', q: 1 }, { a: 'وَالْمَلَكُ', t: 'wa-l-malaku', e: 'and the angels', q: 1 }, { a: 'صَفًّا', t: 'ṣaffan', e: 'rank', q: 1 }, { a: 'صَفًّا', t: 'ṣaffan', e: 'upon rank', q: 1 }, CLOSE ],
  ] },

  { t: 'page', n: '١٤٢' },
  { t: 'box', lines: [
    [ { a: 'وَقَدْ', t: 'wa-qad', e: 'and sometimes' }, { a: 'تَكُونُ', t: 'takūnu', e: 'is' }, { a: 'الْحَالُ', t: 'al-ḥālu', e: 'the ḥāl' }, { a: 'جَامِدَةً', t: 'jāmidatan', e: 'non-derived' }, { a: 'غَيْرَ', t: 'ghayra', e: 'not' }, { a: 'مُؤَوَّلَةٍ', t: 'muʾawwalatin', e: 'construed' }, { a: 'بِالْمُشْتَقِّ', t: 'bi-l-mushtaqqi', e: 'as a derived form' }, { a: 'فِي', t: 'fī', e: 'in' }, { a: 'مَوَاضِعَ،', t: 'mawāḍiʿa', e: 'places' }, { a: 'مِنْهَا', t: 'minhā', e: 'among them' }, { g: ':' } ],
    [ { a: 'الْأَوَّلُ', t: 'al-awwalu', e: 'the first', c: 'red' }, { a: 'إِنْ', t: 'in', e: 'if' }, { a: 'كَانَتْ', t: 'kānat', e: 'it is' }, { a: 'مَوْصُوفَةً،', t: 'mawṣūfatan', e: 'qualified by an adjective' },
      NAHW, { g: ':' }, OPEN, { a: 'إِنَّا', t: 'innā', e: 'indeed We', q: 1 }, { a: 'أَنْزَلْنَاهُ', t: 'anzalnāhu', e: 'sent it down', q: 1 }, { a: 'قُرْآنًا', t: 'qurʾānan', e: 'as a Qurʾān', q: 1 }, { a: 'عَرَبِيًّا', t: 'ʿarabiyyan', e: 'in Arabic', q: 1 }, CLOSE,
      { a: 'وَهِيَ', t: 'wa-hiya', e: 'and it is' }, { a: 'الْحَالُ', t: 'al-ḥālu', e: 'the ḥāl' }, { a: 'الْمُوَطِّئَةُ', t: 'al-muwaṭṭiʾatu', e: 'that paves the way (muwaṭṭiʾah)' } ],
    [ { a: 'الثَّانِي', t: 'ath-thānī', e: 'the second', c: 'red' }, { a: 'إِنْ', t: 'in', e: 'if' }, { a: 'كَانَتْ', t: 'kānat', e: 'it is' }, { a: 'عَدَدًا،', t: 'ʿadadan', e: 'a number' },
      NAHW, { g: ':' }, OPEN, { a: 'فَتَمَّ', t: 'fa-tamma', e: 'so was completed', q: 1 }, { a: 'مِيقَاتُ', t: 'mīqātu', e: 'the appointed term of', q: 1 }, { a: 'رَبِّهِ', t: 'rabbihi', e: 'his Lord', q: 1 }, { a: 'أَرْبَعِينَ', t: 'arbaʿīna', e: 'forty', q: 1 }, { a: 'لَيْلَةً', t: 'laylatan', e: 'nights', q: 1 }, CLOSE ],
    [ { a: 'الثَّالِثُ', t: 'ath-thālithu', e: 'the third', c: 'red' }, { a: 'إِنْ', t: 'in', e: 'if' }, { a: 'كَانَتْ', t: 'kānat', e: 'it is' }, { a: 'أَصْلًا،', t: 'aṣlan', e: 'an origin (raw material)' },
      NAHW, { g: ':' }, OPEN, { a: 'أَأَسْجُدُ', t: 'a-asjudu', e: 'shall I prostrate', q: 1 }, { a: 'لِمَنْ', t: 'li-man', e: 'to one whom', q: 1 }, { a: 'خَلَقْتَ', t: 'khalaqta', e: 'You created', q: 1 }, { a: 'طِينًا', t: 'ṭīnan', e: 'from clay', q: 1 }, CLOSE ],
    [ { a: 'الرَّابِعُ', t: 'ar-rābiʿu', e: 'the fourth', c: 'red' }, { a: 'إِنْ', t: 'in', e: 'if' }, { a: 'كَانَتْ', t: 'kānat', e: 'it is' }, { a: 'فَرْعًا،', t: 'farʿan', e: 'a derivative (product)' },
      NAHW, { g: ':' }, OPEN, { a: 'وَتَنْحِتُونَ', t: 'wa-tanḥitūna', e: 'and you carve', q: 1 }, { a: 'مِنَ', t: 'mina', e: 'from', q: 1 }, { a: 'الْجِبَالِ', t: 'al-jibāli', e: 'the mountains', q: 1 }, { a: 'بُيُوتًا', t: 'buyūtan', e: 'houses', q: 1 }, CLOSE ],
  ] },
  { t: 'box', label: 'حال متنقّلة وحال لازمة', labelEn: 'transient vs. permanent ḥāl', lines: [
    [ { a: 'تَكُونُ', t: 'takūnu', e: 'is' }, { a: 'الْحَالُ', t: 'al-ḥālu', e: 'the ḥāl' }, ELL ],
    [ { a: 'مُتَنَقِّلَةً،', t: 'mutanaqqilatan', e: 'transient' }, { a: 'وَهِيَ', t: 'wa-hiya', e: 'and it is' }, { a: 'الْأَصْلُ،', t: 'al-aṣlu', e: 'the norm' },
      NAHW, { g: ':' }, OPEN, { a: 'وَجَاءُوا', t: 'wa-jāʾū', e: 'and they came to', q: 1 }, { a: 'أَبَاهُمْ', t: 'abāhum', e: 'their father', q: 1 }, { a: 'عِشَاءً', t: 'ʿishāʾan', e: 'at nightfall', q: 1 }, { a: 'يَبْكُونَ', t: 'yabkūna', e: 'weeping', q: 1 }, CLOSE ],
    [ { a: 'وَلَازِمَةً،', t: 'wa-lāzimatan', e: 'and permanent' }, { a: 'وَتُسَمَّى', t: 'wa-tusammā', e: 'and it is called' }, { a: 'حَالًا', t: 'ḥālan', e: 'a ḥāl' }, { a: 'ثَابِتَةً', t: 'thābitatan', e: 'fixed' }, { a: 'أَوْ', t: 'aw', e: 'or' }, { a: 'دَائِمَةً،', t: 'dāʾimatan', e: 'perpetual' },
      NAHW, { g: ':' }, OPEN, { a: 'وَخُلِقَ', t: 'wa-khuliqa', e: 'and was created', q: 1 }, { a: 'الْإِنْسَانُ', t: 'al-insānu', e: 'man', q: 1 }, { a: 'ضَعِيفًا', t: 'ḍaʿīfan', e: 'weak', q: 1 }, CLOSE ],
  ] },
  { t: 'box', label: 'حال مؤسّسة وحال مؤكّدة', labelEn: 'founding vs. corroborating ḥāl', lines: [
    [ { a: 'تَكُونُ', t: 'takūnu', e: 'is' }, { a: 'الْحَالُ', t: 'al-ḥālu', e: 'the ḥāl' }, ELL ],
    [ { a: 'مُؤَسَّسَةً،', t: 'muʾassasatan', e: 'founding (adding new sense)' }, { a: 'وَيُسَمَّى', t: 'wa-yusammā', e: 'and it is called' }, { a: 'مُبَيِّنَةً،', t: 'mubayyinatan', e: 'clarifying' },
      { a: 'وَهِيَ', t: 'wa-hiya', e: 'and it is' }, { a: 'مَا', t: 'mā', e: 'what' }, { a: 'تُفِيدُ', t: 'tufīdu', e: 'conveys' }, { a: 'مَعْنًى', t: 'maʿnan', e: 'a sense' }, { a: 'مُسْتَقِلًّا', t: 'mustaqillan', e: 'independent' }, { a: 'مِنَ', t: 'mina', e: 'of' }, { a: 'الْعَامِلِ،', t: 'al-ʿāmili', e: 'the governor' },
      NAHW, { g: ':' }, OPEN, { a: 'وَلَا', t: 'wa-lā', e: 'and do not', q: 1 }, { a: 'تَمْشِ', t: 'tamshi', e: 'walk', q: 1 }, { a: 'فِي', t: 'fī', e: 'upon', q: 1 }, { a: 'الْأَرْضِ', t: 'al-arḍi', e: 'the earth', q: 1 }, { a: 'مَرَحًا', t: 'maraḥan', e: 'exultantly', q: 1 }, CLOSE ],
    [ { a: 'أَوْ', t: 'aw', e: 'or' }, { a: 'مُؤَكِّدَةً،', t: 'muʾakkidatan', e: 'corroborating' },
      { a: 'وَهِيَ', t: 'wa-hiya', e: 'and it is' }, { a: 'مَا', t: 'mā', e: 'what' }, { a: 'لَا', t: 'lā', e: 'does not' }, { a: 'يُفِيدُ', t: 'yufīdu', e: 'convey' }, { a: 'مَعْنًى', t: 'maʿnan', e: 'a sense' }, { a: 'مُسْتَقِلًّا', t: 'mustaqillan', e: 'independent' }, { a: 'مِنَ', t: 'mina', e: 'of' }, { a: 'الْعَامِلِ،', t: 'al-ʿāmili', e: 'the governor' },
      { a: 'بَلْ', t: 'bal', e: 'rather' }, { a: 'تُؤَكِّدُ', t: 'tuʾakkidu', e: 'it corroborates' }, { a: 'مَعْنَى', t: 'maʿnā', e: 'the sense of' }, { a: 'الْعَامِلِ،', t: 'al-ʿāmili', e: 'the governor' },
      NAHW, { g: ':' }, OPEN, { a: 'وَلَا', t: 'wa-lā', e: 'and do not', q: 1 }, { a: 'تَعْثَوْا', t: 'taʿthaw', e: 'act wickedly', q: 1 }, { a: 'فِي', t: 'fī', e: 'upon', q: 1 }, { a: 'الْأَرْضِ', t: 'al-arḍi', e: 'the earth', q: 1 }, { a: 'مُفْسِدِينَ', t: 'mufsidīna', e: 'spreading corruption', q: 1 }, CLOSE ],
  ] },
  { t: 'box', label: 'حال محكيّة وحال مقارنة وحال مقدّرة', labelEn: 'narrated · concurrent · anticipated ḥāl', lines: [
    [ { a: 'تَكُونُ', t: 'takūnu', e: 'is' }, { a: 'الْحَالُ', t: 'al-ḥālu', e: 'the ḥāl' }, ELL ],
    [ { a: 'مَحْكِيَّةً،', t: 'maḥkiyyatan', e: 'narrated' }, { a: 'أَيْ', t: 'ay', e: 'i.e.' }, { a: 'مَاضِيَةً،', t: 'māḍiyatan', e: 'past' },
      NAHW, { g: ':' }, OPEN, { a: 'قَالَ', t: 'qāla', e: 'he said', q: 1 }, { a: 'رَبِّ', t: 'rabbi', e: 'my Lord', q: 1 }, { a: 'أَنَّى', t: 'annā', e: 'how', q: 1 }, { a: 'يَكُونُ', t: 'yakūnu', e: 'can there be', q: 1 }, { a: 'لِي', t: 'lī', e: 'for me', q: 1 }, { a: 'غُلَامٌ', t: 'ghulāmun', e: 'a boy', q: 1 }, { a: 'وَقَدْ', t: 'wa-qad', e: 'while indeed', q: 1 }, { a: 'بَلَغَنِيَ', t: 'balaghaniya', e: 'has reached me', q: 1 }, { a: 'الْكِبَرُ', t: 'al-kibaru', e: 'old age', q: 1 }, CLOSE ],
    [ { a: 'وَمُقَارِنَةً،', t: 'wa-muqārinatan', e: 'and concurrent' }, NAHW, { g: ':' },
      OPEN, { a: 'وَجَاءُوا', t: 'wa-jāʾū', e: 'and they came to', q: 1 }, { a: 'أَبَاهُمْ', t: 'abāhum', e: 'their father', q: 1 }, { a: 'عِشَاءً', t: 'ʿishāʾan', e: 'at nightfall', q: 1 }, { a: 'يَبْكُونَ', t: 'yabkūna', e: 'weeping', q: 1 }, CLOSE ],
    [ { a: 'وَمُقَدَّرَةً،', t: 'wa-muqaddaratan', e: 'and anticipated' }, { a: 'أَيْ', t: 'ay', e: 'i.e.' }, { a: 'مُسْتَقْبَلَةً،', t: 'mustaqbalatan', e: 'future' },
      NAHW, { g: ':' }, OPEN, { a: 'فَادْخُلُوهَا', t: 'fa-dkhulūhā', e: 'so enter it', q: 1 }, { a: 'خَالِدِينَ', t: 'khālidīna', e: 'abiding forever', q: 1 }, CLOSE ],
  ] },

  { t: 'page', n: '١٤٣' },
  { t: 'box', label: 'حال مقصودة وحال موطّئة', labelEn: 'intended vs. way-paving ḥāl', lines: [
    [ { a: 'تَكُونُ', t: 'takūnu', e: 'is' }, { a: 'الْحَالُ', t: 'al-ḥālu', e: 'the ḥāl' }, ELL ],
    [ { a: 'مَقْصُودَةً،', t: 'maqṣūdatan', e: 'intended in itself' }, NAHW, { g: ':' },
      OPEN, { a: 'وَجَاءُوا', t: 'wa-jāʾū', e: 'and they came to', q: 1 }, { a: 'أَبَاهُمْ', t: 'abāhum', e: 'their father', q: 1 }, { a: 'عِشَاءً', t: 'ʿishāʾan', e: 'at nightfall', q: 1 }, { a: 'يَبْكُونَ', t: 'yabkūna', e: 'weeping', q: 1 }, CLOSE ],
    [ { a: 'وَمُوَطِّئَةً،', t: 'wa-muwaṭṭiʾatan', e: 'and way-paving' }, { a: 'وَهِيَ', t: 'wa-hiya', e: 'and it is' }, { a: 'الْجَامِدَةُ', t: 'al-jāmidatu', e: 'the non-derived' }, { a: 'الْمَوْصُوفَةُ', t: 'al-mawṣūfatu', e: 'qualified' }, { a: 'بِمُشْتَقٍّ،', t: 'bi-mushtaqqin', e: 'by a derived form' },
      NAHW, { g: ':' }, OPEN, { a: 'إِنَّا', t: 'innā', e: 'indeed We', q: 1 }, { a: 'أَنْزَلْنَاهُ', t: 'anzalnāhu', e: 'sent it down', q: 1 }, { a: 'قُرْآنًا', t: 'qurʾānan', e: 'as a Qurʾān', q: 1 }, { a: 'عَرَبِيًّا', t: 'ʿarabiyyan', e: 'in Arabic', q: 1 }, CLOSE ],
  ] },
  { t: 'box', label: 'حال مترادفة وحال متداخلة', labelEn: 'successive vs. nested ḥāl', lines: [
    [ { a: 'وَإِنْ', t: 'wa-in', e: 'and if' }, { a: 'تَعَدَّدَتِ', t: 'taʿaddadati', e: 'are multiple' }, { a: 'الْحَالُ', t: 'al-ḥālu', e: 'the ḥāl' }, { a: 'تَكُونُ', t: 'takūnu', e: 'then is' }, { a: 'الثَّانِيَةُ', t: 'ath-thāniyatu', e: 'the second' }, ELL ],
    [ { a: 'مُتَرَادِفَةً،', t: 'mutarādifatan', e: 'successive' }, { a: 'وَهِيَ', t: 'wa-hiya', e: 'and it is' }, { a: 'الَّتِي', t: 'allatī', e: 'that which' }, { a: 'تَكُونُ', t: 'takūnu', e: 'has' }, { a: 'صَاحِبُهَا', t: 'ṣāḥibuhā', e: 'its subject' }, { a: 'وَاحِدًا', t: 'wāḥidan', e: 'one' }, { a: 'وَالْحَالُ', t: 'wa-l-ḥālu', e: 'while the ḥāl' }, { a: 'مُتَعَدِّدَةً،', t: 'mutaʿaddidatan', e: 'is multiple' },
      NAHW, { g: ':' }, { g: '«' }, { a: 'يُحْشَرُ', t: 'yuḥsharu', e: 'will be gathered' }, { a: 'النَّاسُ', t: 'an-nāsu', e: 'the people' }, { a: 'يَوْمَ', t: 'yawma', e: 'on the Day of' }, { a: 'الْقِيَامَةِ', t: 'al-qiyāmati', e: 'Resurrection' }, { a: 'حُفَاةً', t: 'ḥufātan', e: 'barefoot' }, { a: 'عُرَاةً', t: 'ʿurātan', e: 'naked' }, { a: 'غُرْلًا', t: 'ghurlan', e: 'uncircumcised' }, { g: '»' } ],
    [ { a: 'أَوْ', t: 'aw', e: 'or' }, { a: 'مُتَدَاخِلَةً،', t: 'mutadākhilatan', e: 'nested' }, { a: 'وَهِيَ', t: 'wa-hiya', e: 'and it is' }, { a: 'الَّتِي', t: 'allatī', e: 'that which' }, { a: 'تَكُونُ', t: 'takūnu', e: 'has' }, { a: 'الْحَالُ', t: 'al-ḥālu', e: 'the ḥāl' }, { a: 'الثَّانِيَةُ', t: 'ath-thāniyatu', e: 'second' }, { a: 'حَالًا', t: 'ḥālan', e: 'as a ḥāl' }, { a: 'مِنْ', t: 'min', e: 'of' }, { a: 'ضَمِيرٍ', t: 'ḍamīrin', e: 'a pronoun' }, { a: 'فِي', t: 'fī', e: 'in' }, { a: 'الْحَالِ', t: 'al-ḥāli', e: 'the ḥāl' }, { a: 'الْأُولَى،', t: 'al-ūlā', e: 'first' },
      NAHW, { g: ':' }, OPEN, { a: 'أُولَئِكَ', t: 'ulāʾika', e: 'those', q: 1 }, { a: 'عَلَيْهِمْ', t: 'ʿalayhim', e: 'upon them is', q: 1 }, { a: 'لَعْنَةُ', t: 'laʿnatu', e: 'the curse of', q: 1 }, { a: 'اللهِ', t: 'Allāhi', e: 'Allah', q: 1 }, { a: 'وَالْمَلَائِكَةِ', t: 'wa-l-malāʾikati', e: 'and the angels', q: 1 }, { a: 'وَالنَّاسِ', t: 'wa-n-nāsi', e: 'and the people', q: 1 }, { a: 'أَجْمَعِينَ', t: 'ajmaʿīna', e: 'all together', q: 1 }, { g: '۝' }, { a: 'خَالِدِينَ', t: 'khālidīna', e: 'abiding', q: 1 }, { a: 'فِيهَا', t: 'fīhā', e: 'therein', q: 1 }, { a: 'لَا', t: 'lā', e: 'not', q: 1 }, { a: 'يُخَفَّفُ', t: 'yukhaffafu', e: 'will be lightened', q: 1 }, { a: 'عَنْهُمُ', t: 'ʿanhumu', e: 'for them', q: 1 }, { a: 'الْعَذَابُ', t: 'al-ʿadhābu', e: 'the punishment', q: 1 }, CLOSE ],
  ] },
  { t: 'box', label: 'حال حقيقية وحال سببيّة', labelEn: 'real vs. causal ḥāl', lines: [
    [ { a: 'وَتَكُونُ', t: 'wa-takūnu', e: 'and is' }, { a: 'الْحَالُ', t: 'al-ḥālu', e: 'the ḥāl' }, ELL ],
    [ { a: 'حَقِيقِيَّةً،', t: 'ḥaqīqiyyatan', e: 'real' }, { a: 'وَهِيَ', t: 'wa-hiya', e: 'and it is' }, { a: 'مَا', t: 'mā', e: 'what' }, { a: 'تُبَيِّنُ', t: 'tubayyinu', e: 'clarifies' }, { a: 'هَيْئَةَ', t: 'hayʾata', e: 'the state of' }, { a: 'صَاحِبِهِ،', t: 'ṣāḥibihi', e: 'its own subject' } ],
    [ { a: 'وَسَبَبِيَّةً،', t: 'wa-sababiyyatan', e: 'and causal' }, { a: 'وَهِيَ', t: 'wa-hiya', e: 'and it is' }, { a: 'مَا', t: 'mā', e: 'what' }, { a: 'تُبَيِّنُ', t: 'tubayyinu', e: 'clarifies' }, { a: 'هَيْئَةَ', t: 'hayʾata', e: 'the state of' }, { a: 'مُتَعَلِّقِ', t: 'mutaʿalliqi', e: 'something attached to' }, { a: 'صَاحِبِهِ،', t: 'ṣāḥibihi', e: 'its subject' },
      NAHW, { g: ':' }, OPEN, { a: 'فَتَوَلَّ', t: 'fa-tawalla', e: 'so turn away', q: 1 }, { a: 'عَنْهُمْ', t: 'ʿanhum', e: 'from them', q: 1 }, { a: 'يَوْمَ', t: 'yawma', e: 'on the Day', q: 1 }, { a: 'يَدْعُ', t: 'yadʿu', e: 'when calls', q: 1 }, { a: 'الدَّاعِ', t: 'ad-dāʿi', e: 'the caller', q: 1 }, { a: 'إِلَى', t: 'ilā', e: 'to', q: 1 }, { a: 'شَيْءٍ', t: 'shayʾin', e: 'a thing', q: 1 }, { a: 'نُكُرٍ', t: 'nukurin', e: 'terrible', q: 1 }, { g: '۝' }, { a: 'خُشَّعًا', t: 'khushshaʿan', e: 'humbled', q: 1 }, { a: 'أَبْصَارُهُمْ', t: 'abṣāruhum', e: 'their eyes', q: 1 }, { a: 'يَخْرُجُونَ', t: 'yakhrujūna', e: 'they will emerge', q: 1 }, { a: 'مِنَ', t: 'mina', e: 'from', q: 1 }, { a: 'الْأَجْدَاثِ', t: 'al-ajdāthi', e: 'the graves', q: 1 }, CLOSE ],
  ] },
  { t: 'h2', c: 'red', ar: 'السَّابِعُ: التَّمْيِيزُ', en: 'Seventh — the Specifier (tamyīz)' },
  { t: 'line', w: [
    { a: 'السَّابِعُ', t: 'as-sābiʿu', e: 'the seventh (is)' }, { a: 'التَّمْيِيزُ،', t: 'at-tamyīzu', e: 'the specifier' },
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' }, { a: 'مَا', t: 'mā', e: 'what' }, { a: 'يَرْفَعُ', t: 'yarfaʿu', e: 'removes' }, { a: 'الْإِبْهَامَ', t: 'al-ibhāma', e: 'the vagueness' }, { a: 'عَنْ', t: 'ʿan', e: 'from' }, { a: 'مُفْرَدٍ', t: 'mufradin', e: 'a single word' }, { a: 'مُبْهَمٍ', t: 'mubhamin', e: 'that is vague' }, { a: 'أَوْ', t: 'aw', e: 'or' }, { a: 'نِسْبَةٍ', t: 'nisbatin', e: 'a predication' }, { a: 'مُبْهَمَةٍ', t: 'mubhamatin', e: 'that is vague' },
  ] },
  { t: 'box', label: 'المفرد المبهم', labelEn: 'the vague single word', lines: [
    [ { a: 'الْمُفْرَدُ', t: 'al-mufradu', e: 'the single word' }, { a: 'الْمُبْهَمُ،', t: 'al-mubhamu', e: 'that is vague' }, { a: 'وَيُسَمَّى', t: 'wa-yusammā', e: 'and it is called' }, { a: 'تَمْيِيزٌ', t: 'tamyīzun', e: 'a specifier' }, { a: 'مُفْرَدٌ،', t: 'mufradun', e: 'of a single word' }, { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' }, ELL ],
    [ { a: 'الْعَدَدُ', t: 'al-ʿadadu', e: 'the number' }, ELL ],
    [ { a: 'الصَّرِيحُ،', t: 'aṣ-ṣarīḥu', e: 'the explicit' }, NAHW, { g: ':' },
      OPEN, { a: 'رَأَيْتُ', t: 'raʾaytu', e: 'I saw', q: 1 }, { a: 'أَحَدَ', t: 'aḥada', e: 'eleven', q: 1 }, { a: 'عَشَرَ', t: 'ʿashara', e: '', q: 1 }, { a: 'كَوْكَبًا', t: 'kawkaban', e: 'stars', q: 1 }, CLOSE ],
    [ { a: 'أَوِ', t: 'awi', e: 'or' }, { a: 'الْمُبْهَمُ،', t: 'al-mubhamu', e: 'the vague' }, NAHW, { g: ':' },
      OPEN, { a: 'كَمْ', t: 'kam', e: 'how many', q: 1 }, { a: 'آتَيْنَاهُمْ', t: 'ātaynāhum', e: 'We gave them', q: 1 }, { a: 'مِنْ', t: 'min', e: 'of', q: 1 }, { a: 'آيَةٍ', t: 'āyatin', e: 'a sign', q: 1 }, { a: 'بَيِّنَةٍ', t: 'bayyinatin', e: 'clear', q: 1 }, CLOSE ],
    [ { a: 'وَالْمِقْدَارُ،', t: 'wa-l-miqdāru', e: 'and the measure' }, { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' }, { a: 'مَا', t: 'mā', e: 'what' }, { a: 'يُقَدَّرُ', t: 'yuqaddaru', e: 'is measured' }, { a: 'بِآلَةٍ', t: 'bi-ālatin', e: 'by an instrument' } ],
  ] },

  { t: 'page', n: '١٤٤' },
  { t: 'box', lines: [
    [ { a: 'كَالْكَيْلِ،', t: 'ka-l-kayli', e: 'such as volume' }, NAHW, { g: ':' },
      { a: 'عِنْدِي', t: 'ʿindī', e: 'I have' }, { a: 'لِتْرٌ', t: 'litrun', e: 'a litre' }, { a: 'لَبَنًا', t: 'labanan', e: 'of milk' } ],
    [ { a: 'وَالْوَزْنِ،', t: 'wa-l-wazni', e: 'and weight' }, NAHW, { g: ':' },
      OPEN, { a: 'مِثْقَالَ', t: 'mithqāla', e: 'the weight of', q: 1 }, { a: 'ذَرَّةٍ', t: 'dharratin', e: 'an atom', q: 1 }, { a: 'خَيْرًا', t: 'khayran', e: 'of good', q: 1 }, CLOSE ],
    [ { a: 'وَالْمِسَاحَةِ،', t: 'wa-l-misāḥati', e: 'and area' }, NAHW, { g: ':' },
      { a: 'عِنْدِي', t: 'ʿindī', e: 'I have' }, { a: 'جَرِيبٌ', t: 'jarībun', e: 'an acre' }, { a: 'نَخْلًا', t: 'nakhlan', e: 'of palm trees' } ],
    [ { a: 'وَمَا', t: 'wa-mā', e: 'and what' }, { a: 'يُشْبِهُ', t: 'yushbihu', e: 'resembles' }, { a: 'الْمِقْدَارَ،', t: 'al-miqdāra', e: 'a measure' }, { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' }, { a: 'مَا', t: 'mā', e: 'what' }, { a: 'لَا', t: 'lā', e: 'is not' }, { a: 'يُقَدَّرُ', t: 'yuqaddaru', e: 'measured' }, { a: 'بِآلَةٍ،', t: 'bi-ālatin', e: 'by an instrument' },
      NAHW, { g: ':' }, { a: 'مَا', t: 'mā', e: 'there is not' }, { a: 'فِي', t: 'fī', e: 'in' }, { a: 'السَّمَاءِ', t: 'as-samāʾi', e: 'the sky' }, { a: 'قَدْرُ', t: 'qadru', e: 'the extent of' }, { a: 'رَاحَةٍ', t: 'rāḥatin', e: 'a palm' }, { a: 'سَحَابًا', t: 'saḥāban', e: 'of cloud' } ],
    [ { a: 'وَمَا', t: 'wa-mā', e: 'and what' }, { a: 'أُجْرِيَ', t: 'ujriya', e: 'is treated' }, { a: 'مَجْرَى', t: 'majrā', e: 'in the manner of' }, { a: 'الْمَقَادِيرِ،', t: 'al-maqādīri', e: 'measures' }, { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' }, { a: 'مَا', t: 'mā', e: 'what' }, { a: 'احْتَاجَ', t: 'iḥtāja', e: 'needs' }, { a: 'إِلَى', t: 'ilā', e: '' }, { a: 'تَمْيِيزٍ،', t: 'tamyīzin', e: 'a specifier' },
      NAHW, { g: ':' }, OPEN, { a: 'وَلَوْ', t: 'wa-law', e: 'even if', q: 1 }, { a: 'جِئْنَا', t: 'jiʾnā', e: 'We brought', q: 1 }, { a: 'بِمِثْلِهِ', t: 'bi-mithlihi', e: 'the like of it', q: 1 }, { a: 'مَدَدًا', t: 'madadan', e: 'as a supply', q: 1 }, CLOSE ],
    [ { a: 'وَمَا', t: 'wa-mā', e: 'and what', c: 'red' }, { a: 'هُوَ', t: 'huwa', e: 'is', c: 'red' }, { a: 'فَرْعٌ', t: 'farʿun', e: 'a branch', c: 'red' }, { a: 'لِلتَّمْيِيزِ،', t: 'li-t-tamyīzi', e: 'of the specifier', c: 'red' },
      NAHW, { g: ':' }, { a: 'عِنْدِي', t: 'ʿindī', e: 'I have' }, { a: 'خَاتَمٌ', t: 'khātamun', e: 'a ring' }, { a: 'فِضَّةً،', t: 'fiḍḍatan', e: 'in silver' },
      { a: 'الْغَالِبُ', t: 'al-ghālibu', e: 'the more common' }, { a: 'فِيهِ', t: 'fīhi', e: 'in it' }, { a: 'الْإِضَافَةُ،', t: 'al-iḍāfatu', e: 'is annexation' },
      NAHW, { g: ':' }, { a: 'خَاتَمُ', t: 'khātamu', e: 'a ring of' }, { a: 'فِضَّةٍ', t: 'fiḍḍatin', e: 'silver' } ],
  ] },
  { t: 'box', label: 'النسبة المبهمة', labelEn: 'the vague predication', lines: [
    [ { a: 'النِّسْبَةُ', t: 'an-nisbatu', e: 'the predication' }, { a: 'الْمُبْهَمَةُ،', t: 'al-mubhamatu', e: 'that is vague' }, { a: 'وَيُسَمَّى', t: 'wa-yusammā', e: 'and it is called' }, { a: 'تَمْيِيزُ', t: 'tamyīzu', e: 'the specifier of' }, { a: 'جُمْلَةٍ،', t: 'jumlatin', e: 'a clause' }, { a: 'وَيَكُونُ', t: 'wa-yakūnu', e: 'and it is' }, ELL ],
    [ { a: 'غَيْرَ', t: 'ghayra', e: 'not' }, { a: 'مُحَوَّلٍ،', t: 'muḥawwalin', e: 'transposed' }, NAHW, { g: ':' },
      { a: 'لِلهِ', t: 'lillāhi', e: 'to Allah belongs' }, { a: 'دَرُّهُ', t: 'darruhu', e: 'his excellence' }, { a: 'فَارِسًا،', t: 'fārisan', e: 'as a horseman' } ],
    [ { a: 'وَمُحَوَّلًا', t: 'wa-muḥawwalan', e: 'and transposed' }, ELL ],
    [ { a: 'مِنَ', t: 'mina', e: 'from' }, { a: 'الْفَاعِلِ،', t: 'al-fāʿili', e: 'the agent' }, NAHW, { g: ':' },
      OPEN, { a: 'وَاشْتَعَلَ', t: 'wa-shtaʿala', e: 'and has flared', q: 1 }, { a: 'الرَّأْسُ', t: 'ar-raʾsu', e: 'the head', q: 1 }, { a: 'شَيْبًا', t: 'shayban', e: 'with grey', q: 1 }, CLOSE,
      { a: 'أَيْ', t: 'ay', e: 'i.e.' }, { a: 'شَيْبُ', t: 'shaybu', e: 'the greyness of' }, { a: 'الرَّأْسِ', t: 'ar-raʾsi', e: 'the head' } ],
    [ { a: 'وَمِنَ', t: 'wa-mina', e: 'and from' }, { a: 'الْمَفْعُولِ', t: 'al-mafʿūli', e: 'the object' }, { a: 'بِهِ،', t: 'bihi', e: 'acted upon' }, NAHW, { g: ':' },
      OPEN, { a: 'فَجَّرْنَا', t: 'fajjarnā', e: 'We caused to gush', q: 1 }, { a: 'الْأَرْضَ', t: 'al-arḍa', e: 'the earth', q: 1 }, { a: 'عُيُونًا', t: 'ʿuyūnan', e: 'with springs', q: 1 }, CLOSE,
      { a: 'أَيْ', t: 'ay', e: 'i.e.' }, { a: 'فَجَّرْنَا', t: 'fajjarnā', e: 'We caused to gush' }, { a: 'عُيُونَ', t: 'ʿuyūna', e: 'the springs of' }, { a: 'الْأَرْضِ،', t: 'al-arḍi', e: 'the earth' } ],
    [ { a: 'وَمِنَ', t: 'wa-mina', e: 'and from' }, { a: 'الْمُبْتَدَأِ،', t: 'al-mubtadaʾi', e: 'the mubtadaʾ' }, NAHW, { g: ':' },
      OPEN, { a: 'أَنَا', t: 'anā', e: 'I am', q: 1 }, { a: 'أَكْثَرُ', t: 'aktharu', e: 'greater', q: 1 }, { a: 'مِنْكَ', t: 'minka', e: 'than you', q: 1 }, { a: 'مَالًا', t: 'mālan', e: 'in wealth', q: 1 }, CLOSE,
      { a: 'أَيْ', t: 'ay', e: 'i.e.' }, { a: 'مَالِي', t: 'mālī', e: 'my wealth is' }, { a: 'أَكْثَرُ', t: 'aktharu', e: 'greater' }, { a: 'مِنْ', t: 'min', e: 'than' }, { a: 'مَالِكَ.', t: 'mālika', e: 'your wealth' } ],
    [ { a: 'وَمَا', t: 'wa-mā', e: 'and what' }, { a: 'فِي', t: 'fī', e: 'is in' }, { a: 'حُكْمِ', t: 'ḥukmi', e: 'the ruling of' }, { a: 'الْمُبْتَدَأِ،', t: 'al-mubtadaʾi', e: 'the mubtadaʾ' }, NAHW, { g: ':' },
      OPEN, { a: 'وَكَانَ', t: 'wa-kāna', e: 'and is', q: 1 }, { a: 'الْإِنْسَانُ', t: 'al-insānu', e: 'man', q: 1 }, { a: 'أَكْثَرَ', t: 'akthara', e: 'the most', q: 1 }, { a: 'شَيْءٍ', t: 'shayʾin', e: 'of things', q: 1 }, { a: 'جَدَلًا', t: 'jadalan', e: 'in disputation', q: 1 }, CLOSE,
      { a: 'أَيْ', t: 'ay', e: 'i.e.' }, { a: 'جَدَلُ', t: 'jadalu', e: 'the disputation of' }, { a: 'الْإِنْسَانِ', t: 'al-insāni', e: 'man' }, { a: 'أَكْثَرُ', t: 'aktharu', e: 'is the most of' }, { a: 'شَيْءٍ', t: 'shayʾin', e: 'anything' }, { a: 'فِيهِ', t: 'fīhi', e: 'in it' } ],
  ] },
  { t: 'box', label: 'مسألة', labelEn: 'point', lines: [
    [ { a: 'الْأَصْلُ', t: 'al-aṣlu', e: 'the norm' }, { a: 'فِي', t: 'fī', e: 'for' }, { a: 'التَّمْيِيزِ', t: 'at-tamyīzi', e: 'the specifier' }, { a: 'أَنْ', t: 'an', e: 'is' }, { a: 'يَكُونَ', t: 'yakūna', e: 'to be' }, { a: 'نَكِرَةً', t: 'nakiratan', e: 'indefinite' } ],
  ] },
  { t: 'box', label: 'مسألة', labelEn: 'point', lines: [
    [ { a: 'يُذْكَرُ', t: 'yudhkaru', e: 'is mentioned' }, { a: 'التَّمْيِيزُ', t: 'at-tamyīzu', e: 'the specifier' }, { a: 'فِي', t: 'fī', e: 'among' }, { a: 'الْمَنْصُوبَاتِ', t: 'al-manṣūbāti', e: 'the accusatives' }, { a: 'تَغْلِيبًا،', t: 'taghlīban', e: 'by preponderance' },
      { a: 'فَإِنَّ', t: 'fa-inna', e: 'for indeed' }, { a: 'التَّمْيِيزَ', t: 'at-tamyīza', e: 'the specifier' }, { a: 'قَدْ', t: 'qad', e: 'may' }, { a: 'يَكُونُ', t: 'yakūnu', e: 'be' }, { a: 'مَجْرُورًا', t: 'majrūran', e: 'genitive' } ],
  ] },
  { t: 'box', label: 'إعراب تمييز العدد الصريح', labelEn: 'iʿrāb of the explicit-number specifier', lines: [
    [ { a: 'يَكُونُ', t: 'yakūnu', e: 'is' }, { a: 'تَمْيِيزُ', t: 'tamyīzu', e: 'the specifier of' }, { a: 'الْعَدَدِ', t: 'al-ʿadadi', e: 'the number' }, { a: 'الصَّرِيحِ', t: 'aṣ-ṣarīḥi', e: 'explicit' }, ELL ],
    [ { a: 'مَجْرُورًا', t: 'majrūran', e: 'genitive' }, { a: 'بِالْإِضَافَةِ', t: 'bi-l-iḍāfati', e: 'by annexation' } ],
    [ { a: 'إِمَّا', t: 'immā', e: 'either' }, { a: 'مَجْمُوعًا', t: 'majmūʿan', e: 'in the plural' }, { a: 'فِي', t: 'fī', e: 'for' }, { a: 'الثَّلَاثَةِ', t: 'ath-thalāthati', e: 'three' }, { a: 'إِلَى', t: 'ilā', e: 'to' }, { a: 'الْعَشَرَةِ،', t: 'al-ʿasharati', e: 'ten' },
      NAHW, { g: ':' }, OPEN, { a: 'ثَلَاثَةَ', t: 'thalāthata', e: 'three', q: 1 }, { a: 'أَيَّامٍ', t: 'ayyāmin', e: 'days', q: 1 }, CLOSE ],
  ] },

  { t: 'page', n: '١٤٥' },
  { t: 'box', lines: [
    [ { a: 'وَإِمَّا', t: 'wa-immā', e: 'and either' }, { a: 'مُفْرَدًا', t: 'mufradan', e: 'in the singular' }, { a: 'فِي', t: 'fī', e: 'for' }, ELL ],
    [ { a: 'الْمِائَةِ،', t: 'al-miʾati', e: 'the hundred' }, NAHW, { g: ':' },
      OPEN, { a: 'فَأَمَاتَهُ', t: 'fa-amātahu', e: 'so Allah caused him to die', q: 1 }, { a: 'اللهُ', t: 'Allāhu', e: '', q: 1 }, { a: 'مِائَةَ', t: 'miʾata', e: 'a hundred', q: 1 }, { a: 'عَامٍ', t: 'ʿāmin', e: 'years', q: 1 }, CLOSE ],
    [ { a: 'وَالْأَلْفِ،', t: 'wa-l-alfi', e: 'and the thousand' }, NAHW, { g: ':' },
      OPEN, { a: 'كَأَلْفِ', t: 'ka-alfi', e: 'like a thousand', q: 1 }, { a: 'سَنَةٍ', t: 'sanatin', e: 'years', q: 1 }, CLOSE ],
    [ { a: 'وَمَنْصُوبًا', t: 'wa-manṣūban', e: 'and accusative' }, { a: 'مُفْرَدًا', t: 'mufradan', e: 'in the singular' }, { a: 'فِيمَا', t: 'fīmā', e: 'in what' }, { a: 'عَدَا', t: 'ʿadā', e: 'is besides' }, { a: 'ذَلِكَ،', t: 'dhālika', e: 'that' },
      OPEN, { a: 'إِنِّي', t: 'innī', e: 'indeed I', q: 1 }, { a: 'رَأَيْتُ', t: 'raʾaytu', e: 'saw', q: 1 }, { a: 'أَحَدَ', t: 'aḥada', e: 'eleven', q: 1 }, { a: 'عَشَرَ', t: 'ʿashara', e: '', q: 1 }, { a: 'كَوْكَبًا', t: 'kawkaban', e: 'stars', q: 1 }, CLOSE ],
  ] },
  { t: 'box', label: 'إعراب تمييز العدد المبهم', labelEn: 'iʿrāb of the vague-number specifier', lines: [
    [ { a: 'يَكُونُ', t: 'yakūnu', e: 'is' }, { a: 'تَمْيِيزُ', t: 'tamyīzu', e: 'the specifier of' }, { a: 'الْعَدَدِ', t: 'al-ʿadadi', e: 'the number' }, { a: 'الْمُبْهَمِ', t: 'al-mubhami', e: 'vague' }, ELL ],
    [ { a: 'مَنْصُوبًا', t: 'manṣūban', e: 'accusative' }, { a: 'مُفْرَدًا', t: 'mufradan', e: 'singular' }, { a: 'بَعْدَ', t: 'baʿda', e: 'after' }, { a: 'كَمِ', t: 'kami', e: 'kam' }, { a: 'الِاسْتِفْهَامِيَّةِ،', t: 'al-istifhāmiyyati', e: 'the interrogative' },
      NAHW, { g: ':' }, { a: 'كَمْ', t: 'kam', e: 'how many' }, { a: 'يَوْمًا', t: 'yawman', e: 'days' }, { a: 'لَبِثْتَ،', t: 'labithta', e: 'did you remain' } ],
    [ { a: 'وَيَجُوزُ', t: 'wa-yajūzu', e: 'and it is permitted' }, { a: 'حَذْفُ', t: 'ḥadhfu', e: 'to omit' }, { a: 'تَمْيِيزِهَا', t: 'tamyīzihā', e: 'its specifier' }, { a: 'عِنْدَ', t: 'ʿinda', e: 'given' }, { a: 'قَرِينَةٍ،', t: 'qarīnatin', e: 'an indicator' },
      NAHW, { g: ':' }, OPEN, { a: 'كَمْ', t: 'kam', e: 'how long', q: 1 }, { a: 'لَبِثْتُمْ', t: 'labithtum', e: 'did you remain', q: 1 }, CLOSE,
      { a: 'أَيْ', t: 'ay', e: 'i.e.' }, { a: 'كَمْ', t: 'kam', e: 'how many' }, { a: 'يَوْمًا', t: 'yawman', e: 'days' }, { a: 'لَبِثْتُمْ', t: 'labithtum', e: 'did you remain' } ],
    [ { a: 'وَمَجْرُورًا', t: 'wa-majrūran', e: 'and genitive' }, { a: 'بِحَرْفٍ', t: 'bi-ḥarfin', e: 'by a particle' }, { a: 'مِنَ', t: 'mina', e: 'of' }, { a: 'الْجَارَّةِ', t: 'al-jārrati', e: 'the genitive particles' }, { a: 'الزَّائِدَةِ', t: 'az-zāʾidati', e: 'that are redundant' } ],
    [ { a: 'إِمَّا', t: 'immā', e: 'either' }, { a: 'ظَاهِرَةً،', t: 'ẓāhiratan', e: 'overt' }, NAHW, { g: ':' },
      OPEN, { a: 'كَمْ', t: 'kam', e: 'how many', q: 1 }, { a: 'مِنْ', t: 'min', e: 'a', q: 1 }, { a: 'فِئَةٍ', t: 'fiʾatin', e: 'company', q: 1 }, { a: 'قَلِيلَةٍ', t: 'qalīlatin', e: 'small', q: 1 }, { a: 'غَلَبَتْ', t: 'ghalabat', e: 'overcame', q: 1 }, { a: 'فِئَةً', t: 'fiʾatan', e: 'a company', q: 1 }, { a: 'كَثِيرَةً', t: 'kathīratan', e: 'large', q: 1 }, { a: 'بِإِذْنِ', t: 'bi-idhni', e: 'by the leave of', q: 1 }, { a: 'اللهِ', t: 'Allāhi', e: 'Allah', q: 1 }, CLOSE ],
    [ { a: 'وَإِمَّا', t: 'wa-immā', e: 'and either' }, { a: 'مُقَدَّرَةً', t: 'muqaddaratan', e: 'implicit' }, NAHW, { g: ':' } ],
    [ { a: 'كَمْ', t: 'kam', e: 'how many' }, { a: 'مُلُوكٍ', t: 'mulūkin', e: 'kings' }, { a: 'بَادَ', t: 'bāda', e: 'perished' }, { a: 'مُلْكُهُمْ', t: 'mulkuhum', e: 'their kingdom' },
      { a: 'وَنَعِيمِ', t: 'wa-naʿīmi', e: 'and the ease of' }, { a: 'سُوقَةٍ', t: 'sūqatin', e: 'commoners' }, { a: 'بَادُوا', t: 'bādū', e: 'who perished' } ],
  ] },
  { t: 'box', label: 'بقيّة أحكام كم الخبريّة', labelEn: 'remaining rulings of declarative kam', lines: [
    [ { a: 'الْأَصْلُ', t: 'al-aṣlu', e: 'the norm' }, { a: 'فِي', t: 'fī', e: 'for' }, { a: 'تَمْيِيزِ', t: 'tamyīzi', e: 'the specifier of' }, { a: 'كَمِ', t: 'kami', e: 'kam' }, { a: 'الْخَبَرِيَّةِ', t: 'al-khabariyyati', e: 'the declarative' }, { a: 'أَنْ', t: 'an', e: 'is' }, { a: 'يَكُونَ', t: 'yakūna', e: 'to be' }, { a: 'مُفْرَدًا', t: 'mufradan', e: 'singular' }, { a: 'مُنَكَّرًا', t: 'munakkaran', e: 'indefinite' }, { a: 'مُتَّصِلًا', t: 'muttaṣilan', e: 'joined' }, { a: 'بِهَا', t: 'bihā', e: 'to it' }, ELL,
      { a: 'وَيَجُوزُ', t: 'wa-yajūzu', e: 'and it is permitted' }, ELL ],
    [ { a: 'جَمْعُهُ', t: 'jamʿuhu', e: 'to pluralize it' }, { a: 'وَتَعْرِيفُهُ', t: 'wa-taʿrīfuhu', e: 'and to definitize it' }, { a: 'وَفَصْلُهُ،', t: 'wa-faṣluhu', e: 'and to separate it' },
      { a: 'وَيَجِبُ', t: 'wa-yajibu', e: 'and it is obligatory' }, { a: 'مِنَ', t: 'mina', e: 'to use' }, { a: 'الظَّاهِرَةِ', t: 'aẓ-ẓāhirati', e: 'the overt (min)' }, { a: 'عِنْدَ', t: 'ʿinda', e: 'upon' }, { a: 'الْفَصْلِ،', t: 'al-faṣli', e: 'separation' },
      NAHW, { g: ':' }, OPEN, { a: 'كَمْ', t: 'kam', e: 'how many', q: 1 }, { a: 'أَهْلَكْنَا', t: 'ahlaknā', e: 'We destroyed', q: 1 }, { a: 'قَبْلَهُمْ', t: 'qablahum', e: 'before them', q: 1 }, { a: 'مِنَ', t: 'mina', e: 'of', q: 1 }, { a: 'الْقُرُونِ', t: 'al-qurūni', e: 'the generations', q: 1 }, CLOSE ],
    [ { a: 'وَيَجُوزُ', t: 'wa-yajūzu', e: 'and it is permitted' }, { a: 'حَذْفُ', t: 'ḥadhfu', e: 'to omit' }, { a: 'تَمْيِيزِهَا', t: 'tamyīzihā', e: 'its specifier' }, { a: 'عِنْدَ', t: 'ʿinda', e: 'given' }, { a: 'قَرِينَةٍ،', t: 'qarīnatin', e: 'an indicator' }, NAHW, { g: ':' } ],
    [ { a: 'وَكَمْ', t: 'wa-kam', e: 'and how often' }, { a: 'عَلَّمْتُهُ', t: 'ʿallamtuhu', e: 'I taught him' }, { a: 'نَظْمَ', t: 'naẓma', e: 'the composing of' }, { a: 'الْقَوَافِي', t: 'al-qawāfī', e: 'rhymes' },
      { a: 'فَلَمَّا', t: 'fa-lammā', e: 'and when' }, { a: 'قَالَ', t: 'qāla', e: 'he uttered' }, { a: 'قَافِيَةً', t: 'qāfiyatan', e: 'a rhyme' }, { a: 'هَجَانِي', t: 'hajānī', e: 'he lampooned me' } ],
    [ { a: 'أَيْ', t: 'ay', e: 'i.e.' }, { a: 'كَمْ', t: 'kam', e: 'how many' }, { a: 'مَرَّةٍ', t: 'marratin', e: 'a time' }, { a: 'عَلَّمْتُهُ', t: 'ʿallamtuhu', e: 'I taught him' } ],
    [ { a: 'وَقَدْ', t: 'wa-qad', e: 'and sometimes' }, { a: 'يَكُونُ', t: 'yakūnu', e: 'is' }, { a: 'التَّمْيِيزُ', t: 'at-tamyīzu', e: 'the specifier' }, { a: 'مُؤَكِّدًا', t: 'muʾakkidan', e: 'corroborating' }, { a: 'غَيْرَ', t: 'ghayra', e: 'not' }, { a: 'مُفَسِّرٍ،', t: 'mufassirin', e: 'explanatory' },
      NAHW, { g: ':' }, OPEN, { a: 'إِنَّ', t: 'inna', e: 'indeed', q: 1 }, { a: 'عِدَّةَ', t: 'ʿiddata', e: 'the number of', q: 1 }, { a: 'الشُّهُورِ', t: 'ash-shuhūri', e: 'the months', q: 1 }, { a: 'عِنْدَ', t: 'ʿinda', e: 'with', q: 1 }, { a: 'اللهِ', t: 'Allāhi', e: 'Allah', q: 1 }, { a: 'اثْنَا', t: 'ithnā', e: 'is twelve', q: 1 }, { a: 'عَشَرَ', t: 'ʿashara', e: '', q: 1 }, { a: 'شَهْرًا', t: 'shahran', e: 'months', q: 1 }, CLOSE ],
  ] },
  { t: 'h2', c: 'red', ar: 'الثَّامِنُ: الْمُسْتَثْنَى', en: 'Eighth — the Excepted Noun (mustathnā)' },
  { t: 'line', w: [
    { a: 'الثَّامِنُ', t: 'ath-thāminu', e: 'the eighth (is)' }, { a: 'الْمُسْتَثْنَى،', t: 'al-mustathnā', e: 'the excepted' },
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' }, { a: 'مَا', t: 'mā', e: 'what' }, { a: 'أُخْرِجَ', t: 'ukhrija', e: 'is taken out' }, { a: 'مِنْ', t: 'min', e: 'from' }, { a: 'حُكْمِ', t: 'ḥukmi', e: 'the ruling of' }, { a: 'مَا', t: 'mā', e: 'what' }, { a: 'قَبْلَهُ', t: 'qablahu', e: 'precedes it' },
  ] },
  { t: 'box', label: 'أركان الاستثناء', labelEn: 'the pillars of exception', lines: [
    [ { a: 'لِلِاسْتِثْنَاءِ', t: 'li-l-istithnāʾi', e: 'exception has' }, { a: 'ثَلَاثَةُ', t: 'thalāthatu', e: 'three' }, { a: 'أَرْكَانٍ', t: 'arkānin', e: 'pillars' } ],
  ] },

  { t: 'page', n: '١٤٦' },
  { t: 'box', lines: [
    [ { a: 'الْأَوَّلُ', t: 'al-awwalu', e: 'the first', c: 'red' }, { a: 'الْمُسْتَثْنَى', t: 'al-mustathnā', e: 'that which is excepted' }, { a: 'مِنْهُ،', t: 'minhu', e: 'from' },
      { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' }, { a: 'مَا', t: 'mā', e: 'what' }, { a: 'أُخْرِجَ', t: 'ukhrija', e: 'is taken out' }, { a: 'مِنْهُ', t: 'minhu', e: 'from it' }, { a: 'الْمُسْتَثْنَى،', t: 'al-mustathnā', e: 'the excepted' },
      { a: 'نَحْوُ', t: 'naḥwu', e: 'such as' }, { a: 'الْقَوْمِ', t: 'al-qawmi', e: '“the people”' }, { a: 'فِي', t: 'fī', e: 'in' }, { a: 'قَوْلِنَا', t: 'qawlinā', e: 'our saying' }, { a: 'جَاءَ', t: 'jāʾa', e: 'came' }, { a: 'الْقَوْمُ', t: 'al-qawmu', e: 'the people' }, { a: 'إِلَّا', t: 'illā', e: 'except' }, { a: 'زَيْدًا', t: 'zaydan', e: 'Zayd' } ],
    [ { a: 'الثَّانِي', t: 'ath-thānī', e: 'the second', c: 'red' }, { a: 'أَدَاةُ', t: 'adātu', e: 'the instrument of' }, { a: 'الِاسْتِثْنَاءِ،', t: 'al-istithnāʾi', e: 'exception' },
      { a: 'نَحْوُ', t: 'naḥwu', e: 'such as' }, { a: 'إِلَّا', t: 'illā', e: '“except”' }, { a: 'فِي', t: 'fī', e: 'in' }, { a: 'قَوْلِنَا', t: 'qawlinā', e: 'our saying' }, { a: 'جَاءَ', t: 'jāʾa', e: 'came' }, { a: 'الْقَوْمُ', t: 'al-qawmu', e: 'the people' }, { a: 'إِلَّا', t: 'illā', e: 'except' }, { a: 'زَيْدًا', t: 'zaydan', e: 'Zayd' } ],
    [ { a: 'الثَّالِثُ', t: 'ath-thālithu', e: 'the third', c: 'red' }, { a: 'الْمُسْتَثْنَى،', t: 'al-mustathnā', e: 'the excepted' },
      { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' }, { a: 'مَا', t: 'mā', e: 'what' }, { a: 'أُخْرِجَ', t: 'ukhrija', e: 'is taken out' }, { a: 'مِنْ', t: 'min', e: 'from' }, { a: 'حُكْمِ', t: 'ḥukmi', e: 'the ruling of' }, { a: 'مَا', t: 'mā', e: 'what' }, { a: 'قَبْلَهُ،', t: 'qablahu', e: 'precedes it' },
      { a: 'نَحْوُ', t: 'naḥwu', e: 'such as' }, { a: 'زَيْدًا', t: 'zaydan', e: '“Zayd”' }, { a: 'فِي', t: 'fī', e: 'in' }, { a: 'قَوْلِنَا', t: 'qawlinā', e: 'our saying' }, { a: 'جَاءَ', t: 'jāʾa', e: 'came' }, { a: 'الْقَوْمُ', t: 'al-qawmu', e: 'the people' }, { a: 'إِلَّا', t: 'illā', e: 'except' }, { a: 'زَيْدًا', t: 'zaydan', e: 'Zayd' } ],
  ] },
  { t: 'box', label: 'الاستثناء التام وغير التام', labelEn: 'complete vs. incomplete exception', lines: [
    [ { a: 'الِاسْتِثْنَاءُ', t: 'al-istithnāʾu', e: 'exception' }, { a: 'قِسْمَانِ', t: 'qismāni', e: 'is two divisions' } ],
    [ { a: 'الْأَوَّلُ', t: 'al-awwalu', e: 'the first', c: 'red' }, { a: 'الِاسْتِثْنَاءُ', t: 'al-istithnāʾu', e: 'the exception' }, { a: 'التَّامُّ،', t: 'at-tāmmu', e: 'complete' },
      { a: 'وَيُسَمَّى', t: 'wa-yusammā', e: 'and it is called' }, { a: 'غَيْرَ', t: 'ghayra', e: 'non-' }, { a: 'مُفَرَّغٍ،', t: 'mufarraghin', e: 'vacated' },
      { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' }, { a: 'مَا', t: 'mā', e: 'what' }, { a: 'يَكُونُ', t: 'yakūnu', e: 'has' }, { a: 'فِيهِ', t: 'fīhi', e: 'in it' }, { a: 'الْمُسْتَثْنَى', t: 'al-mustathnā', e: 'that which is excepted' }, { a: 'مِنْهُ', t: 'minhu', e: 'from' }, { a: 'مَذْكُورًا،', t: 'madhkūran', e: 'mentioned' },
      NAHW, { g: ':' }, { a: 'جَاءَ', t: 'jāʾa', e: 'came' }, { a: 'الْقَوْمُ', t: 'al-qawmu', e: 'the people' }, { a: 'إِلَّا', t: 'illā', e: 'except' }, { a: 'زَيْدًا', t: 'zaydan', e: 'Zayd' } ],
    [ { a: 'الثَّانِي', t: 'ath-thānī', e: 'the second', c: 'red' }, { a: 'الِاسْتِثْنَاءُ', t: 'al-istithnāʾu', e: 'the exception' }, { a: 'غَيْرُ', t: 'ghayru', e: 'not' }, { a: 'التَّامِّ،', t: 'at-tāmmi', e: 'complete' },
      { a: 'وَيُسَمَّى', t: 'wa-yusammā', e: 'and it is called' }, { a: 'مُفَرَّغًا،', t: 'mufarraghan', e: 'vacated' },
      { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' }, { a: 'مَا', t: 'mā', e: 'what' }, { a: 'يَكُونُ', t: 'yakūnu', e: 'has' }, { a: 'فِيهِ', t: 'fīhi', e: 'in it' }, { a: 'الْمُسْتَثْنَى', t: 'al-mustathnā', e: 'that which is excepted' }, { a: 'مِنْهُ', t: 'minhu', e: 'from' }, { a: 'غَيْرَ', t: 'ghayra', e: 'not' }, { a: 'مَذْكُورٍ،', t: 'madhkūrin', e: 'mentioned' },
      { a: 'وَلَا', t: 'wa-lā', e: 'and it does not' }, { a: 'يَكُونُ', t: 'yakūnu', e: 'occur' }, { a: 'إِلَّا', t: 'illā', e: 'except' }, { a: 'بَعْدَ', t: 'baʿda', e: 'after' }, { a: 'نَفْيٍ', t: 'nafyin', e: 'a negation' }, { a: 'أَوْ', t: 'aw', e: 'or' }, { a: 'شِبْهِ', t: 'shibhi', e: 'a quasi-' }, { a: 'نَفْيٍ،', t: 'nafyin', e: 'negation' },
      { a: 'وَحِينَئِذٍ', t: 'wa-ḥīnaʾidhin', e: 'and in that case' }, { a: 'تَكُونُ', t: 'takūnu', e: 'becomes' }, { a: 'أَدَاةُ', t: 'adātu', e: 'the instrument of' }, { a: 'الِاسْتِثْنَاءِ', t: 'al-istithnāʾi', e: 'exception' }, { a: 'أَدَاةَ', t: 'adāta', e: 'an instrument of' }, { a: 'حَصْرٍ،', t: 'ḥaṣrin', e: 'restriction' },
      { a: 'وَلَا', t: 'wa-lā', e: 'and does not' }, { a: 'تَعْمَلُ', t: 'taʿmalu', e: 'govern' }, { a: 'إِلَّا،', t: 'illā', e: 'illā' },
      NAHW, { g: ':' }, { a: 'مَا', t: 'mā', e: 'is not' }, { a: 'مُحَمَّدٌ', t: 'muḥammadun', e: 'Muḥammad' }, { a: 'إِلَّا', t: 'illā', e: 'except' }, { a: 'رَسُولٌ،', t: 'rasūlun', e: 'a messenger' },
      { a: 'وَنَحْوُ', t: 'wa-naḥwu', e: 'and like' }, { g: ':' }, { a: 'لَا', t: 'lā', e: 'we do not' }, { a: 'نَعْبُدُ', t: 'naʿbudu', e: 'worship' }, { a: 'إِلَّا', t: 'illā', e: 'except' }, { a: 'اللهَ', t: 'Allāha', e: 'Allah' } ],
  ] },
  { t: 'box', label: 'أقسام الاستثناء التام', labelEn: 'divisions of complete exception', lines: [
    [ { a: 'الِاسْتِثْنَاءُ', t: 'al-istithnāʾu', e: 'the exception' }, { a: 'التَّامُّ', t: 'at-tāmmu', e: 'complete' }, { a: 'قِسْمَانِ', t: 'qismāni', e: 'is two divisions' }, { g: ':' } ],
    [ { a: 'الْأَوَّلُ', t: 'al-awwalu', e: 'the first', c: 'red' }, { a: 'الْمُتَّصِلُ،', t: 'al-muttaṣilu', e: 'the connected' },
      { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' }, { a: 'مَا', t: 'mā', e: 'what' }, { a: 'كَانَ', t: 'kāna', e: 'has' }, { a: 'الْمُسْتَثْنَى', t: 'al-mustathnā', e: 'the excepted' }, { a: 'مِنْ', t: 'min', e: 'of' }, { a: 'جِنْسِ', t: 'jinsi', e: 'the kind of' }, { a: 'الْمُسْتَثْنَى', t: 'al-mustathnā', e: 'that which is excepted' }, { a: 'مِنْهُ،', t: 'minhu', e: 'from' },
      NAHW, { g: ':' }, OPEN, { a: 'ثُمَّ', t: 'thumma', e: 'then', q: 1 }, { a: 'تَوَلَّيْتُمْ', t: 'tawallaytum', e: 'you turned away', q: 1 }, { a: 'إِلَّا', t: 'illā', e: 'except', q: 1 }, { a: 'قَلِيلًا', t: 'qalīlan', e: 'a few', q: 1 }, { a: 'مِنْكُمْ', t: 'minkum', e: 'of you', q: 1 }, CLOSE ],
    [ { a: 'الثَّانِي', t: 'ath-thānī', e: 'the second', c: 'red' }, { a: 'الْمُنْقَطِعُ،', t: 'al-munqaṭiʿu', e: 'the disconnected' },
      { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' }, { a: 'مَا', t: 'mā', e: 'what' }, { a: 'لَمْ', t: 'lam', e: 'does not' }, { a: 'يَكُنِ', t: 'yakuni', e: 'have' }, { a: 'الْمُسْتَثْنَى', t: 'al-mustathnā', e: 'the excepted' }, { a: 'مِنْ', t: 'min', e: 'of' }, { a: 'جِنْسِ', t: 'jinsi', e: 'the kind of' }, { a: 'الْمُسْتَثْنَى', t: 'al-mustathnā', e: 'that which is excepted' }, { a: 'مِنْهُ،', t: 'minhu', e: 'from' },
      { a: 'وَلَا', t: 'wa-lā', e: 'and it does not' }, { a: 'يَأْتِي', t: 'yaʾtī', e: 'come' }, { a: 'إِلَّا', t: 'illā', e: 'except' }, { a: 'إِذَا', t: 'idhā', e: 'when' }, { a: 'أَوْهَمَ', t: 'awhama', e: 'gives the impression' }, { a: 'الْمُسْتَثْنَى', t: 'al-mustathnā', e: 'that which is excepted' }, { a: 'مِنْهُ', t: 'minhu', e: 'from' }, { a: 'دُخُولَ', t: 'dukhūla', e: 'the inclusion of' }, { a: 'الْمُسْتَثْنَى', t: 'al-mustathnā', e: 'the excepted' }, { a: 'فِي', t: 'fī', e: 'in' }, { a: 'حُكْمِ', t: 'ḥukmi', e: 'the ruling of' }, { a: 'مَا', t: 'mā', e: 'what' }, { a: 'قَبْلَهُ،', t: 'qablahu', e: 'precedes it' } ],
    [ { a: 'وَحِينَئِذٍ', t: 'wa-ḥīnaʾidhin', e: 'and in that case' }, { a: 'تَكُونُ', t: 'takūnu', e: 'becomes' }, { a: 'أَدَاةُ', t: 'adātu', e: 'the instrument of' }, { a: 'الِاسْتِثْنَاءِ', t: 'al-istithnāʾi', e: 'exception' }, { a: 'لِلِاسْتِدْرَاكِ', t: 'li-l-istidrāki', e: 'for rectification' }, { a: 'بِمَعْنَى', t: 'bi-maʿnā', e: 'in the sense of' }, { a: 'لَكِنْ،', t: 'lākin', e: '“but”' },
      { a: 'لَا', t: 'lā', e: 'not' }, { a: 'لِلِاسْتِثْنَاءِ،', t: 'li-l-istithnāʾi', e: 'for exception' },
      NAHW, { g: ':' }, OPEN, { a: 'فَسَجَدُوا', t: 'fa-sajadū', e: 'so they prostrated', q: 1 }, { a: 'إِلَّا', t: 'illā', e: 'except', q: 1 }, { a: 'إِبْلِيسَ', t: 'iblīsa', e: 'Iblīs', q: 1 }, CLOSE ],
  ] },
  { t: 'box', label: 'أحكام المستثنى منه', labelEn: 'rulings of the mustathnā minhu', lines: [
    [ { a: 'لَا', t: 'lā', e: 'is not' }, { a: 'يَكُونُ', t: 'yakūnu', e: '' }, { a: 'الْمُسْتَثْنَى', t: 'al-mustathnā', e: 'that which is excepted' }, { a: 'مِنْهُ', t: 'minhu', e: 'from' }, { a: 'إِلَّا', t: 'illā', e: 'except' }, ELL ],
    [ { a: 'مَعْرِفَةً،', t: 'maʿrifatan', e: 'definite' }, NAHW, { g: ':' },
      { a: 'جَاءَ', t: 'jāʾa', e: 'came' }, { a: 'الْقَوْمُ', t: 'al-qawmu', e: 'the people' }, { a: 'إِلَّا', t: 'illā', e: 'except' }, { a: 'أَحْمَدَ', t: 'aḥmada', e: 'Aḥmad' } ],
    [ { a: 'أَوْ', t: 'aw', e: 'or' }, { a: 'نَكِرَةً', t: 'nakiratan', e: 'indefinite' }, { a: 'مُفِيدَةً،', t: 'mufīdatan', e: 'yet informative' }, NAHW, { g: ':' },
      { a: 'مَا', t: 'mā', e: 'did not' }, { a: 'جَاءَ', t: 'jāʾa', e: 'come' }, { a: 'أَحَدٌ', t: 'aḥadun', e: 'anyone' }, { a: 'إِلَّا', t: 'illā', e: 'except' }, { a: 'أَحْمَدَ،', t: 'aḥmada', e: 'Aḥmad' },
      { a: 'بِخِلَافِ', t: 'bi-khilāfi', e: 'unlike' }, { g: ':' }, { a: 'جَاءَ', t: 'jāʾa', e: 'came' }, { a: 'قَوْمٌ', t: 'qawmun', e: 'a people' }, { a: 'إِلَّا', t: 'illā', e: 'except' }, { a: 'خَالِدًا', t: 'khālidan', e: 'Khālid' } ],
  ] },
  { t: 'box', label: 'أدوات الاستثناء', labelEn: 'the instruments of exception', lines: [
    [ { a: 'أَدَاةُ', t: 'adātu', e: 'the instrument of' }, { a: 'الِاسْتِثْنَاءِ', t: 'al-istithnāʾi', e: 'exception' }, { a: 'تَكُونُ', t: 'takūnu', e: 'is' }, ELL ],
  ] },

  { t: 'page', n: '١٤٧' },
  { t: 'box', lines: [
    [ { a: 'حَرْفًا،', t: 'ḥarfan', e: 'a particle' }, { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' }, { a: 'إِلَّا', t: 'illā', e: 'illā' }, { g: '–' }, { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' }, { a: 'الْأَصْلُ', t: 'al-aṣlu', e: 'the base case' }, { a: 'فِي', t: 'fī', e: 'in' }, { a: 'بَابِ', t: 'bābi', e: 'the chapter of' }, { a: 'الِاسْتِثْنَاءِ', t: 'al-istithnāʾi', e: 'exception' }, { g: '–' }, { a: 'وَحَاشَا', t: 'wa-ḥāshā', e: 'and ḥāshā' } ],
    [ { a: 'وَفِعْلًا،', t: 'wa-fiʿlan', e: 'and a verb' }, { a: 'وَهُوَ', t: 'wa-huwa', e: 'and they are' }, { a: 'خَلَا', t: 'khalā', e: 'khalā' }, { a: 'وَعَدَا', t: 'wa-ʿadā', e: 'and ʿadā' }, { a: 'وَمَا', t: 'wa-mā', e: 'and' }, { a: 'خَلَا', t: 'khalā', e: 'mā khalā' }, { a: 'وَمَا', t: 'wa-mā', e: 'and' }, { a: 'عَدَا', t: 'ʿadā', e: 'mā ʿadā' }, { a: 'وَلَيْسَ', t: 'wa-laysa', e: 'and laysa' }, { a: 'وَلَا', t: 'wa-lā', e: 'and' }, { a: 'يَكُونُ،', t: 'yakūnu', e: 'lā yakūnu' },
      NAHW, { g: ':' }, { g: '«' }, { a: 'مَا', t: 'mā', e: 'whatever' }, { a: 'أَنْهَرَ', t: 'anhara', e: 'makes flow' }, { a: 'الدَّمَ', t: 'ad-dama', e: 'the blood' }, { a: 'وَذُكِرَ', t: 'wa-dhukira', e: 'and is mentioned' }, { a: 'اسْمُ', t: 'ismu', e: 'the name of' }, { a: 'اللهِ', t: 'Allāhi', e: 'Allah' }, { a: 'عَلَيْهِ،', t: 'ʿalayhi', e: 'over it' }, { a: 'فَكُلْ', t: 'fa-kul', e: 'then eat' }, { a: 'لَيْسَ', t: 'laysa', e: 'excepting' }, { a: 'السِّنَّ', t: 'as-sinna', e: 'the tooth' }, { a: 'وَالظُّفُرَ', t: 'wa-ẓ-ẓufura', e: 'and the nail' }, { g: '»' } ],
    [ { a: 'وَاسْمًا،', t: 'wa-isman', e: 'and a noun' }, { a: 'وَهُوَ', t: 'wa-huwa', e: 'and they are' }, { a: 'غَيْرُ', t: 'ghayru', e: 'ghayr' }, { a: 'وَسِوَى', t: 'wa-siwā', e: 'and siwā' } ],
  ] },
  { t: 'box', label: 'فائدة في هل خلا وعدا فعلان أو حرفان', labelEn: 'are khalā and ʿadā verbs or particles?', lines: [
    [ { a: 'خَلَا', t: 'khalā', e: 'khalā' }, { a: 'وَعَدَا', t: 'wa-ʿadā', e: 'and ʿadā' }, { a: 'فِعْلَانِ', t: 'fiʿlāni', e: 'are two verbs' }, { a: 'عِنْدَ', t: 'ʿinda', e: 'according to' }, { a: 'الْأَكْثَرِ،', t: 'al-akthari', e: 'the majority' },
      { a: 'وَحَرْفَا', t: 'wa-ḥarfā', e: 'and two particles of' }, { a: 'جَرٍّ', t: 'jarrin', e: 'the genitive' }, { a: 'عِنْدَ', t: 'ʿinda', e: 'according to' }, { a: 'الْبَعْضِ', t: 'al-baʿḍi', e: 'some' } ],
    [ { a: 'وَمَا', t: 'wa-mā', e: 'and' }, { a: 'خَلَا', t: 'khalā', e: 'mā khalā' }, { a: 'وَمَا', t: 'wa-mā', e: 'and' }, { a: 'عَدَا', t: 'ʿadā', e: 'mā ʿadā' }, { a: 'فِعْلَانِ', t: 'fiʿlāni', e: 'are two verbs' }, { a: 'عِنْدَ', t: 'ʿinda', e: 'according to' }, { a: 'الْكُلِّ', t: 'al-kulli', e: 'everyone' } ],
  ] },
  { t: 'box', label: 'أحكام المستثنى', labelEn: 'rulings of the mustathnā', lines: [
    [ { a: 'لَا', t: 'lā', e: 'is not' }, { a: 'يَكُونُ', t: 'yakūnu', e: '' }, { a: 'الْمُسْتَثْنَى', t: 'al-mustathnā', e: 'the excepted' }, { a: 'إِلَّا', t: 'illā', e: 'except' }, ELL ],
    [ { a: 'مَعْرِفَةً،', t: 'maʿrifatan', e: 'definite' }, NAHW, { g: ':' },
      { a: 'جَاءَ', t: 'jāʾa', e: 'came' }, { a: 'الْقَوْمُ', t: 'al-qawmu', e: 'the people' }, { a: 'إِلَّا', t: 'illā', e: 'except' }, { a: 'زَيْدًا', t: 'zaydan', e: 'Zayd' } ],
    [ { a: 'أَوْ', t: 'aw', e: 'or' }, { a: 'نَكِرَةً', t: 'nakiratan', e: 'indefinite' }, { a: 'مَخْصُوصَةً،', t: 'makhṣūṣatan', e: 'yet specified' }, NAHW, { g: ':' },
      { a: 'جَاءَ', t: 'jāʾa', e: 'came' }, { a: 'الْقَوْمُ', t: 'al-qawmu', e: 'the people' }, { a: 'إِلَّا', t: 'illā', e: 'except' }, { a: 'رَجُلًا', t: 'rajulan', e: 'a man' }, { a: 'مَرِيضًا،', t: 'marīḍan', e: 'who was ill' },
      { a: 'أَوْ', t: 'aw', e: 'or' }, { a: 'إِلَّا', t: 'illā', e: 'except' }, { a: 'رَجُلَ', t: 'rajula', e: 'a man of' }, { a: 'سُوءٍ،', t: 'sūʾin', e: 'evil' },
      { a: 'بِخِلَافِ', t: 'bi-khilāfi', e: 'unlike' }, { a: 'جَاءَ', t: 'jāʾa', e: 'came' }, { a: 'الْقَوْمُ', t: 'al-qawmu', e: 'the people' }, { a: 'إِلَّا', t: 'illā', e: 'except' }, { a: 'رَجُلًا', t: 'rajulan', e: 'a man' } ],
  ] },
  { t: 'box', label: 'إعراب المستثنى في الاستثناء المتّصل', labelEn: 'iʿrāb of the mustathnā in connected exception', lines: [
    [ { a: 'يَكُونُ', t: 'yakūnu', e: 'is' }, { a: 'الْمُسْتَثْنَى', t: 'al-mustathnā', e: 'the excepted' }, { a: 'فِي', t: 'fī', e: 'in' }, { a: 'الِاسْتِثْنَاءِ', t: 'al-istithnāʾi', e: 'the exception' }, { a: 'التَّامِّ', t: 'at-tāmmi', e: 'complete' }, { a: 'الْمُتَّصِلِ', t: 'al-muttaṣili', e: 'connected' }, { a: 'فِي', t: 'fī', e: 'in' }, { a: 'كَلَامٍ', t: 'kalāmin', e: 'speech' }, { a: 'مُوجَبٍ', t: 'mūjabin', e: 'affirmative' }, { a: 'مَنْصُوبًا،', t: 'manṣūban', e: 'accusative' },
      NAHW, { g: ':' }, OPEN, { a: 'فَشَرِبُوا', t: 'fa-sharibū', e: 'so they drank', q: 1 }, { a: 'مِنْهُ', t: 'minhu', e: 'from it', q: 1 }, { a: 'إِلَّا', t: 'illā', e: 'except', q: 1 }, { a: 'قَلِيلًا', t: 'qalīlan', e: 'a few', q: 1 }, { a: 'مِنْهُمْ', t: 'minhum', e: 'of them', q: 1 }, CLOSE ],
    [ { a: 'وَيَجُوزُ', t: 'wa-yajūzu', e: 'and it is permitted' }, { a: 'فِي', t: 'fī', e: 'for' }, { a: 'الْمُسْتَثْنَى', t: 'al-mustathnā', e: 'the excepted' }, { a: 'فِي', t: 'fī', e: 'in' }, { a: 'الِاسْتِثْنَاءِ', t: 'al-istithnāʾi', e: 'the exception' }, { a: 'التَّامِّ', t: 'at-tāmmi', e: 'complete' }, { a: 'الْمُتَّصِلِ', t: 'al-muttaṣili', e: 'connected' }, { a: 'فِي', t: 'fī', e: 'in' }, { a: 'غَيْرِ', t: 'ghayri', e: 'non-' }, { a: 'مُوجَبٍ', t: 'mūjabin', e: 'affirmative speech' }, ELL ],
    [ { a: 'النَّصْبُ،', t: 'an-naṣbu', e: 'the accusative' }, NAHW, { g: ':' },
      OPEN, { a: 'وَلَا', t: 'wa-lā', e: 'and let not', q: 1 }, { a: 'يَلْتَفِتْ', t: 'yaltafit', e: 'turn back', q: 1 }, { a: 'مِنْكُمْ', t: 'minkum', e: 'of you', q: 1 }, { a: 'أَحَدٌ', t: 'aḥadun', e: 'anyone', q: 1 }, { a: 'إِلَّا', t: 'illā', e: 'except', q: 1 }, { a: 'امْرَأَتَكَ', t: 'imraʾataka', e: 'your wife', q: 1 }, CLOSE ],
    [ { a: 'وَالْبَدَلُ', t: 'wa-l-badalu', e: 'and apposition (badal)' }, { a: 'مِنَ', t: 'mina', e: 'from' }, { a: 'الْمُسْتَثْنَى', t: 'al-mustathnā', e: 'that which is excepted' }, { a: 'مِنْهُ،', t: 'minhu', e: 'from' },
      NAHW, { g: ':' }, OPEN, { a: 'مَا', t: 'mā', e: 'they did not', q: 1 }, { a: 'فَعَلُوهُ', t: 'faʿalūhu', e: 'do it', q: 1 }, { a: 'إِلَّا', t: 'illā', e: 'except', q: 1 }, { a: 'قَلِيلٌ', t: 'qalīlun', e: 'a few', q: 1 }, { a: 'مِنْهُمْ', t: 'minhum', e: 'of them', q: 1 }, CLOSE ],
  ] },
  { t: 'box', label: 'المستثنى المقدّم', labelEn: 'the fronted mustathnā', lines: [
    [ { a: 'يَكُونُ', t: 'yakūnu', e: 'is' }, { a: 'الْمُسْتَثْنَى', t: 'al-mustathnā', e: 'the excepted' }, { a: 'الْمُقَدَّمُ', t: 'al-muqaddamu', e: 'placed before' }, { a: 'عَلَى', t: 'ʿalā', e: '' }, { a: 'الْمُسْتَثْنَى', t: 'al-mustathnā', e: 'that which is excepted' }, { a: 'مِنْهُ', t: 'minhu', e: 'from' }, { a: 'مَنْصُوبًا،', t: 'manṣūban', e: 'accusative' }, NAHW, { g: ':' } ],
    [ { a: 'وَمَا', t: 'wa-mā', e: 'and I have no' }, { a: 'لِي', t: 'lī', e: '' }, { a: 'إِلَّا', t: 'illā', e: 'except' }, { a: 'آلَ', t: 'āla', e: 'the family of' }, { a: 'أَحْمَدَ', t: 'aḥmada', e: 'Aḥmad' }, { a: 'شِيعَةٌ', t: 'shīʿatun', e: 'as a following' },
      { a: 'وَمَا', t: 'wa-mā', e: 'and I have no' }, { a: 'لِي', t: 'lī', e: '' }, { a: 'إِلَّا', t: 'illā', e: 'except' }, { a: 'مَذْهَبَ', t: 'madhhaba', e: 'the way of' }, { a: 'الْحَقِّ', t: 'al-ḥaqqi', e: 'truth' }, { a: 'مَذْهَبُ', t: 'madhhabu', e: 'as a way' } ],
  ] },
  { t: 'box', label: 'إعراب المستثنى بعد فعل استثناء', labelEn: 'iʿrāb of the mustathnā after an exception-verb', lines: [
    [ { a: 'يَكُونُ', t: 'yakūnu', e: 'is' }, { a: 'الْمُسْتَثْنَى', t: 'al-mustathnā', e: 'the excepted' }, { a: 'بَعْدَ', t: 'baʿda', e: 'after' }, { a: 'فِعْلِ', t: 'fiʿli', e: 'a verb of' }, { a: 'الِاسْتِثْنَاءِ', t: 'al-istithnāʾi', e: 'exception' }, { a: 'مَنْصُوبًا', t: 'manṣūban', e: 'accusative' }, { a: 'عَلَى', t: 'ʿalā', e: 'as' }, { a: 'الْمَفْعُولِيَّةِ،', t: 'al-mafʿūliyyati', e: 'an object' }, NAHW, { g: ':' } ],
  ] },

  { t: 'page', n: '١٤٨' },
  { t: 'box', lines: [
    [ { a: 'أَلَا', t: 'alā', e: 'lo' }, { a: 'كُلُّ', t: 'kullu', e: 'every' }, { a: 'شَيْءٍ', t: 'shayʾin', e: 'thing' }, { a: 'مَا', t: 'mā', e: 'save' }, { a: 'خَلَا', t: 'khalā', e: 'apart from' }, { a: 'اللهَ', t: 'Allāha', e: 'Allah' }, { a: 'بَاطِلُ', t: 'bāṭilu', e: 'is vain' } ],
  ] },
  { t: 'box', label: 'إعراب غير إذا كانت للاستثناء', labelEn: 'iʿrāb of ghayr when used for exception', lines: [
    [ { a: 'يَكُونُ', t: 'yakūnu', e: 'it is' }, ELL ],
    [ { a: 'إِعْرَابُ', t: 'iʿrābu', e: 'the iʿrāb of' }, { a: 'غَيْرٍ', t: 'ghayrin', e: 'ghayr' }, { a: 'مِثْلَ', t: 'mithla', e: 'like' }, { a: 'إِعْرَابِ', t: 'iʿrābi', e: 'the iʿrāb of' }, { a: 'الْمُسْتَثْنَى', t: 'al-mustathnā', e: 'the excepted' }, { a: 'بَعْدَ', t: 'baʿda', e: 'after' }, { a: 'إِلَّا،', t: 'illā', e: 'illā' } ],
    [ { a: 'وَإِعْرَابُ', t: 'wa-iʿrābu', e: 'and the iʿrāb of' }, { a: 'مَا', t: 'mā', e: 'what' }, { a: 'بَعْدَ', t: 'baʿda', e: 'follows' }, { a: 'غَيْرٍ', t: 'ghayrin', e: 'ghayr' }, { a: 'مَجْرُورًا', t: 'majrūran', e: 'is genitive' }, { a: 'عَلَى', t: 'ʿalā', e: 'by' }, { a: 'الْإِضَافَةِ', t: 'al-iḍāfati', e: 'annexation' } ],
  ] },
  { t: 'box', label: 'إعراب المستثنى في الاستثناء المنقطع', labelEn: 'iʿrāb of the mustathnā in disconnected exception', lines: [
    [ { a: 'يَكُونُ', t: 'yakūnu', e: 'is' }, { a: 'الْمُسْتَثْنَى', t: 'al-mustathnā', e: 'the excepted' }, { a: 'فِي', t: 'fī', e: 'in' }, { a: 'الْمُنْقَطِعِ', t: 'al-munqaṭiʿi', e: 'the disconnected' }, { a: 'مَنْصُوبًا،', t: 'manṣūban', e: 'accusative' },
      { a: 'وَنَحْوُ', t: 'wa-naḥwu', e: 'and like' }, { g: ':' }, OPEN, { a: 'فَسَجَدُوا', t: 'fa-sajadū', e: 'so they prostrated', q: 1 }, { a: 'إِلَّا', t: 'illā', e: 'except', q: 1 }, { a: 'إِبْلِيسَ', t: 'iblīsa', e: 'Iblīs', q: 1 }, CLOSE ],
  ] },
  { t: 'box', label: 'معنى حاشا وإعراب ما بعدها', labelEn: 'the sense of ḥāshā and what follows it', lines: [
    [ { a: 'حَاشَا', t: 'ḥāshā', e: 'ḥāshā' }, { a: 'مَوْضُوعَةٌ', t: 'mawḍūʿatun', e: 'is coined' }, { a: 'لِلِاسْتِثْنَاءِ', t: 'li-l-istithnāʾi', e: 'for exception' }, { a: 'مَعَ', t: 'maʿa', e: 'together with' }, { a: 'تَنْزِيهِ', t: 'tanzīhi', e: 'exalting' }, { a: 'الْمُسْتَثْنَى،', t: 'al-mustathnā', e: 'the excepted' },
      { a: 'وَيَكُونُ', t: 'wa-yakūnu', e: 'and is' }, { a: 'الْمُسْتَثْنَى', t: 'al-mustathnā', e: 'the excepted' }, { a: 'بَعْدَهَا', t: 'baʿdahā', e: 'after it' }, { a: 'مَجْرُورًا،', t: 'majrūran', e: 'genitive' },
      NAHW, { g: ':' }, { a: 'كُلُّ', t: 'kullu', e: 'all' }, { a: 'بَنِي', t: 'banī', e: 'the children of' }, { a: 'آدَمَ', t: 'ādama', e: 'Ādam' }, { a: 'خَطَّاءُونَ', t: 'khaṭṭāʾūna', e: 'are prone to error' }, { a: 'حَاشَا', t: 'ḥāshā', e: 'save' }, { a: 'الْأَنْبِيَاءِ', t: 'al-anbiyāʾi', e: 'the prophets' } ],
  ] },
  { t: 'box', label: 'غير بمعنى إلا', labelEn: 'ghayr in the sense of illā', lines: [
    [ { a: 'كَلِمَةُ', t: 'kalimatu', e: 'the word' }, { a: 'غَيْرٍ', t: 'ghayrin', e: 'ghayr' }, { a: 'مَوْضُوعَةٌ', t: 'mawḍūʿatun', e: 'is coined' }, { a: 'لِلصِّفَةِ،', t: 'li-ṣ-ṣifati', e: 'for description' },
      NAHW, { g: ':' }, OPEN, { a: 'لَا', t: 'lā', e: 'do not', q: 1 }, { a: 'تَدْخُلُوا', t: 'tadkhulū', e: 'enter', q: 1 }, { a: 'بُيُوتًا', t: 'buyūtan', e: 'houses', q: 1 }, { a: 'غَيْرَ', t: 'ghayra', e: 'other than', q: 1 }, { a: 'بُيُوتِكُمْ', t: 'buyūtikum', e: 'your houses', q: 1 }, { a: 'حَتَّى', t: 'ḥattā', e: 'until', q: 1 }, { a: 'تَسْتَأْنِسُوا', t: 'tastaʾnisū', e: 'you ask leave', q: 1 }, { a: 'وَتُسَلِّمُوا', t: 'wa-tusallimū', e: 'and greet', q: 1 }, { a: 'عَلَى', t: 'ʿalā', e: '', q: 1 }, { a: 'أَهْلِهَا', t: 'ahlihā', e: 'their people', q: 1 }, CLOSE ],
    [ { a: 'وَقَدْ', t: 'wa-qad', e: 'and sometimes' }, { a: 'تُسْتَعْمَلُ', t: 'tustaʿmalu', e: 'it is used' }, { a: 'لِلِاسْتِثْنَاءِ،', t: 'li-l-istithnāʾi', e: 'for exception' },
      NAHW, { g: ':' }, { a: 'جَاءَ', t: 'jāʾa', e: 'came' }, { a: 'الْأَوْلَادُ', t: 'al-awlādu', e: 'the children' }, { a: 'غَيْرَ', t: 'ghayra', e: 'except' }, { a: 'زَيْدٍ', t: 'zaydin', e: 'Zayd' } ],
  ] },
  { t: 'box', label: 'إلا بمعنى غير', labelEn: 'illā in the sense of ghayr', lines: [
    [ { a: 'كَلِمَةُ', t: 'kalimatu', e: 'the word' }, { a: 'إِلَّا', t: 'illā', e: 'illā' }, { a: 'مَوْضُوعَةٌ', t: 'mawḍūʿatun', e: 'is coined' }, { a: 'لِلِاسْتِثْنَاءِ،', t: 'li-l-istithnāʾi', e: 'for exception' },
      { a: 'وَقَدْ', t: 'wa-qad', e: 'and sometimes' }, { a: 'تُسْتَعْمَلُ', t: 'tustaʿmalu', e: 'it is used' }, { a: 'لِلصِّفَةِ،', t: 'li-ṣ-ṣifati', e: 'for description' },
      NAHW, { g: ':' }, { a: 'النَّاسُ', t: 'an-nāsu', e: 'the people' }, { a: 'هَلْكَى', t: 'halkā', e: 'are ruined' }, { a: 'إِلَّا', t: 'illā', e: 'except' }, { a: 'الْعَالِمُونَ،', t: 'al-ʿālimūna', e: 'the scholars' } ],
  ] },

  { t: 'page', n: '١٤٩' },
  { t: 'box', lines: [
    [ { a: 'وَالْعَالِمُونَ', t: 'wa-l-ʿālimūna', e: 'and the scholars' }, { a: 'هَلْكَى', t: 'halkā', e: 'are ruined' }, { a: 'إِلَّا', t: 'illā', e: 'except' }, { a: 'الْعَامِلُونَ،', t: 'al-ʿāmilūna', e: 'those who act' },
      { a: 'وَالْعَامِلُونَ', t: 'wa-l-ʿāmilūna', e: 'and those who act' }, { a: 'هَلْكَى', t: 'halkā', e: 'are ruined' }, { a: 'إِلَّا', t: 'illā', e: 'except' }, { a: 'الْمُخْلِصُونَ،', t: 'al-mukhliṣūna', e: 'the sincere' },
      { a: 'وَمِنْهُ', t: 'wa-minhu', e: 'and of it is' }, { g: ':' }, OPEN, { a: 'لَوْ', t: 'law', e: 'if', q: 1 }, { a: 'كَانَ', t: 'kāna', e: 'there were', q: 1 }, { a: 'فِيهِمَا', t: 'fīhimā', e: 'in them two', q: 1 }, { a: 'آلِهَةٌ', t: 'ālihatun', e: 'gods', q: 1 }, { a: 'إِلَّا', t: 'illā', e: 'other than', q: 1 }, { a: 'اللهُ', t: 'Allāhu', e: 'Allah', q: 1 }, { a: 'لَفَسَدَتَا', t: 'la-fasadatā', e: 'they would both have gone to ruin', q: 1 }, CLOSE,
      { a: 'وَقَوْلُكَ', t: 'wa-qawluka', e: 'and your saying' }, { g: ':' }, { a: 'لَا', t: 'lā', e: 'there is no' }, { a: 'إِلَهَ', t: 'ilāha', e: 'god' }, { a: 'إِلَّا', t: 'illā', e: 'except' }, { a: 'اللهُ.', t: 'Allāhu', e: 'Allah' } ],
  ] },
  { t: 'box', label: 'مسألة', labelEn: 'point', lines: [
    [ { a: 'قَدْ', t: 'qad', e: 'sometimes' }, { a: 'تَجِيءُ', t: 'tajīʾu', e: 'comes' }, { a: 'كَلِمَةُ', t: 'kalimatu', e: 'the word' }, { a: 'اللَّهُمَّ', t: 'allāhumma', e: 'allāhumma' }, { a: 'قَبْلَ', t: 'qabla', e: 'before' }, { a: 'إِلَّا', t: 'illā', e: 'illā' }, { a: 'إِيذَانًا', t: 'īdhānan', e: 'as a signal of' }, { a: 'بِنُدْرَةِ', t: 'bi-nudrati', e: 'the rarity of' }, { a: 'الْمُسْتَثْنَى،', t: 'al-mustathnā', e: 'the excepted' }, { a: 'مِثْلُ', t: 'mithlu', e: 'like' }, { g: ':' },
      { a: 'لَا', t: 'lā', e: 'does not' }, { a: 'يَغِيبُ', t: 'yaghību', e: 'absent himself' }, { a: 'هَذَا', t: 'hādhā', e: 'this' }, { a: 'الرَّجُلُ', t: 'ar-rajulu', e: 'man' }, { a: 'الصَّالِحُ', t: 'aṣ-ṣāliḥu', e: 'righteous' }, { a: 'عَنِ', t: 'ʿani', e: 'from' }, { a: 'الصَّفِّ', t: 'aṣ-ṣaffi', e: 'the row' }, { a: 'الْأَوَّلِ', t: 'al-awwali', e: 'first' },
      { a: 'اللَّهُمَّ', t: 'allāhumma', e: 'unless indeed' }, { a: 'إِلَّا', t: 'illā', e: '' }, { a: 'أَنْ', t: 'an', e: 'that' }, { a: 'يَكُونَ', t: 'yakūna', e: 'he be' }, { a: 'مَرِيضًا', t: 'marīḍan', e: 'ill' } ],
  ] },
  { t: 'h2', c: 'red', ar: 'التَّاسِعُ: خَبَرُ الْأَفْعَالِ النَّاقِصَةِ', en: 'Ninth — the Predicate of the Defective Verbs' },
  { t: 'line', w: [
    { a: 'التَّاسِعُ', t: 'at-tāsiʿu', e: 'the ninth (is)' }, { a: 'خَبَرُ', t: 'khabaru', e: 'the predicate of' }, { a: 'الْأَفْعَالِ', t: 'al-afʿāli', e: 'the verbs' }, { a: 'النَّاقِصَةِ،', t: 'an-nāqiṣati', e: 'defective (kāna & sisters)' },
    NAHW, { g: ':' }, OPEN, { a: 'إِنَّهُ', t: 'innahu', e: 'indeed he', q: 1 }, { a: 'كَانَ', t: 'kāna', e: 'was', q: 1 }, { a: 'صِدِّيقًا', t: 'ṣiddīqan', e: 'a man of truth', q: 1 }, { a: 'نَبِيًّا', t: 'nabiyyan', e: 'a prophet', q: 1 }, CLOSE,
  ] },
  { t: 'box', label: 'مسألة', labelEn: 'point', lines: [
    [ { a: 'قَدْ', t: 'qad', e: 'sometimes' }, { a: 'يَتَقَدَّمُ', t: 'yataqaddamu', e: 'precedes' }, { a: 'خَبَرُ', t: 'khabaru', e: 'the predicate of' }, { a: 'كَانَ', t: 'kāna', e: 'kāna' }, { a: 'وَأَخَوَاتِهَا', t: 'wa-akhawātihā', e: 'and its sisters' }, { a: 'عَلَى', t: 'ʿalā', e: '' }, { a: 'اسْمِهَا،', t: 'ismihā', e: 'its noun' },
      NAHW, { g: ':' }, { a: 'لَيْسَ', t: 'laysa', e: 'not are' }, { a: 'سَوَاءً', t: 'sawāʾan', e: 'equal' }, { a: 'عَالِمٌ', t: 'ʿālimun', e: 'a knowledgeable one' }, { a: 'وَجَهُولٌ', t: 'wa-jahūlun', e: 'and an ignorant one' } ],
  ] },
  { t: 'box', label: 'مسألة', labelEn: 'point', lines: [
    [ { a: 'وَيَجُوزُ', t: 'wa-yajūzu', e: 'and it is permitted' }, { a: 'تَقْدِيمُ', t: 'taqdīmu', e: 'to place' }, { a: 'الْخَبَرِ', t: 'al-khabari', e: 'the predicate' }, { a: 'عَلَى', t: 'ʿalā', e: 'before' }, { a: 'هَذِهِ', t: 'hādhihi', e: 'these' }, { a: 'الْأَفْعَالِ،', t: 'al-afʿāli', e: 'verbs' },
      NAHW, { g: ':' }, { a: 'قَائِمًا', t: 'qāʾiman', e: 'standing' }, { a: 'كَانَ', t: 'kāna', e: 'was' }, { a: 'زَيْدٌ', t: 'zaydun', e: 'Zayd' } ],
  ] },

  { t: 'page', n: '١٥٠' },
  { t: 'box', lines: [
    [ { a: 'إِلَّا', t: 'illā', e: 'except' }, { a: 'مَا', t: 'mā', e: 'what' }, { a: 'فِي', t: 'fī', e: 'has at' }, { a: 'أَوَّلِهِ', t: 'awwalihi', e: 'its beginning' }, { a: 'مَا', t: 'mā', e: 'mā' }, { a: 'مَصْدَرِيَّةٌ', t: 'maṣdariyyatun', e: 'the maṣdar-forming' }, { a: 'أَوْ', t: 'aw', e: 'or' }, { a: 'مَا', t: 'mā', e: 'mā' }, { a: 'نَافِيَةٌ', t: 'nāfiyatun', e: 'the negating' } ],
  ] },
  { t: 'h2', c: 'red', ar: 'الْعَاشِرُ: خَبَرُ الْحُرُوفِ الْمُشَبَّهَةِ بِلَيْسَ', en: 'Tenth — the Predicate of the Particles Resembling laysa' },
  { t: 'line', w: [
    { a: 'الْعَاشِرُ', t: 'al-ʿāshiru', e: 'the tenth (is)' }, { a: 'خَبَرُ', t: 'khabaru', e: 'the predicate of' }, { a: 'الْحُرُوفِ', t: 'al-ḥurūfi', e: 'the particles' }, { a: 'الْمُشَبَّهَةِ', t: 'al-mushabbahati', e: 'resembling' }, { a: 'بِلَيْسَ،', t: 'bi-laysa', e: 'laysa' },
    { a: 'وَهِيَ', t: 'wa-hiya', e: 'and they are' }, ELL,
  ] },
  { t: 'box', lines: [
    [ { a: 'مَا،', t: 'mā', e: 'mā' }, NAHW, { g: ':' },
      OPEN, { a: 'مَا', t: 'mā', e: 'not is', q: 1 }, { a: 'هَذَا', t: 'hādhā', e: 'this', q: 1 }, { a: 'بَشَرًا', t: 'basharan', e: 'a human', q: 1 }, CLOSE ],
    [ { a: 'وَلَا،', t: 'wa-lā', e: 'and lā' }, NAHW, { g: ':' },
      { a: 'لَا', t: 'lā', e: 'no' }, { a: 'شَيْءٌ', t: 'shayʾun', e: 'thing is' }, { a: 'مُشَابِهًا', t: 'mushābihan', e: 'resembling' }, { a: 'للهِ', t: 'lillāhi', e: 'Allah' } ],
    [ { a: 'وَلَاتَ،', t: 'wa-lāta', e: 'and lāta' }, NAHW, { g: ':' },
      OPEN, { a: 'وَلَاتَ', t: 'wa-lāta', e: 'but it was not', q: 1 }, { a: 'حِينَ', t: 'ḥīna', e: 'a time of', q: 1 }, { a: 'مَنَاصٍ', t: 'manāṣin', e: 'escape', q: 1 }, CLOSE ],
  ] },
  { t: 'h2', c: 'red', ar: 'الْحَادِيَ عَشَرَ: اسْمُ الْحُرُوفِ الْمُشَبَّهَةِ بِالْفِعْلِ', en: 'Eleventh — the Noun of the Particles Resembling the Verb' },
  { t: 'line', w: [
    { a: 'الْحَادِيَ', t: 'al-ḥādiya', e: 'the eleventh (is)' }, { a: 'عَشَرَ', t: 'ʿashara', e: '' }, { a: 'اسْمُ', t: 'ismu', e: 'the noun of' }, { a: 'الْحُرُوفِ', t: 'al-ḥurūfi', e: 'the particles' }, { a: 'الْمُشَبَّهَةِ', t: 'al-mushabbahati', e: 'resembling' }, { a: 'بِالْفِعْلِ،', t: 'bi-l-fiʿli', e: 'the verb (inna & sisters)' },
    NAHW, { g: ':' }, OPEN, { a: 'إِنَّ', t: 'inna', e: 'indeed', q: 1 }, { a: 'اللهَ', t: 'Allāha', e: 'Allah', q: 1 }, { a: 'رَحِيمٌ', t: 'raḥīmun', e: 'is Merciful', q: 1 }, CLOSE,
  ] },
  { t: 'h2', c: 'red', ar: 'الثَّانِيَ عَشَرَ: اسْمُ لَا لِنَفْيِ الْجِنْسِ', en: 'Twelfth — the Noun of lā that Negates the Genus' },
  { t: 'line', w: [
    { a: 'الثَّانِيَ', t: 'ath-thāniya', e: 'the twelfth (is)' }, { a: 'عَشَرَ', t: 'ʿashara', e: '' }, { a: 'اسْمُ', t: 'ismu', e: 'the noun of' }, { a: 'لَا', t: 'lā', e: 'lā' }, { a: 'لِنَفْيِ', t: 'li-nafyi', e: 'that negates' }, { a: 'الْجِنْسِ', t: 'al-jinsi', e: 'the genus' },
  ] },
  { t: 'box', label: 'مسألة', labelEn: 'point', lines: [
    [ { a: 'يَكُونُ', t: 'yakūnu', e: 'is' }, { a: 'اسْمُ', t: 'ismu', e: 'the noun of' }, { a: 'لَا', t: 'lā', e: 'lā' }, { a: 'لِنَفْيِ', t: 'li-nafyi', e: 'that negates' }, { a: 'الْجِنْسِ', t: 'al-jinsi', e: 'the genus' }, ELL ],
    [ { a: 'مَنْصُوبًا', t: 'manṣūban', e: 'accusative' }, { a: 'لَفْظًا', t: 'lafẓan', e: 'in form' }, { a: 'إِنْ', t: 'in', e: 'if' }, { a: 'كَانَ', t: 'kāna', e: 'it is' }, ELL ],
    [ { a: 'مُضَافًا،', t: 'muḍāfan', e: 'annexed' }, NAHW, { g: ':' },
      { a: 'لَا', t: 'lā', e: 'no' }, { a: 'عَمَلَ', t: 'ʿamala', e: 'deed of' }, { a: 'مُرَاءٍ', t: 'murāʾin', e: 'a show-off' }, { a: 'مَقْبُولٌ', t: 'maqbūlun', e: 'is accepted' } ],
    [ { a: 'أَوْ', t: 'aw', e: 'or' }, { a: 'شَبِيهًا', t: 'shabīhan', e: 'resembling' }, { a: 'بِالْمُضَافِ،', t: 'bi-l-muḍāfi', e: 'the annexed' },
      { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' }, { a: 'الْعَامِلُ', t: 'al-ʿāmilu', e: 'what governs' }, { a: 'فِيمَا', t: 'fīmā', e: 'what' }, { a: 'بَعْدَهُ،', t: 'baʿdahu', e: 'follows it' },
      NAHW, { g: ':' }, { a: 'لَا', t: 'lā', e: 'no' }, { a: 'عَاصِيًا', t: 'ʿāṣiyan', e: 'one disobeying' }, { a: 'أُمَّهُ', t: 'ummahu', e: 'his mother' }, { a: 'وَأَبَاهُ', t: 'wa-abāhu', e: 'and his father' }, { a: 'نَاجِحٌ', t: 'nājiḥun', e: 'succeeds' } ],
    [ { a: 'وَمَنْصُوبًا', t: 'wa-manṣūban', e: 'and accusative' }, { a: 'مَحَلًّا', t: 'maḥallan', e: 'in position' }, { a: 'فِيمَا', t: 'fīmā', e: 'in what' }, { a: 'سِوَاهُمَا،', t: 'siwāhumā', e: 'is other than those two' }, { a: 'مَبْنِيًّا', t: 'mabniyyan', e: 'being indeclinable' } ],
    [ { a: 'عَلَى', t: 'ʿalā', e: 'upon' }, { a: 'الْفَتْحِ،', t: 'al-fatḥi', e: 'the fatḥah' }, { a: 'إِنْ', t: 'in', e: 'if' }, { a: 'كَانَ', t: 'kāna', e: 'it is' }, { a: 'مُوَحَّدًا', t: 'muwaḥḥadan', e: 'singular' }, { a: 'أَوْ', t: 'aw', e: 'or' }, { a: 'جَمْعَ', t: 'jamʿa', e: 'a plural of' }, { a: 'تَكْسِيرٍ،', t: 'taksīrin', e: 'breaking' },
      NAHW, { g: ':' }, { a: 'لَا', t: 'lā', e: 'no' }, { a: 'رَجُلَ', t: 'rajula', e: 'man' }, { a: 'وَلَا', t: 'wa-lā', e: 'and no' }, { a: 'رِجَالَ', t: 'rijāla', e: 'men' } ],
    [ { a: 'وَعَلَى', t: 'wa-ʿalā', e: 'and upon' }, { a: 'الْفَتْحِ', t: 'al-fatḥi', e: 'the fatḥah' }, { a: 'أَوِ', t: 'awi', e: 'or' }, { a: 'الْكَسْرِ', t: 'al-kasri', e: 'the kasrah' }, { a: 'إِنْ', t: 'in', e: 'if' }, { a: 'كَانَ', t: 'kāna', e: 'it is' }, { a: 'جَمْعَ', t: 'jamʿa', e: 'a plural of' }, { a: 'مُؤَنَّثٍ', t: 'muʾannathin', e: 'the feminine' }, { a: 'سَالِمًا،', t: 'sāliman', e: 'sound' },
      NAHW, { g: ':' }, { a: 'لَا', t: 'lā', e: 'no' }, { a: 'مُسْلِمَاتِ', t: 'muslimāti', e: 'Muslim women' }, { a: 'وَلَا', t: 'wa-lā', e: 'and no' }, { a: 'مُسْلِمَاتٍ', t: 'muslimātin', e: 'Muslim women' } ],
  ] },
];

if (typeof module !== 'undefined') { module.exports = { DATA_M2B }; }
