/* ── al-Kubrā fī an-Naḥw — المقصد الأول · الباب الثاني في الحرف (pp. 41–…) ──
   The Particle. Begins with الفصل الأول في الحرف العامل → حروف الجر.
   Reuses shared glyphs from muqaddimah.js. مسألة/فائدة commentary boxes & footnotes omitted.   */

const DATA_M1_BAB2 = [
  { t: 'page', n: '٤١' },

  { t: 'h1', ar: 'الْبَابُ الثَّانِي فِي الْحَرْفِ', en: 'The Second Chapter — On the Particle' },
  { t: 'line', w: [
    { a: 'وَفِيهِ', t: 'wa-fīhi', e: 'and in it (are)' },
    { a: 'فَصْلَانِ', t: 'faṣlāni', e: 'two sections' },
  ] },

  { t: 'h2', c: 'green', ar: 'الْفَصْلُ الْأَوَّلُ فِي الْحَرْفِ الْعَامِلِ', en: 'First Section — On the governing particle' },
  { t: 'line', w: [
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
    { a: 'نَوْعَانِ', t: 'nawʿāni', e: 'two types' }, { g: ':' },
  ] },

  { t: 'h2', c: 'green', ar: 'النَّوْعُ الْأَوَّلُ: حُرُوفٌ تَعْمَلُ فِي الِاسْمِ', en: 'First type — particles that operate on the noun' },
  { t: 'line', w: [
    { a: 'وَهِيَ', t: 'wa-hiya', e: 'and they are' },
    { a: 'أَرْبَعَةُ', t: 'arbaʿatu', e: 'four' },
    { a: 'أَقْسَامٍ', t: 'aqsāmin', e: 'divisions' }, { g: ':' },
  ] },

  { t: 'h2', c: 'blue', ar: 'الْقِسْمُ الْأَوَّلُ: حُرُوفٌ تَجُرُّ اسْمًا وَاحِدًا', en: 'First division — particles that put one noun in the genitive' },
  { t: 'line', w: [
    { a: 'وَتُسَمَّى', t: 'wa-tusammā', e: 'and they are called' },
    { a: 'حُرُوفَ', t: 'ḥurūfa', e: 'the particles of' },
    { a: 'الْجَرِّ،', t: 'al-jarri', e: 'genitive (prepositions)' },
    { a: 'وَهِيَ', t: 'wa-hiya', e: 'and they are' },
    { a: 'ثَلَاثَةُ', t: 'thalāthatu', e: 'three' },
    { a: 'أَضْرُبٍ', t: 'aḍrubin', e: 'kinds' }, { g: ':' },
  ] },

  { t: 'h2', c: 'green', ar: 'الضَّرْبُ الْأَوَّلُ: حَرْفُ الْجَرِّ الْأَصْلِيُّ', en: 'First kind — the original preposition' },
  { t: 'line', w: [
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
    { a: 'مَا', t: 'mā', e: 'what' },
    { a: 'يُفِيدُ', t: 'yufīdu', e: 'gives' },
    { a: 'مَعْنًى', t: 'maʿnan', e: 'a meaning' },
    { a: 'خَاصًّا،', t: 'khāṣṣan', e: 'special' },
    { a: 'وَيَكُونُ', t: 'wa-yakūnu', e: 'and it is' },
    { a: 'مَعَ', t: 'maʿa', e: 'with' },
    { a: 'مَجْرُورِهِ', t: 'majrūrihi', e: 'its genitive' },
    { a: 'مَنْصُوبًا', t: 'manṣūban', e: 'in the accusative' },
    { a: 'مَحَلًّا', t: 'maḥallan', e: 'positionally' },
    { a: 'مَعْمُولًا', t: 'maʿmūlan', e: 'governed' },
    { a: 'لِفِعْلٍ', t: 'li-fiʿlin', e: 'by a verb' },
    { a: 'أَوْ', t: 'aw', e: 'or' },
    { a: 'شِبْهِ', t: 'shibhi', e: 'something verb-' },
    { a: 'الْفِعْلِ،', t: 'al-fiʿli', e: 'like' },
  ] },

  /* ── the bāʾ ── */
  { t: 'page', n: '٤٢' },
  { t: 'line', w: [
    { a: 'وَهِيَ', t: 'wa-hiya', e: 'and they are' },
    { a: 'ثَلَاثَةَ', t: 'thalāthata', e: 'thir-' },
    { a: 'عَشَرَ', t: 'ʿashara', e: '-teen' }, { g: ':' },
  ] },
  { t: 'line', w: [
    { a: 'الْأَوَّلُ', t: 'al-awwalu', e: 'the first' }, { g: ':' },
    { a: 'الْبَاءُ،', t: 'al-bāʾu', e: 'the bāʾ' },
  ] },
  { t: 'box', label: 'معنى الباء', labelEn: 'Meaning of the bāʾ', lines: [
    [
      { a: 'مَعْنَى', t: 'maʿnā', e: 'the meaning of' },
      { a: 'الْبَاءِ', t: 'al-bāʾi', e: 'the bāʾ is' },
      { a: 'الْإِلْصَاقُ', t: 'al-ilṣāqu', e: 'adhesion (ilṣāq)' },
    ],
  ] },
  { t: 'h2', c: 'plain', ar: 'إِعْرَابُ الْبَاءِ مَعَ مَجْرُورِهِ', en: 'Parsing the bāʾ with its genitive' },
  { t: 'line', w: [
    { a: 'تَكُونُ', t: 'takūnu', e: 'the bāʾ is' },
    { a: 'الْبَاءُ', t: 'al-bāʾu', e: '' },
    { a: 'مَعَ', t: 'maʿa', e: 'with' },
    { a: 'مَجْرُورِهَا', t: 'majrūrihā', e: 'its genitive' },
    { a: 'بِمَعْنَى', t: 'bi-maʿnā', e: 'in the sense of' },
    ELL,
  ] },
  { t: 'line', w: [
    { a: 'الْمَفْعُولِ', t: 'al-mafʿūli', e: 'the absolute' },
    { a: 'الْمُطْلَقِ،', t: 'al-muṭlaqi', e: 'object (maf‘ūl muṭlaq)' },
    NAHW, { g: ':' }, OPEN,
    { a: 'خُذِ', t: 'khudhi', e: 'take', q: 1 },
    { a: 'الْكِتَابَ', t: 'al-kitāba', e: 'the Scripture', q: 1 },
    { a: 'بِقُوَّةٍ', t: 'bi-quwwatin', e: 'with strength', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'أَوِ', t: 'awi', e: 'or' },
    { a: 'الْمَفْعُولِ', t: 'al-mafʿūli', e: 'the direct' },
    { a: 'بِهِ،', t: 'bihi', e: 'object (maf‘ūl bih)' },
    NAHW, { g: ':' }, OPEN,
    { a: 'فَلَمَّا', t: 'fa-lammā', e: 'so when', q: 1 },
    { a: 'ذَهَبُوا', t: 'dhahabū', e: 'they took', q: 1 },
    { a: 'بِهِ', t: 'bihi', e: 'him away', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'أَوِ', t: 'awi', e: 'or' },
    { a: 'الْمَفْعُولِ', t: 'al-mafʿūli', e: 'the adverbial' },
    { a: 'فِيهِ', t: 'fīhi', e: 'object (maf‘ūl fīh)' },
    ELL,
  ] },
  { t: 'line', w: [
    { a: 'لِلْمَكَانِ،', t: 'lil-makāni', e: 'for place' },
    NAHW, { g: ':' }, OPEN,
    { a: 'وَلَقَدْ', t: 'wa-laqad', e: 'and certainly', q: 1 },
    { a: 'نَصَرَكُمُ', t: 'naṣarakumu', e: 'helped you', q: 1 },
    { a: 'اللهُ', t: 'Allāhu', e: 'Allah', q: 1 },
    { a: 'بِبَدْرٍ', t: 'bi-badrin', e: 'at Badr', q: 1 },
    CLOSE,
  ] },
  { t: 'page', n: '٤٣' },
  { t: 'line', w: [
    { a: 'أَوِ', t: 'awi', e: 'or' },
    { a: 'الزَّمَانِ،', t: 'az-zamāni', e: 'for time' },
    NAHW, { g: ':' }, OPEN,
    { a: 'يُسَبِّحُونَ', t: 'yusabbiḥūna', e: 'they glorify', q: 1 },
    { a: 'لَهُ', t: 'lahu', e: 'Him', q: 1 },
    { a: 'بِالَّيْلِ', t: 'bil-layli', e: 'by night', q: 1 },
    { a: 'وَالنَّهَارِ', t: 'wan-nahāri', e: 'and day', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'أَوِ', t: 'awi', e: 'or' },
    { a: 'الْمَفْعُولِ', t: 'al-mafʿūli', e: 'the causative' },
    { a: 'لَهُ،', t: 'lahu', e: 'object (maf‘ūl lah)' },
    NAHW, { g: ':' }, OPEN,
    { a: 'فَأَهْلَكْنَاهُمْ', t: 'fa-ahlaknāhum', e: 'so We destroyed them', q: 1 },
    { a: 'بِذُنُوبِهِمْ', t: 'bi-dhunūbihim', e: 'for their sins', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'أَوِ', t: 'awi', e: 'or' },
    { a: 'الْمَفْعُولِ', t: 'al-mafʿūli', e: 'the object of' },
    { a: 'مَعَهُ،', t: 'maʿahu', e: 'accompaniment (maf‘ūl ma‘ah)' },
    NAHW, { g: ':' }, OPEN,
    { a: 'وَقَدْ', t: 'wa-qad', e: 'and they', q: 1 },
    { a: 'دَخَلُوا', t: 'dakhalū', e: 'entered', q: 1 },
    { a: 'بِالْكُفْرِ', t: 'bil-kufri', e: 'with disbelief', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'أَوِ', t: 'awi', e: 'or' },
    { a: 'الْحَالِ،', t: 'al-ḥāli', e: 'the circumstantial (ḥāl)' },
    NAHW, { g: ':' }, OPEN,
    { a: 'ادْخُلُوهَا', t: 'udkhulūhā', e: 'enter it', q: 1 },
    { a: 'بِسَلَامٍ', t: 'bi-salāmin', e: 'in peace', q: 1 },
    { a: 'آمِنِينَ', t: 'āminīna', e: 'secure', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'أَوِ', t: 'awi', e: 'or' },
    { a: 'التَّمْيِيزِ،', t: 'at-tamyīzi', e: 'the specification (tamyīz)' },
    NAHW, { g: ':' },
    { a: 'يَمْلَأُ', t: 'yamlaʾu', e: 'fills' },
    { a: 'الْخُلُقُ', t: 'al-khuluqu', e: 'character' },
    { a: 'الْحَسَنُ', t: 'al-ḥasanu', e: 'good' },
    { a: 'الْمِيزَانَ', t: 'al-mīzāna', e: 'the scale' },
    { a: 'بِالْحَسَنَاتِ', t: 'bil-ḥasanāti', e: 'with good deeds' },
  ] },
  { t: 'line', w: [
    { a: 'أَوِ', t: 'awi', e: 'or' },
    { a: 'الْآلَةِ،', t: 'al-ālati', e: 'the instrument' },
    NAHW, { g: ':' }, OPEN,
    { a: 'يَكْتُبُونَ', t: 'yaktubūna', e: 'they write', q: 1 },
    { a: 'الْكِتَابَ', t: 'al-kitāba', e: 'the book', q: 1 },
    { a: 'بِأَيْدِيهِمْ', t: 'bi-aydīhim', e: 'with their hands', q: 1 },
    CLOSE,
  ] },

  { t: 'page', n: '٤٤' },
  { t: 'line', w: [
    { a: 'أَوِ', t: 'awi', e: 'or' },
    { a: 'الْعِوَضِ،', t: 'al-ʿiwaḍi', e: 'exchange' },
    NAHW, { g: ':' }, OPEN,
    { a: 'اشْتَرَوُا', t: 'ishtarawu', e: 'they bought', q: 1 },
    { a: 'الضَّلَالَةَ', t: 'aḍ-ḍalālata', e: 'error', q: 1 },
    { a: 'بِالْهُدَى', t: 'bil-hudā', e: 'for guidance', q: 1 },
    CLOSE,
  ] },

  /* ── min ── */
  { t: 'line', w: [
    { a: 'الثَّانِي', t: 'ath-thānī', e: 'the second' }, { g: ':' },
    { a: 'مِنْ،', t: 'min', e: 'min (from)' },
  ] },
  { t: 'box', label: 'معنى مِن', labelEn: 'Meaning of min', lines: [
    [
      { a: 'مَعْنَى', t: 'maʿnā', e: 'the meaning of' },
      { a: 'مِنِ', t: 'mini', e: 'min is' },
      { a: 'ابْتِدَاءُ', t: 'ibtidāʾu', e: 'the start of' },
      { a: 'الْغَايَةِ', t: 'al-ghāyati', e: 'the limit' },
    ],
  ] },
  { t: 'line', w: [
    { a: 'تَكُونُ', t: 'takūnu', e: 'min is' },
    { a: 'مِنْ', t: 'min', e: '' },
    { a: 'مَعَ', t: 'maʿa', e: 'with' },
    { a: 'مَجْرُورِهَا', t: 'majrūrihā', e: 'its genitive' },
    { a: 'بِمَعْنَى', t: 'bi-maʿnā', e: 'in the sense of' },
    ELL,
  ] },
  { t: 'line', w: [
    { a: 'الْمَفْعُولِ', t: 'al-mafʿūli', e: 'the direct' },
    { a: 'بِهِ،', t: 'bihi', e: 'object' },
    NAHW, { g: ':' },
    { a: 'أَنَا', t: 'anā', e: 'I am' },
    { a: 'تَائِبٌ', t: 'tāʾibun', e: 'repentant' },
    { a: 'مِنْ', t: 'min', e: 'from' },
    { a: 'كُلِّ', t: 'kulli', e: 'every' },
    { a: 'ذَنْبٍ', t: 'dhanbin', e: 'sin' },
  ] },
  { t: 'line', w: [
    { a: 'أَوِ', t: 'awi', e: 'or' },
    { a: 'الْمَفْعُولِ', t: 'al-mafʿūli', e: 'the adverbial' },
    { a: 'فِيهِ', t: 'fīhi', e: 'object' },
    ELL,
  ] },
  { t: 'line', w: [
    { a: 'لِلْمَكَانِ،', t: 'lil-makāni', e: 'for place' },
    NAHW, { g: ':' }, OPEN,
    { a: 'مِنَ', t: 'mina', e: 'from', q: 1 },
    { a: 'الْمَسْجِدِ', t: 'al-masjidi', e: 'the Mosque', q: 1 },
    { a: 'الْحَرَامِ', t: 'al-ḥarāmi', e: 'the Sacred', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'أَوِ', t: 'awi', e: 'or' },
    { a: 'الزَّمَانِ،', t: 'az-zamāni', e: 'for time' },
    NAHW, { g: ':' }, OPEN,
    { a: 'أُسِّسَ', t: 'ussisa', e: 'founded', q: 1 },
    { a: 'عَلَى', t: 'ʿalā', e: 'upon', q: 1 },
    { a: 'التَّقْوَى', t: 'at-taqwā', e: 'piety', q: 1 },
    { a: 'مِنْ', t: 'min', e: 'from', q: 1 },
    { a: 'أَوَّلِ', t: 'awwali', e: 'the first', q: 1 },
    { a: 'يَوْمٍ', t: 'yawmin', e: 'day', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'أَوِ', t: 'awi', e: 'or' },
    { a: 'الْمَفْعُولِ', t: 'al-mafʿūli', e: 'the causative' },
    { a: 'لَهُ،', t: 'lahu', e: 'object' },
    NAHW, { g: ':' }, OPEN,
    { a: 'يَجْعَلُونَ', t: 'yajʿalūna', e: 'they put', q: 1 },
    { a: 'أَصَابِعَهُمْ', t: 'aṣābiʿahum', e: 'their fingers', q: 1 },
    { a: 'فِي', t: 'fī', e: 'in', q: 1 },
    { a: 'آذَانِهِمْ', t: 'ādhānihim', e: 'their ears', q: 1 },
    { a: 'مِنَ', t: 'mina', e: 'because of', q: 1 },
    { a: 'الصَّوَاعِقِ', t: 'aṣ-ṣawāʿiqi', e: 'the thunderbolts', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'أَوِ', t: 'awi', e: 'or' },
    { a: 'التَّمْيِيزِ،', t: 'at-tamyīzi', e: 'the specification' },
    NAHW, { g: ':' }, OPEN,
    { a: 'تَرَى', t: 'tarā', e: 'you see', q: 1 },
    { a: 'أَعْيُنَهُمْ', t: 'aʿyunahum', e: 'their eyes', q: 1 },
    { a: 'تَفِيضُ', t: 'tafīḍu', e: 'overflowing', q: 1 },
    { a: 'مِنَ', t: 'mina', e: 'with', q: 1 },
    { a: 'الدَّمْعِ', t: 'ad-damʿi', e: 'tears', q: 1 },
    CLOSE,
  ] },
  { t: 'page', n: '٤٥' },
  { t: 'line', w: [
    { a: 'أَوِ', t: 'awi', e: 'or' },
    { a: 'الْعِوَضِ،', t: 'al-ʿiwaḍi', e: 'exchange' },
    NAHW, { g: ':' }, OPEN,
    { a: 'أَرَضِيتُمْ', t: 'a-raḍītum', e: 'are you content', q: 1 },
    { a: 'بِالْحَيَاةِ', t: 'bil-ḥayāti', e: 'with the life', q: 1 },
    { a: 'الدُّنْيَا', t: 'ad-dunyā', e: 'of this world', q: 1 },
    { a: 'مِنَ', t: 'mina', e: 'instead of', q: 1 },
    { a: 'الْآخِرَةِ', t: 'al-ākhirati', e: 'the Hereafter', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'أَوِ', t: 'awi', e: 'or' },
    { a: 'الْآلَةِ،', t: 'al-ālati', e: 'the instrument' },
    NAHW, { g: ':' }, OPEN,
    { a: 'يَنْظُرُونَ', t: 'yanẓurūna', e: 'they look', q: 1 },
    { a: 'مِنْ', t: 'min', e: 'with', q: 1 },
    { a: 'طَرْفٍ', t: 'ṭarfin', e: 'a glance', q: 1 },
    { a: 'خَفِيٍّ', t: 'khafiyyin', e: 'stealthy', q: 1 },
    CLOSE,
  ] },

  /* ── ilā ── */
  { t: 'line', w: [
    { a: 'الثَّالِثُ', t: 'ath-thālithu', e: 'the third' }, { g: ':' },
    { a: 'إِلَى،', t: 'ilā', e: 'ilā (to)' },
  ] },
  { t: 'box', label: 'معنى إلى', labelEn: 'Meaning of ilā', lines: [
    [
      { a: 'مَعْنَى', t: 'maʿnā', e: 'the meaning of' },
      { a: 'إِلَى', t: 'ilā', e: 'ilā is' },
      { a: 'انْتِهَاءُ', t: 'intihāʾu', e: 'the end of' },
      { a: 'الْغَايَةِ', t: 'al-ghāyati', e: 'the limit' },
    ],
  ] },
  { t: 'line', w: [
    { a: 'تَكُونُ', t: 'takūnu', e: 'ilā is' },
    { a: 'إِلَى', t: 'ilā', e: '' },
    { a: 'مَعَ', t: 'maʿa', e: 'with' },
    { a: 'مَجْرُورِهَا', t: 'majrūrihā', e: 'its genitive' },
    { a: 'بِمَعْنَى', t: 'bi-maʿnā', e: 'in the sense of' },
    ELL,
  ] },
  { t: 'line', w: [
    { a: 'الْمَفْعُولِ', t: 'al-mafʿūli', e: 'the direct' },
    { a: 'بِهِ،', t: 'bihi', e: 'object' },
    NAHW, { g: ':' }, OPEN,
    { a: 'حَبَّبَ', t: 'ḥabbaba', e: 'He made beloved', q: 1 },
    { a: 'إِلَيْكُمُ', t: 'ilaykumu', e: 'to you', q: 1 },
    { a: 'الْإِيمَانَ', t: 'al-īmāna', e: 'faith', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'أَوِ', t: 'awi', e: 'or' },
    { a: 'الْمَفْعُولِ', t: 'al-mafʿūli', e: 'the adverbial' },
    { a: 'فِيهِ', t: 'fīhi', e: 'object' },
    ELL,
  ] },
  { t: 'line', w: [
    { a: 'لِلْمَكَانِ،', t: 'lil-makāni', e: 'for place' },
    NAHW, { g: ':' }, OPEN,
    { a: 'إِلَى', t: 'ilā', e: 'to', q: 1 },
    { a: 'الْمَسْجِدِ', t: 'al-masjidi', e: 'the Mosque', q: 1 },
    { a: 'الْأَقْصَى', t: 'al-aqṣā', e: 'the Farthest', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'أَوِ', t: 'awi', e: 'or' },
    { a: 'الزَّمَانِ،', t: 'az-zamāni', e: 'for time' },
    NAHW, { g: ':' }, OPEN,
    { a: 'ثُمَّ', t: 'thumma', e: 'then', q: 1 },
    { a: 'أَتِمُّوا', t: 'atimmū', e: 'complete', q: 1 },
    { a: 'الصِّيَامَ', t: 'aṣ-ṣiyāma', e: 'the fast', q: 1 },
    { a: 'إِلَى', t: 'ilā', e: 'until', q: 1 },
    { a: 'الَّيْلِ', t: 'al-layli', e: 'night', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'أَوِ', t: 'awi', e: 'or' },
    { a: 'الْمَفْعُولِ', t: 'al-mafʿūli', e: 'the object of' },
    { a: 'مَعَهُ،', t: 'maʿahu', e: 'accompaniment' },
    NAHW, { g: ':' }, OPEN,
    { a: 'وَلَا', t: 'wa-lā', e: 'and do not', q: 1 },
    { a: 'تَأْكُلُوا', t: 'taʾkulū', e: 'consume', q: 1 },
    { a: 'أَمْوَالَهُمْ', t: 'amwālahum', e: 'their wealth', q: 1 },
    { a: 'إِلَى', t: 'ilā', e: 'along with', q: 1 },
    { a: 'أَمْوَالِكُمْ', t: 'amwālikum', e: 'your wealth', q: 1 },
    CLOSE,
  ] },

  /* ── ʿan ── */
  { t: 'line', w: [
    { a: 'الرَّابِعُ', t: 'ar-rābiʿu', e: 'the fourth' }, { g: ':' },
    { a: 'عَنْ،', t: 'ʿan', e: 'ʿan (about / away from)' },
  ] },
  { t: 'box', label: 'معنى عن', labelEn: 'Meaning of ʿan', lines: [
    [
      { a: 'مَعْنَى', t: 'maʿnā', e: 'the meaning of' },
      { a: 'عَنِ', t: 'ʿani', e: 'ʿan is' },
      { a: 'الْمُجَاوَزَةُ', t: 'al-mujāwazatu', e: 'passing beyond (mujāwaza)' },
    ],
  ] },
  { t: 'page', n: '٤٦' },
  { t: 'line', w: [
    { a: 'تَكُونُ', t: 'takūnu', e: 'ʿan is' },
    { a: 'عَنْ', t: 'ʿan', e: '' },
    { a: 'مَعَ', t: 'maʿa', e: 'with' },
    { a: 'مَجْرُورِهَا', t: 'majrūrihā', e: 'its genitive' },
    { a: 'بِمَعْنَى', t: 'bi-maʿnā', e: 'in the sense of' },
    ELL,
  ] },
  { t: 'line', w: [
    { a: 'الْمَفْعُولِ', t: 'al-mafʿūli', e: 'the direct' },
    { a: 'بِهِ،', t: 'bihi', e: 'object' },
    NAHW, { g: ':' }, OPEN,
    { a: 'وَيَنْهَوْنَ', t: 'wa-yanhawna', e: 'and they forbid', q: 1 },
    { a: 'عَنِ', t: 'ʿani', e: '', q: 1 },
    { a: 'الْمُنْكَرِ', t: 'al-munkari', e: 'wrong', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'أَوِ', t: 'awi', e: 'or' },
    { a: 'الْمَفْعُولِ', t: 'al-mafʿūli', e: 'the adverbial' },
    { a: 'فِيهِ', t: 'fīhi', e: 'object' },
    ELL,
  ] },
  { t: 'line', w: [
    { a: 'لِلْمَكَانِ،', t: 'lil-makāni', e: 'for place' },
    NAHW, { g: ':' }, OPEN,
    { a: 'هُوَ', t: 'huwa', e: 'He', q: 1 },
    { a: 'يَقْبَلُ', t: 'yaqbalu', e: 'accepts', q: 1 },
    { a: 'التَّوْبَةَ', t: 'at-tawbata', e: 'repentance', q: 1 },
    { a: 'عَنْ', t: 'ʿan', e: 'from', q: 1 },
    { a: 'عِبَادِهِ', t: 'ʿibādihi', e: 'His servants', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'أَوِ', t: 'awi', e: 'or' },
    { a: 'الزَّمَانِ،', t: 'az-zamāni', e: 'for time' },
    NAHW, { g: ':' }, OPEN,
    { a: 'عَمَّا', t: 'ʿammā', e: 'after', q: 1 },
    { a: 'قَلِيلٍ', t: 'qalīlin', e: 'a little while', q: 1 },
    { a: 'لَيُصْبِحُنَّ', t: 'la-yuṣbiḥunna', e: 'they will surely become', q: 1 },
    { a: 'نَادِمِينَ', t: 'nādimīna', e: 'regretful', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'أَوِ', t: 'awi', e: 'or' },
    { a: 'الْمَفْعُولِ', t: 'al-mafʿūli', e: 'the causative' },
    { a: 'لَهُ،', t: 'lahu', e: 'object' },
    NAHW, { g: ':' }, OPEN,
    { a: 'وَمَا', t: 'wa-mā', e: 'and we are not', q: 1 },
    { a: 'نَحْنُ', t: 'naḥnu', e: '', q: 1 },
    { a: 'بِتَارِكِي', t: 'bi-tārikī', e: 'going to abandon', q: 1 },
    { a: 'آلِهَتِنَا', t: 'ālihatinā', e: 'our gods', q: 1 },
    { a: 'عَنْ', t: 'ʿan', e: 'because of', q: 1 },
    { a: 'قَوْلِكَ', t: 'qawlika', e: 'your word', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'أَوِ', t: 'awi', e: 'or' },
    { a: 'الْعِوَضِ،', t: 'al-ʿiwaḍi', e: 'exchange / on behalf' },
    NAHW, { g: ':' },
    { a: 'حُجَّ', t: 'ḥujja', e: 'perform Hajj' },
    { a: 'عَنْ', t: 'ʿan', e: 'on behalf of' },
    { a: 'أَبِيكَ', t: 'abīka', e: 'your father' },
  ] },
  { t: 'box', label: 'عن الاسمية', labelEn: 'ʿan used as a noun', lines: [
    [
      { a: 'تَكُونُ', t: 'takūnu', e: 'the word ʿan is' },
      { a: 'كَلِمَةُ', t: 'kalimatu', e: '' },
      { a: 'عَنْ', t: 'ʿan', e: '' },
      { a: 'اسْمًا', t: 'isman', e: 'a noun' },
      { a: 'بِمَعْنَى', t: 'bi-maʿnā', e: 'meaning' },
      { a: 'جَانِبٍ', t: 'jānibin', e: 'side' },
      { a: 'إِذَا', t: 'idhā', e: 'when' },
      { a: 'سُبِقَتْ', t: 'subiqat', e: 'preceded' },
      { a: 'بِمِنْ،', t: 'bi-min', e: 'by min' },
      NAHW, { g: ':' },
      { a: 'جِئْتُ', t: 'jiʾtu', e: 'I came' },
      { a: 'مِنْ', t: 'min', e: 'from' },
      { a: 'عَنْ', t: 'ʿan', e: 'the side of' },
      { a: 'يَمِينِهِ', t: 'yamīnihi', e: 'his right' },
    ],
  ] },

  /* ── ʿalā ── */
  { t: 'line', w: [
    { a: 'الْخَامِسُ', t: 'al-khāmisu', e: 'the fifth' }, { g: ':' },
    { a: 'عَلَى،', t: 'ʿalā', e: 'ʿalā (upon)' },
  ] },
  { t: 'box', label: 'معنى على', labelEn: 'Meaning of ʿalā', lines: [
    [
      { a: 'مَعْنَى', t: 'maʿnā', e: 'the meaning of' },
      { a: 'عَلَى', t: 'ʿalā', e: 'ʿalā is' },
      { a: 'الِاسْتِعْلَاءُ', t: 'al-istiʿlāʾu', e: 'being-upon (istiʿlāʾ)' },
    ],
  ] },
  { t: 'page', n: '٤٧' },
  { t: 'line', w: [
    { a: 'تَكُونُ', t: 'takūnu', e: 'ʿalā is' },
    { a: 'عَلَى', t: 'ʿalā', e: '' },
    { a: 'مَعَ', t: 'maʿa', e: 'with' },
    { a: 'مَجْرُورِهَا', t: 'majrūrihā', e: 'its genitive' },
    { a: 'بِمَعْنَى', t: 'bi-maʿnā', e: 'in the sense of' },
    ELL,
  ] },
  { t: 'line', w: [
    { a: 'الْمَفْعُولِ', t: 'al-mafʿūli', e: 'the direct' },
    { a: 'بِهِ،', t: 'bihi', e: 'object' },
    NAHW, { g: ':' }, OPEN,
    { a: 'أَنْعَمْتَ', t: 'anʿamta', e: 'You favored', q: 1 },
    { a: 'عَلَيْهِمْ', t: 'ʿalayhim', e: 'them', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'أَوِ', t: 'awi', e: 'or' },
    { a: 'الْمَفْعُولِ', t: 'al-mafʿūli', e: 'the adverbial' },
    { a: 'فِيهِ', t: 'fīhi', e: 'object' },
    ELL,
  ] },
  { t: 'line', w: [
    { a: 'لِلْمَكَانِ،', t: 'lil-makāni', e: 'for place' },
    NAHW, { g: ':' }, OPEN,
    { a: 'وَعَلَيْهَا', t: 'wa-ʿalayhā', e: 'and on them', q: 1 },
    { a: 'وَعَلَى', t: 'wa-ʿalā', e: 'and on', q: 1 },
    { a: 'الْفُلْكِ', t: 'al-fulki', e: 'the ships', q: 1 },
    { a: 'تُحْمَلُونَ', t: 'tuḥmalūna', e: 'you are carried', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'أَوِ', t: 'awi', e: 'or' },
    { a: 'الزَّمَانِ،', t: 'az-zamāni', e: 'for time' },
    NAHW, { g: ':' }, OPEN,
    { a: 'وَدَخَلَ', t: 'wa-dakhala', e: 'and he entered', q: 1 },
    { a: 'الْمَدِينَةَ', t: 'al-madīnata', e: 'the city', q: 1 },
    { a: 'عَلَى', t: 'ʿalā', e: 'at', q: 1 },
    { a: 'حِينِ', t: 'ḥīni', e: 'a time of', q: 1 },
    { a: 'غَفْلَةٍ', t: 'ghaflatin', e: 'heedlessness', q: 1 },
    { a: 'مِنْ', t: 'min', e: 'of', q: 1 },
    { a: 'أَهْلِهَا', t: 'ahlihā', e: 'its people', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'أَوِ', t: 'awi', e: 'or' },
    { a: 'الْمَفْعُولِ', t: 'al-mafʿūli', e: 'the causative' },
    { a: 'لَهُ،', t: 'lahu', e: 'object' },
    NAHW, { g: ':' }, OPEN,
    { a: 'لِتُكَبِّرُوا', t: 'li-tukabbirū', e: 'that you may magnify', q: 1 },
    { a: 'اللهَ', t: 'Allāha', e: 'Allah', q: 1 },
    { a: 'عَلَى', t: 'ʿalā', e: 'for', q: 1 },
    { a: 'مَا', t: 'mā', e: 'how', q: 1 },
    { a: 'هَدَاكُمْ', t: 'hadākum', e: 'He guided you', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'أَوِ', t: 'awi', e: 'or' },
    { a: 'الْمَفْعُولِ', t: 'al-mafʿūli', e: 'the object of' },
    { a: 'مَعَهُ،', t: 'maʿahu', e: 'accompaniment' },
    NAHW, { g: ':' }, OPEN,
    { a: 'وَيُطْعِمُونَ', t: 'wa-yuṭʿimūna', e: 'and they feed', q: 1 },
    { a: 'الطَّعَامَ', t: 'aṭ-ṭaʿāma', e: 'food', q: 1 },
    { a: 'عَلَى', t: 'ʿalā', e: 'despite', q: 1 },
    { a: 'حُبِّهِ', t: 'ḥubbihi', e: 'their love of it', q: 1 },
    { a: 'مِسْكِينًا', t: 'miskīnan', e: 'to the needy', q: 1 },
    { a: 'وَيَتِيمًا', t: 'wa-yatīman', e: 'the orphan', q: 1 },
    { a: 'وَأَسِيرًا', t: 'wa-asīran', e: 'and the captive', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'أَوِ', t: 'awi', e: 'or' },
    { a: 'الْحَالِ،', t: 'al-ḥāli', e: 'the circumstantial' },
    NAHW, { g: ':' }, OPEN,
    { a: 'فَمَا', t: 'fa-mā', e: 'and none', q: 1 },
    { a: 'آمَنَ', t: 'āmana', e: 'believed', q: 1 },
    { a: 'لِمُوسَى', t: 'li-mūsā', e: 'in Mūsā', q: 1 },
    { a: 'إِلَّا', t: 'illā', e: 'except', q: 1 },
    { a: 'ذُرِّيَّةٌ', t: 'dhurriyyatun', e: 'some offspring', q: 1 },
    { a: 'مِنْ', t: 'min', e: 'of', q: 1 },
    { a: 'قَوْمِهِ', t: 'qawmihi', e: 'his people', q: 1 },
    { a: 'عَلَى', t: 'ʿalā', e: 'in', q: 1 },
    { a: 'خَوْفٍ', t: 'khawfin', e: 'fear', q: 1 },
    { a: 'مِنْ', t: 'min', e: 'of', q: 1 },
    { a: 'فِرْعَوْنَ', t: 'firʿawna', e: 'Pharaoh', q: 1 },
    { a: 'وَمَلَئِهِمْ', t: 'wa-malaʾihim', e: 'and their chiefs', q: 1 },
    CLOSE,
  ] },

  /* ── lām ── */
  { t: 'page', n: '٤٨' },
  { t: 'line', w: [
    { a: 'السَّادِسُ', t: 'as-sādisu', e: 'the sixth' }, { g: ':' },
    { a: 'اللَّامُ،', t: 'al-lāmu', e: 'the lām (for / to)' },
  ] },
  { t: 'box', label: 'معنى اللام', labelEn: 'Meaning of the lām', lines: [
    [
      { a: 'لِلتَّخْصِيصِ،', t: 'lit-takhṣīṣi', e: 'for assignment' },
      { a: 'وَيُسَمَّى', t: 'wa-yusammā', e: 'also called' },
      { a: 'الِاسْتِحْقَاقَ،', t: 'al-istiḥqāqa', e: 'entitlement' },
      NAHW, { g: ':' }, OPEN,
      { a: 'الْحَمْدُ', t: 'al-ḥamdu', e: 'all praise', q: 1 },
      { a: 'لِلهِ', t: 'li-llāhi', e: 'is for Allah', q: 1 },
      CLOSE,
    ],
    [
      { a: 'وَالْمِلْكِ،', t: 'wal-milki', e: 'and ownership' },
      NAHW, { g: ':' }, OPEN,
      { a: 'لَهُ', t: 'lahu', e: 'to Him belongs', q: 1 },
      { a: 'مَا', t: 'mā', e: 'what is', q: 1 },
      { a: 'فِي', t: 'fī', e: 'in', q: 1 },
      { a: 'السَّمَاوَاتِ', t: 'as-samāwāti', e: 'the heavens', q: 1 },
      { a: 'وَمَا', t: 'wa-mā', e: 'and what is', q: 1 },
      { a: 'فِي', t: 'fī', e: 'in', q: 1 },
      { a: 'الْأَرْضِ', t: 'al-arḍi', e: 'the earth', q: 1 },
      CLOSE,
    ],
    [
      { a: 'وَشِبْهِ', t: 'wa-shibhi', e: 'and quasi-' },
      { a: 'الْمِلْكِ،', t: 'al-milki', e: 'ownership' },
      { a: 'وَيُسَمَّى', t: 'wa-yusammā', e: 'also called' },
      { a: 'النِّسْبَةَ،', t: 'an-nisbata', e: 'relation' },
      NAHW, { g: ':' }, OPEN,
      { a: 'إِنَّ', t: 'inna', e: 'indeed', q: 1 },
      { a: 'فِي', t: 'fī', e: 'in', q: 1 },
      { a: 'السَّمَاوَاتِ', t: 'as-samāwāti', e: 'the heavens', q: 1 },
      { a: 'وَالْأَرْضِ', t: 'wal-arḍi', e: 'and the earth', q: 1 },
      { a: 'لَآيَاتٍ', t: 'la-āyātin', e: 'are signs', q: 1 },
      { a: 'لِلْمُؤْمِنِينَ', t: 'lil-muʾminīna', e: 'for the believers', q: 1 },
      CLOSE,
    ],
  ] },
  { t: 'line', w: [
    { a: 'تَكُونُ', t: 'takūnu', e: 'the lām is' },
    { a: 'اللَّامُ', t: 'al-lāmu', e: '' },
    { a: 'مَعَ', t: 'maʿa', e: 'with' },
    { a: 'مَجْرُورِهَا', t: 'majrūrihā', e: 'its genitive' },
    { a: 'بِمَعْنَى', t: 'bi-maʿnā', e: 'in the sense of' },
    ELL,
  ] },
  { t: 'line', w: [
    { a: 'الْمَفْعُولِ', t: 'al-mafʿūli', e: 'the direct' },
    { a: 'بِهِ،', t: 'bihi', e: 'object' },
    NAHW, { g: ':' }, OPEN,
    { a: 'وَوَهَبْنَا', t: 'wa-wahabnā', e: 'and We granted', q: 1 },
    { a: 'لَهُ', t: 'lahu', e: 'to him', q: 1 },
    { a: 'إِسْحَاقَ', t: 'isḥāqa', e: 'Isḥāq', q: 1 },
    { a: 'وَيَعْقُوبَ', t: 'wa-yaʿqūba', e: 'and Yaʿqūb', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'الْمَفْعُولِ', t: 'al-mafʿūli', e: 'the adverbial' },
    { a: 'فِيهِ', t: 'fīhi', e: 'object' },
    ELL,
  ] },
  { t: 'line', w: [
    { a: 'لِلْمَكَانِ،', t: 'lil-makāni', e: 'for place' },
    NAHW, { g: ':' }, OPEN,
    { a: 'وَإِذَا', t: 'wa-idhā', e: 'and when', q: 1 },
    { a: 'مَسَّ', t: 'massa', e: 'touches', q: 1 },
    { a: 'الْإِنْسَانَ', t: 'al-insāna', e: 'man', q: 1 },
    { a: 'الضُّرُّ', t: 'aḍ-ḍurru', e: 'affliction', q: 1 },
    { a: 'دَعَانَا', t: 'daʿānā', e: 'he calls Us', q: 1 },
    { a: 'لِجَنْبِهِ', t: 'li-janbihi', e: 'on his side', q: 1 },
    { a: 'أَوْ', t: 'aw', e: 'or', q: 1 },
    { a: 'قَاعِدًا', t: 'qāʿidan', e: 'sitting', q: 1 },
    { a: 'أَوْ', t: 'aw', e: 'or', q: 1 },
    { a: 'قَائِمًا', t: 'qāʾiman', e: 'standing', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'أَوِ', t: 'awi', e: 'or' },
    { a: 'الزَّمَانِ،', t: 'az-zamāni', e: 'for time' },
    NAHW, { g: ':' }, OPEN,
    { a: 'وَنَضَعُ', t: 'wa-naḍaʿu', e: 'and We place', q: 1 },
    { a: 'الْمَوَازِينَ', t: 'al-mawāzīna', e: 'the scales', q: 1 },
    { a: 'الْقِسْطَ', t: 'al-qisṭa', e: 'of justice', q: 1 },
    { a: 'لِيَوْمِ', t: 'li-yawmi', e: 'for the Day of', q: 1 },
    { a: 'الْقِيَامَةِ', t: 'al-qiyāmati', e: 'Resurrection', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'أَوِ', t: 'awi', e: 'or' },
    { a: 'الْمَفْعُولِ', t: 'al-mafʿūli', e: 'the causative' },
    { a: 'لَهُ،', t: 'lahu', e: 'object' },
    { a: 'وَالْأَكْثَرُ', t: 'wal-aktharu', e: 'most often' },
    { a: 'أَنْ', t: 'an', e: 'it is' },
    { a: 'يَكُونَ', t: 'yakūna', e: '' },
    { a: 'عَنْ', t: 'ʿan', e: 'by' },
    { a: 'قَصْدِ', t: 'qaṣdi', e: 'the intent of' },
    { a: 'الْفَاعِلِ،', t: 'al-fāʿili', e: 'the doer' },
    NAHW, { g: ':' }, OPEN,
    { a: 'نَزَّلَ', t: 'nazzala', e: 'He sent down', q: 1 },
    { a: 'الْفُرْقَانَ', t: 'al-furqāna', e: 'the Criterion', q: 1 },
    { a: 'عَلَى', t: 'ʿalā', e: 'upon', q: 1 },
    { a: 'عَبْدِهِ', t: 'ʿabdihi', e: 'His servant', q: 1 },
    { a: 'لِيَكُونَ', t: 'li-yakūna', e: 'that he be', q: 1 },
    { a: 'لِلْعَالَمِينَ', t: 'lil-ʿālamīna', e: 'to the worlds', q: 1 },
    { a: 'نَذِيرًا', t: 'nadhīran', e: 'a warner', q: 1 },
    CLOSE,
    { a: 'وَتُسَمَّى', t: 'wa-tusammā', e: 'and it is called' },
    { a: 'لَامَ', t: 'lāma', e: 'the lām of' },
    { a: 'التَّعْلِيلِ', t: 'at-taʿlīli', e: 'causation' },
    { a: 'وَلَامَ', t: 'wa-lāma', e: 'and the lām of' },
    { a: 'كَيْ،', t: 'kay', e: 'kay' },
  ] },
  { t: 'page', n: '٤٩' },
  { t: 'line', w: [
    { a: 'وَقَدْ', t: 'wa-qad', e: 'and it may' },
    { a: 'يَكُونُ', t: 'yakūnu', e: 'be' },
    { a: 'نَتِيجَةً', t: 'natījatan', e: 'an outcome' },
    { a: 'عَنْ', t: 'ʿan', e: 'without' },
    { a: 'غَيْرِ', t: 'ghayri', e: '' },
    { a: 'قَصْدٍ،', t: 'qaṣdin', e: 'intent' },
    NAHW, { g: ':' }, OPEN,
    { a: 'فَالْتَقَطَهُ', t: 'fa-ltaqaṭahu', e: 'and picked him up', q: 1 },
    { a: 'آلُ', t: 'ālu', e: 'the family of', q: 1 },
    { a: 'فِرْعَوْنَ', t: 'firʿawna', e: 'Pharaoh', q: 1 },
    { a: 'لِيَكُونَ', t: 'li-yakūna', e: 'so he became', q: 1 },
    { a: 'لَهُمْ', t: 'lahum', e: 'for them', q: 1 },
    { a: 'عَدُوًّا', t: 'ʿaduwwan', e: 'an enemy', q: 1 },
    { a: 'وَحَزَنًا', t: 'wa-ḥazanan', e: 'and grief', q: 1 },
    CLOSE,
    { a: 'وَتُسَمَّى', t: 'wa-tusammā', e: 'and it is called' },
    { a: 'لَامَ', t: 'lāma', e: 'the lām of' },
    { a: 'الْعَاقِبَةِ', t: 'al-ʿāqibati', e: 'consequence' },
    { a: 'وَلَامَ', t: 'wa-lāma', e: 'and the lām of' },
    { a: 'الصَّيْرُورَةِ', t: 'aṣ-ṣayrūrati', e: 'becoming' },
  ] },

  /* ── fī ── */
  { t: 'line', w: [
    { a: 'السَّابِعُ', t: 'as-sābiʿu', e: 'the seventh' }, { g: ':' },
    { a: 'فِي،', t: 'fī', e: 'fī (in)' },
  ] },
  { t: 'box', label: 'معنى في', labelEn: 'Meaning of fī', lines: [
    [
      { a: 'مَعْنَى', t: 'maʿnā', e: 'the meaning of' },
      { a: 'فِي', t: 'fī', e: 'fī is' },
      { a: 'الظَّرْفِيَّةُ', t: 'aẓ-ẓarfiyyatu', e: 'containment (ẓarfiyya)' },
    ],
  ] },
  { t: 'line', w: [
    { a: 'تَكُونُ', t: 'takūnu', e: 'fī is' },
    { a: 'فِي', t: 'fī', e: '' },
    { a: 'مَعَ', t: 'maʿa', e: 'with' },
    { a: 'مَجْرُورِهَا', t: 'majrūrihā', e: 'its genitive' },
    { a: 'بِمَعْنَى', t: 'bi-maʿnā', e: 'in the sense of' },
    ELL,
  ] },
  { t: 'line', w: [
    { a: 'الْمَفْعُولِ', t: 'al-mafʿūli', e: 'the direct' },
    { a: 'بِهِ،', t: 'bihi', e: 'object' },
    NAHW, { g: ':' }, OPEN,
    { a: 'وَيُسَارِعُونَ', t: 'wa-yusāriʿūna', e: 'and they hasten', q: 1 },
    { a: 'فِي', t: 'fī', e: 'to', q: 1 },
    { a: 'الْخَيْرَاتِ', t: 'al-khayrāti', e: 'good deeds', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'الْمَفْعُولِ', t: 'al-mafʿūli', e: 'the adverbial' },
    { a: 'فِيهِ', t: 'fīhi', e: 'object' },
    ELL,
  ] },
  { t: 'line', w: [
    { a: 'لِلْمَكَانِ،', t: 'lil-makāni', e: 'for place' },
    NAHW, { g: ':' }, OPEN,
    { a: 'رَبَّنَا', t: 'rabbanā', e: 'our Lord', q: 1 },
    { a: 'آتِنَا', t: 'ātinā', e: 'give us', q: 1 },
    { a: 'فِي', t: 'fī', e: 'in', q: 1 },
    { a: 'الدُّنْيَا', t: 'ad-dunyā', e: 'this world', q: 1 },
    { a: 'حَسَنَةً', t: 'ḥasanatan', e: 'good', q: 1 },
    { a: 'وَفِي', t: 'wa-fī', e: 'and in', q: 1 },
    { a: 'الْآخِرَةِ', t: 'al-ākhirati', e: 'the Hereafter', q: 1 },
    { a: 'حَسَنَةً', t: 'ḥasanatan', e: 'good', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'أَوِ', t: 'awi', e: 'or' },
    { a: 'الزَّمَانِ،', t: 'az-zamāni', e: 'for time' },
    NAHW, { g: ':' }, OPEN,
    { a: 'شَهْرُ', t: 'shahru', e: 'the month of', q: 1 },
    { a: 'رَمَضَانَ', t: 'ramaḍāna', e: 'Ramaḍān', q: 1 },
    { a: 'الَّذِي', t: 'alladhī', e: 'in which', q: 1 },
    { a: 'أُنْزِلَ', t: 'unzila', e: 'was sent down', q: 1 },
    { a: 'فِيهِ', t: 'fīhi', e: 'in it', q: 1 },
    { a: 'الْقُرْآنُ', t: 'al-qurʾānu', e: 'the Qurʾān', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'أَوِ', t: 'awi', e: 'or' },
    { a: 'الْمَفْعُولِ', t: 'al-mafʿūli', e: 'the causative' },
    { a: 'لَهُ،', t: 'lahu', e: 'object' },
    NAHW, { g: ':' }, OPEN,
    { a: 'قَالَتْ', t: 'qālat', e: 'she said', q: 1 },
    { a: 'فَذَلِكُنَّ', t: 'fa-dhālikunna', e: 'that is the one', q: 1 },
    { a: 'الَّذِي', t: 'alladhī', e: 'about whom', q: 1 },
    { a: 'لُمْتُنَّنِي', t: 'lumtunnanī', e: 'you blamed me', q: 1 },
    { a: 'فِيهِ', t: 'fīhi', e: 'concerning him', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'أَوِ', t: 'awi', e: 'or' },
    { a: 'الْمَفْعُولِ', t: 'al-mafʿūli', e: 'the object of' },
    { a: 'مَعَهُ،', t: 'maʿahu', e: 'accompaniment' },
    NAHW, { g: ':' }, OPEN,
    { a: 'فَادْخُلِي', t: 'fa-dkhulī', e: 'so enter', q: 1 },
    { a: 'فِي', t: 'fī', e: 'among', q: 1 },
    { a: 'عِبَادِي', t: 'ʿibādī', e: 'My servants', q: 1 },
    CLOSE,
  ] },

  /* ── kāf ── */
  { t: 'line', w: [
    { a: 'الثَّامِنُ', t: 'ath-thāminu', e: 'the eighth' }, { g: ':' },
    { a: 'الْكَافُ،', t: 'al-kāfu', e: 'the kāf (like)' },
  ] },
  { t: 'box', label: 'معنى الكاف', labelEn: 'Meaning of the kāf', lines: [
    [
      { a: 'مَعْنَى', t: 'maʿnā', e: 'the meaning of' },
      { a: 'الْكَافِ', t: 'al-kāfi', e: 'the kāf is' },
      { a: 'التَّشْبِيهُ', t: 'at-tashbīhu', e: 'comparison (tashbīh)' },
    ],
  ] },
  { t: 'line', w: [
    { a: 'تَكُونُ', t: 'takūnu', e: 'the kāf is' },
    { a: 'الْكَافُ', t: 'al-kāfu', e: '' },
    { a: 'مَعَ', t: 'maʿa', e: 'with' },
    { a: 'مَجْرُورِهَا', t: 'majrūrihā', e: 'its genitive' },
    { a: 'بِمَعْنَى', t: 'bi-maʿnā', e: 'in the sense of' },
    ELL,
  ] },
  { t: 'line', w: [
    { a: 'الْمَفْعُولِ', t: 'al-mafʿūli', e: 'the absolute' },
    { a: 'مُطْلَقًا،', t: 'muṭlaqan', e: 'object' },
    NAHW, { g: ':' }, OPEN,
    { a: 'رَبِّ', t: 'rabbi', e: 'my Lord', q: 1 },
    { a: 'ارْحَمْهُمَا', t: 'irḥamhumā', e: 'have mercy on them', q: 1 },
    { a: 'كَمَا', t: 'kamā', e: 'as', q: 1 },
    { a: 'رَبَّيَانِي', t: 'rabbayānī', e: 'they raised me', q: 1 },
    { a: 'صَغِيرًا', t: 'ṣaghīran', e: 'when small', q: 1 },
    CLOSE,
  ] },
  { t: 'page', n: '٥٠' },
  { t: 'line', w: [
    { a: 'أَوِ', t: 'awi', e: 'or' },
    { a: 'الْمَفْعُولِ', t: 'al-mafʿūli', e: 'the causative' },
    { a: 'لَهُ،', t: 'lahu', e: 'object' },
    NAHW, { g: ':' }, OPEN,
    { a: 'وَاذْكُرُوهُ', t: 'wa-dhkurūhu', e: 'and remember Him', q: 1 },
    { a: 'كَمَا', t: 'kamā', e: 'as', q: 1 },
    { a: 'هَدَاكُمْ', t: 'hadākum', e: 'He guided you', q: 1 },
    CLOSE,
  ] },

  /* ── ḥattā ── */
  { t: 'line', w: [
    { a: 'التَّاسِعُ', t: 'at-tāsiʿu', e: 'the ninth' }, { g: ':' },
    { a: 'حَتَّى،', t: 'ḥattā', e: 'ḥattā (until)' },
  ] },
  { t: 'box', label: 'معنى حتى', labelEn: 'Meaning of ḥattā', lines: [
    [
      { a: 'وَهِيَ', t: 'wa-hiya', e: 'it is' },
      { a: 'لِانْتِهَاءِ', t: 'li-intihāʾi', e: 'for the end of' },
      { a: 'الْغَايَةِ', t: 'al-ghāyati', e: 'the limit' },
    ],
  ] },
  { t: 'line', w: [
    { a: 'تَكُونُ', t: 'takūnu', e: 'ḥattā is' },
    { a: 'حَتَّى', t: 'ḥattā', e: '' },
    { a: 'مَعَ', t: 'maʿa', e: 'with' },
    { a: 'مَجْرُورِهَا', t: 'majrūrihā', e: 'its genitive' },
    { a: 'بِمَعْنَى', t: 'bi-maʿnā', e: 'in the sense of' },
    ELL,
  ] },
  { t: 'line', w: [
    { a: 'الْمَفْعُولِ', t: 'al-mafʿūli', e: 'the adverbial' },
    { a: 'فِيهِ', t: 'fīhi', e: 'object' },
    ELL,
  ] },
  { t: 'line', w: [
    { a: 'لِلْمَكَانِ،', t: 'lil-makāni', e: 'for place' },
    NAHW, { g: ':' },
    { a: 'سِرْنَا', t: 'sirnā', e: 'we travelled' },
    { a: 'حَتَّى', t: 'ḥattā', e: 'up to' },
    { a: 'مَكَّةَ', t: 'makkata', e: 'Mecca' },
  ] },
  { t: 'line', w: [
    { a: 'أَوِ', t: 'awi', e: 'or' },
    { a: 'الزَّمَانِ،', t: 'az-zamāni', e: 'for time' },
    NAHW, { g: ':' }, OPEN,
    { a: 'هِيَ', t: 'hiya', e: 'it is [peace]', q: 1 },
    { a: 'حَتَّى', t: 'ḥattā', e: 'until', q: 1 },
    { a: 'مَطْلَعِ', t: 'maṭlaʿi', e: 'the rising of', q: 1 },
    { a: 'الْفَجْرِ', t: 'al-fajri', e: 'dawn', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'أَوِ', t: 'awi', e: 'or' },
    { a: 'الْمَفْعُولِ', t: 'al-mafʿūli', e: 'the causative' },
    { a: 'لَهُ،', t: 'lahu', e: 'object' },
    NAHW, { g: ':' }, OPEN,
    { a: 'وَقَاتِلُوهُمْ', t: 'wa-qātilūhum', e: 'and fight them', q: 1 },
    { a: 'حَتَّى', t: 'ḥattā', e: 'until', q: 1 },
    { a: 'لَا', t: 'lā', e: 'there is no', q: 1 },
    { a: 'تَكُونَ', t: 'takūna', e: '', q: 1 },
    { a: 'فِتْنَةٌ', t: 'fitnatun', e: 'persecution', q: 1 },
    CLOSE,
  ] },

  /* ── the oath particles ── */
  { t: 'page', n: '٥١' },
  { t: 'line', w: [
    { a: 'الْعَاشِرُ', t: 'al-ʿāshiru', e: 'the tenth' }, { g: ':' },
    { a: 'وَاوُ', t: 'wāwu', e: 'the wāw of' },
    { a: 'الْقَسَمِ،', t: 'al-qasami', e: 'oath' },
    NAHW, { g: ':' }, OPEN,
    { a: 'وَالْعَصْرِ', t: 'wal-ʿaṣri', e: 'By time', q: 1 },
    { g: '۝' },
    { a: 'إِنَّ', t: 'inna', e: 'indeed', q: 1 },
    { a: 'الْإِنْسَانَ', t: 'al-insāna', e: 'man', q: 1 },
    { a: 'لَفِي', t: 'la-fī', e: 'is in', q: 1 },
    { a: 'خُسْرٍ', t: 'khusrin', e: 'loss', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'الْحَادِيَ', t: 'al-ḥādiya', e: 'the elev-' },
    { a: 'عَشَرَ', t: 'ʿashara', e: '-enth' }, { g: ':' },
    { a: 'تَاءُ', t: 'tāʾu', e: 'the tāʾ of' },
    { a: 'الْقَسَمِ،', t: 'al-qasami', e: 'oath' },
    NAHW, { g: ':' }, OPEN,
    { a: 'تَاللهِ', t: 'ta-llāhi', e: 'By Allah', q: 1 },
    { a: 'تَفْتَأُ', t: 'taftaʾu', e: 'you will not cease', q: 1 },
    { a: 'تَذْكُرُ', t: 'tadhkuru', e: 'remembering', q: 1 },
    { a: 'يُوسُفَ', t: 'yūsufa', e: 'Yūsuf', q: 1 },
    CLOSE,
  ] },
  { t: 'box', label: 'إعراب واو القسم وتاء القسم', labelEn: 'Parsing the wāw and tāʾ of oath', lines: [
    [
      { a: 'تَكُونُ', t: 'takūnu', e: 'they are' },
      { a: 'وَاوُ', t: 'wāwu', e: 'the wāw of' },
      { a: 'الْقَسَمِ', t: 'al-qasami', e: 'oath' },
      { a: 'وَتَاءُ', t: 'wa-tāʾu', e: 'and the tāʾ of' },
      { a: 'الْقَسَمِ', t: 'al-qasami', e: 'oath' },
      { a: 'مَعَ', t: 'maʿa', e: 'with' },
      { a: 'مَجْرُورَيْهِمَا', t: 'majrūrayhimā', e: 'their genitives' },
      { a: 'بِمَعْنَى', t: 'bi-maʿnā', e: 'in the sense of' },
      { a: 'الْمَفْعُولِ', t: 'al-mafʿūli', e: 'the object' },
      { a: 'بِهِ', t: 'bihi', e: '' },
      { a: 'لِفِعْلٍ', t: 'li-fiʿlin', e: 'of a verb' },
      { a: 'مَحْذُوفٍ،', t: 'maḥdhūfin', e: 'omitted' },
      { a: 'تَقْدِيرُهُ', t: 'taqdīruhu', e: 'implicitly' },
      { a: 'أُقْسِمُ', t: 'uqsimu', e: 'I swear' },
    ],
  ] },
  { t: 'box', label: 'باء القسم', labelEn: 'The bāʾ of oath', lines: [
    [
      { a: 'تَأْتِي', t: 'taʾtī', e: 'the bāʾ comes' },
      { a: 'الْبَاءُ', t: 'al-bāʾu', e: '' },
      { a: 'لِلْقَسَمِ،', t: 'lil-qasami', e: 'for the oath' },
      { a: 'وَهِيَ', t: 'wa-hiya', e: 'and it is' },
      { a: 'أَصْلُ', t: 'aṣlu', e: 'the origin of' },
      { a: 'أَحْرُفِ', t: 'aḥrufi', e: 'the particles of' },
      { a: 'الْقَسَمِ،', t: 'al-qasami', e: 'oath' },
      { a: 'وَيَجُوزُ', t: 'wa-yajūzu', e: 'and it is allowed' },
      { a: 'فِي', t: 'fī', e: 'with' },
      { a: 'فِعْلِ', t: 'fiʿli', e: 'the verb of' },
      { a: 'الْقَسَمِ', t: 'al-qasami', e: 'oath' },
      { a: 'مَعَهَا', t: 'maʿahā', e: 'with it' },
      ELL,
    ],
    [
      { a: 'ذِكْرُهُ،', t: 'dhikruhu', e: 'mentioning it' },
      NAHW, { g: ':' }, OPEN,
      { a: 'لَا', t: 'lā', e: 'I swear', q: 1 },
      { a: 'أُقْسِمُ', t: 'uqsimu', e: '', q: 1 },
      { a: 'بِيَوْمِ', t: 'bi-yawmi', e: 'by the Day of', q: 1 },
      { a: 'الْقِيَامَةِ', t: 'al-qiyāmati', e: 'Resurrection', q: 1 },
      CLOSE,
    ],
    [
      { a: 'وَحَذْفُهُ،', t: 'wa-ḥadhfuhu', e: 'and omitting it' },
      NAHW, { g: ':' }, OPEN,
      { a: 'فَبِعِزَّتِكَ', t: 'fa-bi-ʿizzatika', e: 'then by Your might', q: 1 },
      { a: 'لَأُغْوِيَنَّهُمْ', t: 'la-ughwiyannahum', e: 'I will surely mislead them', q: 1 },
      { a: 'أَجْمَعِينَ', t: 'ajmaʿīna', e: 'all', q: 1 },
      CLOSE,
    ],
  ] },

  /* ── mudh / mundhu ── */
  { t: 'page', n: '٥٢' },
  { t: 'line', w: [
    { a: 'الثَّانِيَ', t: 'ath-thāniya', e: 'the twelf-' },
    { a: 'عَشَرَ', t: 'ʿashara', e: '-th' }, { g: ':' },
    { a: 'مُذْ،', t: 'mudh', e: 'mudh (since)' },
  ] },
  { t: 'line', w: [
    { a: 'الثَّالِثَ', t: 'ath-thālitha', e: 'the thir-' },
    { a: 'عَشَرَ', t: 'ʿashara', e: '-teenth' }, { g: ':' },
    { a: 'مُنْذُ،', t: 'mundhu', e: 'mundhu (since)' },
  ] },
  { t: 'line', w: [
    { a: 'تَكُونُ', t: 'takūnu', e: 'mudh and mundhu are' },
    { a: 'مُذْ', t: 'mudh', e: '' },
    { a: 'وَمُنْذُ', t: 'wa-mundhu', e: '' },
    { a: 'مَعَ', t: 'maʿa', e: 'with' },
    { a: 'مَجْرُورَيْهِمَا', t: 'majrūrayhimā', e: 'their genitives' },
    { a: 'بِمَعْنَى', t: 'bi-maʿnā', e: 'in the sense of' },
    { a: 'الْمَفْعُولِ', t: 'al-mafʿūli', e: 'the adverbial' },
    { a: 'فِيهِ،', t: 'fīhi', e: 'object' },
    NAHW, { g: ':' },
    { a: 'مَا', t: 'mā', e: 'I have not' },
    { a: 'تَرَكْتُ', t: 'taraktu', e: 'left' },
    { a: 'صَلَاةً', t: 'ṣalātan', e: 'a prayer' },
    { a: 'مُذْ', t: 'mudh', e: 'since' },
    { a: 'يَوْمِ', t: 'yawmi', e: 'the day of' },
    { a: 'الْبُلُوغِ', t: 'al-bulūghi', e: 'maturity' },
  ] },
  { t: 'box', label: 'معنى مذ ومنذ', labelEn: 'The senses of mudh / mundhu', lines: [
    [
      { a: 'تُفِيدَانِ', t: 'tufīdāni', e: 'they convey' },
      { a: 'مَعْنَى', t: 'maʿnā', e: 'the sense of' },
      { a: 'فِي', t: 'fī', e: '“fī (in)”' },
      { a: 'إِنْ', t: 'in', e: 'if' },
      { a: 'كَانَ', t: 'kāna', e: 'is' },
      { a: 'مَجْرُورُهُمَا', t: 'majrūruhumā', e: 'their genitive' },
      { a: 'مَعْرِفَةً،', t: 'maʿrifatan', e: 'definite' },
      NAHW, { g: ':' },
      { a: 'مَا', t: 'mā', e: 'I have not' },
      { a: 'رَأَيْتُهُ', t: 'raʾaytuhu', e: 'seen him' },
      { a: 'مُنْذُ', t: 'mundhu', e: 'in' },
      { a: 'الْيَوْمِ', t: 'al-yawmi', e: 'the day (today)' },
    ],
    [
      { a: 'وَمَعْنَى', t: 'wa-maʿnā', e: 'and the sense of' },
      { a: 'مِنْ', t: 'min', e: '“min (from)”' },
      { a: 'إِنْ', t: 'in', e: 'if' },
      { a: 'كَانَ', t: 'kāna', e: 'is' },
      { a: 'نَكِرَةً،', t: 'nakiratan', e: 'indefinite' },
      NAHW, { g: ':' },
      { a: 'مَا', t: 'mā', e: 'I have not' },
      { a: 'رَأَيْتُهُ', t: 'raʾaytuhu', e: 'seen him' },
      { a: 'مُنْذُ', t: 'mundhu', e: 'for' },
      { a: 'يَوْمَيْنِ', t: 'yawmayni', e: 'two days' },
    ],
  ] },
  { t: 'box', label: 'الفعل قبلهما', labelEn: 'The verb before mudh / mundhu', lines: [
    [
      { a: 'يُشْتَرَطُ', t: 'yushtaraṭu', e: 'it is required' },
      { a: 'فِي', t: 'fī', e: 'in' },
      { a: 'الْفِعْلِ', t: 'al-fiʿli', e: 'the verb' },
      { a: 'قَبْلَهُمَا', t: 'qablahumā', e: 'before them' },
      { a: 'أَنْ', t: 'an', e: 'that' },
      { a: 'يَكُونَ', t: 'yakūna', e: 'it be' },
      { a: 'مَاضِيًا', t: 'māḍiyan', e: 'past' },
      { a: 'مَنْفِيًّا،', t: 'manfiyyan', e: 'negated' },
      NAHW, { g: ':' },
      { a: 'مَا', t: 'mā', e: 'I have not' },
      { a: 'رَأَيْتُهُ', t: 'raʾaytuhu', e: 'seen him' },
      { a: 'مُنْذُ', t: 'mundhu', e: 'since' },
      { a: 'يَوْمِ', t: 'yawmi', e: 'the day of' },
      { a: 'الْجُمُعَةِ', t: 'al-jumuʿati', e: 'Friday' },
    ],
    [
      { a: 'أَوْ', t: 'aw', e: 'or' },
      { a: 'مُثْبَتًا', t: 'muthbatan', e: 'affirmative' },
      { a: 'مُمْتَدًّا،', t: 'mumtaddan', e: 'extended' },
      NAHW, { g: ':' },
      { a: 'نِمْتُ', t: 'nimtu', e: 'I have slept' },
      { a: 'مُنْذُ', t: 'mundhu', e: 'since' },
      { a: 'بَعْدَ', t: 'baʿda', e: 'after' },
      { a: 'الْعِشَاءِ', t: 'al-ʿishāʾi', e: 'ʿishāʾ' },
    ],
  ] },

  /* ── kind 2: the preposition resembling the redundant ── */
  { t: 'page', n: '٥٣' },
  { t: 'h2', c: 'green', ar: 'الضَّرْبُ الثَّانِي: حَرْفُ الْجَرِّ الشَّبِيهُ بِالزَّائِدِ', en: 'Second kind — the preposition resembling the redundant' },
  { t: 'line', w: [
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
    { a: 'مَا', t: 'mā', e: 'what' },
    { a: 'يُفِيدُ', t: 'yufīdu', e: 'gives' },
    { a: 'مَعْنًى', t: 'maʿnan', e: 'a meaning' },
    { a: 'خَاصًّا،', t: 'khāṣṣan', e: 'special' },
    { a: 'وَلَا', t: 'wa-lā', e: 'but not' },
    { a: 'يَكُونُ', t: 'yakūnu', e: 'is it' },
    { a: 'مَعَ', t: 'maʿa', e: 'with' },
    { a: 'مَجْرُورِهِ', t: 'majrūrihi', e: 'its genitive' },
    { a: 'مَعْمُولًا', t: 'maʿmūlan', e: 'governed' },
    { a: 'لِفِعْلٍ', t: 'li-fiʿlin', e: 'by a verb' },
    { a: 'أَوْ', t: 'aw', e: 'or' },
    { a: 'شِبْهِ', t: 'shibhi', e: 'something verb-' },
    { a: 'الْفِعْلِ،', t: 'al-fiʿli', e: 'like' },
  ] },
  { t: 'line', w: [
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
    { a: 'ثَلَاثٌ', t: 'thalāthun', e: 'three' }, { g: ':' },
  ] },
  { t: 'line', w: [
    { a: 'الْأَوَّلُ', t: 'al-awwalu', e: 'the first' }, { g: ':' },
    { a: 'رُبَّ،', t: 'rubba', e: 'rubba (many a / few a)' },
    NAHW, { g: ':' },
    { a: 'رُبَّ', t: 'rubba', e: 'many a' },
    { a: 'شَهْوَةٍ', t: 'shahwatin', e: 'desire' },
    { a: 'تُورِثُ', t: 'tūrithu', e: 'bequeaths' },
    { a: 'حُزْنًا', t: 'ḥuznan', e: 'grief' },
    { a: 'طَوِيلًا', t: 'ṭawīlan', e: 'long' },
  ] },
  { t: 'page', n: '٥٤' },
  { t: 'box', label: 'أحكام رُبّ', labelEn: 'Rulings of rubba', lines: [
    [
      { a: 'وَهِيَ', t: 'wa-hiya', e: 'it is' },
      { a: 'لِتَكْثِيرِ', t: 'li-takthīri', e: 'for making many' },
      { a: 'مَجْرُورِهَا', t: 'majrūrihā', e: 'its genitive' },
      { a: 'أَوْ', t: 'aw', e: 'or' },
      { a: 'تَقْلِيلِهِ،', t: 'taqlīlihi', e: 'few' },
      { a: 'وَالْقَرِينَةُ', t: 'wal-qarīnatu', e: 'and context' },
      { a: 'تُعَيِّنُ', t: 'tuʿayyinu', e: 'determines' },
      { a: 'الْمُرَادَ', t: 'al-murāda', e: 'which is meant' },
    ],
    [
      { a: 'لَا', t: 'lā', e: 'it does not' },
      { a: 'تَقَعُ', t: 'taqaʿu', e: 'occur' },
      { a: 'رُبَّ', t: 'rubba', e: 'rubba' },
      { a: 'إِلَّا', t: 'illā', e: 'except' },
      { a: 'فِي', t: 'fī', e: 'at' },
      { a: 'صَدْرِ', t: 'ṣadri', e: 'the start of' },
      { a: 'الْكَلَامِ،', t: 'al-kalāmi', e: 'speech' },
      { a: 'وَقَدْ', t: 'wa-qad', e: 'and may' },
      { a: 'تَتَقَدَّمُهَا', t: 'tataqaddamuhā', e: 'be preceded by' },
      { a: 'حَرْفُ', t: 'ḥarfu', e: 'the particle of' },
      { a: 'النِّدَاءِ،', t: 'an-nidāʾi', e: 'calling' },
      NAHW, { g: ':' },
      { a: 'يَا', t: 'yā', e: 'O,' },
      { a: 'رُبَّ', t: 'rubba', e: 'many a' },
      { a: 'كَاسِيَةٍ', t: 'kāsiyatin', e: 'clothed woman' },
      { a: 'فِي', t: 'fī', e: 'in' },
      { a: 'الدُّنْيَا', t: 'ad-dunyā', e: 'this world' },
      { a: 'عَارِيَةٍ', t: 'ʿāriyatin', e: 'is naked' },
      { a: 'فِي', t: 'fī', e: 'in' },
      { a: 'الْآخِرَةِ', t: 'al-ākhirati', e: 'the Hereafter' },
    ],
    [
      { a: 'وَلَا', t: 'wa-lā', e: 'and' },
      { a: 'يَكُونُ', t: 'yakūnu', e: 'its genitive is only' },
      { a: 'مَجْرُورُهَا', t: 'majrūruhā', e: '' },
      { a: 'إِلَّا', t: 'illā', e: '' },
      { a: 'اسْمًا', t: 'isman', e: 'an overt' },
      { a: 'ظَاهِرًا', t: 'ẓāhiran', e: 'noun' },
      { a: 'نَكِرَةً،', t: 'nakiratan', e: 'indefinite' },
      { a: 'أَوْ', t: 'aw', e: 'or' },
      { a: 'ضَمِيرًا', t: 'ḍamīran', e: 'an ambiguous' },
      { a: 'مُبْهَمًا', t: 'mubhaman', e: 'pronoun' },
      { a: 'مُفَسَّرًا', t: 'mufassaran', e: 'explained' },
      { a: 'بِتَمْيِيزٍ،', t: 'bi-tamyīzin', e: 'by a tamyīz' },
      NAHW, { g: ':' },
      { a: 'رُبَّهُ', t: 'rubbahu', e: 'many a one —' },
      { a: 'رَجُلًا', t: 'rajulan', e: 'a man' },
      { a: 'كَرِيمًا', t: 'karīman', e: 'noble' },
      { a: 'لَقِيتُهُ', t: 'laqītuhu', e: 'I met him' },
    ],
    [
      { a: 'وَيُزَادُ', t: 'wa-yuzādu', e: 'and the kāffah' },
      { a: 'مَا', t: 'mā', e: 'mā' },
      { a: 'الْكَافَّةُ', t: 'al-kāffatu', e: 'is added' },
      { a: 'عَلَى', t: 'ʿalā', e: 'to' },
      { a: 'رُبَّ', t: 'rubba', e: 'rubba' },
      { a: 'فَتَكُفُّهَا', t: 'fa-takuffuhā', e: 'stopping it' },
      { a: 'عَنِ', t: 'ʿani', e: 'from' },
      { a: 'الْعَمَلِ،', t: 'al-ʿamali', e: 'governing' },
      NAHW, { g: ':' },
      { a: 'رُبَّمَا', t: 'rubbamā', e: 'perhaps' },
      { a: 'يَصُومُ', t: 'yaṣūmu', e: 'fasts' },
      { a: 'زَيْدٌ', t: 'zaydun', e: 'Zayd' },
    ],
    [
      { a: 'وَقَدْ', t: 'wa-qad', e: 'and its bāʾ' },
      { a: 'تُخَفَّفُ', t: 'tukhaffafu', e: 'may be lightened' },
      { a: 'بَاؤُهَا،', t: 'bāʾuhā', e: '(rubba → ruba)' },
      NAHW, { g: ':' }, OPEN,
      { a: 'رُبَمَا', t: 'rubamā', e: 'perhaps', q: 1 },
      { a: 'يَوَدُّ', t: 'yawaddu', e: 'will wish', q: 1 },
      { a: 'الَّذِينَ', t: 'alladhīna', e: 'those who', q: 1 },
      { a: 'كَفَرُوا', t: 'kafarū', e: 'disbelieved', q: 1 },
      { a: 'لَوْ', t: 'law', e: 'that', q: 1 },
      { a: 'كَانُوا', t: 'kānū', e: 'they had been', q: 1 },
      { a: 'مُسْلِمِينَ', t: 'muslimīna', e: 'Muslims', q: 1 },
      CLOSE,
    ],
  ] },
  { t: 'page', n: '٥٥' },
  { t: 'box', label: 'حذف رُبّ', labelEn: 'Dropping rubba', lines: [
    [
      { a: 'قَدْ', t: 'qad', e: 'sometimes' },
      { a: 'تُحْذَفُ', t: 'tuḥdhafu', e: 'rubba is dropped,' },
      { a: 'رُبَّ', t: 'rubba', e: '' },
      { a: 'وَيَبْقَى', t: 'wa-yabqā', e: 'and its governance remains' },
      { a: 'عَمَلُهَا', t: 'ʿamaluhā', e: '' },
      { a: 'بَعْدَ', t: 'baʿda', e: 'after' },
      { a: 'الْوَاوِ', t: 'al-wāwi', e: 'the wāw' },
      { a: 'كَثِيرًا،', t: 'kathīran', e: 'often,' },
      { a: 'وَبَعْدَ', t: 'wa-baʿda', e: 'and after' },
      { a: 'الْفَاءِ', t: 'al-fāʾi', e: 'the fāʾ' },
      { a: 'قَلِيلًا،', t: 'qalīlan', e: 'rarely' },
      NAHW, { g: ':' },
      { a: 'وَلَيْلٍ', t: 'wa-laylin', e: 'and many a night' },
      { a: 'كَمَوْجِ', t: 'ka-mawji', e: 'like the waves of' },
      { a: 'الْبَحْرِ', t: 'al-baḥri', e: 'the sea' },
      { a: 'أَرْخَى', t: 'arkhā', e: 'let down' },
      { a: 'سُدُولَهُ', t: 'sudūlahu', e: 'its veils' },
    ],
    [
      { a: 'إِذَا', t: 'idhā', e: 'when' },
      { a: 'وَقَعَتْ', t: 'waqaʿat', e: 'mā comes' },
      { a: 'مَا', t: 'mā', e: '' },
      { a: 'بَعْدَ', t: 'baʿda', e: 'after' },
      { a: 'مِنْ', t: 'min', e: 'min,' },
      { a: 'قَدْ', t: 'qad', e: 'it may' },
      { a: 'تُفِيدُ', t: 'tufīdu', e: 'give' },
      { a: 'مَعْنَى', t: 'maʿnā', e: 'the sense of' },
      { a: 'رُبَّ،', t: 'rubba', e: 'rubba' },
      NAHW, { g: ':' },
      { a: 'كَانَ', t: 'kāna', e: 'he was' },
      { a: 'ﷺ', t: 'ṣallā-llāhu ʿalayhi wa-sallam', e: '(ﷺ)' },
      { a: 'مِمَّا', t: 'mimmā', e: 'one who often' },
      { a: 'يُحَرِّكُ', t: 'yuḥarriku', e: 'moved' },
      { a: 'شَفَتَيْهِ', t: 'shafatayhi', e: 'his lips' },
    ],
  ] },
  { t: 'line', w: [
    { a: 'الثَّانِي', t: 'ath-thānī', e: 'the second' }, { g: ':' },
    { a: 'التَّبْعِيضِيَّةُ،', t: 'at-tabʿīḍiyyatu', e: 'the partitive (min)' },
    NAHW, { g: ':' }, OPEN,
    { a: 'وَلَقَدْ', t: 'wa-laqad', e: 'and there has come', q: 1 },
    { a: 'جَاءَكَ', t: 'jāʾaka', e: 'to you', q: 1 },
    { a: 'مِنْ', t: 'min', e: 'some of', q: 1 },
    { a: 'نَبَإِ', t: 'nabaʾi', e: 'the news of', q: 1 },
    { a: 'الْمُرْسَلِينَ', t: 'al-mursalīna', e: 'the messengers', q: 1 },
    CLOSE,
    { a: 'وَنحو:', t: 'wa-naḥwa', e: 'and e.g.' },
    { a: 'عِنْدِي', t: 'ʿindī', e: 'I have' },
    { a: 'مِنْ', t: 'min', e: 'some' },
    { a: 'مَاءٍ', t: 'māʾin', e: 'water' },
  ] },
  { t: 'line', w: [
    { a: 'الثَّالِثُ', t: 'ath-thālithu', e: 'the third' }, { g: ':' },
    { a: 'حَاشَا،', t: 'ḥāshā', e: 'ḥāshā (except)' },
    NAHW, { g: ':' },
    { a: 'هَلَكَ', t: 'halaka', e: 'perished' },
    { a: 'النَّاسُ', t: 'an-nāsu', e: 'the people' },
    { a: 'حَاشَا', t: 'ḥāshā', e: 'except' },
    { a: 'الْعَالِمِ', t: 'al-ʿālimi', e: 'the scholar' },
  ] },

  /* ── kind 3: the redundant preposition ── */
  { t: 'h2', c: 'green', ar: 'الضَّرْبُ الثَّالِثُ: حَرْفُ الْجَرِّ الزَّائِدُ', en: 'Third kind — the redundant preposition' },
  { t: 'line', w: [
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
    { a: 'مَا', t: 'mā', e: 'what' },
    { a: 'لَا', t: 'lā', e: 'does not' },
    { a: 'يُفِيدُ', t: 'yufīdu', e: 'give' },
    { a: 'مَعْنًى', t: 'maʿnan', e: 'any meaning' },
    { a: 'إِلَّا', t: 'illā', e: 'except' },
    { a: 'التَّأْكِيدَ،', t: 'at-taʾkīda', e: 'emphasis' },
    { a: 'وَلَا', t: 'wa-lā', e: 'and not' },
    { a: 'يَكُونُ', t: 'yakūnu', e: 'is it' },
    { a: 'مَعَ', t: 'maʿa', e: 'with' },
    { a: 'مَجْرُورِهِ', t: 'majrūrihi', e: 'its genitive' },
    { a: 'مَعْمُولًا', t: 'maʿmūlan', e: 'governed' },
    { a: 'لِفِعْلٍ', t: 'li-fiʿlin', e: 'by a verb' },
    { a: 'أَوْ', t: 'aw', e: 'or' },
    { a: 'شِبْهِ', t: 'shibhi', e: 'something verb-' },
    { a: 'الْفِعْلِ،', t: 'al-fiʿli', e: 'like' },
  ] },
  { t: 'line', w: [
    { a: 'وَهِيَ', t: 'wa-hiya', e: 'and they are' },
    { a: 'أَرْبَعَةٌ', t: 'arbaʿatun', e: 'four' }, { g: ':' },
  ] },
  { t: 'line', w: [
    { a: 'الْأَوَّلُ', t: 'al-awwalu', e: 'the first' }, { g: ':' },
    { a: 'الْبَاءُ', t: 'al-bāʾu', e: 'the redundant' },
    { a: 'الزَّائِدَةُ،', t: 'az-zāʾidatu', e: 'bāʾ' },
  ] },
  { t: 'line', w: [
    { a: 'تَقَعُ', t: 'taqaʿu', e: 'the redundant bāʾ occurs' },
    { a: 'الْبَاءُ', t: 'al-bāʾu', e: '' },
    { a: 'الزَّائِدَةُ', t: 'az-zāʾidatu', e: '' },
    { a: 'قِيَاسًا', t: 'qiyāsan', e: 'regularly' },
    { a: 'فِي', t: 'fī', e: 'in' },
    { a: 'خَبَرِ', t: 'khabari', e: 'the predicate of' },
    { a: 'النَّفْيِ', t: 'an-nafyi', e: 'negation' }, { g: ':' },
  ] },
  { t: 'line', w: [
    { a: 'بِلَيْسَ،', t: 'bi-laysa', e: 'with laysa' },
    NAHW, { g: ':' }, OPEN,
    { a: 'وَأَنَّ', t: 'wa-anna', e: 'and that', q: 1 },
    { a: 'اللهَ', t: 'Allāha', e: 'Allah', q: 1 },
    { a: 'لَيْسَ', t: 'laysa', e: 'is not', q: 1 },
    { a: 'بِظَلَّامٍ', t: 'bi-ẓallāmin', e: 'unjust', q: 1 },
    { a: 'لِلْعَبِيدِ', t: 'lil-ʿabīdi', e: 'to His servants', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'وَمَا،', t: 'wa-mā', e: 'and with mā' },
    NAHW, { g: ':' }, OPEN,
    { a: 'وَمَا', t: 'wa-mā', e: 'and your Lord is not', q: 1 },
    { a: 'رَبُّكَ', t: 'rabbuka', e: '', q: 1 },
    { a: 'بِظَلَّامٍ', t: 'bi-ẓallāmin', e: 'unjust', q: 1 },
    { a: 'لِلْعَبِيدِ', t: 'lil-ʿabīdi', e: 'to His servants', q: 1 },
    CLOSE,
  ] },
  { t: 'page', n: '٥٦' },
  { t: 'line', w: [
    { a: 'وَتَقَعُ', t: 'wa-taqaʿu', e: 'and it occurs' },
    { a: 'سَمَاعًا', t: 'samāʿan', e: 'by heard usage' }, { g: ':' },
  ] },
  { t: 'line', w: [
    { a: 'فِي', t: 'fī', e: 'in' },
    { a: 'خَبَرِ', t: 'khabari', e: 'the predicate of' },
    { a: 'الِاسْتِفْهَامِ', t: 'al-istifhāmi', e: 'an interrogative' },
    { a: 'بِهَلْ،', t: 'bi-hal', e: 'with hal' },
    NAHW, { g: ':' },
    { a: 'هَلْ', t: 'hal', e: 'is' },
    { a: 'زَيْدٌ', t: 'zaydun', e: 'Zayd' },
    { a: 'بِقَائِمٍ؟', t: 'bi-qāʾimin', e: 'standing?' },
  ] },
  { t: 'line', w: [
    { a: 'وَفِي', t: 'wa-fī', e: 'and in' },
    { a: 'التَّأْكِيدِ', t: 'at-taʾkīdi', e: 'emphasis' },
    { a: 'الْمَعْنَوِيِّ', t: 'al-maʿnawiyyi', e: 'by meaning' },
    { a: 'بِنَفْسٍ،', t: 'bi-nafsin', e: 'with nafs' },
    NAHW, { g: ':' },
    { a: 'نَظَّفَ', t: 'naẓẓafa', e: 'cleaned' },
    { a: 'الْأَمِيرُ', t: 'al-amīru', e: 'the prince' },
    { a: 'الْمَسْجِدَ', t: 'al-masjida', e: 'the mosque' },
    { a: 'بِنَفْسِهِ', t: 'bi-nafsihi', e: 'himself' },
  ] },
  { t: 'line', w: [
    { a: 'وَفِي', t: 'wa-fī', e: 'and in' },
    { a: 'فَاعِلِ', t: 'fāʿili', e: 'the doer of' },
    { a: 'أَفْعِلْ', t: 'afʿil', e: 'afʿil' },
    { a: 'بِهِ', t: 'bihi', e: 'bihi' },
    { a: 'لِلتَّعَجُّبِ،', t: 'lit-taʿajjubi', e: 'for wonder' },
    NAHW, { g: ':' }, OPEN,
    { a: 'أَسْمِعْ', t: 'asmiʿ', e: 'how well they hear', q: 1 },
    { a: 'بِهِمْ', t: 'bihim', e: '', q: 1 },
    { a: 'وَأَبْصِرْ', t: 'wa-abṣir', e: 'and see', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'وَفِي', t: 'wa-fī', e: 'and in' },
    { a: 'الْمُبْتَدَأِ', t: 'al-mubtadaʾi', e: 'the subject' },
    { a: 'بَعْدَ', t: 'baʿda', e: 'after' },
    { a: 'إِذَا', t: 'idhā', e: 'the sudden' },
    { a: 'الْفُجَائِيَّةِ،', t: 'al-fujāʾiyyati', e: 'idhā' },
    NAHW, { g: ':' },
    { a: 'دَخَلَ', t: 'dakhala', e: 'the man entered' },
    { a: 'الرَّجُلُ', t: 'ar-rajulu', e: '' },
    { a: 'فَإِذَا', t: 'fa-idhā', e: 'and lo,' },
    { a: 'بِابْنِهِ', t: 'bi-bnihi', e: 'his son' },
    { a: 'يُصَلِّي', t: 'yuṣallī', e: 'was praying' },
  ] },
  { t: 'line', w: [
    { a: 'وَفِي', t: 'wa-fī', e: 'and in' },
    { a: 'الْمُبْتَدَأِ', t: 'al-mubtadaʾi', e: 'a subject' },
    { a: 'بِلَفْظِ', t: 'bi-lafẓi', e: 'of the word' },
    { a: 'حَسْبُ،', t: 'ḥasbu', e: 'ḥasb' },
    NAHW, { g: ':' },
    { a: 'بِحَسْبِكَ', t: 'bi-ḥasbika', e: 'enough for you is' },
    { a: 'أَنْ', t: 'an', e: 'that' },
    { a: 'تَصُومَ', t: 'taṣūma', e: 'you fast' },
    { a: 'كُلَّ', t: 'kulla', e: 'each' },
    { a: 'شَهْرٍ', t: 'shahrin', e: 'month' },
    { a: 'ثَلَاثَةَ', t: 'thalāthata', e: 'three' },
    { a: 'أَيَّامٍ', t: 'ayyāmin', e: 'days' },
  ] },
  { t: 'line', w: [
    { a: 'وَخَبَرِ', t: 'wa-khabari', e: 'and the predicate of' },
    { a: 'حَسْبُ،', t: 'ḥasbu', e: 'ḥasb' },
    NAHW, { g: ':' },
    { a: 'حَسْبُكَ', t: 'ḥasbuka', e: 'enough for you is' },
    { a: 'بِزَيْدٍ', t: 'bi-zaydin', e: 'Zayd' },
  ] },
  { t: 'line', w: [
    { a: 'وَفِي', t: 'wa-fī', e: 'and in' },
    { a: 'فَاعِلِ', t: 'fāʿili', e: 'the doer of' },
    { a: 'كَفَى', t: 'kafā', e: 'kafā' },
    { a: 'بِمَعْنَى', t: 'bi-maʿnā', e: 'meaning' },
    { a: 'حَسْبُ،', t: 'ḥasbu', e: 'ḥasb (suffice)' },
    NAHW, { g: ':' }, OPEN,
    { a: 'كَفَى', t: 'kafā', e: 'sufficient is', q: 1 },
    { a: 'بِاللهِ', t: 'bi-llāhi', e: 'Allah', q: 1 },
    { a: 'شَهِيدًا', t: 'shahīdan', e: 'as witness', q: 1 },
    CLOSE,
    { a: 'بِخِلَافِ', t: 'bi-khilāfi', e: 'unlike' },
    { a: 'كَفَى', t: 'kafā', e: 'kafā' },
    { a: 'بِمَعْنَى', t: 'bi-maʿnā', e: 'meaning' },
    { a: 'وَقَى،', t: 'waqā', e: 'to protect' },
    NAHW, { g: ':' }, OPEN,
    { a: 'وَكَفَى', t: 'wa-kafā', e: 'and Allah sufficed', q: 1 },
    { a: 'اللهُ', t: 'Allāhu', e: '', q: 1 },
    { a: 'الْمُؤْمِنِينَ', t: 'al-muʾminīna', e: 'the believers', q: 1 },
    { a: 'الْقِتَالَ', t: 'al-qitāla', e: 'the fighting', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'الثَّانِي', t: 'ath-thānī', e: 'the second' }, { g: ':' },
    { a: 'مِنْ', t: 'min', e: 'the redundant' },
    { a: 'الزَّائِدَةُ،', t: 'az-zāʾidatu', e: 'min' },
  ] },
  { t: 'line', w: [
    { a: 'تَقَعُ', t: 'taqaʿu', e: 'the redundant min occurs' },
    { a: 'مِنْ', t: 'min', e: '' },
    { a: 'الزَّائِدَةُ', t: 'az-zāʾidatu', e: '' },
    { a: 'عَلَى', t: 'ʿalā', e: 'on' },
    { a: 'تَمْيِيزِ', t: 'tamyīzi', e: 'the tamyīz of' },
    { a: 'كَمِ', t: 'kami', e: 'the declarative' },
    { a: 'الْخَبَرِيَّةِ،', t: 'al-khabariyyati', e: 'kam' },
    NAHW, { g: ':' }, OPEN,
    { a: 'كَمْ', t: 'kam', e: 'how many', q: 1 },
    { a: 'آتَيْنَاهُمْ', t: 'ātaynāhum', e: 'We gave them', q: 1 },
    { a: 'مِنْ', t: 'min', e: 'of', q: 1 },
    { a: 'آيَةٍ', t: 'āyatin', e: 'a sign', q: 1 },
    { a: 'بَيِّنَةٍ', t: 'bayyinatin', e: 'clear', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'وَفِي', t: 'wa-fī', e: 'and in' },
    { a: 'كَلَامٍ', t: 'kalāmin', e: 'speech' },
    { a: 'غَيْرِ', t: 'ghayri', e: 'non-' },
    { a: 'مُوجَبٍ', t: 'mūjabin', e: 'affirmative' }, { g: ':' },
    { a: 'بِأَدَاةٍ', t: 'bi-adātin', e: 'with a particle' },
    { a: 'مِنْ', t: 'min', e: 'of' },
    { a: 'أَدَوَاتِ', t: 'adawāti', e: 'the particles of' },
    { a: 'النَّفْيِ،', t: 'an-nafyi', e: 'negation' },
    NAHW, { g: ':' }, OPEN,
    { a: 'مَا', t: 'mā', e: 'there came not', q: 1 },
    { a: 'جَاءَنَا', t: 'jāʾanā', e: 'to us', q: 1 },
    { a: 'مِنْ', t: 'min', e: 'any', q: 1 },
    { a: 'بَشِيرٍ', t: 'bashīrin', e: 'bringer of good news', q: 1 },
    { a: 'وَلَا', t: 'wa-lā', e: 'nor', q: 1 },
    { a: 'نَذِيرٍ', t: 'nadhīrin', e: 'warner', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'أَوْ', t: 'aw', e: 'or' },
    { a: 'بِاسْتِفْهَامٍ', t: 'bi-istifhāmin', e: 'with an interrogative' },
    { a: 'بِمَعْنَى', t: 'bi-maʿnā', e: 'meaning' },
    { a: 'النَّفْيِ،', t: 'an-nafyi', e: 'negation' },
    NAHW, { g: ':' }, OPEN,
    { a: 'هَلْ', t: 'hal', e: 'is there', q: 1 },
    { a: 'مِنْ', t: 'min', e: 'any', q: 1 },
    { a: 'خَالِقٍ', t: 'khāliqin', e: 'creator', q: 1 },
    { a: 'غَيْرُ', t: 'ghayru', e: 'other than', q: 1 },
    { a: 'اللهِ', t: 'Allāhi', e: 'Allah', q: 1 },
    CLOSE,
  ] },
  { t: 'page', n: '٥٧' },
  { t: 'line', w: [
    { a: 'أَوْ', t: 'aw', e: 'or' },
    { a: 'فِي', t: 'fī', e: 'in' },
    { a: 'سِيَاقِ', t: 'siyāqi', e: 'the context of' },
    { a: 'اسْتِفْهَامٍ', t: 'istifhāmin', e: 'an interrogative' },
    { a: 'بِهَلْ،', t: 'bi-hal', e: 'with hal' },
    NAHW, { g: ':' }, OPEN,
    { a: 'هَلْ', t: 'hal', e: 'is there', q: 1 },
    { a: 'مِنْ', t: 'min', e: 'any', q: 1 },
    { a: 'مَزِيدٍ', t: 'mazīdin', e: 'more', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'الثَّالِثُ', t: 'ath-thālithu', e: 'the third' }, { g: ':' },
    { a: 'اللَّامُ', t: 'al-lāmu', e: 'the redundant' },
    { a: 'الزَّائِدَةُ،', t: 'az-zāʾidatu', e: 'lām' },
  ] },
  { t: 'line', w: [
    { a: 'تَقَعُ', t: 'taqaʿu', e: 'it occurs' },
    { a: 'عَلَى', t: 'ʿalā', e: 'on' },
    { a: 'خَبَرِ', t: 'khabari', e: 'the predicate of' },
    { a: 'كَانَ', t: 'kāna', e: 'negated' },
    { a: 'الْمَنْفِيِّ،', t: 'al-manfiyyi', e: 'kāna' },
    { a: 'وَتُسَمَّى', t: 'wa-tusammā', e: 'called' },
    { a: 'لَامَ', t: 'lāma', e: 'the lām of' },
    { a: 'الْجُحُودِ،', t: 'al-juḥūdi', e: 'denial' },
    NAHW, { g: ':' }, OPEN,
    { a: 'فَمَا', t: 'fa-mā', e: 'and Allah would not', q: 1 },
    { a: 'كَانَ', t: 'kāna', e: '', q: 1 },
    { a: 'اللهُ', t: 'Allāhu', e: '', q: 1 },
    { a: 'لِيَظْلِمَهُمْ', t: 'li-yaẓlimahum', e: 'wrong them', q: 1 },
    CLOSE,
  ] },
  { t: 'page', n: '٥٨' },
  { t: 'line', w: [
    { a: 'وَعَلَى', t: 'wa-ʿalā', e: 'and on' },
    { a: 'الْفَاعِلِ،', t: 'al-fāʿili', e: 'the doer' },
    { a: 'وَتُسَمَّى', t: 'wa-tusammā', e: 'called' },
    { a: 'لَامَ', t: 'lāma', e: 'the lām of' },
    { a: 'التَّبْيِينِ،', t: 'at-tabyīni', e: 'clarification' },
    NAHW, { g: ':' }, OPEN,
    { a: 'هَيْتَ', t: 'hayta', e: 'come', q: 1 },
    { a: 'لَكَ', t: 'laka', e: 'you', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'وَعَلَى', t: 'wa-ʿalā', e: 'and on' },
    { a: 'الْمَعْمُولِ', t: 'al-maʿmūli', e: 'a governed term' },
    { a: 'الْمُقَدَّمِ', t: 'al-muqaddami', e: 'fronted' },
    { a: 'لِلْفِعْلِ،', t: 'lil-fiʿli', e: 'before the verb' },
    NAHW, { g: ':' }, OPEN,
    { a: 'إِنْ', t: 'in', e: 'if', q: 1 },
    { a: 'كُنْتُمْ', t: 'kuntum', e: 'you', q: 1 },
    { a: 'لِلرُّؤْيَا', t: 'lir-ruʾyā', e: 'a vision', q: 1 },
    { a: 'تَعْبُرُونَ', t: 'taʿburūna', e: 'can interpret', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'وَعَلَى', t: 'wa-ʿalā', e: 'and on' },
    { a: 'مَعْمُولِ', t: 'maʿmūli', e: 'the governed term of' },
    { a: 'شِبْهِ', t: 'shibhi', e: 'something verb-' },
    { a: 'الْفِعْلِ،', t: 'al-fiʿli', e: 'like' },
    { a: 'وَتُسَمَّى', t: 'wa-tusammā', e: 'called' },
    { a: 'لَامَ', t: 'lāma', e: 'the lām of' },
    { a: 'التَّقْوِيَةِ،', t: 'at-taqwiyati', e: 'strengthening' },
    NAHW, { g: ':' }, OPEN,
    { a: 'فَعَّالٌ', t: 'faʿʿālun', e: 'doer', q: 1 },
    { a: 'لِمَا', t: 'limā', e: 'of what', q: 1 },
    { a: 'يُرِيدُ', t: 'yurīdu', e: 'He wills', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'الرَّابِعُ', t: 'ar-rābiʿu', e: 'the fourth' }, { g: ':' },
    { a: 'الْكَافُ', t: 'al-kāfu', e: 'the redundant' },
    { a: 'الزَّائِدَةُ،', t: 'az-zāʾidatu', e: 'kāf' },
    NAHW, { g: ':' }, OPEN,
    { a: 'لَيْسَ', t: 'laysa', e: 'there is not', q: 1 },
    { a: 'كَمِثْلِهِ', t: 'ka-mithlihi', e: 'like Him', q: 1 },
    { a: 'شَيْءٌ', t: 'shayʾun', e: 'anything', q: 1 },
    CLOSE,
  ] },

  /* ── appendix: disputed prepositions; dropping the preposition ── */
  { t: 'page', n: '٥٩' },
  { t: 'box', label: 'ما هو حرف جر عند البعض', labelEn: 'Particles some count as prepositions', lines: [
    [
      { a: 'الْأَوَّلُ', t: 'al-awwalu', e: 'the first:' },
      { a: 'لَعَلَّ', t: 'laʿalla', e: 'laʿalla' },
      { a: 'فِي', t: 'fī', e: 'in' },
      { a: 'لُغَةِ', t: 'lughati', e: 'the dialect of' },
      { a: 'عُقَيْلٍ،', t: 'ʿuqaylin', e: 'ʿUqayl' },
      NAHW, { g: ':' },
      { a: 'لَعَلَّ', t: 'laʿalla', e: 'perhaps' },
      { a: 'اللهِ', t: 'llāhi', e: 'Allah' },
      { a: 'فَضَّلَكُمْ', t: 'faḍḍalakum', e: 'favored you' },
      { a: 'عَلَيْنَا', t: 'ʿalaynā', e: 'over us' },
    ],
    [
      { a: 'الثَّانِي', t: 'ath-thānī', e: 'the second:' },
      { a: 'خَلَا', t: 'khalā', e: 'khalā' },
      { a: 'وَعَدَا', t: 'wa-ʿadā', e: 'and ʿadā' },
      { a: 'لِلِاسْتِثْنَاءِ،', t: 'lil-istithnāʾi', e: 'for exception' },
      { a: 'وَهُمَا', t: 'wa-humā', e: 'though both are' },
      { a: 'فِعْلَانِ', t: 'fiʿlāni', e: 'verbs' },
      { a: 'عِنْدَ', t: 'ʿinda', e: 'according to' },
      { a: 'الْأَكْثَرِ', t: 'al-aktari', e: 'most' },
      { a: 'لَا', t: 'lā', e: 'not' },
      { a: 'حَرْفَانِ', t: 'ḥarfāni', e: 'particles' },
    ],
    [
      { a: 'الثَّالِثُ', t: 'ath-thālithu', e: 'the third:' },
      { a: 'مَتَى', t: 'matā', e: 'matā' },
      { a: 'بِمَعْنَى', t: 'bi-maʿnā', e: 'meaning' },
      { a: 'مِنْ', t: 'min', e: 'min' },
      { a: 'فِي', t: 'fī', e: 'in' },
      { a: 'لُغَةِ', t: 'lughati', e: 'the dialect of' },
      { a: 'هُذَيْلٍ', t: 'hudhaylin', e: 'Hudhayl' },
    ],
    [
      { a: 'الرَّابِعُ', t: 'ar-rābiʿu', e: 'the fourth:' },
      { a: 'كَيْ', t: 'kay', e: 'kay' },
      { a: 'بِمَعْنَى', t: 'bi-maʿnā', e: 'meaning' },
      { a: 'لِمَ،', t: 'lima', e: '“why”' },
      NAHW, { g: ':' },
      { a: 'كَيْمَهْ', t: 'kaymah', e: 'why' },
      { a: 'عَصَيْتَ', t: 'ʿaṣayta', e: 'did you disobey' },
      { a: 'اللهَ؟', t: 'llāha', e: 'Allah?' },
    ],
  ] },
  { t: 'box', label: 'حذف حرف الجر', labelEn: 'Dropping the preposition', lines: [
    [
      { a: 'يَجُوزُ', t: 'yajūzu', e: 'it is allowed to' },
      { a: 'حَذْفُ', t: 'ḥadhfu', e: 'drop' },
      { a: 'حَرْفِ', t: 'ḥarfi', e: 'the preposition' },
      { a: 'الْجَرِّ', t: 'al-jarri', e: '' },
      { a: 'قِيَاسًا،', t: 'qiyāsan', e: 'regularly,' },
      { a: 'مِنْهَا', t: 'minhā', e: 'among such cases:' },
      { a: 'قَبْلَ', t: 'qabla', e: 'before' },
      { a: 'أَنْ،', t: 'an', e: 'an' },
      NAHW, { g: ':' }, OPEN,
      { a: 'إِنَّ', t: 'inna', e: 'indeed', q: 1 },
      { a: 'اللهَ', t: 'Allāha', e: 'Allah', q: 1 },
      { a: 'يَأْمُرُكُمْ', t: 'yaʾmurukum', e: 'commands you', q: 1 },
      { a: 'أَنْ', t: 'an', e: 'to', q: 1 },
      { a: 'تُؤَدُّوا', t: 'tuʾaddū', e: 'render', q: 1 },
      { a: 'الْأَمَانَاتِ', t: 'al-amānāti', e: 'the trusts', q: 1 },
      { a: 'إِلَى', t: 'ilā', e: 'to', q: 1 },
      { a: 'أَهْلِهَا', t: 'ahlihā', e: 'their owners', q: 1 },
      CLOSE,
    ],
    [
      { a: 'وَقَبْلَ', t: 'wa-qabla', e: 'and before' },
      { a: 'أَنَّ،', t: 'anna', e: 'anna' },
      NAHW, { g: ':' }, OPEN,
      { a: 'أَشْهِدُ', t: 'ushhidu', e: 'I call Allah to witness', q: 1 },
      { a: 'اللهَ', t: 'Allāha', e: '', q: 1 },
      { a: 'وَاشْهَدُوا', t: 'wa-shhadū', e: 'and bear witness', q: 1 },
      { a: 'أَنِّي', t: 'annī', e: 'that I', q: 1 },
      { a: 'بَرِيءٌ', t: 'barīʾun', e: 'am free', q: 1 },
      { a: 'مِمَّا', t: 'mimmā', e: 'of what', q: 1 },
      { a: 'تُشْرِكُونَ', t: 'tushrikūna', e: 'you associate', q: 1 },
      CLOSE,
    ],
    [
      { a: 'وَيَجُوزُ', t: 'wa-yajūzu', e: 'and it is allowed' },
      { a: 'سَمَاعًا،', t: 'samāʿan', e: 'by heard usage,' },
      NAHW, { g: ':' }, OPEN,
      { a: 'إِنَّ', t: 'inna', e: 'indeed', q: 1 },
      { a: 'عَادًا', t: 'ʿādan', e: 'ʿĀd', q: 1 },
      { a: 'كَفَرُوا', t: 'kafarū', e: 'disbelieved in', q: 1 },
      { a: 'رَبَّهُمْ', t: 'rabbahum', e: 'their Lord', q: 1 },
      CLOSE,
      { a: 'وَالْأَصْلُ', t: 'wal-aṣlu', e: 'though the base is' },
      { a: 'مَعَ', t: 'maʿa', e: 'with' },
      { a: 'الْبَاءِ،', t: 'al-bāʾi', e: 'the bāʾ' },
      NAHW, { g: ':' }, OPEN,
      { a: 'كَفَرُوا', t: 'kafarū', e: 'disbelieved', q: 1 },
      { a: 'بِرَبِّهِمْ', t: 'bi-rabbihim', e: 'in their Lord', q: 1 },
      CLOSE,
    ],
    [
      { a: 'وَيُسَمَّى', t: 'wa-yusammā', e: 'and the genitive is called,' },
      { a: 'الْمَجْرُورُ', t: 'al-majrūru', e: '' },
      { a: 'بَعْدَ', t: 'baʿda', e: 'after' },
      { a: 'حَذْفِ', t: 'ḥadhfi', e: 'dropping' },
      { a: 'الْجَارِّ', t: 'al-jārri', e: 'the preposition,' },
      { a: 'مَنْصُوبًا', t: 'manṣūban', e: 'accusative' },
      { a: 'بِنَزْعِ', t: 'bi-nazʿi', e: 'by removal of' },
      { a: 'الْخَافِضِ', t: 'al-khāfiḍi', e: 'the genitive-marker' },
    ],
  ] },
];
