/* ── al-Kubrā fī an-Naḥw — المقدمة · الباب الأول في الكلمة (pp. 6–9) ──
   Word tokens:  {a:Arabic, t:translit, e:English, n?:grammar note, q?:1 Qur'an word}
   Glyphs:       {g:'،'}  punctuation / braces / ellipsis (not interactive)
   Block types:  page | h1 | h2 | line | box | note | table                      */

const OPEN  = { g: '﴿', q: 1 };
const CLOSE = { g: '﴾', q: 1 };
const NAHW  = { a: 'نحو', t: 'naḥwa', e: 'for example', n: 'lit. "in the manner of"' };
const COMMA = { g: '،' };
const ELL   = { g: '…' };

const DATA = [
  { t: 'page', n: '٦' },

  /* ── opening of the Introduction ── */
  { t: 'line', w: [
    { a: 'وَفِيهَا', t: 'wa-fīhā', e: 'and in it (are)', n: 'i.e. in the Introduction' },
    { a: 'ثَلَاثَةُ', t: 'thalāthatu', e: 'three' },
    { a: 'أَبْوَابٍ', t: 'abwābin', e: 'chapters / gates' },
  ] },

  { t: 'h1', ar: 'الْبَابُ الْأَوَّلُ فِي الْكَلِمَةِ', en: 'The First Chapter — On the Word (al-kalimah)' },

  { t: 'line', w: [
    { a: 'وَهِيَ', t: 'wa-hiya', e: 'and it (is)', n: 'the kalimah' },
    { a: 'قَوْلٌ', t: 'qawlun', e: 'a meaningful utterance' },
    { a: 'مُفْرَدٌ،', t: 'mufradun', e: 'single / simple' },
  ] },

  { t: 'box', label: 'منها', lines: [
    [
      { a: 'اللَّفْظُ', t: 'al-lafẓu', e: 'the utterance (sound)' },
      { a: 'كُلُّ', t: 'kullu', e: 'is every' },
      { a: 'مَا', t: 'mā', e: 'thing that' },
      { a: 'خَرَجَ', t: 'kharaja', e: 'comes out' },
      { a: 'مِنْ', t: 'min', e: 'from' },
      { a: 'فَمِ', t: 'fami', e: 'the mouth of' },
      { a: 'الْإِنْسَانِ', t: 'al-insāni', e: 'the human' },
      { a: 'مِنْ', t: 'min', e: 'as' },
      { a: 'صَوْتٍ', t: 'ṣawtin', e: 'sound', n: 'whether meaningful or not' },
    ],
    [
      { a: 'القَوْلُ', t: 'al-qawlu', e: 'the meaningful utterance' },
      { a: 'لَفْظٌ', t: 'lafẓun', e: 'is an utterance' },
      { a: 'دَالٌّ', t: 'dāllun', e: 'denoting' },
      { a: 'عَلَى', t: 'ʿalā', e: 'a' },
      { a: 'مَعْنًى', t: 'maʿnan', e: 'meaning' },
    ],
  ] },

  { t: 'box', label: 'منها', lines: [
    [
      { a: 'الْمُفْرَدُ', t: 'al-mufradu', e: 'the single (word)' },
      { a: 'مَا', t: 'mā', e: 'is that which' },
      { a: 'لَا', t: 'lā', e: 'not' },
      { a: 'تَدُلُّ', t: 'tadullu', e: 'do denote' },
      { a: 'أَجْزَاؤُهُ', t: 'ajzāʾuhu', e: 'its parts' },
      { a: 'عَلَى', t: 'ʿalā', e: 'upon' },
      { a: 'مَعْنًى،', t: 'maʿnan', e: 'a meaning' },
      NAHW, { g: ':' },
      { a: 'رَجُلٌ،', t: 'rajulun', e: '“a man”' },
      { a: 'فَلَا', t: 'fa-lā', e: 'for not' },
      { a: 'تَدُلُّ', t: 'tadullu', e: 'does denote' },
      { a: 'الرَّاءُ', t: 'ar-rāʾu', e: 'the [letter] rāʾ' },
      { a: 'أَوِ', t: 'awi', e: 'or' },
      { a: 'الْجِيمُ', t: 'al-jīmu', e: 'the jīm' },
      { a: 'أَوِ', t: 'awi', e: 'or' },
      { a: 'اللَّامُ', t: 'al-lāmu', e: 'the lām' },
      { a: 'عَلَى', t: 'ʿalā', e: 'upon' },
      { a: 'مَعْنًى', t: 'maʿnan', e: 'a meaning' },
    ],
  ] },

  { t: 'box', label: 'منها', lines: [
    [
      { a: 'الْمُرَكَّبُ', t: 'al-murakkabu', e: 'the compound (word)' },
      { a: 'مَا', t: 'mā', e: 'is that which' },
      { a: 'تَدُلُّ', t: 'tadullu', e: 'do denote' },
      { a: 'أَجْزَاؤُهُ', t: 'ajzāʾuhu', e: 'its parts' },
      { a: 'عَلَى', t: 'ʿalā', e: 'upon' },
      { a: 'مَعْنًى،', t: 'maʿnan', e: 'a meaning' },
      NAHW, { g: ':' },
      { a: 'كِتَابُ', t: 'kitābu', e: '“the book of”' },
      { a: 'الْوَلَدِ،', t: 'al-waladi', e: 'the child' },
      { a: 'فَإِنَّ', t: 'fa-inna', e: 'for indeed' },
      { a: 'كِتَابَ', t: 'kitāba', e: '“book”' },
      { a: 'يَدُلُّ', t: 'yadullu', e: 'denotes' },
      { a: 'عَلَى', t: 'ʿalā', e: 'upon' },
      { a: 'مَعْنًى،', t: 'maʿnan', e: 'a meaning' },
      { a: 'وَالْوَلَدَ', t: 'wal-walada', e: 'and “the child”' },
      { a: 'يَدُلُّ', t: 'yadullu', e: 'denotes' },
      { a: 'عَلَى', t: 'ʿalā', e: 'upon' },
      { a: 'مَعْنًى', t: 'maʿnan', e: 'a meaning' },
    ],
  ] },

  { t: 'line', w: [
    { a: 'وَهِيَ', t: 'wa-hiya', e: 'and it (the word) is' },
    { a: 'ثَلَاثَةُ', t: 'thalāthatu', e: 'three' },
    { a: 'أَقْسَامٍ:', t: 'aqsāmin', e: 'divisions' },
  ] },

  /* ── 1. al-Ism ── */
  { t: 'h2', c: 'green', ar: 'الْقِسْمُ الْأَوَّلُ: الِاسْمُ', en: 'The First Division — The Noun (al-ism)' },

  { t: 'line', w: [
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
    { a: 'مَا', t: 'mā', e: 'that which' },
    { a: 'دَلَّ', t: 'dalla', e: 'denotes' },
    { a: 'عَلَى', t: 'ʿalā', e: 'upon' },
    { a: 'مَعْنًى', t: 'maʿnan', e: 'a meaning' },
    { a: 'فِي', t: 'fī', e: 'in' },
    { a: 'نَفْسِهِ', t: 'nafsihi', e: 'itself' },
    { a: 'غَيْرِ', t: 'ghayri', e: 'not' },
    { a: 'مُقْتَرِنٍ', t: 'muqtarinin', e: 'coupled' },
    { a: 'بِزَمَانٍ،', t: 'bi-zamānin', e: 'with time', n: 'a meaning independent of any tense' },
  ] },

  { t: 'box', label: 'علامات الاسم العربي', labelEn: 'Signs of the Arabic noun', lines: [
    [
      { a: 'يُعْرَفُ', t: 'yuʿrafu', e: 'is recognized' },
      { a: 'الِاسْمُ', t: 'al-ismu', e: 'the noun' },
      ELL,
    ],
    [
      { a: 'بِأَنْ', t: 'bi-an', e: 'by it' },
      { a: 'يَكُونَ', t: 'yakūna', e: 'being' },
      { a: 'مَجْرُورًا،', t: 'majrūran', e: 'genitive (majrūr)', n: 'only nouns take the genitive case' },
      NAHW, { g: ':' }, OPEN,
      { a: 'بِسْمِ', t: 'bismi', e: 'In the name of', q: 1 },
      { a: 'اللهِ', t: 'Allāhi', e: 'Allah', q: 1 },
      CLOSE,
    ],
    [
      { a: 'وَبِأَلْ', t: 'wa-bi-al', e: 'and by “al-”' },
      { a: 'لِلتَّعْرِيفِ،', t: 'lit-taʿrīfi', e: 'for definiteness' },
      NAHW, { g: ':' }, OPEN,
      { a: 'الرَّحْمٰنِ', t: 'ar-Raḥmāni', e: 'the Most Gracious', q: 1 },
      { a: 'الرَّحِيمِ', t: 'ar-Raḥīmi', e: 'the Most Merciful', q: 1 },
      CLOSE,
    ],
    [
      { a: 'وَبِالتَّنْوِينِ،', t: 'wa-bit-tanwīni', e: 'and by nunation (tanwīn)' },
      NAHW, { g: ':' }, OPEN,
      { a: 'هُدًى', t: 'hudan', e: 'a guidance', q: 1 },
      { a: 'لِلْمُتَّقِينَ', t: 'lil-muttaqīna', e: 'for the God-conscious', q: 1 },
      CLOSE,
    ],
    [
      { a: 'وَبِأَنْ', t: 'wa-bi-an', e: 'and by it' },
      { a: 'يَكُونَ', t: 'yakūna', e: 'being' },
      { a: 'مُسْنَدًا', t: 'musnadan', e: 'predicated' },
      { a: 'إِلَيْهِ،', t: 'ilayhi', e: 'to it', n: 'musnad ilayhi = the subject of predication' },
      NAHW, { g: ':' }, OPEN,
      { a: 'إِنَّ', t: 'inna', e: 'Indeed', q: 1 },
      { a: 'إِبْرَاهِيمَ', t: 'Ibrāhīma', e: 'Ibrāhīm', q: 1 },
      { a: 'لَحَلِيمٌ', t: 'la-ḥalīmun', e: 'was forbearing', q: 1 },
      { a: 'أَوَّاهٌ', t: 'awwāhun', e: 'compassionate', q: 1 },
      { a: 'مُنِيبٌ', t: 'munībun', e: 'oft-returning', q: 1 },
      CLOSE,
    ],
    [
      { a: 'وَبِأَنْ', t: 'wa-bi-an', e: 'and by it' },
      { a: 'يَكُونَ', t: 'yakūna', e: 'being' },
      { a: 'مُنَادًى،', t: 'munādan', e: 'a vocative (one called)' },
      NAHW, { g: ':' }, OPEN,
      { a: 'يَٰنُوحُ', t: 'yā Nūḥu', e: 'O Nūḥ!', q: 1 },
      CLOSE,
    ],
    [
      { a: 'وَبِأَنْ', t: 'wa-bi-an', e: 'and by it' },
      { a: 'يَكُونَ', t: 'yakūna', e: 'being' },
      { a: 'مُضَافًا،', t: 'muḍāfan', e: 'a possessor (muḍāf)', n: 'first term of a genitive construction' },
      NAHW, { g: ':' }, OPEN,
      { a: 'رَبِّ', t: 'rabbi', e: 'Lord of', q: 1 },
      { a: 'الْعَالَمِينَ', t: 'al-ʿālamīna', e: 'the worlds', q: 1 },
      CLOSE,
    ],
  ] },

  { t: 'box', label: 'منها', lines: [
    [
      { a: 'الْفِعْلُ', t: 'al-fiʿlu', e: 'the verb' },
      { a: 'وَالْحَرْفُ', t: 'wal-ḥarfu', e: 'and the particle' },
      { a: 'لَا', t: 'lā', e: 'do not' },
      { a: 'يَكُونَانِ', t: 'yakūnāni', e: 'become' },
      { a: 'مَجْرُورَيْنِ،', t: 'majrūrayni', e: 'genitive (both)' },
      { a: 'وَإِنْ', t: 'wa-in', e: 'even if' },
      { a: 'دَخَلَ', t: 'dakhala', e: 'enters' },
      { a: 'عَلَيْهِمَا', t: 'ʿalayhimā', e: 'upon them' },
      { a: 'جَارٌّ،', t: 'jārrun', e: 'a preposition' },
      NAHW, { g: ':' }, OPEN,
      { a: 'لِيَكُونَ', t: 'li-yakūna', e: 'that he be', q: 1 },
      { a: 'لِلْعَالَمِينَ', t: 'lil-ʿālamīna', e: 'to the worlds', q: 1 },
      { a: 'نَذِيرًا', t: 'nadhīran', e: 'a warner', q: 1 },
      CLOSE,
      { a: 'وَنحو:', t: 'wa-naḥwa', e: 'and for example' }, OPEN,
      { a: 'وَاشْهَدْ', t: 'wa-shhad', e: 'and bear witness', q: 1 },
      { a: 'بِأَنَّا', t: 'bi-annā', e: 'that we', q: 1 },
      { a: 'مُسْلِمُونَ', t: 'muslimūna', e: 'are Muslims', q: 1 },
      CLOSE,
    ],
  ] },

  { t: 'box', label: 'منها', lines: [
    [
      { a: 'قَدْ', t: 'qad', e: 'sometimes' },
      { a: 'تَدْخُلُ', t: 'tadkhulu', e: 'enter' },
      { a: 'أَحْرُفُ', t: 'aḥrufu', e: 'the particles of' },
      { a: 'النِّدَاءِ', t: 'an-nidāʾi', e: 'calling (vocative)' },
      { a: 'عَلَى', t: 'ʿalā', e: 'upon' },
      { a: 'غَيْرِ', t: 'ghayri', e: 'other than' },
      { a: 'الْمُنَادَى،', t: 'al-munādā', e: 'the one called' },
      NAHW, { g: ':' }, OPEN,
      { a: 'يَٰلَيْتَ', t: 'yā-layta', e: 'O would that', q: 1 },
      { a: 'قَوْمِي', t: 'qawmī', e: 'my people', q: 1 },
      { a: 'يَعْلَمُونَ', t: 'yaʿlamūna', e: 'knew', q: 1 },
      CLOSE,
    ],
  ] },

  { t: 'note', n: '١', ar: 'قَدْ تُطْلَقُ كَلِمَةُ «مُفْرَدٍ» عَلَى الْمُوَحَّدِ.',
    en: 'The term mufrad is sometimes used for the singular (one in number, vs. dual/plural) — a sense distinct from mufrad meaning “a single, non-compound word.”' },
  { t: 'note', n: '٢', ar: 'الْمُرَكَّبُ تَرْكِيبَ الْمَزْجِ مُفْرَدٌ حَيْثُ لَا تَدُلُّ أَجْزَاؤُهُ عَلَى مَعْنًى، وَإِنْ كَانَتْ أَجْزَاؤُهُ تَدُلُّ عَلَى مَعْنًى فِي أَصْلِهِ، نحو: بَعْلَبَكَّ.',
    en: 'A mixture-compound (tarkīb al-mazj) counts as “single,” since its parts no longer denote a meaning — even if they did in the original — e.g. Baʿlabakk (Baʿl + Bakk).' },
  { t: 'note', n: '', ar: 'فائدة: الْمُرَكَّبُ تَرْكِيبَ الْعَدَدِ قِسْمَانِ: الْأَوَّلُ أَحَدَ عَشَرَ إِلَى تِسْعَةَ عَشَرَ فَهُوَ مُرَكَّبٌ تَرْكِيبَ الْمَزْجِ، الثَّانِي أَحَدٌ وَعِشْرُونَ وَأَخَوَاتُهَا فَهُوَ مُرَكَّبٌ تَرْكِيبَ الْعَطْفِ.',
    en: 'Number-compounds are two kinds: (1) eleven–nineteen, a mixture-compound; (2) twenty-one and its sisters, a conjunction-compound (tarkīb al-ʿaṭf).' },

  /* ── kinds of noun: simple vs interpreted ── */
  { t: 'page', n: '٧' },

  { t: 'h2', c: 'blue', ar: 'أَضْرُبُ الِاسْمِ بِاعْتِبَارِ إِفْرَادِهِ وَتَرْكِيبِهِ', en: 'Kinds of noun — by it being simple or compound' },

  { t: 'line', w: [
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
    { a: 'ضَرْبَانِ،', t: 'ḍarbāni', e: 'two kinds' },
  ] },

  { t: 'h2', c: 'plain', ar: 'الضَّرْبُ الْأَوَّلُ: الِاسْمُ الصَّرِيحُ', en: 'First kind — the explicit noun (ṣarīḥ)' },
  { t: 'line', w: [
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
    { a: 'الِاسْمُ', t: 'al-ismu', e: 'the noun' },
    { a: 'وَحْدَهُ،', t: 'waḥdahu', e: 'on its own' },
    NAHW, { g: ':' },
    { a: 'الصَّوْمُ', t: 'aṣ-ṣawmu', e: '“fasting”' },
  ] },

  { t: 'h2', c: 'plain', ar: 'الضَّرْبُ الثَّانِي: الِاسْمُ الْمُؤَوَّلُ', en: 'Second kind — the interpreted noun (muʾawwal)' },
  { t: 'line', w: [
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
    { a: 'حَرْفُ', t: 'ḥarfu', e: 'a particle of' },
    { a: 'مَصْدَرٍ', t: 'maṣdarin', e: 'verbal-noun', n: 'maṣdarī particle, e.g. an, anna' },
    { a: 'مَعَ', t: 'maʿa', e: 'together with' },
    { a: 'الْجُمْلَةِ', t: 'al-jumlati', e: 'the clause' },
    { a: 'بَعْدَهُ،', t: 'baʿdahu', e: 'after it' },
    NAHW, { g: ':' }, OPEN,
    { a: 'وَأَنْ', t: 'wa-an', e: 'and that', q: 1 },
    { a: 'تَصُومُوا', t: 'taṣūmū', e: 'you fast', q: 1 },
    { a: 'خَيْرٌ', t: 'khayrun', e: 'is better', q: 1 },
    CLOSE,
    { a: '،', g: '،' },
  ] },

  { t: 'note', n: '١', ar: 'أَمْ حَرْفُ تَعْرِيفٍ عِنْدَ أَهْلِ حِمْيَرَ مِنْ أَهْلِ الْيَمَنِ، وَمِنْهُ قَوْلُ النَّبِيِّ ﷺ: «لَيْسَ مِنِ امْبِرِّ امْصِيَامُ فِي امْسَفَرِ».',
    en: '“Am-” is a definite article among the Ḥimyar of Yemen; from it is the Prophet’s ﷺ saying: “It is not righteousness (am-birr) to fast (am-ṣiyām) while travelling (am-safar)” — am- replacing al-.' },
  { t: 'note', n: '', ar: 'عِنْدَ سِيبَوَيْهِ (١٨٠هـ) حَرْفُ التَّعْرِيفِ هِيَ اللَّامُ وَحْدَهَا، وَزِيدَتْ عَلَيْهَا هَمْزَةُ الْوَصْلِ لِتَعَذُّرِ الِابْتِدَاءِ بِالسَّاكِنِ. وَعِنْدَ الْخَلِيلِ (١٧٠هـ) الْأَلِفُ وَاللَّامُ مَعًا. وَعِنْدَ الْمُبَرِّدِ (٢٨٥هـ) الْهَمْزَةُ الْمَفْتُوحَةُ وَحْدَهَا، وَاللَّامُ زِيدَتْ لِلْفَرْقِ بَيْنَهَا وَبَيْنَ هَمْزَةِ الِاسْتِفْهَامِ.',
    en: 'For Sībawayh (d.180) the article is the lām alone (the hamza of connection was added only because one cannot begin on a vowelless letter). For al-Khalīl (d.170) it is alif+lām together. For al-Mubarrad (d.285) it is the fatḥa-hamza alone, the lām being added to distinguish it from the interrogative hamza.' },
  { t: 'note', n: '٢', ar: 'الْمُرَادُ بِالتَّنْوِينِ غَيْرُ تَنْوِينِ التَّرَنُّمِ، وَهُوَ مَا يَلْحَقُ آخِرَ قَوَافِي الشِّعْرِ.',
    en: 'The tanwīn meant here is not the tanwīn of trilling (tarannum) that attaches to the ends of the rhymes of poetry.' },
  { t: 'note', n: '', ar: 'فائدة: الْمَجْرُورُ هُوَ الِاسْمُ الْمُؤَوَّلُ أَيْضًا، دُونَ الْفِعْلِ وَالْحَرْفِ وَحْدَهُمَا.',
    en: 'What takes the genitive includes the interpreted noun as well — not the verb or the bare particle on their own.' },
  { t: 'note', n: '', ar: 'فائدة: «يا» حَرْفُ تَنْبِيهٍ، أَوْ حَرْفُ نِدَاءٍ وَالْمُنَادَى مَحْذُوفٌ، تَقْدِيرُهُ: يَا هَؤُلَاءِ لَيْتَنِي.',
    en: '“Yā” is a particle of alerting, or a vocative particle with the called-one omitted, implicitly: “O you people, would that I…”.' },

  /* ── kinds of noun by meaning ── */
  { t: 'page', n: '٨' },

  { t: 'h2', c: 'blue', ar: 'أَضْرُبُ الِاسْمِ بِاعْتِبَارِ مَعْنَاهُ', en: 'Kinds of noun — by its meaning' },
  { t: 'line', w: [
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
    { a: 'ضَرْبَانِ،', t: 'ḍarbāni', e: 'two kinds' },
  ] },

  { t: 'h2', c: 'plain', ar: 'الضَّرْبُ الْأَوَّلُ: الْمَوْصُوفُ', en: 'First kind — the substantive (mawṣūf)' },
  { t: 'line', w: [
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
    { a: 'مَا', t: 'mā', e: 'that which' },
    { a: 'دَلَّ', t: 'dalla', e: 'denotes' },
    { a: 'عَلَى', t: 'ʿalā', e: 'upon' },
    { a: 'ذَاتٍ', t: 'dhātin', e: 'an entity' },
    { a: 'تَحْتَمِلُ', t: 'taḥtamilu', e: 'that can bear' },
    { a: 'الصِّفَةَ،', t: 'aṣ-ṣifata', e: 'the attribute' },
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
    { a: 'اثْنَانِ', t: 'ithnāni', e: 'two' },
  ] },
  { t: 'line', w: [
    { a: 'الْأَوَّلُ', t: 'al-awwalu', e: 'the first' },
    { a: 'اسْمُ', t: 'ismu', e: 'a noun of' },
    { a: 'عَيْنٍ،', t: 'ʿaynin', e: 'concrete thing', n: 'ism ʿayn = a concrete noun' },
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
    { a: 'مَا', t: 'mā', e: 'that which' },
    { a: 'دَلَّ', t: 'dalla', e: 'denotes' },
    { a: 'عَلَى', t: 'ʿalā', e: 'upon' },
    { a: 'مَا', t: 'mā', e: 'what' },
    { a: 'يَقُومُ', t: 'yaqūmu', e: 'subsists' },
    { a: 'بِذَاتِهِ،', t: 'bi-dhātihi', e: 'by itself' },
    NAHW, { g: ':' },
    { a: 'رَجُلٌ', t: 'rajulun', e: '“a man”' },
  ] },
  { t: 'line', w: [
    { a: 'الثَّانِي', t: 'ath-thānī', e: 'the second' },
    { a: 'اسْمُ', t: 'ismu', e: 'a noun of' },
    { a: 'مَعْنًى،', t: 'maʿnan', e: 'abstract meaning', n: 'ism maʿnā = an abstract noun' },
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
    { a: 'مَا', t: 'mā', e: 'that which' },
    { a: 'دَلَّ', t: 'dalla', e: 'denotes' },
    { a: 'عَلَى', t: 'ʿalā', e: 'upon' },
    { a: 'مَا', t: 'mā', e: 'what' },
    { a: 'لَا', t: 'lā', e: 'does not' },
    { a: 'يَقُومُ', t: 'yaqūmu', e: 'subsist' },
    { a: 'بِذَاتِهِ،', t: 'bi-dhātihi', e: 'by itself' },
    { a: 'بَلْ', t: 'bal', e: 'rather' },
    { a: 'يَقُومُ', t: 'yaqūmu', e: 'subsists' },
    { a: 'بِغَيْرِهِ،', t: 'bi-ghayrihi', e: 'through another' },
    NAHW, { g: ':' },
    { a: 'عِلْمٌ', t: 'ʿilmun', e: '“knowledge”' },
  ] },

  { t: 'h2', c: 'plain', ar: 'الضَّرْبُ الثَّانِي: الصِّفَةُ', en: 'Second kind — the attribute (ṣifah)' },
  { t: 'line', w: [
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
    { a: 'مَا', t: 'mā', e: 'that which' },
    { a: 'دَلَّ', t: 'dalla', e: 'denotes' },
    { a: 'عَلَى', t: 'ʿalā', e: 'upon' },
    { a: 'وَصْفٍ', t: 'waṣfin', e: 'a quality' },
    { a: 'مَوْصُوفٍ،', t: 'mawṣūfin', e: 'of something described' },
    NAHW, { g: ':' },
    { a: 'صَالِحٌ', t: 'ṣāliḥun', e: '“righteous”' },
  ] },

  /* ── 2. al-Fiʿl ── */
  { t: 'h2', c: 'green', ar: 'الْقِسْمُ الثَّانِي: الْفِعْلُ', en: 'The Second Division — The Verb (al-fiʿl)' },
  { t: 'line', w: [
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
    { a: 'مَا', t: 'mā', e: 'that which' },
    { a: 'دَلَّ', t: 'dalla', e: 'denotes' },
    { a: 'عَلَى', t: 'ʿalā', e: 'upon' },
    { a: 'مَعْنًى', t: 'maʿnan', e: 'a meaning' },
    { a: 'فِي', t: 'fī', e: 'in' },
    { a: 'نَفْسِهِ', t: 'nafsihi', e: 'itself' },
    { a: 'مُقْتَرِنٍ', t: 'muqtarinin', e: 'coupled' },
    { a: 'بِزَمَانٍ،', t: 'bi-zamānin', e: 'with time' },
    NAHW, { g: ':' },
    { a: 'عَبَدَ', t: 'ʿabada', e: '“he worshipped”', n: 'past tense (māḍī)' },
    { a: 'وَيَعْبُدُ', t: 'wa-yaʿbudu', e: '“and he worships”', n: 'present (muḍāriʿ)' },
    { a: 'وَاعْبُدْ', t: 'wa-ʿbud', e: '“and worship!”', n: 'command (amr)' },
  ] },

  { t: 'table', head: ['الِاسْمُ الْمَوْصُوفُ، اسْمُ الذَّاتِ', 'اسْمُ الصِّفَةِ'],
    sub: ['إِسْمُ عَيْنٍ', 'إِسْمُ مَعْنًى', ''],
    rows: [['رَجُلٌ', 'عِلْمٌ', 'عَالِمٌ']],
    caption: 'The substantive (ism al-dhāt) splits into concrete (ism ʿayn) and abstract (ism maʿnā); facing it is the attribute (ism al-ṣifah).' },
  { t: 'note', n: '١', ar: 'يَشْتَمِلُ الْفِعْلُ عَلَى ثَلَاثَةِ مَعَانٍ: الْأَوَّلُ الْحَدَثُ، وَهُوَ مَعْنَى الْمَصْدَرِ. الثَّانِي الزَّمَانُ. الثَّالِثُ الْفَاعِلُ. فَقَوْلُنَا «جَلَسَ» يَدُلُّ عَلَى مَعْنَى الْجُلُوسِ، وَوُقُوعِهِ فِي الْمَاضِي، وَالْفَاعِلِ.',
    en: 'The verb comprises three meanings: (1) the event (ḥadath) — the sense of the verbal noun; (2) time; (3) the doer. So “jalasa” denotes the meaning of sitting, its occurring in the past, and the doer.' },
  { t: 'note', n: '', ar: 'فائدة: الْفِعْلُ يَتَكَوَّنُ مِنْ مَادَّةٍ وَهَيْئَةٍ. فَمَادَّةُ «نَصَرَ» النُّونُ وَالصَّادُ وَالرَّاءُ، وَهَيْئَتُهُ كَوْنُهُ عَلَى وَزْنِ فَعَلَ. فَالْمَادَّةُ تَدُلُّ عَلَى الْحَدَثِ (النَّصْرِ)، وَالْهَيْئَةُ تَدُلُّ عَلَى وُقُوعِهِ فِي الْمَاضِي. فَمِنَ الْأَسْمَاءِ مَا دَلَّ عَلَى الزَّمَانِ بِمَادَّتِهِ لَا بِهَيْئَتِهِ، نحو أَمْسِ وَالْآنَ وَغَدًا.',
    en: 'The verb is made of a root-material (mādda) and a pattern (hayʾa). The mādda of naṣara is n-ṣ-r; its hayʾa is the pattern faʿala. The mādda denotes the event (naṣr = help), the hayʾa denotes that it occurred in the past. Some nouns indicate time by their material, not their pattern — e.g. ams (yesterday), al-ān (now), ghadan (tomorrow).' },

  /* ── signs of the verb ── */
  { t: 'page', n: '٩' },

  { t: 'box', label: 'علامات الفعل', labelEn: 'Signs of the verb', lines: [
    [
      { a: 'وَمِنْ', t: 'wa-min', e: 'and among' },
      { a: 'عَلَامَاتِ', t: 'ʿalāmāti', e: 'the signs of' },
      { a: 'الْفِعْلِ', t: 'al-fiʿli', e: 'the verb' },
      { a: 'الْعَامَّةِ', t: 'al-ʿāmmati', e: 'the general' },
      ELL,
    ],
    [
      { a: 'التَّصْرِيفُ', t: 'at-taṣrīfu', e: 'conjugation' },
      { a: 'إِلَى', t: 'ilā', e: 'into' },
      { a: 'الْمَاضِي', t: 'al-māḍī', e: 'the past' },
      { a: 'وَالْمُضَارِعِ،', t: 'wal-muḍāriʿi', e: 'and the present' },
      { a: 'وَالْأَمْرِ', t: 'wal-amri', e: 'and the command' },
      { a: 'وَالنَّهْيِ،', t: 'wan-nahyi', e: 'and the prohibition' },
    ],
    [
      { a: 'وَاتِّصَالُ', t: 'wa-ttiṣālu', e: 'and the attaching of' },
      { a: 'الضَّمَائِرِ', t: 'aḍ-ḍamāʾiri', e: 'the pronouns' },
      { a: 'الْبَارِزَةِ', t: 'al-bārizati', e: 'overt' },
      { a: 'الْمَرْفُوعَةِ،', t: 'al-marfūʿati', e: 'nominative (subject)' },
      NAHW, { g: ':' },
      { a: 'آمَنْتُ،', t: 'āmantu', e: '“I believed”' },
      { a: 'وَآمِنُوا', t: 'wa-āminū', e: '“and believe!”' },
    ],
    [
      { a: 'وَمِنْ', t: 'wa-min', e: 'and among' },
      { a: 'عَلَامَتِهِ', t: 'ʿalāmatihi', e: 'its signs' },
      { a: 'الْخَاصَّةِ', t: 'al-khāṣṣati', e: 'special' },
      { a: 'بِالْمَاضِي', t: 'bil-māḍī', e: 'to the past' },
      ELL,
    ],
    [
      { a: 'اتِّصَالُ', t: 'ittiṣālu', e: 'the attaching of' },
      { a: 'تَاءِ', t: 'tāʾi', e: 'the tāʾ of' },
      { a: 'التَّأْنِيثِ', t: 'at-taʾnīthi', e: 'feminization' },
      { a: 'السَّاكِنَةِ،', t: 'as-sākinati', e: 'quiescent (vowelless)' },
      NAHW, { g: ':' }, OPEN,
      { a: 'آمَنَتْ', t: 'āmanat', e: '“she believed”', q: 1 },
      CLOSE,
    ],
    [
      { a: 'وَمِنْ', t: 'wa-min', e: 'and among' },
      { a: 'عَلَامَتِهِ', t: 'ʿalāmatihi', e: 'its signs' },
      { a: 'الْخَاصَّةِ', t: 'al-khāṣṣati', e: 'special' },
      { a: 'بِالْمُضَارِعِ', t: 'bil-muḍāriʿi', e: 'to the present' },
      ELL,
    ],
    [
      { a: 'لَمْ،', t: 'lam', e: '“lam” (did not)' },
      NAHW, { g: ':' }, OPEN,
      { a: 'لَمْ', t: 'lam', e: 'not', q: 1 },
      { a: 'يَلِدْ', t: 'yalid', e: 'He begets', q: 1 },
      { a: 'وَلَمْ', t: 'wa-lam', e: 'and not', q: 1 },
      { a: 'يُولَدْ', t: 'yūlad', e: 'is He begotten', q: 1 },
      CLOSE,
    ],
    [
      { a: 'وَلَنْ،', t: 'wa-lan', e: 'and “lan” (never)' },
      NAHW, { g: ':' }, OPEN,
      { a: 'لَنْ', t: 'lan', e: 'never', q: 1 },
      { a: 'يُصِيبَنَا', t: 'yuṣībanā', e: 'will befall us', q: 1 },
      { a: 'إِلَّا', t: 'illā', e: 'except', q: 1 },
      { a: 'مَا', t: 'mā', e: 'what', q: 1 },
      { a: 'كَتَبَ', t: 'kataba', e: 'has decreed', q: 1 },
      { a: 'اللهُ', t: 'Allāhu', e: 'Allah', q: 1 },
      { a: 'لَنَا', t: 'lanā', e: 'for us', q: 1 },
      CLOSE,
    ],
    [
      { a: 'وَالسِّينُ،', t: 'was-sīnu', e: 'and the prefix sīn' },
      NAHW, { g: ':' }, OPEN,
      { a: 'سَيَرْحَمُهُمُ', t: 'sa-yarḥamuhumu', e: 'He will have mercy on them', q: 1 },
      { a: 'اللهُ', t: 'Allāhu', e: 'Allah', q: 1 },
      CLOSE,
    ],
    [
      { a: 'وَسَوْفَ،', t: 'wa-sawfa', e: 'and “sawfa” (shall)' },
      NAHW, { g: ':' }, OPEN,
      { a: 'سَوْفَ', t: 'sawfa', e: 'I shall soon', q: 1 },
      { a: 'أَسْتَغْفِرُ', t: 'astaghfiru', e: 'ask forgiveness', q: 1 },
      { a: 'لَكُمْ', t: 'lakum', e: 'for you', q: 1 },
      { a: 'رَبِّي', t: 'rabbī', e: 'from my Lord', q: 1 },
      CLOSE,
    ],
    [
      { a: 'وَافْتِتَاحُهُ', t: 'wa-ftitāḥuhu', e: 'and its beginning' },
      { a: 'بِحَرْفٍ', t: 'bi-ḥarfin', e: 'with a letter' },
      { a: 'مِنْ', t: 'min', e: 'from' },
      { a: 'حُرُوفِ', t: 'ḥurūfi', e: 'the letters of' },
      { a: 'الْمُضَارَعَةِ', t: 'al-muḍāraʿati', e: 'the present-tense prefixes' },
      { a: 'وَهِيَ', t: 'wa-hiya', e: 'which are' },
      { a: 'نَأْتِي،', t: 'naʾtī', e: 'n-’-t-y', n: 'mnemonic for ن أ ت ي' },
      NAHW, { g: ':' }, OPEN,
      { a: 'وَاللهُ', t: 'wallāhu', e: 'And Allah', q: 1 },
      { a: 'يُحْيِي', t: 'yuḥyī', e: 'gives life', q: 1 },
      { a: 'وَيُمِيتُ', t: 'wa-yumītu', e: 'and causes death', q: 1 },
      CLOSE,
    ],
    [
      { a: 'وَنُونَا', t: 'wa-nūnā', e: 'and the two nūns of' },
      { a: 'التَّأْكِيدِ،', t: 'at-taʾkīdi', e: 'emphasis' },
      NAHW, { g: ':' }, OPEN,
      { a: 'لَيُسْجَنَنَّ', t: 'la-yusjananna', e: 'he shall surely be imprisoned', q: 1 },
      { a: 'وَلَيَكُونًا', t: 'wa-la-yakūnan', e: 'and shall surely be', q: 1 },
      { a: 'مِنَ', t: 'mina', e: 'among', q: 1 },
      { a: 'الصَّاغِرِينَ', t: 'aṣ-ṣāghirīna', e: 'the debased', q: 1 },
      CLOSE,
    ],
    [
      { a: 'وَمِنْ', t: 'wa-min', e: 'and among' },
      { a: 'عَلَامَتِهِ', t: 'ʿalāmatihi', e: 'its signs' },
      { a: 'الْخَاصَّةِ', t: 'al-khāṣṣati', e: 'special' },
      { a: 'بِالْمَاضِي', t: 'bil-māḍī', e: 'to the past' },
      { a: 'وَالْمُضَارِعِ', t: 'wal-muḍāriʿi', e: 'and the present' },
      ELL,
    ],
    [
      { a: 'قَدْ،', t: 'qad', e: '“qad”' },
      NAHW, { g: ':' }, OPEN,
      { a: 'لَقَدْ', t: 'laqad', e: 'Certainly', q: 1 },
      { a: 'سَمِعَ', t: 'samiʿa', e: 'has heard', q: 1 },
      { a: 'اللهُ', t: 'Allāhu', e: 'Allah', q: 1 },
      CLOSE,
      { a: 'وَ', t: 'wa', e: 'and' }, OPEN,
      { a: 'قَدْ', t: 'qad', e: 'already', q: 1 },
      { a: 'يَعْلَمُ', t: 'yaʿlamu', e: 'knows', q: 1 },
      { a: 'اللهُ', t: 'Allāhu', e: 'Allah', q: 1 },
      CLOSE,
    ],
    [
      { a: 'وَمِنْ', t: 'wa-min', e: 'and among' },
      { a: 'عَلَامَتِهِ', t: 'ʿalāmatihi', e: 'its signs' },
      { a: 'الْخَاصَّةِ', t: 'al-khāṣṣati', e: 'special' },
      { a: 'بِالْأَمْرِ', t: 'bil-amri', e: 'to the command' },
      ELL,
    ],
    [
      { a: 'دَلَالَتُهُ', t: 'dalālatuhu', e: 'its denoting' },
      { a: 'عَلَى', t: 'ʿalā', e: 'upon' },
      { a: 'الطَّلَبِ', t: 'aṭ-ṭalabi', e: 'command / request' },
      { a: 'مَعَ', t: 'maʿa', e: 'along with' },
      { a: 'قَبُولِهِ', t: 'qabūlihi', e: 'its accepting' },
      { a: 'يَاءَ', t: 'yāʾa', e: 'the yāʾ of' },
      { a: 'الْمُخَاطَبَةِ،', t: 'al-mukhāṭabati', e: 'the female addressee' },
      NAHW, { g: ':' }, OPEN,
      { a: 'وَادْخُلِي', t: 'wa-dkhulī', e: 'and enter', q: 1 },
      { a: 'جَنَّتِي', t: 'jannatī', e: 'My garden', q: 1 },
      CLOSE,
    ],
  ] },

  /* ── 3. al-Ḥarf ── */
  { t: 'h2', c: 'green', ar: 'الْقِسْمُ الثَّالِثُ: الْحَرْفُ', en: 'The Third Division — The Particle (al-ḥarf)' },
  { t: 'line', w: [
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
    { a: 'مَا', t: 'mā', e: 'that which' },
    { a: 'دَلَّ', t: 'dalla', e: 'denotes' },
    { a: 'عَلَى', t: 'ʿalā', e: 'upon' },
    { a: 'مَعْنًى', t: 'maʿnan', e: 'a meaning' },
    { a: 'فِي', t: 'fī', e: 'in' },
    { a: 'غَيْرِهِ،', t: 'ghayrihi', e: 'something else', n: 'a meaning that appears only through another word' },
    NAHW, { g: ':' },
    { a: 'فِي', t: 'fī', e: '“in”' },
    { a: 'وَإِنَّ', t: 'wa-inna', e: '“and inna (indeed)”' },
  ] },

  { t: 'note', n: '١', ar: '«نِعْمَ» وَ«بِئْسَ» فِعْلَانِ عِنْدَ الْبَصْرِيِّينَ بِدَلِيلِ دُخُولِ التَّاءِ عَلَيْهِمَا، أَمَّا عِنْدَ أَهْلِ الْكُوفَةِ فَاسْمَانِ مَبْنِيَّانِ عَلَى الْفَتْحِ، لِدُخُولِ الْجَارِّ عَلَيْهِمَا فِي مِثْلِ قَوْلِهِمْ: نِعْمَ السَّيْرُ عَلَى بِئْسَ الْبَعِيرِ.',
    en: '“Niʿma” and “biʾsa” are verbs for the Basrans (the tāʾ attaches to them), but nouns built on fatḥa for the Kufans (a preposition can precede them, as in “what a fine march upon what a wretched camel”).' },
  { t: 'note', n: '٢', ar: 'فائدة: يَحْتَاجُ الْحَرْفُ لِتَدُلَّ عَلَى مَعْنَاهُ إِلَى غَيْرِهِ ...',
    en: 'The particle needs another word in order to convey its meaning…' },

  /* ── signs of the particle (continues onto p.10) ── */
  { t: 'page', n: '١٠' },

  { t: 'box', label: 'علامات الحرف', labelEn: 'Signs of the particle', lines: [
    [
      { a: 'يُعْرَفُ', t: 'yuʿrafu', e: 'is recognized' },
      { a: 'الْحَرْفُ', t: 'al-ḥarfu', e: 'the particle' },
      { a: 'بِأَلَّا', t: 'bi-allā', e: 'by there not' },
      { a: 'يُوجَدَ', t: 'yūjada', e: 'being found' },
      { a: 'فِيهِ', t: 'fīhi', e: 'in it' },
      { a: 'شَيْءٌ', t: 'shayʾun', e: 'anything' },
      { a: 'مِنْ', t: 'min', e: 'of' },
      { a: 'عَلَامَاتِ', t: 'ʿalāmāti', e: 'the signs of' },
      { a: 'الِاسْمِ', t: 'al-ismi', e: 'the noun' },
      { a: 'وَالْفِعْلِ،', t: 'wal-fiʿli', e: 'and the verb' },
      NAHW, { g: ':' },
      { a: 'هَلْ', t: 'hal', e: '“hal (is/has)”' },
      { a: 'وَبَلْ', t: 'wa-bal', e: 'and “bal (rather)”' },
    ],
  ] },

  { t: 'box', label: 'إطلاقات الحرف', labelEn: 'Senses of the word ḥarf', lines: [
    [
      { a: 'الْحَرْفُ', t: 'al-ḥarfu', e: 'the word ḥarf' },
      { a: 'يُطْلَقُ', t: 'yuṭlaqu', e: 'is applied' },
      { a: 'عَلَى', t: 'ʿalā', e: 'to' },
      ELL,
    ],
    [
      { a: 'حُرُوفُ', t: 'ḥurūfu', e: 'the letters of' },
      { a: 'الْمَبَانِي،', t: 'al-mabānī', e: 'spelling (ḥurūf al-mabānī)', n: 'the alphabet letters as building-blocks' },
      { a: 'وَهِيَ', t: 'wa-hiya', e: 'and they are' },
      { a: 'حُرُوفُ', t: 'ḥurūfu', e: 'the letters of' },
      { a: 'التَّهَجِّي،', t: 'at-tahajjī', e: 'the alphabet' },
      NAHW, { g: ':' },
      { a: 'فَاءٌ،', t: 'fāʾun', e: 'fāʾ' },
      { a: 'وَعَيْنٌ،', t: 'wa-ʿaynun', e: 'and ʿayn' },
      { a: 'وَلَامٌ', t: 'wa-lāmun', e: 'and lām' },
    ],
    [
      { a: 'وَحُرُوفُ', t: 'wa-ḥurūfu', e: 'and the letters of' },
      { a: 'الْمَعَانِي،', t: 'al-maʿānī', e: 'meaning (ḥurūf al-maʿānī)' },
      { a: 'هِيَ', t: 'hiya', e: 'are' },
      { a: 'مَا', t: 'mā', e: 'those that' },
      { a: 'تَدُلُّ', t: 'tadullu', e: 'denote' },
      { a: 'عَلَى', t: 'ʿalā', e: 'a' },
      { a: 'مَعْنًى،', t: 'maʿnan', e: 'meaning' },
      NAHW, { g: ':' },
      { a: 'فِي،', t: 'fī', e: '“fī (in)”' },
      { a: 'وَإِنَّ،', t: 'wa-inna', e: 'and “inna”' },
      { a: 'وَبَلْ،', t: 'wa-bal', e: 'and “bal”' },
      { a: 'وَلَا', t: 'wa-lā', e: 'and “lā”' },
    ],
  ] },

  { t: 'box', label: 'حرف المد وحرف اللين', labelEn: 'Letters of prolongation & softness', lines: [
    [
      { a: 'حَرْفُ', t: 'ḥarfu', e: 'a letter of' },
      { a: 'مَدٍّ', t: 'maddin', e: 'prolongation (madd)' },
      { a: 'حَرْفُ', t: 'ḥarfu', e: 'is a letter of' },
      { a: 'عِلَّةٍ', t: 'ʿillatin', e: 'weakness (ʿillah)' },
      { a: 'سَاكِنٌ', t: 'sākinun', e: 'quiescent' },
      { a: 'قَبْلَهُ', t: 'qablahu', e: 'with before it' },
      { a: 'حَرَكَةٌ', t: 'ḥarakatun', e: 'a vowel' },
      { a: 'تُنَاسِبُهُ،', t: 'tunāsibuhu', e: 'matching it', n: 'ū after ḍamma, ī after kasra, ā after fatḥa' },
      NAHW, { g: ':' }, OPEN,
      { a: 'وَكُونُوا', t: 'wa-kūnū', e: 'and be', q: 1 },
      { a: 'مَعَ', t: 'maʿa', e: 'with', q: 1 },
      { a: 'الصَّادِقِينَ', t: 'aṣ-ṣādiqīna', e: 'the truthful', q: 1 },
      CLOSE,
    ],
    [
      { a: 'حَرْفُ', t: 'ḥarfu', e: 'a letter of' },
      { a: 'لِينٍ', t: 'līnin', e: 'softness (līn)' },
      { a: 'حَرْفُ', t: 'ḥarfu', e: 'is a letter,' },
      { a: 'وَاوٍ', t: 'wāwin', e: 'a wāw' },
      { a: 'أَوْ', t: 'aw', e: 'or' },
      { a: 'يَاءٍ', t: 'yāʾin', e: 'yāʾ' },
      { a: 'سَاكِنٌ', t: 'sākinun', e: 'quiescent' },
      { a: 'قَبْلَهُ', t: 'qablahu', e: 'with before it' },
      { a: 'فَتْحَةٌ،', t: 'fatḥatun', e: 'a fatḥa' },
      NAHW, { g: ':' },
      { a: 'الخَيْرُ', t: 'al-khayru', e: '“the good”' },
      { a: 'فِي', t: 'fī', e: 'in' },
      { a: 'التَّوْبَةِ', t: 'at-tawbati', e: '“repentance”' },
    ],
  ] },
];
