/* ── al-Kubrā fī an-Naḥw — المقدمة · الباب الثاني في الجملة وشبه الجملة والكلام (pp. 10–16) ──
   Continues the Introduction. Reuses the token shapes + shared glyphs (OPEN/CLOSE/NAHW/ELL)
   declared in muqaddimah.js, which loads first.  Footnotes are intentionally omitted.        */

const DATA_BAB2 = [
  { t: 'page', n: '١٠' },

  { t: 'h1', ar: 'الْبَابُ الثَّانِي فِي الْجُمْلَةِ وَشِبْهِ الْجُمْلَةِ وَالْكَلَامِ',
    en: 'The Second Chapter — On the Sentence, the Quasi-Sentence & Speech' },

  { t: 'line', w: [
    { a: 'وَفِيهِ', t: 'wa-fīhi', e: 'and in it (are)' },
    { a: 'ثَلَاثَةُ', t: 'thalāthatu', e: 'three' },
    { a: 'فُصُولٍ', t: 'fuṣūlin', e: 'sections (fuṣūl)' },
  ] },

  /* ── Section 1: the Sentence ── */
  { t: 'h2', c: 'green', ar: 'الْفَصْلُ الْأَوَّلُ فِي الْجُمْلَةِ', en: 'First Section — On the Sentence (al-jumlah)' },
  { t: 'line', w: [
    { a: 'وَهِيَ', t: 'wa-hiya', e: 'and it is' },
    { a: 'مَا', t: 'mā', e: 'that which' },
    { a: 'اشْتَمَلَتْ', t: 'ishtamalat', e: 'comprises' },
    { a: 'عَلَى', t: 'ʿalā', e: 'a' },
    { a: 'مُسْنَدٍ', t: 'musnadin', e: 'predicate (musnad)' },
    { a: 'وَمُسْنَدٍ', t: 'wa-musnadin', e: 'and a subject' },
    { a: 'إِلَيْهِ', t: 'ilayhi', e: 'of predication (musnad ilayhi)' },
  ] },

  { t: 'box', label: 'أركان الجملة', labelEn: 'Pillars of the sentence', lines: [
    [
      { a: 'الْمُسْنَدُ', t: 'al-musnadu', e: 'the musnad' },
      { a: 'إِلَيْهِ', t: 'ilayhi', e: 'ilayhi' },
      { a: 'هُوَ', t: 'huwa', e: 'is' },
      { a: 'الْمُبْتَدَأُ', t: 'al-mubtadaʾu', e: 'the subject (mubtadaʾ)' },
      { a: 'أَوِ', t: 'awi', e: 'or' },
      { a: 'الْفَاعِلُ،', t: 'al-fāʿilu', e: 'the doer (fāʿil)' },
      { a: 'وَيُسَمَّى', t: 'wa-yusammā', e: 'and is called' },
      { a: 'مَحْكُومًا', t: 'maḥkūman', e: 'the thing judged' },
      { a: 'عَلَيْهِ', t: 'ʿalayhi', e: 'about (maḥkūm ʿalayhi)' },
    ],
    [
      { a: 'الْمُسْنَدُ', t: 'al-musnadu', e: 'the musnad' },
      { a: 'هُوَ', t: 'huwa', e: 'is' },
      { a: 'الْخَبَرُ', t: 'al-khabaru', e: 'the predicate (khabar)' },
      { a: 'أَوِ', t: 'awi', e: 'or' },
      { a: 'الْفِعْلُ،', t: 'al-fiʿlu', e: 'the verb' },
      { a: 'وَيُسَمَّى', t: 'wa-yusammā', e: 'and is called' },
      { a: 'مَحْكُومًا', t: 'maḥkūman', e: 'the thing judged' },
      { a: 'بِهِ', t: 'bihi', e: 'by (maḥkūm bihi)' },
    ],
    [
      { a: 'يُسَمَّى', t: 'yusammā', e: 'are called' },
      { a: 'الْمُسْنَدُ', t: 'al-musnadu', e: 'the musnad' },
      { a: 'إِلَيْهِ', t: 'ilayhi', e: 'ilayhi' },
      { a: 'وَالْمُسْنَدُ', t: 'wal-musnadu', e: 'and the musnad' },
      { a: 'عُمْدَةً،', t: 'ʿumdatan', e: 'the core (ʿumdah)' },
      { a: 'وَيُسَمَّى', t: 'wa-yusammā', e: 'and is called' },
      { a: 'مَا', t: 'mā', e: 'what' },
      { a: 'سِوَاهُمَا', t: 'siwāhumā', e: 'is other than them' },
      { a: 'فَضْلَةً', t: 'faḍlatan', e: 'surplus (faḍlah)' },
      { a: 'وَقَيْدًا', t: 'wa-qaydan', e: 'and restriction (qayd)' },
    ],
  ] },

  /* ── Issue 1: by form ── */
  { t: 'page', n: '١١' },
  { t: 'line', w: [
    { a: 'وَفِيهِ', t: 'wa-fīhi', e: 'and in it (are)' },
    { a: 'ثَلَاثُ', t: 'thalāthu', e: 'three' },
    { a: 'مَسَائِلَ', t: 'masāʾila', e: 'issues (masāʾil)' },
  ] },
  { t: 'h2', c: 'red', ar: 'الْمَسْأَلَةُ الْأُولَى: أَقْسَامُ الْجُمْلَةِ بِاعْتِبَارِ هَيْئَتِهَا',
    en: 'First Issue — Divisions of the sentence by its form (hayʾah)' },
  { t: 'line', w: [
    { a: 'وَهِيَ', t: 'wa-hiya', e: 'and it is' },
    { a: 'قِسْمَانِ', t: 'qismāni', e: 'two kinds' },
  ] },

  { t: 'h2', c: 'blue', ar: 'الْقِسْمُ الْأَوَّلُ: الْجُمْلَةُ الِاسْمِيَّةُ', en: 'First division — the nominal sentence (al-jumlah al-ismiyyah)' },
  { t: 'line', w: [
    { a: 'وَهِيَ', t: 'wa-hiya', e: 'and it is' },
    { a: 'مَا', t: 'mā', e: 'what' },
    { a: 'صَدَرَتْ', t: 'ṣadarat', e: 'begins' },
    { a: 'بِاسْمٍ،', t: 'bi-ismin', e: 'with a noun' },
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
    { a: 'ضَرْبَانِ', t: 'ḍarbāni', e: 'two kinds' },
  ] },

  { t: 'h2', c: 'plain', ar: 'الضَّرْبُ الْأَوَّلُ: الْجُمْلَةُ الِاسْمِيَّةُ غَيْرُ الْمَنْسُوخَةِ', en: 'First kind — the non-abrogated nominal sentence' },
  { t: 'line', w: [
    { a: 'وَهِيَ', t: 'wa-hiya', e: 'and it is' },
    { a: 'مَا', t: 'mā', e: 'that which' },
    { a: 'لَمْ', t: 'lam', e: 'not' },
    { a: 'يَدْخُلْ', t: 'yadkhul', e: 'has entered' },
    { a: 'عَلَيْهَا', t: 'ʿalayhā', e: 'upon it' },
    { a: 'نَاسِخٌ،', t: 'nāsikhun', e: 'an abrogator (nāsikh)', n: 'kāna, inna and their sisters' },
    NAHW, { g: ':' }, OPEN,
    { a: 'وَاللهُ', t: 'wallāhu', e: 'And Allah', q: 1 },
    { a: 'غَفُورٌ', t: 'ghafūrun', e: 'is Forgiving', q: 1 },
    { a: 'رَحِيمٌ', t: 'raḥīmun', e: 'Merciful', q: 1 },
    CLOSE,
  ] },

  { t: 'h2', c: 'plain', ar: 'الضَّرْبُ الثَّانِي: الْجُمْلَةُ الِاسْمِيَّةُ الْمَنْسُوخَةُ', en: 'Second kind — the abrogated nominal sentence' },
  { t: 'line', w: [
    { a: 'وَهِيَ', t: 'wa-hiya', e: 'and it is' },
    { a: 'مَا', t: 'mā', e: 'that which' },
    { a: 'دَخَلَ', t: 'dakhala', e: 'has entered' },
    { a: 'عَلَيْهَا', t: 'ʿalayhā', e: 'upon it' },
    { a: 'نَاسِخٌ،', t: 'nāsikhun', e: 'an abrogator' },
    NAHW, { g: ':' }, OPEN,
    { a: 'إِنَّ', t: 'inna', e: 'Indeed', q: 1 },
    { a: 'اللهَ', t: 'Allāha', e: 'Allah', q: 1 },
    { a: 'غَفُورٌ', t: 'ghafūrun', e: 'is Forgiving', q: 1 },
    { a: 'رَحِيمٌ', t: 'raḥīmun', e: 'Merciful', q: 1 },
    CLOSE,
  ] },

  { t: 'h2', c: 'blue', ar: 'الْقِسْمُ الثَّانِي: الْجُمْلَةُ الْفِعْلِيَّةُ', en: 'Second division — the verbal sentence (al-jumlah al-fiʿliyyah)' },
  { t: 'line', w: [
    { a: 'وَهِيَ', t: 'wa-hiya', e: 'and it is' },
    { a: 'مَا', t: 'mā', e: 'what' },
    { a: 'صَدَرَتْ', t: 'ṣadarat', e: 'begins' },
    { a: 'بِفِعْلٍ،', t: 'bi-fiʿlin', e: 'with a verb' },
    NAHW, { g: ':' }, OPEN,
    { a: 'وَخَلَقَ', t: 'wa-khalaqa', e: 'and He created', q: 1 },
    { a: 'كُلَّ', t: 'kulla', e: 'every', q: 1 },
    { a: 'شَيْءٍ', t: 'shayʾin', e: 'thing', q: 1 },
    CLOSE,
  ] },

  { t: 'table', head: ['عُمْدَةٌ', 'فَضْلَةٌ، قَيْدٌ'],
    sub: ['مُسْنَدٌ إِلَيْهِ<br>مَحْكُومٌ عَلَيْهِ', 'مُسْنَدٌ<br>مَحْكُومٌ بِهِ', ''],
    rows: [['مُبْتَدَأٌ، فَاعِلٌ', 'خَبَرٌ، فِعْلٌ', 'الْمَفَاعِيلُ الْخَمْسَةُ وَغَيْرُهَا']],
    caption: 'The core (ʿumdah) is the musnad ilayhi (mubtadaʾ/fāʿil) and the musnad (khabar/fiʿl); everything else — the five objects and so on — is surplus (faḍlah) or restriction (qayd).' },

  /* ── Issue 2: by meaning ── */
  { t: 'page', n: '١٢' },
  { t: 'h2', c: 'red', ar: 'الْمَسْأَلَةُ الثَّانِيَةُ: أَقْسَامُ الْجُمْلَةِ بِاعْتِبَارِ مَعْنَاهَا',
    en: 'Second Issue — Divisions of the sentence by its meaning' },
  { t: 'line', w: [
    { a: 'وَهِيَ', t: 'wa-hiya', e: 'and it is' },
    { a: 'قِسْمَانِ', t: 'qismāni', e: 'two kinds' },
  ] },

  { t: 'h2', c: 'blue', ar: 'الْقِسْمُ الْأَوَّلُ: الْجُمْلَةُ الْخَبَرِيَّةُ', en: 'First division — the declarative sentence (al-khabariyyah)' },
  { t: 'line', w: [
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
    { a: 'مَا', t: 'mā', e: 'that in which' },
    { a: 'يَكُونُ', t: 'yakūnu', e: 'can be' },
    { a: 'الْقَائِلُ', t: 'al-qāʾilu', e: 'the speaker' },
    { a: 'صَادِقًا', t: 'ṣādiqan', e: 'truthful' },
    { a: 'فِي', t: 'fī', e: 'in' },
    { a: 'كَلَامِهِ', t: 'kalāmihi', e: 'his speech' },
    { a: 'أَوْ', t: 'aw', e: 'or' },
    { a: 'كَاذِبًا،', t: 'kādhiban', e: 'lying' },
    NAHW, { g: ':' }, OPEN,
    { a: 'إِيَّاكَ', t: 'iyyāka', e: 'You alone', q: 1 },
    { a: 'نَعْبُدُ', t: 'naʿbudu', e: 'we worship', q: 1 },
    { a: 'وَإِيَّاكَ', t: 'wa-iyyāka', e: 'and You alone', q: 1 },
    { a: 'نَسْتَعِينُ', t: 'nastaʿīnu', e: 'we ask for help', q: 1 },
    CLOSE,
  ] },

  { t: 'h2', c: 'blue', ar: 'الْقِسْمُ الثَّانِي: الْجُمْلَةُ الْإِنْشَائِيَّةُ', en: 'Second division — the performative sentence (al-inshāʾiyyah)' },
  { t: 'line', w: [
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
    { a: 'مَا', t: 'mā', e: 'that in which' },
    { a: 'لَا', t: 'lā', e: 'not' },
    { a: 'يَكُونُ', t: 'yakūnu', e: 'is' },
    { a: 'الْقَائِلُ', t: 'al-qāʾilu', e: 'the speaker' },
    { a: 'صَادِقًا', t: 'ṣādiqan', e: 'truthful' },
    { a: 'فِي', t: 'fī', e: 'in' },
    { a: 'كَلَامِهِ', t: 'kalāmihi', e: 'his speech' },
    { a: 'أَوْ', t: 'aw', e: 'or' },
    { a: 'كَاذِبًا،', t: 'kādhiban', e: 'lying' },
    { a: 'وَهِيَ', t: 'wa-hiya', e: 'and they are' }, { g: ':' },
  ] },

  { t: 'line', w: [
    { a: 'الِاسْتِفْهَامُ،', t: 'al-istifhāmu', e: 'the interrogative' },
    NAHW, { g: ':' }, OPEN,
    { a: 'أَإِلَهٌ', t: 'a-ilāhun', e: 'Is there a god', q: 1 },
    { a: 'مَعَ', t: 'maʿa', e: 'with', q: 1 },
    { a: 'اللهِ', t: 'Allāhi', e: 'Allah', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'وَالتَّمَنِّي،', t: 'wat-tamannī', e: 'and wishing (tamannī)' },
    NAHW, { g: ':' }, OPEN,
    { a: 'يَا', t: 'yā', e: 'O', q: 1 },
    { a: 'لَيْتَ', t: 'layta', e: 'would that', q: 1 },
    { a: 'قَوْمِي', t: 'qawmī', e: 'my people', q: 1 },
    { a: 'يَعْلَمُونَ', t: 'yaʿlamūna', e: 'knew', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'وَالنِّدَاءُ،', t: 'wan-nidāʾu', e: 'and calling (nidāʾ)' },
    NAHW, { g: ':' }, OPEN,
    { a: 'يَا', t: 'yā', e: 'O', q: 1 },
    { a: 'أَيُّهَا', t: 'ayyuhā', e: 'you', q: 1 },
    { a: 'الرَّسُولُ', t: 'ar-rasūlu', e: 'Messenger', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'وَالتَّحْذِيرُ،', t: 'wat-taḥdhīru', e: 'and warning (taḥdhīr)' },
    NAHW, { g: ':' }, OPEN,
    { a: 'نَاقَةَ', t: 'nāqata', e: 'the she-camel of', q: 1 },
    { a: 'اللهِ', t: 'Allāhi', e: 'Allah', q: 1 },
    { a: 'وَسُقْيَاهَا', t: 'wa-suqyāhā', e: 'and her drink', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'وَالْإِغْرَاءُ،', t: 'wal-ighrāʾu', e: 'and incitement (ighrāʾ)' },
    NAHW, { g: ':' },
    { a: 'الْعِلْمَ', t: 'al-ʿilma', e: '“knowledge!' },
    { a: 'الْعِلْمَ', t: 'al-ʿilma', e: 'knowledge!”' },
  ] },
  { t: 'line', w: [
    { a: 'وَالْأَمْرُ،', t: 'wal-amru', e: 'and the command' },
    NAHW, { g: ':' }, OPEN,
    { a: 'وَأَقِيمُوا', t: 'wa-aqīmū', e: 'and establish', q: 1 },
    { a: 'الصَّلَاةَ', t: 'aṣ-ṣalāta', e: 'the prayer', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'وَالنَّهْيُ،', t: 'wan-nahyu', e: 'and prohibition' },
    NAHW, { g: ':' }, OPEN,
    { a: 'وَلَا', t: 'wa-lā', e: 'and do not', q: 1 },
    { a: 'تَقْرَبُوا', t: 'taqrabū', e: 'approach', q: 1 },
    { a: 'الْفَوَاحِشَ', t: 'al-fawāḥisha', e: 'immoralities', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'وَالدُّعَاءُ،', t: 'wad-duʿāʾu', e: 'and supplication (duʿāʾ)' },
    NAHW, { g: ':' }, OPEN,
    { a: 'سَلَامٌ', t: 'salāmun', e: 'Peace', q: 1 },
    { a: 'عَلَيْكُمْ', t: 'ʿalaykum', e: 'be upon you', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'وَصِيَغُ', t: 'wa-ṣiyaghu', e: 'and the forms of' },
    { a: 'الْمَدْحِ', t: 'al-madḥi', e: 'praise' },
    { a: 'وَالذَّمِّ،', t: 'wadh-dhammi', e: 'and blame' },
    NAHW, { g: ':' }, OPEN,
    { a: 'وَلَنِعْمَ', t: 'wa-la-niʿma', e: 'and how excellent is', q: 1 },
    { a: 'دَارُ', t: 'dāru', e: 'the home of', q: 1 },
    { a: 'الْمُتَّقِينَ', t: 'al-muttaqīna', e: 'the righteous', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'وَصِيَغُ', t: 'wa-ṣiyaghu', e: 'and the forms of' },
    { a: 'التَّوَجُّعِ', t: 'at-tawajjuʿi', e: 'lamentation' },
    { a: 'وَالتَّفَجُّعِ،', t: 'wat-tafajjuʿi', e: 'and grief' },
    NAHW, { g: ':' }, OPEN,
    { a: 'يَا', t: 'yā', e: 'O', q: 1 },
    { a: 'حَسْرَتَا', t: 'ḥasratā', e: 'my regret', q: 1 },
    { a: 'عَلَى', t: 'ʿalā', e: 'over', q: 1 },
    { a: 'مَا', t: 'mā', e: 'what', q: 1 },
    { a: 'فَرَّطْتُ', t: 'farraṭtu', e: 'I neglected', q: 1 },
    { a: 'فِي', t: 'fī', e: 'regarding', q: 1 },
    { a: 'جَنْبِ', t: 'janbi', e: 'the duty to', q: 1 },
    { a: 'اللهِ', t: 'Allāhi', e: 'Allah', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'وَالْقَسَمُ،', t: 'wal-qasamu', e: 'and the oath' },
    NAHW, { g: ':' }, OPEN,
    { a: 'وَالْعَصْرِ', t: 'wal-ʿaṣri', e: 'By time', q: 1 },
    CLOSE,
  ] },

  /* ── Issue 3: by relation to another sentence ── */
  { t: 'page', n: '١٣' },
  { t: 'h2', c: 'red', ar: 'الْمَسْأَلَةُ الثَّالِثَةُ: أَقْسَامُ الْجُمْلَةِ بِاعْتِبَارِ نِسْبَتِهَا إِلَى جُمْلَةٍ أُخْرَى',
    en: 'Third Issue — Divisions of the sentence by its relation to another sentence' },
  { t: 'line', w: [
    { a: 'وَهِيَ', t: 'wa-hiya', e: 'and it is' },
    { a: 'قِسْمَانِ', t: 'qismāni', e: 'two kinds' },
  ] },
  { t: 'h2', c: 'blue', ar: 'الْقِسْمُ الْأَوَّلُ: الْجُمْلَةُ الْكُبْرَى', en: 'First division — the major sentence (al-kubrā)' },
  { t: 'line', w: [
    { a: 'وَهِيَ', t: 'wa-hiya', e: 'and it is' },
    { a: 'مَا', t: 'mā', e: 'what' },
    { a: 'اشْتَمَلَتْ', t: 'ishtamalat', e: 'comprises' },
    { a: 'عَلَى', t: 'ʿalā', e: 'a' },
    { a: 'جُمْلَةٍ،', t: 'jumlatin', e: '[smaller] sentence' },
    NAHW, { g: ':' }, OPEN,
    { a: 'وَاللهُ', t: 'wallāhu', e: 'And Allah', q: 1 },
    { a: 'يَعْلَمُ', t: 'yaʿlamu', e: 'knows', q: 1 },
    CLOSE,
  ] },
  { t: 'h2', c: 'blue', ar: 'الْقِسْمُ الثَّانِي: الْجُمْلَةُ الصُّغْرَى', en: 'Second division — the minor sentence (aṣ-ṣughrā)' },
  { t: 'line', w: [
    { a: 'وَهِيَ', t: 'wa-hiya', e: 'and it is' },
    { a: 'مَا', t: 'mā', e: 'what' },
    { a: 'تَقَعُ', t: 'taqaʿu', e: 'occupies' },
    { a: 'مَوْقِعَ', t: 'mawqiʿa', e: 'the place of' },
    { a: 'مُفْرَدٍ', t: 'mufradin', e: 'a single word' },
    { a: 'فِي', t: 'fī', e: 'within' },
    { a: 'الْكُبْرَى،', t: 'al-kubrā', e: 'the major', n: 'e.g. “yaʿlam” is khabar of “Allāhu” — a small jumla in the place of a single word' },
    NAHW, { g: ':' }, OPEN,
    { a: 'وَاللهُ', t: 'wallāhu', e: 'And Allah', q: 1 },
    { a: 'يَعْلَمُ', t: 'yaʿlamu', e: 'knows', q: 1 },
    CLOSE,
  ] },

  /* ── Section 2: the Quasi-Sentence ── */
  { t: 'h2', c: 'green', ar: 'الْفَصْلُ الثَّانِي فِي شِبْهِ الْجُمْلَةِ', en: 'Second Section — On the Quasi-Sentence (shibh al-jumlah)' },
  { t: 'line', w: [
    { a: 'وَفِيهِ', t: 'wa-fīhi', e: 'and in it (are)' },
    { a: 'مَسْأَلَتَانِ', t: 'masʾalatāni', e: 'two issues' },
  ] },

  { t: 'h2', c: 'red', ar: 'الْمَسْأَلَةُ الْأُولَى: أَقْسَامُ شِبْهِ الْجُمْلَةِ بِاعْتِبَارِ هَيْئَتِهَا',
    en: 'First Issue — Divisions of the quasi-sentence by its form' },
  { t: 'line', w: [
    { a: 'وَهِيَ', t: 'wa-hiya', e: 'and it is' },
    { a: 'قِسْمَانِ', t: 'qismāni', e: 'two kinds' },
  ] },
  { t: 'h2', c: 'blue', ar: 'الْقِسْمُ الْأَوَّلُ: الْجَارُّ وَالْمَجْرُورُ', en: 'First — the preposition & its genitive (al-jārr wa-l-majrūr)' },
  { t: 'line', w: [
    NAHW, { g: ':' },
    { a: 'فِي', t: 'fī', e: '“in' },
    { a: 'مَكَّةَ', t: 'Makkata', e: 'Mecca”' },
  ] },
  { t: 'h2', c: 'blue', ar: 'الْقِسْمُ الثَّانِي: الظَّرْفُ وَالْمُضَافُ إِلَيْهِ', en: 'Second — the adverbial & its genitive (aẓ-ẓarf wa-l-muḍāf ilayhi)' },
  { t: 'line', w: [
    NAHW, { g: ':' },
    { a: 'عِنْدَ', t: 'ʿinda', e: '“by' },
    { a: 'الْكَعْبَةِ', t: 'al-kaʿbati', e: 'the Kaʿbah”' },
  ] },

  /* ── Issue 2: by governor ── */
  { t: 'page', n: '١٤' },
  { t: 'h2', c: 'red', ar: 'الْمَسْأَلَةُ الثَّانِيَةُ: أَقْسَامُ شِبْهِ الْجُمْلَةِ بِاعْتِبَارِ عَامِلِهَا',
    en: 'Second Issue — Divisions of the quasi-sentence by its governor (ʿāmil)' },
  { t: 'box', label: 'المتعلِّق والمتعلَّق', labelEn: 'The attaching & the attached-to', lines: [
    [
      { a: 'يُسَمَّى', t: 'yusammā', e: 'is called' },
      { a: 'عَامِلُ', t: 'ʿāmilu', e: 'the governor of' },
      { a: 'شِبْهِ', t: 'shibhi', e: 'the quasi-' },
      { a: 'الْجُمْلَةِ', t: 'al-jumlati', e: 'sentence' },
      { a: 'مُتَعَلَّقًا،', t: 'mutaʿallaqan', e: 'the attached-to (mutaʿallaq)' },
      { a: 'وَتُسَمَّى', t: 'wa-tusammā', e: 'and is called' },
      { a: 'شِبْهُ', t: 'shibhu', e: 'the quasi-' },
      { a: 'الْجُمْلَةِ', t: 'al-jumlati', e: 'sentence' },
      { a: 'الْوَاقِعَةُ', t: 'al-wāqiʿatu', e: 'occurring' },
      { a: 'فِي', t: 'fī', e: 'in' },
      { a: 'الْجُمْلَةِ', t: 'al-jumlati', e: 'the sentence' },
      { a: 'مُتَعَلِّقًا', t: 'mutaʿalliqan', e: 'the attaching (mutaʿalliq)' },
    ],
  ] },
  { t: 'line', w: [
    { a: 'وَهِيَ', t: 'wa-hiya', e: 'and it is' },
    { a: 'قِسْمَانِ', t: 'qismāni', e: 'two kinds' },
  ] },

  { t: 'h2', c: 'blue', ar: 'الْقِسْمُ الْأَوَّلُ: الظَّرْفُ اللَّغْوُ', en: 'First division — the relative adverbial (aẓ-ẓarf al-laghw)' },
  { t: 'line', w: [
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
    { a: 'شِبْهُ', t: 'shibhu', e: 'a quasi-' },
    { a: 'جُمْلَةٍ', t: 'jumlatin', e: 'sentence' },
    { a: 'عَامِلُهَا', t: 'ʿāmiluhā', e: 'whose governor is' },
    ELL,
  ] },
  { t: 'line', w: [
    { a: 'مَذْكُورٌ،', t: 'madhkūrun', e: 'mentioned' },
    NAHW, { g: ':' }, OPEN,
    { a: 'لَقَدْ', t: 'laqad', e: 'Certainly', q: 1 },
    { a: 'أَرْسَلْنَا', t: 'arsalnā', e: 'We sent', q: 1 },
    { a: 'نُوحًا', t: 'nūḥan', e: 'Nūḥ', q: 1 },
    { a: 'إِلَى', t: 'ilā', e: 'to', q: 1 },
    { a: 'قَوْمِهِ', t: 'qawmihi', e: 'his people', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'أَوْ', t: 'aw', e: 'or' },
    { a: 'مَحْذُوفٌ', t: 'maḥdhūfun', e: 'omitted' },
    { a: 'مَخْصُوصٌ،', t: 'makhṣūṣun', e: 'but a specific one' },
    NAHW, { g: ':' }, OPEN,
    { a: 'وَإِلَى', t: 'wa-ilā', e: 'And to', q: 1 },
    { a: 'عَادٍ', t: 'ʿādin', e: 'ʿĀd', q: 1 },
    { a: 'أَخَاهُمْ', t: 'akhāhum', e: 'their brother', q: 1 },
    { a: 'هُودًا', t: 'hūdan', e: 'Hūd', q: 1 },
    CLOSE,
    { a: 'أَيْ', t: 'ay', e: 'i.e.' },
    { a: 'أَرْسَلْنَا', t: 'arsalnā', e: 'We sent' },
  ] },

  { t: 'box', label: 'مواضع حذف عامل اللغو', labelEn: 'Where the laghw governor must be dropped', lines: [
    [
      { a: 'الْغَالِبُ', t: 'al-ghālibu', e: 'the common case' },
      { a: 'فِي', t: 'fī', e: 'with' },
      { a: 'عَامِلِ', t: 'ʿāmili', e: 'the governor of' },
      { a: 'الظَّرْفِ', t: 'aẓ-ẓarfi', e: 'the adverbial' },
      { a: 'اللَّغْوِ', t: 'al-laghwi', e: 'laghw' },
      { a: 'أَنْ', t: 'an', e: 'is that' },
      { a: 'يُذْكَرَ،', t: 'yudhkara', e: 'it be mentioned' },
      { a: 'وَيَجِبُ', t: 'wa-yajibu', e: 'but obligatory is' },
      { a: 'حَذْفُهُ', t: 'ḥadhfuhu', e: 'its omission' },
      { a: 'فِي', t: 'fī', e: 'in' },
      { a: 'مَوَاضِعَ،', t: 'mawāḍiʿa', e: 'certain places' },
      { a: 'مِنْهَا', t: 'minhā', e: 'among them' },
      ELL,
    ],
    [
      { a: 'الْأَوَّلُ', t: 'al-awwalu', e: 'the first' },
      { a: 'الْأَمْثَالُ،', t: 'al-amthālu', e: 'proverbs' },
      NAHW, { g: ':' },
      { a: 'الْكِلَابُ', t: 'al-kilābu', e: '“the dogs' },
      { a: 'عَلَى', t: 'ʿalā', e: 'upon' },
      { a: 'الْبَقَرِ', t: 'al-baqari', e: 'the cattle”', n: 'a proverb — the verb (“set them”) is dropped' },
    ],
    [
      { a: 'الثَّانِي', t: 'ath-thānī', e: 'the second' },
      { a: 'الْعِبَارَاتُ', t: 'al-ʿibārātu', e: 'the expressions' },
      { a: 'الْمَأْثُورَةُ،', t: 'al-maʾthūratu', e: 'transmitted' },
      NAHW, { g: ':' },
      { a: 'بِأَبِي', t: 'bi-abī', e: '“with my father' },
      { a: 'أَنْتَ', t: 'anta', e: 'are you' },
      { a: 'وَأُمِّي،', t: 'wa-ummī', e: 'and my mother”' },
      { a: 'أَيْ', t: 'ay', e: 'i.e.' },
      { a: 'أَنْتَ', t: 'anta', e: 'you' },
      { a: 'مَفْدِيٌّ', t: 'mafdiyyun', e: 'are ransomed' },
      { a: 'بِأَبِي', t: 'bi-abī', e: 'with my father' },
      { a: 'وَأُمِّي', t: 'wa-ummī', e: 'and my mother' },
    ],
    [
      { a: 'الثَّالِثُ', t: 'ath-thālithu', e: 'the third' },
      { a: 'الْقَسَمُ', t: 'al-qasamu', e: 'the oath' },
      { a: 'بِغَيْرِ', t: 'bi-ghayri', e: 'with other than' },
      { a: 'الْبَاءِ،', t: 'al-bāʾi', e: 'the bāʾ' },
      NAHW, { g: ':' }, OPEN,
      { a: 'تَاللهِ', t: 'ta-llāhi', e: 'By Allah', q: 1 },
      { a: 'تَفْتَأُ', t: 'taftaʾu', e: 'you will not cease', q: 1 },
      { a: 'تَذْكُرُ', t: 'tadhkuru', e: 'remembering', q: 1 },
      { a: 'يُوسُفَ', t: 'Yūsufa', e: 'Yūsuf', q: 1 },
      CLOSE,
    ],
    [
      { a: 'الرَّابِعُ', t: 'ar-rābiʿu', e: 'the fourth' },
      { a: 'خَبَرُ', t: 'khabaru', e: 'the predicate of' },
      { a: 'كَانَ', t: 'kāna', e: 'kāna' },
      { a: 'مَعَ', t: 'maʿa', e: 'with' },
      { a: 'لَامِ', t: 'lāmi', e: 'the lām of' },
      { a: 'الْجُحُودِ،', t: 'al-juḥūdi', e: 'denial (lām al-juḥūd)' },
      NAHW, { g: ':' }, OPEN,
      { a: 'مَا', t: 'mā', e: 'Not', q: 1 },
      { a: 'كَانَ', t: 'kāna', e: 'would', q: 1 },
      { a: 'اللهُ', t: 'Allāhu', e: 'Allah', q: 1 },
      { a: 'لِيُعَذِّبَهُمْ', t: 'li-yuʿadhdhibahum', e: 'punish them', q: 1 },
      { a: 'وَأَنْتَ', t: 'wa-anta', e: 'while you', q: 1 },
      { a: 'فِيهِمْ', t: 'fīhim', e: 'are among them', q: 1 },
      CLOSE,
      { a: 'أَيْ', t: 'ay', e: 'i.e.' },
      { a: 'قَاصِدًا', t: 'qāṣidan', e: 'intending' },
      { a: 'لِيُعَذِّبَهُمْ', t: 'li-yuʿadhdhibahum', e: 'to punish them' },
    ],
  ] },

  { t: 'h2', c: 'blue', ar: 'الْقِسْمُ الثَّانِي: الظَّرْفُ الْمُسْتَقَرُّ فِيهِ', en: 'Second division — the adverbial of settledness (aẓ-ẓarf al-mustaqarru fīh)' },
  { t: 'line', w: [
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
    { a: 'شِبْهُ', t: 'shibhu', e: 'a quasi-' },
    { a: 'جُمْلَةٍ', t: 'jumlatin', e: 'sentence' },
    { a: 'عَامِلُهَا', t: 'ʿāmiluhā', e: 'whose governor' },
    { a: 'مَحْذُوفٌ', t: 'maḥdhūfun', e: 'is omitted' },
    { a: 'عَامٌّ،', t: 'ʿāmmun', e: 'and general' },
    NAHW, { g: ':' }, OPEN,
    { a: 'إِنَّكَ', t: 'innaka', e: 'Indeed you are', q: 1 },
    { a: 'عَلَى', t: 'ʿalā', e: 'upon', q: 1 },
    { a: 'صِرَاطٍ', t: 'ṣirāṭin', e: 'a path', q: 1 },
    { a: 'مُسْتَقِيمٍ', t: 'mustaqīmin', e: 'straight', q: 1 },
    CLOSE,
    { a: 'أَيْ', t: 'ay', e: 'i.e.' },
    { a: 'تَثْبُتُ', t: 'tathbutu', e: 'you are established' },
    { a: 'أَيْ', t: 'ay', e: 'i.e.' },
    { a: 'ثَابِتٌ', t: 'thābitun', e: 'firm' },
  ] },

  /* ── the omitted general governor ── */
  { t: 'page', n: '١٥' },
  { t: 'box', label: 'المحذوف العام', labelEn: 'The general omitted governor', lines: [
    [
      { a: 'الْعَامِلُ', t: 'al-ʿāmilu', e: 'the governor' },
      { a: 'الْمَحْذُوفُ', t: 'al-maḥdhūfu', e: 'omitted' },
      { a: 'الْعَامُّ', t: 'al-ʿāmmu', e: 'general' },
      { a: 'مَا', t: 'mā', e: 'is what' },
      { a: 'يَدُلُّ', t: 'yadullu', e: 'denotes' },
      { a: 'عَلَى', t: 'ʿalā', e: '' },
      { a: 'الْوُجُودِ،', t: 'al-wujūdi', e: 'existence' },
      NAHW, { g: ':' },
      { a: 'اسْتَقَرَّ', t: 'istaqarra', e: '“settled”' },
      { a: 'وَوُجِدَ', t: 'wa-wujida', e: '“was found”' },
      { a: 'وَثَبَتَ', t: 'wa-thabata', e: '“was established”' },
    ],
  ] },
  { t: 'box', label: 'صور العامل المحذوف', labelEn: 'Forms the omitted governor takes', lines: [
    [
      { a: 'الْعَامِلُ', t: 'al-ʿāmilu', e: 'the governor' },
      { a: 'الْمَحْذُوفُ', t: 'al-maḥdhūfu', e: 'omitted' },
      { a: 'يَكُونُ', t: 'yakūnu', e: 'may be' },
      ELL,
    ],
    [
      { a: 'فِعْلًا،', t: 'fiʿlan', e: 'a verb' },
      NAHW, { g: ':' },
      { a: 'اسْتَقَرَّ،', t: 'istaqarra', e: 'istaqarra' },
      { a: 'وَثَبَتَ،', t: 'wa-thabata', e: 'thabata' },
      { a: 'وَوُجِدَ،', t: 'wa-wujida', e: 'wujida' },
      { a: 'وَيَكُونُ', t: 'wa-yakūnu', e: 'yakūnu' },
    ],
    [
      { a: 'أَوِ', t: 'awi', e: 'or' },
      { a: 'اسْمًا', t: 'isman', e: 'a noun' },
      { a: 'بِمَعْنَى', t: 'bi-maʿnā', e: 'with the sense of' },
      { a: 'الْفِعْلِ،', t: 'al-fiʿli', e: 'the verb' },
      NAHW, { g: ':' },
      { a: 'مُسْتَقِرٌّ،', t: 'mustaqirrun', e: 'mustaqirr' },
      { a: 'وَثَابِتٌ،', t: 'wa-thābitun', e: 'thābit' },
      { a: 'وَمَوْجُودٌ،', t: 'wa-mawjūdun', e: 'mawjūd' },
      { a: 'وَكَائِنٌ', t: 'wa-kāʾinun', e: 'kāʾin' },
    ],
    [
      { a: 'إِلَّا', t: 'illā', e: 'except' },
      { a: 'فِي', t: 'fī', e: 'in' },
      { a: 'الصِّلَةِ،', t: 'aṣ-ṣilati', e: 'the relative clause (ṣilah)' },
      { a: 'فَيَكُونُ', t: 'fa-yakūnu', e: 'where it is' },
      { a: 'فِعْلًا', t: 'fiʿlan', e: 'a verb' },
      { a: 'لَا', t: 'lā', e: 'and nothing' },
      { a: 'غَيْرَ،', t: 'ghayra', e: 'else' },
      NAHW, { g: ':' },
      { a: 'الَّذِي', t: 'alladhī', e: '“the one' },
      { a: 'فِي', t: 'fī', e: 'in' },
      { a: 'مَكَّةَ', t: 'Makkata', e: 'Mecca”' },
      { a: 'أَيِ', t: 'ayi', e: 'i.e.' },
      { a: 'اسْتَقَرَّ', t: 'istaqarra', e: 'settled' },
    ],
  ] },
  { t: 'box', label: 'مواضع الظرف المستقر', labelEn: 'The five places of the settled adverbial', lines: [
    [
      { a: 'يَقَعُ', t: 'yaqaʿu', e: 'occurs' },
      { a: 'الظَّرْفُ', t: 'aẓ-ẓarfu', e: 'the adverbial' },
      { a: 'الْمُسْتَقَرُّ', t: 'al-mustaqarru', e: 'settled' },
      { a: 'فِي', t: 'fī', e: 'in' },
      { a: 'خَمْسَةِ', t: 'khamsati', e: 'five' },
      { a: 'مَوَاضِعَ', t: 'mawāḍiʿa', e: 'places' }, { g: ':' },
    ],
    [
      { a: 'الْأَوَّلُ', t: 'al-awwalu', e: 'the first' },
      { a: 'الْخَبَرُ', t: 'al-khabaru', e: 'the predicate' },
      { a: 'وَمَا', t: 'wa-mā', e: 'and what' },
      { a: 'فِي', t: 'fī', e: 'is in' },
      { a: 'حُكْمِهِ،', t: 'ḥukmihi', e: 'its ruling' },
      NAHW, { g: ':' }, OPEN,
      { a: 'وَهُوَ', t: 'wa-huwa', e: 'and He is', q: 1 },
      { a: 'عَلَى', t: 'ʿalā', e: 'upon', q: 1 },
      { a: 'صِرَاطٍ', t: 'ṣirāṭin', e: 'a path', q: 1 },
      { a: 'مُسْتَقِيمٍ', t: 'mustaqīmin', e: 'straight', q: 1 },
      CLOSE,
    ],
    [
      { a: 'الثَّانِي', t: 'ath-thānī', e: 'the second' },
      { a: 'الْحَالُ،', t: 'al-ḥālu', e: 'the circumstantial (ḥāl)' },
      NAHW, { g: ':' }, OPEN,
      { a: 'فَخَرَجَ', t: 'fa-kharaja', e: 'so he went out', q: 1 },
      { a: 'عَلَى', t: 'ʿalā', e: 'before', q: 1 },
      { a: 'قَوْمِهِ', t: 'qawmihi', e: 'his people', q: 1 },
      { a: 'فِي', t: 'fī', e: 'in', q: 1 },
      { a: 'زِينَتِهِ', t: 'zīnatihi', e: 'his adornment', q: 1 },
      CLOSE,
    ],
    [
      { a: 'الثَّالِثُ', t: 'ath-thālithu', e: 'the third' },
      { a: 'النَّعْتُ،', t: 'an-naʿtu', e: 'the adjective (naʿt)' },
      NAHW, { g: ':' }, OPEN,
      { a: 'أُولَئِكَ', t: 'ulāʾika', e: 'those are', q: 1 },
      { a: 'عَلَى', t: 'ʿalā', e: 'upon', q: 1 },
      { a: 'هُدًى', t: 'hudan', e: 'guidance', q: 1 },
      { a: 'مِنْ', t: 'min', e: 'from', q: 1 },
      { a: 'رَبِّهِمْ', t: 'rabbihim', e: 'their Lord', q: 1 },
      CLOSE,
    ],
    [
      { a: 'الرَّابِعُ', t: 'ar-rābiʿu', e: 'the fourth' },
      { a: 'الصِّلَةُ،', t: 'aṣ-ṣilatu', e: 'the relative clause (ṣilah)' },
      NAHW, { g: ':' }, OPEN,
      { a: 'وَلَهُ', t: 'wa-lahu', e: 'and to Him belongs', q: 1 },
      { a: 'مَنْ', t: 'man', e: 'whoever', q: 1 },
      { a: 'فِي', t: 'fī', e: 'is in', q: 1 },
      { a: 'السَّمَاوَاتِ', t: 'as-samāwāti', e: 'the heavens', q: 1 },
      { a: 'وَالْأَرْضِ', t: 'wal-arḍi', e: 'and the earth', q: 1 },
      CLOSE,
    ],
    [
      { a: 'الْخَامِسُ', t: 'al-khāmisu', e: 'the fifth' },
      { a: 'الِاعْتِمَادُ،', t: 'al-iʿtimādu', e: 'dependence (iʿtimād)' },
      NAHW, { g: ':' }, OPEN,
      { a: 'أَفِي', t: 'a-fī', e: 'Is there about', q: 1 },
      { a: 'اللهِ', t: 'Allāhi', e: 'Allah', q: 1 },
      { a: 'شَكٌّ', t: 'shakkun', e: 'any doubt', q: 1 },
      CLOSE,
    ],
  ] },

  /* ── Section 3: Speech ── */
  { t: 'page', n: '١٦' },
  { t: 'h2', c: 'green', ar: 'الْفَصْلُ الثَّالِثُ فِي الْكَلَامِ', en: 'Third Section — On Speech (al-kalām)' },
  { t: 'line', w: [
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
    { a: 'قَوْلٌ', t: 'qawlun', e: 'an utterance' },
    { a: 'مُفِيدٌ', t: 'mufīdun', e: 'beneficial (mufīd)', n: 'one it is good to fall silent upon' },
  ] },
  { t: 'line', w: [
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
    { a: 'قِسْمَانِ', t: 'qismāni', e: 'two kinds' },
  ] },
  { t: 'h2', c: 'blue', ar: 'الْقِسْمُ الْأَوَّلُ: الْمُوجَبُ', en: 'First division — the affirmative (al-mūjab)' },
  { t: 'line', w: [
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
    { a: 'مَا', t: 'mā', e: 'that in which' },
    { a: 'لَيْسَ', t: 'laysa', e: 'there is not' },
    { a: 'فِيهِ', t: 'fīhi', e: 'in it' },
    { a: 'نَفْيٌ', t: 'nafyun', e: 'negation' },
    { a: 'أَوْ', t: 'aw', e: 'or' },
    { a: 'نَهْيٌ', t: 'nahyun', e: 'prohibition' },
    { a: 'أَوِ', t: 'awi', e: 'or' },
    { a: 'اسْتِفْهَامٌ،', t: 'istifhāmun', e: 'interrogation' },
    NAHW, { g: ':' }, OPEN,
    { a: 'أَعْبُدُ', t: 'aʿbudu', e: 'I worship', q: 1 },
    { a: 'اللهَ', t: 'Allāha', e: 'Allah', q: 1 },
    { a: 'الَّذِي', t: 'alladhī', e: 'who', q: 1 },
    { a: 'يَتَوَفَّاكُمْ', t: 'yatawaffākum', e: 'takes your souls', q: 1 },
    CLOSE,
  ] },
  { t: 'h2', c: 'blue', ar: 'الْقِسْمُ الثَّانِي: غَيْرُ الْمُوجَبِ', en: 'Second division — the non-affirmative (ghayr al-mūjab)' },
  { t: 'line', w: [
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
    { a: 'مَا', t: 'mā', e: 'that in which' },
    { a: 'فِيهِ', t: 'fīhi', e: 'there is' },
    ELL,
  ] },
  { t: 'line', w: [
    { a: 'نَفْيٌ،', t: 'nafyun', e: 'negation' },
    NAHW, { g: ':' }, OPEN,
    { a: 'فَلَا', t: 'fa-lā', e: 'so I do not', q: 1 },
    { a: 'أَعْبُدُ', t: 'aʿbudu', e: 'worship', q: 1 },
    { a: 'الَّذِينَ', t: 'alladhīna', e: 'those whom', q: 1 },
    { a: 'تَعْبُدُونَ', t: 'taʿbudūna', e: 'you worship', q: 1 },
    { a: 'مِنْ', t: 'min', e: '', q: 1 },
    { a: 'دُونِ', t: 'dūni', e: 'besides', q: 1 },
    { a: 'اللهِ', t: 'Allāhi', e: 'Allah', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'أَوْ', t: 'aw', e: 'or' },
    { a: 'نَهْيٌ،', t: 'nahyun', e: 'prohibition' },
    NAHW, { g: ':' }, OPEN,
    { a: 'لَا', t: 'lā', e: 'do not', q: 1 },
    { a: 'تُشْرِكْ', t: 'tushrik', e: 'associate', q: 1 },
    { a: 'بِاللهِ', t: 'bi-llāhi', e: 'with Allah', q: 1 },
    CLOSE,
  ] },
  { t: 'line', w: [
    { a: 'أَوِ', t: 'awi', e: 'or' },
    { a: 'اسْتِفْهَامٌ،', t: 'istifhāmun', e: 'interrogation' },
    NAHW, { g: ':' }, OPEN,
    { a: 'أَأَتَّخِذُ', t: 'a-attakhidhu', e: 'Should I take', q: 1 },
    { a: 'مِنْ', t: 'min', e: '', q: 1 },
    { a: 'دُونِهِ', t: 'dūnihi', e: 'besides Him', q: 1 },
    { a: 'آلِهَةً', t: 'ālihatan', e: 'gods', q: 1 },
    CLOSE,
  ] },
];
