// Daram — pre-generated question bank.  DO NOT EDIT BY HAND.
// Built by test-maker/build-bank.mjs on 2026-06-29T20:41:48.678Z.
// 70 questions across 6 chapters.
// Each item: { id, chapterId, chapterAr, chapterEn, archetype, marks, promptEn, promptAr, markScheme }.
const QUESTION_BANK =
[
  {
    "id": "muq-bab-1--explain-line--explain-the-following-matn-line--a",
    "chapterId": "muq-bab-1",
    "chapterAr": "الباب الأول في الكلمة",
    "chapterEn": "The Word (al-kalimah)",
    "archetype": "explain-line",
    "marks": 5,
    "promptEn": "Explain the following matn line, making clear what kind of word it defines and how the definition works.",
    "promptAr": "الِاسْمُ وَهُوَ مَا دَلَّ عَلَى مَعْنًى فِي نَفْسِهِ غَيْرِ مُقْتَرِنٍ بِزَمَانٍ.",
    "markScheme": "Model answer: This is the definition of the noun (al-ism). 'مَا دَلَّ عَلَى مَعْنًى' = it denotes a meaning; 'فِي نَفْسِهِ' = that meaning is complete in itself, i.e. understood without needing another word (this distinguishes the noun from the ḥarf, whose meaning is فِي غَيْرِهِ); 'غَيْرِ مُقْتَرِنٍ بِزَمَانٍ' = not coupled with a tense/time, which distinguishes it from the verb (which is مُقْتَرِنٌ بِزَمَانٍ). Examples: رَجُلٌ, عِلْمٌ. Marks: 1 for identifying it as the definition of the noun; 2 for 'meaning in itself' and its distinction from the ḥarf; 2 for 'not coupled with time' and its distinction from the verb."
  },
  {
    "id": "muq-bab-1--explain-line--explain-the-following-matn-line--c",
    "chapterId": "muq-bab-1",
    "chapterAr": "الباب الأول في الكلمة",
    "chapterEn": "The Word (al-kalimah)",
    "archetype": "explain-line",
    "marks": 5,
    "promptEn": "Explain the following matn line and show, with an example, why a ḥarf differs from a noun and a verb in how it conveys meaning.",
    "promptAr": "الْحَرْفُ مَا دَلَّ عَلَى مَعْنًى فِي غَيْرِهِ، نَحْوُ فِي وَإِنَّ.",
    "markScheme": "Model answer: This defines the particle (al-ḥarf). 'مَا دَلَّ عَلَى مَعْنًى فِي غَيْرِهِ' = it denotes a meaning only in/through another word — it cannot convey its meaning standing alone but needs a متعلَّق. Contrast: the noun and verb denote a meaning فِي نَفْسِهِ (complete in themselves). Example: فِي (in) has no understood sense until joined to something, e.g. فِي الْبَيْتِ; likewise إِنَّ requires a following clause. Marks: 1 identify as definition of the ḥarf; 2 explain 'meaning in another' / dependence on a متعلَّق; 1 contrast with noun and verb; 1 valid worked example."
  },
  {
    "id": "muq-bab-1--state-types--state-the-three-divisions-of-the-e",
    "chapterId": "muq-bab-1",
    "chapterAr": "الباب الأول في الكلمة",
    "chapterEn": "The Word (al-kalimah)",
    "archetype": "state-types",
    "marks": 6,
    "promptEn": "State the three divisions of the word (al-kalimah) and, for each, give one recognising sign (ʿalāmah) by which it may be identified, with an example.",
    "promptAr": "",
    "markScheme": "Model answer: (1) الِاسْم (noun) — recognised e.g. by being مَجْرُور (بِسْمِ اللهِ), or by أل (الرَّحْمٰنِ), or by tanwīn (هُدًى), etc. (2) الْفِعْل (verb) — recognised e.g. by accepting قَدْ / السِّين / سَوْفَ / لَمْ / لَنْ, or تاء التأنيث الساكنة (آمَنَتْ), or the مُضارعة letters (يُحْيِي). (3) الْحَرْف (particle) — recognised by the absence in it of any sign of the noun or verb (هَلْ، بَلْ). Marks: 2 per division (1 for naming it, 1 for a correct sign + example). Total 6."
  },
  {
    "id": "muq-bab-1--compare--explain-with-examples-the-differ-g",
    "chapterId": "muq-bab-1",
    "chapterAr": "الباب الأول في الكلمة",
    "chapterEn": "The Word (al-kalimah)",
    "archetype": "compare",
    "marks": 8,
    "promptEn": "Explain, with examples, the difference between اسم العين (noun of a concrete entity) and اسم المعنى (noun of an abstract meaning).",
    "promptAr": "",
    "markScheme": "Model answer: Both fall under the مَوْصُوف (substantive: مَا دَلَّ عَلَى ذَاتٍ تَحْتَمِلُ الصِّفَةَ). اسْمُ الْعَيْن = denotes something that subsists by itself (مَا يَقُومُ بِذَاتِهِ), e.g. رَجُلٌ, a man — a self-standing entity. اسْمُ الْمَعْنَى = denotes something that does NOT subsist by itself but subsists through another (لَا يَقُومُ بِذَاتِهِ بَلْ يَقُومُ بِغَيْرِهِ), e.g. عِلْمٌ, knowledge — which exists only in a knower. Marks: 2 for placing both under al-mawṣūf; 2 for correct definition of ism ʿayn + example; 2 for correct definition of ism maʿnā + example; 2 for clearly articulating the contrast (self-subsisting vs. subsisting-through-another)."
  },
  {
    "id": "muq-bab-1--compare--explain-with-examples-the-differ-i",
    "chapterId": "muq-bab-1",
    "chapterAr": "الباب الأول في الكلمة",
    "chapterEn": "The Word (al-kalimah)",
    "archetype": "compare",
    "marks": 8,
    "promptEn": "Explain, with examples, the difference between حرف المدّ (letter of prolongation) and حرف اللين (letter of softness).",
    "promptAr": "حَرْفُ مَدٍّ حَرْفُ عِلَّةٍ سَاكِنٌ قَبْلَهُ حَرَكَةٌ تُنَاسِبُهُ — حَرْفُ لِينٍ حَرْفُ وَاوٍ أَوْ يَاءٍ سَاكِنٌ قَبْلَهُ فَتْحَةٌ.",
    "markScheme": "Model answer: حرف المدّ is a vowelless letter of ʿillah (ا/و/ي) preceded by a homogeneous (matching) vowel — alif after fatḥa, wāw after ḍamma, yāʾ after kasra, e.g. كُونُوا (ḍamma before sākin wāw). حرف اللين is specifically a vowelless wāw or yāʾ preceded by a fatḥa (which does NOT match it), e.g. الخَيْر، التَّوْبَة. Key difference: madd requires the preceding vowel to be homogeneous with the letter; līn has a wāw/yāʾ sākin preceded by a non-homogeneous fatḥa; also līn is restricted to wāw and yāʾ. Marks: 2 definition+example of madd; 2 definition+example of līn; 2 the homogeneity (مناسبة) point; 2 noting alif cannot be a līn letter / līn limited to wāw & yāʾ."
  },
  {
    "id": "muq-bab-1--explain-statement--explain-the-following-statement--k",
    "chapterId": "muq-bab-1",
    "chapterAr": "الباب الأول في الكلمة",
    "chapterEn": "The Word (al-kalimah)",
    "archetype": "explain-statement",
    "marks": 15,
    "promptEn": "Explain the following statement as fully as possible, with examples.",
    "promptAr": "يَشْتَمِلُ الْفِعْلُ عَلَى ثَلَاثَةِ مَعَانٍ: الْأَوَّلُ الْحَدَثُ وَهُوَ مَعْنَى الْمَصْدَرِ، وَالثَّانِي الزَّمَانُ، وَالثَّالِثُ الْفَاعِلُ. وَالْفِعْلُ يَتَكَوَّنُ مِنْ مَادَّةٍ وَهَيْئَةٍ.",
    "markScheme": "Model answer: The verb comprises three meanings together: (1) الحدث — the event/action itself, which is the meaning of the maṣdar; (2) الزمان — the time of its occurrence (past/present); (3) الفاعل — the doer. So جَلَسَ denotes the act of sitting, that it occurred in the past, and a doer. Composition: every verb is made of a مَادَّة (root-material) and a هَيْئَة (pattern). The mādda of نَصَرَ is ن-ص-ر and denotes the event (النصر = help); the hayʾa is the pattern فَعَلَ and denotes that it occurred in the past. Note: some nouns indicate time by their material (mādda) not their pattern, e.g. أَمْسِ، الآنَ، غَدًا — but they remain nouns because the time is not from a verbal pattern. Marks: 3 for naming/explaining ḥadath (=maṣdar meaning); 3 for zamān; 3 for fāʿil; 3 for the mādda/hayʾa distinction with a worked example (naṣara); 2 for the ams/al-ān/ghadan nuance; 1 for the worked example جلس. Total 15."
  },
  {
    "id": "muq-bab-1--explain-statement--explain-the-following-statement--m",
    "chapterId": "muq-bab-1",
    "chapterAr": "الباب الأول في الكلمة",
    "chapterEn": "The Word (al-kalimah)",
    "archetype": "explain-statement",
    "marks": 15,
    "promptEn": "Explain the following statement on the signs of the noun as fully as possible, with examples, noting how the verb and particle are excluded.",
    "promptAr": "يُعْرَفُ الِاسْمُ بِأَنْ يَكُونَ مَجْرُورًا، وَبِأَلْ لِلتَّعْرِيفِ، وَبِالتَّنْوِينِ، وَبِأَنْ يَكُونَ مُسْنَدًا إِلَيْهِ، وَبِأَنْ يَكُونَ مُنَادًى، وَبِأَنْ يَكُونَ مُضَافًا.",
    "markScheme": "Model answer: The noun is recognised by six signs: (1) being majrūr — بِسْمِ اللهِ; (2) أل of definiteness — الرَّحْمٰنِ الرَّحِيمِ; (3) tanwīn — هُدًى لِلْمُتَّقِينَ (the tanwīn intended excludes تنوين الترنّم of poetry); (4) being musnad ilayhi (subject/predicated-to) — إِنَّ إِبْرَاهِيمَ لَحَلِيمٌ; (5) being a munādā (vocative) — يَا نُوحُ; (6) being muḍāf (possessor) — رَبِّ الْعَالَمِينَ. The verb and ḥarf can never be majrūr even if a jārr precedes them (لِيَكُونَ لِلْعَالَمِينَ نَذِيرًا; بِأَنَّا مُسْلِمُونَ — here أن + clause is an interpreted noun). Likewise vocative particles may enter on a non-munādā (يَا لَيْتَ قَوْمِي), where يا is a particle of tanbīh / the munādā is omitted. Marks: 1 per sign with example (6); 3 for the verb/ḥarf not taking jarr point with example; 2 for the muʾawwal/jarr nuance; 2 for the tanwīn al-tarannum or yā-non-munādā nuance; 1 organisation/completeness. Total 15."
  },
  {
    "id": "muq-bab-1--define-types-examples--what-is-the-noun-considered-with-o",
    "chapterId": "muq-bab-1",
    "chapterAr": "الباب الأول في الكلمة",
    "chapterEn": "The Word (al-kalimah)",
    "archetype": "define-types-examples",
    "marks": 15,
    "promptEn": "What is the noun considered with respect to its being simple or compound (bi-iʿtibār ifrādihi wa-tarkībihi)? State its types and give examples.",
    "promptAr": "",
    "markScheme": "Model answer: By this consideration the noun is of two kinds (ضربان): (1) الاسم الصريح (the explicit noun) — the noun standing on its own, e.g. الصَّوْمُ. (2) الاسم المؤوّل (the interpreted noun) — a حرف مصدر together with the clause after it, taken in the sense of a maṣdar, e.g. وَأَنْ تَصُومُوا خَيْرٌ (= وَصِيَامُكُمْ خَيْرٌ). Supporting points: what takes the genitive includes the muʾawwal too, not just the ṣarīḥ — e.g. أن + clause functions as a noun and can be governed; the bare verb/ḥarf cannot take jarr. Marks: 2 for framing as 'two kinds by ifrād/tarkīb'; 4 for ṣarīḥ defined + example; 4 for muʾawwal defined (ḥarf maṣdar + clause) + example; 3 for showing the muʾawwal works as a noun (e.g. can be majrūr / paraphrase to maṣdar); 2 quality of examples. Total 15."
  },
  {
    "id": "muq-bab-1--define-types-examples--what-is-the-substantive-consider-q",
    "chapterId": "muq-bab-1",
    "chapterAr": "الباب الأول في الكلمة",
    "chapterEn": "The Word (al-kalimah)",
    "archetype": "define-types-examples",
    "marks": 15,
    "promptEn": "What is the مَوْصُوف (substantive) considered by its meaning? State its types and give examples, and contrast it with the صِفَة.",
    "promptAr": "",
    "markScheme": "Model answer: By its meaning the noun is two kinds: المَوْصُوف and الصِّفَة. The mawṣūf = مَا دَلَّ عَلَى ذَاتٍ تَحْتَمِلُ الصِّفَةَ (denotes an entity that can bear an attribute); it is itself two: (1) اسم عين — denotes what subsists by itself (مَا يَقُومُ بِذَاتِهِ), e.g. رَجُلٌ; (2) اسم معنى — denotes what does not subsist by itself but through another, e.g. عِلْمٌ. The ṣifah = مَا دَلَّ عَلَى وَصْفِ مَوْصُوفٍ (denotes a quality of something described), e.g. صَالِحٌ / عَالِمٌ. Marks: 2 for the two-kinds framing (mawṣūf vs ṣifah); 3 for defining mawṣūf; 3 for ism ʿayn + example; 3 for ism maʿnā + example; 3 for ṣifah defined + example; 1 completeness. Total 15."
  },
  {
    "id": "muq-bab-1--enumerate--enumerate-the-signs-al-m-t-of-th-s",
    "chapterId": "muq-bab-1",
    "chapterAr": "الباب الأول في الكلمة",
    "chapterEn": "The Word (al-kalimah)",
    "archetype": "enumerate",
    "marks": 12,
    "promptEn": "Enumerate the signs (ʿalāmāt) of the verb that are special to the muḍāriʿ (present tense), giving the meaning/function of each with an example.",
    "promptAr": "",
    "markScheme": "Model answer (signs special to the muḍāriʿ): (1) لَمْ — negation+jazm of the present, لَمْ يَلِدْ; (2) لَنْ — negation of the future ('never'), لَنْ يُصِيبَنَا; (3) السِّين — near future ('will'), سَيَرْحَمُهُمُ اللهُ; (4) سَوْفَ — future ('shall'), سَوْفَ أَسْتَغْفِرُ; (5) the letters of muḍāraʿah ن-أ-ت-ي (نأتي) opening the verb, يُحْيِي وَيُمِيتُ; (6) نُونَا التَّأْكِيد (the two nūns of emphasis), لَيُسْجَنَنَّ. Marks: 2 per item (1 name, 1 meaning+example) for six items = 12. Award partial if fewer items; accept also قَدْ noting it is shared with the past (not exclusive to muḍāriʿ) — do not penalise listing it as shared."
  },
  {
    "id": "muq-bab-1--enumerate--enumerate-the-six-signs-by-which-u",
    "chapterId": "muq-bab-1",
    "chapterAr": "الباب الأول في الكلمة",
    "chapterEn": "The Word (al-kalimah)",
    "archetype": "enumerate",
    "marks": 12,
    "promptEn": "Enumerate the six signs by which the noun (al-ism) is recognised, stating the function of each with an example.",
    "promptAr": "",
    "markScheme": "Model answer: (1) كونه مجرورًا — being in the genitive: بِسْمِ اللهِ; (2) أل التعريف — the definite article: الرَّحْمٰنِ الرَّحِيمِ; (3) التنوين — nunation: هُدًى لِلْمُتَّقِينَ; (4) كونه مسندًا إليه — being that which is predicated to: إِنَّ إِبْرَاهِيمَ لَحَلِيمٌ; (5) كونه منادًى — being a vocative: يَا نُوحُ; (6) كونه مضافًا — being a possessor/muḍāf: رَبِّ الْعَالَمِينَ. Marks: 2 per sign (1 naming, 1 correct example) = 12 total."
  },
  {
    "id": "muq-bab-1--classify-tarkib--classify-the-category-ism-fi-l-a-w",
    "chapterId": "muq-bab-1",
    "chapterAr": "الباب الأول في الكلمة",
    "chapterEn": "The Word (al-kalimah)",
    "archetype": "classify-tarkib",
    "marks": 9,
    "promptEn": "Classify the category (ism / fiʿl / ḥarf) of each underlined word, then translate the phrase and give its tarkīb (iʿrāb).",
    "promptAr": "كِتَابُ الْوَلَدِ",
    "markScheme": "Model answer: Classification — كِتَابُ is an ism (noun); الْوَلَدِ is an ism (noun); the phrase as a whole is مُرَكَّب (its parts each denote a meaning, unlike the مُفْرَد). Translation: 'the book of the child / the child's book.' Tarkīb: this is a tarkīb iḍāfī (genitive construction): كِتَابُ = muḍāf, marfūʿ/here showing ḍamma as the base form, and it is the muḍāf; الْوَلَدِ = muḍāf ilayhi, majrūr, sign of jarr the kasra. The whole is an example of المُرَكَّب because كِتَاب denotes a meaning and الوَلَد denotes a meaning. Marks: 1 kitāb = ism; 1 walad = ism; 1 phrase = murakkab (with reason); 2 correct translation; 2 identifying iḍāfah (muḍāf / muḍāf ilayhi); 2 iʿrāb of al-walad as majrūr by kasra (muḍāf ilayhi). Total 9."
  },
  {
    "id": "muq-bab-1--classify-tarkib--classify-the-category-ism-fi-l-a-y",
    "chapterId": "muq-bab-1",
    "chapterAr": "الباب الأول في الكلمة",
    "chapterEn": "The Word (al-kalimah)",
    "archetype": "classify-tarkib",
    "marks": 9,
    "promptEn": "Classify the category (ism / fiʿl / ḥarf) of each word, then translate the sentence and give its tarkīb (iʿrāb), commenting on the sign that identifies the verb.",
    "promptAr": "سَيَرْحَمُهُمُ اللهُ.",
    "markScheme": "Model answer: Classification — السِّين is a ḥarf (a sign of the muḍāriʿ verb, here a particle of near-future); يَرْحَمُ is a fiʿl muḍāriʿ (recognised by the مُضارعة letter يـ and by accepting the سِّين); هُمُ is an ism (attached object pronoun, mabnī); اللهُ is an ism. Translation: 'Allah will (soon) have mercy on them.' Tarkīb: السِّين حرف تنفيس / استقبال; يَرْحَمُ fiʿl muḍāriʿ marfūʿ, sign ḍamma; the ـهُمُ is a connected pronoun in maḥall naṣb as the object (mafʿūl bihi); اللهُ is the fāʿil, marfūʿ, sign ḍamma (lafẓ al-jalālah). The verbhood of يرحم is confirmed by the prefixed سِّين, a sign special to the muḍāriʿ. Marks: 1 sīn = ḥarf; 1 yarḥamu = fiʿl; 1 hum/Allāh = ism; 2 translation; 2 fāʿil + maf'ūl identification; 2 verb-sign comment (sīn special to muḍāriʿ). Total 9."
  },
  {
    "id": "muq-bab-2--explain-line--explain-the-following-matn-line--1n",
    "chapterId": "muq-bab-2",
    "chapterAr": "الباب الثاني في الجملة وشبه الجملة والكلام",
    "chapterEn": "Sentence, quasi-sentence & speech",
    "archetype": "explain-line",
    "marks": 5,
    "promptEn": "Explain the following matn line, clarifying the term it defines.",
    "promptAr": "الْكَلَامُ هُوَ قَوْلٌ مُفِيدٌ",
    "markScheme": "Model answer: This is the definition of al-kalām (speech) given in the third section. Al-kalām is a 'qawl' (an utterance — articulate sounds carrying letters) that is 'mufīd' (beneficial), i.e. it conveys a complete meaning upon which it is sound for the listener to remain silent, e.g. أَعْبُدُ اللهَ. The qualifier mufīd excludes utterances that do not yield a complete benefit. Breakdown: 2 marks for explaining 'qawl' (an utterance); 2 marks for explaining 'mufīd' (conveys complete benefit / listener can be silent); 1 mark for noting this is the definition of kalām with a correct example."
  },
  {
    "id": "muq-bab-2--explain-line--explain-the-following-matn-line--1p",
    "chapterId": "muq-bab-2",
    "chapterAr": "الباب الثاني في الجملة وشبه الجملة والكلام",
    "chapterEn": "Sentence, quasi-sentence & speech",
    "archetype": "explain-line",
    "marks": 5,
    "promptEn": "Explain the following matn line and what it defines, with an example.",
    "promptAr": "وَهِيَ مَا تَقَعُ مَوْقِعَ مُفْرَدٍ فِي الْكُبْرَى",
    "markScheme": "Model answer: This defines al-jumlah aṣ-ṣughrā (the minor sentence) under the third issue (division by relation to another sentence). The minor sentence is one that occupies the position of a single word (mufrad) within a larger/major sentence — i.e. it functions grammatically as one unit (such as a khabar) inside the kubrā. Example: in وَاللهُ يَعْلَمُ, the verbal sentence يَعْلَمُ is the ṣughrā occupying the place of the khabar of اللهُ, while the whole is the kubrā. Breakdown: 2 marks for identifying the term (ṣughrā); 2 marks for explaining 'occupies the place of a single word in the kubrā'; 1 mark for a correct example showing the ṣughrā inside the kubrā."
  },
  {
    "id": "muq-bab-2--state-types--state-the-divisions-of-the-sente-1r",
    "chapterId": "muq-bab-2",
    "chapterAr": "الباب الثاني في الجملة وشبه الجملة والكلام",
    "chapterEn": "Sentence, quasi-sentence & speech",
    "archetype": "state-types",
    "marks": 6,
    "promptEn": "State the divisions of the sentence (al-jumlah) with respect to its form (hayʾah), and for each give the recognising sign (ʿalāmah) by which it is identified, with an example.",
    "promptAr": "",
    "markScheme": "Model answer: By its form the sentence is two kinds: (1) al-jumlah al-ismiyyah (nominal) — ʿalāmah: it begins with a noun (مَا صَدَرَتْ بِاسْمٍ), e.g. وَاللهُ غَفُورٌ رَحِيمٌ; (2) al-jumlah al-fiʿliyyah (verbal) — ʿalāmah: it begins with a verb (مَا صَدَرَتْ بِفِعْلٍ), e.g. وَخَلَقَ كُلَّ شَيْءٍ. Breakdown: 1 mark each for naming the two types (2); 1 mark each for the correct ʿalāmah of each (2); 1 mark each for a sound example of each (2)."
  },
  {
    "id": "muq-bab-2--state-types--state-the-divisions-of-the-quasi-1t",
    "chapterId": "muq-bab-2",
    "chapterAr": "الباب الثاني في الجملة وشبه الجملة والكلام",
    "chapterEn": "Sentence, quasi-sentence & speech",
    "archetype": "state-types",
    "marks": 6,
    "promptEn": "State the divisions of the quasi-sentence (shibh al-jumlah) with respect to its form, giving for each its recognising sign and an example.",
    "promptAr": "",
    "markScheme": "Model answer: By its form shibh al-jumlah is two kinds: (1) al-jārr wa-l-majrūr — recognised by a preposition followed by its genitive noun, e.g. فِي مَكَّةَ; (2) aẓ-ẓarf wa-l-muḍāf ilayh — recognised by an adverb (of time/place) followed by the noun it is annexed to, e.g. عِنْدَ الْكَعْبَةِ. Breakdown: 1 mark each for naming the two kinds (2); 1 mark each for the recognising sign (2); 1 mark each for a correct example (2)."
  },
  {
    "id": "muq-bab-2--compare--explain-with-examples-the-differ-1v",
    "chapterId": "muq-bab-2",
    "chapterAr": "الباب الثاني في الجملة وشبه الجملة والكلام",
    "chapterEn": "Sentence, quasi-sentence & speech",
    "archetype": "compare",
    "marks": 8,
    "promptEn": "Explain, with examples, the difference between the declarative sentence (al-jumlah al-khabariyyah) and the performative sentence (al-jumlah al-inshāʾiyyah).",
    "promptAr": "",
    "markScheme": "Model answer: This is the division of the sentence by its meaning. The khabariyyah is that in which the speaker may be described as truthful or lying — its content can be tested against reality, e.g. إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ. The inshāʾiyyah is that in which the speaker can be described as neither truthful nor lying, because it creates rather than reports a meaning; its categories include interrogation, wishing, calling, command, prohibition, etc., e.g. أَإِلَهٌ مَعَ اللهِ (istifhām) and أَقِيمُوا الصَّلَاةَ (amr). Breakdown: 3 marks for the defining criterion of khabariyyah (admits truth/falsehood) with example; 3 marks for the defining criterion of inshāʾiyyah (admits neither) with example; 2 marks for clearly contrasting the two."
  },
  {
    "id": "muq-bab-2--compare--explain-with-examples-the-differ-1x",
    "chapterId": "muq-bab-2",
    "chapterAr": "الباب الثاني في الجملة وشبه الجملة والكلام",
    "chapterEn": "Sentence, quasi-sentence & speech",
    "archetype": "compare",
    "marks": 8,
    "promptEn": "Explain, with examples, the difference between aẓ-ẓarf al-laghw and aẓ-ẓarf al-mustaqarru fīh.",
    "promptAr": "",
    "markScheme": "Model answer: Both are divisions of shibh al-jumlah by its governor (ʿāmil). (1) Aẓ-ẓarf al-laghw: a quasi-sentence whose governor is either mentioned (madhkūr), e.g. لَقَدْ أَرْسَلْنَا نُوحًا إِلَى قَوْمِهِ (governor أَرْسَلْنَا stated), or omitted but a specific/particular verb (maḥdhūf makhṣūṣ), e.g. وَإِلَى عَادٍ أَخَاهُمْ هُودًا, i.e. أَرْسَلْنَا. (2) Aẓ-ẓarf al-mustaqarru fīh: a quasi-sentence whose governor is omitted and general (maḥdhūf ʿāmm) — a word denoting mere existence such as استقرّ/ثبت/وُجد — e.g. إِنَّكَ عَلَى صِرَاطٍ مُسْتَقِيمٍ, i.e. ثَابِتٌ. The key contrast: laghw has a mentioned or specific omitted governor; mustaqarr always has an omitted general governor of existence. Breakdown: 3 marks for laghw (mentioned / specific omitted) with example; 3 marks for mustaqarr (omitted general governor of existence) with example; 2 marks for the explicit contrast."
  },
  {
    "id": "muq-bab-2--explain-statement--explain-the-following-statement--1z",
    "chapterId": "muq-bab-2",
    "chapterAr": "الباب الثاني في الجملة وشبه الجملة والكلام",
    "chapterEn": "Sentence, quasi-sentence & speech",
    "archetype": "explain-statement",
    "marks": 15,
    "promptEn": "Explain the following statement as fully as possible, with examples.",
    "promptAr": "الْغَالِبُ فِي عَامِلِ الظَّرْفِ اللَّغْوِ أَنْ يُذْكَرَ، وَيَجِبُ حَذْفُهُ فِي مَوَاضِعَ",
    "markScheme": "Model answer: The governor (ʿāmil) of aẓ-ẓarf al-laghw is most commonly mentioned (madhkūr), as in لَقَدْ أَرْسَلْنَا نُوحًا إِلَى قَوْمِهِ. However, in certain places its omission is obligatory (yajib ḥadhfuhu). These are four: (1) al-amthāl — proverbs, e.g. الْكِلَابُ عَلَى الْبَقَرِ; (2) al-ʿibārāt al-maʾthūrah — transmitted/set expressions, e.g. بِأَبِي أَنْتَ وَأُمِّي, i.e. أَنْتَ مَفْدِيٌّ بِأَبِي وَأُمِّي; (3) al-qasam bi-ghayr al-bāʾ — an oath with other than the bāʾ, e.g. تَاللهِ تَفْتَأُ تَذْكُرُ يُوسُفَ; (4) khabar kāna with lām al-juḥūd (the lām of denial), e.g. مَا كَانَ اللهُ لِيُعَذِّبَهُمْ وَأَنْتَ فِيهِمْ, i.e. قَاصِدًا لِيُعَذِّبَهُمْ. Breakdown: 3 marks for the general principle (governor usually mentioned, sometimes obligatorily omitted); 3 marks for each of the four places correctly named with its example (3×4 = 12 available, capped so total = 15). Award up to 3 per place: name (1) + example (1) + brief explanation (1); cap overall at 15."
  },
  {
    "id": "muq-bab-2--explain-statement--explain-the-following-statement--21",
    "chapterId": "muq-bab-2",
    "chapterAr": "الباب الثاني في الجملة وشبه الجملة والكلام",
    "chapterEn": "Sentence, quasi-sentence & speech",
    "archetype": "explain-statement",
    "marks": 15,
    "promptEn": "Explain the following statement as fully as possible, with examples, including the forms the omitted governor may take and the places in which this quasi-sentence occurs.",
    "promptAr": "الظَّرْفُ الْمُسْتَقَرُّ فِيهِ هُوَ شِبْهُ جُمْلَةٍ عَامِلُهَا مَحْذُوفٌ عَامٌّ",
    "markScheme": "Model answer: Aẓ-ẓarf al-mustaqarru fīh is a quasi-sentence whose governor is omitted and general (maḥdhūf ʿāmm) — i.e. a word denoting mere existence such as استقرّ، وُجد، ثبت — e.g. إِنَّكَ عَلَى صِرَاطٍ مُسْتَقِيمٍ, i.e. تَثْبُتُ / ثَابِتٌ. The omitted governor may take two forms: (a) a verb, e.g. اسْتَقَرَّ، ثَبَتَ، وُجِدَ، يَكُونُ; or (b) a noun with the sense of the verb, e.g. مُسْتَقِرٌّ، ثَابِتٌ، مَوْجُودٌ، كَائِنٌ — except in the ṣilah (relative clause), where it must be a verb only, e.g. الَّذِي فِي مَكَّةَ, i.e. اسْتَقَرَّ. It occurs in five places: (1) the khabar and what is in its ruling — وَهُوَ عَلَى صِرَاطٍ مُسْتَقِيمٍ; (2) the ḥāl — فَخَرَجَ عَلَى قَوْمِهِ فِي زِينَتِهِ; (3) the naʿt — أُولَئِكَ عَلَى هُدًى مِنْ رَبِّهِمْ; (4) the ṣilah — وَلَهُ مَنْ فِي السَّمَاوَاتِ وَالْأَرْضِ; (5) al-iʿtimād (dependence) — أَفِي اللهِ شَكٌّ. Breakdown: 3 marks for the definition (omitted general governor of existence) with example; 3 marks for the two forms (verb / noun in verb's sense) plus the ṣilah exception; 5 marks for naming the five places (1 each); 4 marks for supplying correct examples across the places. Cap total at 15."
  },
  {
    "id": "muq-bab-2--define-types-examples--what-is-shibh-al-jumlah-the-quas-23",
    "chapterId": "muq-bab-2",
    "chapterAr": "الباب الثاني في الجملة وشبه الجملة والكلام",
    "chapterEn": "Sentence, quasi-sentence & speech",
    "archetype": "define-types-examples",
    "marks": 15,
    "promptEn": "What is shibh al-jumlah (the quasi-sentence)? What are its types (by form and by governor)? Give examples.",
    "promptAr": "",
    "markScheme": "Model answer: Shibh al-jumlah is an expression that resembles a sentence but is not a full one, divided in two respects. (A) By its form (hayʾah), two kinds: (1) al-jārr wa-l-majrūr — e.g. فِي مَكَّةَ; (2) aẓ-ẓarf wa-l-muḍāf ilayh — e.g. عِنْدَ الْكَعْبَةِ. (B) By its governor (ʿāmil) — noting its governor is called the mutaʿallaq and the shibh al-jumlah itself the mutaʿalliq — two kinds: (1) aẓ-ẓarf al-laghw, whose governor is mentioned (e.g. لَقَدْ أَرْسَلْنَا نُوحًا إِلَى قَوْمِهِ) or specifically omitted (e.g. وَإِلَى عَادٍ أَخَاهُمْ هُودًا, i.e. أَرْسَلْنَا); (2) aẓ-ẓarf al-mustaqarru fīh, whose governor is omitted and general (e.g. إِنَّكَ عَلَى صِرَاطٍ مُسْتَقِيمٍ, i.e. ثَابِتٌ). Breakdown: 3 marks for a sound description of shibh al-jumlah and the two-respects framework; 4 marks for the two form-types with examples (2 each); 4 marks for the two governor-types with examples (2 each); 2 marks for the mutaʿallaq/mutaʿalliq terminology; 2 marks for overall accuracy/coverage. Cap at 15."
  },
  {
    "id": "muq-bab-2--enumerate--enumerate-the-categories-of-the--25",
    "chapterId": "muq-bab-2",
    "chapterAr": "الباب الثاني في الجملة وشبه الجملة والكلام",
    "chapterEn": "Sentence, quasi-sentence & speech",
    "archetype": "enumerate",
    "marks": 12,
    "promptEn": "Enumerate the categories of the performative sentence (al-jumlah al-inshāʾiyyah) mentioned in the chapter, giving for each a brief identification and an example.",
    "promptAr": "",
    "markScheme": "Model answer (the eleven categories with examples): (1) al-istifhām (interrogation) — أَإِلَهٌ مَعَ اللهِ; (2) at-tamannī (wishing) — يَا لَيْتَ قَوْمِي يَعْلَمُونَ; (3) an-nidāʾ (calling) — يَا أَيُّهَا الرَّسُولُ; (4) at-taḥdhīr (warning) — نَاقَةَ اللهِ وَسُقْيَاهَا; (5) al-ighrāʾ (incitement) — الْعِلْمَ الْعِلْمَ; (6) al-amr (command) — وَأَقِيمُوا الصَّلَاةَ; (7) an-nahy (prohibition) — وَلَا تَقْرَبُوا الْفَوَاحِشَ; (8) ad-duʿāʾ (supplication) — سَلَامٌ عَلَيْكُمْ; (9) ṣiyagh al-madḥ wa-dh-dhamm (forms of praise/blame) — وَلَنِعْمَ دَارُ الْمُتَّقِينَ; (10) ṣiyagh at-tawajjuʿ wa-t-tafajjuʿ (lamentation/grief) — يَا حَسْرَتَا عَلَى مَا فَرَّطْتُ فِي جَنْبِ اللهِ; (11) al-qasam (oath) — وَالْعَصْرِ. Breakdown: 11 marks — approx. 1 mark per category correctly named with a fitting example (accept the chapter examples); +1 mark for completeness/correct framing as inshāʾiyyah. Deduct for items invented outside the chapter list. Cap at 12."
  },
  {
    "id": "muq-bab-2--classify-tarkib--classify-the-category-noun-verb--27",
    "chapterId": "muq-bab-2",
    "chapterAr": "الباب الثاني في الجملة وشبه الجملة والكلام",
    "chapterEn": "Sentence, quasi-sentence & speech",
    "archetype": "classify-tarkib",
    "marks": 9,
    "promptEn": "Classify the category (noun / verb / particle) of the word شَكٌّ in the sentence below; then translate the sentence and give its full tarkīb (iʿrāb).",
    "promptAr": "أَفِي اللهِ شَكٌّ",
    "markScheme": "Model answer: Classification — شَكٌّ is an ism (noun). Translation — 'Is there any doubt about Allah?'. Tarkīb: الهمزة (أ) — hamzat al-istifhām, ḥarf, no place in iʿrāb; فِي — ḥarf jarr; اللهِ — lafẓ al-jalālah, majrūr by فِي, sign is the kasrah; the jārr wa-majrūr فِي اللهِ is shibh jumlah (aẓ-ẓarf al-mustaqarru fīh, here in the place of iʿtimād / khabar muqaddam), its general governor omitted (i.e. كائن/موجود); شَكٌّ — mubtadaʾ muʾakhkhar, marfūʿ, sign is the ḍammah (tanwīn). The sentence is a jumlah ismiyyah (inshāʾiyyah – istifhām). Breakdown: 2 marks for correctly classifying شَكٌّ as a noun; 2 marks for an accurate translation; 5 marks for the iʿrāb — 1 for the hamzat al-istifhām, 1 for فِي as ḥarf jarr, 1 for اللهِ majrūr, 1 for identifying the jārr-majrūr as shibh jumlah / khabar muqaddam (iʿtimād), 1 for شَكٌّ as mubtadaʾ muʾakhkhar marfūʿ."
  },
  {
    "id": "muq-bab-3--explain-line--explain-the-following-line-of-th-n",
    "chapterId": "muq-bab-3",
    "chapterAr": "الباب الثالث في العامل والمعمول والإعراب",
    "chapterEn": "Governor, governed & iʿrāb",
    "archetype": "explain-line",
    "marks": 5,
    "promptEn": "Explain the following line of the matn, which defines the governor (al-ʿāmil).",
    "promptAr": "فَالْعَامِلُ مَا يُوجِبُ حَالَةً، نَحْوُ «لَنْ» فِي قَوْلِهِ تَعَالَى: وَلَنْ نُشْرِكَ بِرَبِّنَا أَحَدًا",
    "markScheme": "Model answer: The ʿāmil (governor) is that which necessitates/brings about a grammatical state (ḥālah) in another word, i.e. it makes a word take a particular iʿrāb. The example is «لَنْ»: it is a naṣb-particle that necessitates the naṣb of the muḍāriʿ «نُشْرِكَ» (note the fatḥah). So «لَنْ» governs and the verb is what receives the state. Breakdown: definition of ʿāmil as 'what necessitates a state' (2); linking 'state' to iʿrāb effect on another word (1); identifying لن as the ʿāmil necessitating naṣb in نُشْرِكَ (2)."
  },
  {
    "id": "muq-bab-3--explain-line--explain-the-following-line-of-th-p",
    "chapterId": "muq-bab-3",
    "chapterAr": "الباب الثالث في العامل والمعمول والإعراب",
    "chapterEn": "Governor, governed & iʿrāb",
    "archetype": "explain-line",
    "marks": 5,
    "promptEn": "Explain the following line of the matn, which defines iʿrāb.",
    "promptAr": "وَهُوَ أَثَرٌ يَجْلِبُهُ الْعَامِلُ فِي آخِرِ الْكَلِمَةِ",
    "markScheme": "Model answer: Iʿrāb is an effect (athar) — i.e. a change of the ending — that the governor (ʿāmil) brings about (yajlibu) at the end (ākhir) of the word. Three elements: (a) it is an effect/sign, not the letter itself; (b) its cause is the ʿāmil; (c) its locus is the final part of the word. E.g. the ḍammah on «الْمُؤْمِنُ» brought by the rāfiʿ. Breakdown: athar = effect at word-end (2); caused by the ʿāmil (2); located at the end of the word (1)."
  },
  {
    "id": "muq-bab-3--explain-line--explain-the-following-line-of-th-r",
    "chapterId": "muq-bab-3",
    "chapterAr": "الباب الثالث في العامل والمعمول والإعراب",
    "chapterEn": "Governor, governed & iʿrāb",
    "archetype": "explain-line",
    "marks": 5,
    "promptEn": "Explain the following line of the matn, which defines the governed (al-maʿmūl).",
    "promptAr": "الْمَعْمُولُ مَا يَقْبَلُ حَالَةً وَيَكُونُ لَهُ إِعْرَابٌ، نَحْوُ «صَاحِبٌ» فِي قَوْلِهِ تَعَالَى: مَا ضَلَّ صَاحِبُكُمْ",
    "markScheme": "Model answer: The maʿmūl (governed) is that which accepts a grammatical state and has iʿrāb (a varying ending). Example: «صَاحِبُكُمْ» — it accepts the state of rafʿ as fāʿil and so carries a ḍammah; it is the word acted upon by the ʿāmil (here ضَلَّ). Breakdown: maʿmūl accepts a ḥālah (2); it possesses iʿrāb (1); correct identification of صَاحِب as the governed word taking rafʿ (2)."
  },
  {
    "id": "muq-bab-3--state-types--state-the-divisions-aqs-m-of-i-r-t",
    "chapterId": "muq-bab-3",
    "chapterAr": "الباب الثالث في العامل والمعمول والإعراب",
    "chapterEn": "Governor, governed & iʿrāb",
    "archetype": "state-types",
    "marks": 6,
    "promptEn": "State the divisions (aqsām) of iʿrāb. For each one give a recognising sign/feature by which it is identified.",
    "promptAr": "",
    "markScheme": "Model answer — iʿrāb is three divisions: (1) al-lafẓī (overt) — sign: the ʿalāmah actually appears in pronunciation, e.g. ḍammah/kasrah in «يَجْتَهِدُ الْمُؤْمِنُ فِي الْخَيْرِ». (2) at-taqdīrī (estimated) — sign: the ʿalāmah is prevented from appearing by an impediment (māniʿ) on a maqṣūr/manqūṣ word, e.g. estimated ḍammah/kasrah in «يَسْعَى الْفَتَى إِلَى الْهُدَى». (3) al-maḥallī (positional) — sign: the word is a mabnī that cannot bear any iʿrāb mark, so the iʿrāb is assigned to its position, e.g. «تَسْعَيْنَ أَنْتُنَّ إِلَيْهِ». Breakdown: 2 marks per type (1 for naming/defining + 1 for its recognising sign/example)."
  },
  {
    "id": "muq-bab-3--compare--explain-with-examples-the-differ-v",
    "chapterId": "muq-bab-3",
    "chapterAr": "الباب الثالث في العامل والمعمول والإعراب",
    "chapterEn": "Governor, governed & iʿrāb",
    "archetype": "compare",
    "marks": 8,
    "promptEn": "Explain, with examples, the difference between al-ʿāmil (the governor) and al-maʿmūl (the governed).",
    "promptAr": "",
    "markScheme": "Model answer: The ʿāmil is what necessitates a grammatical state in another word (it acts); it comprises all verbs, some particles and some nouns — e.g. «لَنْ» in «لَنْ نُشْرِكَ» necessitating naṣb. The maʿmūl is what accepts that state and consequently has iʿrāb (it is acted upon); it comprises all nouns except asmāʾ al-fiʿl, the muḍāriʿ, the māḍī entered by a nāṣib/jāzim, part of sentences, and all quasi-sentences — e.g. «صَاحِبُكُمْ» taking rafʿ in «مَا ضَلَّ صَاحِبُكُمْ». Key contrast: ʿāmil = cause/actor; maʿmūl = recipient/object of the action. Breakdown: define ʿāmil (2); define maʿmūl (2); state the cause-vs-recipient relationship (2); a correct example of each (2)."
  },
  {
    "id": "muq-bab-3--compare--explain-with-examples-the-differ-x",
    "chapterId": "muq-bab-3",
    "chapterAr": "الباب الثالث في العامل والمعمول والإعراب",
    "chapterEn": "Governor, governed & iʿrāb",
    "archetype": "compare",
    "marks": 8,
    "promptEn": "Explain, with examples, the difference between al-iʿrāb at-taqdīrī (estimated iʿrāb) and al-iʿrāb al-maḥallī (positional iʿrāb).",
    "promptAr": "",
    "markScheme": "Model answer: Both share that the iʿrāb sign does not appear in the utterance, but the reason differs. In at-taqdīrī the word IS capable of bearing the mark, yet a māniʿ (impediment, e.g. the final alif/yāʾ of a maqṣūr or manqūṣ) prevents it, so the mark is 'estimated' on the letter — e.g. estimated ḍammah on «الْفَتَى» and kasrah on «الْهُدَى» in «يَسْعَى الْفَتَى إِلَى الْهُدَى». In al-maḥallī the word is mabnī and inherently CANNOT bear any iʿrāb mark, so iʿrāb is attributed to its grammatical position (maḥall) — e.g. «تَسْعَيْنَ أَنْتُنَّ إِلَيْهِ». Breakdown: shared feature (non-appearance) (1); taqdīrī = impediment though capable + example (3); maḥallī = inability of mabnī word + position + example (3); explicit statement of the contrasting cause (1)."
  },
  {
    "id": "muq-bab-3--explain-statement--explain-the-following-statement--z",
    "chapterId": "muq-bab-3",
    "chapterAr": "الباب الثالث في العامل والمعمول والإعراب",
    "chapterEn": "Governor, governed & iʿrāb",
    "archetype": "explain-statement",
    "marks": 15,
    "promptEn": "Explain the following statement as fully as possible, with examples.",
    "promptAr": "وَهُوَ أَثَرٌ يَجْلِبُهُ الْعَامِلُ فِي آخِرِ الْكَلِمَةِ، وَهُوَ ثَلَاثَةُ أَقْسَامٍ: الْإِعْرَابُ اللَّفْظِيُّ، وَالْإِعْرَابُ التَّقْدِيرِيُّ، وَالْإِعْرَابُ الْمَحَلِّيُّ",
    "markScheme": "Model answer: Definition — iʿrāb is an effect (athar) brought about by the ʿāmil at the end of the word; its cause is the governor, its locus the word-ending, and it is the changing of the ending according to the governing factor. It has three divisions: (1) al-lafẓī (overt): the sign appears in pronunciation, e.g. the visible ḍammah on «الْمُؤْمِنُ» and kasrah on «الْخَيْرِ» in «يَجْتَهِدُ الْمُؤْمِنُ فِي الْخَيْرِ». (2) at-taqdīrī (estimated): the sign does not appear due to an impediment, though the word could bear it, e.g. the estimated ḍammah on «الْفَتَى» and kasrah on «الْهُدَى» in «يَسْعَى الْفَتَى إِلَى الْهُدَى». (3) al-maḥallī (positional): the sign does not appear because a mabnī word cannot bear it, so iʿrāb is given to its position, e.g. «تَسْعَيْنَ أَنْتُنَّ إِلَيْهِ». One may add what receives iʿrāb: all nouns, some verbs, sentences partly, quasi-sentences fully — never particles. Breakdown: explain the definition fully (athar / by ʿāmil / at word-end) (3); each of the three divisions defined with example (3×3 = 9); overall coherence + correct examples / note on what takes iʿrāb (3)."
  },
  {
    "id": "muq-bab-3--define-types-examples--what-is-i-r-b-what-are-its-types-11",
    "chapterId": "muq-bab-3",
    "chapterAr": "الباب الثالث في العامل والمعمول والإعراب",
    "chapterEn": "Governor, governed & iʿrāb",
    "archetype": "define-types-examples",
    "marks": 15,
    "promptEn": "What is iʿrāb? What are its types? Give examples of each.",
    "promptAr": "",
    "markScheme": "Model answer: Definition — iʿrāb is an effect (athar) brought about by the ʿāmil at the end of the word (the change of the word-ending caused by the governor). Types (three): (1) al-iʿrāb al-lafẓī — overt iʿrāb that appears in the utterance, e.g. ḍammah/kasrah in «يَجْتَهِدُ الْمُؤْمِنُ فِي الْخَيْرِ». (2) al-iʿrāb at-taqdīrī — estimated iʿrāb that does not appear because of an impediment, e.g. estimated ḍammah/kasrah in «يَسْعَى الْفَتَى إِلَى الْهُدَى». (3) al-iʿrāb al-maḥallī — positional iʿrāb that does not appear because the word (mabnī) cannot bear the sign, so it is assigned to its position, e.g. «تَسْعَيْنَ أَنْتُنَّ إِلَيْهِ». Breakdown: correct definition (3); naming all three types (3); definition of each (3); a correct example for each (6 — 2 each)."
  },
  {
    "id": "muq-bab-3--classify-tarkib--for-the-sentence-below-a-classif-13",
    "chapterId": "muq-bab-3",
    "chapterAr": "الباب الثالث في العامل والمعمول والإعراب",
    "chapterEn": "Governor, governed & iʿrāb",
    "archetype": "classify-tarkib",
    "marks": 9,
    "promptEn": "For the sentence below: (a) classify the category of each main word (ism / fiʿl / ḥarf); (b) translate the sentence; (c) give its tarkīb / iʿrāb, naming the type of iʿrāb each word carries.",
    "promptAr": "يَجْتَهِدُ الْمُؤْمِنُ فِي الْخَيْرِ",
    "markScheme": "Model answer: (a) «يَجْتَهِدُ» fiʿl muḍāriʿ; «الْمُؤْمِنُ» ism; «فِي» ḥarf jarr; «الْخَيْرِ» ism. (b) Translation: 'The believer strives in (doing) good.' (c) Iʿrāb: «يَجْتَهِدُ» fiʿl muḍāriʿ marfūʿ, sign = ḍammah ẓāhirah (lafẓī); «الْمُؤْمِنُ» fāʿil marfūʿ, ḍammah ẓāhirah (lafẓī); «فِي» ḥarf jarr mabnī; «الْخَيْرِ» ism majrūr by فِي, kasrah ẓāhirah (lafẓī) — the jārr + majrūr forms a shibh al-jumlah. This is an example of overt (lafẓī) iʿrāb. Breakdown: correct word classification (3); accurate translation (2); iʿrāb of each word with iʿrāb-type identified as lafẓī (4)."
  },
  {
    "id": "muq-bab-3--classify-tarkib--for-the-sentence-below-a-classif-15",
    "chapterId": "muq-bab-3",
    "chapterAr": "الباب الثالث في العامل والمعمول والإعراب",
    "chapterEn": "Governor, governed & iʿrāb",
    "archetype": "classify-tarkib",
    "marks": 9,
    "promptEn": "For the sentence below: (a) classify the category of each main word (ism / fiʿl / ḥarf); (b) translate the sentence; (c) give its tarkīb / iʿrāb, stating which type of iʿrāb (lafẓī / taqdīrī / maḥallī) each word carries and why.",
    "promptAr": "يَسْعَى الْفَتَى إِلَى الْهُدَى",
    "markScheme": "Model answer: (a) «يَسْعَى» fiʿl muḍāriʿ; «الْفَتَى» ism (maqṣūr); «إِلَى» ḥarf jarr; «الْهُدَى» ism (maqṣūr). (b) Translation: 'The youth strives toward guidance.' (c) Iʿrāb: «يَسْعَى» fiʿl muḍāriʿ marfūʿ with an estimated ḍammah (taqdīrī) — prevented by the final alif; «الْفَتَى» fāʿil marfūʿ, estimated ḍammah (taqdīrī) — māniʿ of the maqṣūr alif; «إِلَى» ḥarf jarr mabnī; «الْهُدَى» ism majrūr by إِلَى with an estimated kasrah (taqdīrī) — also a maqṣūr, the jārr+majrūr = shibh al-jumlah. This illustrates estimated (taqdīrī) iʿrāb. Breakdown: correct classification (3); accurate translation (2); iʿrāb with taqdīrī identified and impediment explained (4)."
  },
  {
    "id": "m1-muq--explain-line--explain-the-following-line-of-th-0",
    "chapterId": "m1-muq",
    "chapterAr": "المقدمة",
    "chapterEn": "Introduction (Aim One)",
    "archetype": "explain-line",
    "marks": 5,
    "promptEn": "Explain the following line of the matn fully, making clear what category of word it concerns and what is being affirmed of it.",
    "promptAr": "الْأَوَّلُ: الْأَفْعَالُ كُلُّهَا عَامِلَةٌ",
    "markScheme": "Model answer: This is the first of the five principles (mabādiʾ) of the Introduction. It states that the verbs (الأفعال), in their entirety — every one of them without exception (note كُلُّهَا, 'all of them') — are governing words (عاملة), i.e. each verb exercises ʿamal (grammatical government) over what comes after it, causing raf‘/naṣb/jarr in the words it governs. There is no verb that is non-governing. Breakdown: identifying it as the first mabdaʾ (1); that the subject is الأفعال = verbs (1); that كُلُّها means 'all/every one without exception' (1); that عاملة = it governs / exercises ʿamal (1); the point that NO verb is exempt — all verbs govern (1)."
  },
  {
    "id": "m1-muq--explain-line--explain-the-following-line-of-th-2",
    "chapterId": "m1-muq",
    "chapterAr": "المقدمة",
    "chapterEn": "Introduction (Aim One)",
    "archetype": "explain-line",
    "marks": 5,
    "promptEn": "Explain the following line of the matn, making clear the meaning of the key term and what is denied of it.",
    "promptAr": "الْخَامِسُ: شِبْهُ الْجُمْلَةِ كُلُّهَا غَيْرُ عَامِلَةٍ",
    "markScheme": "Model answer: This is the fifth principle. شِبْهُ الْجُمْلَةِ (the 'quasi-sentence' — i.e. the ظرف and the جار ومجرور) is, in its entirety (كُلُّهَا), غَيْرُ عَامِلَةٍ — non-governing; it does not exercise ʿamal over other words. No type of shibh al-jumlah governs. Breakdown: identifying it as the fifth mabdaʾ (1); شبه الجملة = quasi-sentence (1); كُلُّها = the whole of it / every kind (1); غير عاملة = does not govern (1); the totality point — none of it governs (1)."
  },
  {
    "id": "m1-muq--explain-line--explain-what-this-opening-line-t-4",
    "chapterId": "m1-muq",
    "chapterAr": "المقدمة",
    "chapterEn": "Introduction (Aim One)",
    "archetype": "explain-line",
    "marks": 5,
    "promptEn": "Explain what this opening line tells the student about the structure of what follows.",
    "promptAr": "وَفِيهَا خَمْسَةُ مَبَادِئَ",
    "markScheme": "Model answer: Spoken of the Introduction (المقدمة), this line states that within it (فِيهَا, the feminine pronoun referring back to المقدمة) there are five mabādiʾ — five foundational principles laid down before the four chapters and conclusion. مَبَادِئُ is the plural of مَبْدَأٌ (a starting-point/principle). Breakdown: فيها refers to المقدمة (1); خمسة = five (1); مبادئ = principles, plural of مبدأ (1); meaning of mabdaʾ as a foundational starting-point (1); that these precede the abwāb (chapters) as preliminaries (1)."
  },
  {
    "id": "m1-muq--compare--explain-with-examples-the-differ-8",
    "chapterId": "m1-muq",
    "chapterAr": "المقدمة",
    "chapterEn": "Introduction (Aim One)",
    "archetype": "compare",
    "marks": 8,
    "promptEn": "Explain, with examples, the difference between a word that is عامِلة (governing) and one that is غير عامِلة (non-governing).",
    "promptAr": "",
    "markScheme": "Model answer: A عامِلة word is one that exercises ʿamal — it has a grammatical effect on the word(s) following it, producing a particular iʿrāb (raf‘, naṣb or jarr). According to the mabādiʾ, all verbs are of this kind, as are SOME particles and SOME nouns — e.g. a verb governs its faaʿil/maf‘ūl, a governing particle like an inflecting ḥarf affects what follows. A غير عامِلة word has no such effect; the structures called الجملة and شبه الجملة are wholly non-governing, and likewise SOME particles and SOME nouns. The dividing line is the presence or absence of ʿamal (grammatical government). Breakdown: definition of عاملة as exercising ʿamal/changing iʿrāb (2); definition of غير عاملة as having no such effect (2); correct examples of each drawn from the mabādiʾ — all verbs / some particles / some nouns vs jumlah & shibh jumlah / some particles / some nouns (2); clearly stating the criterion of distinction (2)."
  },
  {
    "id": "m1-muq--compare--explain-with-reference-to-the-ma-a",
    "chapterId": "m1-muq",
    "chapterAr": "المقدمة",
    "chapterEn": "Introduction (Aim One)",
    "archetype": "compare",
    "marks": 8,
    "promptEn": "Explain, with reference to the mabādiʾ, the difference between the verbs (الأفعال) and the nouns (الأسماء) with respect to government (العمل).",
    "promptAr": "",
    "markScheme": "Model answer: With respect to ʿamal the mabādiʾ treat the two categories differently. The first principle states الأفعال كلها عاملة — the verbs are governing words UNIVERSALLY: every verb without exception exercises ʿamal (note كُلُّها). The third principle states الأسماء بعضها عاملة وبعضها غير عاملة — the nouns are governing only PARTIALLY: some nouns govern (e.g. a noun that acts as an ʿāmil) while others do not. So the contrast is totality vs partiality: 'all verbs govern' versus 'only some nouns govern'. Breakdown: stating the verbs' principle (كلها عاملة) with meaning (2); stating the nouns' principle (بعضها عاملة وبعضها غير) with meaning (2); drawing out the key contrast of كُلّ (all) vs بعض (some) (2); accurate examples / illustration of governing vs non-governing instances (2)."
  },
  {
    "id": "m1-muq--explain-statement--explain-the-following-principle--c",
    "chapterId": "m1-muq",
    "chapterAr": "المقدمة",
    "chapterEn": "Introduction (Aim One)",
    "archetype": "explain-statement",
    "marks": 15,
    "promptEn": "Explain the following principle as fully as possible, with examples, clarifying why the particles are treated differently from the verbs.",
    "promptAr": "الثَّانِي: الْحُرُوفُ بَعْضُهَا عَامِلَةٌ، وَبَعْضُهَا غَيْرُ عَامِلَةٍ",
    "markScheme": "Model answer: This is the second mabdaʾ. Unlike the verbs (first principle: الأفعال كلها عاملة), the particles (الحروف) are split: بَعْضُهَا عَامِلَةٌ — some of them are governing, exercising ʿamal on what follows them and effecting a particular iʿrāb; وَبَعْضُهَا غَيْرُ عَامِلَةٍ — and some of them are non-governing, having no grammatical effect. So the qualifier here is بعض (some), not كُلّ (all): government is not universal among particles. The word بعض is repeated to mark a genuine two-way division of the category. Examples: a governing particle (ḥarf ʿāmil) imposes its iʿrāb on the following word, whereas a non-governing particle (such as a mere connective/answer particle) leaves the following word as it is. Breakdown: identifying it as the second principle (2); الحروف = particles (1); بعضها عاملة = some govern, with explanation of ʿamal/effect on iʿrāb (3); بعضها غير عاملة = some do not govern (3); the significance of بعض vs كُلّ — partial not universal (2); contrast with verbs being wholly governing (2); supporting examples of governing and non-governing particles (2)."
  },
  {
    "id": "m1-muq--explain-statement--explain-the-following-two-princi-e",
    "chapterId": "m1-muq",
    "chapterAr": "المقدمة",
    "chapterEn": "Introduction (Aim One)",
    "archetype": "explain-statement",
    "marks": 15,
    "promptEn": "Explain the following two principles together as fully as possible, with examples, clarifying what is meant by الجملة and شبه الجملة and why both are said not to govern.",
    "promptAr": "الرَّابِعُ: الْجُمْلَةُ كُلُّهَا غَيْرُ عَامِلَةٍ — الْخَامِسُ: شِبْهُ الْجُمْلَةِ كُلُّهَا غَيْرُ عَامِلَةٍ",
    "markScheme": "Model answer: These are the fourth and fifth mabādiʾ, and they pair together because both deny ʿamal of a whole class of structures. الجُملة (the sentence — whether ismiyya or fi‘liyya) is, in its entirety (كُلُّها), غير عاملة: as a complete structure it does not itself act as a governing word over other words. شِبه الجُملة (the quasi-sentence — the ظرف and the جار ومجرور) is likewise كُلُّها غير عاملة: none of it governs. The key word in both is كُلّ ('all/the whole of'), marking a UNIVERSAL denial — there is no governing jumlah and no governing shibh jumlah, in contrast to the particles and nouns where only بعض (some) govern. Breakdown: identifying them as the fourth and fifth principles (2); meaning of الجملة, with the sentence types (2); meaning of شبه الجملة as ظرف and جار ومجرور (3); كلها غير عاملة = the whole class does not govern, for each (4); the force of كُلّ as universal denial (2); contrast with the partial (بعض) cases of particles/nouns (2)."
  },
  {
    "id": "m1-muq--define-types-examples--using-the-five-mab-di-of-the-int-g",
    "chapterId": "m1-muq",
    "chapterAr": "المقدمة",
    "chapterEn": "Introduction (Aim One)",
    "archetype": "define-types-examples",
    "marks": 15,
    "promptEn": "Using the five mabādiʾ of the Introduction, explain how words and structures are divided with respect to government (العمل). What are the categories, which fall under each, and give examples.",
    "promptAr": "",
    "markScheme": "Model answer: ʿAmal (government) is a word's grammatical effect upon what follows it, producing a definite iʿrāb. The mabādiʾ classify five categories by whether they exercise ʿamal: (a) العاملة دائماً (always governing): the verbs (الأفعال كلها عاملة) — every verb governs, e.g. a verb governing its subject/object. (b) ما بعضه عامل (partly governing): the particles (الحروف بعضها عاملة وبعضها غير) and the nouns (الأسماء بعضها عاملة وبعضها غير) — some members govern, some do not. (c) غير العاملة دائماً (never governing): the sentence (الجملة كلها غير عاملة) and the quasi-sentence — ظرف and جار ومجرور — (شبه الجملة كلها غير عاملة), neither of which governs. The organising criterion throughout is كُلّ (all) vs بعض (some): universal for verbs (all govern) and for jumal/shibh jumal (none govern), but partial for particles and nouns. Breakdown: defining ʿamal (2); the verbs category — all govern, with example (3); the particles & nouns category — some govern, some not (3); the jumla category — none govern (2); the shibh jumla category — ظرف & جار ومجرور, none govern (3); drawing out the كُلّ/بعض organising principle (2)."
  },
  {
    "id": "m1-muq--enumerate--list-the-five-principles-mab-di--6",
    "chapterId": "m1-muq",
    "chapterAr": "المقدمة",
    "chapterEn": "Introduction (Aim One)",
    "archetype": "enumerate",
    "marks": 12,
    "promptEn": "List the five principles (mabādiʾ) of the Introduction in order, stating for each one what it affirms or denies.",
    "promptAr": "",
    "markScheme": "Model answer (the five mabādiʾ): (1) الأول — الأفعال كلها عاملة: the verbs, all of them, govern. (2) الثاني — الحروف بعضها عاملة وبعضها غير عاملة: the particles, some of them govern and some do not. (3) الثالث — الأسماء بعضها عاملة وبعضها غير عاملة: the nouns, some govern and some do not. (4) الرابع — الجملة كلها غير عاملة: the sentence, all of it, does not govern. (5) الخامس — شبه الجملة كلها غير عاملة: the quasi-sentence, all of it, does not govern. Breakdown: 2 marks per principle correctly stated with its ḥukm (10 marks total), plus 2 marks for correct order/numbering = 12. Deduct for any principle whose 'all / some' qualifier is wrong."
  },
  {
    "id": "m1-muq--classify-tarkib--classify-the-word-in-the-sentenc-i",
    "chapterId": "m1-muq",
    "chapterAr": "المقدمة",
    "chapterEn": "Introduction (Aim One)",
    "archetype": "classify-tarkib",
    "marks": 9,
    "promptEn": "Classify the word كُلُّ in the sentence below by its word-category (kind of kalima). Then translate the sentence and give its full tarkīb / iʿrāb.",
    "promptAr": "الْأَفْعَالُ كُلُّهَا عَامِلَةٌ",
    "markScheme": "Model answer — Classification: كُلّ is an اسم (noun); here it functions as a tawkīd ma‘nawī (word of corroboration) and is in construct (muḍāf) to the pronoun ها. Translation: 'The verbs, all of them, are governing (words).' Tarkīb/iʿrāb: الْأَفْعَالُ — mubtadaʾ, marfū‘, sign of raf‘ the ḍamma; كُلُّ — tawkīd ma‘nawī of الأفعال, following it in raf‘ (marfū‘ bi-l-ḍamma) and muḍāf; ها — ḍamīr muttaṣil in maḥall jarr, muḍāf ilayh; عَامِلَةٌ — khabar of the mubtadaʾ, marfū‘, sign of raf‘ the ḍamma; and the jumla is ismiyya. Breakdown: correctly classifying كُلّ as a noun / tawkīd (2); accurate translation (2); iʿrāb of الأفعال as mubtadaʾ marfū‘ (1.5); كلها as tawkīd marfū‘ + ها muḍāf ilayh (2); عاملة as khabar marfū‘ (1.5)."
  },
  {
    "id": "m1-bab-1--explain-line--explain-the-following-matn-line--x",
    "chapterId": "m1-bab-1",
    "chapterAr": "الباب الأول في الفعل",
    "chapterEn": "The Verb",
    "archetype": "explain-line",
    "marks": 5,
    "promptEn": "Explain the following matn line, clarifying the key technical term it defines and what makes a verb belong to it.",
    "promptAr": "الْقِيَاسِيُّ مَا لَهُ قَاعِدَةٌ مُطَّرِدَةٌ",
    "markScheme": "Model answer: The qiyāsī (regular) verb is defined as that which has a consistent, always-applicable rule (qāʿida muṭṭarida) — i.e. its behaviour follows a fixed grammatical pattern that does not depend on what was specifically heard from the Arabs. This is the first of the two main types of verb (the other being samāʿī). It is the qiyāsī verb that raises the fāʿil/nāʾib al-fāʿil and puts the mafāʿīl and ḥāl in the accusative, and it subdivides into lāzim and mutaʿaddī. Breakdown: 2 marks for correctly translating/defining qiyāsī as having a consistent rule; 1 mark for noting it is one of the two types of verb (contrast with samāʿī); 2 marks for placing it in context (governs fāʿil/objects, divides into lāzim & mutaʿaddī)."
  },
  {
    "id": "m1-bab-1--explain-line--explain-the-following-matn-line--z",
    "chapterId": "m1-bab-1",
    "chapterAr": "الباب الأول في الفعل",
    "chapterEn": "The Verb",
    "archetype": "explain-line",
    "marks": 5,
    "promptEn": "Explain the following matn line and illustrate it with an example of your own or from the chapter.",
    "promptAr": "الْإِلْغَاءُ إِبْطَالُ عَمَلِ فِعْلِ الْقَلْبِ اللَّفْظِيِّ وَالْمَحَلِّيِّ",
    "markScheme": "Model answer: Ilghāʾ (cancellation) means nullifying the governance of a heart-verb both in form (lafẓ) and in position (maḥall) — i.e. unlike taʿlīq (where governance is dropped only in form but retained in position), in ilghāʾ the verb does not operate at all. It is preferred (yatarajjaḥ) when the verb comes after its two governed terms, e.g. مُحَمَّدٌ صَادِقٌ عَلِمْتُ (both terms stay nominative). By contrast, applying the governance is preferred when the verb sits between its two objects, e.g. مُحَمَّدًا عَلِمْتُ صَادِقًا. Breakdown: 2 marks for defining ilghāʾ as nullifying governance in both lafẓ and maḥall; 1 mark for contrasting it implicitly/explicitly with taʿlīq; 2 marks for a correct example of the cancelled state (verb deferred, terms nominative)."
  },
  {
    "id": "m1-bab-1--state-types--state-the-types-of-the-transitiv-11",
    "chapterId": "m1-bab-1",
    "chapterAr": "الباب الأول في الفعل",
    "chapterEn": "The Verb",
    "archetype": "state-types",
    "marks": 6,
    "promptEn": "State the types of the transitive verb (al-fiʿl al-mutaʿaddī) and, for each, give a recognising sign/example.",
    "promptAr": "وَالْفِعْلُ الْمُتَعَدِّي ثَلَاثَةُ أَضْرُبٍ",
    "markScheme": "Model answer: The transitive verb is of three kinds: (1) transitive to one object — sign: it takes a single mafʿūl bihi, e.g. خَلَقَ السَّمَاوَاتِ وَالْأَرْضَ; (2) transitive to two objects — sign: it governs two accusatives (either originally mubtadaʾ/khabar or not), e.g. وَهَدَيْنَاهُمَا الصِّرَاطَ الْمُسْتَقِيمَ and وَمَا أَظُنُّ السَّاعَةَ قَائِمَةً; (3) transitive to three objects — sign: it is always a heart-verb whose 2nd and 3rd objects were originally mubtadaʾ/khabar, e.g. يُرِيهِمُ اللهُ أَعْمَالَهُمْ حَسَرَاتٍ. Breakdown: 2 marks per kind (1 for naming the kind, 1 for a correct recognising sign/example), total 6."
  },
  {
    "id": "m1-bab-1--state-types--the-verbs-of-the-heart-af-l-al-q-13",
    "chapterId": "m1-bab-1",
    "chapterAr": "الباب الأول في الفعل",
    "chapterEn": "The Verb",
    "archetype": "state-types",
    "marks": 6,
    "promptEn": "The verbs of the heart (afʿāl al-qulūb) fall into two categories. State them, and for each give its recognising feature with an example verb.",
    "promptAr": "أَفْعَالُ الْقُلُوبِ اثْنَانِ",
    "markScheme": "Model answer: (1) Those denoting certainty (yaqīn) — recognised by the sense of definite knowledge/finding; verbs include وَجَدَ، أَلْفَى، رَأَى، عَلِمَ، عَرَفَ، دَرَى، تَعَلَّمْ, e.g. وَيَعْلَمُونَ أَنَّهُ الْحَقُّ. (2) Those denoting preponderant opinion (ẓann), also called afʿāl al-rujḥān — recognised by the sense of thinking/supposing; verbs include ظَنَّ، حَسِبَ، زَعَمَ، جَعَلَ، حَجَا، عَدَّ، وَهَبَ، خَالَ, e.g. وَيَحْسَبُونَ أَنَّهُمْ مُهْتَدُونَ. Breakdown: 3 marks each category — 1 for naming (yaqīn / ẓann-rujḥān), 1 for the distinguishing sense, 1 for a correct example verb."
  },
  {
    "id": "m1-bab-1--compare--explain-with-examples-the-differ-15",
    "chapterId": "m1-bab-1",
    "chapterAr": "الباب الأول في الفعل",
    "chapterEn": "The Verb",
    "archetype": "compare",
    "marks": 8,
    "promptEn": "Explain, with examples, the difference between al-taʿlīq and al-ilghāʾ as they affect the governance of a heart-verb.",
    "promptAr": "إِذَا سَدَّتِ الْجُمْلَةُ مَسَدَّ مَفْعُولَيْ فِعْلِ الْقَلْبِ لَمْ يَعْمَلْ فِيهَا لَفْظًا بَلْ مَحَلًّا، وَيُسَمَّى ذَلِكَ تَعْلِيقًا",
    "markScheme": "Model answer: Taʿlīq (suspension): the heart-verb is prevented from governing in form (lafẓ) but still governs in position (maḥall); it occurs when the following clause begins with a word that has clause-initial right (ṣadr al-kalām), e.g. إِنِ النَّافِيَة، مَا النَّافِيَة، لَامِ الِابْتِدَاءِ، لَعَلَّ، الِاسْتِفْهَام، لَامِ جَوَابِ الْقَسَمِ — e.g. لَقَدْ عَلِمْتَ مَا أَنْزَلَ هَؤُلَاءِ... (mā nāfiya suspends ʿalima). Ilghāʾ (cancellation): governance is nullified in BOTH form and position — the verb does not operate at all; it is preferred when the verb is deferred after its two terms, e.g. مُحَمَّدٌ صَادِقٌ عَلِمْتُ. Key contrast: taʿlīq retains maḥall governance and is triggered by a ṣadr-al-kalām word; ilghāʾ removes all governance and is a matter of word-order preference. Breakdown: 3 marks for explaining taʿlīq (with a trigger + example); 3 marks for explaining ilghāʾ (with example); 2 marks for articulating the precise distinction (maḥall retained vs. wholly nullified / trigger vs. word-order)."
  },
  {
    "id": "m1-bab-1--compare--explain-with-examples-the-differ-17",
    "chapterId": "m1-bab-1",
    "chapterAr": "الباب الأول في الفعل",
    "chapterEn": "The Verb",
    "archetype": "compare",
    "marks": 8,
    "promptEn": "Explain, with examples, the difference between ʿasā and kāda, both of which denote proximity (muqāraba).",
    "promptAr": "تَدُلُّ عَلَى مَعْنَى الْمُقَارَبَةِ عَسَى عَلَى سَبِيلِ الرَّجَاءِ، وَكَادَ وَأَخَوَاتُهَا عَلَى سَبِيلِ الْحُصُولِ",
    "markScheme": "Model answer: Both express muqāraba (proximity of the predicate's occurrence), but ʿasā does so by way of hope/expectation (rajāʾ) — it is a verb of hoping, e.g. عَسَى اللهُ أَنْ يَعْفُوَ عَنْهُمْ — whereas kāda does so by way of actual nearness to occurrence (ḥuṣūl) — it is a verb of proximity, e.g. وَكَادُوا يَقْتُلُونَنِي (they were on the verge of killing me). Further: an is frequent in ʿasā's predicate but rare with kāda; and kāda has a special affirmative/negative behaviour — affirmative كَادَ = act did NOT happen though nearly did; negative لَا يَكَادُ = act did not happen and was not even near (more emphatic). Breakdown: 2 marks ʿasā (rajāʾ sense + example); 2 marks kāda (ḥuṣūl sense + example); 2 marks for the rajāʾ-vs-ḥuṣūl distinction; 2 marks for a supporting nuance (an usage, or kāda's affirmative/negative meaning)."
  },
  {
    "id": "m1-bab-1--compare--distinguish-with-examples-betwee-19",
    "chapterId": "m1-bab-1",
    "chapterAr": "الباب الأول في الفعل",
    "chapterEn": "The Verb",
    "archetype": "compare",
    "marks": 8,
    "promptEn": "Distinguish, with examples, between a verb used as nāqiṣ (defective) and the same verb used as tāmm (complete).",
    "promptAr": "الْفِعْلُ التَّامُّ مَا يَكْتَفِي بِفَاعِلِهِ وَلَا يَحْتَاجُ إِلَى خَبَرٍ",
    "markScheme": "Model answer: A nāqiṣ (defective) verb does not give complete meaning with its marfūʿ alone: it enters upon a mubtadaʾ and khabar, raising the first (its ism) and putting the second in the accusative (its khabar), e.g. كَانَ زَيْدٌ قَائِمًا. A tāmm (complete) verb is content with its fāʿil and needs no khabar, e.g. كَانَتْ حَرْبٌ (a war occurred), وَإِنْ كَانَ ذُو عُسْرَةٍ (if there is one in hardship), حِينَ تُمْسُونَ وَحِينَ تُصْبِحُونَ, and مَا دَامَتِ السَّمَاوَاتُ وَالْأَرْضُ. Kāna and most of its sisters can be tāmm — except مَا زَالَ، مَا فَتِئَ، مَا بَرِحَ، and لَيْسَ, which only function as nāqiṣ. Breakdown: 3 marks for the nāqiṣ description (raises ism, naṣb khabar) with example; 3 marks for the tāmm description (suffices with fāʿil) with example; 2 marks for noting which sisters cannot be tāmm."
  },
  {
    "id": "m1-bab-1--explain-statement--explain-the-following-statement--1b",
    "chapterId": "m1-bab-1",
    "chapterAr": "الباب الأول في الفعل",
    "chapterEn": "The Verb",
    "archetype": "explain-statement",
    "marks": 15,
    "promptEn": "Explain the following statement as fully as possible, with examples, covering every trigger mentioned.",
    "promptAr": "يُعَلَّقُ عَمَلُ فِعْلِ الْقَلْبِ عَنِ الْجُمْلَةِ بَعْدَهُ إِنْ صُدِّرَتْ بِمَا لَهُ صَدْرُ الْكَلَامِ، مِثْلُ: إِنِ النَّافِيَةِ وَمَا النَّافِيَةِ وَلَامِ الِابْتِدَاءِ وَلَعَلَّ وَالِاسْتِفْهَامِ وَلَامِ جَوَابِ الْقَسَمِ",
    "markScheme": "Model answer: When a sentence fills the place of the two objects of a heart-verb, the verb cannot govern that sentence in form (lafẓ) — instead it governs only in position (maḥall); this is taʿlīq. The cause is a word possessing ṣadr al-kalām (the right to head the utterance) appearing at the start of the clause, blocking the verb's lafẓī governance. The chapter lists six triggers: (1) إِنْ النَّافِيَة — وَتَظُنُّونَ إِنْ لَبِثْتُمْ إِلَّا قَلِيلًا; (2) مَا النَّافِيَة — لَقَدْ عَلِمْتَ مَا أَنْزَلَ هَؤُلَاءِ إِلَّا رَبُّ السَّمَاوَاتِ; (3) لَامُ الِابْتِدَاءِ — وَلَقَدْ عَلِمُوا لَمَنِ اشْتَرَاهُ مَا لَهُ فِي الْآخِرَةِ مِنْ خَلَاقٍ; (4) لَعَلَّ — وَمَا أَدْرِي لَعَلَّهُ فِتْنَةٌ لَكُمْ; (5) الِاسْتِفْهَام — وَسَيَعْلَمُ الَّذِينَ ظَلَمُوا أَيَّ مُنْقَلَبٍ يَنْقَلِبُونَ; (6) لَامُ جَوَابِ الْقَسَمِ — وَلَقَدْ عَلِمْتُ لَتَأْتِيَنَّ مَنِيَّتِي. Breakdown: 3 marks for the core principle (governance suspended in lafẓ, retained in maḥall = taʿlīq) and the ṣadr-al-kalām rationale; 2 marks for each of the six triggers correctly named with a valid example (12 marks), capped so total = 15. Award full marks for the principle + at least five well-exemplified triggers."
  },
  {
    "id": "m1-bab-1--explain-statement--explain-the-following-statement--1d",
    "chapterId": "m1-bab-1",
    "chapterAr": "الباب الأول في الفعل",
    "chapterEn": "The Verb",
    "archetype": "explain-statement",
    "marks": 15,
    "promptEn": "Explain the following statement about kāna as fully as possible, with an example for each meaning.",
    "promptAr": "يَدُلُّ كَانَ عَلَى الْمَاضِي الْمُنْقَطِعِ، وَالْمَاضِي الْمُتَجَدِّدِ، وَالْحَالِ بِمَعْنَى مَا زَالَ، وَالِاسْتِقْبَالِ، وَقَدْ يَدُلُّ عَلَى الِانْتِفَاءِ وَالْقُدْرَةِ",
    "markScheme": "Model answer: Kāna carries several time-senses: (1) the completed/cut-off past (māḍī munqaṭiʿ) — either in the manner of fixedness, وَكَانُوا عَلَيْهِ شُهَدَاءَ, or of occurrence, وَلَقَدْ كَانُوا عَاهَدُوا اللهَ مِنْ قَبْلُ; (2) the recurring past (māḍī mutajaddid) — either continuity, كُنْتُ أَذْهَبُ يَوْمًا, or habit, كَانَا يَأْكُلَانِ الطَّعَامَ; (3) the present in the sense of mā zāla (still is) — وَكَانَ الْإِنْسَانُ عَجُولًا; (4) the future — كَانَتْ لَهُمْ جَنَّاتُ الْفِرْدَوْسِ نُزُلًا. Beyond time it may denote: (5) negation (intifāʾ) — مَا كَانَ لَنَا أَنْ نُشْرِكَ بِاللهِ مِنْ شَيْءٍ; and (6) capability/fittingness (qudra) — وَمَا كَانَ لِنَفْسٍ أَنْ تَمُوتَ إِلَّا بِإِذْنِ اللهِ. Breakdown: 2 marks for each of the six senses (name + valid example) = 12; 3 marks for organising and correctly distinguishing the sub-types (munqaṭiʿ thubūt/ḥudūth, mutajaddid istimrār/ʿāda). Total 15."
  },
  {
    "id": "m1-bab-1--define-types-examples--what-are-the-defective-verbs-al--1f",
    "chapterId": "m1-bab-1",
    "chapterAr": "الباب الأول في الفعل",
    "chapterEn": "The Verb",
    "archetype": "define-types-examples",
    "marks": 15,
    "promptEn": "What are the defective verbs (al-afʿāl al-nāqiṣa)? What are their four kinds? Give examples.",
    "promptAr": "الْأَفْعَالُ النَّاقِصَةُ: وَهِيَ أَفْعَالٌ تَدْخُلُ عَلَى الْمُبْتَدَأِ وَالْخَبَرِ، وَتَرْفَعُ الْأَوَّلَ وَيُسَمَّى اسْمَهَا، وَتَنْصِبُ الثَّانِيَ وَيُسَمَّى خَبَرَهَا",
    "markScheme": "Model answer: Definition — defective verbs are verbs that enter upon a mubtadaʾ and khabar, raising the first (called their ism) and putting the second in the accusative (called their khabar); they are part of the samāʿī verb. Their four kinds (aḍrub) are: (1) كَانَ وَأَخَوَاتُهَا (thirteen: كان، أصبح، أضحى، أمسى، ظلّ، بات، صار، ما برح، ما انفكّ، ما زال، ما فتئ، ما دام، ليس), e.g. صَارَ الْخَمْرُ خَلًّا; (2) أَفْعَالُ الرَّجَاءِ (verbs of hoping: عسى، اخلولق، حرى), e.g. عَسَى أَنْ يَنْفَعَنَا; (3) أَفْعَالُ الْمُقَارَبَةِ (verbs of proximity: كاد، كرب، أوشك), e.g. وَكَادُوا يَقْتُلُونَنِي; (4) أَفْعَالُ الشُّرُوعِ (verbs of beginning: جعل، أخذ، طفق، علق، أنشأ), e.g. وَطَفِقَا يَخْصِفَانِ. Breakdown: 3 marks for the definition (governance of ism/khabar); 3 marks for each of the four kinds correctly named with at least one example (12), capped to make total 15. Bonus-worthy detail (sense of each kind) can offset a missing example."
  },
  {
    "id": "m1-bab-1--define-types-examples--what-are-the-forms-of-wonder-iya-1h",
    "chapterId": "m1-bab-1",
    "chapterAr": "الباب الأول في الفعل",
    "chapterEn": "The Verb",
    "archetype": "define-types-examples",
    "marks": 15,
    "promptEn": "What are the forms of wonder (ṣiyagh al-taʿajjub)? What are their two kinds and their sub-forms? Give examples.",
    "promptAr": "صِيَغُ التَّعَجُّبِ: وَهِيَ مَا وُضِعَتْ لِلدَّلَالَةِ عَلَى التَّعَجُّبِ، وَهِيَ ضَرْبَانِ",
    "markScheme": "Model answer: Definition — ṣiyagh al-taʿajjub are forms coined to express wonder/amazement; they are the third division of the samāʿī verb's praise/blame/wonder category. Two kinds: (A) Qiyāsī (regular) — three forms: (1) مَا أَفْعَلَهُ, e.g. فَمَا أَصْبَرَهُمْ عَلَى النَّارِ (with two parsing views of mā: interrogative, or an indefinite qualified noun meaning 'a great thing'); (2) أَفْعِلْ بِهِ, e.g. أَسْمِعْ بِهِمْ وَأَبْصِرْ (originally afʿala, changed to command form, with bāʾ added to the fāʿil because predicating a command to an overt noun is ugly); (3) فَعُلَ — original or transferred, e.g. كَبُرَتْ كَلِمَةً تَخْرُجُ مِنْ أَفْو��اهِهِمْ. (B) Samāʿī (heard) — among them: سُبْحَانَ اللهِ (سُبْحَانَكَ...), the interrogative (كَيْفَ تَكْفُرُونَ بِاللهِ), and the vocative/nidāʾ (يَا بُشْرَى هَذَا غُلَامٌ). Breakdown: 2 marks for the definition; 2 marks for the qiyāsī/samāʿī division; 3 marks for the three qiyāsī forms (1 each, with example); 3 marks for at least two samāʿī forms with examples; up to 3 marks for the extra parsing notes (mā afʿalahu views, afʿil bihi derivation). Total 15."
  },
  {
    "id": "m1-bab-1--enumerate--enumerate-k-na-and-its-sisters-k-1j",
    "chapterId": "m1-bab-1",
    "chapterAr": "الباب الأول في الفعل",
    "chapterEn": "The Verb",
    "archetype": "enumerate",
    "marks": 12,
    "promptEn": "Enumerate kāna and its sisters (kāna wa-akhawātuhā) — list them and state the meaning/function of each.",
    "promptAr": "الضَّرْبُ الْأَوَّلُ: كَانَ وَأَخَوَاتُهَا، وَهِيَ ثَلَاثَةَ عَشَرَ",
    "markScheme": "Model answer (13 items): (1) كَانَ — being/was (past, present, future, etc.); (2) أَصْبَحَ — qualifying of the noun by the khabar at morning; (3) أَضْحَى — at forenoon (ḍuḥā); (4) أَمْسَى — at evening; (5) ظَلَّ — during the daytime; (6) بَاتَ — during the night; (7) صَارَ — for change of essence/attributes (becoming); (8) مَا بَرِحَ — continuity (to keep on); (9) مَا انْفَكَّ — continuity; (10) مَا زَالَ — continuity; (11) مَا فَتِئَ — continuity; (12) مَا دَامَ — to set the time of what precedes by the duration of the qualifying; (13) لَيْسَ — negating the present. Breakdown: 12 marks total ≈ ~0.9 per item — award roughly 1 mark per correctly named verb WITH its meaning/function; allow full 12 for all thirteen named with at least an acceptable gloss. Deduct for a verb named without meaning or for any non-sister wrongly included."
  },
  {
    "id": "m1-bab-1--enumerate--enumerate-the-verbs-of-praise-an-1l",
    "chapterId": "m1-bab-1",
    "chapterAr": "الباب الأول في الفعل",
    "chapterEn": "The Verb",
    "archetype": "enumerate",
    "marks": 12,
    "promptEn": "Enumerate the verbs of praise and blame (afʿāl al-madḥ wa-l-dhamm) with the meaning of each, and state what they govern.",
    "promptAr": "أَفْعَالُ الْمَدْحِ وَالذَّمِّ: وَهِيَ تَرْفَعُ فَاعِلَهَا وَمَخْصُوصَهَا، وَهِيَ خَمْسَةٌ",
    "markScheme": "Model answer: They are five, governing (raising) both their fāʿil and their makhṣūṣ: (1) نِعْمَ — how excellent (praise), e.g. نِعْمَ الْعَبْدُ; (2) حَبَّذَا — how excellent (praise), e.g. حَبَّذَا خَالِدٌ; (3) بِئْسَ — how wretched (blame); (4) سَاءَ — how evil (blame), e.g. بِئْسَ الشَّرَابُ وَسَاءَتْ مُرْتَفَقًا; (5) لَا حَبَّذَا — how wretched (blame), e.g. لَا حَبَّذَا الْكِبْرُ. Also appended (mulḥaq): any verb on the pattern فَعُلَ, originally (وَحَسُنَتْ مُرْتَفَقًا) or transferred to it (كَتُبَ زَيْدٌ). Breakdown: 2 marks for stating they are five and that they raise fāʿil + makhṣūṣ; 8 marks for the five verbs (≈1.5 each: naming + meaning/example); 2 marks for the appended faʿula category. Total 12."
  },
  {
    "id": "m1-bab-1--classify-tarkib--first-classify-the-category-of-t-1n",
    "chapterId": "m1-bab-1",
    "chapterAr": "الباب الأول في الفعل",
    "chapterEn": "The Verb",
    "archetype": "classify-tarkib",
    "marks": 9,
    "promptEn": "First classify the category of the verb صَارَ (what kind of verb is it, and what does it do grammatically?). Then translate the sentence and give the full tarkīb/iʿrāb of each word.",
    "promptAr": "صَارَ الْخَمْرُ خَلًّا",
    "markScheme": "Model answer: Classification — صَارَ is a samāʿī, defective verb (fiʿl nāqiṣ), one of kāna's sisters, denoting taḥawwul (change of essence/attributes); it raises an ism and puts a khabar in the accusative. Translation: 'The wine became vinegar.' Iʿrāb: صَارَ — fiʿl māḍin nāqiṣ mabnī ʿalā al-fatḥ; الْخَمْرُ — ismu ṣāra marfūʿ, ʿalāmatuhu al-ḍamma; خَلًّا — khabaru ṣāra manṣūb, ʿalāmatuhu al-fatḥa. Breakdown: 3 marks for correct classification (nāqiṣ, sister of kāna, sense of taḥawwul, raises ism / naṣb khabar); 2 marks for an accurate translation; 4 marks for the iʿrāb (≈1.3 each: verb as nāqiṣ māḍī, الخمر as marfūʿ ism, خلًّا as manṣūb khabar — award the 4th mark for citing the ʿalāmāt correctly)."
  },
  {
    "id": "m1-bab-1--classify-tarkib--first-classify-the-category-of-t-1p",
    "chapterId": "m1-bab-1",
    "chapterAr": "الباب الأول في الفعل",
    "chapterEn": "The Verb",
    "archetype": "classify-tarkib",
    "marks": 9,
    "promptEn": "First classify the category of the word نِعْمَ (what kind of verb is it and what does it govern?). Then translate the sentence and give the full tarkīb/iʿrāb of each word.",
    "promptAr": "نِعْمَ الْعَبْدُ",
    "markScheme": "Model answer: Classification — نِعْمَ is a samāʿī jāmid verb of praise (fiʿl al-madḥ), one of the five praise/blame verbs; it raises a fāʿil (here definite by lām al-jins) and a makhṣūṣ bi-l-madḥ. Translation: 'How excellent (an) excellent is the servant.' (The makhṣūṣ may be elided or stated.) Iʿrāb: نِعْمَ — fiʿl māḍin jāmid li-inshāʾ al-madḥ, mabnī ʿalā al-fatḥ; الْعَبْدُ — fāʿil niʿma marfūʿ, ʿalāmatuhu al-ḍamma, muʿarraf bi-lām al-jins; the makhṣūṣ bi-l-madḥ is here omitted/understood (or, if stated, would be mubtadaʾ muʾakhkhar marfūʿ with the preceding jumla as its khabar muqaddam). Breakdown: 3 marks for classification (verb of madḥ, jāmid, raises fāʿil + makhṣūṣ, fāʿil definite by lām al-jins); 2 marks for translation; 4 marks for iʿrāb (niʿma as jāmid māḍī li-l-madḥ; al-ʿabd as marfūʿ fāʿil with its ʿalāma; correct treatment of the makhṣūṣ)."
  },
  {
    "id": "m1-bab-2--explain-line--explain-the-following-line-from--1c",
    "chapterId": "m1-bab-2",
    "chapterAr": "الباب الثاني في الحرف",
    "chapterEn": "The Particle",
    "archetype": "explain-line",
    "marks": 5,
    "promptEn": "Explain the following line from the matn, stating which particle is intended, its grammatical category, and its core meaning, with an example.",
    "promptAr": "مَعْنَى عَنِ الْمُجَاوَزَةُ",
    "markScheme": "Model answer: عَنْ is the fourth of the thirteen original prepositions (حرف الجر الأصلي). Its core meaning is الْمُجَاوَزَة — passing beyond / going away from something. As an original preposition it (with its genitive) is positionally accusative, governed by a verb or quasi-verb. Example: وَيَنْهَوْنَ عَنِ الْمُنْكَرِ (here عن المنكر is in the sense of the مفعول به). Breakdown: 1 — identifies عَنْ as a preposition / original preposition; 2 — gives the meaning مجاوزة and explains it (passing beyond/away from); 1 — notes it governs a genitive; 1 — supplies a correct Qur'anic/illustrative example."
  },
  {
    "id": "m1-bab-2--explain-line--explain-this-line-what-situation-1e",
    "chapterId": "m1-bab-2",
    "chapterAr": "الباب الثاني في الحرف",
    "chapterEn": "The Particle",
    "archetype": "explain-line",
    "marks": 5,
    "promptEn": "Explain this line: what situation does it describe, and what is the term coined for the affected noun?",
    "promptAr": "وَيُسَمَّى الْمَجْرُورُ بَعْدَ حَذْفِ الْجَارِّ مَنْصُوبًا بِنَزْعِ الْخَافِضِ",
    "markScheme": "Model answer: When a preposition is dropped (which is permitted — قياسًا e.g. before أَنْ and أَنَّ, and سماعًا), the noun that would have been its genitive is no longer kept in the genitive; instead it is regarded as accusative, and this accusative is technically named مَنْصُوب بِنَزْعِ الْخَافِضِ (accusative by removal of the genitive-marker). Example: إِنَّ عَادًا كَفَرُوا رَبَّهُمْ — the base being كَفَرُوا بِرَبِّهِمْ, so رَبَّهُمْ became accusative after the omission of the bāʾ. Breakdown: 2 — explains that the preposition has been omitted and the noun is now treated as accusative; 1 — gives the technical name نزع الخافض; 1 — notes omission is permitted (قياسًا/سماعًا) e.g. before أن/أنّ; 1 — supplies a valid example such as كفروا ربهم ← كفروا بربهم."
  },
  {
    "id": "m1-bab-2--state-types--state-the-kinds-of-the-prepositi-1g",
    "chapterId": "m1-bab-2",
    "chapterAr": "الباب الثاني في الحرف",
    "chapterEn": "The Particle",
    "archetype": "state-types",
    "marks": 6,
    "promptEn": "State the kinds (أضرُب) of the preposition (حرف الجر), and for each give the distinguishing feature (علامة) by which it is recognised.",
    "promptAr": "",
    "markScheme": "Model answer — three kinds: (1) الْأَصْلِيُّ (original): gives a special meaning AND it (with its genitive) is positionally accusative, governed by a verb or quasi-verb — e.g. خُذِ الْكِتَابَ بِقُوَّةٍ. (2) الشَّبِيهُ بِالزَّائِدِ (resembling the redundant): gives a special meaning BUT is NOT governed by a verb or quasi-verb — e.g. رُبَّ شَهْوَةٍ تُورِثُ حُزْنًا. (3) الزَّائِدُ (redundant): gives no meaning except emphasis (التأكيد) and is NOT governed by a verb or quasi-verb — e.g. لَيْسَ كَمِثْلِهِ شَيْءٌ. Breakdown: 2 marks per kind (1 for naming the kind, 1 for its correct distinguishing feature/sign). Total 6."
  },
  {
    "id": "m1-bab-2--compare--explain-with-examples-the-differ-1i",
    "chapterId": "m1-bab-2",
    "chapterAr": "الباب الثاني في الحرف",
    "chapterEn": "The Particle",
    "archetype": "compare",
    "marks": 8,
    "promptEn": "Explain, with examples, the difference between لَام التَّعْلِيل (لَام كَي) and لَام الْعَاقِبَة (لَام الصَّيْرُورَة).",
    "promptAr": "",
    "markScheme": "Model answer: Both are uses of the lām (السادس من الحروف) when it conveys the sense of the مفعول له. (a) لَام التَّعْلِيل / لَام كَي expresses a genuine purpose intended by the doer (عن قصد الفاعل), and this is the more frequent use — e.g. نَزَّلَ الْفُرْقَانَ عَلَى عَبْدِهِ لِيَكُونَ لِلْعَالَمِينَ نَذِيرًا (the warning was the intended aim). (b) لَام الْعَاقِبَة / لَام الصَّيْرُورَة expresses an unintended outcome/result (نتيجة عن غير قصد) — e.g. فَالْتَقَطَهُ آلُ فِرْعَوْنَ لِيَكُونَ لَهُمْ عَدُوًّا وَحَزَنًا (they did not pick him up in order that he become an enemy; that was merely the eventual outcome). Breakdown: 2 — defines lām al-taʿlīl as intended purpose; 2 — its example; 2 — defines lām al-ʿāqiba as unintended consequence; 2 — its example. Total 8."
  },
  {
    "id": "m1-bab-2--compare--explain-with-examples-the-differ-1k",
    "chapterId": "m1-bab-2",
    "chapterAr": "الباب الثاني في الحرف",
    "chapterEn": "The Particle",
    "archetype": "compare",
    "marks": 8,
    "promptEn": "Explain, with examples, the difference between حرف الجر الشَّبِيه بالزَّائِد and حرف الجر الزَّائِد.",
    "promptAr": "",
    "markScheme": "Model answer: Both share that they are NOT (with their genitive) governed by a verb or quasi-verb (لا يكون مع مجروره معمولًا لفعل أو شبه الفعل). They differ in meaning: (1) الشَّبِيه بالزَّائِد DOES give a special meaning (يفيد معنى خاصًّا) — its members are رُبَّ (for making the genitive many or few), the partitive مِنْ (التبعيضية, e.g. عِنْدِي مِنْ مَاءٍ), and حَاشَا for exception (هَلَكَ النَّاسُ حَاشَا الْعَالِمِ). (2) الزَّائِد gives NO meaning except emphasis (لا يفيد معنى إلا التأكيد) — its members are the redundant بَاء (لَيْسَ بِظَلَّامٍ), مِنْ (مَا جَاءَنَا مِنْ بَشِيرٍ), لَام (فَعَّالٌ لِمَا يُرِيدُ), and كَاف (لَيْسَ كَمِثْلِهِ شَيْءٌ). Breakdown: 2 — states the shared feature (not governed); 2 — shabīh gives a special meaning + example; 2 — zāʾid gives only taʾkīd + example; 2 — lists/illustrates the members of each. Total 8."
  },
  {
    "id": "m1-bab-2--explain-statement--explain-the-following-statement--1m",
    "chapterId": "m1-bab-2",
    "chapterAr": "الباب الثاني في الحرف",
    "chapterEn": "The Particle",
    "archetype": "explain-statement",
    "marks": 15,
    "promptEn": "Explain the following statement as fully as possible, with examples.",
    "promptAr": "وَهِيَ لِتَكْثِيرِ مَجْرُورِهَا أَوْ تَقْلِيلِهِ، وَالْقَرِينَةُ تُعَيِّنُ الْمُرَادَ، وَلَا تَقَعُ رُبَّ إِلَّا فِي صَدْرِ الْكَلَامِ",
    "markScheme": "Model answer (rubba — رُبَّ, the first of the prepositions resembling the redundant): (1) Meaning: it serves to make its genitive MANY (تكثير) or FEW (تقليل), and the context (القرينة) determines which is intended — e.g. رُبَّ شَهْوَةٍ تُورِثُ حُزْنًا طَوِيلًا. (2) Position: it occurs only at the beginning of the speech (صدر الكلام); it may be preceded by the particle of calling — يَا رُبَّ كَاسِيَةٍ فِي الدُّنْيَا عَارِيَةٍ فِي الْآخِرَةِ. (3) Its genitive must be either an overt indefinite noun (اسم ظاهر نكرة) or an ambiguous pronoun explained by a tamyīz — رُبَّهُ رَجُلًا كَرِيمًا لَقِيتُهُ. (4) Adding the kāffah mā (ما الكافة) stops it from governing — رُبَّمَا يَصُومُ زَيْدٌ. (5) Its bāʾ may be lightened — رُبَمَا يَوَدُّ الَّذِينَ كَفَرُوا. (6) رُبَّ may be dropped while its governance remains: often after the wāw (وَلَيْلٍ كَمَوْجِ الْبَحْرِ أَرْخَى سُدُولَهُ) and rarely after the fāʾ; and مَا after مِنْ may carry the sense of rubba (كَانَ ﷺ مِمَّا يُحَرِّكُ شَفَتَيْهِ). Breakdown: 2 — takthīr/taqlīl + role of qarīna; 2 — must be at start of speech / may follow yā; 2 — nature of its genitive (indefinite noun or ambiguous pronoun + tamyīz); 2 — mā al-kāffa stops governance; 2 — lightening of the bāʾ; 2 — dropping rubba after wāw/fāʾ and min mā; 3 — supplying apt examples throughout. Total 15."
  },
  {
    "id": "m1-bab-2--explain-statement--explain-the-following-statement--1o",
    "chapterId": "m1-bab-2",
    "chapterAr": "الباب الثاني في الحرف",
    "chapterEn": "The Particle",
    "archetype": "explain-statement",
    "marks": 15,
    "promptEn": "Explain the following statement as fully as possible, with examples, detailing where this particle occurs.",
    "promptAr": "تَقَعُ الْبَاءُ الزَّائِدَةُ قِيَاسًا فِي خَبَرِ النَّفْيِ بِلَيْسَ وَمَا، وَتَقَعُ سَمَاعًا فِي مَوَاضِعَ أُخَرَ",
    "markScheme": "Model answer (the redundant bāʾ — الباء الزائدة, the first of the four redundant prepositions; it adds no meaning except emphasis): It occurs (A) regularly/analogically (قياسًا) in the predicate of negation: with لَيْسَ — وَأَنَّ اللهَ لَيْسَ بِظَلَّامٍ لِلْعَبِيدِ; and with مَا — وَمَا رَبُّكَ بِظَلَّامٍ لِلْعَبِيدِ. (B) By heard usage (سماعًا) in several places: (1) the predicate of an interrogative with هل — هَلْ زَيْدٌ بِقَائِمٍ؟; (2) the maʿnawī emphasis with نَفْس — نَظَّفَ الْأَمِيرُ الْمَسْجِدَ بِنَفْسِهِ; (3) the agent of أَفْعِلْ بِهِ of wonder — أَسْمِعْ بِهِمْ وَأَبْصِرْ; (4) the subject after the sudden إذا الفجائية — دَخَلَ الرَّجُلُ فَإِذَا بِابْنِهِ يُصَلِّي; (5) the subject expressed with حَسْب — بِحَسْبِكَ أَنْ تَصُومَ...; (6) the predicate of حَسْب — حَسْبُكَ بِزَيْدٍ; (7) the agent of كَفَى meaning ḥasb (suffice) — كَفَى بِاللهِ شَهِيدًا (unlike كَفَى meaning protect: وَكَفَى اللهُ الْمُؤْمِنِينَ الْقِتَالَ). Breakdown: 1 — notes it only emphasises (no added meaning); 3 — the قياسًا cases (laysa & mā) with examples; 7 — the سماعًا cases (≈1 each) with examples; 2 — the kafā distinction (suffice vs protect); 2 — overall accuracy and ḥarakāt of examples. Total 15."
  },
  {
    "id": "m1-bab-2--define-types-examples--what-is-the-redundant-prepositio-1q",
    "chapterId": "m1-bab-2",
    "chapterAr": "الباب الثاني في الحرف",
    "chapterEn": "The Particle",
    "archetype": "define-types-examples",
    "marks": 15,
    "promptEn": "What is the redundant preposition (حرف الجر الزائد)? What are its members, and in which positions does each occur? Give examples.",
    "promptAr": "",
    "markScheme": "Model answer: Definition — حرف الجر الزائد is a preposition that gives no meaning except emphasis (التأكيد), and it (with its genitive) is not governed by a verb or quasi-verb. Its members are four: (1) الباء الزائدة — qiyāsan in the predicate of negation with laysa/mā (لَيْسَ بِظَلَّامٍ), and samāʿan in several places (هَلْ زَيْدٌ بِقَائِمٍ؟; كَفَى بِاللهِ شَهِيدًا). (2) مِنْ الزائدة — on the tamyīz of declarative كم (كَمْ آتَيْنَاهُمْ مِنْ آيَةٍ بَيِّنَةٍ), and in non-affirmative speech: after a negation particle (مَا جَاءَنَا مِنْ بَشِيرٍ), after an interrogative meaning negation (هَلْ مِنْ خَالِقٍ غَيْرُ اللهِ), or with هل (هَلْ مِنْ مَزِيدٍ). (3) اللام الزائدة — on the predicate of negated kāna (لام الجحود): فَمَا كَانَ اللهُ لِيَظْلِمَهُمْ; on the agent (لام التبيين): هَيْتَ لَكَ; on a fronted governed term: إِنْ كُنْتُمْ لِلرُّؤْيَا تَعْبُرُونَ; on the object of a quasi-verb (لام التقوية): فَعَّالٌ لِمَا يُرِيدُ. (4) الكاف الزائدة — لَيْسَ كَمِثْلِهِ شَيْءٌ. Breakdown: 3 — correct definition (emphasis only; not governed); 3 each for بَاء، مِنْ، لَام with their positions + examples (9); the كَاف with example; remaining marks for accuracy/examples. Total 15."
  },
  {
    "id": "m1-bab-2--enumerate--list-the-thirteen-original-prepo-1s",
    "chapterId": "m1-bab-2",
    "chapterAr": "الباب الثاني في الحرف",
    "chapterEn": "The Particle",
    "archetype": "enumerate",
    "marks": 12,
    "promptEn": "List the thirteen original prepositions (حروف الجر الأصلية) in order, and for each give its core meaning (where the matn states one).",
    "promptAr": "",
    "markScheme": "Model answer (in order): 1 الْبَاء — الإلصاق (adhesion); 2 مِنْ — ابتداء الغاية (start of the limit); 3 إِلَى — انتهاء الغاية (end of the limit); 4 عَنْ — المجاوزة (passing beyond); 5 عَلَى — الاستعلاء (being upon); 6 اللَّام — التخصيص/الاستحقاق, الملك, شبه الملك/النسبة (assignment/entitlement, ownership, quasi-ownership/relation); 7 فِي — الظرفية (containment); 8 الْكَاف — التشبيه (comparison); 9 حَتَّى — انتهاء الغاية (end of the limit); 10 وَاو الْقَسَم (the wāw of oath); 11 تَاء الْقَسَم (the tāʾ of oath); 12 مُذْ (since); 13 مُنْذُ (since) — mudh/mundhu give the sense of فِي with a definite genitive and مِنْ with an indefinite. Breakdown: roughly 1 mark per particle correctly named in order (13 items → cap at 12), with its meaning required where the matn supplies one; deduct for omissions, wrong order, or missing meanings. Total 12."
  },
  {
    "id": "m1-bab-2--classify-tarkib--classify-the-word-which-category-1u",
    "chapterId": "m1-bab-2",
    "chapterAr": "الباب الثاني في الحرف",
    "chapterEn": "The Particle",
    "archetype": "classify-tarkib",
    "marks": 9,
    "promptEn": "Classify the word رُبَّ (which category of particle is it?). Then translate the sentence and give its full tarkīb/iʿrāb.",
    "promptAr": "رُبَّ شَهْوَةٍ تُورِثُ حُزْنًا طَوِيلًا",
    "markScheme": "Model answer: Classification — رُبَّ is a حرف جر شَبِيه بالزَّائِد (it gives a special meaning, here تقليل/تكثير, but is not governed by a verb or quasi-verb); it occurs at the start of the speech (صدر الكلام) and its genitive is an indefinite overt noun. Translation: 'Many a desire bequeaths long grief.' Iʿrāb: رُبَّ — حرف جر شبيه بالزائد، مبني، لا محل له. شَهْوَةٍ — مجرور لفظًا برُبَّ، مرفوع محلًّا مبتدأ (indefinite, permitted after rubba). تُورِثُ — فعل مضارع مرفوع، وفاعله ضمير مستتر تقديره هي (يعود على شهوة)، والجملة الفعلية خبر المبتدأ. حُزْنًا — مفعول به منصوب. طَوِيلًا — نعت لـ حُزْنًا منصوب. Breakdown: 2 — correct classification of rubba as shabīh bil-zāʾid; 2 — accurate translation; 5 — iʿrāb (1 rubba, 1 shahwa as lafẓan majrūr/maḥallan mubtadaʾ, 1 tūrithu + hidden agent + jumla khabar, 1 ḥuznan mafʿūl bih, 1 ṭawīlan naʿt). Total 9."
  },
  {
    "id": "m1-bab-2--classify-tarkib--classify-the-particle-in-this-se-1w",
    "chapterId": "m1-bab-2",
    "chapterAr": "الباب الثاني في الحرف",
    "chapterEn": "The Particle",
    "archetype": "classify-tarkib",
    "marks": 9,
    "promptEn": "Classify the particle الباء in this sentence (which category of preposition is it?). Then translate the sentence and give its full tarkīb/iʿrāb.",
    "promptAr": "كَفَى بِاللهِ شَهِيدًا",
    "markScheme": "Model answer: Classification — the بَاء here is a باء زائدة (redundant preposition, adding emphasis only); specifically it falls on the agent of كَفَى when كَفَى carries the meaning of حَسْب (to suffice) — distinct from كَفَى meaning وَقَى (to protect), as in وَكَفَى اللهُ الْمُؤْمِنِينَ الْقِتَالَ. Translation: 'Allah suffices as a witness' / 'Sufficient is Allah as a witness.' Iʿrāb: كَفَى — فعل ماضٍ مبني على الفتح المقدَّر. بِ — حرف جر زائد. اللهِ — لفظ الجلالة مجرور لفظًا بالباء الزائدة، مرفوع محلًّا فاعل كَفَى. شَهِيدًا — تمييز (أو حال) منصوب. Breakdown: 2 — classifies the bāʾ as redundant on the fāʿil of kafā (= ḥasb); 2 — accurate translation; 5 — iʿrāb (1 kafā as māḍī, 1 bāʾ zāʾida, 1 Allāh majrūr lafẓan/marfūʿ maḥallan fāʿil, 1 shahīdan manṣūb tamyīz/ḥāl, 1 noting the kafā=ḥasb vs waqā distinction). Total 9."
  }
];
