/* ── Shadhā al-ʿArf fī Fann aṣ-Ṣarf — الميزان الصرفي (Worksheet 2) ──
   وزن الثلاثي · وزن ما زاد على ثلاثة أحرف · وزن الحالات الخاصة
   Reuses the SA_* glyph/word constants declared in wk01-muqaddimah.js
   (this file must be loaded after it). `c:'red'` mirrors the worksheet colour. */

const DATA_WK02 = [
  { t: 'page', n: '١' },

  { t: 'h1', c: 'blue', ar: 'الْمِيزَانُ الصَّرْفِيُّ', en: 'The Morphological Scale (al-Mīzān aṣ-Ṣarfī)' },

  /* ── وزن الثلاثي ── */
  { t: 'h2', c: 'blue', ar: 'وَزْنُ الثُّلَاثِيِّ', en: 'Weighing the Trilateral Word' },

  { t: 'line', w: [
    { a: 'لَمَّا', t: 'lammā', e: 'since' },
    { a: 'كَانَ', t: 'kāna', e: 'is' },
    { a: 'أَكْثَرُ', t: 'aktharu', e: 'most of' },
    { a: 'كَلِمَاتِ', t: 'kalimāti', e: 'the words of' },
    { a: 'اللُّغَةِ', t: 'al-lughati', e: 'the language' },
    { a: 'الْعَرَبِيَّةِ', t: 'al-ʿarabiyyati', e: 'Arabic' },
    { a: 'ثُلَاثِيَّ', t: 'thulāthiyya', e: 'trilateral in' },
    { a: 'الْأُصُولِ', t: 'al-uṣūli', e: 'root-letters' },
    SA_COMMA,
    { a: 'اعْتَبَرَ', t: 'iʿtabara', e: 'reckoned' },
    { a: 'عُلَمَاءُ', t: 'ʿulamāʾu', e: 'the scholars of' },
    { a: 'الصَّرْفِ', t: 'aṣ-ṣarfi', e: 'ṣarf' },
    { a: 'أَنَّ', t: 'anna', e: 'that' },
    { a: 'أُصُولَ', t: 'uṣūla', e: 'the roots of' },
    { a: 'الْكَلِمَاتِ', t: 'al-kalimāti', e: 'words' },
    { a: 'ثَلَاثَةُ', t: 'thalāthatu', e: '(are) three' },
    { a: 'أَحْرُفٍ', t: 'aḥrufin', e: 'letters' },
    SA_COMMA,
    { a: 'وَقَابَلُوهَا', t: 'wa-qābalūhā', e: 'and they matched them' },
    { a: 'عِنْدَ', t: 'ʿinda', e: 'when' },
    { a: 'الْوَزْنِ', t: 'al-wazni', e: 'weighing' },
    { a: 'بِالْفَاءِ', t: 'bi-l-fāʾi', e: 'with fāʾ', c: 'red' },
    { a: 'وَالْعَيْنِ', t: 'wa-l-ʿayni', e: 'and ʿayn', c: 'red' },
    { a: 'وَاللَّامِ', t: 'wa-l-lāmi', e: 'and lām', c: 'red' },
    SA_COMMA,
    { a: 'مُصَوَّرَةً', t: 'muṣawwaratan', e: 'shaped' },
    { a: 'بِصُورَةِ', t: 'bi-ṣūrati', e: 'in the form of' },
    { a: 'الْمَوْزُونِ', t: 'al-mawzūni', e: 'the weighed word' },
    { g: '.' },
  ] },

  { t: 'line', w: [
    { a: 'فَائِدَةُ', t: 'fāʾidatu', e: 'the benefit of' },
    { a: 'الْمِيزَانِ', t: 'al-mīzāni', e: 'the scale' },
    { a: 'ذِكْرُ', t: 'dhikru', e: 'is the indicating of' },
    { g: ':' },
  ] },

  { t: 'box', lines: [
    [ { g: '١ –' },
      { a: 'الْحَرَكَاتِ', t: 'al-ḥarakāti', e: 'the vowels' },
      { a: 'وَالسَّكَنَاتِ', t: 'wa-s-sakanāti', e: 'and the quiescences (sukūns)' },
      SA_COMMA ],
    [ { g: '٢ –' },
      { a: 'الْأُصُولِ', t: 'al-uṣūli', e: 'the root-letters' },
      { a: 'وَالزَّوَائِدِ', t: 'wa-z-zawāʾidi', e: 'and the added letters' },
      SA_COMMA ],
    [ { g: '٣ –' },
      { a: 'تَقَدُّمِ', t: 'taqaddumi', e: 'the precedence of' },
      { a: 'الْحُرُوفِ', t: 'al-ḥurūfi', e: 'the letters' },
      { a: 'وَتَأَخُّرِهَا', t: 'wa-taʾakhkhurihā', e: 'and their coming later' },
      SA_COMMA ],
    [ { g: '٤ –' },
      { a: 'ذِكْرِ', t: 'dhikri', e: 'the indicating of' },
      { a: 'الْحُرُوفِ', t: 'al-ḥurūfi', e: 'the letters' },
      { a: 'وَحَذْفِهَا', t: 'wa-ḥadhfihā', e: 'and their elision' },
      { g: '.' } ],
  ] },

  { t: 'line', w: [
    SA_NAHW, { g: ':' },
    { a: 'انْكَسَرَ', t: 'inkasara', e: 'inkasara (it broke)', c: 'red' },
    { g: '=' },
    { a: 'انْفَعَلَ', t: 'infaʿala', e: 'infaʿala (its pattern)', c: 'red' },
    { g: '.' },
  ] },

  { t: 'line', w: [
    { a: 'فَيَقُولُونَ', t: 'fa-yaqūlūna', e: 'so they say' },
    { a: 'فِي', t: 'fī', e: 'for' },
    { a: 'وَزْنِ', t: 'wazni', e: 'the measure of' },
    { a: 'قَمَر', t: 'qamar', e: 'qamar (moon)' },
    { a: 'مَثَلًا', t: 'mathalan', e: 'for example' },
    { g: ':' },
    { a: 'فَعَلْ', t: 'faʿal', e: 'faʿal', n: 'q→f, m→ʿ, r→l' },
    SA_COMMA,
    { a: 'بِالتَّحْرِيكِ', t: 'bi-t-taḥrīki', e: 'with vowelling' },
    { g: '(' },
    { a: 'الْحَرَكَةِ', t: 'al-ḥarakati', e: 'i.e. the vowel', c: 'red' },
    { g: ')' },
    SA_COMMA,
    { a: 'وَفِي', t: 'wa-fī', e: 'and for' },
    { a: 'جَمْل', t: 'jaml', e: 'jaml (camel)' },
    { g: ':' },
    { a: 'فِعْل', t: 'fiʿl', e: 'fiʿl' },
    SA_COMMA,
    { a: 'بِكَسْرِ', t: 'bi-kasri', e: 'with a kasrah on' },
    { a: 'الْفَاءِ', t: 'al-fāʾi', e: 'the fāʾ' },
    { a: 'وَسُكُونِ', t: 'wa-sukūni', e: 'and sukūn on' },
    { a: 'الْعَيْنِ', t: 'al-ʿayni', e: 'the ʿayn' },
    SA_COMMA,
    { a: 'وَفِي', t: 'wa-fī', e: 'and for' },
    { a: 'كَرُمَ', t: 'karuma', e: 'karuma (he was noble)' },
    { g: ':' },
    { a: 'فَعُل', t: 'faʿul', e: 'faʿul' },
    SA_COMMA,
    { a: 'بِفَتْحِ', t: 'bi-fatḥi', e: 'with a fatḥah on' },
    { a: 'الْفَاءِ', t: 'al-fāʾi', e: 'the fāʾ' },
    { a: 'وَضَمِّ', t: 'wa-ḍammi', e: 'and a ḍammah on' },
    { a: 'الْعَيْنِ', t: 'al-ʿayni', e: 'the ʿayn' },
    SA_COMMA,
    { a: 'وَهَلُمَّ', t: 'wa-halumma', e: 'and so' },
    { a: 'جَرًّا', t: 'jarran', e: 'forth' },
    SA_COMMA,
    { a: 'وَيُسَمُّونَ', t: 'wa-yusammūna', e: 'and they call' },
    { a: 'الْحَرْفَ', t: 'al-ḥarfa', e: 'the letter' },
    { a: 'الْأَوَّلَ', t: 'al-awwala', e: 'first' },
    { a: 'فَاءَ', t: 'fāʾa', e: 'the fāʾ of', c: 'red' },
    { a: 'الْكَلِمَةِ', t: 'al-kalimati', e: 'the word' },
    SA_COMMA,
    { a: 'وَالثَّانِيَ', t: 'wa-th-thāniya', e: 'and the second' },
    { a: 'عَيْنَ', t: 'ʿayna', e: 'the ʿayn of', c: 'red' },
    { a: 'الْكَلِمَةِ', t: 'al-kalimati', e: 'the word' },
    SA_COMMA,
    { a: 'وَالثَّالِثَ', t: 'wa-th-thālitha', e: 'and the third' },
    { a: 'لَامَ', t: 'lāma', e: 'the lām of', c: 'red' },
    { a: 'الْكَلِمَةِ', t: 'al-kalimati', e: 'the word' },
    { g: '.' },
  ] },

  /* ── وزن ما زاد على ثلاثة أحرف ── */
  { t: 'h2', c: 'blue', ar: 'وَزْنُ مَا زَادَ عَلَى ثَلَاثَةِ أَحْرُفٍ', en: 'Weighing What Exceeds Three Letters' },

  { t: 'line', w: [
    { a: 'فَإِذَا', t: 'fa-idhā', e: 'so when' },
    { a: 'زَادَتِ', t: 'zādati', e: 'exceeds' },
    { a: 'الْكَلِمَةُ', t: 'al-kalimatu', e: 'the word' },
    { a: 'عَلَى', t: 'ʿalā', e: 'beyond' },
    { a: 'ثَلَاثَةِ', t: 'thalāthati', e: 'three' },
    { a: 'أَحْرُفٍ', t: 'aḥrufin', e: 'letters' },
    { g: ':' },
  ] },

  { t: 'line', w: [
    { g: '١ -' },
    { a: 'فَإِنْ', t: 'fa-in', e: 'if' },
    { a: 'كَانَتْ', t: 'kānat', e: 'is' },
    { a: 'زِيَادَتُهَا', t: 'ziyādatuhā', e: 'its increase' },
    { a: 'نَاشِئَةً', t: 'nāshiʾatan', e: 'arising' },
    { a: 'مِنْ', t: 'min', e: 'from', c: 'red' },
    { a: 'أَصْلِ', t: 'aṣli', e: 'the root of', c: 'red' },
    { a: 'الْكَلِمَةِ', t: 'al-kalimati', e: 'the word', c: 'red' },
    { a: 'عَلَى', t: 'ʿalā', e: 'being of' },
    { a: 'أَرْبَعَةِ', t: 'arbaʿati', e: 'four' },
    { a: 'أَحْرُفٍ', t: 'aḥrufin', e: 'letters' },
    { a: 'أَوْ', t: 'aw', e: 'or' },
    { a: 'خَمْسَةٍ', t: 'khamsatin', e: 'five' },
    SA_COMMA,
    { a: 'زِدْتَ', t: 'zidta', e: 'you add' },
    { a: 'فِي', t: 'fī', e: 'in' },
    { a: 'الْمِيزَانِ', t: 'al-mīzāni', e: 'the scale' },
    { a: 'لَامًا', t: 'lāman', e: 'a lām' },
    { a: 'أَوْ', t: 'aw', e: 'or' },
    { a: 'لَامَيْنِ', t: 'lāmayni', e: 'two lāms' },
    { a: 'عَلَى', t: 'ʿalā', e: 'onto' },
    { a: 'أَحْرُفِ', t: 'aḥrufi', e: 'the letters' },
    { g: '(ف ع ل)' },
    SA_COMMA,
    { a: 'فَتَقُولُ', t: 'fa-taqūlu', e: 'so you say' },
    { a: 'فِي', t: 'fī', e: 'for' },
    { a: 'وَزْنِ', t: 'wazni', e: 'the measure of' },
    { a: 'دَحْرَجَ', t: 'daḥraja', e: 'daḥraja (to roll)', n: 'quadriliteral root' },
    { g: ':' },
    { a: 'فَعْلَلَ', t: 'faʿlala', e: 'faʿlala' },
    SA_COMMA,
    { g: '(' },
    { a: 'بَعْثَرَ', t: 'baʿthara', e: 'baʿthara (to scatter)', c: 'red' },
    { a: 'وَسْوَسَ', t: 'waswasa', e: 'waswasa (to whisper)', c: 'red' },
    { a: 'جَعْفَر', t: 'jaʿfar', e: 'jaʿfar (a stream)', c: 'red' },
    { a: 'ثَعْلَب', t: 'thaʿlab', e: 'thaʿlab (fox)', c: 'red' },
    { g: ')' },
    { a: 'وَفِي', t: 'wa-fī', e: 'and for' },
    { a: 'وَزْنِ', t: 'wazni', e: 'the measure of' },
    { a: 'جَحْمَرِش', t: 'jaḥmarish', e: 'jaḥmarish (old woman)', n: 'quinqueliteral root' },
    { g: ':' },
    { a: 'فَعْلَلِل', t: 'faʿlalil', e: 'faʿlalil' },
    { g: '.' },
  ] },

  { t: 'line', w: [
    { g: '٢ -' },
    { a: 'وَإِنْ', t: 'wa-in', e: 'and if' },
    { a: 'كَانَتْ', t: 'kānat', e: 'it is' },
    { a: 'نَاشِئَةً', t: 'nāshiʾatan', e: 'arising' },
    { a: 'مِنْ', t: 'min', e: 'from', c: 'red' },
    { a: 'تَكْرِيرِ', t: 'takrīri', e: 'the repetition of', c: 'red' },
    { a: 'حَرْفٍ', t: 'ḥarfin', e: 'a letter' },
    { a: 'مِنْ', t: 'min', e: 'from' },
    { a: 'أُصُولِ', t: 'uṣūli', e: 'the roots of' },
    { a: 'الْكَلِمَةِ', t: 'al-kalimati', e: 'the word' },
    SA_COMMA,
    { a: 'كَرَّرْتَ', t: 'karrarta', e: 'you repeat' },
    { a: 'مَا', t: 'mā', e: 'what' },
    { a: 'يُقَابِلُهُ', t: 'yuqābiluhu', e: 'corresponds to it' },
    { a: 'فِي', t: 'fī', e: 'in' },
    { a: 'الْمِيزَانِ', t: 'al-mīzāni', e: 'the scale' },
    SA_COMMA,
    { a: 'فَتَقُولُ', t: 'fa-taqūlu', e: 'so you say' },
    { a: 'فِي', t: 'fī', e: 'for' },
    { a: 'وَزْنِ', t: 'wazni', e: 'the measure of' },
    { a: 'قَدَّمَ', t: 'qaddama', e: 'qaddama (he advanced)' },
    { a: 'مَثَلًا', t: 'mathalan', e: 'for example' },
    SA_COMMA,
    { a: 'بِتَشْدِيدِ', t: 'bi-tashdīdi', e: 'with a doubling of' },
    { a: 'الْعَيْنِ', t: 'al-ʿayni', e: 'the ʿayn' },
    { g: ':' },
    { a: 'فَعَّلَ', t: 'faʿʿala', e: 'faʿʿala' },
    SA_COMMA,
    { a: 'وَفِي', t: 'wa-fī', e: 'and for' },
    { a: 'وَزْنِ', t: 'wazni', e: 'the measure of' },
    { a: 'جَلْبَبَ', t: 'jalbaba', e: 'jalbaba (he clothed)' },
    { g: ':' },
    { a: 'فَعْلَلَ', t: 'faʿlala', e: 'faʿlala' },
    { g: '؛' },
    { a: 'وَيُقَالُ', t: 'wa-yuqālu', e: 'and it is called' },
    { a: 'لَهُ', t: 'lahu', e: 'for it' },
    { a: 'مُضَعَّفُ', t: 'muḍaʿʿafu', e: 'the doubled-' },
    { a: 'الْعَيْنِ', t: 'al-ʿayni', e: 'ʿayn' },
    { a: 'أَوِ', t: 'awi', e: 'or' },
    { a: 'اللَّامِ', t: 'al-lāmi', e: 'lām verb' },
    { g: '.' },
  ] },

  { t: 'line', w: [
    { g: '٣ -' },
    { a: 'وَإِنْ', t: 'wa-in', e: 'and if' },
    { a: 'كَانَتِ', t: 'kānati', e: 'is' },
    { a: 'الزِّيَادَةُ', t: 'az-ziyādatu', e: 'the increase' },
    { a: 'نَاشِئَةً', t: 'nāshiʾatan', e: 'arising' },
    { a: 'مِنْ', t: 'min', e: 'from', c: 'red' },
    { a: 'زِيَادَةِ', t: 'ziyādati', e: 'the adding of', c: 'red' },
    { a: 'حَرْفٍ', t: 'ḥarfin', e: 'a letter', c: 'red' },
    { a: 'أَوْ', t: 'aw', e: 'or' },
    { a: 'أَكْثَرَ', t: 'akthara', e: 'more' },
    { a: 'مِنْ', t: 'min', e: 'from' },
    { a: 'حُرُوفِ', t: 'ḥurūfi', e: 'the letters of' },
    { a: 'سَأَلْتُمُونِيهَا', t: 'saʾaltumūnīhā', e: '"saʾaltumūnīhā"', n: 'mnemonic gathering the ten augmentative letters' },
    SA_COMMA,
    { a: 'الَّتِي', t: 'allatī', e: 'which' },
    { a: 'هِيَ', t: 'hiya', e: 'are' },
    { a: 'حُرُوفُ', t: 'ḥurūfu', e: 'the letters of' },
    { a: 'الزِّيَادَةِ', t: 'az-ziyādati', e: 'augmentation' },
    SA_COMMA,
    { a: 'قَابَلْتَ', t: 'qābalta', e: 'you match' },
    { a: 'الْأُصُولَ', t: 'al-uṣūla', e: 'the root-letters' },
    { a: 'بِالْأُصُولِ', t: 'bi-l-uṣūli', e: 'with root-letters (ف ع ل)' },
    SA_COMMA,
    { a: 'وَعَبَّرْتَ', t: 'wa-ʿabbarta', e: 'and you express' },
    { a: 'عَنِ', t: 'ʿani', e: 'for' },
    { a: 'الزَّائِدِ', t: 'az-zāʾidi', e: 'the added letter' },
    { a: 'بِلَفْظِهِ', t: 'bi-lafẓihi', e: 'by its own form' },
    SA_COMMA,
    { a: 'فَتَقُولُ', t: 'fa-taqūlu', e: 'so you say' },
    { a: 'فِي', t: 'fī', e: 'for' },
    { a: 'وَزْنِ', t: 'wazni', e: 'the measure of' },
    { a: 'قَائِم', t: 'qāʾim', e: 'qāʾim (standing)' },
    { a: 'مَثَلًا', t: 'mathalan', e: 'for example' },
    { g: ':' },
    { a: 'فَاعِل', t: 'fāʿil', e: 'fāʿil' },
    SA_COMMA,
    { a: 'وَفِي', t: 'wa-fī', e: 'and for' },
    { a: 'وَزْنِ', t: 'wazni', e: 'the measure of' },
    { a: 'تَقَدَّمَ', t: 'taqaddama', e: 'taqaddama (he came forward)' },
    { g: ':' },
    { a: 'تَفَعَّلَ', t: 'tafaʿʿala', e: 'tafaʿʿala' },
    SA_COMMA,
    { a: 'وَفِي', t: 'wa-fī', e: 'and for' },
    { a: 'وَزْنِ', t: 'wazni', e: 'the measure of' },
    { a: 'اسْتَخْرَجَ', t: 'istakhraja', e: 'istakhraja (he extracted)' },
    { g: ':' },
    { a: 'اسْتَفْعَلَ', t: 'istafʿala', e: 'istafʿala' },
    SA_COMMA,
    { a: 'وَفِي', t: 'wa-fī', e: 'and for' },
    { a: 'وَزْنِ', t: 'wazni', e: 'the measure of' },
    { a: 'مُجْتَهِد', t: 'mujtahid', e: 'mujtahid (diligent)' },
    { g: ':' },
    { a: 'مُفْتَعِل', t: 'muftaʿil', e: 'muftaʿil' },
    SA_COMMA,
    { a: 'وَهَكَذَا', t: 'wa-hākadhā', e: 'and so on' },
    { g: '.' },
  ] },

  { t: 'line', w: [
    { a: 'مَرْمَرِيس', t: 'marmarīs', e: 'marmarīs (a hardy she-camel)', n: 'a rare six-form pattern with reduplicated roots', c: 'red' },
    { g: '=' },
    { a: 'فَعْفَعِيل', t: 'faʿfaʿīl', e: 'faʿfaʿīl', c: 'red' },
    { g: '.' },
  ] },

  /* ── وزن الحالات الخاصة ── */
  { t: 'h2', c: 'blue', ar: 'وَزْنُ الْحَالَاتِ الْخَاصَّةِ', en: 'Weighing the Special Cases' },

  { t: 'line', w: [
    { g: '٤ -' },
    { a: 'وَفِيمَا', t: 'wa-fīmā', e: 'and in the case' },
    { a: 'إِذَا', t: 'idhā', e: 'when' },
    { a: 'كَانَ', t: 'kāna', e: 'is' },
    { a: 'الزَّائِدُ', t: 'az-zāʾidu', e: 'the added letter' },
    { a: 'مُبْدَلًا', t: 'mubdalan', e: 'substituted' },
    { a: 'مِنْ', t: 'min', e: 'from', c: 'red' },
    { a: 'تَاءِ', t: 'tāʾi', e: 'the tāʾ of', c: 'red' },
    { a: 'الِافْتِعَالِ', t: 'al-iftiʿāli', e: 'iftiʿāl (form VIII)', c: 'red' },
    SA_COMMA,
    { a: 'يُنْطَقُ', t: 'yunṭaqu', e: 'is pronounced' },
    { a: 'بِهَا', t: 'bihā', e: 'as it (the original tāʾ)' },
    { a: 'نَظَرًا', t: 'naẓaran', e: 'having regard' },
    { a: 'إِلَى', t: 'ilā', e: 'to' },
    { a: 'الْأَصْلِ', t: 'al-aṣli', e: 'the original' },
    SA_COMMA,
    { a: 'يُقَالُ', t: 'yuqālu', e: 'it is said' },
    { a: 'مَثَلًا', t: 'mathalan', e: 'for example' },
    { a: 'فِي', t: 'fī', e: 'for' },
    { a: 'وَزْنِ', t: 'wazni', e: 'the measure of' },
    { a: 'اضْطَرَبَ', t: 'iḍṭaraba', e: 'iḍṭaraba (he was agitated)' },
    { g: ':' },
    { a: 'افْتَعَلَ', t: 'iftaʿala', e: 'iftaʿala' },
    SA_COMMA,
    { a: 'لَا', t: 'lā', e: 'not' },
    { a: 'افْطَعَلَ', t: 'ifṭaʿala', e: 'ifṭaʿala' },
    SA_COMMA,
    { a: 'وَقَدْ', t: 'wa-qad', e: 'and indeed' },
    { a: 'أَجَازَهُ', t: 'ajāzahu', e: 'it was permitted by' },
    { a: 'الرَّضِيُّ', t: 'ar-raḍiyyu', e: 'ar-Raḍī', n: 'the grammarian al-Raḍī al-Astarābādhī' },
    { g: '.' },
  ] },

  { t: 'line', w: [
    { a: 'صَلَحَ', t: 'ṣalaḥa', e: 'ṣalaḥa (it was sound)' },
    { g: '–' },
    { a: 'اصْتَلَحَ', t: 'iṣtalaḥa', e: 'iṣtalaḥa (original form)', c: 'red' },
    { g: '–' },
    { a: 'اصْطَلَحَ', t: 'iṣṭalaḥa', e: 'iṣṭalaḥa (after substitution)', c: 'red' },
  ] },

  { t: 'page', n: '٢' },

  { t: 'line', w: [
    { a: 'زَجَرَ', t: 'zajara', e: 'zajara (he rebuked)', n: 'to chide, rebuke or forbid' },
    { g: '–' },
    { a: 'ازْتَجَرَ', t: 'iztajara', e: 'iztajara (original form)', c: 'red' },
    { g: '–' },
    { a: 'ازْدَجَرَ', t: 'izdajara', e: 'izdajara (after substitution)', c: 'red' },
  ] },

  { t: 'line', w: [
    { g: '٥ -' },
    { a: 'وَإِنْ', t: 'wa-in', e: 'and if' },
    { a: 'حَصَلَ', t: 'ḥaṣala', e: 'there occurs' },
    { a: 'حَذْفٌ', t: 'ḥadhfun', e: 'an elision', c: 'red' },
    { a: 'فِي', t: 'fī', e: 'in', c: 'red' },
    { a: 'الْمَوْزُونِ', t: 'al-mawzūni', e: 'the weighed word', c: 'red' },
    { a: 'حُذِفَ', t: 'ḥudhifa', e: 'is elided' },
    { a: 'مَا', t: 'mā', e: 'what' },
    { a: 'يُقَابِلُهُ', t: 'yuqābiluhu', e: 'corresponds to it' },
    { a: 'فِي', t: 'fī', e: 'in' },
    { a: 'الْمِيزَانِ', t: 'al-mīzāni', e: 'the scale' },
    SA_COMMA,
    { a: 'فَتَقُولُ', t: 'fa-taqūlu', e: 'so you say' },
    { a: 'فِي', t: 'fī', e: 'for' },
    { a: 'وَزْنِ', t: 'wazni', e: 'the measure of' },
    { a: 'قُلْ', t: 'qul', e: 'qul (say!)', n: 'from qāla; the ʿayn (و) is dropped' },
    { a: 'مَثَلًا', t: 'mathalan', e: 'for example' },
    { g: ':' },
    { a: 'فُلْ', t: 'ful', e: 'ful' },
    SA_COMMA,
    { a: 'وَفِي', t: 'wa-fī', e: 'and for' },
    { a: 'وَزْنِ', t: 'wazni', e: 'the measure of' },
    { a: 'قَاضٍ', t: 'qāḍin', e: 'qāḍin (a judge)', n: 'the lām (ي) is dropped' },
    { g: ':' },
    { a: 'فَاعٍ', t: 'fāʿin', e: 'fāʿin' },
    SA_COMMA,
    { a: 'وَفِي', t: 'wa-fī', e: 'and for' },
    { a: 'وَزْنِ', t: 'wazni', e: 'the measure of' },
    { a: 'عِدَةٍ', t: 'ʿidatin', e: 'ʿidah (a promise)', n: 'from waʿd; the fāʾ (و) is dropped' },
    { g: ':' },
    { a: 'عِلَةٍ', t: 'ʿilatin', e: 'ʿilah' },
    { g: '.' },
  ] },

  { t: 'line', w: [
    { g: '٦ -' },
    { a: 'وَإِنْ', t: 'wa-in', e: 'and if' },
    { a: 'حَصَلَ', t: 'ḥaṣala', e: 'there occurs' },
    { a: 'قَلْبٌ', t: 'qalbun', e: 'a transposition', c: 'red' },
    { g: '(' },
    { a: 'الْمَكَانِ', t: 'al-makāni', e: 'of place (metathesis)', c: 'red' },
    { g: ')' },
    { a: 'فِي', t: 'fī', e: 'in', c: 'red' },
    { a: 'الْمَوْزُونِ', t: 'al-mawzūni', e: 'the weighed word', c: 'red' },
    SA_COMMA,
    { a: 'حَصَلَ', t: 'ḥaṣala', e: 'it occurs' },
    { a: 'أَيْضًا', t: 'ayḍan', e: 'also' },
    { a: 'فِي', t: 'fī', e: 'in' },
    { a: 'الْمِيزَانِ', t: 'al-mīzāni', e: 'the scale' },
    SA_COMMA,
    { a: 'فَيُقَالُ', t: 'fa-yuqālu', e: 'so it is said' },
    { a: 'مَثَلًا', t: 'mathalan', e: 'for example' },
    { a: 'فِي', t: 'fī', e: 'for' },
    { a: 'وَزْنِ', t: 'wazni', e: 'the measure of' },
    { a: 'جَاهٍ', t: 'jāhin', e: 'jāh (rank)', n: 'metathesis of wajh (و ج ه)' },
    { g: ':' },
    { a: 'عَفَلٍ', t: 'ʿafalin', e: 'ʿafal' },
    SA_COMMA,
    { a: 'بِتَقْدِيمِ', t: 'bi-taqdīmi', e: 'by advancing' },
    { a: 'الْعَيْنِ', t: 'al-ʿayni', e: 'the ʿayn' },
    { a: 'عَلَى', t: 'ʿalā', e: 'before' },
    { a: 'الْفَاءِ', t: 'al-fāʾi', e: 'the fāʾ' },
    { g: '.' },
  ] },
];
