/* ── Shadhā al-ʿArf — التقسيم الأول للفعل (Worksheet 3) ──
   الباب الأول في الفعل · التقسيم الأول: ماضٍ ومضارع وأمر · أسماء الأفعال
   Reuses the SA_* constants from wk01-muqaddimah.js (load after it).             */

const DATA_WK03 = [
  { t: 'page', n: '١' },

  { t: 'h1', c: 'blue', ar: 'الْبَابُ الْأَوَّلُ: فِي الْفِعْلِ', en: 'Chapter One — The Verb (it has several divisions)' },
  { t: 'h2', c: 'blue', ar: 'التَّقْسِيمُ الْأَوَّلُ لِلْفِعْلِ: إِلَى مَاضٍ وَمُضَارِعٍ وَأَمْرٍ', en: 'First Division: Past, Present & Imperative' },

  /* ── الماضي ── */
  { t: 'h2', c: 'blue', ar: 'مَاضٍ', en: 'The Past (al-māḍī)' },

  { t: 'line', w: [
    { a: 'فَالْمَاضِي', t: 'fa-l-māḍī', e: 'the past tense', c: 'red' },
    { g: ':' },
    { a: 'مَا', t: 'mā', e: 'is that which' },
    { a: 'يَدُلُّ', t: 'yadullu', e: 'denotes' },
    { a: 'عَلَى', t: 'ʿalā', e: 'upon' },
    { a: 'حُدُوثِ', t: 'ḥudūthi', e: 'the occurrence of' },
    { a: 'شَيْءٍ', t: 'shayʾin', e: 'a thing' },
    { a: 'قَبْلَ', t: 'qabla', e: 'before' },
    { a: 'زَمَنِ', t: 'zamani', e: 'the time of' },
    { a: 'التَّكَلُّمِ', t: 'at-takallumi', e: 'speaking' },
    { a: 'غَالِبًا', t: 'ghāliban', e: 'usually', c: 'red' },
    SA_COMMA,
    SA_NAHW,
    { a: 'قَامَ', t: 'qāma', e: '"he stood"' },
    SA_COMMA,
    { a: 'وَقَعَدَ', t: 'wa-qaʿada', e: 'and "he sat"' },
    SA_COMMA,
    { a: 'وَأَكَلَ', t: 'wa-akala', e: 'and "he ate"' },
    SA_COMMA,
    { a: 'وَشَرِبَ', t: 'wa-shariba', e: 'and "he drank"' },
    { g: '.' },
  ] },

  { t: 'line', w: [
    { a: 'خَرَجَ', t: 'kharaja', e: 'excluded is', c: 'red' },
    { a: 'مِنْهُ', t: 'minhu', e: 'from it', c: 'red' },
    { a: 'أَفْعَالُ', t: 'afʿālu', e: 'the verbs of' },
    { a: 'الْعُقُودِ', t: 'al-ʿuqūdi', e: 'contracts (ʿuqūd)', n: 'performative verbs — present in meaning though past in form' },
    SA_COMMA,
    SA_NAHW, { g: ':' },
    { a: 'بِعْتُكَ', t: 'biʿtuka', e: '"I hereby sell to you"' },
    SA_COMMA,
    { a: 'زَوَّجْتُكَ', t: 'zawwajtuka', e: '"I hereby marry you (to her)"' },
  ] },

  { t: 'line', w: [
    { a: 'وَمِثَالٌ', t: 'wa-mithālun', e: 'and an example (of past form, other sense)' },
    { g: ':' },
    { a: 'إِنْ', t: 'in', e: 'if' },
    { a: 'زُرْتَنِي', t: 'zurtanī', e: 'you visit me', n: 'past form, future meaning' },
    { a: 'أُكْرِمْكَ', t: 'ukrimka', e: 'I will honour you' },
    SA_COMMA,
    { a: 'وَ', t: 'wa', e: 'and' },
    SA_OPEN,
    { a: 'إِنَّا', t: 'innā', e: 'Indeed We', q: 1 },
    { a: 'أَعْطَيْنَاكَ', t: 'aʿṭaynāka', e: 'have given you', q: 1 },
    { a: 'الْكَوْثَرَ', t: 'al-kawthara', e: 'al-Kawthar', q: 1 },
    SA_CLOSE,
    { g: '[الكوثر: ١]' },
  ] },

  { t: 'line', w: [
    { a: 'وَعَلَامَتُهُ', t: 'wa-ʿalāmatuhu', e: 'and its sign', c: 'red' },
    { a: 'أَنْ', t: 'an', e: 'is that' },
    { a: 'يَقْبَلَ', t: 'yaqbala', e: 'it accepts' },
    { a: 'تَاءَ', t: 'tāʾa', e: 'the tāʾ of', c: 'red' },
    { a: 'الْفَاعِلِ', t: 'al-fāʿili', e: 'the doer (tāʾ al-fāʿil)', c: 'red' },
    SA_COMMA,
    SA_NAHW,
    { a: 'قَرَأْتُ', t: 'qaraʾtu', e: '"I read"' },
    { g: '.' },
    { a: 'وَتَاءَ', t: 'wa-tāʾa', e: 'and the tāʾ of', c: 'red' },
    { a: 'التَّأْنِيثِ', t: 'at-taʾnīthi', e: 'feminisation', c: 'red' },
    { a: 'السَّاكِنَةَ', t: 'as-sākinata', e: 'quiescent', c: 'red', n: 'the silent tāʾ of feminisation' },
    SA_COMMA,
    SA_NAHW,
    { a: 'قَرَأَتْ', t: 'qaraʾat', e: '"she read"' },
    { a: 'هِنْدُ', t: 'hindu', e: 'Hind' },
    { g: '.' },
  ] },

  /* ── المضارع ── */
  { t: 'h2', c: 'blue', ar: 'مُضَارِعٌ', en: 'The Present (al-muḍāriʿ)' },

  { t: 'line', w: [
    { a: 'وَالْمُضَارِعُ', t: 'wa-l-muḍāriʿu', e: 'the present tense', c: 'red' },
    { g: ':' },
    { a: 'مَا', t: 'mā', e: 'is that which' },
    { a: 'دَلَّ', t: 'dalla', e: 'denotes' },
    { a: 'عَلَى', t: 'ʿalā', e: 'upon' },
    { a: 'حُدُوثِ', t: 'ḥudūthi', e: 'the occurrence of' },
    { a: 'شَيْءٍ', t: 'shayʾin', e: 'a thing' },
    { a: 'فِي', t: 'fī', e: 'in' },
    { a: 'زَمَنِ', t: 'zamani', e: 'the time of' },
    { a: 'التَّكَلُّمِ', t: 'at-takallumi', e: 'speaking' },
    { a: 'أَوْ', t: 'aw', e: 'or' },
    { a: 'بَعْدَهُ', t: 'baʿdahu', e: 'after it' },
    { a: 'غَالِبًا', t: 'ghāliban', e: 'usually', c: 'red' },
    { a: 'أَوْ', t: 'aw', e: 'or' },
    { a: 'لِلِاسْتِمْرَارِ', t: 'li-l-istimrāri', e: 'for continuity', c: 'red' },
    SA_COMMA,
    SA_NAHW,
    { a: 'يَقْرَأُ', t: 'yaqraʾu', e: '"he reads"' },
    { a: 'وَيَكْتُبُ', t: 'wa-yaktubu', e: 'and "he writes"' },
    SA_COMMA,
    { a: 'فَهُوَ', t: 'fa-huwa', e: 'so it is' },
    { a: 'صَالِحٌ', t: 'ṣāliḥun', e: 'suitable' },
    { a: 'لِلْحَالِ', t: 'li-l-ḥāli', e: 'for the present' },
    { a: 'وَالِاسْتِقْبَالِ', t: 'wa-l-istiqbāli', e: 'and the future' },
    { g: '.' },
  ] },

  { t: 'line', w: [
    { a: 'خَرَجَ', t: 'kharaja', e: 'excluded is', c: 'red' },
    { a: 'مِنْهُ', t: 'minhu', e: 'from it', c: 'red' },
    SA_OPEN,
    { a: 'لَمْ', t: 'lam', e: 'not', q: 1 },
    { a: 'يَلِدْ', t: 'yalid', e: 'He begot', q: 1, n: '"lam" turns the present form into past meaning' },
    { a: 'وَلَمْ', t: 'wa-lam', e: 'and not', q: 1 },
    { a: 'يُولَدْ', t: 'yūlad', e: 'was He begotten', q: 1 },
    SA_CLOSE,
    { g: '[الإخلاص: ٣]' },
  ] },

  { t: 'line', w: [
    { a: 'وَيُعَيِّنُهُ', t: 'wa-yuʿayyinuhu', e: 'and it is fixed' },
    { a: 'لِلْحَالِ', t: 'li-l-ḥāli', e: 'to the present', c: 'red' },
    { a: 'لَامُ', t: 'lāmu', e: 'by the lām of' },
    { a: 'الِابْتِدَاءِ', t: 'al-ibtidāʾi', e: 'inception (lām al-ibtidāʾ)' },
    SA_COMMA,
    { a: 'وَلَا', t: 'wa-lā', e: 'and "lā"' },
    { a: 'وَمَا', t: 'wa-mā', e: 'and "mā"' },
    { a: 'النَّافِيَتَانِ', t: 'an-nāfiyatāni', e: 'the two negatives' },
    SA_COMMA,
    SA_NAHW, { g: ':' },
  ] },

  { t: 'line', w: [
    SA_OPEN,
    { a: 'إِنِّي', t: 'innī', e: 'indeed it', q: 1 },
    { a: 'لَيَحْزُنُنِي', t: 'la-yaḥzununī', e: 'grieves me', q: 1, c: 'red', n: 'lām al-ibtidāʾ fixes it to the present' },
    { a: 'أَنْ', t: 'an', e: 'that', q: 1 },
    { a: 'تَذْهَبُوا', t: 'tadhhabū', e: 'you take', q: 1 },
    { a: 'بِهِ', t: 'bihi', e: 'him away', q: 1 },
    SA_CLOSE,
    { g: '[يوسف: ١٣]' },
  ] },

  { t: 'line', w: [
    { a: 'خَرَجَ', t: 'kharaja', e: 'excluded is', c: 'red' },
    { a: 'مِنْهُ', t: 'minhu', e: 'from it', c: 'red' },
    SA_OPEN,
    { a: 'إِنَّ', t: 'inna', e: 'indeed', q: 1 },
    { a: 'رَبَّكَ', t: 'rabbaka', e: 'your Lord', q: 1 },
    { a: 'لَيَحْكُمُ', t: 'la-yaḥkumu', e: 'will judge', q: 1, c: 'red' },
    { a: 'بَيْنَهُمْ', t: 'baynahum', e: 'between them', q: 1 },
    { a: 'يَوْمَ', t: 'yawma', e: 'on the Day of', q: 1 },
    { a: 'الْقِيَامَةِ', t: 'al-qiyāmati', e: 'Resurrection', q: 1, n: 'future despite the lām — so not fixed to the present' },
    SA_CLOSE,
    { g: '[النحل: ١٢٤]' },
  ] },

  { t: 'line', w: [
    SA_OPEN,
    { a: 'لَا', t: 'lā', e: 'not', q: 1, c: 'red', n: '"lā" the negator fixes it to the present' },
    { a: 'يُحِبُّ', t: 'yuḥibbu', e: 'loves', q: 1 },
    { a: 'اللَّهُ', t: 'allāhu', e: 'God', q: 1 },
    { a: 'الْجَهْرَ', t: 'al-jahra', e: 'the open utterance', q: 1 },
    { a: 'بِالسُّوءِ', t: 'bi-s-sūʾi', e: 'of evil', q: 1 },
    { a: 'مِنَ', t: 'mina', e: 'in', q: 1 },
    { a: 'الْقَوْلِ', t: 'al-qawli', e: 'speech', q: 1 },
    SA_CLOSE,
    { g: '[النساء: ١٤٨]' },
  ] },

  { t: 'line', w: [
    SA_OPEN,
    { a: 'وَمَا', t: 'wa-mā', e: 'and not', q: 1, c: 'red', n: '"mā" the negator fixes "tadrī" to the present' },
    { a: 'تَدْرِي', t: 'tadrī', e: 'knows', q: 1 },
    { a: 'نَفْسٌ', t: 'nafsun', e: 'any soul', q: 1 },
    { a: 'مَاذَا', t: 'mādhā', e: 'what', q: 1 },
    { a: 'تَكْسِبُ', t: 'taksibu', e: 'it will earn', q: 1 },
    { a: 'غَدًا', t: 'ghadan', e: 'tomorrow', q: 1 },
    SA_CLOSE,
    { g: '[لقمان: ٣٤]' },
  ] },

  { t: 'line', w: [
    { a: 'وَيُعَيِّنُهُ', t: 'wa-yuʿayyinuhu', e: 'and it is fixed' },
    { a: 'لِلِاسْتِقْبَالِ', t: 'li-l-istiqbāli', e: 'to the future', c: 'red' },
    { a: 'السِّينُ', t: 'as-sīnu', e: 'by "sa-"', c: 'red' },
    { a: 'وَالسَّوْفُ', t: 'wa-s-sawfu', e: 'and "sawfa"', c: 'red' },
    { a: 'وَلَنْ', t: 'wa-lan', e: 'and "lan"', c: 'red' },
    { a: 'وَأَنْ', t: 'wa-an', e: 'and "an"', c: 'red' },
    { a: 'وَإِنْ', t: 'wa-in', e: 'and "in"', c: 'red' },
    SA_COMMA,
    SA_NAHW, { g: ':' },
  ] },

  { t: 'line', w: [
    SA_OPEN,
    { a: 'سَيَقُولُ', t: 'sa-yaqūlu', e: 'will say', q: 1, c: 'red', n: 'the "s-" of the future' },
    { a: 'السُّفَهَاءُ', t: 'as-sufahāʾu', e: 'the foolish', q: 1 },
    { a: 'مِنَ', t: 'mina', e: 'among', q: 1 },
    { a: 'النَّاسِ', t: 'an-nāsi', e: 'the people', q: 1 },
    { a: 'مَا', t: 'mā', e: 'what', q: 1 },
    { a: 'وَلَّاهُمْ', t: 'wallāhum', e: 'has turned them', q: 1 },
    { a: 'عَنْ', t: 'ʿan', e: 'from', q: 1 },
    { a: 'قِبْلَتِهِمُ', t: 'qiblatihimu', e: 'their qiblah', q: 1 },
    { a: 'الَّتِي', t: 'allatī', e: 'which', q: 1 },
    { a: 'كَانُوا', t: 'kānū', e: 'they were', q: 1 },
    { a: 'عَلَيْهَا', t: 'ʿalayhā', e: 'upon', q: 1 },
    SA_CLOSE,
    { g: '[البقرة: ١٤٢]' },
  ] },

  { t: 'line', w: [
    SA_OPEN,
    { a: 'وَلَسَوْفَ', t: 'wa-la-sawfa', e: 'and surely soon', q: 1, c: 'red', n: '"sawfa" of the future' },
    { a: 'يُعْطِيكَ', t: 'yuʿṭīka', e: 'will give you', q: 1 },
    { a: 'رَبُّكَ', t: 'rabbuka', e: 'your Lord', q: 1 },
    { a: 'فَتَرْضَى', t: 'fa-tarḍā', e: 'and you will be content', q: 1 },
    SA_CLOSE,
    { g: '[الضحى: ٥]' },
  ] },

  { t: 'line', w: [
    SA_OPEN,
    { a: 'لَنْ', t: 'lan', e: 'never', q: 1, c: 'red', n: '"lan" fixes it to the future' },
    { a: 'تَنَالُوا', t: 'tanālū', e: 'will you attain', q: 1 },
    { a: 'الْبِرَّ', t: 'al-birra', e: 'righteousness', q: 1 },
    { a: 'حَتَّى', t: 'ḥattā', e: 'until', q: 1 },
    { a: 'تُنْفِقُوا', t: 'tunfiqū', e: 'you spend', q: 1 },
    { a: 'مِمَّا', t: 'mimmā', e: 'from what', q: 1 },
    { a: 'تُحِبُّونَ', t: 'tuḥibbūna', e: 'you love', q: 1 },
    SA_CLOSE,
    { g: '[آل عمران: ٩٢]' },
  ] },

  { t: 'line', w: [
    SA_OPEN,
    { a: 'وَأَنْ', t: 'wa-an', e: 'and that', q: 1, c: 'red', n: '"an" fixes it to the future' },
    { a: 'تَصُومُوا', t: 'taṣūmū', e: 'you fast', q: 1 },
    { a: 'خَيْرٌ', t: 'khayrun', e: 'is better', q: 1 },
    { a: 'لَكُمْ', t: 'lakum', e: 'for you', q: 1 },
    SA_CLOSE,
    { g: '[البقرة: ١٨٤]' },
  ] },

  { t: 'line', w: [
    SA_OPEN,
    { a: 'إِنْ', t: 'in', e: 'if', q: 1, c: 'red', n: '"in" (conditional) fixes it to the future' },
    { a: 'يَنْصُرْكُمُ', t: 'yanṣurkumu', e: 'helps you', q: 1 },
    { a: 'اللَّهُ', t: 'allāhu', e: 'God', q: 1 },
    { a: 'فَلَا', t: 'fa-lā', e: 'then no', q: 1 },
    { a: 'غَالِبَ', t: 'ghāliba', e: 'overcomer', q: 1 },
    { a: 'لَكُمْ', t: 'lakum', e: 'for you', q: 1 },
    SA_CLOSE,
    { g: '[آل عمران: ١٦٠]' },
  ] },

  { t: 'line', w: [
    { a: 'وَعَلَامَتُهُ', t: 'wa-ʿalāmatuhu', e: 'and its sign', c: 'red' },
    { g: ':' },
    { a: 'أَنْ', t: 'an', e: 'is that' },
    { a: 'يَصِحَّ', t: 'yaṣiḥḥa', e: 'it is valid' },
    { a: 'وُقُوعُهُ', t: 'wuqūʿuhu', e: 'for it to occur' },
    { a: 'بَعْدَ', t: 'baʿda', e: 'after' },
    { a: 'لَمْ', t: 'lam', e: '"lam"', c: 'red' },
    SA_COMMA,
    SA_NAHW, { g: ':' },
    SA_OPEN,
    { a: 'لَمْ', t: 'lam', e: 'not', q: 1 },
    { a: 'يَلِدْ', t: 'yalid', e: 'He begot', q: 1 },
    { a: 'وَلَمْ', t: 'wa-lam', e: 'and not', q: 1 },
    { a: 'يُولَدْ', t: 'yūlad', e: 'was He begotten', q: 1 },
    SA_CLOSE,
    { g: '[الإخلاص: ٣]' },
  ] },

  { t: 'line', w: [
    { a: 'وَلَا', t: 'wa-lā', e: 'and there is no' },
    { a: 'بُدَّ', t: 'budda', e: 'escaping' },
    { a: 'أَنْ', t: 'an', e: 'that' },
    { a: 'يَكُونَ', t: 'yakūna', e: 'it be' },
    { a: 'مَبْدُوءًا', t: 'mabdūʾan', e: 'begun' },
    { a: 'بِحَرْفٍ', t: 'bi-ḥarfin', e: 'with a letter' },
    { a: 'مِنْ', t: 'min', e: 'from' },
    { a: 'حُرُوفِ', t: 'ḥurūfi', e: 'the letters of' },
    { a: 'أَنَيْتُ', t: 'anaytu', e: '"anaytu"', c: 'red', n: 'mnemonic for the four prefixes: hamzah · nūn · yāʾ · tāʾ' },
    SA_COMMA,
    { a: 'وَتُسَمَّى', t: 'wa-tusammā', e: 'and they are called' },
    { a: 'أَحْرُفَ', t: 'aḥrufa', e: 'the letters of', c: 'red' },
    { a: 'الْمُضَارَعَةِ', t: 'al-muḍāraʿati', e: 'the present prefix (aḥruf al-muḍāraʿah)', c: 'red' },
    { g: '.' },
  ] },

  /* ── الأمر ── */
  { t: 'h2', c: 'blue', ar: 'أَمْرٌ', en: 'The Imperative (al-amr)' },

  { t: 'line', w: [
    { a: 'وَالْأَمْرُ', t: 'wa-l-amru', e: 'the imperative', c: 'red' },
    { g: ':' },
    { a: 'مَا', t: 'mā', e: 'is that by which' },
    { a: 'يُطْلَبُ', t: 'yuṭlabu', e: 'is sought' },
    { a: 'بِهِ', t: 'bihi', e: '(by it)' },
    { a: 'حُصُولُ', t: 'ḥuṣūlu', e: 'the occurrence of' },
    { a: 'شَيْءٍ', t: 'shayʾin', e: 'a thing' },
    { a: 'بَعْدَ', t: 'baʿda', e: 'after' },
    { a: 'زَمَنِ', t: 'zamani', e: 'the time of' },
    { a: 'التَّكَلُّمِ', t: 'at-takallumi', e: 'speaking' },
    SA_COMMA,
    SA_NAHW,
    { a: 'اجْتَهِدْ', t: 'ijtahid', e: '"strive!"' },
    { g: '.' },
  ] },

  { t: 'line', w: [
    { a: 'وَعَلَامَتُهُ', t: 'wa-ʿalāmatuhu', e: 'and its sign', c: 'red' },
    { a: 'أَنْ', t: 'an', e: 'is that' },
    { a: 'يَقْبَلَ', t: 'yaqbala', e: 'it accepts' },
    { a: 'نُونَ', t: 'nūna', e: 'the nūn of', c: 'red' },
    { a: 'التَّوْكِيدِ', t: 'at-tawkīdi', e: 'emphasis', c: 'red' },
    SA_COMMA,
    { a: 'وَيَاءَ', t: 'wa-yāʾa', e: 'and the yāʾ of', c: 'red' },
    { a: 'الْمُخَاطَبَةِ', t: 'al-mukhāṭabati', e: 'the female addressee', c: 'red' },
    { g: ':' },
    { a: 'مَعَ', t: 'maʿa', e: 'together with' },
    { a: 'دَلَالَتِهِ', t: 'dalālatihi', e: 'its indicating' },
    { a: 'عَلَى', t: 'ʿalā', e: 'of' },
    { a: 'الطَّلَبِ', t: 'aṭ-ṭalabi', e: 'a request (ṭalab)' },
    { g: '.' },
  ] },

  { t: 'page', n: '٢' },

  /* ── أسماء الأفعال ── */
  { t: 'h2', c: 'blue', ar: 'أَسْمَاءُ الْأَفْعَالِ', en: 'Verbal Nouns (asmāʾ al-afʿāl)' },

  { t: 'line', w: [
    { a: 'وَأَمَّا', t: 'wa-ammā', e: 'as for' },
    { a: 'مَا', t: 'mā', e: 'that which' },
    { a: 'يَدُلُّ', t: 'yadullu', e: 'denotes' },
    { a: 'عَلَى', t: 'ʿalā', e: 'upon' },
    { a: 'مَعَانِي', t: 'maʿānī', e: 'the meanings of' },
    { a: 'الْأَفْعَالِ', t: 'al-afʿāli', e: 'verbs' },
    { a: 'وَلَا', t: 'wa-lā', e: 'but does not' },
    { a: 'يَقْبَلُ', t: 'yaqbalu', e: 'accept' },
    { a: 'عَلَامَاتِهَا', t: 'ʿalāmātihā', e: 'their signs' },
    SA_COMMA,
    { a: 'فَيُقَالُ', t: 'fa-yuqālu', e: 'it is called' },
    { a: 'لَهُ', t: 'lahu', e: '(for it)' },
    { a: 'اسْمُ', t: 'ismu', e: 'a noun of', c: 'red' },
    { a: 'فِعْلٍ', t: 'fiʿlin', e: 'a verb (ism fiʿl)', c: 'red' },
    SA_COMMA,
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
    { a: 'عَلَى', t: 'ʿalā', e: 'of' },
    { a: 'ثَلَاثَةِ', t: 'thalāthati', e: 'three' },
    { a: 'أَقْسَامٍ', t: 'aqsāmin', e: 'kinds' },
    { g: ':' },
  ] },

  { t: 'line', w: [
    { a: 'اسْمُ', t: 'ismu', e: 'a noun of', c: 'red' },
    { a: 'فِعْلٍ', t: 'fiʿlin', e: 'a past', c: 'red' },
    { a: 'مَاضٍ', t: 'māḍin', e: 'verb (ism fiʿl māḍī)', c: 'red' },
    SA_COMMA,
    SA_NAHW,
    { a: 'هَيْهَاتَ', t: 'hayhāta', e: '"hayhāta" (far is it!)' },
    { a: 'وَشَتَّانَ', t: 'wa-shattāna', e: 'and "shattāna" (how different!)' },
    SA_COMMA,
    { a: 'بِمَعْنَى', t: 'bi-maʿnā', e: 'meaning' },
    { a: 'بَعُدَ', t: 'baʿuda', e: '"it became far"' },
    { a: 'وَافْتَرَقَ', t: 'wa-ftaraqa', e: 'and "they parted"' },
    { g: '.' },
  ] },

  { t: 'line', w: [
    { a: 'وَاسْمُ', t: 'wa-smu', e: 'and a noun of', c: 'red' },
    { a: 'فِعْلٍ', t: 'fiʿlin', e: 'a present', c: 'red' },
    { a: 'مُضَارِعٍ', t: 'muḍāriʿin', e: 'verb (ism fiʿl muḍāriʿ)', c: 'red' },
    SA_COMMA,
    { a: 'كَوَيْ', t: 'ka-way', e: 'such as "way"' },
    { a: 'وَأُفٍّ', t: 'wa-uffin', e: 'and "uff"' },
    SA_COMMA,
    { a: 'بِمَعْنَى', t: 'bi-maʿnā', e: 'meaning' },
    { a: 'أَتَعَجَّبُ', t: 'ataʿajjabu', e: '"I wonder"' },
    { a: 'وَأَتَضَجَّرُ', t: 'wa-ataḍajjaru', e: 'and "I am vexed"' },
    { g: '.' },
  ] },

  { t: 'line', w: [
    { a: 'وَاسْمُ', t: 'wa-smu', e: 'and a noun of', c: 'red' },
    { a: 'فِعْلٍ', t: 'fiʿlin', e: 'a command', c: 'red' },
    { a: 'أَمْرٍ', t: 'amrin', e: 'verb (ism fiʿl amr)', c: 'red' },
    SA_COMMA,
    { a: 'كَصَهْ', t: 'ka-ṣah', e: 'such as "ṣah"' },
    { a: 'بِمَعْنَى', t: 'bi-maʿnā', e: 'meaning' },
    { a: 'اسْكُتْ', t: 'uskut', e: '"be silent!"' },
    { a: 'وَآمِينَ', t: 'wa-āmīn', e: 'and "āmīn"' },
    { a: 'بِمَعْنَى', t: 'bi-maʿnā', e: 'meaning' },
    { a: 'اسْتَجِبْ', t: 'istajib', e: '"respond!"' },
    SA_COMMA,
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
    { a: 'أَكْثَرُهَا', t: 'aktharuhā', e: 'the most of them' },
    { a: 'وُجُودًا', t: 'wujūdan', e: 'in occurrence' },
    { g: '.' },
  ] },
];
