/* ── Shadhā al-ʿArf — التقسيم الثاني للفعل (Worksheet 4) ──
   الفعل إلى صحيح ومعتل · أقسام الصحيح (سالم/مضعّف/مهموز) · أقسام المعتل
   (مثال/أجوف/ناقص/لفيف) · تطبيق على الاسم. Commentary "قوله…" = labelled boxes.
   Reuses the SA_* constants from wk01-muqaddimah.js (load after it).             */

const DATA_WK04 = [
  { t: 'page', n: '١' },

  { t: 'h2', c: 'blue', ar: 'التَّقْسِيمُ الثَّانِي لِلْفِعْلِ', en: 'Second Division of the Verb' },

  { t: 'line', w: [
    { a: 'يَنْقَسِمُ', t: 'yanqasimu', e: 'is divided' },
    { a: 'الْفِعْلُ', t: 'al-fiʿlu', e: 'the verb' },
    { a: 'إِلَى', t: 'ilā', e: 'into' },
    { a: 'صَحِيحٍ', t: 'ṣaḥīḥin', e: 'sound (ṣaḥīḥ)', c: 'red' },
    SA_COMMA,
    { a: 'وَمُعْتَلٍّ', t: 'wa-muʿtallin', e: 'and defective (muʿtall)', c: 'red' },
    { g: ':' },
  ] },

  { t: 'line', w: [
    { a: 'وَالْعِلَّةُ', t: 'wa-l-ʿillatu', e: '"ʿillah" (weakness)', c: 'red' },
    { a: 'لُغَةً', t: 'lughatan', e: 'linguistically' },
    { a: 'هِيَ', t: 'hiya', e: 'is' },
    { a: 'الْمَرَضُ', t: 'al-maraḍu', e: 'illness' },
    { a: 'وَالضَّعْفُ', t: 'wa-ḍ-ḍaʿfu', e: 'and weakness' },
    SA_COMMA,
    { a: 'سُمِّيَتْ', t: 'summiyat', e: 'are named' },
    { a: 'حُرُوفُ', t: 'ḥurūfu', e: 'the letters' },
    { g: '(و ا ي)' },
    { a: 'حُرُوفَ', t: 'ḥurūfa', e: 'letters of', c: 'red' },
    { a: 'عِلَّةٍ', t: 'ʿillatin', e: 'weakness', c: 'red' },
    { a: 'لِأَنَّهَا', t: 'li-annahā', e: 'because they' },
    { a: 'حُرُوفٌ', t: 'ḥurūfun', e: 'are letters' },
    { a: 'ضَعِيفَةٌ', t: 'ḍaʿīfatun', e: 'weak' },
    { a: 'يُصِيبُهَا', t: 'yuṣībuhā', e: 'affected by' },
    { a: 'الْإِعْلَالُ', t: 'al-iʿlālu', e: 'iʿlāl (modification)' },
    { a: 'بِكَثْرَةٍ', t: 'bi-kathratin', e: 'frequently' },
    { a: 'بِالْقَلْبِ', t: 'bi-l-qalbi', e: 'by substitution' },
    { a: 'وَالْحَذْفِ', t: 'wa-l-ḥadhfi', e: 'and elision' },
    { a: 'وَنَقْلِ', t: 'wa-naqli', e: 'and the transfer of' },
    { a: 'الْحَرَكَةِ', t: 'al-ḥarakati', e: 'the vowel' },
    { a: 'عَنْهَا', t: 'ʿanhā', e: 'from them' },
  ] },

  { t: 'line', w: [
    { a: 'فَالصَّحِيحُ', t: 'fa-ṣ-ṣaḥīḥu', e: 'the sound (verb)', c: 'red' },
    { g: ':' },
    { a: 'مَا', t: 'mā', e: 'is that whose' },
    { a: 'خَلَتْ', t: 'khalat', e: 'are free' },
    { a: 'أُصُولُهُ', t: 'uṣūluhu', e: 'roots' },
    { a: 'مِنْ', t: 'min', e: 'of' },
    { a: 'أَحْرُفِ', t: 'aḥrufi', e: 'the letters of', c: 'red' },
    { a: 'الْعِلَّةِ', t: 'al-ʿillati', e: 'weakness', c: 'red' },
    SA_COMMA,
    { a: 'وَهِيَ', t: 'wa-hiya', e: 'which are' },
    { a: 'الْأَلِفُ', t: 'al-alifu', e: 'the alif' },
    SA_COMMA,
    { a: 'وَالْوَاوُ', t: 'wa-l-wāwu', e: 'the wāw' },
    SA_COMMA,
    { a: 'وَالْيَاءُ', t: 'wa-l-yāʾu', e: 'and the yāʾ' },
    SA_COMMA,
    SA_NAHW,
    { a: 'كَتَبَ', t: 'kataba', e: 'kataba (he wrote)' },
    { a: 'وَجَلَسَ', t: 'wa-jalasa', e: 'and jalasa (he sat)' },
    { g: '.' },
  ] },

  { t: 'line', w: [
    { a: 'ثُمَّ', t: 'thumma', e: 'then' },
    { a: 'إِنَّ', t: 'inna', e: 'indeed' },
    { a: 'حَرْفَ', t: 'ḥarfa', e: 'a letter of' },
    { a: 'الْعِلَّةِ', t: 'al-ʿillati', e: 'weakness' },
    { a: 'إِنْ', t: 'in', e: 'if' },
    { a: 'سُكِّنَ', t: 'sukkina', e: 'is made quiescent' },
    { a: 'وَانْفَتَحَ', t: 'wa-nfataḥa', e: 'and what is before it is open' },
    { a: 'مَا', t: 'mā', e: 'is' },
    { a: 'قَبْلَهُ', t: 'qablahu', e: 'before it' },
    { a: 'يُسَمَّى', t: 'yusammā', e: 'is called' },
    { a: 'لِينًا', t: 'līnan', e: 'a soft letter (līn)', c: 'red' },
    SA_COMMA,
    { a: 'كَثَوْبٍ', t: 'ka-thawbin', e: 'such as thawb' },
    { a: 'وَسَيْفٍ', t: 'wa-sayfin', e: 'and sayf' },
    SA_COMMA,
    { a: 'فَإِنْ', t: 'fa-in', e: 'but if' },
    { a: 'جَانَسَهُ', t: 'jānasahu', e: 'homogeneous with it is' },
    { a: 'مَا', t: 'mā', e: 'what is' },
    { a: 'قَبْلَهُ', t: 'qablahu', e: 'before it' },
    { a: 'مِنَ', t: 'mina', e: 'of' },
    { a: 'الْحَرَكَاتِ', t: 'al-ḥarakāti', e: 'the vowels' },
    { a: 'يُسَمَّى', t: 'yusammā', e: 'it is called' },
    { a: 'مَدًّا', t: 'maddan', e: 'a prolongation (madd)', c: 'red' },
    { a: 'كَقَالَ', t: 'ka-qāla', e: 'such as qāla' },
    { a: 'يَقُولُ', t: 'yaqūlu', e: 'yaqūlu' },
    { a: 'قِيلَا', t: 'qīlā', e: 'qīlā' },
    { g: '؛' },
    { a: 'فَعَلَى', t: 'fa-ʿalā', e: 'so upon' },
    { a: 'ذَلِكَ', t: 'dhālika', e: 'that' },
    { a: 'لَا', t: 'lā', e: 'not' },
    { a: 'تَنْفَكُّ', t: 'tanfakku', e: 'ceases' },
    { a: 'الْأَلِفُ', t: 'al-alifu', e: 'the alif' },
    { a: 'عَنْ', t: 'ʿan', e: 'from' },
    { a: 'كَوْنِهَا', t: 'kawnihā', e: 'being' },
    { a: 'حَرْفَ', t: 'ḥarfa', e: 'a letter of' },
    { a: 'عِلَّةٍ', t: 'ʿillatin', e: 'weakness' },
    SA_COMMA,
    { a: 'وَمَدٍّ', t: 'wa-maddin', e: 'of madd' },
    SA_COMMA,
    { a: 'وَلِينٍ', t: 'wa-līnin', e: 'and līn' },
    SA_COMMA,
    { a: 'لِسُكُونِهَا', t: 'li-sukūnihā', e: 'for it is always quiescent' },
    { a: 'وَفَتْحِ', t: 'wa-fatḥi', e: 'and the fatḥah of' },
    { a: 'مَا', t: 'mā', e: 'what is' },
    { a: 'قَبْلَهَا', t: 'qablahā', e: 'before it' },
    { a: 'دَائِمًا', t: 'dāʾiman', e: 'always' },
    SA_COMMA,
    { a: 'بِخِلَافِ', t: 'bi-khilāfi', e: 'unlike' },
    { a: 'أُخْتَيْهَا', t: 'ukhtayhā', e: 'its two sisters (wāw & yāʾ)' },
    { g: '.' },
  ] },

  { t: 'box', label: 'شرح', labelEn: 'Commentary', lines: [
    [
      { a: 'قَوْلُهُ', t: 'qawluhu', e: 'his words' },
      { a: 'فِي', t: 'fī', e: 'on' },
      { a: 'الْفِعْلِ', t: 'al-fiʿli', e: 'the sound' },
      { a: 'الصَّحِيحِ', t: 'aṣ-ṣaḥīḥi', e: 'verb' },
      { a: '"مَا', t: 'mā', e: '"that whose' },
      { a: 'خَلَتْ', t: 'khalat', e: 'are free' },
      { a: 'أُصُولُهُ"', t: 'uṣūluhu', e: 'roots"' },
      { a: 'يَدُلُّ', t: 'yadullu', e: 'shows' },
      { a: 'عَلَى', t: 'ʿalā', e: 'that' },
      { a: 'أَنَّ', t: 'anna', e: '—' },
      { a: 'الْحُكْمَ', t: 'al-ḥukma', e: 'the ruling' },
      { a: 'مُتَعَلِّقٌ', t: 'mutaʿalliqun', e: 'attaches' },
      { a: 'بِالْحُرُوفِ', t: 'bi-l-ḥurūfi', e: 'to the letters' },
      { a: 'الْأَصْلِيَّةِ', t: 'al-aṣliyyati', e: 'that are radical' },
      { a: 'دُونَ', t: 'dūna', e: 'not' },
      { a: 'الزَّائِدَةِ', t: 'az-zāʾidati', e: 'the added ones' },
      { g: '.' },
    ],
    [
      { a: 'فَنَحْوُ', t: 'fa-naḥwu', e: 'so the likes of' },
      { a: 'كَتَبَ', t: 'kataba', e: 'kataba' },
      { a: 'وَضَرَبَ', t: 'wa-ḍaraba', e: 'ḍaraba' },
      { a: 'وَعَمِلَ', t: 'wa-ʿamila', e: 'and ʿamila' },
      { a: 'أَفْعَالٌ', t: 'afʿālun', e: 'are sound' },
      { a: 'صَحِيحَةٌ', t: 'ṣaḥīḥatun', e: 'verbs' },
      SA_COMMA,
      { a: 'وَكَذَا', t: 'wa-kadhā', e: 'and so too' },
      { a: 'مَا', t: 'mā', e: 'what' },
      { a: 'اشْتُقَّ', t: 'ushtuqqa', e: 'is derived' },
      { a: 'مِنْهَا', t: 'minhā', e: 'from them' },
      { a: 'كَكَاتِبٍ', t: 'ka-kātibin', e: 'such as kātib' },
      { a: 'وَضَارِبٍ', t: 'wa-ḍāribin', e: 'ḍārib' },
      { a: 'وَعَامِلٍ', t: 'wa-ʿāmilin', e: 'and ʿāmil' },
      { g: '.' },
    ],
  ] },

  { t: 'line', w: [
    { a: 'وَالْمُعْتَلُّ', t: 'wa-l-muʿtallu', e: 'the defective (verb)', c: 'red' },
    { g: ':' },
    { a: 'مَا', t: 'mā', e: 'is that' },
    { a: 'كَانَ', t: 'kāna', e: 'which has' },
    { a: 'أَحَدُ', t: 'aḥadu', e: 'one of' },
    { a: 'أُصُولِهِ', t: 'uṣūlihi', e: 'its roots' },
    { a: 'حَرْفَ', t: 'ḥarfa', e: 'a letter of', c: 'red' },
    { a: 'عِلَّةٍ', t: 'ʿillatin', e: 'weakness', c: 'red' },
    SA_COMMA,
    SA_NAHW,
    { a: 'وَجَدَ', t: 'wajada', e: 'wajada (he found)' },
    SA_COMMA,
    { a: 'وَقَالَ', t: 'wa-qāla', e: 'qāla (he said)' },
    SA_COMMA,
    { a: 'وَسَعَى', t: 'wa-saʿā', e: 'and saʿā (he strove)' },
    { g: '.' },
  ] },

  { t: 'line', w: [
    { a: 'وَلِكُلٍّ', t: 'wa-li-kullin', e: 'and each' },
    { a: 'مِنَ', t: 'mina', e: 'of' },
    { a: 'الصَّحِيحِ', t: 'aṣ-ṣaḥīḥi', e: 'the sound' },
    { a: 'وَالْمُعْتَلِّ', t: 'wa-l-muʿtalli', e: 'and the defective' },
    { a: 'أَقْسَامٌ', t: 'aqsāmun', e: 'has divisions' },
    { g: ':' },
  ] },

  /* ── أقسام الصحيح ── */
  { t: 'h2', c: 'blue', ar: 'أَقْسَامُ الصَّحِيحِ', en: 'Divisions of the Sound Verb' },

  { t: 'line', w: [
    { a: 'يَنْقَسِمُ', t: 'yanqasimu', e: 'is divided' },
    { a: 'الصَّحِيحُ', t: 'aṣ-ṣaḥīḥu', e: 'the sound' },
    { a: 'إِلَى', t: 'ilā', e: 'into' },
    { a: 'سَالِمٍ', t: 'sālimin', e: 'sound-proper (sālim)', c: 'red' },
    SA_COMMA,
    { a: 'وَمُضَعَّفٍ', t: 'wa-muḍaʿʿafin', e: 'doubled (muḍaʿʿaf)', c: 'red' },
    SA_COMMA,
    { a: 'وَمَهْمُوزٍ', t: 'wa-mahmūzin', e: 'and hamzated (mahmūz)', c: 'red' },
    { g: '.' },
  ] },

  { t: 'line', w: [
    { a: 'فَالسَّالِمُ', t: 'fa-s-sālimu', e: 'the sound-proper', c: 'red' },
    { g: ':' },
    { a: 'مَا', t: 'mā', e: 'is that whose' },
    { a: 'سَلِمَتْ', t: 'salimat', e: 'are safe' },
    { a: 'أُصُولُهُ', t: 'uṣūluhu', e: 'roots' },
    { a: 'مِنْ', t: 'min', e: 'from' },
    { a: 'أَحْرُفِ', t: 'aḥrufi', e: 'the letters of' },
    { a: 'الْعِلَّةِ', t: 'al-ʿillati', e: 'weakness' },
    { a: 'وَالْهَمْزَةِ', t: 'wa-l-hamzati', e: 'the hamzah' },
    { a: 'وَالتَّضْعِيفِ', t: 'wa-t-taḍʿīfi', e: 'and doubling' },
    SA_COMMA,
    { a: 'كَضَرَبَ', t: 'ka-ḍaraba', e: 'such as ḍaraba' },
    { a: 'وَنَصَرَ', t: 'wa-naṣara', e: 'naṣara' },
    { a: 'وَقَعَدَ', t: 'wa-qaʿada', e: 'qaʿada' },
    { a: 'وَجَلَسَ', t: 'wa-jalasa', e: 'and jalasa' },
    SA_COMMA,
    { a: 'فَإِذَنْ', t: 'fa-idhan', e: 'so then' },
    { a: 'يَكُونُ', t: 'yakūnu', e: 'is' },
    { a: 'كُلُّ', t: 'kullu', e: 'every' },
    { a: 'سَالِمٍ', t: 'sālimin', e: 'sālim' },
    { a: 'صَحِيحًا', t: 'ṣaḥīḥan', e: 'ṣaḥīḥ' },
    SA_COMMA,
    { a: 'وَلَا', t: 'wa-lā', e: 'but not' },
    { a: 'عَكْسَ', t: 'ʿaksa', e: 'the reverse' },
    { g: '.' },
  ] },

  { t: 'line', w: [
    { a: 'وَالْمُضَعَّفُ', t: 'wa-l-muḍaʿʿafu', e: 'the doubled', c: 'red' },
    { g: ':' },
    { a: 'وَيُقَالُ', t: 'wa-yuqālu', e: 'it is also called' },
    { a: 'لَهُ', t: 'lahu', e: '—' },
    { a: 'الْأَصَمُّ', t: 'al-aṣammu', e: 'the deaf (al-aṣamm)' },
    { a: 'لِشِدَّتِهِ', t: 'li-shiddatihi', e: 'for its strength' },
    SA_COMMA,
    { a: 'يَنْقَسِمُ', t: 'yanqasimu', e: 'it divides' },
    { a: 'إِلَى', t: 'ilā', e: 'into' },
    { a: 'قِسْمَيْنِ', t: 'qismayni', e: 'two kinds' },
    { g: ':' },
    { a: 'مُضَعَّفِ', t: 'muḍaʿʿafi', e: 'doubled of', c: 'red' },
    { a: 'الثُّلَاثِيِّ', t: 'ath-thulāthiyyi', e: 'the trilateral', c: 'red' },
    { a: 'وَمَزِيدِهِ', t: 'wa-mazīdihi', e: 'and its augmented', c: 'red' },
    SA_COMMA,
    { a: 'وَمُضَعَّفِ', t: 'wa-muḍaʿʿafi', e: 'and doubled of', c: 'red' },
    { a: 'الرُّبَاعِيِّ', t: 'ar-rubāʿiyyi', e: 'the quadriliteral', c: 'red' },
    { g: '.' },
  ] },

  { t: 'line', w: [
    { a: 'فَمُضَعَّفُ', t: 'fa-muḍaʿʿafu', e: 'the doubled of', c: 'red' },
    { a: 'الثُّلَاثِيِّ', t: 'ath-thulāthiyyi', e: 'the trilateral', c: 'red' },
    { a: 'وَمَزِيدِهِ', t: 'wa-mazīdihi', e: 'and its augmented', c: 'red' },
    { g: ':' },
    { a: 'مَا', t: 'mā', e: 'is that' },
    { a: 'كَانَتْ', t: 'kānat', e: 'whose' },
    { a: 'عَيْنُهُ', t: 'ʿaynuhu', e: 'ʿayn' },
    { a: 'وَلَامُهُ', t: 'wa-lāmuhu', e: 'and lām' },
    { a: 'مِنْ', t: 'min', e: 'are of' },
    { a: 'جِنْسٍ', t: 'jinsin', e: 'one' },
    { a: 'وَاحِدٍ', t: 'wāḥidin', e: 'kind' },
    SA_COMMA,
    SA_NAHW,
    { a: 'فَرَّ', t: 'farra', e: 'farra (he fled)' },
    SA_COMMA,
    { a: 'مَدَّ', t: 'madda', e: 'madda (he stretched)' },
    SA_COMMA,
    { a: 'وَامْتَدَّ', t: 'wa-mtadda', e: 'imtadda' },
    SA_COMMA,
    { a: 'وَاسْتَمَدَّ', t: 'wa-stamadda', e: 'and istamadda' },
    SA_COMMA,
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
    { a: 'مَحَلُّ', t: 'maḥallu', e: 'the locus of', c: 'red' },
    { a: 'نَظَرِ', t: 'naẓari', e: 'the concern of', c: 'red' },
    { a: 'الصَّرْفِيِّ', t: 'aṣ-ṣarfiyyi', e: 'the morphologist', c: 'red' },
    { g: '.' },
  ] },

  { t: 'box', label: 'شرح', labelEn: 'Commentary', lines: [
    [
      { a: 'وَهُوَ', t: 'wa-huwa', e: 'it (the trilateral doubled)' },
      { a: 'الَّذِي', t: 'alladhī', e: 'is the one' },
      { a: 'لَهُ', t: 'lahu', e: 'that has' },
      { a: 'أَحْكَامٌ', t: 'aḥkāmun', e: 'rulings' },
      { a: 'صَرْفِيَّةٌ', t: 'ṣarfiyyatun', e: 'morphological' },
      { a: 'كَالْإِدْغَامِ', t: 'ka-l-idghāmi', e: 'such as idghām (assimilation)' },
      { a: 'وَنَقْلِ', t: 'wa-naqli', e: 'transfer of' },
      { a: 'الْحَرَكَةِ', t: 'al-ḥarakati', e: 'the vowel' },
      { a: 'وَإِسْنَادِ', t: 'wa-isnādi', e: 'and attaching' },
      { a: 'الضَّمَائِرِ', t: 'aḍ-ḍamāʾiri', e: 'the pronouns' },
      { a: 'إِلَيْهِ', t: 'ilayhi', e: 'to it' },
      SA_COMMA,
      { a: 'بِخِلَافِ', t: 'bi-khilāfi', e: 'unlike' },
      { a: 'الرُّبَاعِيِّ', t: 'ar-rubāʿiyyi', e: 'the quadriliteral' },
      { g: '.' },
    ],
  ] },

  { t: 'line', w: [
    { a: 'وَمُضَعَّفُ', t: 'wa-muḍaʿʿafu', e: 'and the doubled', c: 'red' },
    { a: 'الرُّبَاعِيِّ', t: 'ar-rubāʿiyyi', e: 'quadriliteral', c: 'red' },
    { g: ':' },
    { a: 'مَا', t: 'mā', e: 'is that' },
    { a: 'كَانَتْ', t: 'kānat', e: 'whose' },
    { a: 'فَاؤُهُ', t: 'fāʾuhu', e: 'fāʾ' },
    { a: 'وَلَامُهُ', t: 'wa-lāmuhu', e: 'and first' },
    { a: 'الْأُولَى', t: 'al-ūlā', e: 'lām' },
    { a: 'مِنْ', t: 'min', e: 'are of' },
    { a: 'جِنْسٍ', t: 'jinsin', e: 'one kind' },
    SA_COMMA,
    { a: 'وَعَيْنُهُ', t: 'wa-ʿaynuhu', e: 'and its ʿayn' },
    { a: 'وَلَامُهُ', t: 'wa-lāmuhu', e: 'and second' },
    { a: 'الثَّانِيَةُ', t: 'ath-thāniyatu', e: 'lām' },
    { a: 'مِنْ', t: 'min', e: 'of' },
    { a: 'جِنْسٍ', t: 'jinsin', e: 'one kind' },
    SA_COMMA,
    { a: 'كَزَلْزَلَ', t: 'ka-zalzala', e: 'such as zalzala' },
    SA_COMMA,
    { a: 'وَعَسْعَسَ', t: 'wa-ʿasʿasa', e: 'ʿasʿasa' },
    SA_COMMA,
    { a: 'وَقَلْقَلَ', t: 'wa-qalqala', e: 'and qalqala' },
    { g: '.' },
  ] },

  { t: 'page', n: '٢' },

  { t: 'line', w: [
    { a: 'وَالْمَهْمُوزُ', t: 'wa-l-mahmūzu', e: 'the hamzated', c: 'red' },
    { g: ':' },
    { a: 'مَا', t: 'mā', e: 'is that' },
    { a: 'كَانَ', t: 'kāna', e: 'which has' },
    { a: 'أَحَدُ', t: 'aḥadu', e: 'one of' },
    { a: 'أُصُولِهِ', t: 'uṣūlihi', e: 'its roots' },
    { a: 'هَمْزَةً', t: 'hamzatan', e: 'a hamzah' },
    SA_COMMA,
    SA_NAHW,
    { a: 'أَخَذَ', t: 'akhadha', e: 'akhadha (he took)' },
    SA_COMMA,
    { a: 'وَسَأَلَ', t: 'wa-saʾala', e: 'saʾala (he asked)' },
    SA_COMMA,
    { a: 'وَقَرَأَ', t: 'wa-qaraʾa', e: 'and qaraʾa (he read)' },
    { g: '.' },
  ] },

  /* ── أقسام المعتل ── */
  { t: 'h2', c: 'blue', ar: 'أَقْسَامُ الْمُعْتَلِّ', en: 'Divisions of the Defective Verb' },

  { t: 'line', w: [
    { a: 'يَنْقَسِمُ', t: 'yanqasimu', e: 'is divided' },
    { a: 'الْمُعْتَلُّ', t: 'al-muʿtallu', e: 'the defective' },
    { a: 'إِلَى', t: 'ilā', e: 'into' },
    { a: 'مِثَالٍ', t: 'mithālin', e: 'assimilated (mithāl)', c: 'red' },
    SA_COMMA,
    { a: 'وَأَجْوَفَ', t: 'wa-ajwafa', e: 'hollow (ajwaf)', c: 'red' },
    SA_COMMA,
    { a: 'وَنَاقِصٍ', t: 'wa-nāqiṣin', e: 'defective-lām (nāqiṣ)', c: 'red' },
    SA_COMMA,
    { a: 'وَلَفِيفٍ', t: 'wa-lafīfin', e: 'and doubly-weak (lafīf)', c: 'red' },
    { g: '.' },
  ] },

  { t: 'line', w: [
    { a: 'فَالْمِثَالُ', t: 'fa-l-mithālu', e: 'the assimilated', c: 'red' },
    { g: ':' },
    { a: 'مَا', t: 'mā', e: 'is that whose' },
    { a: 'اعْتُلَّتْ', t: 'uʿtullat', e: 'is weak' },
    { a: 'فَاؤُهُ', t: 'fāʾuhu', e: 'fāʾ' },
    SA_COMMA,
    SA_NAHW,
    { a: 'وَعَدَ', t: 'waʿada', e: 'waʿada (he promised)' },
    { a: 'وَيَسَرَ', t: 'wa-yasara', e: 'and yasara' },
    SA_COMMA,
    { a: 'وَسُمِّيَ', t: 'wa-summiya', e: 'and it is so named' },
    { a: 'بِذَلِكَ', t: 'bi-dhālika', e: 'thus' },
    { a: 'لِأَنَّهُ', t: 'li-annahu', e: 'because it' },
    { a: 'يُمَاثِلُ', t: 'yumāthilu', e: 'resembles' },
    { a: 'الصَّحِيحَ', t: 'aṣ-ṣaḥīḥa', e: 'the sound (verb)' },
    { a: 'فِي', t: 'fī', e: 'in' },
    { a: 'عَدَمِ', t: 'ʿadami', e: 'the absence of' },
    { a: 'إِعْلَالِ', t: 'iʿlāli', e: 'modification of' },
    { a: 'مَاضِيهِ', t: 'māḍīhi', e: 'its past' },
    { g: '.' },
  ] },

  { t: 'box', label: 'شرح', labelEn: 'Commentary', lines: [
    [
      { a: 'أَيْ', t: 'ay', e: 'that is' },
      { a: 'أَنَّ', t: 'anna', e: '—' },
      { a: 'وَعَدَ', t: 'waʿada', e: 'waʿada' },
      { a: 'لَا', t: 'lā', e: 'is not' },
      { a: 'يُعَلُّ', t: 'yuʿallu', e: 'altered' },
      { a: 'بِحَذْفٍ', t: 'bi-ḥadhfin', e: 'by elision' },
      { a: 'أَوْ', t: 'aw', e: 'or' },
      { a: 'قَلْبٍ', t: 'qalbin', e: 'substitution' },
      { a: 'بِخِلَافِ', t: 'bi-khilāfi', e: 'unlike' },
      { g: ':' },
    ],
    [
      { a: 'الْأَجْوَفِ', t: 'al-ajwafi', e: 'the hollow', c: 'red' },
      { a: 'فَيُعَلُّ', t: 'fa-yuʿallu', e: 'which is altered' },
      { a: 'كَقَالَ', t: 'ka-qāla', e: 'as qāla' },
      { a: 'بِالْقَلْبِ', t: 'bi-l-qalbi', e: 'by substitution' },
      { a: 'وَقُلْتُ', t: 'wa-qultu', e: 'and qultu' },
      { a: 'بِالْحَذْفِ', t: 'bi-l-ḥadhfi', e: 'by elision' },
      { g: '.' },
    ],
    [
      { a: 'وَالنَّاقِصِ', t: 'wa-n-nāqiṣi', e: 'and the defective-lām', c: 'red' },
      { a: 'فَيُعَلُّ', t: 'fa-yuʿallu', e: 'which is altered' },
      { a: 'كَرَمَى', t: 'ka-ramā', e: 'as ramā' },
      { a: 'بِالْقَلْبِ', t: 'bi-l-qalbi', e: 'by substitution' },
      { a: 'وَرَمَوْا', t: 'wa-ramaw', e: 'and ramaw' },
      { a: 'بِالْحَذْفِ', t: 'bi-l-ḥadhfi', e: 'by elision' },
      { g: '.' },
    ],
    [
      { a: 'أَمَّا', t: 'ammā', e: 'but' },
      { a: 'الْمِثَالُ', t: 'al-mithālu', e: 'the assimilated', c: 'red' },
      { a: 'فَلَا', t: 'fa-lā', e: 'is not' },
      { a: 'يُعَلُّ', t: 'yuʿallu', e: 'altered' },
      SA_COMMA,
      { a: 'وَعَدَ', t: 'waʿada', e: 'waʿada' },
      { a: 'وَوَعَدْتُ', t: 'wa-waʿadtu', e: 'waʿadtu' },
      { a: 'وَوَعَدُوا', t: 'wa-waʿadū', e: 'and waʿadū' },
      { g: '.' },
    ],
  ] },

  { t: 'line', w: [
    { a: 'وَالْأَجْوَفُ', t: 'wa-l-ajwafu', e: 'the hollow', c: 'red' },
    { g: ':' },
    { a: 'مَا', t: 'mā', e: 'is that whose' },
    { a: 'اعْتَلَّتْ', t: 'uʿtullat', e: 'is weak' },
    { a: 'عَيْنُهُ', t: 'ʿaynuhu', e: 'ʿayn' },
    SA_COMMA,
    SA_NAHW,
    { a: 'قَالَ', t: 'qāla', e: 'qāla' },
    { a: 'وَبَاعَ', t: 'wa-bāʿa', e: 'and bāʿa' },
    SA_COMMA,
    { a: 'وَسُمِّيَ', t: 'wa-summiya', e: 'and it is so named' },
    { a: 'بِذَلِكَ', t: 'bi-dhālika', e: 'thus' },
    { a: 'لِخُلُوِّ', t: 'li-khuluwwi', e: 'for the emptiness of' },
    { a: 'جَوْفِهِ', t: 'jawfihi', e: 'its hollow (jawf)' },
    SA_COMMA,
    { a: 'أَيْ', t: 'ay', e: 'i.e.' },
    { a: 'وَسَطِهِ', t: 'wasaṭihi', e: 'its middle' },
    SA_COMMA,
    { a: 'مِنَ', t: 'mina', e: 'of' },
    { a: 'الْحَرْفِ', t: 'al-ḥarfi', e: 'a sound' },
    { a: 'الصَّحِيحِ', t: 'aṣ-ṣaḥīḥi', e: 'letter' },
    { g: '.' },
    { a: 'وَيُسَمَّى', t: 'wa-yusammā', e: 'and it is also called' },
    { a: 'أَيْضًا', t: 'ayḍan', e: 'also' },
    { a: 'ذَا', t: 'dhā', e: 'possessor of', c: 'red' },
    { a: 'الثَّلَاثَةِ', t: 'ath-thalāthati', e: 'three (dhāt ath-thalāthah)', c: 'red' },
    SA_COMMA,
    { a: 'لِأَنَّهُ', t: 'li-annahu', e: 'because' },
    { a: 'عِنْدَ', t: 'ʿinda', e: 'upon' },
    { a: 'إِسْنَادِهِ', t: 'isnādihi', e: 'its attachment' },
    { a: 'لِتَاءِ', t: 'li-tāʾi', e: 'to the tāʾ of' },
    { a: 'الْفَاعِلِ', t: 'al-fāʿili', e: 'the doer' },
    SA_COMMA,
    { a: 'يَصِيرُ', t: 'yaṣīru', e: 'it becomes' },
    { a: 'مَعَهَا', t: 'maʿahā', e: 'with it' },
    { a: 'عَلَى', t: 'ʿalā', e: 'of' },
    { a: 'ثَلَاثَةِ', t: 'thalāthati', e: 'three' },
    { a: 'أَحْرُفٍ', t: 'aḥrufin', e: 'letters' },
    SA_COMMA,
    { a: 'كَقُلْتُ', t: 'ka-qultu', e: 'as qultu' },
    { a: 'وَبِعْتُ', t: 'wa-biʿtu', e: 'and biʿtu' },
    SA_COMMA,
    { a: 'فِي', t: 'fī', e: 'from' },
    { a: 'قَالَ', t: 'qāla', e: 'qāla' },
    { a: 'وَبَاعَ', t: 'wa-bāʿa', e: 'and bāʿa' },
    { g: '.' },
  ] },

  { t: 'box', label: 'شرح', labelEn: 'Commentary', lines: [
    [
      { a: 'هَذَا', t: 'hādhā', e: 'this' },
      { a: 'الْحُكْمُ', t: 'al-ḥukmu', e: 'ruling' },
      { a: 'يَشْمَلُ', t: 'yashmalu', e: 'covers' },
      { a: 'ضَمَائِرَ', t: 'ḍamāʾira', e: 'the pronouns of' },
      { a: 'الرَّفْعِ', t: 'ar-rafʿi', e: 'the nominative' },
      { a: 'الْمُتَحَرِّكَةَ', t: 'al-mutaḥarrikata', e: 'that are vowelled' },
      { a: 'الْمُتَّصِلَةَ', t: 'al-muttaṣilata', e: 'and attached' },
      SA_COMMA,
      { a: 'وَهِيَ', t: 'wa-hiya', e: 'which are' },
      { a: 'ثَلَاثَةٌ', t: 'thalāthatun', e: 'three' },
      { g: ':' },
      { a: 'تَاءُ', t: 'tāʾu', e: 'the tāʾ of' },
      { a: 'الْفَاعِلِ', t: 'al-fāʿili', e: 'the doer' },
      { a: 'وَنَا', t: 'wa-nā', e: 'the "nā" of' },
      { a: 'الْمُتَكَلِّمِينَ', t: 'al-mutakallimīna', e: 'the speakers' },
      { a: 'وَنُونُ', t: 'wa-nūnu', e: 'and the nūn of' },
      { a: 'النِّسْوَةِ', t: 'an-niswati', e: 'the women' },
      SA_COMMA,
      SA_NAHW,
      { a: 'قُلْتُ', t: 'qultu', e: 'qultu' },
      { a: 'وَنَحْنُ', t: 'wa-naḥnu', e: 'and naḥnu' },
      { a: 'قُلْنَا', t: 'qulnā', e: 'qulnā' },
      { a: 'وَهُنَّ', t: 'wa-hunna', e: 'and hunna' },
      { a: 'قُلْنَ', t: 'qulna', e: 'qulna' },
      { a: 'شَيْئًا', t: 'shayʾan', e: 'something' },
      { g: '.' },
    ],
  ] },

  { t: 'line', w: [
    { a: 'وَالنَّاقِصُ', t: 'wa-n-nāqiṣu', e: 'the defective-lām', c: 'red' },
    { g: ':' },
    { a: 'مَا', t: 'mā', e: 'is that whose' },
    { a: 'اعْتَلَّتْ', t: 'uʿtullat', e: 'is weak' },
    { a: 'لَامُهُ', t: 'lāmuhu', e: 'lām' },
    SA_COMMA,
    SA_NAHW,
    { a: 'غَزَا', t: 'ghazā', e: 'ghazā (he raided)' },
    { a: 'وَرَمَى', t: 'wa-ramā', e: 'and ramā (he threw)' },
    SA_COMMA,
    { a: 'وَسُمِّيَ', t: 'wa-summiya', e: 'and it is so named' },
    { a: 'بِذَلِكَ', t: 'bi-dhālika', e: 'thus' },
    { a: 'لِنُقْصَانِهِ', t: 'li-nuqṣānihi', e: 'for its deficiency' },
    SA_COMMA,
    { a: 'بِحَذْفِ', t: 'bi-ḥadhfi', e: 'by the elision of' },
    { a: 'آخِرِهِ', t: 'ākhirihi', e: 'its end' },
    { a: 'فِي', t: 'fī', e: 'in' },
    { a: 'بَعْضِ', t: 'baʿḍi', e: 'some' },
    { a: 'التَّصَارِيفِ', t: 'at-taṣārīfi', e: 'conjugations' },
    SA_COMMA,
    { a: 'كَغَزَتْ', t: 'ka-ghazat', e: 'as ghazat' },
    { a: 'وَرَمَتْ', t: 'wa-ramat', e: 'and ramat' },
    SA_COMMA,
    { a: 'وَيُسَمَّى', t: 'wa-yusammā', e: 'and it is also called' },
    { a: 'أَيْضًا', t: 'ayḍan', e: 'also' },
    { a: 'ذَا', t: 'dhā', e: 'possessor of', c: 'red' },
    { a: 'الْأَرْبَعَةِ', t: 'al-arbaʿati', e: 'four (dhāt al-arbaʿah)', c: 'red' },
    SA_COMMA,
    { a: 'لِأَنَّهُ', t: 'li-annahu', e: 'because' },
    { a: 'عِنْدَ', t: 'ʿinda', e: 'upon' },
    { a: 'إِسْنَادِهِ', t: 'isnādihi', e: 'its attachment' },
    { a: 'لِتَاءِ', t: 'li-tāʾi', e: 'to the tāʾ of' },
    { a: 'الْفَاعِلِ', t: 'al-fāʿili', e: 'the doer' },
    { a: 'يَصِيرُ', t: 'yaṣīru', e: 'it becomes' },
    { a: 'مَعَهَا', t: 'maʿahā', e: 'with it' },
    { a: 'عَلَى', t: 'ʿalā', e: 'of' },
    { a: 'أَرْبَعَةِ', t: 'arbaʿati', e: 'four' },
    { a: 'أَحْرُفٍ', t: 'aḥrufin', e: 'letters' },
    SA_COMMA,
    SA_NAHW,
    { a: 'غَزَوْتُ', t: 'ghazawtu', e: 'ghazawtu' },
    { a: 'وَرَمَيْتُ', t: 'wa-ramaytu', e: 'and ramaytu' },
    { g: '.' },
  ] },

  { t: 'line', w: [
    { a: 'وَاللَّفِيفُ', t: 'wa-l-lafīfu', e: 'the doubly-weak (lafīf)', c: 'red' },
    { a: 'قِسْمَانِ', t: 'qismāni', e: 'is two kinds' },
    { g: ':' },
  ] },

  { t: 'line', w: [
    { a: 'مَفْرُوقٌ', t: 'mafrūqun', e: 'separated (mafrūq)', c: 'red' },
    SA_COMMA,
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
    { a: 'مَا', t: 'mā', e: 'that whose' },
    { a: 'اعْتَلَّتْ', t: 'uʿtullat', e: 'are weak' },
    { a: 'فَاؤُهُ', t: 'fāʾuhu', e: 'fāʾ' },
    { a: 'وَلَامُهُ', t: 'wa-lāmuhu', e: 'and lām' },
    SA_COMMA,
    SA_NAHW,
    { a: 'وَفَى', t: 'wafā', e: 'wafā (he fulfilled)' },
    SA_COMMA,
    { a: 'وَسُمِّيَ', t: 'wa-summiya', e: 'and it is so named' },
    { a: 'بِذَلِكَ', t: 'bi-dhālika', e: 'thus' },
    { a: 'لِكَوْنِ', t: 'li-kawni', e: 'because' },
    { a: 'الْحَرْفِ', t: 'al-ḥarfi', e: 'the sound' },
    { a: 'الصَّحِيحِ', t: 'aṣ-ṣaḥīḥi', e: 'letter (the ʿayn)' },
    { a: 'فَارِقًا', t: 'fāriqan', e: 'separates' },
    { a: 'بَيْنَ', t: 'bayna', e: 'between' },
    { a: 'حَرْفَيِ', t: 'ḥarfayi', e: 'the two letters of' },
    { a: 'الْعِلَّةِ', t: 'al-ʿillati', e: 'weakness' },
    { g: '.' },
  ] },

  { t: 'page', n: '٣' },

  { t: 'line', w: [
    { a: 'وَمَقْرُونٌ', t: 'wa-maqrūnun', e: 'and joined (maqrūn)', c: 'red' },
    SA_COMMA,
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
    { a: 'مَا', t: 'mā', e: 'that whose' },
    { a: 'اعْتَلَّتْ', t: 'uʿtullat', e: 'are weak' },
    { a: 'عَيْنُهُ', t: 'ʿaynuhu', e: 'ʿayn' },
    { a: 'وَلَامُهُ', t: 'wa-lāmuhu', e: 'and lām' },
    SA_COMMA,
    SA_NAHW,
    { a: 'طَوَى', t: 'ṭawā', e: 'ṭawā (he folded)' },
    { a: 'وَرَوَى', t: 'wa-rawā', e: 'and rawā (he related)' },
    SA_COMMA,
    { a: 'وَسُمِّيَ', t: 'wa-summiya', e: 'and it is so named' },
    { a: 'بِذَلِكَ', t: 'bi-dhālika', e: 'thus' },
    { a: 'لِاقْتِرَانِ', t: 'li-qtirāni', e: 'for the joining of' },
    { a: 'حَرْفَيِ', t: 'ḥarfayi', e: 'the two letters of' },
    { a: 'الْعِلَّةِ', t: 'al-ʿillati', e: 'weakness' },
    { a: 'بَعْضِهِمَا', t: 'baʿḍihimā', e: 'one' },
    { a: 'بِبَعْضٍ', t: 'bi-baʿḍin', e: 'to the other' },
    { g: '.' },
  ] },

  { t: 'line', w: [
    { a: 'وَهَذِهِ', t: 'wa-hādhihi', e: 'and these' },
    { a: 'التَّقَاسِيمُ', t: 'at-taqāsīmu', e: 'divisions' },
    { a: 'الَّتِي', t: 'allatī', e: 'which' },
    { a: 'جَرَتْ', t: 'jarat', e: 'applied' },
    { a: 'فِي', t: 'fī', e: 'to' },
    { a: 'الْفِعْلِ', t: 'al-fiʿli', e: 'the verb' },
    SA_COMMA,
    { a: 'تَجْرِي', t: 'tajrī', e: 'apply' },
    { a: 'أَيْضًا', t: 'ayḍan', e: 'also' },
    { a: 'فِي', t: 'fī', e: 'to' },
    { a: 'الِاسْمِ', t: 'al-ismi', e: 'the noun' },
    SA_COMMA,
    SA_NAHW,
    { a: 'شَمْسٍ', t: 'shamsin', e: 'shams (sun)' },
    SA_COMMA,
    { a: 'وَوَجْهٍ', t: 'wa-wajhin', e: 'wajh (face)' },
    SA_COMMA,
    { a: 'وَيُمْنٍ', t: 'wa-yumnin', e: 'yumn (blessing)' },
    SA_COMMA,
    { a: 'وَقَوْلٍ', t: 'wa-qawlin', e: 'qawl (saying)' },
    SA_COMMA,
    { a: 'وَسَيْفٍ', t: 'wa-sayfin', e: 'sayf (sword)' },
    SA_COMMA,
    { a: 'وَدَلْوٍ', t: 'wa-dalwin', e: 'dalw (bucket)' },
    SA_COMMA,
    { a: 'وَظَبْيٍ', t: 'wa-ẓabyin', e: 'ẓaby (gazelle)' },
    SA_COMMA,
    { a: 'وَوَحْيٍ', t: 'wa-waḥyin', e: 'waḥy (revelation)' },
    SA_COMMA,
    { a: 'وَجَوٍّ', t: 'wa-jawwin', e: 'jaww (atmosphere)' },
    SA_COMMA,
    { a: 'وَحَيٍّ', t: 'wa-ḥayyin', e: 'ḥayy (living)' },
    SA_COMMA,
    { a: 'وَأَمْرٍ', t: 'wa-amrin', e: 'amr (command)' },
    SA_COMMA,
    { a: 'وَبِئْرٍ', t: 'wa-biʾrin', e: 'biʾr (well)' },
    SA_COMMA,
    { a: 'وَنَبَأٍ', t: 'wa-nabaʾin', e: 'nabaʾ (tiding)' },
    SA_COMMA,
    { a: 'وَحَدٍّ', t: 'wa-ḥaddin', e: 'ḥadd (limit)' },
    SA_COMMA,
    { a: 'وَبُلْبُلٍ', t: 'wa-bulbulin', e: 'and bulbul (nightingale)' },
    { g: '.' },
  ] },

  { t: 'box', label: 'تطبيق', labelEn: 'Application to the noun', lines: [
    [ { a: 'شَمْسٌ', t: 'shams', e: 'shams' }, { g: ':' },
      { a: 'سَالِمٌ', t: 'sālim', e: 'sound-proper (sālim)', c: 'red' } ],
    [ { a: 'وَجْهٌ', t: 'wajh', e: 'wajh' }, { a: 'وَيُمْنٌ', t: 'wa-yumn', e: 'and yumn' }, { g: ':' },
      { a: 'مِثَالٌ', t: 'mithāl', e: 'assimilated (mithāl)', c: 'red' } ],
    [ { a: 'قَوْلٌ', t: 'qawl', e: 'qawl' }, { a: 'وَسَيْفٌ', t: 'wa-sayf', e: 'and sayf' }, { g: ':' },
      { a: 'أَجْوَفُ', t: 'ajwaf', e: 'hollow (ajwaf)', c: 'red' } ],
    [ { a: 'دَلْوٌ', t: 'dalw', e: 'dalw' }, { a: 'وَظَبْيٌ', t: 'wa-ẓaby', e: 'and ẓaby' }, { g: ':' },
      { a: 'نَاقِصٌ', t: 'nāqiṣ', e: 'defective-lām (nāqiṣ)', c: 'red' } ],
    [ { a: 'وَحْيٌ', t: 'waḥy', e: 'waḥy' }, { g: ':' },
      { a: 'لَفِيفٌ', t: 'lafīf', e: 'separated', c: 'red' }, { a: 'مَفْرُوقٌ', t: 'mafrūq', e: 'lafīf', c: 'red' } ],
    [ { a: 'جَوٌّ', t: 'jaww', e: 'jaww' }, { a: 'وَحَيٌّ', t: 'wa-ḥayy', e: 'and ḥayy' }, { g: ':' },
      { a: 'لَفِيفٌ', t: 'lafīf', e: 'joined', c: 'red' }, { a: 'مَقْرُونٌ', t: 'maqrūn', e: 'lafīf', c: 'red' } ],
    [ { a: 'أَمْرٌ', t: 'amr', e: 'amr' }, { a: 'وَبِئْرٌ', t: 'wa-biʾr', e: 'biʾr' }, { a: 'وَنَبَأٌ', t: 'wa-nabaʾ', e: 'and nabaʾ' }, { g: ':' },
      { a: 'مَهْمُوزٌ', t: 'mahmūz', e: 'hamzated (mahmūz)', c: 'red' } ],
    [ { a: 'حَدٌّ', t: 'ḥadd', e: 'ḥadd' }, { g: ':' },
      { a: 'مُضَاعَفٌ', t: 'muḍāʿaf', e: 'trilateral', c: 'red' }, { a: 'ثُلَاثِيٌّ', t: 'thulāthī', e: 'doubled', c: 'red' } ],
    [ { a: 'بُلْبُلٌ', t: 'bulbul', e: 'bulbul' }, { g: ':' },
      { a: 'مُضَعَّفٌ', t: 'muḍaʿʿaf', e: 'quadriliteral', c: 'red' }, { a: 'رُبَاعِيٌّ', t: 'rubāʿī', e: 'doubled', c: 'red' } ],
  ] },
];
