/* ── Shadhā al-ʿArf — التقسيم الثالث للفعل (Worksheet 5) ──
   الفعل إلى مجرد ومزيد · الأبواب الستة للثلاثي المجرد (مع جدول الأبواب)
   The large 10-column taṣrīf grids on the worksheet are reference tables and are
   not reproduced here; the bāb-overview matrix is rendered as a `grid` block.
   Reuses the SA_* constants from wk01-muqaddimah.js (load after it).             */

const DATA_WK05 = [
  { t: 'page', n: '١' },

  { t: 'h2', c: 'blue', ar: 'التَّقْسِيمُ الثَّالِثُ لِلْفِعْلِ — بِحَسَبِ التَّجَرُّدِ وَالزِّيَادَةِ', en: 'Third Division — by Bareness & Augmentation' },

  { t: 'line', w: [
    { a: 'يَنْقَسِمُ', t: 'yanqasimu', e: 'is divided' },
    { a: 'الْفِعْلُ', t: 'al-fiʿlu', e: 'the verb' },
    { a: 'إِلَى', t: 'ilā', e: 'into' },
    { a: 'مُجَرَّدٍ', t: 'mujarradin', e: 'bare (mujarrad)', c: 'red' },
    { a: 'وَمَزِيدٍ', t: 'wa-mazīdin', e: 'and augmented (mazīd)', c: 'red' },
    { g: '.' },
  ] },

  { t: 'line', w: [
    { a: 'فَالْمُجَرَّدُ', t: 'fa-l-mujarradu', e: 'the bare', c: 'red' },
    { g: ':' },
    { a: 'مَا', t: 'mā', e: 'is that' },
    { a: 'كَانَتْ', t: 'kānat', e: 'whose' },
    { a: 'جَمِيعُ', t: 'jamīʿu', e: 'all' },
    { a: 'حُرُوفِهِ', t: 'ḥurūfihi', e: 'its letters' },
    { a: 'أَصْلِيَّةً', t: 'aṣliyyatan', e: 'are radical' },
    SA_COMMA,
    { a: 'لَا', t: 'lā', e: 'not' },
    { a: 'يَسْقُطُ', t: 'yasquṭu', e: 'falls' },
    { a: 'حَرْفٌ', t: 'ḥarfun', e: 'a letter' },
    { a: 'مِنْهَا', t: 'minhā', e: 'of them' },
    { a: 'فِي', t: 'fī', e: 'in' },
    { a: 'تَصَارِيفِ', t: 'taṣārīfi', e: 'the conjugations of' },
    { a: 'الْكَلِمَةِ', t: 'al-kalimati', e: 'the word' },
    { a: 'بِغَيْرِ', t: 'bi-ghayri', e: 'without' },
    { a: 'عِلَّةٍ', t: 'ʿillatin', e: 'a cause' },
    { g: '.' },
  ] },

  { t: 'line', w: [
    { a: 'وَالْمَزِيدُ', t: 'wa-l-mazīdu', e: 'the augmented', c: 'red' },
    { g: ':' },
    { a: 'مَا', t: 'mā', e: 'is that' },
    { a: 'زِيدَ', t: 'zīda', e: 'is added' },
    { a: 'فِيهِ', t: 'fīhi', e: 'to which' },
    { a: 'حَرْفٌ', t: 'ḥarfun', e: 'a letter' },
    { a: 'أَوْ', t: 'aw', e: 'or' },
    { a: 'أَكْثَرُ', t: 'aktharu', e: 'more' },
    { a: 'عَلَى', t: 'ʿalā', e: 'upon' },
    { a: 'حُرُوفِهِ', t: 'ḥurūfihi', e: 'its letters' },
    { a: 'الْأَصْلِيَّةِ', t: 'al-aṣliyyati', e: 'radical' },
    { g: '.' },
  ] },

  { t: 'line', w: [
    { a: 'وَالْمُجَرَّدُ', t: 'wa-l-mujarradu', e: 'the bare' },
    { a: 'قِسْمَانِ', t: 'qismāni', e: 'is two kinds' },
    { g: ':' },
    { a: 'ثُلَاثِيٌّ', t: 'thulāthiyyun', e: 'trilateral', c: 'red' },
    { a: 'وَرُبَاعِيٌّ', t: 'wa-rubāʿiyyun', e: 'and quadriliteral', c: 'red' },
    { g: '.' },
  ] },

  { t: 'line', w: [
    { a: 'وَالْمَزِيدُ', t: 'wa-l-mazīdu', e: 'the augmented' },
    { a: 'قِسْمَانِ', t: 'qismāni', e: 'is two kinds' },
    { g: ':' },
    { a: 'مَزِيدُ', t: 'mazīdu', e: 'augmented of', c: 'red' },
    { a: 'الثُّلَاثِيِّ', t: 'ath-thulāthiyyi', e: 'the trilateral', c: 'red' },
    SA_COMMA,
    { a: 'وَمَزِيدُ', t: 'wa-mazīdu', e: 'and augmented of', c: 'red' },
    { a: 'الرُّبَاعِيِّ', t: 'ar-rubāʿiyyi', e: 'the quadriliteral', c: 'red' },
    { g: '.' },
  ] },

  { t: 'line', w: [
    { a: 'أَمَّا', t: 'ammā', e: 'as for' },
    { a: 'الثُّلَاثِيُّ', t: 'ath-thulāthiyyu', e: 'the trilateral' },
    { a: 'الْمُجَرَّدُ', t: 'al-mujarradu', e: 'bare' },
    { a: 'فَلَهُ', t: 'fa-lahu', e: 'it has' },
    { a: 'بِاعْتِبَارِ', t: 'bi-ʿtibāri', e: 'by considering' },
    { a: 'مَاضِيهِ', t: 'māḍīhi', e: 'its past' },
    { a: 'فَقَطْ', t: 'faqaṭ', e: 'alone' },
    { a: 'ثَلَاثَةُ', t: 'thalāthatu', e: 'three' },
    { a: 'أَبْوَابٍ', t: 'abwābin', e: 'forms (bābs)' },
    SA_COMMA,
    { a: 'لِأَنَّهُ', t: 'li-annahu', e: 'because it' },
    { a: 'دَائِمًا', t: 'dāʾiman', e: 'always' },
    { a: 'مَفْتُوحُ', t: 'maftūḥu', e: 'has a fatḥah on' },
    { a: 'الْفَاءِ', t: 'al-fāʾi', e: 'the fāʾ' },
    SA_COMMA,
    { a: 'وَعَيْنُهُ', t: 'wa-ʿaynuhu', e: 'and its ʿayn' },
    { a: 'إِمَّا', t: 'immā', e: 'is either' },
    { a: 'مَفْتُوحَةً', t: 'maftūḥatan', e: 'fatḥah' },
    SA_COMMA,
    { a: 'أَوْ', t: 'aw', e: 'or' },
    { a: 'مَكْسُورَةً', t: 'maksūratan', e: 'kasrah' },
    { a: 'أَوْ', t: 'aw', e: 'or' },
    { a: 'مَضْمُومَةً', t: 'maḍmūmatan', e: 'ḍammah' },
    SA_COMMA,
    SA_NAHW,
    { a: 'ضَرَبَ', t: 'ḍaraba', e: 'ḍaraba' },
    { a: 'وَفَتَحَ', t: 'wa-fataḥa', e: 'and fataḥa' },
    { a: 'وَنَصَرَ', t: 'wa-naṣara', e: 'and naṣara' },
    SA_COMMA,
    { a: 'وَنَحْوُ', t: 'wa-naḥwu', e: 'and like' },
    { a: 'كَرُمَ', t: 'karuma', e: 'karuma' },
    SA_COMMA,
    { a: 'وَنَحْوُ', t: 'wa-naḥwu', e: 'and like' },
    { a: 'فَرِحَ', t: 'fariḥa', e: 'fariḥa' },
    { a: 'وَحَسِبَ', t: 'wa-ḥasiba', e: 'and ḥasiba' },
    { g: '.' },
  ] },

  { t: 'line', w: [
    { a: 'وَبِاعْتِبَارِ', t: 'wa-bi-ʿtibāri', e: 'and by considering' },
    { a: 'الْمَاضِي', t: 'al-māḍī', e: 'the past' },
    { a: 'مَعَ', t: 'maʿa', e: 'with' },
    { a: 'الْمُضَارِعِ', t: 'al-muḍāriʿi', e: 'the present' },
    { a: 'لَهُ', t: 'lahu', e: 'it has' },
    { a: 'سِتَّةُ', t: 'sittatu', e: 'six' },
    { a: 'أَبْوَابٍ', t: 'abwābin', e: 'forms' },
    SA_COMMA,
    { a: 'لِأَنَّ', t: 'li-anna', e: 'because' },
    { a: 'عَيْنَ', t: 'ʿayna', e: 'the ʿayn of' },
    { a: 'الْمُضَارِعِ', t: 'al-muḍāriʿi', e: 'the present' },
    { a: 'إِمَّا', t: 'immā', e: 'is either' },
    { a: 'مَضْمُومَةٌ', t: 'maḍmūmatun', e: 'ḍammah' },
    { a: 'أَوْ', t: 'aw', e: 'or' },
    { a: 'مَفْتُوحَةٌ', t: 'maftūḥatun', e: 'fatḥah' },
    { a: 'أَوْ', t: 'aw', e: 'or' },
    { a: 'مَكْسُورَةٌ', t: 'maksūratun', e: 'kasrah' },
    SA_COMMA,
    { a: 'وَثَلَاثَةٌ', t: 'wa-thalāthatun', e: 'and three' },
    { a: 'فِي', t: 'fī', e: 'by' },
    { a: 'ثَلَاثَةٍ', t: 'thalāthatin', e: 'three' },
    { a: 'بِتِسْعَةٍ', t: 'bi-tisʿatin', e: 'make nine' },
    SA_COMMA,
    { a: 'يَمْتَنِعُ', t: 'yamtaniʿu', e: 'barred is' },
    { a: 'كَسْرُ', t: 'kasru', e: 'the kasrah of' },
    { a: 'الْعَيْنِ', t: 'al-ʿayni', e: 'the ʿayn' },
    { a: 'فِي', t: 'fī', e: 'in' },
    { a: 'الْمَاضِي', t: 'al-māḍī', e: 'the past' },
    { a: 'مَعَ', t: 'maʿa', e: 'with' },
    { a: 'ضَمِّهَا', t: 'ḍammihā', e: 'its ḍammah' },
    { a: 'فِي', t: 'fī', e: 'in' },
    { a: 'الْمُضَارِعِ', t: 'al-muḍāriʿi', e: 'the present' },
    SA_COMMA,
    { a: 'وَضَمُّ', t: 'wa-ḍammu', e: 'and the ḍammah of' },
    { a: 'الْعَيْنِ', t: 'al-ʿayni', e: 'the ʿayn' },
    { a: 'فِي', t: 'fī', e: 'in' },
    { a: 'الْمَاضِي', t: 'al-māḍī', e: 'the past' },
    { a: 'مَعَ', t: 'maʿa', e: 'with' },
    { a: 'كَسْرِهَا', t: 'kasrihā', e: 'its kasrah' },
    { a: 'أَوْ', t: 'aw', e: 'or' },
    { a: 'فَتْحِهَا', t: 'fatḥihā', e: 'fatḥah' },
    { a: 'فِي', t: 'fī', e: 'in' },
    { a: 'الْمُضَارِعِ', t: 'al-muḍāriʿi', e: 'the present' },
    { g: '.' },
  ] },

  { t: 'grid',
    cols: ['يَفْعُلُ', 'يَفْعِلُ', 'يَفْعَلُ'],
    rows: [
      { h: 'فَعَلَ', c: ['نَصَرَ يَنْصُرُ', 'ضَرَبَ يَضْرِبُ', 'فَتَحَ يَفْتَحُ'] },
      { h: 'فَعِلَ', c: ['—', 'حَسِبَ يَحْسِبُ', 'سَمِعَ يَسْمَعُ'] },
      { h: 'فَعُلَ', c: ['كَرُمَ يَكْرُمُ', '—', '—'] },
    ],
    caption: 'أبواب الثلاثي المجرد — Patterns of al-māḍī & al-muḍāriʿ' },

  { t: 'line', w: [
    { a: 'فَإِذَنْ', t: 'fa-idhan', e: 'so then' },
    { a: 'تَكُونُ', t: 'takūnu', e: 'are' },
    { a: 'أَبْوَابُ', t: 'abwābu', e: 'the forms of' },
    { a: 'الثُّلَاثِيِّ', t: 'ath-thulāthiyyi', e: 'the trilateral' },
    { a: 'سِتَّةً', t: 'sittatan', e: 'six' },
    { g: ':' },
  ] },

  /* ── الباب الأول ── */
  { t: 'h2', c: 'blue', ar: 'الْبَابُ الْأَوَّلُ: فَعَلَ يَفْعُلُ', en: 'Form 1: faʿala – yafʿulu' },
  { t: 'line', w: [
    { a: 'بِفَتْحِ', t: 'bi-fatḥi', e: 'with a fatḥah on' },
    { a: 'الْعَيْنِ', t: 'al-ʿayni', e: 'the ʿayn' },
    { a: 'فِي', t: 'fī', e: 'in' },
    { a: 'الْمَاضِي', t: 'al-māḍī', e: 'the past' },
    { a: 'وَضَمِّهَا', t: 'wa-ḍammihā', e: 'and a ḍammah on it' },
    { a: 'فِي', t: 'fī', e: 'in' },
    { a: 'الْمُضَارِعِ', t: 'al-muḍāriʿi', e: 'the present' },
    SA_COMMA,
    { a: 'كَنَصَرَ', t: 'ka-naṣara', e: 'such as naṣara' },
    { a: 'يَنْصُرُ', t: 'yanṣuru', e: 'yanṣuru' },
    SA_COMMA,
    { a: 'وَقَعَدَ', t: 'wa-qaʿada', e: 'qaʿada' },
    { a: 'يَقْعُدُ', t: 'yaqʿudu', e: 'yaqʿudu' },
    SA_COMMA,
    { a: 'وَأَخَذَ', t: 'wa-akhadha', e: 'akhadha' },
    { a: 'يَأْخُذُ', t: 'yaʾkhudhu', e: 'yaʾkhudhu' },
    SA_COMMA,
    { a: 'وَبَرَأَ', t: 'wa-baraʾa', e: 'baraʾa' },
    { a: 'يَبْرُؤُ', t: 'yabruʾu', e: 'yabruʾu' },
    SA_COMMA,
    { a: 'وَقَالَ', t: 'wa-qāla', e: 'qāla' },
    { a: 'يَقُولُ', t: 'yaqūlu', e: 'yaqūlu' },
    SA_COMMA,
    { a: 'وَغَزَا', t: 'wa-ghazā', e: 'ghazā' },
    { a: 'يَغْزُو', t: 'yaghzū', e: 'yaghzū' },
    SA_COMMA,
    { a: 'وَمَرَّ', t: 'wa-marra', e: 'marra' },
    { a: 'يَمُرُّ', t: 'yamurru', e: 'yamurru' },
    { g: '.' },
  ] },

  /* ── الباب الثاني ── */
  { t: 'h2', c: 'blue', ar: 'الْبَابُ الثَّانِي: فَعَلَ يَفْعِلُ', en: 'Form 2: faʿala – yafʿilu' },
  { t: 'line', w: [
    { a: 'بِفَتْحِ', t: 'bi-fatḥi', e: 'with a fatḥah on' },
    { a: 'الْعَيْنِ', t: 'al-ʿayni', e: 'the ʿayn' },
    { a: 'فِي', t: 'fī', e: 'in' },
    { a: 'الْمَاضِي', t: 'al-māḍī', e: 'the past' },
    { a: 'وَكَسْرِهَا', t: 'wa-kasrihā', e: 'and a kasrah on it' },
    { a: 'فِي', t: 'fī', e: 'in' },
    { a: 'الْمُضَارِعِ', t: 'al-muḍāriʿi', e: 'the present' },
    SA_COMMA,
    { a: 'كَضَرَبَ', t: 'ka-ḍaraba', e: 'such as ḍaraba' },
    { a: 'يَضْرِبُ', t: 'yaḍribu', e: 'yaḍribu' },
    SA_COMMA,
    { a: 'وَجَلَسَ', t: 'wa-jalasa', e: 'jalasa' },
    { a: 'يَجْلِسُ', t: 'yajlisu', e: 'yajlisu' },
    SA_COMMA,
    { a: 'وَوَعَدَ', t: 'wa-waʿada', e: 'waʿada' },
    { a: 'يَعِدُ', t: 'yaʿidu', e: 'yaʿidu' },
    SA_COMMA,
    { a: 'وَبَاعَ', t: 'wa-bāʿa', e: 'bāʿa' },
    { a: 'يَبِيعُ', t: 'yabīʿu', e: 'yabīʿu' },
    SA_COMMA,
    { a: 'وَرَمَى', t: 'wa-ramā', e: 'ramā' },
    { a: 'يَرْمِي', t: 'yarmī', e: 'yarmī' },
    SA_COMMA,
    { a: 'وَوَقَى', t: 'wa-waqā', e: 'waqā' },
    { a: 'يَقِي', t: 'yaqī', e: 'yaqī' },
    SA_COMMA,
    { a: 'وَطَوَى', t: 'wa-ṭawā', e: 'ṭawā' },
    { a: 'يَطْوِي', t: 'yaṭwī', e: 'yaṭwī' },
    SA_COMMA,
    { a: 'وَفَرَّ', t: 'wa-farra', e: 'farra' },
    { a: 'يَفِرُّ', t: 'yafirru', e: 'yafirru' },
    SA_COMMA,
    { a: 'وَأَتَى', t: 'wa-atā', e: 'atā' },
    { a: 'يَأْتِي', t: 'yaʾtī', e: 'yaʾtī' },
    SA_COMMA,
    { a: 'وَجَاءَ', t: 'wa-jāʾa', e: 'jāʾa' },
    { a: 'يَجِيءُ', t: 'yajīʾu', e: 'yajīʾu' },
    SA_COMMA,
    { a: 'وَأَبَرَ', t: 'wa-abara', e: 'abara' },
    { a: 'النَّخْلَ', t: 'an-nakhla', e: 'the palm' },
    { a: 'يَأْبُرُهُ', t: 'yaʾburuhu', e: 'pollinates it' },
    SA_COMMA,
    { a: 'وَأَوَى', t: 'wa-awā', e: 'awā' },
    { a: 'يَأْوِي', t: 'yaʾwī', e: 'yaʾwī' },
    SA_COMMA,
    { a: 'وَوَأَى', t: 'wa-waʾā', e: 'waʾā', n: 'meaning waʿada — to promise' },
    { a: 'يَئِي', t: 'yaʾī', e: 'yaʾī' },
    SA_COMMA,
    { a: 'وَهَنَأَ', t: 'wa-hanaʾa', e: 'hanaʾa', n: 'to be pleasant' },
    { a: 'يَهْنِيءُ', t: 'yahniʾu', e: 'yahniʾu' },
    { g: '.' },
  ] },

  /* ── الباب الثالث ── */
  { t: 'h2', c: 'blue', ar: 'الْبَابُ الثَّالِثُ: فَعَلَ يَفْعَلُ', en: 'Form 3: faʿala – yafʿalu' },
  { t: 'line', w: [
    { a: 'بِالْفَتْحِ', t: 'bi-l-fatḥi', e: 'with a fatḥah' },
    { a: 'فِيهِمَا', t: 'fīhimā', e: 'in both' },
    { g: ':' },
    { a: 'كَفَتَحَ', t: 'ka-fataḥa', e: 'such as fataḥa' },
    { a: 'يَفْتَحُ', t: 'yaftaḥu', e: 'yaftaḥu' },
    SA_COMMA,
    { a: 'وَذَهَبَ', t: 'wa-dhahaba', e: 'dhahaba' },
    { a: 'يَذْهَبُ', t: 'yadhhabu', e: 'yadhhabu' },
    SA_COMMA,
    { a: 'وَسَعَى', t: 'wa-saʿā', e: 'saʿā' },
    { a: 'يَسْعَى', t: 'yasʿā', e: 'yasʿā' },
    SA_COMMA,
    { a: 'وَوَضَعَ', t: 'wa-waḍaʿa', e: 'waḍaʿa' },
    { a: 'يَضَعُ', t: 'yaḍaʿu', e: 'yaḍaʿu' },
    SA_COMMA,
    { a: 'وَيَفَعَ', t: 'wa-yafaʿa', e: 'yafaʿa', n: 'yafaʿa l-jabal: he climbed the mountain; (of a boy) he neared twenty' },
    { a: 'يَيْفَعُ', t: 'yayfaʿu', e: 'yayfaʿu' },
    SA_COMMA,
    { a: 'وَوَهَلَ', t: 'wa-wahala', e: 'wahala', n: 'wahala ilā sh-shayʾ: his mind went to it' },
    { a: 'يَوْهَلُ', t: 'yawhalu', e: 'yawhalu' },
    SA_COMMA,
    { a: 'وَأَلَهَ', t: 'wa-alaha', e: 'alaha', n: 'to worship' },
    { a: 'يَأْلَهُ', t: 'yaʾlahu', e: 'yaʾlahu' },
    SA_COMMA,
    { a: 'وَسَأَلَ', t: 'wa-saʾala', e: 'saʾala' },
    { a: 'يَسْأَلُ', t: 'yasʾalu', e: 'yasʾalu' },
    SA_COMMA,
    { a: 'وَقَرَأَ', t: 'wa-qaraʾa', e: 'qaraʾa' },
    { a: 'يَقْرَأُ', t: 'yaqraʾu', e: 'yaqraʾu' },
    { g: '.' },
  ] },

  { t: 'line', w: [
    { a: 'وَكُلُّ', t: 'wa-kullu', e: 'and every' },
    { a: 'مَا', t: 'mā', e: 'verb' },
    { a: 'كَانَتْ', t: 'kānat', e: 'whose' },
    { a: 'عَيْنُهُ', t: 'ʿaynuhu', e: 'ʿayn' },
    { a: 'مَفْتُوحَةً', t: 'maftūḥatan', e: 'is open' },
    { a: 'فِي', t: 'fī', e: 'in' },
    { a: 'الْمَاضِي', t: 'al-māḍī', e: 'the past' },
    { a: 'وَالْمُضَارِعِ', t: 'wa-l-muḍāriʿi', e: 'and present' },
    SA_COMMA,
    { a: 'فَهُوَ', t: 'fa-huwa', e: 'is' },
    { a: 'حَلْقِيُّ', t: 'ḥalqiyyu', e: 'guttural in', c: 'red' },
    { a: 'الْعَيْنِ', t: 'al-ʿayni', e: 'its ʿayn', c: 'red' },
    { a: 'أَوِ', t: 'awi', e: 'or' },
    { a: 'اللَّامِ', t: 'al-lāmi', e: 'lām' },
    { g: '.' },
    { a: 'وَلَيْسَ', t: 'wa-laysa', e: 'but not' },
    { a: 'كُلُّ', t: 'kullu', e: 'every' },
    { a: 'مَا', t: 'mā', e: 'verb that' },
    { a: 'كَانَ', t: 'kāna', e: 'is' },
    { a: 'حَلْقِيًّا', t: 'ḥalqiyyan', e: 'guttural' },
    { a: 'مَفْتُوحًا', t: 'maftūḥan', e: 'is open' },
    { a: 'فِيهِمَا', t: 'fīhimā', e: 'in both' },
    { g: '.' },
  ] },

  { t: 'line', w: [
    { a: 'وَحُرُوفُ', t: 'wa-ḥurūfu', e: 'and the letters of' },
    { a: 'الْحَلْقِ', t: 'al-ḥalqi', e: 'the throat' },
    { a: 'سِتَّةٌ', t: 'sittatun', e: 'are six' },
    { g: ':' },
    { a: 'الْهَمْزَةُ', t: 'al-hamzatu', e: 'the hamzah', c: 'red' },
    { a: 'وَالْهَاءُ', t: 'wa-l-hāʾu', e: 'and the hāʾ', c: 'red' },
    SA_COMMA,
    { a: 'وَالْحَاءُ', t: 'wa-l-ḥāʾu', e: 'the ḥāʾ', c: 'red' },
    { a: 'وَالْخَاءُ', t: 'wa-l-khāʾu', e: 'and the khāʾ', c: 'red' },
    SA_COMMA,
    { a: 'وَالْعَيْنُ', t: 'wa-l-ʿaynu', e: 'the ʿayn', c: 'red' },
    { a: 'وَالْغَيْنُ', t: 'wa-l-ghaynu', e: 'and the ghayn', c: 'red' },
    { g: '.' },
  ] },

  { t: 'page', n: '٣' },

  { t: 'line', w: [
    { a: 'وَمَا', t: 'wa-mā', e: 'and what' },
    { a: 'جَاءَ', t: 'jāʾa', e: 'comes' },
    { a: 'مِنْ', t: 'min', e: 'from' },
    { a: 'هَذَا', t: 'hādhā', e: 'this' },
    { a: 'الْبَابِ', t: 'al-bābi', e: 'form' },
    { a: 'بِدُونِ', t: 'bi-dūni', e: 'without' },
    { a: 'حَرْفٍ', t: 'ḥarfin', e: 'a letter' },
    { a: 'حَلْقِيٍّ', t: 'ḥalqiyyin', e: 'guttural' },
    { a: 'فَشَاذٌّ', t: 'fa-shādhdhun', e: 'is anomalous (shādhdh)', c: 'red' },
    SA_COMMA,
    { a: 'كَأَبَى', t: 'ka-abā', e: 'such as abā' },
    { a: 'يَأْبَى', t: 'yaʾbā', e: 'yaʾbā' },
    SA_COMMA,
    { a: 'وَهَلَكَ', t: 'wa-halaka', e: 'halaka' },
    { a: 'يَهْلَكُ', t: 'yahlaku', e: 'yahlaku' },
    { a: 'فِي', t: 'fī', e: 'in' },
    { a: 'إِحْدَى', t: 'iḥdā', e: 'one of' },
    { a: 'لُغَتَيْهِ', t: 'lughatayhi', e: 'its two dialects' },
    SA_COMMA,
    { a: 'أَوْ', t: 'aw', e: 'or' },
    { a: 'مِنْ', t: 'min', e: 'from' },
    { a: 'تَدَاخُلِ', t: 'tadākhuli', e: 'the overlap of' },
    { a: 'اللُّغَاتِ', t: 'al-lughāti', e: 'dialects' },
    SA_COMMA,
    { a: 'كَرَكَنَ', t: 'ka-rakana', e: 'such as rakana' },
    { a: 'يَرْكَنُ', t: 'yarkanu', e: 'yarkanu' },
    SA_COMMA,
    { a: 'وَقَلَى', t: 'wa-qalā', e: 'and qalā' },
    { a: 'يَقْلَى', t: 'yaqlā', e: 'yaqlā' },
    { a: 'غَيْرُ', t: 'ghayru', e: 'is not' },
    { a: 'فَصِيحٍ', t: 'faṣīḥin', e: 'eloquent' },
    { g: '.' },
    { a: 'وَبَقَى', t: 'wa-baqā', e: 'and baqā' },
    { a: 'يَبْقَى', t: 'yabqā', e: 'yabqā' },
    { g: ':' },
    { a: 'لُغَةُ', t: 'lughatu', e: 'is the dialect of' },
    { a: 'طَيِّئٍ', t: 'ṭayyiʾin', e: 'Ṭayyiʾ' },
    SA_COMMA,
    { a: 'وَالْأَصْلُ', t: 'wa-l-aṣlu', e: 'and the origin' },
    { a: 'كَسْرُ', t: 'kasru', e: 'is the kasrah of' },
    { a: 'الْعَيْنِ', t: 'al-ʿayni', e: 'the ʿayn' },
    { a: 'فِي', t: 'fī', e: 'in' },
    { a: 'الْمَاضِي', t: 'al-māḍī', e: 'the past' },
    SA_COMMA,
    { a: 'وَلَكِنَّهُمْ', t: 'wa-lākinnahum', e: 'but they' },
    { a: 'قَلَبُوهُ', t: 'qalabūhu', e: 'changed it' },
    { a: 'فَتْحَةً', t: 'fatḥatan', e: 'to a fatḥah' },
    { a: 'تَخْفِيفًا', t: 'takhfīfan', e: 'for ease' },
    SA_COMMA,
    { a: 'وَهَذَا', t: 'wa-hādhā', e: 'and this' },
    { a: 'قِيَاسٌ', t: 'qiyāsun', e: 'is standard' },
    { a: 'عِنْدَهُمْ', t: 'ʿindahum', e: 'for them' },
    { g: '.' },
  ] },

  /* ── الباب الرابع ── */
  { t: 'h2', c: 'blue', ar: 'الْبَابُ الرَّابِعُ: فَعِلَ يَفْعَلُ', en: 'Form 4: faʿila – yafʿalu' },
  { t: 'line', w: [
    { a: 'بِكَسْرِ', t: 'bi-kasri', e: 'with a kasrah on' },
    { a: 'الْعَيْنِ', t: 'al-ʿayni', e: 'the ʿayn' },
    { a: 'فِي', t: 'fī', e: 'in' },
    { a: 'الْمَاضِي', t: 'al-māḍī', e: 'the past' },
    SA_COMMA,
    { a: 'وَفَتْحِهَا', t: 'wa-fatḥihā', e: 'and a fatḥah on it' },
    { a: 'فِي', t: 'fī', e: 'in' },
    { a: 'الْمُضَارِعِ', t: 'al-muḍāriʿi', e: 'the present' },
    SA_COMMA,
    { a: 'كَفَرِحَ', t: 'ka-fariḥa', e: 'such as fariḥa' },
    { a: 'يَفْرَحُ', t: 'yafraḥu', e: 'yafraḥu' },
    SA_COMMA,
    { a: 'وَعَلِمَ', t: 'wa-ʿalima', e: 'ʿalima' },
    { a: 'يَعْلَمُ', t: 'yaʿlamu', e: 'yaʿlamu' },
    SA_COMMA,
    { a: 'وَوَجِلَ', t: 'wa-wajila', e: 'wajila' },
    { a: 'يَوْجَلُ', t: 'yawjalu', e: 'yawjalu' },
    SA_COMMA,
    { a: 'وَيَبِسَ', t: 'wa-yabisa', e: 'yabisa' },
    { a: 'يَيْبَسُ', t: 'yaybasu', e: 'yaybasu' },
    SA_COMMA,
    { a: 'وَخَافَ', t: 'wa-khāfa', e: 'khāfa' },
    { a: 'يَخَافُ', t: 'yakhāfu', e: 'yakhāfu' },
    SA_COMMA,
    { a: 'وَهَابَ', t: 'wa-hāba', e: 'hāba' },
    { a: 'يَهَابُ', t: 'yahābu', e: 'yahābu' },
    SA_COMMA,
    { a: 'وَغَيِدَ', t: 'wa-ghayida', e: 'ghayida' },
    { a: 'يَغْيَدُ', t: 'yaghyadu', e: 'yaghyadu' },
    SA_COMMA,
    { a: 'وَعَوِرَ', t: 'wa-ʿawira', e: 'ʿawira' },
    { a: 'يَعْوَرُ', t: 'yaʿwaru', e: 'yaʿwaru' },
    SA_COMMA,
    { a: 'وَرَضِيَ', t: 'wa-raḍiya', e: 'raḍiya' },
    { a: 'يَرْضَى', t: 'yarḍā', e: 'yarḍā' },
    SA_COMMA,
    { a: 'وَقَوِيَ', t: 'wa-qawiya', e: 'qawiya' },
    { a: 'يَقْوَى', t: 'yaqwā', e: 'yaqwā' },
    SA_COMMA,
    { a: 'وَعَضَّ', t: 'wa-ʿaḍḍa', e: 'ʿaḍḍa' },
    { a: 'يَعَضُّ', t: 'yaʿaḍḍu', e: 'yaʿaḍḍu' },
    SA_COMMA,
    { a: 'وَأَمِنَ', t: 'wa-amina', e: 'amina' },
    { a: 'يَأْمَنُ', t: 'yaʾmanu', e: 'yaʾmanu' },
    SA_COMMA,
    { a: 'وَسَئِمَ', t: 'wa-saʾima', e: 'saʾima' },
    { a: 'يَسْأَمُ', t: 'yasʾamu', e: 'yasʾamu' },
    SA_COMMA,
    { a: 'وَصَدِئَ', t: 'wa-ṣadiʾa', e: 'ṣadiʾa' },
    { a: 'يَصْدَأُ', t: 'yaṣdaʾu', e: 'yaṣdaʾu' },
    { g: '.' },
  ] },

  { t: 'line', w: [
    { a: 'وَيَأْتِي', t: 'wa-yaʾtī', e: 'and from this form come' },
    { a: 'مِنْ', t: 'min', e: '—' },
    { a: 'هَذَا', t: 'hādhā', e: '—' },
    { a: 'الْبَابِ', t: 'al-bābi', e: '—' },
    { a: 'الْأَفْعَالُ', t: 'al-afʿālu', e: 'the verbs' },
    { a: 'الدَّالَّةُ', t: 'ad-dāllatu', e: 'denoting' },
    { a: 'عَلَى', t: 'ʿalā', e: '—' },
    { g: ':' },
  ] },

  { t: 'line', w: [
    { a: 'الْفَرَحِ', t: 'al-faraḥi', e: 'joy', c: 'red' },
    { a: 'وَتَوَابِعِهِ', t: 'wa-tawābiʿihi', e: 'and its likes' },
    { g: ':' },
    { a: 'كَفَرِحَ', t: 'ka-fariḥa', e: 'such as fariḥa (rejoiced)' },
    { a: 'وَطَرِبَ', t: 'wa-ṭariba', e: 'ṭariba', n: 'to be delighted' },
    { a: 'وَبَطِرَ', t: 'wa-baṭira', e: 'baṭira', n: 'to be reckless / vain' },
    { a: 'وَأَشِرَ', t: 'wa-ashira', e: 'ashira', n: 'to rejoice excessively, to boast' },
    SA_COMMA,
    { a: 'وَغَضِبَ', t: 'wa-ghaḍiba', e: 'ghaḍiba (got angry)' },
    { a: 'وَحَزِنَ', t: 'wa-ḥazina', e: 'and ḥazina (grieved)' },
    { g: '.' },
  ] },

  { t: 'line', w: [
    { a: 'وَالِامْتِلَاءِ', t: 'wa-l-imtilāʾi', e: 'fullness', c: 'red' },
    { a: 'وَالْخُلُوِّ', t: 'wa-l-khuluwwi', e: 'and emptiness', c: 'red' },
    { g: ':' },
    { a: 'كَشَبِعَ', t: 'ka-shabiʿa', e: 'such as shabiʿa (was sated)' },
    { a: 'وَرَوِيَ', t: 'wa-rawiya', e: 'rawiya (was quenched)' },
    { a: 'وَسَكِرَ', t: 'wa-sakira', e: 'and sakira (got drunk)' },
    { g: '.' },
  ] },

  { t: 'line', w: [
    { a: 'وَالْأَلْوَانِ', t: 'wa-l-alwāni', e: 'colours', c: 'red' },
    { a: 'وَالْعُيُوبِ', t: 'wa-l-ʿuyūbi', e: 'and defects', c: 'red' },
    { g: ':' },
    { a: 'كَعَطِشَ', t: 'ka-ʿaṭisha', e: 'such as ʿaṭisha (was thirsty)' },
    { a: 'وَظَمِئَ', t: 'wa-ẓamiʾa', e: 'ẓamiʾa', n: 'to be thirsty' },
    { a: 'وَصَدِيَ', t: 'wa-ṣadiya', e: 'ṣadiya', n: 'to be very thirsty' },
    { a: 'وَهَيِمَ', t: 'wa-hayima', e: 'hayima', n: 'to drink yet remain thirsty' },
    SA_COMMA,
    { a: 'وَكَحَمِرَ', t: 'wa-ka-ḥamira', e: 'and ḥamira (became red)' },
    { a: 'وَسَوِدَ', t: 'wa-sawida', e: 'sawida (became black)' },
    SA_COMMA,
    { a: 'وَكَعَوِرَ', t: 'wa-ka-ʿawira', e: 'and ʿawira', n: 'to become one-eyed' },
    { a: 'وَعَمِشَ', t: 'wa-ʿamisha', e: 'ʿamisha', n: 'to be weak-sighted' },
    { a: 'وَجَهِرَ', t: 'wa-jahira', e: 'jahira', n: 'to have a loud voice' },
    { g: '.' },
  ] },

  { t: 'page', n: '٤' },

  { t: 'line', w: [
    { a: 'وَالْخِلَقِ', t: 'wa-l-khilaqi', e: 'physical traits', c: 'red' },
    { a: 'الظَّاهِرَةِ', t: 'aẓ-ẓāhirati', e: 'outward' },
    { a: 'الَّتِي', t: 'allatī', e: 'which' },
    { a: 'تُذْكَرُ', t: 'tudhkaru', e: 'are mentioned' },
    { a: 'لِتَحْلِيَةِ', t: 'li-taḥliyati', e: 'to describe the beauty of' },
    { a: 'الْإِنْسَانِ', t: 'al-insāni', e: 'a person' },
    { a: 'فِي', t: 'fī', e: 'in' },
    { a: 'الْغَزَلِ', t: 'al-ghazali', e: 'love-poetry' },
    { g: ':' },
    { a: 'كَغَيِدَ', t: 'ka-ghayida', e: 'such as ghayida', n: 'to have a soft, tender neck' },
    { a: 'وَهَيِفَ', t: 'wa-hayifa', e: 'hayifa', n: 'to be slim and slender' },
    { a: 'وَلَمِيَ', t: 'wa-lamiya', e: 'lamiya', n: 'to have beautiful lips' },
    { g: '.' },
  ] },

  /* ── الباب الخامس ── */
  { t: 'h2', c: 'blue', ar: 'الْبَابُ الْخَامِسُ: فَعُلَ يَفْعُلُ', en: 'Form 5: faʿula – yafʿulu' },
  { t: 'line', w: [
    { a: 'بِضَمِّ', t: 'bi-ḍammi', e: 'with a ḍammah on' },
    { a: 'الْعَيْنِ', t: 'al-ʿayni', e: 'the ʿayn' },
    { a: 'فِيهِمَا', t: 'fīhimā', e: 'in both' },
    SA_COMMA,
    { a: 'كَشَرُفَ', t: 'ka-sharufa', e: 'such as sharufa' },
    { a: 'يَشْرُفُ', t: 'yashrufu', e: 'yashrufu' },
    SA_COMMA,
    { a: 'وَحَسُنَ', t: 'wa-ḥasuna', e: 'ḥasuna' },
    { a: 'يَحْسُنُ', t: 'yaḥsunu', e: 'yaḥsunu' },
    SA_COMMA,
    { a: 'وَوَسُمَ', t: 'wa-wasuma', e: 'wasuma' },
    { a: 'يَوْسُمُ', t: 'yawsumu', e: 'yawsumu' },
    SA_COMMA,
    { a: 'وَيَمُنَ', t: 'wa-yamuna', e: 'yamuna' },
    { a: 'يَيْمُنُ', t: 'yaymunu', e: 'yaymunu' },
    SA_COMMA,
    { a: 'وَأَسُلَ', t: 'wa-asula', e: 'asula' },
    { a: 'يَأْسُلُ', t: 'yaʾsulu', e: 'yaʾsulu' },
    SA_COMMA,
    { a: 'وَلَؤُمَ', t: 'wa-laʾuma', e: 'laʾuma' },
    { a: 'يَلْؤُمُ', t: 'yalʾumu', e: 'yalʾumu' },
    SA_COMMA,
    { a: 'وَجَرُؤَ', t: 'wa-jaruʾa', e: 'jaruʾa' },
    { a: 'يَجْرُؤُ', t: 'yajruʾu', e: 'yajruʾu' },
    SA_COMMA,
    { a: 'وَسَرُوَ', t: 'wa-saruwa', e: 'saruwa' },
    { a: 'يَسْرُو', t: 'yasrū', e: 'yasrū' },
    { g: '.' },
  ] },

  { t: 'line', w: [
    { a: 'وَهَذَا', t: 'wa-hādhā', e: 'and this' },
    { a: 'الْبَابُ', t: 'al-bābu', e: 'form' },
    { a: 'لِلْأَوْصَافِ', t: 'li-l-awṣāfi', e: 'is for the traits', c: 'red' },
    { a: 'الْخِلْقِيَّةِ', t: 'al-khilqiyyati', e: 'innate (instinctive)', c: 'red' },
    SA_COMMA,
    { a: 'وَهِيَ', t: 'wa-hiya', e: 'which are' },
    { a: 'الَّتِي', t: 'allatī', e: 'those that' },
    { a: 'لَهَا', t: 'lahā', e: 'have' },
    { a: 'مُكْثٌ', t: 'mukthun', e: 'permanence' },
    { g: '.' },
  ] },

  { t: 'line', w: [
    { a: 'وَلَمْ', t: 'wa-lam', e: 'and there came' },
    { a: 'يَرِدْ', t: 'yarid', e: '—' },
    { a: 'مِنْ', t: 'min', e: 'from' },
    { a: 'هَذَا', t: 'hādhā', e: 'this' },
    { a: 'الْبَابِ', t: 'al-bābi', e: 'form' },
    { a: 'يَائِيُّ', t: 'yāʾiyyu', e: 'no yāʾ-' },
    { a: 'اللَّامِ', t: 'al-lāmi', e: 'lām verb' },
    { a: 'إِلَّا', t: 'illā', e: 'except' },
    { a: 'لَفْظَةُ', t: 'lafẓatu', e: 'the word' },
    { a: 'هَيُؤَ', t: 'hayuʾa', e: 'hayuʾa', n: 'meaning: he became of good form (ṣāra dhā hayʾah)' },
    SA_COMMA,
    { a: 'وَلَا', t: 'wa-lā', e: 'nor' },
    { a: 'مُضَاعَفًا', t: 'muḍāʿafan', e: 'a doubled one' },
    { a: 'إِلَّا', t: 'illā', e: 'except' },
    { a: 'قَلِيلًا', t: 'qalīlan', e: 'rarely' },
    SA_COMMA,
    { a: 'كَشَرُرْتَ', t: 'ka-sharurta', e: 'such as sharurta' },
    { a: 'وَلَبُبْتَ', t: 'wa-labubta', e: 'and labubta', n: 'ʿayn takes ḍammah or kasrah; the present is talabbu with fatḥah only' },
    { g: '.' },
  ] },

  { t: 'line', w: [
    { a: 'وَلَكَ', t: 'wa-laka', e: 'and you may' },
    { a: 'أَنْ', t: 'an', e: '—' },
    { a: 'تُحَوِّلَ', t: 'tuḥawwila', e: 'convert' },
    { a: 'كُلَّ', t: 'kulla', e: 'any' },
    { a: 'فِعْلٍ', t: 'fiʿlin', e: 'verb' },
    { a: 'ثُلَاثِيٍّ', t: 'thulāthiyyin', e: 'trilateral' },
    { a: 'إِلَى', t: 'ilā', e: 'to' },
    { a: 'هَذَا', t: 'hādhā', e: 'this' },
    { a: 'الْبَابِ', t: 'al-bābi', e: 'form' },
    SA_COMMA,
    { a: 'لِلدَّلَالَةِ', t: 'li-d-dalālati', e: 'to indicate' },
    { a: 'عَلَى', t: 'ʿalā', e: 'that' },
    { a: 'أَنَّ', t: 'anna', e: '—' },
    { a: 'مَعْنَاهُ', t: 'maʿnāhu', e: 'its meaning' },
    { a: 'صَارَ', t: 'ṣāra', e: 'has become' },
    { a: 'كَالْغَرِيزَةِ', t: 'ka-l-gharīzati', e: 'like an instinct' },
    { a: 'فِي', t: 'fī', e: 'in' },
    { a: 'صَاحِبِهِ', t: 'ṣāḥibihi', e: 'its possessor' },
    { g: ':' },
    SA_NAHW,
    { a: 'جَهِلَ', t: 'jahila', e: 'jahila' },
    { a: 'وَجَهُلَ', t: 'wa-jahula', e: 'and jahula' },
    SA_COMMA,
    { a: 'وَأَكَلَ', t: 'wa-akala', e: 'akala' },
    { a: 'وَأَكُلَ', t: 'wa-akula', e: 'and akula' },
    { g: '.' },
  ] },

  { t: 'line', w: [
    { a: 'وَرُبَّمَا', t: 'wa-rubbamā', e: 'and sometimes' },
    { a: 'اسْتُعْمِلَتْ', t: 'ustuʿmilat', e: 'are used' },
    { a: 'أَفْعَالُ', t: 'afʿālu', e: 'the verbs of' },
    { a: 'هَذَا', t: 'hādhā', e: 'this' },
    { a: 'الْبَابِ', t: 'al-bābi', e: 'form' },
    { a: 'لِلتَّعَجُّبِ', t: 'li-t-taʿajjubi', e: 'for wonderment', c: 'red' },
    SA_COMMA,
    { a: 'فَتَنْسَلِخُ', t: 'fa-tanslakhu', e: 'shedding' },
    { a: 'عَنِ', t: 'ʿani', e: '—' },
    { a: 'الْحَدَثِ', t: 'al-ḥadathi', e: 'the action' },
    SA_COMMA,
    { a: 'كَضَرُبَتْ', t: 'ka-ḍarubat', e: 'such as ḍarubat' },
    { a: 'يَدُهُ', t: 'yaduhu', e: 'his hand' },
    { a: 'بِمَعْنَى', t: 'bi-maʿnā', e: 'meaning' },
    { a: 'مَا', t: 'mā', e: 'how' },
    { a: 'أَضْرَبَهُ', t: 'aḍrabahu', e: 'skilful he is' },
    { a: 'تَعَجُّبًا', t: 'taʿajjuban', e: 'in wonder' },
    { a: 'مِنْ', t: 'min', e: 'at' },
    { a: 'ضَرْبِهِ', t: 'ḍarbihi', e: 'his striking' },
    { g: '.' },
  ] },

  /* ── الباب السادس ── */
  { t: 'h2', c: 'blue', ar: 'الْبَابُ السَّادِسُ: فَعِلَ يَفْعِلُ', en: 'Form 6: faʿila – yafʿilu' },
  { t: 'line', w: [
    { a: 'بِالْكَسْرِ', t: 'bi-l-kasri', e: 'with a kasrah' },
    { a: 'فِيهِمَا', t: 'fīhimā', e: 'in both' },
    SA_COMMA,
    { a: 'كَحَسِبَ', t: 'ka-ḥasiba', e: 'such as ḥasiba' },
    { a: 'يَحْسِبُ', t: 'yaḥsibu', e: 'yaḥsibu' },
    { a: 'وَنَعِمَ', t: 'wa-naʿima', e: 'naʿima' },
    { a: 'يَنْعِمُ', t: 'yanʿimu', e: 'yanʿimu' },
    SA_COMMA,
    { a: 'وَهُوَ', t: 'wa-huwa', e: 'and it is' },
    { a: 'قَلِيلٌ', t: 'qalīlun', e: 'rare' },
    { a: 'فِي', t: 'fī', e: 'in' },
    { a: 'الصَّحِيحِ', t: 'aṣ-ṣaḥīḥi', e: 'the sound (verb)' },
    SA_COMMA,
    { a: 'كَثِيرٌ', t: 'kathīrun', e: 'frequent' },
    { a: 'فِي', t: 'fī', e: 'in' },
    { a: 'الْمُعْتَلِّ', t: 'al-muʿtalli', e: 'the defective' },
    { g: '(٢٤ فعلًا)' },
    SA_COMMA,
    { a: 'كَمَا', t: 'kamā', e: 'as' },
    { a: 'سَيَأْتِي', t: 'sa-yaʾtī', e: 'will follow' },
    { g: ':' },
  ] },
];
