// Module 17 — الرسم والوصل والوقف: أول ثلاثة أبواب من خاتمة النحو
//
// Content is adapted from the first three sub-decks of النَحْوُ__5
// الخاتمة__3 الحرف.apkg (36 notes: 08 Orthography 12, 09 Wasl 14, 10 Waqf
// 10). The fourth sub-topic of this deck, وجوه الكلمات (140 notes across
// four further sub-decks), is large enough on its own to form Module 18 —
// this module covers only the three "mechanics of the written/spoken
// word" topics: رسم الحروف (where writing and pronunciation of a word
// diverge), الوصل (connecting speech: همزة الوصل and التقاء الساكنين),
// and الوقف (how to stop correctly on a word).

export default {
  id: '17',
  title: 'الرسم والوصل والوقف',
  heading: 'الخاتمة',
  blurb: 'The mechanics of writing and reading a word correctly: رسم الحروف (where the Uthmanic script writes a letter that isn’t pronounced, or drops one that is), الوصل (همزة الوصل and resolving التقاء الساكنين), and الوقف (how to stop on a word that ends in a سكون, a تاء مربوطة, a منقوص, or a تنوين).',
  lessons: [
    // ---------------------------------------------------------------- L1
    {
      id: 'l1',
      title: 'رَسْمُ الْحُرُوفِ',
      subtitle: 'Orthography — where the Uthmanic script writes a letter that isn’t pronounced, or drops one that is',
      concepts: [
        {
          heading: 'مَوْضُوعُ خَاتِمَةِ النَّحْوِ، وَمَجَالَا الرَّسْمِ',
          tldr: 'الْخَاتِمَة closes النَّحْو with four chapters, and the first of them, الرَّسْم, studies only the places where writing and pronunciation part company.',
          body: `The <bdi>خَاتِمَة</bdi> that closes النَّحْو covers four topics: (1) <bdi>رَسْمُ الْحُرُوفِ</bdi> — orthography, (2) <bdi>الْوَصْل</bdi> — joining one word to the next in speech, (3) <bdi>الْوَقْف</bdi> — stopping on a word, (4) <bdi>وُجُوهُ الْكَلِمَاتِ</bdi> — the several uses one word can carry. This module takes the first three of them. <bdi>الرَّسْم</bdi> itself has exactly two halves: (1) <bdi>مَا يُكْتَبُ وَلَا يُلْفَظُ</bdi> — what the script writes but the tongue never says, (2) <bdi>مَا يُلْفَظُ وَلَا يُكْتَبُ</bdi> — what the tongue says but the script never writes. So الرَّسْم is not about إِعْرَاب at all. It is about the gap between the written word and the spoken one.`,
          examples: [
            { ar: 'أَطَاعُوا', en: 'they obeyed', note: 'مَا يُكْتَبُ وَلَا يُلْفَظُ — the أَلِف after the وَاو sits on the page and has no share in the sound' },
            { ar: 'الْعَٰلَمِينَ', en: 'the worlds', note: 'مَا يُلْفَظُ وَلَا يُكْتَبُ — you pronounce an أَلِف after the عَيْن that the Uthmanic spelling leaves out' },
          ],
          exercise: {
            prompt: `The chapter of الرَّسْم divides into exactly two halves. Which pair names them?`,
            kind: 'mcq',
            options: ['مَا يُكْتَبُ وَلَا يُلْفَظُ، وَمَا يُلْفَظُ وَلَا يُكْتَبُ', 'الْوَصْلُ وَالْوَقْفُ', 'هَمْزَةُ الْوَصْلِ وَالْتِقَاءُ السَّاكِنَيْنِ', 'رَسْمُ الْحُرُوفِ وَوُجُوهُ الْكَلِمَاتِ'],
            correct: 0,
          },
        },
        {
          heading: 'الْأَلِفُ الَّتِي تُكْتَبُ وَلَا تُلْفَظُ',
          tldr: 'Only two things in the language write an أَلِف that is never pronounced: the أَلِف after وَاوُ الْجَمَاعَةِ, and the أَلِف inside مِائَة.',
          body: `Two cases, and only two, put an <bdi>أَلِف</bdi> on the page that the tongue never reaches: (1) after the <bdi>وَاوُ الْجَمَاعَةِ</bdi> of a verb, as in <bdi>أَطَاعُوا</bdi>, (2) inside the word <bdi>مِائَة</bdi>. Read <bdi>أَطَاعُوا</bdi> aloud and it ends on the long ū of the وَاو, with nothing after it. Read <bdi>مِائَة</bdi> aloud and it is simply <bdi>مِئَة</bdi>. In both the أَلِف belongs to the script alone. These two are the whole of <bdi>مَا يُكْتَبُ وَلَا يُلْفَظُ</bdi>.`,
          examples: [
            { ar: 'أَطَاعُوا رَبَّهُمْ', en: 'they obeyed their Lord', note: 'the أَلِف after وَاوُ الْجَمَاعَةِ is written but silent — the verb is read أَطَاعُو' },
            { ar: 'مِائَةُ دِرْهَمٍ', en: 'a hundred dirhams', note: 'مِائَة is read مِئَة, its أَلِف being on the page only; دِرْهَمٍ is مَجْرُور as the مُضَافٌ إِلَيْهِ' },
            { ar: 'كَتَبُوا الدَّرْسَ', en: 'they wrote the lesson', note: 'the same rule on a different verb — any وَاوُ الْجَمَاعَةِ takes a silent أَلِف after it' },
          ],
          exercise: {
            prompt: `Which one of these four أَلِفَات is written but never pronounced?`,
            kind: 'mcq',
            options: ['The أَلِف after وَاوُ الْجَمَاعَةِ in أَطَاعُوا', 'The أَلِف of the جَمْعُ الْمُذَكَّرِ السَّالِمِ in ﴿الْعَٰلَمِينَ﴾', 'The أَلِف of the pronoun نَا in ﴿زِدْنَٰهُمْ﴾', 'The أَلِف that تَنْوِينُ الْفَتْحِ turns into at الْوَقْف'],
            correct: 0,
          },
        },
        {
          heading: 'الْأَلِفُ الَّتِي تُلْفَظُ وَلَا تُكْتَبُ (الرَّسْمُ الْعُثْمَانِيُّ)',
          tldr: 'الرَّسْمُ الْعُثْمَانِيُّ leaves a fully pronounced أَلِف out of the writing in four cases: the two sound plurals, a long اسْم أَعْجَمِيّ, and نَا before الْهَاءُ وَأَخَوَاتُهَا.',
          body: `In <bdi>الرَّسْمُ الْعُثْمَانِيُّ</bdi> an أَلِف that is fully pronounced is left out of the writing in four cases: (1) the <bdi>جَمْعُ الْمُذَكَّرِ السَّالِمُ</bdi>, e.g. ﴿الْعَٰلَمِينَ﴾, (2) the <bdi>جَمْعُ الْمُؤَنَّثِ السَّالِمُ</bdi>, e.g. ﴿كَلِمَٰتٍ﴾, (3) an <bdi>اسْمٌ أَعْجَمِيٌّ</bdi> of more than three letters, e.g. ﴿إِبْرَٰهِمَ وَإِسْمَٰعِيلَ وَإِسْحَٰقَ﴾, (4) the pronoun <bdi>نَا</bdi> standing before <bdi>الْهَاءُ وَأَخَوَاتُهَا</bdi>, e.g. ﴿زِدْنَٰهُمْ﴾. None of these is a misspelling to be tidied up. The small upright stroke <bdi>ٰ</bdi> printed over the letter is the mushaf telling you that the أَلِف is still fully there in the sound.`,
          examples: [
            { ar: '﴿الْحَمْدُ لِلَّهِ رَبِّ الْعَٰلَمِينَ﴾', en: 'Praise be to Allah, Lord of the worlds', note: 'الْعَٰلَمِينَ is a جَمْعُ مُذَكَّرٍ سَالِمٌ, مَجْرُور as مُضَافٌ إِلَيْهِ, and read with an أَلِف the page does not show' },
            { ar: '﴿كَلِمَٰتٍ﴾', en: '(certain) words', note: 'جَمْعُ الْمُؤَنَّثِ السَّالِمُ — read كَلِمَاتٍ, though the أَلِف before the تَاء is unwritten' },
            { ar: '﴿زِدْنَٰهُمْ﴾', en: 'We increased them', note: 'the فَاعِل نَا is read in full, yet only its نُون is written, because هُمْ (of الْهَاءُ وَأَخَوَاتُهَا) follows it' },
          ],
          exercise: {
            prompt: `﴿زِدْنَٰهُمْ﴾ drops the أَلِف of the pronoun نَا from the writing. Which of these also drops a pronounced أَلِف in الرَّسْمُ الْعُثْمَانِيُّ?`,
            kind: 'mcq',
            options: ['﴿كَلِمَٰتٍ﴾ — the جَمْعُ الْمُؤَنَّثِ السَّالِمُ', 'أَطَاعُوا — the أَلِف after وَاوُ الْجَمَاعَةِ', 'مِائَة — the أَلِف written inside it', 'حَمْزَةْ — the تَاء stopped on as a هَاء'],
            correct: 0,
          },
        },
        {
          heading: 'حَذْفُ الْيَاءِ وَالْوَاوِ رَسْمًا',
          tldr: 'The يَاء is dropped from the writing in five cases, the وَاو in one — and in every one of the six the letter is still pronounced.',
          body: `The <bdi>يَاء</bdi> is dropped from the writing in five cases: (1) two يَاءَانِ meeting in the middle of a word, e.g. ﴿الْأُمِّيّٖنَ﴾, (2) two يَاءَانِ meeting at the end of a word, e.g. ﴿يُحْيٖ﴾, (3) a يَاء with a <bdi>سَاكِن</bdi> right after it, e.g. ﴿يُنَادِ الْمُنَادِ﴾, (4) a يَاء falling at the end of an <bdi>آيَة</bdi>, e.g. ﴿الْكَبِيرُ الْمُتَعَالِ﴾, (5) a word مُضَاف to <bdi>يَاءُ الْمُتَكَلِّمِ</bdi> in a نِدَاء, e.g. ﴿رَبِّ اجْعَلْنِي مُقِيمَ الصَّلَوٰةِ﴾. The <bdi>وَاو</bdi> has one case only: a سَاكِنَة وَاو meeting another وَاو after a <bdi>ضَمَّة</bdi>, as in ﴿يَسْتَوٗنَ﴾, written for <bdi>يَسْتَوُونَ</bdi>. Note that none of these six is a deletion in speech. The letter is still read; only the page is short of it.`,
          examples: [
            { ar: '﴿يَوْمَ يُنَادِ الْمُنَادِ﴾', en: 'the Day the caller calls', note: 'يُنَادِي loses its يَاء on the page because the سَاكِن لَام of الْمُنَادِ follows — it is still read يُنَادِي' },
            { ar: '﴿الْكَبِيرُ الْمُتَعَالِ﴾', en: 'the Great, the Most High', note: 'رَأْسُ آيَةٍ — الْمُتَعَالِي drops its يَاء in writing purely because the verse ends there' },
            { ar: '﴿يَسْتَوٗنَ﴾', en: 'they are equal', note: 'the single وَاو case: يَسْتَوُونَ has a سَاكِنَة وَاو after a ضَمَّة, so one وَاو goes unwritten' },
          ],
          exercise: {
            prompt: `Why is the يَاء of ﴿الْكَبِيرُ الْمُتَعَالِ﴾ dropped from the writing?`,
            kind: 'mcq',
            options: ['It falls at the end of an آيَة', 'Two يَاءَانِ meet in the middle of the word', 'A سَاكِن follows it', 'It is مُضَاف to يَاءُ الْمُتَكَلِّمِ'],
            correct: 0,
          },
        },
        {
          heading: 'الْأَلِفُ الْمُتَطَرِّفَةُ: فِي الثُّلَاثِيِّ وَمَا زَادَ عَلَيْهِ',
          tldr: 'In a ثُلَاثِيّ the origin of the final أَلِف decides its shape — ى from a يَاء, ا from a وَاو — but past three letters it is written ى either way.',
          body: `<bdi>الْأَلِفُ الْمُتَطَرِّفَةُ</bdi> is the أَلِف that lands at the very end of a word, and its shape turns on the word's length. In a <bdi>ثُلَاثِيّ</bdi> the origin of the أَلِف decides: (1) origin a <bdi>يَاء</bdi> — write <bdi>ى</bdi>, as in <bdi>سَعَى الْفَتَى إِلَى الْهُدَى</bdi>, (2) origin a <bdi>وَاو</bdi> — write a plain <bdi>ا</bdi>, as in <bdi>دَعَا النَّبِيُّ ﷺ بِالْخُلُقِ لَا بِالْعَصَا</bdi>. In a word of four letters or more the question of origin never arises: the أَلِف is written <bdi>ى</bdi> either way, as in <bdi>الْمُصْطَفَى</bdi>. To find the origin, put the اسْم into the <bdi>مُثَنَّى</bdi>. <bdi>الْعَصَا</bdi> gives <bdi>عَصَوَانِ</bdi>, showing a وَاو, while <bdi>الْفَتَى</bdi> gives <bdi>فَتَيَانِ</bdi>, showing a يَاء.`,
          examples: [
            { ar: 'سَعَى الْفَتَى إِلَى الْهُدَى', en: 'the youth strove toward guidance', note: 'three ثُلَاثِيّ words whose أَلِف comes from a يَاء, so all three take ى; الْفَتَى is a فَاعِل مَرْفُوع by a ضَمَّة مُقَدَّرَة' },
            { ar: 'دَعَا النَّبِيُّ ﷺ بِالْخُلُقِ لَا بِالْعَصَا', en: 'the Prophet ﷺ called by good character, not by the stick', note: 'دَعَا and الْعَصَا trace back to a وَاو (عَصَوَانِ), so each takes a plain ا' },
            { ar: 'اقْتَدَيْتُ بِالْمُصْطَفَى ﷺ', en: 'I followed the Chosen One ﷺ', note: 'الْمُصْطَفَى runs past three letters, so its final أَلِف is ى whatever its origin' },
          ],
          exercise: {
            prompt: `الْعَصَا is written with a plain ا while الْهُدَى is written with ى. What explains the difference?`,
            kind: 'mcq',
            options: ['The أَلِف of الْعَصَا comes from a وَاو (عَصَوَانِ); that of الْهُدَى comes from a يَاء', 'الْعَصَا is four letters, while الْهُدَى is only three', 'الْعَصَا is مَبْنِيّ, while الْهُدَى is مُعْرَب', 'There is no rule — the two spellings are simply conventional'],
            correct: 0,
          },
        },
      ],
      quiz: [
        {
          q: 'What are the two areas of study within رَسْمُ الْحُرُوفِ؟',
          options: ['مَا يُكْتَبُ وَلَا يُلْفَظُ، وَمَا يُلْفَظُ وَلَا يُكْتَبُ', 'الْوَصْلُ وَالْوَقْفُ', 'هَمْزَةُ الْوَصْلِ وَالْتِقَاءُ السَّاكِنَيْنِ', 'الِاسْمُ وَالْفِعْلُ'],
          correct: 0,
        },
        {
          q: 'Which two cases write an أَلِف that is never pronounced?',
          options: ['The أَلِف after وَاوُ الْجَمَاعَةِ in أَطَاعُوا, and the أَلِف of مِائَة', 'The أَلِف of ﴿الْعَٰلَمِينَ﴾, and the أَلِف of ﴿كَلِمَٰتٍ﴾', 'The أَلِف of an اسْم أَعْجَمِيّ, and نَا before الْهَاء', 'None — every أَلِف written in Arabic is pronounced'],
          correct: 0,
        },
        {
          q: 'In الرَّسْمُ الْعُثْمَانِيُّ, in how many cases is a pronounced أَلِف left out of the writing?',
          options: ['Two', 'Three', 'Four', 'Five'],
          correct: 2,
        },
        {
          q: '﴿يُنَادِ الْمُنَادِ﴾ drops the يَاء of يُنَادِي. Why?',
          options: ['Because a سَاكِن follows it', 'Because two يَاءَانِ meet in the middle of the word', 'Because it falls at the end of an آيَة', 'Because it is مُضَاف to يَاءُ الْمُتَكَلِّمِ'],
          correct: 0,
        },
        {
          q: 'When is the وَاو dropped from the writing?',
          options: ['When a سَاكِنَة وَاو meets another وَاو after a ضَمَّة, as in ﴿يَسْتَوٗنَ﴾', 'When a سَاكِنَة وَاو meets another وَاو after a كَسْرَة', 'At the end of every آيَة without exception', 'When the word is مُضَاف to يَاءُ الْمُتَكَلِّمِ'],
          correct: 0,
        },
        {
          q: 'الْمُصْطَفَى runs to more than three letters. How is its final أَلِف written?',
          options: ['ى, whatever the أَلِف’s origin', 'ا, whatever the أَلِف’s origin', 'ى if the origin is a وَاو, ا if it is a يَاء', 'Either shape, at the writer’s choice'],
          correct: 0,
        },
      ],
      bank: [
        {
          title: 'أَبْوَابُ الْخَاتِمَةِ الْأَرْبَعَةُ',
          kind: 'mcq',
          prompt: 'The خَاتِمَة that closes النَّحْو is built from how many chapters, and which?',
          options: ['Four: رَسْمُ الْحُرُوفِ، الْوَصْلُ، الْوَقْفُ، وُجُوهُ الْكَلِمَاتِ', 'Three: الِاسْمُ، الْفِعْلُ، الْحَرْفُ', 'Two: مَا يُكْتَبُ، وَمَا يُلْفَظُ', 'Five, adding التَّرْكِيبُ to the four'],
          correct: 0,
        },
        {
          title: 'أَطَاعُوا',
          kind: 'mcq',
          prompt: 'Which رَسْم rule is at work in أَطَاعُوا?',
          options: ['An أَلِف after وَاوُ الْجَمَاعَةِ, written but not pronounced', 'An أَلِف of the جَمْعُ الْمُذَكَّرِ السَّالِمِ, pronounced but not written', 'A يَاء dropped because a سَاكِن follows it', 'A وَاو dropped after a ضَمَّة'],
          correct: 0,
        },
        {
          title: 'مِائَة',
          kind: 'mcq',
          prompt: 'مِائَة carries a silent أَلِف in its spelling. What licenses it?',
          options: ['It is one of only two cases in which an unpronounced أَلِف is written', 'It is an اسْم أَعْجَمِيّ of more than three letters', 'It is a جَمْعُ مُؤَنَّثٍ سَالِمٌ', 'It is مُضَاف to يَاءُ الْمُتَكَلِّمِ'],
          correct: 0,
        },
        {
          title: '﴿الْعَٰلَمِينَ﴾',
          kind: 'mcq',
          prompt: 'Which رَسْم rule explains the missing أَلِف in ﴿الْعَٰلَمِينَ﴾?',
          options: ['The جَمْعُ الْمُذَكَّرِ السَّالِمُ drops its pronounced أَلِف in writing', 'The جَمْعُ الْمُؤَنَّثِ السَّالِمُ drops its pronounced أَلِف', 'An اسْم أَعْجَمِيّ over three letters drops its أَلِف', 'نَا before الْهَاءُ وَأَخَوَاتُهَا drops its أَلِف'],
          correct: 0,
        },
        {
          title: '﴿كَلِمَٰتٍ﴾',
          kind: 'mcq',
          prompt: 'Which case of أَلِف-omission does ﴿كَلِمَٰتٍ﴾ illustrate?',
          options: ['جَمْعُ الْمُؤَنَّثِ السَّالِمِ', 'جَمْعُ الْمُذَكَّرِ السَّالِمِ', 'الِاسْمُ الْأَعْجَمِيُّ', 'نَا قَبْلَ الْهَاءِ وَأَخَوَاتِهَا'],
          correct: 0,
        },
        {
          title: '﴿إِبْرَٰهِمَ وَإِسْمَٰعِيلَ وَإِسْحَٰقَ﴾',
          kind: 'mcq',
          prompt: 'These three names all drop a pronounced أَلِف from the writing. What is the condition?',
          options: ['Being an اسْم أَعْجَمِيّ of more than three letters', 'Being a جَمْعُ مُذَكَّرٍ سَالِمٌ', 'Being مُضَاف to the pronoun نَا', 'Being an اسْم مَنْقُوص at the end of an آيَة'],
          correct: 0,
        },
        {
          title: '﴿زِدْنَٰهُمْ﴾',
          kind: 'mcq',
          prompt: 'What exactly is left out of the spelling of ﴿زِدْنَٰهُمْ﴾?',
          options: ['The أَلِف of the pronoun نَا, standing before الْهَاءُ وَأَخَوَاتُهَا', 'The يَاء of an اسْم مَنْقُوص', 'The وَاو of وَاوُ الْجَمَاعَةِ', 'The أَلِف of a جَمْع مُذَكَّر سَالِم'],
          correct: 0,
        },
        {
          title: '﴿الْأُمِّيّٖنَ﴾',
          kind: 'mcq',
          prompt: 'Why does ﴿الْأُمِّيّٖنَ﴾ drop one of its يَاءَانِ in writing?',
          options: ['Two يَاءَانِ meet in the middle of the word', 'Two يَاءَانِ meet at the end of the word', 'A سَاكِن follows the يَاء', 'The word falls at the end of an آيَة'],
          correct: 0,
        },
        {
          title: '﴿يُحْيٖ﴾',
          kind: 'mcq',
          prompt: 'Why does ﴿يُحْيٖ﴾ drop its final يَاء in writing?',
          options: ['Two يَاءَانِ meet at the end of the word', 'Two يَاءَانِ meet in the middle of the word', 'It is مُضَاف to يَاءُ الْمُتَكَلِّمِ', 'It falls at the end of an آيَة'],
          correct: 0,
        },
        {
          title: '﴿رَبِّ اجْعَلْنِي مُقِيمَ الصَّلَوٰةِ﴾',
          kind: 'mcq',
          prompt: '﴿رَبِّ﴾ here drops its يَاء in writing. Why?',
          options: ['It is مُضَاف to يَاءُ الْمُتَكَلِّمِ inside a نِدَاء', 'A سَاكِن follows it', 'It falls at the end of an آيَة', 'Two يَاءَانِ meet in the middle of the word'],
          correct: 0,
        },
        {
          title: '﴿يَسْتَوٗنَ﴾',
          kind: 'mcq',
          prompt: 'What is dropped from the writing of ﴿يَسْتَوٗنَ﴾ (originally يَسْتَوُونَ), and on what condition?',
          options: ['A وَاو, when a سَاكِنَة وَاو meets a ضَمَّة before it', 'A يَاء, when two يَاءَانِ meet', 'An أَلِف, after وَاوُ الْجَمَاعَةِ', 'A هَمْزَة, at the head of the word'],
          correct: 0,
        },
        {
          title: 'سَعَى وَدَعَا',
          kind: 'mcq',
          prompt: 'Why is the final أَلِف of سَعَى written ى while that of دَعَا is written ا?',
          options: ['The أَلِف of سَعَى comes from a يَاء, that of دَعَا from a وَاو', 'سَعَى has four letters, while دَعَا has three', 'سَعَى is a فِعْل, while دَعَا is an اسْم', 'No rule distinguishes them — both spellings are free'],
          correct: 0,
        },
        {
          title: 'إِلَى الْهُدَى',
          kind: 'mcq',
          prompt: 'الْهُدَى ends in an أَلِف written ى. What does that shape tell you about the أَلِف?',
          options: ['That its origin is a يَاء (هَدَيَ)', 'That its origin is a وَاو', 'That the word is رُبَاعِيّ', 'That the أَلِف is زَائِدَة, not أَصْلِيَّة'],
          correct: 0,
        },
        {
          title: 'الْمُصْطَفَى',
          kind: 'mcq',
          prompt: 'الْمُصْطَفَى has more than three letters. How is its final أَلِف written, whatever its origin?',
          options: ['ى, dotless', 'ا, plain', 'Either ى or ا, freely', 'It is dropped from the writing altogether'],
          correct: 0,
        },
        {
          title: 'لَا بِالْعَصَا',
          kind: 'mcq',
          prompt: 'الْعَصَا traces back to عَصَوَانِ. What does that origin settle about its final أَلِف?',
          options: ['A plain ا, because the origin is a وَاو', 'A dotless ى, because the origin is a يَاء', 'Either shape, since عَصَا is only three letters', 'ى, because the word is مُضَاف'],
          correct: 0,
        },
        {
          title: 'اخْتِبَارُ الْمُثَنَّى',
          kind: 'mcq',
          prompt: 'الْفَتَى gives فَتَيَانِ in the مُثَنَّى. What question does that dual settle?',
          options: ['Whether the final أَلِف is from a يَاء or a وَاو, and so whether it is written ى or ا', 'Whether the word is مُعْرَب or مَبْنِيّ', 'Whether the أَلِف is pronounced or silent', 'Whether the word takes تَنْوِين at الْوَقْف'],
          correct: 0,
        },
        {
          title: 'الرَّسْمُ: التَّعْرِيفُ',
          kind: 'mcq',
          prompt: 'الرَّسْم as a topic studies:',
          options: ['Where the writing and the pronunciation of a word diverge', 'Where to stop when reading aloud', 'How to join one word to the next in recitation', 'The several grammatical uses one word can carry'],
          correct: 0,
        },
        {
          title: 'مَا يُكْتَبُ وَلَا يُلْفَظُ',
          kind: 'mcq',
          prompt: 'Which of these is an instance of مَا يُكْتَبُ وَلَا يُلْفَظُ?',
          options: ['The أَلِف of أَطَاعُوا', 'The أَلِف of ﴿الْعَٰلَمِينَ﴾', 'The يَاء of ﴿يُحْيٖ﴾', 'The وَاو of ﴿يَسْتَوٗنَ﴾'],
          correct: 0,
        },
        {
          title: 'مَا يُلْفَظُ وَلَا يُكْتَبُ',
          kind: 'mcq',
          prompt: 'Which of these is an instance of مَا يُلْفَظُ وَلَا يُكْتَبُ?',
          options: ['The أَلِف of ﴿كَلِمَٰتٍ﴾', 'The أَلِف of أَطَاعُوا', 'The أَلِف of مِائَة', 'None — whatever is pronounced is also written'],
          correct: 0,
        },
        {
          title: 'الْأَلِفُ الْخَنْجَرِيَّةُ',
          kind: 'mcq',
          prompt: 'A small upright stroke (ٰ) is printed over a letter in the mushaf, as in ﴿كَلِمَٰتٍ﴾. What is it telling the reader?',
          options: ['That an أَلِف is pronounced there although it is not written', 'That the letter under it is سَاكِن', 'That the أَلِف written there is silent', 'That the reader must stop on the word'],
          correct: 0,
        },
        {
          title: 'كَلِمَةٌ بِلَا مُخَالَفَةٍ',
          kind: 'mcq',
          prompt: 'In which of these four words do the writing and the pronunciation agree completely, with no رَسْم rule in play?',
          options: ['كَتَبَ الطَّالِبُ', 'أَطَاعُوا', 'مِائَة', '﴿يُحْيٖ﴾'],
          correct: 0,
        },
        {
          title: 'تَرْكِيب: أَتُكْتَبُ الْأَلِفُ أَمْ تُلْفَظُ؟',
          kind: 'tarkeeb',
          instruction: 'Classify the أَلِف in each word as تُكْتَبُ وَلَا تُلْفَظُ or تُلْفَظُ وَلَا تُكْتَبُ.',
          source: 'أَطَاعُوا / مِائَة / ﴿الْعَٰلَمِينَ﴾ / ﴿زِدْنَٰهُمْ﴾',
          words: ['أَطَاعُوا', 'مِائَة', 'الْعَٰلَمِينَ', 'زِدْنَٰهُمْ'],
          labels: ['تُكْتَبُ وَلَا تُلْفَظُ', 'تُكْتَبُ وَلَا تُلْفَظُ', 'تُلْفَظُ وَلَا تُكْتَبُ', 'تُلْفَظُ وَلَا تُكْتَبُ'],
          distractors: ['تُكْتَبُ وَتُلْفَظُ مَعًا'],
        },
        {
          title: 'تَرْكِيب: لِمَاذَا حُذِفَتِ الْأَلِفُ؟',
          kind: 'tarkeeb',
          instruction: 'Identify which of the four الرَّسْم الْعُثْمَانِيّ cases explains the missing أَلِف in each word.',
          source: '﴿الْعَٰلَمِينَ﴾ / ﴿كَلِمَٰتٍ﴾ / ﴿إِبْرَٰهِمَ﴾ / ﴿زِدْنَٰهُمْ﴾',
          words: ['الْعَٰلَمِينَ', 'كَلِمَٰتٍ', 'إِبْرَٰهِمَ', 'زِدْنَٰهُمْ'],
          labels: ['جَمْعُ مُذَكَّرٍ سَالِمٌ', 'جَمْعُ مُؤَنَّثٍ سَالِمٌ', 'اسْمٌ أَعْجَمِيٌّ فَوْقَ ثَلَاثَةِ أَحْرُفٍ', 'نَا قَبْلَ الْهَاءِ وَأَخَوَاتِهَا'],
          distractors: ['اسْمٌ مَقْصُورٌ'],
        },
        {
          title: 'تَرْكِيب: لِمَاذَا حُذِفَتِ الْيَاءُ؟',
          kind: 'tarkeeb',
          instruction: 'Identify which of the five cases explains the dropped يَاء in each word.',
          source: '﴿الْأُمِّيّٖنَ﴾ / ﴿يُحْيٖ﴾ / ﴿يُنَادِ الْمُنَادِ﴾ / ﴿الْكَبِيرُ الْمُتَعَالِ﴾',
          words: ['الْأُمِّيّٖنَ', 'يُحْيٖ', 'يُنَادِ', 'الْمُتَعَالِ'],
          labels: ['الْتِقَاءُ يَاءَيْنِ وَسَطَ الْكَلِمَةِ', 'الْتِقَاءُ يَاءَيْنِ آخِرَ الْكَلِمَةِ', 'مَجِيءُ سَاكِنٍ بَعْدَهَا', 'آخِرُ آيَةٍ'],
          distractors: ['الْإِضَافَةُ إِلَى يَاءِ الْمُتَكَلِّمِ'],
        },
        {
          title: 'تَرْكِيب: أَصْلُ الْأَلِفِ الْمُتَطَرِّفَةِ',
          kind: 'tarkeeb',
          instruction: 'Classify the origin of each final أَلِف: أَصْلُهَا يَاءٌ or أَصْلُهَا وَاوٌ.',
          source: 'سَعَى / دَعَا / الْفَتَى / الْعَصَا',
          words: ['سَعَى', 'دَعَا', 'الْفَتَى', 'الْعَصَا'],
          labels: ['أَصْلُهَا يَاءٌ', 'أَصْلُهَا وَاوٌ', 'أَصْلُهَا يَاءٌ', 'أَصْلُهَا وَاوٌ'],
          distractors: ['أَصْلُهَا هَمْزَةٌ'],
        },
        {
          title: 'تَرْكِيب: ثُلَاثِيٌّ أَمْ رُبَاعِيٌّ فَأَكْثَرُ؟',
          kind: 'tarkeeb',
          instruction: 'For each word, say which final-أَلِف rule applies: the ثُلَاثِيّ rule, where the origin decides, or the رُبَاعِيّ فَأَكْثَر rule, where it is always ى.',
          source: 'هُدًى / عَصًا / الْمُصْطَفَى / الْفَتَى',
          words: ['هُدًى', 'عَصًا', 'الْمُصْطَفَى', 'الْفَتَى'],
          labels: ['ثُلَاثِيٌّ: أَصْلُهَا يَاءٌ', 'ثُلَاثِيٌّ: أَصْلُهَا وَاوٌ', 'رُبَاعِيٌّ فَأَكْثَرُ: ى دَائِمًا', 'ثُلَاثِيٌّ: أَصْلُهَا يَاءٌ'],
          distractors: ['لَا قَاعِدَةَ تَحْكُمُهُ'],
        },
        {
          title: 'تَرْكِيب: مُرَاجَعَةٌ شَامِلَةٌ عَلَى الرَّسْمِ',
          kind: 'tarkeeb',
          instruction: 'Classify the رَسْم phenomenon each word illustrates.',
          source: 'مِائَة / ﴿كَلِمَٰتٍ﴾ / ﴿يَسْتَوٗنَ﴾ / الْمُصْطَفَى',
          words: ['مِائَة', 'كَلِمَٰتٍ', 'يَسْتَوٗنَ', 'الْمُصْطَفَى'],
          labels: ['أَلِفٌ تُكْتَبُ وَلَا تُلْفَظُ', 'أَلِفٌ تُلْفَظُ وَلَا تُكْتَبُ', 'وَاوٌ تُلْفَظُ وَلَا تُكْتَبُ', 'أَلِفٌ مُتَطَرِّفَةٌ تُكْتَبُ ى دَائِمًا'],
          distractors: ['يَاءٌ تُلْفَظُ وَلَا تُكْتَبُ'],
        },
      ],
    },

    // ---------------------------------------------------------------- L2
    {
      id: 'l2',
      title: 'الْوَصْلُ',
      subtitle: 'Connected Speech — همزة الوصل and how to resolve two sākins meeting',
      concepts: [
        {
          heading: 'الْوَصْلُ: تَعْرِيفُهُ وَمَجَالَا دِرَاسَتِهِ',
          tldr: 'الْوَصْل is carrying the sound on past the end of a word instead of cutting it off, and its chapter covers only هَمْزَةُ الْوَصْلِ and الْتِقَاءُ السَّاكِنَيْنِ.',
          body: `<bdi>الْوَصْل</bdi> is not cutting the sound off at the end of a word, but carrying it straight on into the next. This is <bdi>الْأَصْل</bdi> in speech, not an option: <bdi>الدِّينُ النَّصِيحَةُ</bdi> is read as one connected run. Its chapter studies two things: (1) <bdi>هَمْزَةُ الْوَصْلِ</bdi> — a hamzah that survives only at a beginning, (2) <bdi>الْتِقَاءُ سَاكِنَيْنِ</bdi> — what happens when two vowelless letters collide. Both arise from the same fact. Joining words together is exactly what disturbs the vowels at their edges.`,
          examples: [
            { ar: 'الدِّينُ النَّصِيحَةُ', en: 'religion is sincere counsel', note: 'read وَصْلًا — النَّصِيحَةُ keeps the ضَمَّة of its رَفْع as خَبَر, and the تَاء is fully sounded' },
            { ar: 'الدِّينُ النَّصِيحَهْ', en: 'religion is sincere counsel (stopping at the end)', note: 'the same words at الْوَقْف — the ضَمَّة falls away and the تَاء is read as a سَاكِنَة هَاء' },
          ],
          exercise: {
            prompt: `الْوَصْل is defined as:`,
            kind: 'mcq',
            options: ['Not cutting the sound off at the end of a word, but carrying it into the next', 'Cutting the sound off at the end of a word', 'Writing a letter that is never pronounced', 'Dropping the final vowel of a word before a stop'],
            correct: 0,
          },
        },
        {
          heading: 'هَمْزَةُ الْوَصْلِ: تَعْرِيفُهَا وَمَوَاضِعُهَا',
          tldr: 'هَمْزَةُ الْوَصْلِ is sounded when you begin with its word and dropped when the word is joined to what precedes it, and it occurs in four positions.',
          body: `<bdi>هَمْزَةُ الْوَصْلِ</bdi> is a hamzah written at the head of a word which is pronounced when you begin with that word (<bdi>ابْتِدَاءً</bdi>) and dropped once the word is joined to what precedes it (<bdi>وَصْلًا</bdi>). It sits in four positions: (1) an اسْم made definite by <bdi>أَلْ</bdi>, e.g. <bdi>الرَّبُّ</bdi>, (2) a fixed list of أَسْمَاء — <bdi>اسْم، اسْت، ابْن، ابْنُم، ابْنَة، امْرُؤ، امْرَأَة</bdi> with their duals, plus <bdi>اثْنَيْنِ وَاثْنَتَيْنِ</bdi> and <bdi>ايْمُنُ اللَّهِ</bdi>, (3) the أَمْر of a three-letter verb, e.g. <bdi>اعْرِفْ رَبَّكَ وَاعْبُدْهُ</bdi>, (4) a مَاضٍ of more than four letters, along with its أَمْر and its مَصْدَر, e.g. <bdi>اسْتَغْفَرَ، اسْتَغْفِرْ، اسْتِغْفَارٌ</bdi>. The test is always the same. Say the word first in a sentence, then bury it in the middle of one, and listen for the hamzah disappearing.`,
          examples: [
            { ar: 'اقْرَإِ الْقُرْآنَ وَاعْمَلْ بِهِ', en: 'Recite the Qur’an and act by it', note: 'اقْرَإِ opens the sentence, so its هَمْزَة is sounded; the هَمْزَة of اعْمَلْ is dropped after the وَاو' },
            { ar: 'وَاسْتَغْفِرْ لِذَنْبِكَ', en: 'and seek forgiveness for your sin', note: 'a مَاضٍ over four letters gives an أَمْر with هَمْزَةُ وَصْل — after the وَاو it is read وَسْتَغْفِرْ' },
            { ar: 'هُوَ الرَّبُّ لَا رَبَّ سِوَاهُ', en: 'He is the Lord; there is no lord besides Him', note: 'the هَمْزَة of أَلْ is a هَمْزَةُ وَصْل, so after هُوَ it is not sounded — read هُوَ رْرَبُّ' },
          ],
          clarification: `One sub-rule inside position (2) is worth pulling out on its own: the أَلِف of <bdi>ابْن</bdi> is itself dropped from the writing, but only on one condition. That condition is that ابْن be a <bdi>بَدَل</bdi> standing between a person's name and the name of his actual father, as in <bdi>مُحَمَّدُ بْنُ عَبْدِ اللَّهِ ﷺ</bdi>. Where the condition fails the أَلِف stays put, as in <bdi>عَبْدِ اللَّهِ بْنِ أُبَيٍّ ابْنِ سَلُولَ</bdi>. It fails there because <bdi>سَلُول</bdi> was not his father, so that second ابْن is not a بَدَل between a name and a father's name.`,
          exercise: {
            prompt: `In مُحَمَّدُ بْنُ عَبْدِ اللَّهِ ﷺ the أَلِف of ابْن is dropped, yet عَبْدِ اللَّهِ بْنِ أُبَيٍّ ابْنِ سَلُولَ keeps it. Why?`,
            kind: 'mcq',
            options: ['In the first, ابْن is a بَدَل between a name and the name of the actual father', 'In the first, ابْن begins a new sentence', 'In the first, ابْن is مَرْفُوع rather than مَجْرُور', 'There is no rule — the spelling of ابْن is free either way'],
            correct: 0,
          },
        },
        {
          heading: 'أَثَرُ دُخُولِ أَلْ عَلَى هَمْزَةِ الْوَصْلِ',
          tldr: 'When أَلْ enters a word that itself opens with a هَمْزَةُ وَصْل, that second hamzah is dropped and the لَام of أَلْ takes a كَسْرَة.',
          body: `Two هَمْزَتَا وَصْل cannot both stand at the head of one word. So when <bdi>أَلْ</bdi> enters upon a word whose own first letter carries a هَمْزَةُ وَصْل, two things happen together: (1) the word's own هَمْزَةُ الْوَصْلِ is dropped, (2) the <bdi>لَام</bdi> of أَلْ takes a <bdi>كَسْرَة</bdi> to carry the letter that is left behind. So one says <bdi>الِاجْتِنَابُ مِنَ الْمَعَاصِي خَيْرٌ مِنَ الِاسْتِغْفَارِ لَهُ</bdi>. What one never says is <bdi>الِائْتِجْنَاب</bdi> or <bdi>الِائْسْتِغْفَار</bdi>, which would try to sound both hamzahs at once.`,
          examples: [
            { ar: 'الِاجْتِنَابُ مِنَ الْمَعَاصِي خَيْرٌ مِنَ الِاسْتِغْفَارِ لَهُ', en: 'Avoiding sins is better than seeking forgiveness for them', note: 'both مَصْدَران lose their own هَمْزَةُ وَصْل under أَلْ; الِاجْتِنَابُ is مُبْتَدَأ مَرْفُوع and الِاسْتِغْفَارِ is مَجْرُور by مِنْ' },
            { ar: 'الِانْطِلَاقُ خَيْرٌ مِنَ الِانْتِظَارِ', en: 'setting off is better than waiting', note: 'the same rule on two more مَصَادِر — the لَام of أَلْ carries a كَسْرَة, and no second hamzah is written or said' },
          ],
          exercise: {
            prompt: `أَلْ enters upon اجْتِنَاب, whose own first letter carries a هَمْزَةُ وَصْل. What happens?`,
            kind: 'mcq',
            options: ['The word’s own هَمْزَةُ الْوَصْلِ drops and the لَام of أَلْ takes a كَسْرَة', 'Both hamzahs are kept and both are pronounced', 'The لَام of أَلْ is dropped instead of the hamzah', 'The word is written and read as الِائْتِجْنَاب'],
            correct: 0,
          },
        },
        {
          heading: 'الْتِقَاءُ السَّاكِنَيْنِ: تَعْرِيفُهُ وَمَا يَقَعُ مِنْهُ عَلَى حَدِّهِ',
          tldr: 'Two سَاكِنَانِ meeting عَلَى حَدِّهِ are left exactly as they are, and that happens in two cases only: at الْوَقْف, and a حَرْف مَدّ before a مُدْغَم letter.',
          body: `<bdi>الْتِقَاءُ سَاكِنَيْنِ</bdi>, also called <bdi>اجْتِمَاعُ سَاكِنَيْنِ</bdi>, is two vowelless letters landing side by side. It splits in two: (1) <bdi>عَلَى حَدِّهِ</bdi> — within the limit the language allows, so nothing at all is done about it, (2) <bdi>عَلَى غَيْرِ حَدِّهِ</bdi> — past that limit, so it must be resolved. عَلَى حَدِّهِ has two cases only: (1) at <bdi>الْوَقْف</bdi>, e.g. stopping on ﴿الرَّحْمَٰنِ الرَّحِيمْ﴾, (2) a <bdi>حَرْف مَدّ</bdi> followed by a <bdi>مُدْغَم</bdi> letter, e.g. ﴿الضَّالِّينَ﴾. Both are tolerated for the same reason. The first سَاكِن in each is a long stretched sound, audible enough on its own that the two do not crush together.`,
          examples: [
            { ar: '﴿بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمْ﴾', en: 'In the name of Allah, the Most Merciful, the Bestower of Mercy', note: 'stopping turns الرَّحِيمِ into الرَّحِيمْ, so the سَاكِنَة يَاء and the سَاكِنَة مِيم meet — عَلَى حَدِّهِ, and nothing is repaired' },
            { ar: '﴿وَلَا الضَّالِّينَ﴾', en: 'nor of those who go astray', note: 'the أَلِف is a حَرْف مَدّ and the لَام after it is مُدْغَمَة — two سَاكِنَانِ عَلَى حَدِّهِ, left standing' },
          ],
          exercise: {
            prompt: `Two سَاكِنَانِ meeting عَلَى حَدِّهِ are left as they are. In which two cases does that happen?`,
            kind: 'mcq',
            options: ['At الْوَقْف, and when a حَرْف مَدّ is followed by a مُدْغَم letter', 'At الِابْتِدَاء, and before every هَمْزَةُ وَصْل', 'In every فِعْل مَاضٍ, and every فِعْل مُضَارِع', 'Only in the Qur’an, never in ordinary speech'],
            correct: 0,
          },
        },
        {
          heading: 'الْتِقَاءُ السَّاكِنَيْنِ عَلَى غَيْرِ حَدِّهِ: الْحَذْفُ وَالْحَرَكَاتُ الثَّلَاثُ',
          tldr: 'Outside the limit the clash must be repaired: the first سَاكِن is deleted when it is a حَرْف مَدّ, and otherwise takes a ضَمَّة, a فَتْحَة, or the default كَسْرَة.',
          body: `When two سَاكِنَانِ meet outside the proper limit the clash has to be resolved, and the repair depends on what the first سَاكِن is: (1) it is deleted if it is a <bdi>حَرْف مَدّ</bdi>, so <bdi>النَّجَاةُ فِي الصِّدْقِ</bdi> is read <bdi>النَّجَاةُ فِ الصِّدْقِ</bdi>, (2) it takes a <bdi>ضَمَّة</bdi> if it is the <bdi>مِيمُ الْجَمْعِ</bdi> or the <bdi>وَاوُ الْجَمَاعَةِ</bdi>, as in <bdi>هُمُ النَّاصِحُونَ</bdi> and <bdi>دَعَوُا اللَّهَ</bdi>, (3) it takes a <bdi>فَتْحَة</bdi> if it is the نُون of <bdi>مِنْ</bdi>, as in <bdi>الْإِخْلَاصُ مِنَ النَّصِيحَةِ</bdi>, (4) it takes a <bdi>كَسْرَة</bdi> in everything that is left over. That last, default كَسْرَة covers three kinds of letter: (1) a <bdi>حَرْف صَحِيح</bdi>, as in <bdi>نَصَحَتِ الْأُمُّ</bdi>, (2) the نُون of <bdi>تَنْوِين</bdi>, as in <bdi>خَدِيجَةُ نَاصِحَةٌنِ الصِّدِّيقَاتِ</bdi>, (3) a <bdi>حَرْف لِين</bdi>, as in <bdi>صُمْ يَوْمَيِ التَّاسُوعَاءِ</bdi>. So كَسْرَة is the rule, and deletion, ضَمَّة and فَتْحَة are the three named exceptions to it.`,
          examples: [
            { ar: 'النَّجَاةُ فِ الصِّدْقِ', en: 'salvation lies in truthfulness (as pronounced)', note: 'written فِي, but its يَاء is a حَرْف مَدّ meeting the سَاكِن لَام of الصِّدْقِ, so it is deleted in the reading' },
            { ar: 'دَعَوُا اللَّهَ', en: 'they called upon Allah', note: 'دَعَوْا ends in وَاوُ الْجَمَاعَةِ, so before the سَاكِن لَام it takes a ضَمَّة instead of being deleted' },
            { ar: 'نَصَحَتِ الْأُمُّ وَلَدَهَا', en: 'the mother advised her child', note: 'the تَاء of نَصَحَتْ is a حَرْف صَحِيح, so it takes the default كَسْرَة; الْأُمُّ stays فَاعِل مَرْفُوع' },
          ],
          clarification: `The تَنْوِين example is written in an unusual way on purpose. <bdi>خَدِيجَةُ نَاصِحَةٌنِ الصِّدِّيقَاتِ</bdi> spells out the نُون that تَنْوِين actually is, so that you can see the سَاكِن doing the colliding. Normally you would only write <bdi>نَاصِحَةٌ</bdi> and hear the نُون. Here the نُون of the تَنْوِين meets the سَاكِن لَام of <bdi>الصِّدِّيقَاتِ</bdi>, and being neither a حَرْف مَدّ, nor مِيمُ الْجَمْعِ, nor the نُون of مِنْ, it falls to the default and takes a كَسْرَة.`,
          exercise: {
            prompt: `دَعَوُا اللَّهَ carries a ضَمَّة on the وَاو. Why that vowel?`,
            kind: 'mcq',
            options: ['The first of the two سَاكِنَانِ is وَاوُ الْجَمَاعَةِ, which takes a ضَمَّة', 'It is the نُون of مِنْ, which takes a فَتْحَة', 'It is a حَرْف مَدّ, and a حَرْف مَدّ is deleted', 'It is a حَرْف صَحِيح, which takes the default كَسْرَة'],
            correct: 0,
          },
        },
      ],
      quiz: [
        {
          q: 'What is الْوَصْل؟',
          options: ['Not cutting the sound off at the end of a word — the default in speech', 'Cutting the sound off at the end of a word', 'A hamzah pronounced only when beginning speech', 'The meeting of two سَاكِنَانِ'],
          correct: 0,
        },
        {
          q: 'هَمْزَةُ الْوَصْلِ is dropped:',
          options: ['وَصْلًا, though it is pronounced when you begin with the word', 'Always, in every context whatsoever', 'Only in the Qur’an', 'Only when it follows أَلْ التَّعْرِيفِ'],
          correct: 0,
        },
        {
          q: 'In how many positions does هَمْزَةُ الْوَصْلِ occur?',
          options: ['Two', 'Three', 'Four', 'Five'],
          correct: 2,
        },
        {
          q: 'When أَلْ enters a word whose own first letter carries a هَمْزَةُ وَصْل, what becomes of that hamzah?',
          options: ['It is dropped, and the لَام of أَلْ takes a كَسْرَة', 'It is kept and pronounced in full', 'It turns into a هَمْزَةُ قَطْع', 'Nothing changes at all'],
          correct: 0,
        },
        {
          q: 'الْتِقَاءُ سَاكِنَيْنِ عَلَى حَدِّهِ is left alone in which two cases?',
          options: ['At الْوَقْف, and a حَرْف مَدّ before a مُدْغَم letter', 'Before every هَمْزَةُ وَصْل, and after every تَنْوِين', 'Only in poetry, never in the Qur’an', 'At الِابْتِدَاء, and before نُونُ الْوِقَايَةِ'],
          correct: 0,
        },
        {
          q: 'Two سَاكِنَانِ meet outside their proper limit and the first is a حَرْف مَدّ. What happens to it?',
          options: ['It is deleted from the pronunciation', 'It takes a ضَمَّة', 'It takes a فَتْحَة', 'It is written but not pronounced, like a هَمْزَةُ وَصْل'],
          correct: 0,
        },
      ],
      bank: [
        {
          title: 'الأصل في الكلام',
          kind: 'mcq',
          prompt: 'What is the default (الأصل) way of reading connected speech?',
          options: ['وصلاً — continuing the sound into the next word', 'وقفًا — cutting the sound off after every word', 'بالتنوين دائمًا', 'بهمزة القطع دائمًا'],
          correct: 0,
        },
        {
          title: 'اِقْرَأِ الْقُرْآنَ',
          kind: 'mcq',
          prompt: 'The همزة at the start of اِقْرَأِ is a همزة وصل. What happens to it when this phrase is read after another word (وصلًا)?',
          options: ['It is dropped from pronunciation', 'It is pronounced with a فتحة', 'It turns into همزة قطع', 'It is written but never pronounced, even at the start'],
          correct: 0,
        },
        {
          title: 'الرَّبُّ',
          kind: 'mcq',
          prompt: 'Which موضع of همزة الوصل does الرَّبُّ illustrate?',
          options: ['الاسم المعرف بأل', 'اسم من الأسماء الستة المسموعة (اسم، ابن...)', 'أمر الثلاثي', 'ماضي فوق أربعة أحرف'],
          correct: 0,
        },
        {
          title: 'اعْرِفْ رَبَّكَ',
          kind: 'mcq',
          prompt: 'اعْرِفْ opens with a همزة وصل. Which موضع does it illustrate?',
          options: ['أمر الفعل الثلاثي', 'الاسم المعرف بأل', 'ماضي فوق أربعة أحرف ومصدره', 'الأسماء الستة المسموعة'],
          correct: 0,
        },
        {
          title: 'اسْتَغْفَرَ، اسْتَغْفِرْ، اسْتِغْفارٌ',
          kind: 'mcq',
          prompt: 'These three words all open with همزة وصل. What do they have in common?',
          options: ['A ماضي of more than four letters, its أمر, and its مصدر', 'All three are أسماء معرفة بأل', 'All three are من الأسماء الستة المسموعة', 'All three are أفعال ثلاثية'],
          correct: 0,
        },
        {
          title: 'ابن بين علمين',
          kind: 'mcq',
          prompt: 'مُحَمَّدُ بْنُ عَبْدِ اللهِ drops the alif of ابن. What condition allows that?',
          options: ['ابن is a بدل sitting between a name and the name of the actual father', 'ابن is مرفوع here', 'ابن begins the sentence', 'ابن is مثنى here'],
          correct: 0,
        },
        {
          title: 'ابن ليس بدلاً',
          kind: 'mcq',
          prompt: 'عَبْدِ اللهِ بْنِ أُبَيٍّ ابْنِ سَلُولَ keeps the alif of the second ابن. Why?',
          options: ['Salūl was not the actual father, so ابن here is not a بدل between the two names', 'It is مرفوع, unlike the first ابن', 'It follows a اسم معرف بأل', 'There is no rule — spelling of ابن is arbitrary'],
          correct: 0,
        },
        {
          title: 'الِاجْتِنابُ',
          kind: 'mcq',
          prompt: 'Why is الِاجْتِنابُ correct, rather than الِائْتِجناب?',
          options: ['The word’s own همزة الوصل drops once أل enters, and the لام of أل takes a كسرة', 'اجتناب has no همزة وصل to begin with', 'أل never combines with a همزة وصل at all', 'Both spellings are accepted interchangeably'],
          correct: 0,
        },
        {
          title: 'اجتماع ساكنين',
          kind: 'mcq',
          prompt: 'التقاء ساكنين is also known by which other name?',
          options: ['اجتماع ساكنين', 'همزة الوصل', 'الرسم العثماني', 'لام الجواب'],
          correct: 0,
        },
        {
          title: '﴿الرَّحِيمْ﴾ at a stop',
          kind: 'mcq',
          prompt: 'Stopping on ﴿…الرَّحِيمْ﴾ leaves two sākins in a row. Why is this tolerated rather than resolved?',
          options: ['Because it occurs at الوقف, one of the two cases عَلَى حَدِّهِ', 'Because a حرف مد always resolves itself', 'Because الوقف never produces سواكن', 'Because the reciter must add a vowel here'],
          correct: 0,
        },
        {
          title: '﴿الضَّالِّينَ﴾',
          kind: 'mcq',
          prompt: 'A حرف مد is followed by a مُدْغَم (assimilated) letter in ﴿الضَّالِّينَ﴾. Is this التقاء ساكنين resolved or tolerated?',
          options: ['Tolerated — على حَدِّه', 'Resolved by deleting the حرف مد', 'Resolved by adding a كسرة', 'Resolved by adding a فتحة'],
          correct: 0,
        },
        {
          title: 'النَّجاةُ فِ الصِّدْقِ',
          kind: 'mcq',
          prompt: 'Why is the wāw of فِي dropped in pronunciation before الصِّدْقِ?',
          options: ['It is a حرف مد meeting a following sākin outside its proper limit, so it is deleted', 'It is the ميم الجمع', 'It is the nūn of مِنْ', 'It is a soft (لين) letter'],
          correct: 0,
        },
        {
          title: 'هُمُ النّاصِحونَ',
          kind: 'mcq',
          prompt: 'Why does the ميم of هُمْ take a dammah before النّاصِحونَ?',
          options: ['It is the ميم الجمع, the first of two meeting sākins', 'It is the nūن of مِنْ', 'It is a حرف مد', 'It is a soft (لين) letter'],
          correct: 0,
        },
        {
          title: 'مِنَ النَّصيحَةِ',
          kind: 'mcq',
          prompt: 'مِنْ takes a fathah on its nūn before النَّصيحَةِ. Why a fathah rather than a kasrah?',
          options: ['Because it is specifically the nūn of مِنْ', 'Because it is a sound (صحيح) letter', 'Because it is the nūn of tanwīn', 'Because it is a soft (لين) letter'],
          correct: 0,
        },
        {
          title: 'نَصَحَتِ الأُمُّ',
          kind: 'mcq',
          prompt: 'The تاء of نَصَحَتْ takes a kasrah before الأُمُّ. Why?',
          options: ['It is a sound (صحيح) letter, one of the three kasrah cases', 'It is the ميم الجمع', 'It is the nūn of مِنْ', 'It is a حرف مد'],
          correct: 0,
        },
        {
          title: 'خَديجَةُ ناصِحَةٌنِ الصَّدِّيقاتِ',
          kind: 'mcq',
          prompt: 'The kasrah appearing here belongs to which of the three كسرة cases?',
          options: ['نون التنوين', 'ميم الجمع', 'نون مِنْ', 'حرف لين'],
          correct: 0,
        },
        {
          title: 'يَوْمَيِ التّاسوعاءِ',
          kind: 'mcq',
          prompt: 'The dual’s soft yāʾ takes a kasrah before التّاسوعاءِ. Which of the three كسرة cases is this?',
          options: ['A soft (لين) letter', 'A sound (صحيح) letter', 'نون التنوين', 'ميم الجمع'],
          correct: 0,
        },
        {
          title: 'دَعَوُا اللهَ',
          kind: 'mcq',
          prompt: 'The wāw of دَعَوْا (originally) takes a dammah before اللهَ. Which case is this?',
          options: ['The plural verb’s soft wāw, one of the two dammah cases', 'The nūn of مِنْ', 'A sound letter, one of the three kasrah cases', 'A حرف مد, deleted outright'],
          correct: 0,
        },
        {
          title: 'تركيب: مواضع همزة الوصل',
          kind: 'tarkeeb',
          instruction: 'Match each word to the موضع of همزة الوصل it illustrates.',
          source: 'الرَّبُّ / اعْرِفْ / اسْتَغْفَرَ / اسْمٌ',
          words: ['الرَّبُّ', 'اعْرِفْ', 'اسْتَغْفَرَ', 'اسْمٌ'],
          labels: ['الاسم المعرف بأل', 'أمر الثلاثي', 'ماضي فوق أربعة أحرف', 'من الأسماء الستة المسموعة'],
          distractors: ['همزة قطع'],
        },
        {
          title: 'تركيب: التقاء الساكنين — على حَدِّه أم على غير حَدِّه?',
          kind: 'tarkeeb',
          instruction: 'Classify each case as على حَدِّه or على غير حَدِّه.',
          source: '﴿الرَّحِيمْ﴾ (وقف) / ﴿الضَّالِّينَ﴾ / النَّجاةُ فِ الصِّدْقِ / هُمُ النّاصِحونَ',
          words: ['الرَّحِيمْ', 'الضَّالِّينَ', 'النَّجاةُ فِ الصِّدْقِ', 'هُمُ النّاصِحونَ'],
          labels: ['على حَدِّه', 'على حَدِّه', 'على غير حَدِّه', 'على غير حَدِّه'],
          distractors: ['لا التقاء هنا'],
        },
        {
          title: 'تركيب: حركة الساكن الأول',
          kind: 'tarkeeb',
          instruction: 'Which vowel does the first of the two meeting sākins take — or is it deleted?',
          source: 'هُمُ النّاصِحونَ / مِنَ النَّصيحَةِ / نَصَحَتِ الأُمُّ / النَّجاةُ فِ الصِّدْقِ',
          words: ['هُمُ النّاصِحونَ', 'مِنَ النَّصيحَةِ', 'نَصَحَتِ الأُمُّ', 'النَّجاةُ فِ الصِّدْقِ'],
          labels: ['ضمة (ميم الجمع)', 'فتحة (نون مِنْ)', 'كسرة (حرف صحيح)', 'حذف (حرف مد)'],
          distractors: ['فتحة (حرف مد)'],
        },
        {
          title: 'تركيب: مواضع أخرى لهمزة الوصل',
          kind: 'tarkeeb',
          instruction: 'Identify the موضع of همزة الوصل in each word.',
          source: 'امْرَأَة / اثْنَيْنِ / اسْتِغْفَارٌ / اعْبُدْهُ',
          words: ['امْرَأَة', 'اثْنَيْنِ', 'اسْتِغْفَارٌ', 'اعْبُدْهُ'],
          labels: ['من الأسماء الستة المسموعة', 'من الأسماء الستة المسموعة (المثنى)', 'مصدر الماضي فوق أربعة أحرف', 'أمر الثلاثي'],
          distractors: ['همزة قطع'],
        },
        {
          title: 'تركيب: مراجعة الوصل',
          kind: 'tarkeeb',
          instruction: 'Classify the وصل phenomenon in each item.',
          source: 'اِقْرَأِ الْقُرْآنَ / الِاجْتِنابُ / ﴿الضَّالِّينَ﴾ / دَعَوُا اللهَ',
          words: ['اِقْرَأِ', 'الِاجْتِنابُ', 'الضَّالِّينَ', 'دَعَوُا'],
          labels: ['همزة وصل تُحذف وصلًا', 'أل تُسقط همزة الوصل التي تليها', 'التقاء ساكنين على حَدِّه', 'واو الجماعة تأخذ ضمة عند التقاء ساكنين'],
          distractors: ['همزة قطع لا تُحذف أبدًا'],
        },
        {
          title: 'تركيب: حركات الساكن الأول — مراجعة شاملة',
          kind: 'tarkeeb',
          instruction: 'Which vowel (or deletion) does the first sākin take in each?',
          source: 'مِنَ النَّصيحَةِ / خَديجَةُ ناصِحَةٌنِ / يَوْمَيِ التّاسوعاءِ / هُمُ النّاصِحونَ',
          words: ['مِنَ', 'خَديجَةُ ناصِحَةٌنِ', 'يَوْمَيِ', 'هُمُ'],
          labels: ['فتحة (نون مِنْ)', 'كسرة (نون التنوين)', 'كسرة (حرف لين)', 'ضمة (ميم الجمع)'],
          distractors: ['حذف (حرف مد)'],
        },
      ],
    },

    // ---------------------------------------------------------------- L3
    {
      id: 'l3',
      title: 'الوقف',
      subtitle: 'Stopping — how to correctly stop on a word ending in a سكون, تاء مربوطة, منقوص, or تنوين',
      concepts: [
        {
          heading: 'تعريف الوقف، والوقف على الساكن والمتحرك',
          body: `<bdi>الْوَقْف</bdi> is <bdi>قَطْعُ الصَّوْتِ عِنْدَ آخِرِ الْكَلِمَةِ</bdi> — cutting off the sound at the end of a word. A word already ending in a sākin is stopped on with <bdi>سُكُون</bdi>, e.g. <bdi>رَحْمَةَ اللهِ نَرْجو، وَلَمْ نَيْأَسْ</bdi>. A word ending in a vowelled letter is stopped on by deleting its vowel, e.g. <bdi>أَنْزَلَ اللهُ القُرْآنْ، وَآمَنّا بِهْ</bdi>.`,
          sample: `تعريف الوقف — قطع الصوت عند آخر الكلمة<br>الوقف على الساكن — رَحْمَةَ اللهِ نَرْجو، وَلَمْ نَيْأَسْ<br>الوقف على المتحرك — أَنْزَلَ اللهُ القُرْآنْ`,
          exercise: {
            prompt: `How does one stop on a word already ending in a sākin?`,
            kind: 'mcq',
            options: ['With سكون — no change is needed', 'By deleting the final vowel', 'By restoring a dropped letter', 'By adding an alif'],
            correct: 0,
          },
        },
        {
          heading: 'الوقف على تاء التأنيث المربوطة والاسم المقصور',
          body: `<bdi>تَاءُ التَّأْنِيثِ المَرْبُوطَة</bdi> is stopped on with a sākin <bdi>هَاء</bdi>, e.g. <bdi>اسْتُشْهِدَ حَمْزَةْ ڤ</bdi>. The <bdi>اِسْمُ مَقْصُور</bdi> is stopped on by retaining its alif, e.g. <bdi>الهُدَى</bdi>.`,
          sample: `تاء التأنيث المربوطة — اسْتُشْهِدَ حَمْزَةْ (تاء ← هاء ساكنة)<br>الاسم المقصور — الهُدَى (تثبت الألف)`,
          exercise: {
            prompt: `How is تاء التأنيث المربوطة handled at الوقف?`,
            kind: 'mcq',
            options: ['It turns into a sākin هاء', 'It is deleted entirely', 'It keeps its own vowel', 'It turns into a تاء مفتوحة'],
            correct: 0,
          },
        },
        {
          heading: 'الوقف على الاسم المنقوص المنوَّن، وعلى التنوين عمومًا',
          body: `The <bdi>اِسْمٌ مَنْقُوصٌ مُنَوَّن</bdi> is stopped on either with سكون, e.g. <bdi>جاءَنا هادْ</bdi>, or by restoring its yāʾ, e.g. <bdi>جاءَنا هادي</bdi> — and the yāʾ of a منقوص may likewise be dropped in the Qur’an, as in ﴿الْكَبِيرُ الْمُتَعَالْ﴾. Beyond the منقوص, stopping on <bdi>تَنْوِين</bdi> generally follows the vowel it carries: if the tanwīn is a <bdi>دَمَّة</bdi> or <bdi>كَسْرَة</bdi>, it is simply deleted, e.g. <bdi>صَدَقَ مُحَمَّدْ ﷺ</bdi>; if it is a <bdi>فَتْحَة</bdi>, the stop is made with an alif instead, e.g. <bdi>وَكَذَّبَ الفاسِقونَ مُحَمَّدا ﷺ</bdi>.`,
          sample: `الاسم المنقوص المنون — جاءَنا هادْ / جاءَنا هادي<br>تنوين ضم أو كسر — صَدَقَ مُحَمَّدْ (يُحذف)<br>تنوين فتح — مُحَمَّدا (تصير ألفًا)`,
          exercise: {
            prompt: `Stopping on a word carrying تنوين الفتح, one adds:`,
            kind: 'mcq',
            options: ['An alif', 'A sākin هاء', 'Nothing — the tanwīn is simply deleted', 'A restored yāʾ'],
            correct: 0,
          },
        },
        {
          heading: 'الوقف على نون التوكيد الخفيفة وعلى إِذَنْ',
          body: `The <bdi>نُونُ التَّوْكِيدِ الخَفِيفَة</bdi> is stopped on with an alif, e.g. ﴿لَنَسْفَعًا﴾. <bdi>إِذَنْ</bdi> is stopped on by turning its nūn into an alif, <bdi>إِذًا</bdi>, e.g. <bdi>فَيُقْبَلُ مِنْكُمْ إِذًا</bdi>.`,
          sample: `نون التوكيد الخفيفة — ﴿لَنَسْفَعًا﴾ (نون ← ألف)<br>إذَنْ — إِذًا (نون ← ألف)`,
          exercise: {
            prompt: `How is إِذَنْ stopped on?`,
            kind: 'mcq',
            options: ['Its nūn turns into an alif: إِذًا', 'Its nūn is simply deleted', 'It keeps its nūn with سكون', 'It turns into إِذِي'],
            correct: 0,
          },
        },
        {
          heading: 'تطبيق: أمثلة على الوقف',
          body: `Putting the rules together: <bdi>السّاعَة</bdi> (ending in تاء مربوطة) is stopped on as <bdi>السّاعَهْ</bdi> — the تاء becomes a sākin هاء. <bdi>هادٍ</bdi> (اسم منقوص منوَّن) is stopped on as <bdi>هادْ</bdi> or <bdi>هادي</bdi>. <bdi>مُحَمَّدًا</bdi> (تنوين فتح) is stopped on as <bdi>مُحَمَّدا</bdi> — the tanwīn becomes an alif.`,
          sample: `السّاعَة ← السّاعَهْ<br>هادٍ ← هادْ أو هادي<br>مُحَمَّدًا ← مُحَمَّدا`,
          exercise: {
            prompt: `Stopping on هَادٍ (اسم منقوص منوَّن), which two outcomes are both correct?`,
            kind: 'mcq',
            options: ['هادْ (سكون), or هادي (restoring the yāʾ)', 'هادا only, never هادْ', 'هادٍ stays exactly as it is', 'هادهْ, turning the tanwīn into a هاء'],
            correct: 0,
          },
        },
      ],
      quiz: [
        {
          q: 'الوقف is defined as:',
          options: ['قطع الصوت عند آخر الكلمة', 'عدم قطع الصوت عند آخر الكلمة', 'همزة تُحذف في درج الكلام', 'التقاء ساكنين على حَدِّه'],
          correct: 0,
        },
        {
          q: 'How does one stop on a word ending in a vowelled (متحرك) letter?',
          options: ['By deleting its vowel', 'By adding a سكون فقط بلا حذف', 'By restoring a dropped letter', 'By turning the vowel into تنوين'],
          correct: 0,
        },
        {
          q: 'تاء التأنيث المربوطة at الوقف becomes:',
          options: ['A sākin هاء', 'A sākin تاء', 'An alif', 'Nothing — it is deleted'],
          correct: 0,
        },
        {
          q: 'الاسم المنقوص at الوقف keeps or restores which letter?',
          options: ['Its yāʾ (or drops it, as sometimes happens in the Qur’an)', 'Its wāw', 'Its alif', 'Its hamzah'],
          correct: 0,
        },
        {
          q: 'Stopping on تنوين الفتح, e.g. مُحَمَّدًا, one adds:',
          options: ['An alif', 'A sākin هاء', 'Nothing at all', 'A restored yāʾ'],
          correct: 0,
        },
        {
          q: 'نون التوكيد الخفيفة at الوقف turns into:',
          options: ['An alif', 'A sākin نون', 'A هاء', 'It is deleted entirely'],
          correct: 0,
        },
      ],
      bank: [
        {
          title: 'رَحْمَةَ اللهِ نَرْجو',
          kind: 'mcq',
          prompt: 'نَرْجو already ends in a sākin واو. How is it stopped on?',
          options: ['With سكون, unchanged', 'By deleting the واو', 'By adding an alif', 'By restoring a hidden یاء'],
          correct: 0,
        },
        {
          title: 'أَنْزَلَ اللهُ القُرْآنْ',
          kind: 'mcq',
          prompt: 'القُرْآنَ (originally vowelled) is stopped on as القُرْآنْ. What happened?',
          options: ['Its final vowel was deleted', 'A سكون letter was added', 'Its تنوين became an alif', 'Its final letter was replaced'],
          correct: 0,
        },
        {
          title: 'اسْتُشْهِدَ حَمْزَةْ',
          kind: 'mcq',
          prompt: 'حَمْزَة ends in تاء التأنيث المربوطة. What does it become at الوقف?',
          options: ['A sākin هاء: حَمْزَةْ', 'A sākin تاء', 'An alif', 'It is dropped entirely'],
          correct: 0,
        },
        {
          title: 'الهُدَى at a stop',
          kind: 'mcq',
          prompt: 'الهُدَى (اسم مقصور) is stopped on by:',
          options: ['Retaining its alif, unchanged', 'Deleting its alif', 'Turning its alif into a yāʾ', 'Adding a سكون هاء'],
          correct: 0,
        },
        {
          title: 'جاءَنا هادْ',
          kind: 'mcq',
          prompt: 'هادٍ (منقوص منوَّن) is stopped on here with سكون, giving هادْ. What is the other valid way to stop on it?',
          options: ['Restoring the yāʾ: هادي', 'Adding an alif: هادا', 'Turning the dāl into a هاء', 'Keeping the تنوين as-is'],
          correct: 0,
        },
        {
          title: '﴿الْكَبِيرُ الْمُتَعَالْ﴾',
          kind: 'mcq',
          prompt: 'المُتَعَالِ drops its yāʾ here at the end of a verse. What kind of noun is المتعالي?',
          options: ['اسم منقوص', 'اسم مقصور', 'اسم ممدود', 'مصدر ميمي'],
          correct: 0,
        },
        {
          title: 'صَدَقَ مُحَمَّدْ ﷺ',
          kind: 'mcq',
          prompt: 'مُحَمَّدٌ carries تنوين ضم. How is it stopped on?',
          options: ['The tanwīn (and its vowel) is simply deleted', 'The tanwīn becomes an alif', 'The tanwīn becomes a سكون هاء', 'The tanwīn is kept in full'],
          correct: 0,
        },
        {
          title: 'آمَنَ المُؤْمِنونَ بِمُحَمَّدْ ﷺ',
          kind: 'mcq',
          prompt: 'مُحَمَّدٍ here carries تنوين كسر. Stopping on it, the tanwīn is:',
          options: ['Deleted, exactly as with تنوين ضم', 'Turned into an alif', 'Turned into a sākin هاء', 'Kept in full'],
          correct: 0,
        },
        {
          title: 'وَكَذَّبَ الفاسِقونَ مُحَمَّدا ﷺ',
          kind: 'mcq',
          prompt: 'مُحَمَّدًا carries تنوين فتح. Why is the stop مُحَمَّدا rather than مُحَمَّدْ?',
          options: ['تنوين الفتح alone is replaced by an alif at الوقف, unlike ضم and كسر', 'فتحة tanwīn is never dropped at all', 'فتحة tanwīn always keeps its ن sound', 'This word is مبني, not معرب'],
          correct: 0,
        },
        {
          title: '﴿لَنَسْفَعًا﴾',
          kind: 'mcq',
          prompt: 'This ends in نون التوكيد الخفيفة. At الوقف, that نون:',
          options: ['Becomes an alif', 'Is deleted outright', 'Becomes a سكون نون', 'Becomes a هاء'],
          correct: 0,
        },
        {
          title: 'إِذًا',
          kind: 'mcq',
          prompt: 'إِذَنْ becomes إِذًا at الوقف. What happened to its نون?',
          options: ['It turned into an alif', 'It was deleted entirely', 'It kept its سكون unchanged', 'It turned into a هاء'],
          correct: 0,
        },
        {
          title: 'وَآمَنّا بِهْ',
          kind: 'mcq',
          prompt: 'بِهِ (originally vowelled) is stopped on as بِهْ. Which rule applies?',
          options: ['Stopping on a متحرك letter by deleting its vowel', 'Stopping on تاء التأنيث المربوطة', 'Stopping on تنوين الفتح', 'Stopping on نون التوكيد الخفيفة'],
          correct: 0,
        },
        {
          title: 'وَلَمْ نَيْأَسْ',
          kind: 'mcq',
          prompt: 'نَيْأَسْ already ends in a sākin. At الوقف, this word:',
          options: ['Needs no change at all', 'Must add an alif regardless', 'Must restore a dropped letter', 'Must turn its final letter into a هاء'],
          correct: 0,
        },
        {
          title: 'Two options for هادٍ',
          kind: 'mcq',
          prompt: 'Both هادْ and هادي are accepted stops on هادٍ. What do these two options represent?',
          options: ['سكون on the منقوص, or restoring its yāʾ', 'Two entirely different words', 'ضم then فتح tanwīn', 'A wrong option and a right one'],
          correct: 0,
        },
        {
          title: 'السّاعَهْ',
          kind: 'mcq',
          prompt: 'السّاعَة is stopped on as السّاعَهْ. Which letter changed, and into what?',
          options: ['The تاء المربوطة became a sākin هاء', 'The عين became a hamzah', 'The سين became a صاد', 'The لام of أل was dropped'],
          correct: 0,
        },
        {
          title: 'درجة التنوين عند الوقف',
          kind: 'mcq',
          prompt: 'Which vowel of تنوين is the ONLY one replaced by an alif rather than simply deleted, at الوقف?',
          options: ['فتحة (تنوين النصب)', 'ضمة (تنوين الرفع)', 'كسرة (تنوين الجر)', 'كلها تُحذف بلا استثناء'],
          correct: 0,
        },
        {
          title: 'قطع الصوت',
          kind: 'mcq',
          prompt: 'الوقف, defined as قطع الصوت عند آخر الكلمة, is the opposite of:',
          options: ['الوصل', 'الرسم', 'التنوين', 'الإعراب'],
          correct: 0,
        },
        {
          title: 'مقارنة: الوقف على الساكن',
          kind: 'mcq',
          prompt: 'Comparing نَرْجو (already sākin) and القُرْآنَ (vowelled): which one needs a change at الوقف?',
          options: ['القُرْآنَ alone — its vowel is deleted', 'نَرْجو alone — a letter is added', 'Both need the same treatment', 'Neither needs any change'],
          correct: 0,
        },
        {
          title: 'تركيب: كيف نقف على كل كلمة?',
          kind: 'tarkeeb',
          instruction: 'Match each word to how it is stopped on.',
          source: 'نَرْجو / القُرْآنَ / حَمْزَة / الهُدَى',
          words: ['نَرْجو', 'القُرْآنَ', 'حَمْزَة', 'الهُدَى'],
          labels: ['سكون (بلا تغيير)', 'حذف الحركة', 'هاء ساكنة بدل التاء', 'إثبات الألف'],
          distractors: ['إبدالها ألفًا'],
        },
        {
          title: 'تركيب: التنوين عند الوقف',
          kind: 'tarkeeb',
          instruction: 'For each tanwīn, say what happens to it at الوقف: يُحذف or يصير ألفًا.',
          source: 'مُحَمَّدٌ (ضم) / مُحَمَّدٍ (كسر) / مُحَمَّدًا (فتح) / هادٍ (كسر، منقوص)',
          words: ['مُحَمَّدٌ', 'مُحَمَّدٍ', 'مُحَمَّدًا', 'هادٍ'],
          labels: ['يُحذف', 'يُحذف', 'يصير ألفًا', 'يُحذف أو تُثبت الياء'],
          distractors: ['يصير هاءً'],
        },
        {
          title: 'تركيب: مواضع خاصة عند الوقف',
          kind: 'tarkeeb',
          instruction: 'Match each item to its special stop.',
          source: 'إِذَنْ / ﴿لَنَسْفَعًا﴾ / هادٍ / حَمْزَة',
          words: ['إِذَنْ', 'لَنَسْفَعًا', 'هادٍ', 'حَمْزَة'],
          labels: ['النون تصير ألفًا: إذًا', 'نون التوكيد الخفيفة تصير ألفًا', 'الياء تُحذف أو تثبت', 'التاء المربوطة تصير هاءً ساكنة'],
          distractors: ['تُحذف بلا بدل'],
        },
        {
          title: 'تركيب: تصنيف نوع الكلمة عند الوقف',
          kind: 'tarkeeb',
          instruction: 'Classify each word by the الوقف rule that governs it.',
          source: 'السّاعَة / الهُدَى / هادٍ / مُحَمَّدا',
          words: ['السّاعَة', 'الهُدَى', 'هادٍ', 'مُحَمَّدا'],
          labels: ['تاء التأنيث المربوطة', 'اسم مقصور', 'اسم منقوص منون', 'تنوين فتح'],
          distractors: ['نون التوكيد'],
        },
        {
          title: 'تركيب: ساكن أصلاً أم يحتاج تغييرًا?',
          kind: 'tarkeeb',
          instruction: 'For each word, say whether it needs a change at الوقف or already ends correctly.',
          source: 'نَرْجو / نَيْأَسْ / أَنْزَلَ اللهُ القُرْآنَ / آمَنّا بِهِ',
          words: ['نَرْجو', 'نَيْأَسْ', 'القُرْآنَ', 'بِهِ'],
          labels: ['لا تغيير', 'لا تغيير', 'حذف الحركة', 'حذف الحركة'],
          distractors: ['إثبات الألف'],
        },
        {
          title: 'تركيب: مراجعة شاملة على الوقف',
          kind: 'tarkeeb',
          instruction: 'Give the correct stop-form for each word.',
          source: 'مُحَمَّدٌ / مُحَمَّدًا / حَمْزَة / إِذَنْ',
          words: ['مُحَمَّدٌ', 'مُحَمَّدًا', 'حَمْزَة', 'إِذَنْ'],
          labels: ['مُحَمَّدْ', 'مُحَمَّدا', 'حَمْزَةْ', 'إِذًا'],
          distractors: ['مُحَمَّدٍ'],
        },
      ],
    },
  ],
};
