// Module 02 — الْفِعْل الْقِيَاسِيّ (The Analogical/Rule-Governed Verb)
//
// Content is adapted from a bilingual Anki deck
// (النَحْوُ__2 الْعَامِلِ وَغَيْرِ الْعَامِلِ__1 الْفِعْلِ__1 القياسي.apkg,
// 36 notes across 2 sub-decks) and cross-checked against the Daram Learn
// lessons for al-Kubrā fī an-Naḥw (m1-bab-1, sections qiyasi/qulub/tahwil/
// taliq) and its game bank (bank-fil), from which several worked `examples`
// and bank questions are drawn. Every Arabic word is fully vocalised: in a
// grammar text a wrong harakah teaches wrong grammar, and this chapter is
// entirely about which مَفْعُول is مَنْصُوب by what.
//
// The source deck covers only الْفِعْل الْقِيَاسِيّ (§1 of الْفِعْل, itself §1 of
// الْعَامِل وَغَيْر الْعَامِل) — اللَّازِم/الْمُتَعَدِّي, أَفْعَال الْقُلُوب, أَفْعَال التَّحْوِيل, and
// التَّعْلِيق/الْإِلْغَاء. الْفِعْل السَّمَاعِيّ (§2 of الْفِعْل) is covered separately in
// Module 03; الْعَامِل within الِاسْم and الْحَرْف could extend this module further.

export default {
  id: '02',
  title: 'الْفِعْل الْقِيَاسِيّ',
  heading: 'الْعَامِل وَغَيْر الْعَامِل',
  subheading: 'الْفِعْل',
  blurb: 'The قِيَاسِيّ فِعْل: transitivity (لَازِم vs مُتَعَدٍّ), the multi-object أَفْعَال الْقُلُوب and أَفْعَال التَّحْوِيل, and how التَّعْلِيق and الْإِلْغَاء affect their government.',
  lessons: [
    // ---------------------------------------------------------------- L1
    {
      id: 'l1',
      title: 'اللَّازِمُ وَالْمُتَعَدِّي',
      subtitle: 'Transitivity — تَعْرِيفُ اللَّازِمِ وَالْمُتَعَدِّي, and the two ways a فِعْل reaches its مَفْعُول',
      concepts: [
        {
          heading: 'عَامِلُ الْفِعْلِ: الْقِيَاسِيُّ وَالسَّمَاعِيُّ',
          tldr: 'الْقِيَاسِيّ governs by one fixed rule — رَفْع on the فَاعِل, نَصْب on the مَفَاعِيل and the حَال — while السَّمَاعِيّ follows no rule at all.',
          body: `<bdi>عَامِلُ الْفِعْلِ</bdi> — the way a فِعْل governs the words around it — comes in two kinds. (1) <bdi>الْقِيَاسِيُّ</bdi> has a <bdi>قَاعِدَةٌ مُطَّرِدَةٌ</bdi>, a rule that holds every time. (2) <bdi>السَّمَاعِيُّ</bdi> has no such rule and rests on <bdi>السَّمَاعُ</bdi>, what was heard from the Arabs. This module treats الْقِيَاسِيّ alone. Its rule runs in two directions: (1) it puts <bdi>الْفَاعِلَ</bdi>, or <bdi>نَائِبَهُ</bdi> when the فِعْل is مَبْنِيّ لِلْمَجْهُول, in <bdi>رَفْع</bdi>, (2) it puts <bdi>الْمَفَاعِيلَ</bdi> and <bdi>الْحَالَ</bdi> in <bdi>نَصْب</bdi>. Nothing else falls to it — a <bdi>جَرّ</bdi> ending never comes from the فِعْل.`,
          examples: [
            { ar: 'ضَرَبَ الْوَلَدُ الْكَلْبَ مُسْرِعًا', en: 'the boy struck the dog, hurrying', note: 'the whole قِيَاسِيّ rule in one جُمْلَة — الْوَلَدُ مَرْفُوع as فَاعِل, الْكَلْبَ مَنْصُوب as مَفْعُول بِهِ, مُسْرِعًا مَنْصُوب as حَال' },
            { ar: 'ضُرِبَ الْكَلْبُ', en: 'the dog was struck', note: 'with no فَاعِل left, الْكَلْبُ steps up as نَائِبُ الْفَاعِلِ and takes the same رَفْع the فَاعِل had' },
            { ar: 'كَانَ زَيْدٌ قَائِمًا', en: 'Zayd was standing', note: 'a سَمَاعِيّ عَامِل by contrast — كَانَ raises زَيْدٌ as its اسْم and puts قَائِمًا in نَصْب as its خَبَر, which no قَاعِدَة مُطَّرِدَة predicts' },
          ],
          exercise: {
            prompt: `Which of these is NOT something the قِيَاسِيّ فِعْل governs?`,
            kind: 'mcq',
            options: ['رَفْعُ الْفَاعِلِ', 'نَصْبُ الْمَفْعُولِ بِهِ', 'نَصْبُ الْحَالِ', 'جَرُّ الْمُضَافِ إِلَيْهِ'],
            correct: 3,
          },
        },
        {
          heading: 'الْفِعْلُ اللَّازِمُ',
          tldr: 'اللَّازِم is a فِعْل whose effect never reaches a مَفْعُول بِهِ — though it still reaches a مَفْعُول فِيهِ or a حَال.',
          body: `<bdi>الْفِعْلُ اللَّازِمُ</bdi> is one whose effect does not pass beyond its <bdi>فَاعِل</bdi> to a <bdi>مَفْعُولٌ بِهِ</bdi>. It carries three names for the one idea: (1) <bdi>لَازِم</bdi>, (2) <bdi>فِعْلٌ قَاصِرٌ</bdi> — it falls short of an object, (3) <bdi>فِعْلٌ غَيْرُ مُتَعَدٍّ</bdi> — it does not cross over. What لُزُوم bars is one thing only, the مَفْعُول بِهِ. The same فِعْل may still put other مَنْصُوبَات after it, above all the <bdi>مَفْعُول فِيهِ</bdi> and the <bdi>حَال</bdi>. So do not read "no مَفْعُول بِهِ" as "no مَنْصُوب at all".`,
          examples: [
            { ar: '﴿وَلَا هُمْ يَحْزَنُونَ﴾', en: 'nor shall they grieve', note: 'يَحْزَنُونَ has its فَاعِل in the وَاو and nothing receives the grieving — لَازِم' },
            { ar: 'جَلَسَ الطَّالِبُ أَمَامَ الْمُعَلِّمِ مُتَأَدِّبًا', en: 'the student sat before the teacher, well-mannered', note: 'جَلَسَ is لَازِم, yet أَمَامَ is مَنْصُوب as مَفْعُول فِيهِ and مُتَأَدِّبًا مَنْصُوب as حَال — only الطَّالِبُ is مَرْفُوع' },
          ],
          exercise: {
            prompt: `جَلَسَ الطَّالِبُ أَمَامَ الْمُعَلِّمِ has no مَفْعُول بِهِ, so جَلَسَ is لَازِم. Does that mean its effect cannot reach anything beyond الْفَاعِل at all?`,
            kind: 'mcq',
            options: ['Correct — a لَازِم فِعْل never governs anything beyond its فَاعِل', 'No — it can still reach a مَفْعُول فِيهِ or a حَال, just not a مَفْعُول بِهِ', 'No — it can still take a second فَاعِل', 'No — الْفِعْل اللَّازِم takes a مَفْعُول بِهِ whenever that مَفْعُول is مَعْرِفَة'],
            correct: 1,
          },
        },
        {
          heading: 'طُرُقُ التَّعَدِّي: بِنَفْسِهِ وَبِحَرْفِ الْجَرِّ',
          tldr: 'A مُتَعَدٍّ reaches its مَفْعُول بِهِ either بِنَفْسِهِ, leaving it مَنْصُوب, or بِوَاسِطَةِ حَرْفِ جَرٍّ, leaving it مَجْرُور.',
          body: `<bdi>الْفِعْلُ الْمُتَعَدِّي</bdi> is one whose effect does pass to a <bdi>مَفْعُولٌ بِهِ</bdi>, and it too carries three names: (1) <bdi>مُتَعَدٍّ</bdi>, (2) <bdi>فِعْلٌ وَاقِعٌ</bdi> — its effect falls upon the object, (3) <bdi>فِعْلٌ مُجَاوِزٌ</bdi> — it crosses over to it. It reaches that مَفْعُول by one of two routes: (1) <bdi>بِنَفْسِهِ</bdi>, with the مَفْعُول بِهِ مَنْصُوب straight after it, (2) <bdi>بِوَاسِطَةِ حَرْفِ جَرٍّ</bdi>, with the مَفْعُول بِهِ مَجْرُور by that حَرْف. On the second route the جَارّ وَمَجْرُور gets three names of its own: (1) <bdi>مَفْعُولٌ بِهِ بِوَاسِطَةِ حَرْفِ الْجَرِّ</bdi>, (2) <bdi>مُتَعَلِّقٌ بِمَعْنَى الْمَفْعُولِ بِهِ</bdi>, (3) <bdi>مَفْعُولٌ بِهِ غَيْرُ صَرِيحٍ</bdi>. One and the same فِعْل can take both routes in different places.`,
          examples: [
            { ar: '﴿الْحَمْدُ لِلَّهِ الَّذِي أَذْهَبَ عَنَّا الْحَزَنَ﴾', en: 'praise be to Allah, who has removed grief from us', note: 'مُتَعَدٍّ بِنَفْسِهِ — الْحَزَنَ is مَنْصُوب by أَذْهَبَ itself, with no حَرْف جَرّ standing in between' },
            { ar: '﴿ذَهَبَ اللَّهُ بِنُورِهِمْ﴾', en: 'Allah took away their light', note: 'مُتَعَدٍّ بِوَاسِطَةِ حَرْفِ الْجَرِّ — نُورِ is مَجْرُور by the بَاء, yet it is the object in meaning: a مَفْعُول بِهِ غَيْرُ صَرِيحٍ' },
            { ar: '﴿اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ﴾', en: 'guide us to the straight path', note: 'هَدَى بِنَفْسِهِ here, الصِّرَاطَ مَنْصُوب — but بِحَرْفِ الْجَرِّ in ﴿وَهَدَاهُ إِلَىٰ صِرَاطٍ مُسْتَقِيمٍ﴾, where صِرَاطٍ is مَجْرُور by إِلَى' },
          ],
          exercise: {
            prompt: `In ﴿ذَهَبَ اللَّهُ بِنُورِهِمْ﴾, نُورِهِمْ is the مَفْعُول بِهِ of ذَهَبَ — but it is مَجْرُور, not مَنْصُوب. What is this way of being مُتَعَدٍّ called?`,
            kind: 'mcq',
            options: ['مُتَعَدٍّ بِنَفْسِهِ', 'مُتَعَدٍّ بِوَاسِطَةِ حَرْفِ الْجَرِّ', 'مُتَعَدٍّ إِلَى مَفْعُولَيْنِ', 'فِعْلٌ لَازِمٌ يَتْبَعُهُ حَرْفُ جَرٍّ'],
            correct: 1,
          },
        },
        {
          heading: 'أَضْرُبُ الْمُتَعَدِّي الثَّلَاثَةُ',
          tldr: 'A مُتَعَدٍّ takes one, two or three مَفَاعِيل, and the two-object kind splits by whether its مَفْعُولَانِ were originally a مُبْتَدَأٌ وَخَبَرٌ.',
          body: `Counted by how many مَفَاعِيل it reaches, the مُتَعَدِّي has three <bdi>أَضْرُبٍ</bdi>: (1) <bdi>مُتَعَدٍّ إِلَى مَفْعُولٍ وَاحِدٍ</bdi>, (2) <bdi>مُتَعَدٍّ إِلَى مَفْعُولَيْنِ</bdi>, (3) <bdi>مُتَعَدٍّ إِلَى ثَلَاثَةِ مَفَاعِيلَ</bdi>. The middle ضَرْب then divides again, and the test is the origin of its two مَفَاعِيل. (1) Where they were never a <bdi>مُبْتَدَأٌ وَخَبَرٌ</bdi>, the فِعْل is a <bdi>فِعْلُ جَارِحَةٍ</bdi> — the giving أَفْعَال <bdi>أَعْطَى، مَنَحَ، وَهَبَ، كَسَا</bdi> and their like. (2) Where they were a مُبْتَدَأٌ وَخَبَرٌ, the فِعْل is a <bdi>فِعْلُ قَلْبٍ</bdi> or a <bdi>فِعْلُ تَحْوِيلٍ</bdi>. Both مَفْعُولَانِ are مَنْصُوب either way; only their origin differs. Lessons 2 and 3 are built entirely on that second kind.`,
          examples: [
            { ar: '﴿خَلَقَ السَّمَاوَاتِ وَالْأَرْضَ﴾', en: 'He created the heavens and the earth', note: 'one مَفْعُول بِهِ — السَّمَاوَاتِ is مَنْصُوب by كَسْرَة, being a جَمْع مُؤَنَّث سَالِم, and الْأَرْضَ is مَعْطُوف on it' },
            { ar: '﴿وَهَدَيْنَاهُمَا الصِّرَاطَ الْمُسْتَقِيمَ﴾', en: 'and We guided them both to the straight path', note: 'two مَفَاعِيل — هُمَا then الصِّرَاطَ مَنْصُوب — but هُمَا الصِّرَاطُ is no sentence, so هَدَى is a فِعْلُ جَارِحَةٍ' },
            { ar: '﴿وَمَا أَظُنُّ السَّاعَةَ قَائِمَةً﴾', en: 'and I do not think the Hour will come to pass', note: 'السَّاعَةُ قَائِمَةٌ was a مُبْتَدَأٌ وَخَبَرٌ; أَظُنُّ turned both into مَنْصُوبَيْنِ, السَّاعَةَ قَائِمَةً — a فِعْلُ قَلْبٍ' },
          ],
          exercise: {
            prompt: `أَعْطَى takes two مَفَاعِيل, and so does ظَنَّ. What separates the class أَعْطَى belongs to from the class ظَنَّ belongs to?`,
            kind: 'mcq',
            options: ['Whether the two مَفَاعِيل were originally a مُبْتَدَأٌ وَخَبَرٌ', 'Whether the فِعْل is مَاضٍ or مُضَارِع', 'Whether the فِعْل is لَازِم or مُتَعَدٍّ', 'Whether the مَفْعُولَانِ can ever be deleted'],
            correct: 0,
          },
        },
      ],
      quiz: [
        {
          q: 'What are the two types of عَامِلُ الْفِعْلِ؟',
          options: ['الْقِيَاسِيُّ وَالسَّمَاعِيُّ', 'اللَّازِمُ وَالْمُتَعَدِّي', 'الظَّاهِرُ وَالْمُقَدَّرُ', 'الْأَصْلِيُّ وَالْفَرْعِيُّ'],
          correct: 0,
        },
        {
          q: 'الْفِعْل اللَّازِم is defined as:',
          options: ['A فِعْل whose effect passes to a مَفْعُول بِهِ', 'A فِعْل whose effect does not pass beyond its فَاعِل to a مَفْعُول بِهِ', 'A فِعْل tied to a specific time', 'A فِعْل that never takes a فَاعِل'],
          correct: 1,
        },
        {
          q: 'Which best describes الْفِعْل الْمُتَعَدِّي؟',
          options: ['فِعْلٌ قَاصِرٌ, whose effect stays with its فَاعِل', 'فِعْلٌ وَاقِعٌ, whose effect passes to a مَفْعُول بِهِ', 'فِعْلٌ جَامِدٌ, which cannot be conjugated', 'فِعْلٌ مَبْنِيٌّ, which never takes إِعْرَاب'],
          correct: 1,
        },
        {
          q: 'In ﴿وَهَدَاهُ إِلَىٰ صِرَاطٍ مُسْتَقِيمٍ﴾, how is هَدَى مُتَعَدٍّ here?',
          options: ['بِنَفْسِهِ', 'بِوَاسِطَةِ حَرْفِ الْجَرِّ', 'It is لَازِم in this āyah', 'By way of its فَاعِل'],
          correct: 1,
        },
        {
          q: 'أَعْطَى and مَنَحَ belong to which class of two-مَفْعُول أَفْعَال؟',
          options: ['أَفْعَالُ الْجَارِحَةِ', 'أَفْعَالُ الْقُلُوبِ', 'أَفْعَالُ التَّحْوِيلِ', 'أَفْعَالُ الشُّرُوعِ'],
          correct: 0,
        },
        {
          q: 'Can the مَفَاعِيل of a giving-type فِعْل (مُتَعَدٍّ لِمَفْعُولَيْنِ) be deleted?',
          options: ['Yes — one, the other, or both may be deleted', 'No, never', 'Only the first may be deleted', 'Only when the فِعْل is a فِعْل أَمْر'],
          correct: 0,
        },
      ],
      bank: [
        {
          title: 'قِيَاسِيٌّ أَمْ سَمَاعِيٌّ؟',
          kind: 'mcq',
          prompt: "A فِعْل's government follows no consistent rule and depends only on what has been transmitted. That government is:",
          options: ['قِيَاسِيٌّ', 'سَمَاعِيٌّ', 'مُطَّرِدٌ', 'مَنْسُوخٌ'],
          correct: 1,
        },
        {
          title: 'مَاذَا يَرْفَعُ الْقِيَاسِيُّ؟',
          kind: 'mcq',
          prompt: 'الْفِعْل الْقِيَاسِيّ puts which of these in رَفْع?',
          options: ['الْفَاعِلَ أَوْ نَائِبَهُ', 'الْمَفْعُولَ بِهِ', 'الْحَالَ', 'الْمُضَافَ إِلَيْهِ'],
          correct: 0,
        },
        {
          title: 'أَسْمَاءٌ أُخْرَى لِلَّازِمِ',
          kind: 'mcq',
          prompt: 'الْفِعْل اللَّازِم is also known as:',
          options: ['فِعْلٌ قَاصِرٌ', 'فِعْلٌ وَاقِعٌ', 'فِعْلٌ مُجَاوِزٌ', 'فِعْلُ جَارِحَةٍ'],
          correct: 0,
        },
        {
          title: 'أَسْمَاءٌ أُخْرَى لِلْمُتَعَدِّي',
          kind: 'mcq',
          prompt: 'الْفِعْل الْمُتَعَدِّي is called فِعْلًا وَاقِعًا, and is also known as:',
          options: ['فِعْلًا مُجَاوِزًا', 'فِعْلًا قَاصِرًا', 'فِعْلًا جَارِحًا', 'فِعْلًا نَاقِصًا'],
          correct: 0,
        },
        {
          title: 'مِثَالٌ عَلَى اللَّازِمِ',
          kind: 'mcq',
          prompt: '﴿وَلَا هُمْ يَحْزَنُونَ﴾ — why is يَحْزَنُونَ counted a فِعْل لَازِم?',
          options: ['Because its effect reaches no مَفْعُول بِهِ', 'Because it has no فَاعِل', 'Because it is مَبْنِيّ لِلْمَجْهُول', 'Because it does not accept تَصْرِيف'],
          correct: 0,
        },
        {
          title: 'هَلْ يَتَعَدَّى اللَّازِمُ لِغَيْرِ الْمَفْعُولِ بِهِ؟',
          kind: 'mcq',
          prompt: 'جَلَسَ الطَّالِبُ أَمَامَ الْمُعَلِّمِ مُتَأَدِّبًا — أَمَامَ and مُتَأَدِّبًا prove that a لَازِم فِعْل can still reach:',
          options: ['الْمَفْعُولَ فِيهِ وَالْحَالَ', 'الْمَفْعُولَ بِهِ وَحْدَهُ', 'الْمَفْعُولَ الْمُطْلَقَ وَحْدَهُ', 'Nothing at all beyond its فَاعِل'],
          correct: 0,
        },
        {
          title: 'الْحَالُ فِي جُمْلَةِ اللَّازِمِ',
          kind: 'mcq',
          prompt: 'In جَلَسَ الطَّالِبُ أَمَامَ الْمُعَلِّمِ مُتَأَدِّبًا, which single word is the حَال?',
          options: ['مُتَأَدِّبًا', 'أَمَامَ', 'الطَّالِبُ', 'الْمُعَلِّمِ'],
          correct: 0,
        },
        {
          title: 'مُتَعَدٍّ بِنَفْسِهِ',
          kind: 'mcq',
          prompt: '﴿الْحَمْدُ لِلَّهِ الَّذِي أَذْهَبَ عَنَّا الْحَزَنَ﴾ — أَذْهَبَ here is مُتَعَدٍّ:',
          options: ['بِنَفْسِهِ', 'بِحَرْفِ الْجَرِّ', 'إِلَى مَفْعُولَيْنِ', 'بِوَاسِطَةِ الْفَاعِلِ'],
          correct: 0,
        },
        {
          title: 'إِعْرَابُ الْحَزَنَ',
          kind: 'mcq',
          prompt: 'In ﴿أَذْهَبَ عَنَّا الْحَزَنَ﴾, what is the إِعْرَاب of الْحَزَنَ?',
          options: ['مَفْعُولٌ بِهِ مَنْصُوبٌ', 'مَجْرُورٌ بِعَنْ', 'حَالٌ مَنْصُوبٌ', 'فَاعِلٌ مَرْفُوعٌ'],
          correct: 0,
        },
        {
          title: 'مُتَعَدٍّ بِحَرْفِ جَرٍّ',
          kind: 'mcq',
          prompt: '﴿ذَهَبَ اللَّهُ بِنُورِهِمْ﴾ — how does ذَهَبَ reach its مَفْعُول here?',
          options: ['بِوَاسِطَةِ حَرْفِ الْجَرِّ', 'بِنَفْسِهِ مُبَاشَرَةً', 'بِالتَّضْعِيفِ', 'It does not reach one — ذَهَبَ is لَازِم here'],
          correct: 0,
        },
        {
          title: 'اسْمٌ آخَرُ لِلْمَفْعُولِ بِوَاسِطَةِ حَرْفِ الْجَرِّ',
          kind: 'mcq',
          prompt: 'A مَفْعُول بِهِ reached by way of a حَرْف جَرّ is also called:',
          options: ['مَفْعُولًا بِهِ غَيْرَ صَرِيحٍ', 'مَفْعُولًا مُطْلَقًا', 'مَفْعُولًا لِأَجْلِهِ', 'نَائِبَ فَاعِلٍ'],
          correct: 0,
        },
        {
          title: 'هَدَى بِالطَّرِيقَتَيْنِ',
          kind: 'mcq',
          prompt: '﴿اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ﴾ and ﴿وَهَدَاهُ إِلَىٰ صِرَاطٍ مُسْتَقِيمٍ﴾ together prove that:',
          options: ['One and the same فِعْل can be مُتَعَدٍّ بِنَفْسِهِ in one place and بِحَرْفِ الْجَرِّ in another', 'هَدَى is a فِعْل لَازِم in every context', 'هَدَى only ever reaches its مَفْعُول through a حَرْف جَرّ', 'التَّعَدِّي بِحَرْفِ الْجَرِّ is impossible with هَدَى'],
          correct: 0,
        },
        {
          title: 'أَضْرُبُ الْمُتَعَدِّي',
          kind: 'mcq',
          prompt: 'How many أَضْرُب does الْفِعْل الْمُتَعَدِّي split into, counted by number of مَفَاعِيل?',
          options: ['ثَلَاثَةٌ', 'اثْنَانِ', 'أَرْبَعَةٌ', 'خَمْسَةٌ'],
          correct: 0,
        },
        {
          title: 'مَفْعُولٌ وَاحِدٌ',
          kind: 'mcq',
          prompt: '﴿خَلَقَ السَّمَاوَاتِ وَالْأَرْضَ﴾ — خَلَقَ here is مُتَعَدٍّ to:',
          options: ['مَفْعُولٍ وَاحِدٍ', 'مَفْعُولَيْنِ', 'ثَلَاثَةِ مَفَاعِيلَ', 'It reaches no مَفْعُول at all'],
          correct: 0,
        },
        {
          title: 'أَفْعَالُ الْجَارِحَةِ',
          kind: 'mcq',
          prompt: 'أَعْطَى، مَنَحَ، وَهَبَ، كَسَا take two مَفْعُولَيْنِ that were NOT originally مُبْتَدَأٌ وَخَبَرٌ. These أَفْعَال are called:',
          options: ['أَفْعَالُ الْجَارِحَةِ', 'أَفْعَالُ الْقُلُوبِ', 'أَفْعَالُ التَّحْوِيلِ', 'أَفْعَالُ الشُّرُوعِ'],
          correct: 0,
        },
        {
          title: 'أَصْلُ الْمَفْعُولَيْنِ',
          kind: 'mcq',
          prompt: 'What distinguishes the مَفْعُولَانِ of a فِعْل like ظَنَّ from those of a فِعْل like أَعْطَى?',
          options: ["That ظَنَّ's two مَفْعُولَانِ were originally مُبْتَدَأٌ وَخَبَرٌ", "That أَعْطَى's two مَفْعُولَانِ were originally مُبْتَدَأٌ وَخَبَرٌ", 'That ظَنَّ can only ever take one مَفْعُول', 'There is no difference between the two classes'],
          correct: 0,
        },
        {
          title: 'الْمَفْعُولُ الْأَوَّلُ لِهَدَى',
          kind: 'mcq',
          prompt: 'In ﴿وَهَدَيْنَاهُمَا الصِّرَاطَ الْمُسْتَقِيمَ﴾, which word is the FIRST مَفْعُول بِهِ?',
          options: ['the attached pronoun هُمَا', 'الصِّرَاطَ', 'الْمُسْتَقِيمَ', 'the نَا of هَدَيْنَا'],
          correct: 0,
        },
        {
          title: 'لِمَاذَا هَدَى فِعْلُ جَارِحَةٍ',
          kind: 'mcq',
          prompt: 'Why do the two مَفَاعِيل of ﴿وَهَدَيْنَاهُمَا الصِّرَاطَ الْمُسْتَقِيمَ﴾ not count as an original مُبْتَدَأٌ وَخَبَرٌ?',
          options: ['Because هُمَا الصِّرَاطُ was never a meaningful جُمْلَة to begin with', 'Because the first مَفْعُول is a pronoun rather than a plain اسْم', 'Because هَدَى can also be مُتَعَدٍّ بِحَرْفِ الْجَرِّ', 'Because الصِّرَاطَ carries أَلْ and so cannot be a خَبَر'],
          correct: 0,
        },
        {
          title: 'حَذْفُ مَفَاعِيلِ أَفْعَالِ الْإِعْطَاءِ',
          kind: 'mcq',
          prompt: '﴿وَإِنَّكَ لَتَهْدِي إِلَىٰ صِرَاطٍ مُسْتَقِيمٍ﴾ drops one مَفْعُول of هَدَى. Which مَفَاعِيل of a giving-type فِعْل may be dropped?',
          options: ['Either one of them, or both together', 'Neither of them, under any circumstance', 'The first alone', 'The second alone'],
          correct: 0,
        },
        {
          title: 'مِثَالُ حَذْفِ كِلَا الْمَفْعُولَيْنِ',
          kind: 'mcq',
          prompt: '﴿أَعْطَىٰ كُلَّ شَيْءٍ خَلْقَهُ ثُمَّ هَدَىٰ﴾ — what has been dropped from هَدَى here?',
          options: ['Both of its مَفْعُولَانِ together', 'Its فَاعِل alone', 'Only the حَرْف جَرّ', 'Nothing has been dropped'],
          correct: 0,
        },
        {
          title: 'الْفِعْلُ الْقِيَاسِيُّ: مَاذَا يَنْصِبُ؟',
          kind: 'mcq',
          prompt: 'Besides raising the فَاعِل, what does الْفِعْل الْقِيَاسِيّ put in نَصْب?',
          options: ['الْمَفَاعِيلَ وَالْحَالَ', 'الْمُضَافَ إِلَيْهِ', 'الْفَاعِلَ نَفْسَهُ', 'التَّمْيِيزَ وَحْدَهُ'],
          correct: 0,
        },
        {
          title: 'الْفِعْلُ الْوَاقِعُ',
          kind: 'mcq',
          prompt: 'Why is الْفِعْل الْمُتَعَدِّي also called فِعْلًا وَاقِعًا?',
          options: ['Because its effect falls (يَقَعُ) upon the مَفْعُول بِهِ', 'Because it falls between two فَاعِلَيْنِ', 'Because it only occurs in the مَاضِي', 'Because it takes the place of an اسْم'],
          correct: 0,
        },
        {
          title: 'تَرْكِيب: لَازِمٌ أَمْ مُتَعَدٍّ؟',
          kind: 'tarkeeb',
          instruction: 'Classify each فِعْل: لَازِم or مُتَعَدٍّ?',
          source: '﴿وَلَا هُمْ يَحْزَنُونَ﴾ / ﴿خَلَقَ السَّمَاوَاتِ وَالْأَرْضَ﴾ / جَلَسَ الطَّالِبُ / ﴿أَذْهَبَ عَنَّا الْحَزَنَ﴾',
          words: ['يَحْزَنُونَ', 'خَلَقَ', 'جَلَسَ', 'أَذْهَبَ'],
          labels: ['لَازِم', 'مُتَعَدٍّ', 'لَازِم', 'مُتَعَدٍّ'],
          distractors: ['فِعْلُ قَلْبٍ'],
        },
        {
          title: 'تَرْكِيب: بِنَفْسِهِ أَمْ بِحَرْفِ جَرٍّ؟',
          kind: 'tarkeeb',
          instruction: 'Classify how each فِعْل reaches its مَفْعُول: بِنَفْسِهِ or بِحَرْفِ جَرٍّ?',
          source: '﴿أَذْهَبَ عَنَّا الْحَزَنَ﴾ / ﴿ذَهَبَ اللَّهُ بِنُورِهِمْ﴾ / ﴿اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ﴾ / ﴿وَهَدَاهُ إِلَىٰ صِرَاطٍ مُسْتَقِيمٍ﴾',
          words: ['أَذْهَبَ', 'ذَهَبَ', 'اهْدِنَا', 'هَدَاهُ'],
          labels: ['مُتَعَدٍّ بِنَفْسِهِ', 'مُتَعَدٍّ بِحَرْفِ جَرٍّ', 'مُتَعَدٍّ بِنَفْسِهِ', 'مُتَعَدٍّ بِحَرْفِ جَرٍّ'],
          distractors: ['لَازِم'],
        },
        {
          title: 'تَرْكِيب: أَفْعَالُ الْجَارِحَةِ أَمْ أَفْعَالُ الْقَلْبِ؟',
          kind: 'tarkeeb',
          instruction: 'Classify each two-مَفْعُول فِعْل: أَفْعَالُ الْجَارِحَةِ or أَفْعَالُ الْقَلْبِ?',
          source: '﴿وَهَدَيْنَاهُمَا الصِّرَاطَ الْمُسْتَقِيمَ﴾ / ﴿وَمَا أَظُنُّ السَّاعَةَ قَائِمَةً﴾ / ﴿أَعْطَىٰ كُلَّ شَيْءٍ خَلْقَهُ﴾ / مَنَحَ الْأَمِيرُ الْفَقِيرَ مَالًا',
          words: ['هَدَيْنَاهُمَا', 'أَظُنُّ', 'أَعْطَىٰ', 'مَنَحَ'],
          labels: ['أَفْعَالُ الْجَارِحَةِ', 'أَفْعَالُ الْقَلْبِ', 'أَفْعَالُ الْجَارِحَةِ', 'أَفْعَالُ الْجَارِحَةِ'],
          distractors: ['أَفْعَالٌ نَاقِصَةٌ'],
        },
        {
          title: 'تَرْكِيب: مَاذَا يَرْفَعُ وَيَنْصِبُ الْقِيَاسِيُّ؟',
          kind: 'tarkeeb',
          instruction: "Identify each word's grammatical role under الْفِعْل الْقِيَاسِيّ's government.",
          source: 'ضَرَبَ الْوَلَدُ الْكَلْبَ مُسْرِعًا',
          words: ['الْوَلَدُ', 'الْكَلْبَ', 'مُسْرِعًا'],
          labels: ['فَاعِلٌ مَرْفُوعٌ', 'مَفْعُولٌ بِهِ مَنْصُوبٌ', 'حَالٌ مَنْصُوبٌ'],
          distractors: ['مُضَافٌ إِلَيْهِ مَجْرُورٌ'],
        },
        {
          title: 'تَرْكِيب: لَازِمٌ أَمْ مُتَعَدٍّ؟ (٢)',
          kind: 'tarkeeb',
          instruction: 'Classify each فِعْل: لَازِم or مُتَعَدٍّ?',
          source: '﴿فَاصْبِرْ صَبْرًا جَمِيلًا﴾ / ﴿وَاللَّهُ بَصِيرٌ بِمَا تَعْمَلُونَ﴾ / خَرَجَ الرَّجُلُ / أَكَلَ الْوَلَدُ التُّفَّاحَةَ',
          words: ['اصْبِرْ', 'تَعْمَلُونَ', 'خَرَجَ', 'أَكَلَ'],
          labels: ['لَازِم', 'مُتَعَدٍّ', 'لَازِم', 'مُتَعَدٍّ'],
          distractors: ['فِعْلُ تَحْوِيلٍ'],
        },
        {
          title: 'تَرْكِيب: عَدَدُ الْمَفَاعِيلِ',
          kind: 'tarkeeb',
          instruction: 'Classify each فِعْل by its number of مَفَاعِيل: مَفْعُولٌ وَاحِدٌ or مَفْعُولَانِ?',
          source: '﴿خَلَقَ السَّمَاوَاتِ وَالْأَرْضَ﴾ / ﴿وَهَدَيْنَاهُمَا الصِّرَاطَ الْمُسْتَقِيمَ﴾ / مَنَحَ الْأَمِيرُ الْفَقِيرَ مَالًا / ﴿أَذْهَبَ عَنَّا الْحَزَنَ﴾',
          words: ['خَلَقَ', 'هَدَيْنَاهُمَا', 'مَنَحَ', 'أَذْهَبَ'],
          labels: ['مَفْعُولٌ وَاحِدٌ', 'مَفْعُولَانِ', 'مَفْعُولَانِ', 'مَفْعُولٌ وَاحِدٌ'],
          distractors: ['ثَلَاثَةُ مَفَاعِيلَ'],
        },
      ],
    },

    // ---------------------------------------------------------------- L2
    {
      id: 'l2',
      title: 'أَفْعَالُ الْقُلُوبِ',
      subtitle: 'Verbs of the Heart — الْيَقِين and الظَّنّ, and how their two مَنْصُوبَانِ behave',
      concepts: [
        {
          heading: 'أَفْعَالُ الْقُلُوبِ: الْيَقِينُ وَالظَّنُّ',
          tldr: 'أَفْعَالُ الْقُلُوبِ are the two-object أَفْعَال of inner judgement: seven of الْيَقِين and eight of الظَّنّ, each pair of مَفَاعِيل once a مُبْتَدَأٌ وَخَبَرٌ.',
          body: `<bdi>أَفْعَالُ الْقُلُوبِ</bdi> are the branch of the two-object مُتَعَدِّي whose مَفْعُولَانِ were originally a <bdi>مُبْتَدَأٌ وَخَبَرٌ</bdi>. The فِعْل enters on that nominal جُمْلَة and pulls both halves down into <bdi>نَصْب</bdi>. They divide by the strength of the judgement in the heart. Those of certainty, <bdi>الْيَقِينُ</bdi>, are seven: <bdi>وَجَدَ</bdi>، <bdi>أَلْفَى</bdi>، <bdi>رَأَى</bdi>، <bdi>عَلِمَ</bdi>، <bdi>عَرَفَ</bdi>، <bdi>دَرَى</bdi>، <bdi>تَعَلَّمْ</bdi>. Those of preponderant opinion, <bdi>الظَّنُّ</bdi> — also called <bdi>أَفْعَالُ الرُّجْحَانِ</bdi> — are eight: <bdi>ظَنَّ</bdi>، <bdi>حَسِبَ</bdi>، <bdi>زَعَمَ</bdi>، <bdi>جَعَلَ</bdi>، <bdi>حَجَا</bdi>، <bdi>عَدَّ</bdi>، <bdi>وَهَبَ</bdi>، <bdi>خَالَ</bdi>. That origin in a مُبْتَدَأٌ وَخَبَرٌ is what makes a فِعْل a فِعْلُ قَلْبٍ rather than a plain مُتَعَدٍّ لِمَفْعُولَيْنِ.`,
          examples: [
            { ar: 'عَلِمْتُ زَيْدًا قَائِمًا', en: 'I knew Zayd to be standing', note: 'a فِعْل of الْيَقِين — زَيْدٌ قَائِمٌ came in as مُبْتَدَأ وَخَبَر and left as زَيْدًا قَائِمًا, both مَنْصُوب by عَلِمَ' },
            { ar: 'ظَنَنْتُ الْجَوَّ صَافِيًا', en: 'I thought the weather clear', note: 'a فِعْل of الظَّنّ — the same two مَنْصُوبَانِ, but the judgement is رُجْحَان, a leaning, not certainty' },
            { ar: 'تَعَلَّمْ شِفَاءَ النَّفْسِ قَهْرَ عَدُوِّهَا', en: "know that the soul's cure is subduing its enemy", note: 'تَعَلَّمْ in this list means اعْلَمْ, not "learn"; شِفَاءَ is its first مَفْعُول and قَهْرَ its second, both مَنْصُوب' },
          ],
          exercise: {
            prompt: `عَلِمَ and ظَنَّ are both أَفْعَال الْقُلُوب, but from different families. Which family does ظَنَّ belong to?`,
            kind: 'mcq',
            options: ['الْيَقِين', 'الظَّنّ (الرُّجْحَان)', 'Both families at once', 'Neither of the two'],
            correct: 1,
          },
        },
        {
          heading: 'أَمْثِلَةٌ قُرْآنِيَّةٌ عَلَى أَفْعَالِ الْقُلُوبِ',
          tldr: 'One شَاهِد per family: وَجَدَ reads as يَقِين, while حَسِبَ and جَعَلَ read as ظَنّ — and each governs two مَنْصُوبَيْنِ.',
          body: `In <bdi>﴿وَإِنْ وَجَدْنَا أَكْثَرَهُمْ لَفَاسِقِينَ﴾</bdi>, <bdi>وَجَدَ</bdi> means "we knew for certain", so it is a فِعْلُ قَلْبٍ of الْيَقِين. Its two مَفْعُولَانِ are <bdi>أَكْثَرَهُمْ</bdi>, مَنْصُوب by فَتْحَة, and <bdi>لَفَاسِقِينَ</bdi>, مَنْصُوب by the يَاء of the جَمْع مُذَكَّر سَالِم. In <bdi>﴿وَيَحْسَبُونَ أَنَّهُمْ مُهْتَدُونَ﴾</bdi>, <bdi>حَسِبَ</bdi> reports a mere supposition, so it belongs to الظَّنّ. In <bdi>﴿وَجَعَلُوا الْمَلَائِكَةَ الَّذِينَ هُمْ عِبَادُ الرَّحْمَٰنِ إِنَاثًا﴾</bdi>, <bdi>جَعَلَ</bdi> is also الظَّنّ: they could not transform the angels, they merely supposed them female.`,
          examples: [
            { ar: '﴿وَإِنْ وَجَدْنَا أَكْثَرَهُمْ لَفَاسِقِينَ﴾', en: 'and We found most of them to be transgressors', note: 'يَقِين — أَكْثَرَ is the first مَفْعُول and فَاسِقِينَ the second, both مَنْصُوب; the لَام is لَامُ الِابْتِدَاءِ, not part of the إِعْرَاب' },
            { ar: '﴿وَيَحْسَبُونَ أَنَّهُمْ مُهْتَدُونَ﴾', en: 'and they think that they are guided', note: 'ظَنّ — here أَنَّهُمْ مُهْتَدُونَ, an اسْم مُؤَوَّل, fills both مَفْعُول slots at once instead of two separate مَنْصُوبَيْنِ' },
            { ar: '﴿وَجَعَلُوا الْمَلَائِكَةَ الَّذِينَ هُمْ عِبَادُ الرَّحْمَٰنِ إِنَاثًا﴾', en: 'and they made the angels, who are the servants of the Most Merciful, females', note: 'ظَنّ — الْمَلَائِكَةَ is مَنْصُوب as first مَفْعُول and إِنَاثًا مَنْصُوب as second; no real transformation took place' },
          ],
          exercise: {
            prompt: `In ﴿وَجَعَلُوا الْمَلَائِكَةَ ... إِنَاثًا﴾, جَعَلَ takes الْمَلَائِكَةَ and إِنَاثًا as two مَنْصُوبَيْنِ. Which category of أَفْعَال الْقُلُوب is that?`,
            kind: 'mcq',
            options: ['فِعْلُ قَلْبٍ مِنْ أَفْعَالِ الظَّنِّ (الرُّجْحَانِ)', 'فِعْلُ قَلْبٍ مِنْ أَفْعَالِ الْيَقِينِ', 'Not a فِعْل قَلْب at all, but a فِعْل جَارِحَة', 'A فِعْل لَازِم that reaches no مَفْعُول'],
            correct: 0,
          },
        },
        {
          heading: 'حَذْفُ مَفَاعِيلِ أَفْعَالِ الْقُلُوبِ: الِاخْتِصَارُ وَالِاقْتِصَارُ',
          tldr: 'Dropping BOTH مَفْعُولَيْنِ with a قَرِينَة pointing to them is الِاخْتِصَار and is allowed; dropping just ONE with no قَرِينَة is الِاقْتِصَار and is not.',
          body: `The two مَفْعُولَانِ of a فِعْل قَلْب can drop out of the wording, but only on one pattern. (1) <bdi>الِاخْتِصَارُ</bdi> is dropping both together while a <bdi>قَرِينَة</bdi> elsewhere in the كَلَام still recovers them, and it is permitted. (2) <bdi>الِاقْتِصَارُ</bdi> is dropping one alone with nothing pointing to the other, and it is not permitted. The reason lies in where the two مَفْعُولَانِ came from. They were a <bdi>مُبْتَدَأٌ وَخَبَرٌ</bdi>, and you cannot name a subject and then withhold what is being said about it. So the choice is to keep both or to drop both.`,
          examples: [
            { ar: '﴿أَيْنَ شُرَكَائِيَ الَّذِينَ كُنْتُمْ تَزْعُمُونَ﴾', en: 'Where are My partners whom you used to claim?', note: 'الِاخْتِصَار — both مَفْعُولَا تَزْعُمُونَ are gone, the reading being تَزْعُمُونَهُمْ شُرَكَائِي, and شُرَكَائِي in the question is the قَرِينَة' },
            { ar: 'ظَنَنْتُ زَيْدًا', en: 'I thought Zayd…', note: 'الِاقْتِصَار — زَيْدًا is مَنْصُوب as the first مَفْعُول, but nothing supplies the second, so the كَلَام is left broken' },
          ],
          exercise: {
            prompt: `﴿أَيْنَ شُرَكَائِيَ الَّذِينَ كُنْتُمْ تَزْعُمُونَ﴾ deletes both مَفْعُولَا زَعَمَ, yet the sentence still stands. What licenses deleting both together?`,
            kind: 'mcq',
            options: ['That a قَرِينَة points to what was deleted — the permitted الِاخْتِصَار', 'That زَعَمَ is a فِعْل لَازِم needing no مَفْعُولَيْنِ', 'That deleting only one مَفْعُول is always the permitted option', 'That أَفْعَال الْقُلُوب need no مَفْعُول at all'],
            correct: 0,
          },
        },
        {
          heading: 'مَعَانٍ خَاصَّةٌ: أَلَمْ تَرَ وَأَرَأَيْتَ وَكَافُ الْخِطَابِ',
          tldr: 'أَلَمْ تَرَ is أَلَمْ تَعْلَمْ with تَعَجُّب, أَرَأَيْتَ is أَخْبِرْنِي, and the كَاف of أَرَأَيْتَكَ is pure تَوْكِيدُ الْخِطَابِ.',
          body: `Three idiomatic uses of رَأَى are worth learning on their own. (1) <bdi>أَلَمْ تَرَ</bdi> means <bdi>أَلَمْ تَعْلَمْ</bdi> with a shade of <bdi>التَّعَجُّب</bdi>; knowledge is voiced as seeing because <bdi>الْبَصَر</bdi> is its strongest cause. (2) <bdi>أَرَأَيْتَ</bdi> means <bdi>أَخْبِرْنِي</bdi> in a situation that astonishes, and its <bdi>ضَمِيرٌ مَرْفُوعٌ</bdi> tracks the addressee: <bdi>أَرَأَيْتِ</bdi>، <bdi>أَرَأَيْتُمَا</bdi>، <bdi>أَرَأَيْتُمْ</bdi>. (3) <bdi>أَرَأَيْتَكَ</bdi> adds a <bdi>كَافُ الْخِطَابِ</bdi> purely for <bdi>تَوْكِيدُ الْخِطَابِ</bdi>. The tell-tale sign is what moves. Once the كَاف is there the تَاء freezes at <bdi>تَ</bdi> and only the كَاف changes, which proves the كَاف is no ضَمِير مَرْفُوع.`,
          examples: [
            { ar: 'أَلَمْ تَرَ أَنَّ الصَّبْرَ مِفْتَاحُ الْفَرَجِ', en: 'do you not know that patience is the key to relief?', note: 'أَلَمْ تَرَ = أَلَمْ تَعْلَمْ with تَعَجُّب; the أَنَّ clause fills the مَفْعُول slot of the قَلْب فِعْل' },
            { ar: '﴿أَرَأَيْتَ مَنِ اتَّخَذَ إِلَٰهَهُ هَوَاهُ﴾', en: 'Have you seen the one who takes his desire as his god?', note: 'أَرَأَيْتَ = أَخْبِرْنِي — a demand for information about something remarkable, not a question about eyesight' },
            { ar: 'أَرَأَيْتَكِ، أَرَأَيْتَكُمْ', en: 'tell me! (to a woman; to a group)', note: 'the تَاء never leaves its فَتْحَة while the كَاف runs through كِ and كُمْ — so the كَاف is a كَاف خِطَاب, not the فَاعِل' },
          ],
          exercise: {
            prompt: `In أَرَأَيْتَكَ, which part is the ضَمِير مَرْفُوع of رَأَى, and which part is there only for تَوْكِيد الْخِطَاب?`,
            kind: 'mcq',
            options: ['التَّاء is the ضَمِير مَرْفُوع; الْكَاف is a كَاف خِطَاب for emphasis', 'الْكَاف is the ضَمِير مَرْفُوع; التَّاء is زَائِدَة for emphasis', 'The two together form one repeated ضَمِير مَرْفُوع', 'There is no ضَمِير in the word — the فِعْل is مَبْنِيّ لِلْمَجْهُول'],
            correct: 0,
          },
        },
        {
          heading: 'أَفْعَالُ الْقُلُوبِ خَارِجَ مَعْنَى الْقَلْبِ',
          tldr: 'Used outside its قَلْبِيّ sense, one of these أَفْعَال drops to a single مَفْعُول بِهِ مَنْصُوب like any ordinary مُتَعَدٍّ.',
          body: `The two-object behaviour rides on the mental judgement, not on the letters of the فِعْل. Take that sense away and the second مَفْعُول goes with it. The Qurʾān shows this: (1) <bdi>﴿لَا تَعْلَمُونَ شَيْئًا﴾</bdi> reads as لَا تَعْرِفُونَ, (2) <bdi>﴿لَاتَّخَذْتَ عَلَيْهِ أَجْرًا﴾</bdi> reads as طَلَبْتَ, (3) <bdi>﴿وَأَلْفَيَا سَيِّدَهَا لَدَى الْبَابِ﴾</bdi> reads as صَادَفَا. Ordinary speech does the same: (1) <bdi>وَجَدْتُ الضَّالَّةَ</bdi> is أَصَبْتُهَا, (2) <bdi>رَأَيْتُ زَيْدًا</bdi> is أَبْصَرْتُهُ, (3) <bdi>ظَنَنْتُ زَيْدًا</bdi> is اتَّهَمْتُهُ. In each of the six the one مَفْعُول is مَنْصُوب and no second مَنْصُوب follows it.`,
          examples: [
            { ar: 'رَأَيْتُ زَيْدًا', en: 'I saw Zayd', note: 'physical sight — زَيْدًا is the only مَفْعُول, مَنْصُوب, and nothing follows to be a second one' },
            { ar: 'رَأَيْتُ زَيْدًا صَادِقًا', en: 'I knew Zayd to be truthful', note: 'the قَلْبِيّ sense returns and a second مَنْصُوب appears — صَادِقًا, which was the خَبَر of زَيْدٌ صَادِقٌ' },
            { ar: '﴿وَأَلْفَيَا سَيِّدَهَا لَدَى الْبَابِ﴾', en: 'and they both found her master at the door', note: 'أَلْفَى here is صَادَفَا, a chance meeting — سَيِّدَ is its single مَفْعُول, and لَدَى is a ظَرْف, not a second one' },
          ],
          exercise: {
            prompt: `رَأَيْتُ زَيْدًا, in the sense of أَبْصَرْتُهُ, takes only one مَفْعُول. Why does رَأَى not take two مَفَاعِيل here the way it does as a فِعْل قَلْب?`,
            kind: 'mcq',
            options: ['Because it is used for physical sight (أَبْصَرَ), not for قَلْبِيّ knowledge', 'Because زَيْدًا cannot be a مَفْعُول بِهِ', 'Because رَأَى is لَازِم in this جُمْلَة', 'Because it is being used as a فِعْل أَمْر'],
            correct: 0,
          },
        },
      ],
      quiz: [
        {
          q: 'Which of these four is one of أَفْعَال الْيَقِين, not أَفْعَال الظَّنّ؟',
          options: ['حَسِبَ', 'زَعَمَ', 'عَلِمَ', 'خَالَ'],
          correct: 2,
        },
        {
          q: 'What does أَرَأَيْتَ mean in ﴿أَرَأَيْتَ مَنِ اتَّخَذَ إِلَٰهَهُ هَوَاهُ﴾؟',
          options: ['أَخْبِرْنِي', 'أَبْصَرْتَ', 'اعْتَقَدْتَ', 'اتَّهَمْتَ'],
          correct: 0,
        },
        {
          q: 'الِاخْتِصَار, in deleting the مَفَاعِيل of أَفْعَال الْقُلُوب, means:',
          options: ['Deleting both مَفْعُولَيْنِ together, with a قَرِينَة pointing to them', 'Deleting one مَفْعُول with no قَرِينَة at all', 'Never deleting any مَفْعُول under any circumstance', 'Turning the فِعْل into the صِيغَة الْمَبْنِيّ لِلْمَجْهُول'],
          correct: 0,
        },
        {
          q: 'ظَنَنْتُ زَيْدًا, in the sense of اتَّهَمْتُهُ, takes how many مَفَاعِيل؟',
          options: ['مَفْعُولًا وَاحِدًا', 'مَفْعُولَيْنِ', 'ثَلَاثَةَ مَفَاعِيلَ', 'It takes no مَفْعُول at all'],
          correct: 0,
        },
        {
          q: 'In أَرَأَيْتَكَ, what is the role of the كَاف؟',
          options: ['A كَاف خِطَاب added for تَوْكِيد, not a ضَمِير مَرْفُوع', 'The ضَمِير مَرْفُوع standing as فَاعِل', 'A مَفْعُول بِهِ', 'A حَرْف جَرّ'],
          correct: 0,
        },
        {
          q: 'In ﴿وَيَحْسَبُونَ أَنَّهُمْ مُهْتَدُونَ﴾, حَسِبَ belongs to:',
          options: ['أَفْعَالُ الْيَقِينِ', 'أَفْعَالُ الظَّنِّ (الرُّجْحَانِ)', 'أَفْعَالُ التَّحْوِيلِ', 'أَفْعَالُ الْجَارِحَةِ'],
          correct: 1,
        },
      ],
      bank: [
        {
          title: 'كَمْ عَدَدُ أَفْعَالِ الْيَقِينِ؟',
          kind: 'mcq',
          prompt: 'How many أَفْعَال الْيَقِين are counted in this chapter?',
          options: ['سَبْعَةٌ', 'سِتَّةٌ', 'ثَمَانِيَةٌ', 'خَمْسَةٌ'],
          correct: 0,
        },
        {
          title: 'كَمْ عَدَدُ أَفْعَالِ الظَّنِّ؟',
          kind: 'mcq',
          prompt: 'How many أَفْعَال الظَّنّ (الرُّجْحَان) are counted in this chapter?',
          options: ['ثَمَانِيَةٌ', 'سَبْعَةٌ', 'سِتَّةٌ', 'تِسْعَةٌ'],
          correct: 0,
        },
        {
          title: 'اسْمٌ آخَرُ لِأَفْعَالِ الظَّنِّ',
          kind: 'mcq',
          prompt: 'أَفْعَال الظَّنّ are also called:',
          options: ['أَفْعَالُ الرُّجْحَانِ', 'أَفْعَالُ الْجَارِحَةِ', 'أَفْعَالُ الْيَقِينِ', 'أَفْعَالُ التَّحْوِيلِ'],
          correct: 0,
        },
        {
          title: 'تَعَلَّمْ فِي قَائِمَةِ الْيَقِينِ',
          kind: 'mcq',
          prompt: 'In the list of أَفْعَال الْيَقِين, what does تَعَلَّمْ mean?',
          options: ['اعْلَمْ — "know for certain", not "learn"', 'تَدَرَّبْ — "train yourself at it"', 'دَرَسَ — "he studied"', 'عَلَّمَ غَيْرَهُ — "he taught someone else"'],
          correct: 0,
        },
        {
          title: 'وَجَدَ فِي الْآيَةِ',
          kind: 'mcq',
          prompt: '﴿وَإِنْ وَجَدْنَا أَكْثَرَهُمْ لَفَاسِقِينَ﴾ — وَجَدَ here belongs to:',
          options: ['أَفْعَالُ الْيَقِينِ', 'أَفْعَالُ الظَّنِّ', 'أَفْعَالُ التَّحْوِيلِ', 'أَفْعَالُ الْجَارِحَةِ'],
          correct: 0,
        },
        {
          title: 'مَا يَشْتَرِكُ فِيهِ أَفْعَالُ الْقُلُوبِ',
          kind: 'mcq',
          prompt: 'What do all أَفْعَال الْقُلُوب have in common?',
          options: ['That their two مَفْعُولَانِ were originally a مُبْتَدَأٌ وَخَبَرٌ', 'That they are all أَفْعَال أَمْر', 'That none of them ever accepts تَصْرِيف', 'That they always come in the صِيغَة الْمَبْنِيّ لِلْمَجْهُول'],
          correct: 0,
        },
        {
          title: 'إِعْرَابُ مَفْعُولَيْ ظَنَّ',
          kind: 'mcq',
          prompt: 'In ظَنَنْتُ الْجَوَّ صَافِيًا, what is the إِعْرَاب of الْجَوَّ and صَافِيًا?',
          options: ['Both مَنْصُوب — مَفْعُولٌ أَوَّلُ and مَفْعُولٌ ثَانٍ', 'الْجَوَّ مَنْصُوب, صَافِيًا مَرْفُوع as its خَبَر', 'الْجَوَّ مَرْفُوع as مُبْتَدَأ, صَافِيًا مَنْصُوب', 'Both still مَرْفُوع, as مُبْتَدَأٌ وَخَبَرٌ'],
          correct: 0,
        },
        {
          title: 'أَصْلُ مَفْعُولَيْ عَلِمَ',
          kind: 'mcq',
          prompt: 'عَلِمْتُ زَيْدًا قَائِمًا — what was this كَلَام before عَلِمَ entered it?',
          options: ['زَيْدٌ قَائِمٌ, a مُبْتَدَأٌ وَخَبَرٌ', 'زَيْدًا قَائِمًا, already both مَنْصُوب', 'قَامَ زَيْدٌ, a جُمْلَة فِعْلِيَّة', 'Nothing — the two words never formed a جُمْلَة'],
          correct: 0,
        },
        {
          title: 'الِاقْتِصَارُ',
          kind: 'mcq',
          prompt: 'الِاقْتِصَار, in deleting one مَفْعُول of a فِعْل قَلْب, is:',
          options: ['Not permitted, because no قَرِينَة recovers the other', 'Permitted in every case', 'Obligatory in every جُمْلَة', 'Specific to أَفْعَال الْيَقِين alone'],
          correct: 0,
        },
        {
          title: 'لِمَاذَا يَمْتَنِعُ الِاقْتِصَارُ',
          kind: 'mcq',
          prompt: 'Why is dropping only ONE مَفْعُول of a فِعْل قَلْب forbidden?',
          options: ['Because the two were a مُبْتَدَأٌ وَخَبَرٌ — you cannot name a subject and withhold its خَبَر', 'Because a فِعْل قَلْب may never lose any مَفْعُول whatsoever', 'Because the second مَفْعُول is always a whole جُمْلَة', 'Because الِاقْتِصَار belongs to أَفْعَال التَّحْوِيل instead'],
          correct: 0,
        },
        {
          title: 'تَقْدِيرُ الِاخْتِصَارِ',
          kind: 'mcq',
          prompt: '﴿أَيْنَ شُرَكَائِيَ الَّذِينَ كُنْتُمْ تَزْعُمُونَ﴾ — what is the implied wording?',
          options: ['تَزْعُمُونَهُمْ شُرَكَائِي', 'تَزْعُمُونَ شُرَكَائِي أَنْتُمْ', 'زَعَمْتُمْ أَنْ لَا شُرَكَاءَ', 'تَزْعُمُونَ أَنَّكُمْ شُرَكَاءُ'],
          correct: 0,
        },
        {
          title: 'أَلَمْ تَرَ',
          kind: 'mcq',
          prompt: 'أَلَمْ تَرَ carries the meaning of:',
          options: ['أَلَمْ تَعْلَمْ, with a shade of تَعَجُّب', 'أَلَمْ تَسْمَعْ', 'أَلَمْ تَقُلْ', 'أَلَمْ تَذْهَبْ'],
          correct: 0,
        },
        {
          title: 'لِمَاذَا تُعَبِّرُ الرُّؤْيَةُ عَنِ الْعِلْمِ؟',
          kind: 'mcq',
          prompt: 'Why is الْعِلْم expressed through الرُّؤْيَة in أَلَمْ تَرَ?',
          options: ['Because الْبَصَر is the strongest cause of الْعِلْم', 'Because الرُّؤْيَة and الْعِلْم are always exact synonyms', 'Because أَلَمْ تَرَ is a فِعْل أَمْر', 'Because there is no relation at all between الرُّؤْيَة and الْعِلْم'],
          correct: 0,
        },
        {
          title: 'أَرَأَيْتَ، أَرَأَيْتِ، أَرَأَيْتُمْ',
          kind: 'mcq',
          prompt: 'أَرَأَيْتَ، أَرَأَيْتِ، أَرَأَيْتُمْ — what is it that changes across these three?',
          options: ['The ضَمِير مَرْفُوع, tracking the مُخَاطَب', 'The فِعْل itself, root and all', 'The meaning, completely, in each صِيغَة', 'Nothing at all changes'],
          correct: 0,
        },
        {
          title: 'لَا تَعْلَمُونَ شَيْئًا',
          kind: 'mcq',
          prompt: '﴿لَا تَعْلَمُونَ شَيْئًا﴾ carries the meaning of:',
          options: ['لَا تَعْرِفُونَ', 'لَا تَظُنُّونَ', 'لَا تَتَّهِمُونَ', 'لَا تَتَحَوَّلُونَ'],
          correct: 0,
        },
        {
          title: 'لَاتَّخَذْتَ عَلَيْهِ أَجْرًا',
          kind: 'mcq',
          prompt: '﴿لَاتَّخَذْتَ عَلَيْهِ أَجْرًا﴾ carries the meaning of:',
          options: ['طَلَبْتَ', 'ظَنَنْتَ', 'وَجَدْتَ', 'عَرَفْتَ'],
          correct: 0,
        },
        {
          title: 'وَأَلْفَيَا سَيِّدَهَا لَدَى الْبَابِ',
          kind: 'mcq',
          prompt: '﴿وَأَلْفَيَا سَيِّدَهَا لَدَى الْبَابِ﴾ carries the meaning of:',
          options: ['صَادَفَا', 'ظَنَّا', 'اتَّهَمَا', 'طَلَبَا'],
          correct: 0,
        },
        {
          title: 'وَجَدْتُ الضَّالَّةَ',
          kind: 'mcq',
          prompt: 'وَجَدْتُ الضَّالَّةَ carries the meaning of:',
          options: ['أَصَبْتُهَا', 'ظَنَنْتُهَا', 'عَرَفْتُهَا بِالِاسْمِ', 'تَحَوَّلْتُ إِلَيْهَا'],
          correct: 0,
        },
        {
          title: 'رَأَيْتُ زَيْدًا',
          kind: 'mcq',
          prompt: 'رَأَيْتُ زَيْدًا, in the sense of أَبْصَرْتُهُ — how many مَفَاعِيل does رَأَى take here?',
          options: ['مَفْعُولًا وَاحِدًا', 'مَفْعُولَيْنِ', 'ثَلَاثَةَ مَفَاعِيلَ', 'It takes none'],
          correct: 0,
        },
        {
          title: 'لِمَاذَا سُمِّيَتْ أَفْعَالَ الْقُلُوبِ؟',
          kind: 'mcq',
          prompt: 'أَفْعَال الْقُلُوب are named for the heart because:',
          options: ['They indicate a قَلْبِيّ judgement such as الْيَقِين or الظَّنّ', 'Their government moves from الْقَلْب to الْجَوَارِح', 'They need no فَاعِل at all', 'They only ever occur مَبْنِيَّة لِلْمَجْهُول'],
          correct: 0,
        },
        {
          title: 'جَعَلَ فِي الْآيَةِ',
          kind: 'mcq',
          prompt: 'جَعَلَ in ﴿وَجَعَلُوا الْمَلَائِكَةَ ... إِنَاثًا﴾ belongs to:',
          options: ['أَفْعَالُ الظَّنِّ', 'أَفْعَالُ الْيَقِينِ', 'أَفْعَالُ الْجَارِحَةِ', 'الْأَفْعَالُ اللَّازِمَةُ'],
          correct: 0,
        },
        {
          title: 'الْفَرْقُ بَيْنَ الِاخْتِصَارِ وَالِاقْتِصَارِ',
          kind: 'mcq',
          prompt: 'What is the practical difference between الِاخْتِصَار and الِاقْتِصَار?',
          options: ['الِاخْتِصَار drops both with a قَرِينَة; الِاقْتِصَار drops one without a قَرِينَة', 'الِاخْتِصَار drops one with a قَرِينَة; الِاقْتِصَار drops both without a قَرِينَة', 'There is no difference between the two', 'الِاخْتِصَار belongs to the مَاضِي and الِاقْتِصَار to the مُضَارِع'],
          correct: 0,
        },
        {
          title: 'تَرْكِيب: أَمْثِلَةٌ قُرْآنِيَّةٌ',
          kind: 'tarkeeb',
          instruction: 'Classify each فِعْل قَلْب in these آيَات: الْيَقِين or الظَّنّ?',
          source: '﴿وَإِنْ وَجَدْنَا أَكْثَرَهُمْ لَفَاسِقِينَ﴾ / ﴿وَيَحْسَبُونَ أَنَّهُمْ مُهْتَدُونَ﴾ / ﴿وَجَعَلُوا الْمَلَائِكَةَ ... إِنَاثًا﴾',
          words: ['وَجَدْنَا', 'يَحْسَبُونَ', 'جَعَلُوا'],
          labels: ['الْيَقِين', 'الظَّنّ', 'الظَّنّ'],
          distractors: ['التَّحْوِيل'],
        },
        {
          title: 'تَرْكِيب: بِمَعْنَى الْقَلْبِ أَمْ خَارِجَ مَعْنَاهُ؟',
          kind: 'tarkeeb',
          instruction: 'Classify each usage: بِمَعْنَى الْقَلْبِ (two مَفَاعِيل) or خَارِجَ مَعْنَى الْقَلْبِ (one)?',
          source: 'وَجَدْتُ الضَّالَّةَ / ﴿وَإِنْ وَجَدْنَا أَكْثَرَهُمْ لَفَاسِقِينَ﴾ / رَأَيْتُ زَيْدًا / ﴿وَيَحْسَبُونَ أَنَّهُمْ مُهْتَدُونَ﴾',
          words: ['وَجَدْتُ', 'وَجَدْنَا', 'رَأَيْتُ', 'يَحْسَبُونَ'],
          labels: ['خَارِجَ مَعْنَى الْقَلْبِ', 'بِمَعْنَى الْقَلْبِ', 'خَارِجَ مَعْنَى الْقَلْبِ', 'بِمَعْنَى الْقَلْبِ'],
          distractors: ['فِعْلُ تَحْوِيلٍ'],
        },
        {
          title: 'تَرْكِيب: الِاخْتِصَارُ أَمِ الِاقْتِصَارُ؟',
          kind: 'tarkeeb',
          instruction: 'Classify each deletion: اخْتِصَار (permitted) or اقْتِصَار (not permitted)?',
          source: '﴿أَيْنَ شُرَكَائِيَ الَّذِينَ كُنْتُمْ تَزْعُمُونَ﴾ / ظَنَنْتُ زَيْدًا',
          words: ['تَزْعُمُونَ', 'ظَنَنْتُ'],
          labels: ['اخْتِصَار', 'اقْتِصَار'],
          distractors: ['إِلْغَاء'],
        },
        {
          title: 'تَرْكِيب: عَدَدُ الْمَفَاعِيلِ بَعْدَ تَغَيُّرِ الْمَعْنَى',
          kind: 'tarkeeb',
          instruction: 'Classify each فِعْل by its number of مَفَاعِيل in this usage.',
          source: '﴿لَا تَعْلَمُونَ شَيْئًا﴾ / ﴿وَأَلْفَيَا سَيِّدَهَا لَدَى الْبَابِ﴾ / ﴿وَإِنْ وَجَدْنَا أَكْثَرَهُمْ لَفَاسِقِينَ﴾ / ﴿وَيَحْسَبُونَ أَنَّهُمْ مُهْتَدُونَ﴾',
          words: ['تَعْلَمُونَ', 'أَلْفَيَا', 'وَجَدْنَا', 'يَحْسَبُونَ'],
          labels: ['مَفْعُولٌ وَاحِدٌ', 'مَفْعُولٌ وَاحِدٌ', 'مَفْعُولَانِ', 'مَفْعُولَانِ'],
          distractors: ['ثَلَاثَةُ مَفَاعِيلَ'],
        },
        {
          title: 'تَرْكِيب: تَصْنِيفٌ عَامٌّ لِأَفْعَالِ الْقُلُوبِ',
          kind: 'tarkeeb',
          instruction: 'Classify each فِعْل: أَفْعَالُ الْيَقِينِ or أَفْعَالُ الظَّنِّ?',
          source: 'دَرَى / تَعَلَّمْ / زَعَمَ / خَالَ',
          words: ['دَرَى', 'تَعَلَّمْ', 'زَعَمَ', 'خَالَ'],
          labels: ['الْيَقِين', 'الْيَقِين', 'الظَّنّ', 'الظَّنّ'],
          distractors: ['الْجَارِحَة'],
        },
        {
          title: 'تَرْكِيب: إِعْرَابُ مَفْعُولَيِ الْقَلْبِ',
          kind: 'tarkeeb',
          instruction: 'Identify the role of each word under the government of the فِعْل قَلْب.',
          source: 'عَلِمْتُ زَيْدًا قَائِمًا',
          words: ['عَلِمْتُ', 'زَيْدًا', 'قَائِمًا'],
          labels: ['فِعْلٌ وَفَاعِلُهُ', 'مَفْعُولٌ أَوَّلُ مَنْصُوبٌ', 'مَفْعُولٌ ثَانٍ مَنْصُوبٌ'],
          distractors: ['خَبَرٌ مَرْفُوعٌ'],
        },
      ],
    },

    // ---------------------------------------------------------------- L3
    {
      id: 'l3',
      title: 'أَفْعَالُ التَّحْوِيلِ',
      subtitle: 'Verbs of Conversion — التَّحْوِيل, the three-مَفْعُول فِعْل, and مَا يَسُدُّ مَسَدَّ الْمَفْعُولَيْنِ',
      concepts: [
        {
          heading: 'أَفْعَالُ التَّحْوِيلِ: تَعْرِيفُهَا وَأَمْثِلَتُهَا',
          tldr: 'أَفْعَالُ التَّحْوِيلِ are the six أَفْعَال carrying the sense of صَيَّرَ; like أَفْعَال الْقُلُوب they leave two مَنْصُوبَيْنِ that began as مُبْتَدَأٌ وَخَبَرٌ.',
          body: `<bdi>أَفْعَالُ التَّحْوِيلِ</bdi> are the second branch of the two-object class met in Lesson 1 — every فِعْل bearing the sense of <bdi>صَيَّرَ</bdi>, to turn one thing into another. They are six: <bdi>صَيَّرَ</bdi>، <bdi>رَدَّ</bdi>، <bdi>تَرَكَ</bdi>، <bdi>تَخِذَ</bdi>، <bdi>جَعَلَ</bdi>، <bdi>وَهَبَ</bdi>. They sit beside أَفْعَال الْقُلُوب because their two مَفْعُولَانِ have the same origin, a <bdi>مُبْتَدَأٌ وَخَبَرٌ</bdi>, and the same إِعْرَاب, both مَنْصُوب. The difference is what the فِعْل reports. A فِعْل قَلْب reports a judgement formed in the heart, while a فِعْل تَحْوِيل reports a change actually worked on the thing itself.`,
          examples: [
            { ar: '﴿وَاتَّخَذَ اللَّهُ إِبْرَاهِيمَ خَلِيلًا﴾', en: 'and Allah took Ibrāhīm as an intimate friend', note: 'بِمَعْنَى صَيَّرَ — إِبْرَاهِيمَ is the first مَفْعُول, مَنْصُوب by فَتْحَة with no تَنْوِين since it is مَمْنُوع مِنَ الصَّرْفِ, and خَلِيلًا the second' },
            { ar: '﴿فَجَعَلْنَاهُ هَبَاءً مَنْثُورًا﴾', en: 'and We made it scattered dust', note: 'the attached هُ is the first مَفْعُول and هَبَاءً the second, مَنْصُوب — a real change of state, so تَحْوِيل and not ظَنّ' },
            { ar: '﴿يَرُدُّونَكُمْ ... كُفَّارًا﴾', en: 'they would turn you back into disbelievers', note: 'رَدَّ بِمَعْنَى صَيَّرَ — كُمْ is the first مَفْعُول and كُفَّارًا the second, مَنْصُوب by فَتْحَة' },
          ],
          exercise: {
            prompt: `جَعَلَ and وَهَبَ each appear in TWO different lists across this module. Which two classes do they straddle?`,
            kind: 'mcq',
            options: ['أَفْعَالُ الظَّنِّ (الْقَلْبِ) وَأَفْعَالُ التَّحْوِيلِ', 'أَفْعَالُ الْيَقِينِ وَأَفْعَالُ الْجَارِحَةِ', 'اللَّازِمُ وَالْمُتَعَدِّي', 'التَّعْلِيقُ وَالْإِلْغَاءُ'],
            correct: 0,
          },
        },
        {
          heading: 'أَفْعَالُ التَّحْوِيلِ خَارِجَ مَعْنَى التَّحْوِيلِ',
          tldr: 'Outside the sense of صَيَّرَ, one of these أَفْعَال drops to a single مَفْعُول — the same rule that governs أَفْعَال الْقُلُوب.',
          body: `The second مَفْعُول rides on the sense of تَحْوِيل, so it leaves when that sense leaves. Three Qurʾānic cases show it: (1) <bdi>﴿إِنِّي تَرَكْتُ مِلَّةَ قَوْمٍ لَا يُؤْمِنُونَ بِاللَّهِ﴾</bdi>, where تَرَكَ is plain abandoning, (2) <bdi>﴿ثُمَّ يُرَدُّ إِلَىٰ رَبِّهِ﴾</bdi>, where رَدَّ means <bdi>يُصَارُ</bdi>, a plain returning, (3) <bdi>﴿وَجَعَلَ لَكُمُ السَّمْعَ وَالْأَبْصَارَ وَالْأَفْئِدَةَ﴾</bdi>, where جَعَلَ means <bdi>خَلَقَ</bdi>. In the third, the three coordinated أَسْمَاء are one مَفْعُول with two words مَعْطُوفَة on it, not three مَفَاعِيل. Count مَنْصُوبَات, then ask which of them the فِعْل actually governs.`,
          examples: [
            { ar: '﴿إِنِّي تَرَكْتُ مِلَّةَ قَوْمٍ لَا يُؤْمِنُونَ بِاللَّهِ﴾', en: 'indeed I have left the creed of a people who do not believe in Allah', note: 'تَرَكَ outside تَحْوِيل — مِلَّةَ is the single مَفْعُول, مَنْصُوب and مُضَاف to قَوْمٍ' },
            { ar: '﴿وَجَعَلَ لَكُمُ السَّمْعَ وَالْأَبْصَارَ وَالْأَفْئِدَةَ﴾', en: 'and He made for you hearing, sight and hearts', note: 'جَعَلَ = خَلَقَ, so one مَفْعُول: السَّمْعَ مَنْصُوب, with الْأَبْصَارَ and الْأَفْئِدَةَ مَعْطُوفَة on it' },
            { ar: 'صَيَّرَ الْخَيَّاطُ الثَّوْبَ قَمِيصًا', en: 'the tailor turned the cloth into a shirt', note: 'the contrast case — here the sense of صَيَّرَ is present, so a second مَنْصُوب, قَمِيصًا, appears after الثَّوْبَ' },
          ],
          exercise: {
            prompt: `﴿وَجَعَلَ لَكُمُ السَّمْعَ وَالْأَبْصَارَ وَالْأَفْئِدَةَ﴾ — جَعَلَ here means خَلَقَ. Does it take one مَفْعُول or two, and why؟`,
            kind: 'mcq',
            options: ['One — because the sense of التَّحْوِيل is absent here', 'Two — because جَعَلَ is a فِعْل تَحْوِيل wherever it occurs', 'Three — because three أَسْمَاء follow it', 'None — because it is لَازِم in this آيَة'],
            correct: 0,
          },
        },
        {
          heading: 'الْفِعْلُ الْآخِذُ لِثَلَاثَةِ مَفَاعِيلَ',
          tldr: 'Only a فِعْل قَلْب made causative reaches three مَفَاعِيل, and its second and third are the old مُبْتَدَأٌ وَخَبَرٌ.',
          body: `Three مَفَاعِيل is the ceiling, and only one class of فِعْل reaches it: a <bdi>فِعْلُ قَلْبٍ</bdi> that has been made causative, most often by a هَمْزَة on the front. So <bdi>رَأَى</bdi> reaches two مَفَاعِيل and <bdi>أَرَى</bdi> reaches three, the extra one being the person made to know. The family is seven: <bdi>أَرَى</bdi>، <bdi>أَعْلَمَ</bdi>، <bdi>نَبَّأَ</bdi>، <bdi>أَنْبَأَ</bdi>، <bdi>خَبَّرَ</bdi>، <bdi>أَخْبَرَ</bdi>، <bdi>حَدَّثَ</bdi>. The second and third مَفْعُولَانِ keep the property they had as a two-object pair: they were a <bdi>مُبْتَدَأٌ وَخَبَرٌ</bdi>. The first مَفْعُول was never part of that pair. No فِعْل تَحْوِيل and no فِعْل جَارِحَة ever reaches three.`,
          examples: [
            { ar: '﴿كَذَٰلِكَ يُرِيهِمُ اللَّهُ أَعْمَالَهُمْ حَسَرَاتٍ عَلَيْهِمْ﴾', en: 'thus does Allah show them their deeds as regrets upon them', note: 'اللَّهُ is the مَرْفُوع فَاعِل; هِمْ is the first مَفْعُول, أَعْمَالَهُمْ the second مَنْصُوب, and حَسَرَاتٍ the third, مَنْصُوب by كَسْرَة as a جَمْع مُؤَنَّث سَالِم' },
            { ar: 'أَعْلَمْتُ زَيْدًا عَمْرًا مُسَافِرًا', en: 'I informed Zayd that ʿAmr was travelling', note: 'أَعْلَمَ is the causative of عَلِمَ — زَيْدًا is the first مَفْعُول, while عَمْرًا مُسَافِرًا were عَمْرٌو مُسَافِرٌ before the فِعْل entered' },
            { ar: 'عَلِمْتُ عَمْرًا مُسَافِرًا', en: 'I knew ʿAmr to be travelling', note: 'the same pair without the هَمْزَة — عَلِمَ reaches only two, which shows the third مَفْعُول is bought by التَّعْدِيَة, not by the root' },
          ],
          exercise: {
            prompt: `﴿يُرِيهِمُ اللَّهُ أَعْمَالَهُمْ حَسَرَاتٍ﴾ takes three مَفَاعِيل. Which class of فِعْل can ever reach three?`,
            kind: 'mcq',
            options: ['فِعْلُ الْقَلْبِ alone', 'Any فِعْل مُتَعَدٍّ whatsoever', 'فِعْلُ التَّحْوِيلِ alone', 'A فِعْل لَازِم joined to a حَرْف جَرّ'],
            correct: 0,
          },
        },
        {
          heading: 'مَا يَسُدُّ مَسَدَّ مَفْعُولَيْ فِعْلِ الْقَلْبِ',
          tldr: 'An اسْم مُؤَوَّل or a whole جُمْلَة can fill both مَفْعُول slots of a فِعْل قَلْب at once — يَسُدُّ مَسَدَّهُمَا.',
          body: `The two مَفْعُولَانِ do not always appear as two separate أَسْمَاء مَنْصُوبَة. Two things can take their place together (<bdi>يَسُدُّ مَسَدَّهُمَا</bdi>): (1) an <bdi>اسْمٌ مُؤَوَّلٌ</bdi>, built from أَنَّ and what follows it, (2) a whole <bdi>جُمْلَة</bdi>. In both cases you should still be able to read the filler back as a مُبْتَدَأٌ وَخَبَرٌ, which is the test that the slot really is the two-مَفْعُول slot. This is also the doorway to the next lesson. Once a جُمْلَة sits in that slot, the question becomes whether the فِعْل can still reach it, and that question is التَّعْلِيق.`,
          examples: [
            { ar: '﴿وَاعْلَمُوا أَنَّ اللَّهَ مَعَ الْمُتَّقِينَ﴾', en: 'and know that Allah is with those who fear Him', note: 'أَنَّ اللَّهَ مَعَ الْمُتَّقِينَ is an اسْم مُؤَوَّل filling both مَفْعُول slots of اعْلَمُوا at once' },
            { ar: '﴿وَاللَّهُ يَشْهَدُ إِنَّ الْمُنَافِقِينَ لَكَاذِبُونَ﴾', en: 'and Allah bears witness that the hypocrites are liars', note: 'here a whole جُمْلَة fills the slot; note the كَسْرَة on إِنَّ and the لَام on لَكَاذِبُونَ — the wording is untouched by يَشْهَدُ' },
          ],
          exercise: {
            prompt: `In ﴿وَاعْلَمُوا أَنَّ اللَّهَ مَعَ الْمُتَّقِينَ﴾, اعْلَمُوا is a فِعْل قَلْب needing two مَفَاعِيل — yet only one اسْم مُؤَوَّل follows it. How is that possible?`,
            kind: 'mcq',
            options: ['The اسْم مُؤَوَّل alone stands in for both مَفْعُولَيْنِ together', 'اعْلَمُوا is لَازِم here and needs no مَفْعُولَيْنِ', 'One of the two مَفْعُولَيْنِ has been deleted with no قَرِينَة', 'أَنَّ اللَّهَ مَعَ الْمُتَّقِينَ is a single مَفْعُول and the other is simply absent'],
            correct: 0,
          },
        },
      ],
      quiz: [
        {
          q: 'How many أَفْعَال التَّحْوِيل were listed?',
          options: ['سِتَّةٌ', 'خَمْسَةٌ', 'سَبْعَةٌ', 'ثَمَانِيَةٌ'],
          correct: 0,
        },
        {
          q: 'Which two أَفْعَال appear in both أَفْعَال الظَّنّ and أَفْعَال التَّحْوِيل؟',
          options: ['جَعَلَ وَوَهَبَ', 'ظَنَّ وَصَيَّرَ', 'رَدَّ وَتَرَكَ', 'زَعَمَ وَتَخِذَ'],
          correct: 0,
        },
        {
          q: '﴿ثُمَّ يُرَدُّ إِلَىٰ رَبِّهِ﴾, in the sense of يُصَارُ — how many مَفَاعِيل does رَدَّ govern here?',
          options: ['مَفْعُولًا وَاحِدًا', 'مَفْعُولَيْنِ', 'ثَلَاثَةَ مَفَاعِيلَ', 'It governs none'],
          correct: 0,
        },
        {
          q: 'A فِعْل taking three مَفَاعِيل is always:',
          options: ['فِعْلَ قَلْبٍ', 'فِعْلَ تَحْوِيلٍ', 'فِعْلَ جَارِحَةٍ', 'فِعْلًا لَازِمًا'],
          correct: 0,
        },
        {
          q: 'What can يَسُدُّ مَسَدَّ the two مَفْعُولَانِ of a فِعْل قَلْب؟',
          options: ['الِاسْمُ الْمُؤَوَّلُ أَوِ الْجُمْلَةُ', 'الْحَالُ أَوِ التَّمْيِيزُ', 'الْمَفْعُولُ الْمُطْلَقُ وَحْدَهُ', 'Nothing can stand in for them'],
          correct: 0,
        },
        {
          q: '﴿وَاتَّخَذَ اللَّهُ إِبْرَاهِيمَ خَلِيلًا﴾ — اتَّخَذَ here is a فِعْل:',
          options: ['تَحْوِيل', 'قَلْب مِنْ أَفْعَالِ الْيَقِينِ', 'لَازِم', 'جَارِحَة'],
          correct: 0,
        },
      ],
      bank: [
        {
          title: 'مَعْنَى أَفْعَالِ التَّحْوِيلِ',
          kind: 'mcq',
          prompt: 'أَفْعَال التَّحْوِيل all carry the sense of:',
          options: ['صَيَّرَ', 'ظَنَّ', 'عَلِمَ', 'وَجَدَ'],
          correct: 0,
        },
        {
          title: 'مِنْ أَفْعَالِ التَّحْوِيلِ',
          kind: 'mcq',
          prompt: 'صَيَّرَ، رَدَّ، تَرَكَ belong to:',
          options: ['أَفْعَالُ التَّحْوِيلِ', 'أَفْعَالُ الْيَقِينِ', 'أَفْعَالُ الْجَارِحَةِ', 'أَفْعَالُ الظَّنِّ وَحْدَهَا'],
          correct: 0,
        },
        {
          title: 'مَفْعُولَا اتَّخَذَ',
          kind: 'mcq',
          prompt: '﴿وَاتَّخَذَ اللَّهُ إِبْرَاهِيمَ خَلِيلًا﴾ — the two مَفْعُولَانِ of اتَّخَذَ are:',
          options: ['إِبْرَاهِيمَ وَخَلِيلًا', 'اللَّهُ وَإِبْرَاهِيمَ', 'خَلِيلًا وَحْدَهُ', 'It has no مَفْعُول'],
          correct: 0,
        },
        {
          title: 'إِعْرَابُ إِبْرَاهِيمَ',
          kind: 'mcq',
          prompt: 'In ﴿وَاتَّخَذَ اللَّهُ إِبْرَاهِيمَ خَلِيلًا﴾, why does إِبْرَاهِيمَ carry a bare فَتْحَة with no تَنْوِين?',
          options: ['Because it is مَنْصُوب and مَمْنُوع مِنَ الصَّرْفِ', 'Because it is مَجْرُور by an unstated حَرْف جَرّ', 'Because it is مَبْنِيّ and takes no إِعْرَاب', 'Because it is the فَاعِل of اتَّخَذَ'],
          correct: 0,
        },
        {
          title: 'تَرَكَ خَارِجَ مَعْنَى التَّحْوِيلِ',
          kind: 'mcq',
          prompt: '﴿إِنِّي تَرَكْتُ مِلَّةَ قَوْمٍ لَا يُؤْمِنُونَ بِاللَّهِ﴾ — تَرَكَ here is:',
          options: ['Outside the sense of التَّحْوِيل, so it takes one مَفْعُول', 'Inside the sense of التَّحْوِيل, so it takes two', 'A فِعْل لَازِم reaching no مَفْعُول', 'A فِعْل قَلْب of الْيَقِين'],
          correct: 0,
        },
        {
          title: 'يُرَدُّ إِلَىٰ رَبِّهِ',
          kind: 'mcq',
          prompt: '﴿ثُمَّ يُرَدُّ إِلَىٰ رَبِّهِ﴾ carries the meaning of:',
          options: ['يُصَارُ', 'يُصَيَّرُ', 'يُتْرَكُ', 'يُتَّخَذُ'],
          correct: 0,
        },
        {
          title: 'السَّمْعُ وَالْأَبْصَارُ وَالْأَفْئِدَةُ',
          kind: 'mcq',
          prompt: '﴿وَجَعَلَ لَكُمُ السَّمْعَ وَالْأَبْصَارَ وَالْأَفْئِدَةَ﴾ — جَعَلَ here carries the meaning of:',
          options: ['خَلَقَ أَوْ أَوْجَدَ', 'صَيَّرَ', 'ظَنَّ', 'تَرَكَ'],
          correct: 0,
        },
        {
          title: 'ثَلَاثَةُ مَنْصُوبَاتٍ أَمْ مَفْعُولٌ وَاحِدٌ؟',
          kind: 'mcq',
          prompt: 'Three مَنْصُوبَات follow جَعَلَ in ﴿وَجَعَلَ لَكُمُ السَّمْعَ وَالْأَبْصَارَ وَالْأَفْئِدَةَ﴾. How many مَفَاعِيل is that?',
          options: ['One — الْأَبْصَارَ and الْأَفْئِدَةَ are مَعْطُوفَة on السَّمْعَ', 'Three — one مَفْعُول per مَنْصُوب', 'Two — the last two count as a single مَفْعُول', 'None — all three are أَحْوَال'],
          correct: 0,
        },
        {
          title: 'مِثَالٌ عَلَى ثَلَاثَةِ مَفَاعِيلَ',
          kind: 'mcq',
          prompt: 'Which of these four أَفْعَال is cited as taking three مَفَاعِيل?',
          options: ['أَرَى', 'رَأَى', 'وَهَبَ', 'صَيَّرَ'],
          correct: 0,
        },
        {
          title: 'أُسْرَةُ الثَّلَاثَةِ مَفَاعِيلَ',
          kind: 'mcq',
          prompt: 'Which set lists the أَفْعَال that reach three مَفَاعِيل?',
          options: ['أَرَى، أَعْلَمَ، نَبَّأَ، أَنْبَأَ، خَبَّرَ، أَخْبَرَ، حَدَّثَ', 'صَيَّرَ، رَدَّ، تَرَكَ، تَخِذَ، جَعَلَ، وَهَبَ', 'وَجَدَ، أَلْفَى، رَأَى، عَلِمَ، عَرَفَ، دَرَى', 'أَعْطَى، مَنَحَ، وَهَبَ، كَسَا'],
          correct: 0,
        },
        {
          title: 'مِنْ أَيْنَ جَاءَ الْمَفْعُولُ الثَّالِثُ؟',
          kind: 'mcq',
          prompt: 'رَأَى reaches two مَفَاعِيل and أَرَى reaches three. What buys the extra one?',
          options: ['التَّعْدِيَة بِالْهَمْزَةِ — the causative هَمْزَة adds the person made to know', 'The root itself, which always allowed three', 'A حَرْف جَرّ understood before the third', 'The third مَفْعُول is really a حَال'],
          correct: 0,
        },
        {
          title: 'عَدَدُ مَفَاعِيلِ يُرِي',
          kind: 'mcq',
          prompt: '﴿كَذَٰلِكَ يُرِيهِمُ اللَّهُ أَعْمَالَهُمْ حَسَرَاتٍ عَلَيْهِمْ﴾ — how many مَفَاعِيل does يُرِي take here?',
          options: ['ثَلَاثَةٌ', 'اثْنَانِ', 'وَاحِدٌ', 'None'],
          correct: 0,
        },
        {
          title: 'الْفَاعِلُ فِي آيَةِ الْحَسَرَاتِ',
          kind: 'mcq',
          prompt: 'In ﴿يُرِيهِمُ اللَّهُ أَعْمَالَهُمْ حَسَرَاتٍ﴾, which word is the مَرْفُوع فَاعِل?',
          options: ['اللَّهُ', 'the attached هِمْ', 'أَعْمَالَهُمْ', 'حَسَرَاتٍ'],
          correct: 0,
        },
        {
          title: 'إِعْرَابُ حَسَرَاتٍ',
          kind: 'mcq',
          prompt: 'In ﴿يُرِيهِمُ اللَّهُ أَعْمَالَهُمْ حَسَرَاتٍ﴾, what is the إِعْرَاب of حَسَرَاتٍ?',
          options: ['مَفْعُولٌ ثَالِثٌ مَنْصُوبٌ, its فَتْحَة replaced by كَسْرَة as a جَمْع مُؤَنَّث سَالِم', 'مَجْرُورٌ, since it ends in كَسْرَة', 'حَالٌ مَنْصُوبٌ from أَعْمَالَهُمْ', 'خَبَرٌ مَرْفُوعٌ of a deleted مُبْتَدَأ'],
          correct: 0,
        },
        {
          title: 'أَصْلُ الْمَفْعُولِ الثَّانِي وَالثَّالِثِ',
          kind: 'mcq',
          prompt: 'For a three-مَفْعُول فِعْل, the second and third مَفْعُولَانِ were originally:',
          options: ['مُبْتَدَأٌ وَخَبَرٌ', 'فَاعِلٌ وَنَائِبُهُ', 'حَالٌ وَتَمْيِيزٌ', 'مُضَافٌ وَمُضَافٌ إِلَيْهِ'],
          correct: 0,
        },
        {
          title: 'الِاسْمُ الْمُؤَوَّلُ',
          kind: 'mcq',
          prompt: 'After a فِعْل قَلْب, an اسْم مُؤَوَّل can:',
          options: ['stand in for both مَفْعُولَيْنِ at once', 'replace the فَاعِل and nothing else', 'be a حَرْف rather than an اسْم', 'never occur after أَفْعَال الْقُلُوب at all'],
          correct: 0,
        },
        {
          title: 'وَاعْلَمُوا أَنَّ اللَّهَ مَعَ الْمُتَّقِينَ',
          kind: 'mcq',
          prompt: '﴿وَاعْلَمُوا أَنَّ اللَّهَ مَعَ الْمُتَّقِينَ﴾ — what يَسُدُّ مَسَدَّ the two مَفْعُولَانِ of اعْلَمُوا?',
          options: ['أَنَّ اللَّهَ مَعَ الْمُتَّقِينَ, an اسْم مُؤَوَّل', 'اللَّهَ alone', 'الْمُتَّقِينَ alone', 'Nothing stands in for them'],
          correct: 0,
        },
        {
          title: 'وَاللَّهُ يَشْهَدُ إِنَّ الْمُنَافِقِينَ لَكَاذِبُونَ',
          kind: 'mcq',
          prompt: '﴿وَاللَّهُ يَشْهَدُ إِنَّ الْمُنَافِقِينَ لَكَاذِبُونَ﴾ — what يَسُدُّ مَسَدَّ the two مَفْعُولَانِ of يَشْهَدُ?',
          options: ['The whole جُمْلَة that follows it', 'An اسْم مُؤَوَّل', 'A مَفْعُول مُطْلَق', 'A حَال مَنْصُوب'],
          correct: 0,
        },
        {
          title: 'جَعَلَ مُشْتَرَكٌ',
          kind: 'mcq',
          prompt: 'جَعَلَ is listed under both of which two classes?',
          options: ['أَفْعَالُ الظَّنِّ وَأَفْعَالُ التَّحْوِيلِ', 'أَفْعَالُ الْيَقِينِ وَأَفْعَالُ التَّحْوِيلِ', 'اللَّازِمُ وَالْمُتَعَدِّي', 'التَّعْلِيقُ وَالْإِلْغَاءُ'],
          correct: 0,
        },
        {
          title: 'كَيْفَ تُمَيِّزُ جَعَلَ',
          kind: 'mcq',
          prompt: 'جَعَلَ takes two مَفْعُولَيْنِ as a فِعْل ظَنّ and as a فِعْل تَحْوِيل alike. How do you tell which is meant?',
          options: ['By the sense — "deemed" is ظَنّ, "rendered" is تَحْوِيل', 'By the tense of the فِعْل', 'By counting the مَنْصُوبَات after it', 'It is always ظَنّ when a مَنْصُوب follows'],
          correct: 0,
        },
        {
          title: 'وَهَبَ مُشْتَرَكٌ',
          kind: 'mcq',
          prompt: 'وَهَبَ is listed under both of which two classes?',
          options: ['أَفْعَالُ الظَّنِّ وَأَفْعَالُ التَّحْوِيلِ', 'أَفْعَالُ الْيَقِينِ وَالْجَارِحَةِ', 'اللَّازِمُ وَالْمُتَعَدِّي', 'التَّعْلِيقُ وَالْإِلْغَاءُ'],
          correct: 0,
        },
        {
          title: 'عَدَدُ مَفَاعِيلِ اتَّخَذَ',
          kind: 'mcq',
          prompt: 'How many مَفَاعِيل does اتَّخَذَ govern in ﴿وَاتَّخَذَ اللَّهُ إِبْرَاهِيمَ خَلِيلًا﴾?',
          options: ['اثْنَانِ', 'وَاحِدٌ', 'ثَلَاثَةٌ', 'None'],
          correct: 0,
        },
        {
          title: 'مَا لَا يَبْلُغُ ثَلَاثَةَ مَفَاعِيلَ',
          kind: 'mcq',
          prompt: 'A فِعْل reaching three مَفَاعِيل can never be:',
          options: ['فِعْلَ تَحْوِيلٍ أَوْ فِعْلَ جَارِحَةٍ', 'فِعْلَ قَلْبٍ', 'أَرَى or one of its family', 'مُتَعَدِّيًا at all'],
          correct: 0,
        },
        {
          title: 'وَجْهُ الشَّبَهِ بَيْنَ الْمَفْعُولَيْنِ',
          kind: 'mcq',
          prompt: 'What do the مَفْعُولَانِ of a فِعْل قَلْب share with the second and third مَفْعُولَانِ of a فِعْل like أَرَى?',
          options: ['Both pairs were originally a مُبْتَدَأٌ وَخَبَرٌ', 'Neither pair may ever be deleted', 'Neither pair may precede its فِعْل', 'There is no similarity between them'],
          correct: 0,
        },
        {
          title: 'تَرْكِيب: بِمَعْنَى التَّحْوِيلِ أَمْ لَا؟',
          kind: 'tarkeeb',
          instruction: 'Classify each فِعْل: بِمَعْنَى التَّحْوِيلِ or خَارِجَ مَعْنَى التَّحْوِيلِ?',
          source: '﴿وَاتَّخَذَ اللَّهُ إِبْرَاهِيمَ خَلِيلًا﴾ / ﴿إِنِّي تَرَكْتُ مِلَّةَ قَوْمٍ﴾ / ﴿ثُمَّ يُرَدُّ إِلَىٰ رَبِّهِ﴾ / ﴿وَجَعَلَ لَكُمُ السَّمْعَ وَالْأَبْصَارَ﴾',
          words: ['اتَّخَذَ', 'تَرَكْتُ', 'يُرَدُّ', 'جَعَلَ'],
          labels: ['بِمَعْنَى التَّحْوِيلِ', 'خَارِجَ مَعْنَى التَّحْوِيلِ', 'خَارِجَ مَعْنَى التَّحْوِيلِ', 'خَارِجَ مَعْنَى التَّحْوِيلِ'],
          distractors: ['فِعْلٌ لَازِمٌ'],
        },
        {
          title: 'تَرْكِيب: قَائِمَةُ أَفْعَالِ التَّحْوِيلِ',
          kind: 'tarkeeb',
          instruction: 'Classify each فِعْل: one of أَفْعَال التَّحْوِيل, or not?',
          source: 'صَيَّرَ / رَدَّ / دَرَى / عَلِمَ',
          words: ['صَيَّرَ', 'رَدَّ', 'دَرَى', 'عَلِمَ'],
          labels: ['مِنْ أَفْعَالِ التَّحْوِيلِ', 'مِنْ أَفْعَالِ التَّحْوِيلِ', 'لَيْسَ مِنْ أَفْعَالِ التَّحْوِيلِ', 'لَيْسَ مِنْ أَفْعَالِ التَّحْوِيلِ'],
          distractors: ['التَّعْلِيق'],
        },
        {
          title: 'تَرْكِيب: كَمْ مَفْعُولًا؟',
          kind: 'tarkeeb',
          instruction: 'Classify each فِعْل by its number of مَفَاعِيل in the context given.',
          source: '﴿وَاتَّخَذَ اللَّهُ إِبْرَاهِيمَ خَلِيلًا﴾ / ﴿يُرِيهِمُ اللَّهُ أَعْمَالَهُمْ حَسَرَاتٍ﴾ / ﴿إِنِّي تَرَكْتُ مِلَّةَ قَوْمٍ﴾',
          words: ['اتَّخَذَ', 'يُرِيهِمُ', 'تَرَكْتُ'],
          labels: ['مَفْعُولَانِ', 'ثَلَاثَةُ مَفَاعِيلَ', 'مَفْعُولٌ وَاحِدٌ'],
          distractors: ['لَا مَفْعُولَ لَهُ'],
        },
        {
          title: 'تَرْكِيب: مَا الَّذِي يَسُدُّ مَسَدَّ الْمَفْعُولَيْنِ؟',
          kind: 'tarkeeb',
          instruction: 'Classify each filler: اسْم مُؤَوَّل or جُمْلَة?',
          source: '﴿وَاعْلَمُوا أَنَّ اللَّهَ مَعَ الْمُتَّقِينَ﴾ / ﴿وَاللَّهُ يَشْهَدُ إِنَّ الْمُنَافِقِينَ لَكَاذِبُونَ﴾',
          words: ['أَنَّ اللَّهَ مَعَ الْمُتَّقِينَ', 'إِنَّ الْمُنَافِقِينَ لَكَاذِبُونَ'],
          labels: ['اسْمٌ مُؤَوَّلٌ', 'جُمْلَةٌ'],
          distractors: ['حَالٌ'],
        },
        {
          title: 'تَرْكِيب: أَفْعَالٌ مُشْتَرَكَةٌ',
          kind: 'tarkeeb',
          instruction: 'Classify each فِعْل: أَفْعَالُ الظَّنِّ, أَفْعَالُ التَّحْوِيلِ, or both?',
          source: 'جَعَلَ / وَهَبَ / زَعَمَ / صَيَّرَ',
          words: ['جَعَلَ', 'وَهَبَ', 'زَعَمَ', 'صَيَّرَ'],
          labels: ['كِلْتَاهُمَا', 'كِلْتَاهُمَا', 'الظَّنُّ وَحْدَهَا', 'التَّحْوِيلُ وَحْدَهَا'],
          distractors: ['الْيَقِينُ وَحْدَهَا'],
        },
        {
          title: 'تَرْكِيب: فِعْلُ قَلْبٍ أَمْ فِعْلُ تَحْوِيلٍ؟',
          kind: 'tarkeeb',
          instruction: 'Classify each فِعْل: فِعْلُ قَلْبٍ or فِعْلُ تَحْوِيلٍ?',
          source: '﴿يُرِيهِمُ اللَّهُ أَعْمَالَهُمْ حَسَرَاتٍ﴾ / ﴿وَاتَّخَذَ اللَّهُ إِبْرَاهِيمَ خَلِيلًا﴾ / ﴿فَجَعَلْنَاهُ هَبَاءً مَنْثُورًا﴾',
          words: ['يُرِيهِمُ', 'اتَّخَذَ', 'جَعَلْنَاهُ'],
          labels: ['فِعْلُ قَلْبٍ', 'فِعْلُ تَحْوِيلٍ', 'فِعْلُ تَحْوِيلٍ'],
          distractors: ['فِعْلُ جَارِحَةٍ'],
        },
      ],
    },

    // ---------------------------------------------------------------- L4
    {
      id: 'l4',
      title: 'التَّعْلِيقُ وَالْإِلْغَاءُ',
      subtitle: 'Suspension and Cancellation — how a فِعْل قَلْب loses its لَفْظِيّ government',
      concepts: [
        {
          heading: 'التَّعْلِيقُ: الْعَمَلُ مَحَلًّا لَا لَفْظًا',
          tldr: 'In التَّعْلِيق the فِعْل قَلْب still governs the جُمْلَة filling its مَفْعُول slot مَحَلًّا, but not لَفْظًا — the endings inside it do not change.',
          body: `When a <bdi>جُمْلَة</bdi> fills the slot of the two مَفْعُولَانِ, something has to give. The فِعْل cannot put a whole جُمْلَة into نَصْب, yet the جُمْلَة is still sitting where two مَنْصُوبَانِ belong. The settlement is that the فِعْل governs it <bdi>مَحَلًّا</bdi>, in grammatical position, and not <bdi>لَفْظًا</bdi>, in wording. That suspension of the wording-level government is <bdi>التَّعْلِيق</bdi>, and the clause is called a <bdi>جُمْلَةٌ مُعَلَّقٌ عَنْهَا الْعَمَلُ</bdi>. So the practical test is the endings. If the words after the فِعْل keep the إِعْرَاب they would have had on their own, the فِعْل has been مُعَلَّق.`,
          examples: [
            { ar: 'عَلِمْتُ لَزَيْدٌ قَائِمٌ', en: 'I knew that Zayd was indeed standing', note: 'without the لَام this would read عَلِمْتُ زَيْدًا قَائِمًا; لَامُ الِابْتِدَاءِ suspends عَلِمَ, so both stay مَرْفُوع as مُبْتَدَأٌ وَخَبَرٌ' },
            { ar: '﴿وَاللَّهُ يَشْهَدُ إِنَّ الْمُنَافِقِينَ لَكَاذِبُونَ﴾', en: 'and Allah bears witness that the hypocrites are liars', note: 'إِنَّ keeps its كَسْرَة and لَكَاذِبُونَ stays مَرْفُوع — يَشْهَدُ reaches the جُمْلَة مَحَلًّا only' },
          ],
          exercise: {
            prompt: `A فِعْل قَلْب's مَفْعُولَانِ are replaced by a whole جُمْلَة and التَّعْلِيق applies. Does the فِعْل still govern that جُمْلَة at all?`,
            kind: 'mcq',
            options: ['Yes — مَحَلًّا, but not لَفْظًا', 'No — it does not reach the جُمْلَة in any way', 'Yes — لَفْظًا and مَحَلًّا both', 'It cannot be told until the فِعْل itself is parsed'],
            correct: 0,
          },
        },
        {
          heading: 'مَا يَقْبَلُ التَّعْلِيقَ مِنَ الْأَفْعَالِ',
          tldr: 'التَّعْلِيق is not limited to أَفْعَال الْقُلُوب: any فِعْل of إِخْبَار or اسْتِفْهَام takes it, even one that governs a single مَفْعُول.',
          body: `أَفْعَالُ الْقُلُوبِ are the home of التَّعْلِيق, but they are not its limit. Every فِعْل resembling them takes it too — any فِعْل indicating <bdi>إِخْبَار</bdi> or <bdi>اسْتِفْهَام</bdi>, since both deal in a mental content the way a فِعْل قَلْب does. Two Qurʾānic cases show the resemblance: (1) <bdi>﴿لِيَبْلُوَكُمْ أَيُّكُمْ أَحْسَنُ عَمَلًا﴾</bdi> for إِخْبَار, (2) <bdi>﴿سَلْهُمْ أَيُّهُمْ بِذَٰلِكَ زَعِيمٌ﴾</bdi> for اسْتِفْهَام. Even the number of مَفَاعِيل is beside the point. A فِعْل that normally reaches only one مَفْعُول is suspended just the same when an اسْتِفْهَام opens the clause after it.`,
          examples: [
            { ar: '﴿لِيَبْلُوَكُمْ أَيُّكُمْ أَحْسَنُ عَمَلًا﴾', en: 'that He may test you as to which of you is best in deed', note: 'أَيُّكُمْ stays مَرْفُوع as مُبْتَدَأ and أَحْسَنُ مَرْفُوع as its خَبَر — يَبْلُو reaches them مَحَلًّا only' },
            { ar: '﴿سَلْهُمْ أَيُّهُمْ بِذَٰلِكَ زَعِيمٌ﴾', en: 'ask them which of them will guarantee that', note: 'a فِعْل of اسْتِفْهَام مُعَلَّق — أَيُّهُمْ مُبْتَدَأ مَرْفُوع and زَعِيمٌ خَبَر مَرْفُوع, both untouched by سَلْ' },
            { ar: '﴿فَلْيَنْظُرْ أَيُّهَا أَزْكَىٰ طَعَامًا﴾', en: 'let him look at which of them is purest in food', note: 'نَظَرَ reaches one مَفْعُول only, yet the اسْتِفْهَام suspends it all the same, leaving أَيُّهَا مَرْفُوع' },
          ],
          exercise: {
            prompt: `يَنْظُرُ normally takes only one مَفْعُول, yet ﴿فَلْيَنْظُرْ أَيُّهَا أَزْكَىٰ طَعَامًا﴾ shows it مُعَلَّق before a whole جُمْلَة. What licenses treating a single-مَفْعُول فِعْل this way؟`,
            kind: 'mcq',
            options: ['That the جُمْلَة after it opens with an اسْتِفْهَام', 'That يَنْظُرُ has permanently joined أَفْعَال الْقُلُوب', 'That the جُمْلَة after it is a جُمْلَة اسْمِيَّة مَنْسُوخَة', 'Nothing justifies it — the آيَة is an anomaly'],
            correct: 0,
          },
        },
        {
          heading: 'الْمُعَلِّقَاتُ السَّبْعُ',
          tldr: 'The seven الْمُعَلِّقَات share one trait: each has صَدْرُ الْكَلَامِ, a claim to open its own clause, so the فِعْل cannot reach past it.',
          body: `Seven items suspend the لَفْظِيّ government of a فِعْل قَلْب, and they are called <bdi>الْمُعَلِّقَات</bdi>: (1) <bdi>إِنْ النَّافِيَةُ</bdi>, (2) <bdi>مَا النَّافِيَةُ</bdi>, (3) <bdi>لَامُ الِابْتِدَاءِ</bdi>, (4) <bdi>اللَّامُ الْمُزَحْلَقَةُ</bdi>, (5) <bdi>لَعَلَّ</bdi>, (6) حَرْفُ or اسْمُ <bdi>الِاسْتِفْهَامِ</bdi>, (7) <bdi>لَامُ جَوَابِ الْقَسَمِ</bdi>. Their شَوَاهِد run in the same order: (1) <bdi>﴿وَتَظُنُّونَ إِنْ لَبِثْتُمْ إِلَّا قَلِيلًا﴾</bdi>, (2) <bdi>﴿لَقَدْ عَلِمْتَ مَا أَنْزَلَ هَٰؤُلَاءِ إِلَّا رَبُّ السَّمَاوَاتِ وَالْأَرْضِ﴾</bdi>, (3) <bdi>﴿وَلَقَدْ عَلِمُوا لَمَنِ اشْتَرَاهُ مَا لَهُ فِي الْآخِرَةِ مِنْ خَلَاقٍ﴾</bdi>, (4) <bdi>﴿قَدْ نَعْلَمُ إِنَّهُ لَيَحْزُنُكَ الَّذِي يَقُولُونَ﴾</bdi>, (5) <bdi>﴿وَإِنْ أَدْرِي لَعَلَّهُ فِتْنَةٌ لَكُمْ﴾</bdi>, (6) <bdi>﴿وَسَيَعْلَمُ الَّذِينَ ظَلَمُوا أَيَّ مُنْقَلَبٍ يَنْقَلِبُونَ﴾</bdi>, (7) <bdi>وَلَقَدْ عَلِمْتُ لَتَأْتِيَنَّ مَنِيَّتِي</bdi>. Do not learn them as a bare list. Every one of the seven holds <bdi>صَدْرُ الْكَلَامِ</bdi>, and that single shared trait is the whole reason they suspend.`,
          examples: [
            { ar: '﴿وَتَظُنُّونَ إِنْ لَبِثْتُمْ إِلَّا قَلِيلًا﴾', en: 'and you think you tarried only a little', note: 'إِنْ النَّافِيَة holds صَدْرُ الْكَلَامِ, so تَظُنُّونَ cannot reach the clause لَفْظًا; لَبِثْتُمْ keeps its own form' },
            { ar: '﴿قَدْ نَعْلَمُ إِنَّهُ لَيَحْزُنُكَ الَّذِي يَقُولُونَ﴾', en: 'We do know that what they say grieves you', note: 'the لَام on لَيَحْزُنُكَ is اللَّامُ الْمُزَحْلَقَةُ — نَعْلَمُ is suspended and إِنَّ keeps its كَسْرَة' },
            { ar: 'وَلَقَدْ عَلِمْتُ لَتَأْتِيَنَّ مَنِيَّتِي', en: 'and I have surely known that my death will come', note: 'لَامُ جَوَابِ الْقَسَمِ suspends عَلِمْتُ; مَنِيَّتِي is مَرْفُوع as فَاعِل of تَأْتِيَنَّ, not مَنْصُوب by عَلِمْتُ' },
          ],
          exercise: {
            prompt: `In ﴿قَدْ نَعْلَمُ إِنَّهُ لَيَحْزُنُكَ الَّذِي يَقُولُونَ﴾, which مُعَلِّق suspends the لَفْظِيّ government of نَعْلَمُ؟`,
            kind: 'mcq',
            options: ['اللَّامُ الْمُزَحْلَقَةُ', 'إِنْ النَّافِيَةُ', 'لَعَلَّ', 'لَامُ جَوَابِ الْقَسَمِ'],
            correct: 0,
          },
        },
        {
          heading: 'لِمَاذَا لَا يَعْمَلُ الْفِعْلُ فِيمَا لَهُ صَدْرُ الْكَلَامِ',
          tldr: 'A word holding صَدْرُ الْكَلَامِ cannot be governed by anything before it, so its إِعْرَاب must come from what follows.',
          body: `Take <bdi>﴿وَسَيَعْلَمُ الَّذِينَ ظَلَمُوا أَيَّ مُنْقَلَبٍ يَنْقَلِبُونَ﴾</bdi>. On sight, <bdi>أَيَّ مُنْقَلَبٍ</bdi> looks like a <bdi>مَعْمُول</bdi> of <bdi>سَيَعْلَمُ</bdi> — it is مَنْصُوب, and سَيَعْلَمُ is right there. But it is not. <bdi>الِاسْتِفْهَام</bdi> holds <bdi>صَدْرُ الْكَلَامِ</bdi>, the right to open its own sentence, and nothing standing before it may govern it. The نَصْب therefore comes from behind: <bdi>يَنْقَلِبُونَ</bdi>, the فِعْل after it, governs أَيَّ on the pattern of a مَفْعُول مُطْلَق. This is التَّعْلِيق seen from the other side. The rule is not about ظَنَّ and عَلِمَ in particular but about صَدَارَة, which is why a single-مَفْعُول فِعْل is suspended by an اسْتِفْهَام just as readily.`,
          examples: [
            { ar: '﴿وَسَيَعْلَمُ الَّذِينَ ظَلَمُوا أَيَّ مُنْقَلَبٍ يَنْقَلِبُونَ﴾', en: 'and those who did wrong will come to know what turn of fortune they will take', note: 'أَيَّ is مَنْصُوب by يَنْقَلِبُونَ, the فِعْل that follows it, never by سَيَعْلَمُ before it' },
            { ar: '﴿سَلْهُمْ أَيُّهُمْ بِذَٰلِكَ زَعِيمٌ﴾', en: 'ask them which of them will guarantee that', note: 'the same صَدَارَة, this time protecting a رَفْع — أَيُّهُمْ is مُبْتَدَأ مَرْفُوع and out of the reach of سَلْ' },
          ],
          exercise: {
            prompt: `أَيَّ مُنْقَلَبٍ in ﴿وَسَيَعْلَمُ الَّذِينَ ظَلَمُوا أَيَّ مُنْقَلَبٍ يَنْقَلِبُونَ﴾ is مَنْصُوب by which فِعْل؟`,
            kind: 'mcq',
            options: ['يَنْقَلِبُونَ, the فِعْل after it', 'سَيَعْلَمُ, the فِعْل before it', 'Both أَفْعَال together', 'Neither — it is مَرْفُوع, not مَنْصُوب'],
            correct: 0,
          },
        },
        {
          heading: 'الْإِلْغَاءُ: إِعْمَالٌ أَمْ إِلْغَاءٌ؟',
          tldr: 'الْإِلْغَاء cancels the government of a فِعْل قَلْب لَفْظًا AND مَحَلًّا, and it is the preferred reading once the فِعْل trails behind both مَفْعُولَيْهِ.',
          body: `<bdi>الْإِلْغَاء</bdi> is the harder of the two cancellations. التَّعْلِيق suspends the wording only and leaves the مَحَلّ standing; الْإِلْغَاء kills both, <bdi>لَفْظًا</bdi> and <bdi>مَحَلًّا</bdi>, so the two words revert to being a plain مُبْتَدَأٌ وَخَبَرٌ. Which reading is preferred turns on where the فِعْل stands. (1) With the فِعْل between its two مَفْعُولَانِ, <bdi>الْإِعْمَال</bdi> is preferred and both stay مَنْصُوب: <bdi>مُحَمَّدًا عَلِمْتُ صَادِقًا</bdi>. (2) With the فِعْل after both of them, الْإِلْغَاء is preferred and both are مَرْفُوع: <bdi>مُحَمَّدٌ صَادِقٌ عَلِمْتُ</bdi>. The reasoning is plain enough — a فِعْل trailing behind its content has already lost its grip on it.`,
          examples: [
            { ar: 'عَلِمْتُ مُحَمَّدًا صَادِقًا', en: 'I knew Muhammad to be truthful', note: 'the فِعْل leads, so there is no choice: it operates, and both مَفْعُولَانِ are مَنْصُوب' },
            { ar: 'مُحَمَّدًا عَلِمْتُ صَادِقًا', en: 'Muhammad — I knew him truthful', note: 'الْإِعْمَال preferred: the فِعْل sits between the two, so مُحَمَّدًا and صَادِقًا both keep نَصْب' },
            { ar: 'مُحَمَّدٌ صَادِقٌ عَلِمْتُ', en: 'Muhammad is truthful, I knew', note: 'الْإِلْغَاء preferred: the فِعْل trails behind both, so they read as مُبْتَدَأٌ وَخَبَرٌ, both مَرْفُوع' },
          ],
          exercise: {
            prompt: `مُحَمَّدٌ صَادِقٌ عَلِمْتُ places عَلِمْتُ AFTER both مَفْعُولَيْنِ. Which is preferred here, الْإِعْمَال or الْإِلْغَاء؟`,
            kind: 'mcq',
            options: ['الْإِلْغَاء', 'الْإِعْمَال', 'التَّعْلِيق', 'Neither — both are barred'],
            correct: 0,
          },
        },
      ],
      quiz: [
        {
          q: 'What is the definition of التَّعْلِيق؟',
          options: ["Suspending the فِعْل's government لَفْظًا but not مَحَلًّا, because a مُعَلِّق has intervened", "Cancelling the فِعْل's government لَفْظًا and مَحَلًّا alike", 'Deleting both مَفْعُولَيِ الْفِعْلِ together', 'Turning the فِعْل into the صِيغَة الْمَبْنِيّ لِلْمَجْهُول'],
          correct: 0,
        },
        {
          q: "A جُمْلَة from which a فِعْل's government has been suspended is called:",
          options: ['جُمْلَةٌ مُعَلَّقٌ عَنْهَا الْعَمَلُ', 'جُمْلَةٌ مَسْدُودَةٌ', 'جُمْلَةٌ مُلْغَاةٌ', 'جُمْلَةٌ مَنْسُوخَةٌ'],
          correct: 0,
        },
        {
          q: 'How many الْمُعَلِّقَات were listed?',
          options: ['سَبْعَةٌ', 'سِتَّةٌ', 'ثَمَانِيَةٌ', 'خَمْسَةٌ'],
          correct: 0,
        },
        {
          q: '﴿وَسَيَعْلَمُ الَّذِينَ ظَلَمُوا أَيَّ مُنْقَلَبٍ يَنْقَلِبُونَ﴾ — what makes أَيَّ مُنْقَلَبٍ مَنْصُوب؟',
          options: ['يَنْقَلِبُونَ, the فِعْل after it', 'سَيَعْلَمُ, the فِعْل before it', 'الَّذِينَ, the اسْم مَوْصُول', 'Nothing — it has no نَاصِب at all'],
          correct: 0,
        },
        {
          q: 'What is the definition of الْإِلْغَاء؟',
          options: ["Voiding the فِعْل's government لَفْظًا and مَحَلًّا together", "Suspending the فِعْل's government لَفْظًا only", 'Deleting the فِعْل from the جُمْلَة', 'Fronting the مَفْعُول ahead of the فَاعِل'],
          correct: 0,
        },
        {
          q: 'مُحَمَّدًا عَلِمْتُ صَادِقًا — which of the two treatments is preferred here?',
          options: ['الْإِعْمَال', 'الْإِلْغَاء', 'التَّعْلِيق', 'Neither of the two'],
          correct: 0,
        },
      ],
      bank: [
        {
          title: 'مَاذَا يُبْطِلُ التَّعْلِيقُ؟',
          kind: 'mcq',
          prompt: "التَّعْلِيق suspends the فِعْل's government:",
          options: ['لَفْظًا only, not مَحَلًّا', 'مَحَلًّا only, not لَفْظًا', 'لَفْظًا and مَحَلًّا together', 'It suspends nothing at all'],
          correct: 0,
        },
        {
          title: 'أَفْعَالٌ شَبِيهَةٌ بِأَفْعَالِ الْقُلُوبِ',
          kind: 'mcq',
          prompt: 'أَفْعَال الْإِخْبَار and أَفْعَال الِاسْتِفْهَام resemble أَفْعَال الْقُلُوب, and therefore:',
          options: ['they accept التَّعْلِيق exactly as أَفْعَال الْقُلُوب do', 'they never accept التَّعْلِيق', 'they are all لَازِمَة', 'they accept الْإِلْغَاء but never التَّعْلِيق'],
          correct: 0,
        },
        {
          title: 'الْجَامِعُ بَيْنَ الْمُعَلِّقَاتِ',
          kind: 'mcq',
          prompt: 'The seven الْمُعَلِّقَات look unrelated. What single trait do they all share?',
          options: ['Each holds صَدْرُ الْكَلَامِ, so nothing before it may govern past it', 'Each is a حَرْف نَفْي', 'Each carries a لَام in its form', 'Each puts what follows it in نَصْب'],
          correct: 0,
        },
        {
          title: 'سَلْهُمْ أَيُّهُمْ بِذَٰلِكَ زَعِيمٌ',
          kind: 'mcq',
          prompt: '﴿سَلْهُمْ أَيُّهُمْ بِذَٰلِكَ زَعِيمٌ﴾ — سَلْ here is a فِعْل of:',
          options: ['اسْتِفْهَام, and so accepts التَّعْلِيق', 'قَلْب, from أَفْعَال الْيَقِين', 'تَحْوِيل', 'لُزُوم, reaching no مَفْعُول'],
          correct: 0,
        },
        {
          title: 'إِعْرَابُ أَيُّكُمْ',
          kind: 'mcq',
          prompt: 'In ﴿لِيَبْلُوَكُمْ أَيُّكُمْ أَحْسَنُ عَمَلًا﴾, what is the إِعْرَاب of أَيُّكُمْ?',
          options: ['مُبْتَدَأٌ مَرْفُوعٌ, since يَبْلُو is مُعَلَّق and cannot put it in نَصْب', 'مَفْعُولٌ بِهِ مَنْصُوبٌ by يَبْلُو', 'مَجْرُورٌ by إِضَافَة to كُمْ', 'فَاعِلٌ مَرْفُوعٌ of يَبْلُو'],
          correct: 0,
        },
        {
          title: 'فَلْيَنْظُرْ أَيُّهَا أَزْكَىٰ طَعَامًا',
          kind: 'mcq',
          prompt: '﴿فَلْيَنْظُرْ أَيُّهَا أَزْكَىٰ طَعَامًا﴾ — how is يَنْظُرْ suspended when it takes only one مَفْعُول?',
          options: ['Because the جُمْلَة after it is اسْتِفْهَامِيَّة', 'Because it is in truth a فِعْل قَلْب', 'Because it is a فِعْل تَحْوِيل', 'Because a جُمْلَة اسْمِيَّة مَنْسُوخَة follows it'],
          correct: 0,
        },
        {
          title: 'وَتَظُنُّونَ إِنْ لَبِثْتُمْ',
          kind: 'mcq',
          prompt: '﴿وَتَظُنُّونَ إِنْ لَبِثْتُمْ إِلَّا قَلِيلًا﴾ — the مُعَلِّق here is:',
          options: ['إِنْ النَّافِيَةُ', 'مَا النَّافِيَةُ', 'لَامُ الِابْتِدَاءِ', 'لَعَلَّ'],
          correct: 0,
        },
        {
          title: 'لَقَدْ عَلِمْتَ مَا أَنْزَلَ هَٰؤُلَاءِ',
          kind: 'mcq',
          prompt: '﴿لَقَدْ عَلِمْتَ مَا أَنْزَلَ هَٰؤُلَاءِ إِلَّا رَبُّ السَّمَاوَاتِ وَالْأَرْضِ﴾ — the مُعَلِّق here is:',
          options: ['مَا النَّافِيَةُ', 'إِنْ النَّافِيَةُ', 'اللَّامُ الْمُزَحْلَقَةُ', 'لَامُ جَوَابِ الْقَسَمِ'],
          correct: 0,
        },
        {
          title: 'وَلَقَدْ عَلِمُوا لَمَنِ اشْتَرَاهُ',
          kind: 'mcq',
          prompt: '﴿وَلَقَدْ عَلِمُوا لَمَنِ اشْتَرَاهُ مَا لَهُ فِي الْآخِرَةِ مِنْ خَلَاقٍ﴾ — the مُعَلِّق here is:',
          options: ['لَامُ الِابْتِدَاءِ', 'اللَّامُ الْمُزَحْلَقَةُ', 'لَعَلَّ', 'الِاسْتِفْهَامُ'],
          correct: 0,
        },
        {
          title: 'قَدْ نَعْلَمُ إِنَّهُ لَيَحْزُنُكَ',
          kind: 'mcq',
          prompt: '﴿قَدْ نَعْلَمُ إِنَّهُ لَيَحْزُنُكَ الَّذِي يَقُولُونَ﴾ — the مُعَلِّق here is:',
          options: ['اللَّامُ الْمُزَحْلَقَةُ', 'لَامُ الِابْتِدَاءِ', 'مَا النَّافِيَةُ', 'لَامُ جَوَابِ الْقَسَمِ'],
          correct: 0,
        },
        {
          title: 'وَإِنْ أَدْرِي لَعَلَّهُ فِتْنَةٌ',
          kind: 'mcq',
          prompt: '﴿وَإِنْ أَدْرِي لَعَلَّهُ فِتْنَةٌ لَكُمْ﴾ — the مُعَلِّق here is:',
          options: ['لَعَلَّ', 'إِنْ النَّافِيَةُ', 'الِاسْتِفْهَامُ', 'لَامُ الِابْتِدَاءِ'],
          correct: 0,
        },
        {
          title: 'حَرْفُ الِاسْتِفْهَامِ مُعَلِّقًا',
          kind: 'mcq',
          prompt: 'عَلِمْتُ أَزَيْدٌ قَائِمٌ أَمْ عَمْرٌو — the مُعَلِّق here is:',
          options: ['حَرْفُ الِاسْتِفْهَامِ', 'لَعَلَّ', 'مَا النَّافِيَةُ', 'لَامُ جَوَابِ الْقَسَمِ'],
          correct: 0,
        },
        {
          title: 'وَلَقَدْ عَلِمْتُ لَتَأْتِيَنَّ مَنِيَّتِي',
          kind: 'mcq',
          prompt: 'وَلَقَدْ عَلِمْتُ لَتَأْتِيَنَّ مَنِيَّتِي — the مُعَلِّق here is:',
          options: ['لَامُ جَوَابِ الْقَسَمِ', 'لَامُ الِابْتِدَاءِ', 'اللَّامُ الْمُزَحْلَقَةُ', 'مَا النَّافِيَةُ'],
          correct: 0,
        },
        {
          title: 'صَدْرُ الْكَلَامِ',
          kind: 'mcq',
          prompt: 'Why is أَيَّ مُنْقَلَبٍ not parsed as a مَعْمُول of سَيَعْلَمُ?',
          options: ['Because الِاسْتِفْهَام holds صَدْرُ الْكَلَامِ, so nothing before it may govern it', 'Because سَيَعْلَمُ is a فِعْل لَازِم', 'Because أَيَّ مُنْقَلَبٍ is مَبْنِيّ and takes no إِعْرَاب', 'Because سَيَعْلَمُ is a فِعْل أَمْر'],
          correct: 0,
        },
        {
          title: 'لِمَاذَا الْمَرْفُوعَانِ بَعْدَ اللَّامِ',
          kind: 'mcq',
          prompt: 'عَلِمْتُ لَزَيْدٌ قَائِمٌ — why are زَيْدٌ and قَائِمٌ مَرْفُوع rather than مَنْصُوب?',
          options: ['لَامُ الِابْتِدَاءِ suspended عَلِمْتُ لَفْظًا, so the pair stays مُبْتَدَأً وَخَبَرًا', 'عَلِمَ is لَازِم and never governs anything', 'The two words are the فَاعِل of عَلِمْتُ', 'Their نَصْب is مُقَدَّر and simply not written'],
          correct: 0,
        },
        {
          title: 'الْإِلْغَاءُ يُخَالِفُ التَّعْلِيقَ',
          kind: 'mcq',
          prompt: 'الْإِلْغَاء differs from التَّعْلِيق in that it:',
          options: ['voids the government لَفْظًا and مَحَلًّا together, not لَفْظًا alone', 'does not void the government at all', 'belongs to أَفْعَال التَّحْوِيل alone', 'only enters upon a جُمْلَة اسْمِيَّة'],
          correct: 0,
        },
        {
          title: 'مُحَمَّدٌ صَادِقٌ عَلِمْتُ',
          kind: 'mcq',
          prompt: 'مُحَمَّدٌ صَادِقٌ عَلِمْتُ — why is الْإِلْغَاء preferred here?',
          options: ['Because the فِعْل comes after both مَفْعُولَيْنِ rather than between them', 'Because the فِعْل comes before both مَفْعُولَيْنِ', 'Because the فِعْل is مَبْنِيّ لِلْمَجْهُول', 'Because the جُمْلَة is اسْتِفْهَامِيَّة'],
          correct: 0,
        },
        {
          title: 'مُحَمَّدًا عَلِمْتُ صَادِقًا',
          kind: 'mcq',
          prompt: 'مُحَمَّدًا عَلِمْتُ صَادِقًا — why is الْإِعْمَال preferred here?',
          options: ['Because the فِعْل falls between its two مَفْعُولَيْنِ', 'Because the فِعْل falls after its two مَفْعُولَيْنِ', 'Because the جُمْلَة is مُعَلَّقَة', 'Because the فِعْل is a فِعْل تَحْوِيل'],
          correct: 0,
        },
        {
          title: 'الْإِعْرَابُ عِنْدَ الْإِلْغَاءِ',
          kind: 'mcq',
          prompt: 'Once الْإِلْغَاء is applied in مُحَمَّدٌ صَادِقٌ عَلِمْتُ, what is the إِعْرَاب of مُحَمَّدٌ and صَادِقٌ?',
          options: ['مُبْتَدَأٌ وَخَبَرٌ, both مَرْفُوع', 'مَفْعُولَانِ, both مَنْصُوب', 'مُحَمَّدٌ مَرْفُوع and صَادِقٌ مَنْصُوب', 'Both مَنْصُوب مَحَلًّا, مَرْفُوع لَفْظًا'],
          correct: 0,
        },
        {
          title: 'تَعْلِيقُ فِعْلٍ بِمَفْعُولٍ وَاحِدٍ',
          kind: 'mcq',
          prompt: 'Can a single-مَفْعُول فِعْل accept التَّعْلِيق without being one of أَفْعَال الْقُلُوب at all?',
          options: ['Yes, if the جُمْلَة after it opens with an اسْتِفْهَام', 'No — التَّعْلِيق is limited to two-مَفْعُول أَفْعَال', 'Yes, but only when the فِعْل is an أَمْر', 'No, under no circumstance whatsoever'],
          correct: 0,
        },
        {
          title: 'مَا الْأَفْعَالُ الَّتِي تَقْبَلُ التَّعْلِيقَ؟',
          kind: 'mcq',
          prompt: 'Which أَفْعَال accept التَّعْلِيق alongside أَفْعَال الْقُلُوب?',
          options: ['Every فِعْل indicating إِخْبَار or اسْتِفْهَام', 'Every فِعْل لَازِم', 'أَفْعَال التَّحْوِيل alone', 'Every فِعْل مَاضٍ'],
          correct: 0,
        },
        {
          title: 'التَّعْلِيقُ وَالْإِلْغَاءُ خَاصَّانِ بِمَاذَا؟',
          kind: 'mcq',
          prompt: 'التَّعْلِيق and الْإِلْغَاء both belong to:',
          options: ['أَفْعَال الْقُلُوب and the أَفْعَال resembling them', 'الْأَفْعَال اللَّازِمَة alone', 'أَفْعَال الْأَمْر alone', 'الْحُرُوف النَّاسِخَة'],
          correct: 0,
        },
        {
          title: 'تَرْكِيب: الْمُعَلِّقَاتُ (١)',
          kind: 'tarkeeb',
          instruction: 'Identify the مُعَلِّق in each تَرْكِيب.',
          source: '﴿وَتَظُنُّونَ إِنْ لَبِثْتُمْ إِلَّا قَلِيلًا﴾ / ﴿قَدْ نَعْلَمُ إِنَّهُ لَيَحْزُنُكَ الَّذِي يَقُولُونَ﴾ / ﴿وَإِنْ أَدْرِي لَعَلَّهُ فِتْنَةٌ لَكُمْ﴾ / عَلِمْتُ أَزَيْدٌ قَائِمٌ أَمْ عَمْرٌو',
          words: ['إِنْ', 'لَيَحْزُنُكَ', 'لَعَلَّهُ', 'أَزَيْدٌ'],
          labels: ['إِنْ النَّافِيَةُ', 'اللَّامُ الْمُزَحْلَقَةُ', 'لَعَلَّ', 'حَرْفُ الِاسْتِفْهَامِ'],
          distractors: ['مَا النَّافِيَةُ'],
        },
        {
          title: 'تَرْكِيب: الْمُعَلِّقَاتُ (٢)',
          kind: 'tarkeeb',
          instruction: 'Identify the مُعَلِّق in each تَرْكِيب.',
          source: '﴿لَقَدْ عَلِمْتَ مَا أَنْزَلَ هَٰؤُلَاءِ إِلَّا رَبُّ السَّمَاوَاتِ وَالْأَرْضِ﴾ / ﴿وَلَقَدْ عَلِمُوا لَمَنِ اشْتَرَاهُ مَا لَهُ فِي الْآخِرَةِ مِنْ خَلَاقٍ﴾ / وَلَقَدْ عَلِمْتُ لَتَأْتِيَنَّ مَنِيَّتِي',
          words: ['مَا', 'لَمَنِ', 'لَتَأْتِيَنَّ'],
          labels: ['مَا النَّافِيَةُ', 'لَامُ الِابْتِدَاءِ', 'لَامُ جَوَابِ الْقَسَمِ'],
          distractors: ['اللَّامُ الْمُزَحْلَقَةُ'],
        },
        {
          title: 'تَرْكِيب: أَفْعَالٌ تَقْبَلُ التَّعْلِيقَ',
          kind: 'tarkeeb',
          instruction: 'Classify each فِعْل: an original فِعْل قَلْب, or a resembling فِعْل of إِخْبَار / اسْتِفْهَام?',
          source: '﴿لِيَبْلُوَكُمْ أَيُّكُمْ أَحْسَنُ عَمَلًا﴾ / ﴿سَلْهُمْ أَيُّهُمْ بِذَٰلِكَ زَعِيمٌ﴾ / عَلِمْتُ أَنَّ الْحَقَّ ظَاهِرٌ',
          words: ['يَبْلُوَكُمْ', 'سَلْهُمْ', 'عَلِمْتُ'],
          labels: ['فِعْلُ إِخْبَارٍ مُشَابِهٌ', 'فِعْلُ اسْتِفْهَامٍ مُشَابِهٌ', 'فِعْلُ قَلْبٍ أَصْلِيٌّ'],
          distractors: ['فِعْلُ تَحْوِيلٍ'],
        },
        {
          title: 'تَرْكِيب: الْإِعْمَالُ أَمِ الْإِلْغَاءُ؟',
          kind: 'tarkeeb',
          instruction: 'Classify the treatment of the فِعْل in each تَرْكِيب: الْإِعْمَال or الْإِلْغَاء?',
          source: 'مُحَمَّدًا عَلِمْتُ صَادِقًا / مُحَمَّدٌ صَادِقٌ عَلِمْتُ',
          words: ['مُحَمَّدًا', 'مُحَمَّدٌ'],
          labels: ['الْإِعْمَالُ', 'الْإِلْغَاءُ'],
          distractors: ['التَّعْلِيقُ'],
        },
        {
          title: 'تَرْكِيب: تَعْلِيقٌ أَمْ إِلْغَاءٌ؟',
          kind: 'tarkeeb',
          instruction: 'Classify each case: did تَعْلِيق or إِلْغَاء take place?',
          source: '﴿وَتَظُنُّونَ إِنْ لَبِثْتُمْ إِلَّا قَلِيلًا﴾ / مُحَمَّدٌ صَادِقٌ عَلِمْتُ',
          words: ['تَظُنُّونَ', 'عَلِمْتُ'],
          labels: ['تَعْلِيقٌ', 'إِلْغَاءٌ'],
          distractors: ['إِعْمَالٌ'],
        },
        {
          title: 'تَرْكِيب: مُرَاجَعَةٌ عَامَّةٌ',
          kind: 'tarkeeb',
          instruction: 'Classify each case: تَعْلِيق, إِعْمَال, إِلْغَاء, or a word holding صَدْرُ الْكَلَامِ?',
          source: '﴿سَلْهُمْ أَيُّهُمْ بِذَٰلِكَ زَعِيمٌ﴾ / مُحَمَّدًا عَلِمْتُ صَادِقًا / مُحَمَّدٌ صَادِقٌ عَلِمْتُ / ﴿وَسَيَعْلَمُ الَّذِينَ ظَلَمُوا أَيَّ مُنْقَلَبٍ يَنْقَلِبُونَ﴾',
          words: ['سَلْهُمْ', 'صَادِقًا', 'صَادِقٌ', 'مُنْقَلَبٍ'],
          labels: ['تَعْلِيقٌ', 'إِعْمَالٌ', 'إِلْغَاءٌ', 'لَهُ صَدْرُ الْكَلَامِ'],
          distractors: ['اخْتِصَارٌ'],
        },
      ],
    },
  ],
};
