// Module 07 — حروف العطف والجواب والتأكيد والشرط (غير العاملة)
//
// Content is adapted from the first half of a bilingual Anki deck
// (النَحْوُ__2 الْعَامِلِ وَغَيْرِ الْعَامِلِ__2 الْحَرْفِ__2 الحرف غير العامل.apkg,
// 109 notes total) prepared for this conversion. That single source deck was
// split into two modules (07 and 08) at the midpoint by note count — 54
// notes here, 55 in Module 08 — landing exactly on the boundary between its
// "٠4 أحرف الشرط" and "٠5 التوبيخ والتحضيض والعرض" sub-decks, so the split
// falls on a natural topic break rather than mid-topic. Concept bodies are
// short by design (a sentence or two, not teaching prose); quiz/bank
// question text is English with Arabic grammatical terms left in Arabic.
//
// This module covers the first four of ten حروف غير عاملة families (§2 of
// الحرف, itself §2 of العامل وغير العامل): أحرف العطف (the nine
// non-governing conjunctions), أحرف الجواب (response particles), أحرف
// التأكيد (non-governing emphasis particles), and أحرف الشرط (لو، لولا،
// لوما، أمّا — conditional particles that do NOT cause جزم, unlike إنْ and
// its sisters in Module 06).
//
// Cross-checked against the Daram Learn lessons m1-bab-2d/2e/2f (book
// pp. 81–92) and the game bank 4-harf-ghayr-amil, from which several
// `examples`, the `why:` rationales folded into notes, and a number of bank
// items are drawn. Every Arabic word is fully vocalised: in a grammar text a
// wrong harakah teaches wrong grammar — and in this بَاب above all, since the
// whole claim of العطف is that the مَعْطُوف carries the case of the مَعْطُوف عَلَيْهِ.

export default {
  id: '07',
  title: 'الْعَطْف وَمَا بَعْدَهُ',
  heading: 'الْعَامِل وَغَيْر الْعَامِل',
  subheading: 'الْحَرْف غَيْر الْعَامِل',
  blurb: 'The nine أَحْرُف عَطْف and what each signifies, أَحْرُف الْجَوَاب (نَعَمْ، بَلَىٰ، كَلَّا…), أَحْرُف التَّأْكِيد (اللَّامَات، النُّونَانِ، قَدْ), and the أَحْرُف شَرْط that cause no جَزْم (لَوْ، لَوْلَا، لَوْمَا، أَمَّا).',
  lessons: [
    // ---------------------------------------------------------------- L1
    {
      id: 'l1',
      title: 'أَحْرُفُ الْعَطْفِ',
      subtitle: 'Conjunctions — what each of the nine أَحْرُف عَطْف signifies, and the case they hand on',
      concepts: [
        {
          heading: 'أَحْرُفُ الْعَطْفِ التِّسْعَةُ وَالْوَاوُ',
          tldr: 'Every عَطْف hands the مَعْطُوف the same إِعْرَاب the مَعْطُوف عَلَيْهِ carries; الْوَاو adds nothing beyond الْجَمْع مُطْلَقًا.',
          body: `The second class of <bdi>الْحُرُوف غَيْر الْعَامِلَة</bdi> is <bdi>أَحْرُفُ الْعَطْفِ</bdi>. They are nine: (1) <bdi>الْوَاوُ</bdi>, (2) <bdi>الْفَاءُ</bdi>, (3) <bdi>ثُمَّ</bdi>, (4) <bdi>حَتَّىٰ</bdi>, (5) <bdi>أَوْ</bdi>, (6) <bdi>أَمْ</bdi>, (7) <bdi>لَا</bdi>, (8) <bdi>بَلْ</bdi>, (9) <bdi>لَكِنْ</bdi>. Whatever a particular حَرْف means, the عَطْف itself always does one grammatical thing: it gives the <bdi>مَعْطُوف</bdi> the same إِعْرَاب as the <bdi>مَعْطُوف عَلَيْهِ</bdi>. So the harakah on the second word is not decoration — it is the evidence that عَطْف happened at all. <bdi>الْوَاو</bdi> is the first of the nine and signifies <bdi>الْجَمْعَ مُطْلَقًا</bdi>, bare joining. It claims nothing about <bdi>الْمَعِيَّة</bdi>, their happening together, and nothing about <bdi>التَّرْتِيب</bdi>, which of them came first. Either may still be gathered from a <bdi>قَرِينَة</bdi> outside the حَرْف, never from the وَاو itself.`,
          examples: [
            { ar: 'جَاءَ زَيْدٌ وَعَمْرٌو', en: 'Zayd and ʿAmr came', note: 'عَمْرٌو is مَرْفُوع because the فَاعِل زَيْدٌ is مَرْفُوع — and الْوَاو says nothing about who arrived first.' },
            { ar: 'قُلْ أَطِيعُوا اللَّهَ وَالرَّسُولَ', en: 'Say: obey Allah and the Messenger', note: 'الرَّسُولَ is مَنْصُوب because the مَفْعُول بِهِ اللَّهَ is مَنْصُوب — the مَعْطُوف simply copies the case.' },
            { ar: 'فَانْكِحُوا مَا طَابَ لَكُمْ مِنَ النِّسَاءِ مَثْنَىٰ وَثُلَاثَ وَرُبَاعَ', en: 'Marry such women as are lawful for you, two or three or four', note: 'ثُلَاثَ and رُبَاعَ are مَنْصُوب like مَثْنَىٰ and take no تَنْوِين, being مَمْنُوع مِنَ الصَّرْفِ — الْوَاو joining inside a command.' },
          ],
          exercise: {
            prompt: `What does حَرْف الْعَطْف الْوَاو signify؟`,
            kind: 'mcq',
            options: ['الْجَمْعُ مُطْلَقًا — joining, with no indication of order or simultaneity', 'الْجَمْعُ مَعَ التَّرْتِيبِ وَالتَّعْقِيبِ — joining with immediate order', 'الْجَمْعُ مَعَ التَّرْتِيبِ وَالتَّرَاخِي — joining with delayed order', 'الْغَايَةُ وَالتَّدْرِيجُ — an endpoint reached gradually'],
            correct: 0,
          },
        },
        {
          heading: 'الْفَاءُ: التَّرْتِيبُ وَالتَّعْقِيبُ وَالسَّبَبُ',
          tldr: 'الْفَاء joins in order with no gap, and between two جُمَل it can mark التَّرْتِيب الزَّمَانِيّ, التَّرْتِيب الذِّكْرِيّ, or السَّبَب.',
          body: `<bdi>الْفَاءُ</bdi> signifies <bdi>الْجَمْعَ مَعَ التَّرْتِيبِ وَالتَّعْقِيبِ</bdi> — joining, in order, with nothing in between. Its تَعْقِيب is relative rather than absolute: <bdi>تَعْقِيبُ كُلِّ شَيْءٍ بِحَسَبِهِ</bdi>. The gap inside <bdi>سَافَرْتُ إِلَىٰ مَكَّةَ فَالْمَدِينَةِ</bdi> is naturally days long, while the gap inside <bdi>دَخَلَ زَيْدٌ الدَّارَ فَعَمْرٌو</bdi> is seconds. Joining one جُمْلَة to another, the فَاء marks one of three things: (1) <bdi>التَّرْتِيبُ الزَّمَانِيُّ</bdi>, plain order in time, (2) <bdi>التَّرْتِيبُ الذِّكْرِيُّ</bdi>, a detail laid onto a summary already stated, (3) <bdi>السَّبَبُ</bdi>, causation. The causation runs in either direction. What follows may be the cause of what precedes, the فَاء then reading like a لَام التَّعْلِيل, "because". Or what precedes may be the cause of what follows, the فَاء reading "therefore". <bdi>الْفَاءُ الْفَصِيحَةُ</bdi> is the فَاء whose <bdi>مَعْطُوف عَلَيْهِ</bdi> — often a whole stretch of narrative — has been dropped and left for the reader to supply.`,
          examples: [
            { ar: 'آمَنَتْ خَدِيجَةُ فَأَبُو بَكْرٍ', en: 'Khadījah believed, then Abū Bakr', note: 'أَبُو بَكْرٍ is مَرْفُوع بِالْوَاوِ, one of الْأَسْمَاء الْخَمْسَة, matching the فَاعِل خَدِيجَةُ; the فَاء puts him straight after her.' },
            { ar: 'وَتَزَوَّدُوا فَإِنَّ خَيْرَ الزَّادِ التَّقْوَىٰ', en: 'And take provision, for the best provision is taqwā', note: 'فَاء السَّبَب running backwards — what follows is the reason for what precedes, so the فَاء reads "because".' },
            { ar: 'فَقُلْنَا اذْهَبَا إِلَى الْقَوْمِ الَّذِينَ كَذَّبُوا بِآيَاتِنَا فَدَمَّرْنَاهُمْ تَدْمِيرًا', en: 'So We said: go to the people who denied Our signs — then We destroyed them utterly', note: 'الْفَاء الْفَصِيحَة: the going, the summons and the denial are all omitted between the two clauses.' },
          ],
          exercise: {
            prompt: `Is the immediacy (التَّعْقِيب) of الْفَاء absolute, the same length in every sentence؟`,
            kind: 'mcq',
            options: ['No — تَعْقِيبُ كُلِّ شَيْءٍ بِحَسَبِهِ: immediacy is measured against the action described', 'Yes, it is always instantaneous with zero gap', 'No, الْفَاء never indicates any order at all', 'Yes, but only in Qurʾānic Arabic'],
            correct: 0,
          },
        },
        {
          heading: 'ثُمَّ',
          tldr: 'ثُمَّ orders its two sides exactly as الْفَاء does, but asserts a gap — التَّرَاخِي in place of التَّعْقِيب.',
          body: `<bdi>ثُمَّ</bdi> signifies <bdi>الْجَمْعَ مَعَ التَّرْتِيبِ وَالتَّرَاخِي</bdi> — joining, in order, with an interval between the two. It differs from الْفَاء in exactly one thing: both order their two sides, but الْفَاء denies the gap and ثُمَّ asserts it. Joining one جُمْلَة to another, ثُمَّ marks one of two things: (1) <bdi>التَّرْتِيبُ الزَّمَانِيُّ</bdi>, one event later than another in time, (2) <bdi>التَّرْتِيبُ الذِّكْرِيُّ</bdi>, where the joined جُمْلَة is not later but higher in rank, reading roughly "furthermore".`,
          examples: [
            { ar: 'آمَنَ عَلِيٌّ ثُمَّ عُمَرُ', en: 'ʿAlī believed, and later ʿUmar', note: 'عُمَرُ is مَرْفُوع بِالضَّمَّةِ with no تَنْوِين, being مَمْنُوع مِنَ الصَّرْفِ, matching عَلِيٌّ; ثُمَّ places him later, after an interval.' },
            { ar: 'ثُمَّ يُمِيتُكُمْ ثُمَّ يُحْيِيكُمْ ثُمَّ إِلَيْهِ تُرْجَعُونَ', en: 'Then He causes you to die, then gives you life, then to Him you are returned', note: 'تَرْتِيب زَمَانِيّ — three events genuinely following one another in time.' },
            { ar: 'فَإِلَيْنَا مَرْجِعُهُمْ ثُمَّ اللَّهُ شَهِيدٌ عَلَىٰ مَا يَفْعَلُونَ', en: 'Then to Us is their return; then Allah is witness over what they do', note: 'تَرْتِيب ذِكْرِيّ — the witnessing is not later in time, it outranks what came before.' },
          ],
          exercise: {
            prompt: `What does حَرْف الْعَطْف ثُمَّ signify, and how does it differ from الْفَاء؟`,
            kind: 'mcq',
            options: ['الْجَمْعُ مَعَ التَّرْتِيبِ وَالتَّرَاخِي — order, but with a delay rather than immediacy', 'الْجَمْعُ مَعَ التَّرْتِيبِ وَالتَّعْقِيبِ, exactly like الْفَاء with no difference', 'الْجَمْعُ مُطْلَقًا, with no order implied at all', 'الشَّكُّ بَعْدَ الْخَبَرِ'],
            correct: 0,
          },
        },
        {
          heading: 'حَتَّى الْعَاطِفَةُ',
          tldr: 'حَتَّى الْعَاطِفَة marks الْغَايَة وَالتَّدْرِيج, and its مَعْطُوف must be both a جُزْء of the مَعْطُوف عَلَيْهِ and its آخِر جُزْء.',
          body: `<bdi>حَتَّىٰ</bdi> signifies <bdi>الْغَايَةَ وَالتَّدْرِيجَ</bdi>: الْغَايَة is the far end of a thing, and التَّدْرِيج is the step-by-step approach to that end. Its مَعْطُوف has to satisfy two conditions: (1) it must be a <bdi>جُزْء</bdi> of the مَعْطُوف عَلَيْهِ, (2) it must be its <bdi>آخِر جُزْء</bdi>, either <bdi>حَقِيقَةً</bdi> or <bdi>حُكْمًا</bdi>. Being the last part حُكْمًا works from either end of the scale — by <bdi>قُوَّة</bdi>, the greatest of them, or by <bdi>ضَعْف</bdi>, the least. The غَايَة itself may be one of three kinds: (1) <bdi>زَمَان</bdi>, (2) <bdi>مَكَان</bdi>, (3) <bdi>رُتْبَة</bdi>. Like الْوَاو, and unlike الْفَاء and ثُمَّ, حَتَّى الْعَاطِفَة gives no <bdi>تَرْتِيب زَمَانِيّ</bdi> whatever.`,
          examples: [
            { ar: 'أَكَلْتُ السَّمَكَةَ حَتَّىٰ رَأْسَهَا', en: 'I ate the fish, right down to its head', note: 'رَأْسَهَا is مَنْصُوب like السَّمَكَةَ — that shared نَصْب is what makes this حَتَّىٰ عَاطِفَة and not جَارَّة.' },
            { ar: 'مَاتَ النَّاسُ حَتَّى الْأَنْبِيَاءُ', en: 'People died, even the prophets', note: 'الْأَنْبِيَاءُ is مَرْفُوع like النَّاسُ; they are the last part حُكْمًا بِالْقُوَّةِ, the greatest of them, not the last to die.' },
            { ar: 'صُمْتُ رَمَضَانَ حَتَّىٰ يَوْمِ الْفِطْرِ', en: 'I fasted Ramadan up to the day of ʿĪd', note: 'يَوْمِ is مَجْرُور, not مَنْصُوب — الْعِيد is no part of الصَّوْم, so this حَتَّىٰ can only be جَارَّة.' },
          ],
          clarification: `Two tests separate <bdi>حَتَّى الْعَاطِفَة</bdi> from <bdi>حَتَّى الْجَارَّة</bdi>: (1) part-hood — the مَعْطُوف must be a جُزْء of what precedes, while the مَجْرُور need only be connected to it, (2) the ruling — the مَعْطُوف always shares the ruling of what precedes, while the مَجْرُور shares it only when nothing indicates otherwise. Run both on <bdi>صُمْتُ رَمَضَانَ حَتَّىٰ آخِرَ يَوْمٍ مِنْهُ</bdi> and it is عَاطِفَة: the last day is part of Ramadan and is itself fasted, and the نَصْب on آخِرَ says so. Run them on <bdi>صُمْتُ رَمَضَانَ حَتَّىٰ يَوْمِ الْفِطْرِ</bdi> and it can only be جَارَّة, since الْعِيد is no part of الصَّوْم and is never fasted. <bdi>سِرْتُ النَّهَارَ حَتَّى الْعَصْرِ</bdi> is the middle case: الْعَصْر is a جُزْء of النَّهَار, yet the جَرّ shows حَتَّىٰ working here as a preposition.`,
          exercise: {
            prompt: `What are the two conditions on the مَعْطُوف of حَتَّىٰ؟`,
            kind: 'mcq',
            options: ['It must be a جُزْء of the مَعْطُوف عَلَيْهِ, and it must be its last part, حَقِيقَةً or حُكْمًا', 'It must be a wholly separate اسْم, unrelated to what precedes it', 'It must be a جُمْلَة, never a single مُفْرَد', 'It must denote time, never place or rank'],
            correct: 0,
          },
        },
        {
          heading: 'أَوْ وَأَمْ',
          tldr: 'أَوْ reads off whatever precedes it — الشَّكّ after a خَبَر, التَّخْيِير after an أَمْر, الْجَمْع after a نَفْي — while أَمْ lives only inside الِاسْتِفْهَام.',
          body: `<bdi>أَوْ</bdi> takes its sense from whatever precedes it, in three cases: (1) <bdi>الشَّكُّ بَعْدَ الْخَبَرِ</bdi>, doubt after a statement, (2) <bdi>التَّخْيِيرُ بَعْدَ الْأَمْرِ</bdi>, a free choice after a command, (3) <bdi>الْجَمْعُ بَعْدَ النَّفْيِ أَوِ النَّهْيِ</bdi>, where أَوْ joins exactly as الْوَاو does. That third case is the trap: after a نَهْي, أَوْ does not hand you either option, it forbids both. <bdi>أَمْ</bdi> is restricted to <bdi>الِاسْتِفْهَام</bdi> and to whatever carries its meaning, and it has two uses: (1) <bdi>طَلَبُ التَّعْيِينِ</bdi>, demanding which of the two, (2) <bdi>التَّسْوِيَةُ</bdi>, declaring the two equal.`,
          examples: [
            { ar: 'فَفِدْيَةٌ مِنْ صِيَامٍ أَوْ صَدَقَةٍ أَوْ نُسُكٍ', en: 'then a ransom of fasting, or charity, or sacrifice', note: 'صَدَقَةٍ and نُسُكٍ are مَجْرُور like صِيَامٍ after مِنْ; التَّخْيِير after a command — any one of the three discharges the فِدْيَة.' },
            { ar: 'وَلَا تُطِعْ مِنْهُمْ آثِمًا أَوْ كَفُورًا', en: 'And obey not from among them a sinner or an ingrate', note: 'كَفُورًا is مَنْصُوب like آثِمًا; after a نَهْي أَوْ gives الْجَمْع — obey neither, not "pick one".' },
            { ar: 'سَوَاءٌ عَلَيْهِمْ أَأَنْذَرْتَهُمْ أَمْ لَمْ تُنْذِرْهُمْ', en: 'It is the same to them whether you warn them or do not warn them', note: 'أَمْ لِلتَّسْوِيَة, paired with هَمْزَة التَّسْوِيَة — no answer is being requested.' },
          ],
          exercise: {
            prompt: `What is أَمْ restricted to, and what are its two uses؟`,
            kind: 'mcq',
            options: ['Restricted to الِاسْتِفْهَام and what carries its meaning; its uses are طَلَبُ التَّعْيِينِ and التَّسْوِيَةُ', 'Restricted to الْأَمْر alone; its uses are التَّخْيِير and الشَّكّ', 'It carries no restriction at all and may open any جُمْلَة', 'Restricted to النَّفْي; its uses are التَّوْكِيد and الِاسْتِدْرَاك'],
            correct: 0,
          },
        },
        {
          heading: 'لَا وَبَلْ وَلَكِنْ وَإِمَّا',
          tldr: 'لَا strips the ruling off its مَعْطُوف, بَلْ turns away from what precedes, لَكِنْ corrects it — and إِمَّا is no حَرْف عَطْف at all.',
          body: `<bdi>لَا</bdi> denies the <bdi>مَعْطُوف</bdi> the ruling just affirmed, on the single condition that <bdi>إِثْبَات</bdi> or <bdi>أَمْر</bdi> precedes it. <bdi>بَلْ</bdi> signifies <bdi>الْإِضْرَاب</bdi>, turning away from what precedes, and its effect flips with the polarity before it: (1) after <bdi>إِيجَاب</bdi> or <bdi>أَمْر</bdi> it strips the ruling off the first word and hands it to the second, (2) after <bdi>نَفْي</bdi> or <bdi>نَهْي</bdi> it leaves the first word's ruling standing and gives the second the opposite. <bdi>لَكِنْ</bdi> signifies <bdi>الِاسْتِدْرَاك</bdi>, meaning that what follows it corrects what precedes, and it coordinates on two conditions: (1) a <bdi>نَفْي</bdi> or <bdi>نَهْي</bdi> stands before it, (2) no <bdi>وَاو</bdi> accompanies it. <bdi>إِمَّا</bdi>, on the sounder view, is no حَرْف عَطْف at all, though it matches أَوْ and أَمْ in meaning.`,
          examples: [
            { ar: 'اعْمَلْ صَالِحًا لَا سَيِّئًا', en: 'Do good, not evil', note: 'سَيِّئًا is مَنْصُوب like صَالِحًا, yet لَا denies it the ruling — the case is shared, the حُكْم is not.' },
            { ar: 'صُمِ الْيَوْمَ بَلْ غَدًا', en: 'Fast today — rather, tomorrow', note: 'After an أَمْر بَلْ is لِلْإِبْطَال: the order leaves الْيَوْمَ (مَنْصُوب) and lands on غَدًا (مَنْصُوب).' },
            { ar: 'مَا جَاءَ زَيْدٌ لَكِنْ خَالِدٌ', en: 'Zayd did not come, but Khālid did', note: 'خَالِدٌ is مَرْفُوع like زَيْدٌ; لَكِنْ coordinates here because a نَفْي precedes and no وَاو is attached to it.' },
          ],
          clarification: `Three of these four change status once a <bdi>وَاو</bdi> is in play: (1) لَا preceded by نَفْي or نَهْي cannot coordinate alone — the وَاو becomes obligatory and لَا itself is <bdi>زَائِدَة</bdi>, as in <bdi>وَلَنْ تَرْضَىٰ عَنْكَ الْيَهُودُ وَلَا النَّصَارَىٰ</bdi>, (2) لَا entering a negated خَبَر, نَعْت or حَال must be repeated with the وَاو, as in <bdi>لَا مَقْطُوعَةٍ وَلَا مَمْنُوعَةٍ</bdi>, (3) لَكِنْ joined to a وَاو stops coordinating and the وَاو does the work instead, as in <bdi>وَلَكِنْ رَسُولَ اللَّهِ</bdi>. إِمَّا is the fourth case, and the odd one: it never coordinates to begin with, it comes only doubled, as in <bdi>إِمَّا شَاكِرًا وَإِمَّا كَفُورًا</bdi>, or with أَوْ standing in for its second half, as in <bdi>الِاسْمُ إِمَّا مُذَكَّرٌ أَوْ مُؤَنَّثٌ</bdi>.`,
          exercise: {
            prompt: `What happens to لَا الْعَاطِفَة when a نَفْي or نَهْي precedes it rather than an إِثْبَات؟`,
            kind: 'mcq',
            options: ['الْوَاو becomes obligatory, and لَا itself becomes زَائِدَة', 'Nothing changes — لَا behaves identically in every case', 'لَا converts into لَكِنْ automatically', 'لَا can no longer be used at all in that position'],
            correct: 0,
          },
        },
      ],
      quiz: [
        {
          q: 'How many أَحْرُف عَطْف غَيْر عَامِلَة are there؟',
          options: ['تِسْعَةٌ', 'سَبْعَةٌ', 'ثَمَانِيَةٌ', 'عَشَرَةٌ'],
          correct: 0,
        },
        {
          q: 'Whatever the particular حَرْف means, what does the عَطْف itself always do to the مَعْطُوف?',
          options: ['It gives it the same إِعْرَاب as the مَعْطُوف عَلَيْهِ', 'It puts it into النَّصْب, whatever precedes it', 'It puts it into الْجَرّ, whatever precedes it', 'It leaves it مَبْنِيّ, with no إِعْرَاب at all'],
          correct: 0,
        },
        {
          q: 'حَرْف الْعَطْف الْفَاء signifies:',
          options: ['الْجَمْعُ مَعَ التَّرْتِيبِ وَالتَّعْقِيبِ', 'الْجَمْعُ مُطْلَقًا', 'الْجَمْعُ مَعَ التَّرْتِيبِ وَالتَّرَاخِي', 'الْغَايَةُ وَالتَّدْرِيجُ'],
          correct: 0,
        },
        {
          q: '﴿ثُمَّ يُمِيتُكُمْ ثُمَّ يُحْيِيكُمْ ثُمَّ إِلَيْهِ تُرْجَعُونَ﴾ illustrates ثُمَّ marking:',
          options: ['التَّرْتِيبُ الزَّمَانِيُّ', 'التَّرْتِيبُ الذِّكْرِيُّ only', 'السَّبَبُ', 'الشَّكُّ'],
          correct: 0,
        },
        {
          q: 'أَكَلْتُ السَّمَكَةَ حَتَّى الْفَاكِهَةَ is rejected because الْفَاكِهَة is not:',
          options: ['a جُزْء of السَّمَكَة', 'مُذَكَّرَة', 'مَعْرِفَة', 'مَجْرُورَة'],
          correct: 0,
        },
        {
          q: "﴿سَوَاءٌ عَلَيْهِمْ أَأَنْذَرْتَهُمْ أَمْ لَمْ تُنْذِرْهُمْ﴾ illustrates أَمْ's use of:",
          options: ['التَّسْوِيَةُ', 'طَلَبُ التَّعْيِينِ', 'التَّخْيِيرُ', 'الشَّكُّ'],
          correct: 0,
        },
      ],
      bank: [
        {
          title: 'التِّسْعَةُ بِالِاسْمِ',
          kind: 'mcq',
          prompt: 'List the nine أَحْرُف عَطْف غَيْر عَامِلَة.',
          options: ['الْوَاوُ، الْفَاءُ، ثُمَّ، حَتَّىٰ، أَوْ، أَمْ، لَا، بَلْ، لَكِنْ', 'الْوَاوُ، مِنْ، إِلَىٰ، عَنْ، عَلَىٰ، فِي، الْبَاءُ، اللَّامُ، الْكَافُ', 'إِنْ، إِذْمَا، لَوْ، لَوْلَا، لَوْمَا، أَمَّا، لَمْ، لَمَّا', 'هَلْ، الْهَمْزَةُ، مَا، مَنْ، أَيُّ، كَيْفَ، مَتَىٰ'],
          correct: 0,
        },
        {
          title: 'إِعْرَابُ الْمَعْطُوفِ',
          kind: 'mcq',
          prompt: 'جَاءَ زَيْدٌ وَعَمْرٌو — why is عَمْرٌو مَرْفُوع rather than مَنْصُوب?',
          options: ['Because the مَعْطُوف copies the إِعْرَاب of the مَعْطُوف عَلَيْهِ, and زَيْدٌ is a فَاعِل مَرْفُوع', 'Because الْوَاو itself governs الرَّفْع in every position', 'Because a proper name can only ever be مَرْفُوع', 'Because جَاءَ raises both of them independently as two فَاعِلَانِ'],
          correct: 0,
        },
        {
          title: 'الْوَاوُ وَمَعِيَّةُ الْفِعْلَيْنِ',
          kind: 'mcq',
          prompt: 'جَاءَ زَيْدٌ وَعَمْرٌو — what does الْوَاو tell you about whether they came together or separately?',
          options: ['Nothing at all — it is silent on both الْمَعِيَّة and التَّرْتِيب', 'That they definitely came together', 'That they definitely came separately', 'That زَيْد definitely came first'],
          correct: 0,
        },
        {
          title: 'الْفَاءُ الْفَصِيحَةُ',
          kind: 'mcq',
          prompt: 'الْفَاء الْفَصِيحَة is a فَاء before which:',
          options: ['the مَعْطُوف عَلَيْهِ — often a whole stretch of narrative — has been omitted', 'the مَعْطُوف has been omitted', 'a قَسَم has been omitted', 'nothing at all has been omitted'],
          correct: 0,
        },
        {
          title: 'فَاءُ السَّبَبِ: تَعْلِيلٌ',
          kind: 'mcq',
          prompt: '﴿وَتَزَوَّدُوا فَإِنَّ خَيْرَ الزَّادِ التَّقْوَىٰ﴾ — الْفَاء here means:',
          options: ['because — what follows is the cause of what precedes', 'therefore — what precedes is the cause of what follows', 'then, immediately afterwards', 'furthermore'],
          correct: 0,
        },
        {
          title: 'فَاءُ السَّبَبِ: نَتِيجَةٌ',
          kind: 'mcq',
          prompt: '﴿إِنَّكُمْ ظَلَمْتُمْ أَنْفُسَكُمْ بِاتِّخَاذِكُمُ الْعِجْلَ فَتُوبُوا إِلَىٰ بَارِئِكُمْ﴾ — الْفَاء here means:',
          options: ['therefore — what precedes is the cause of what follows', 'because — what follows is the cause of what precedes', 'unless', 'while'],
          correct: 0,
        },
        {
          title: 'الْفَاءُ بَيْنَ جُمْلَتَيْنِ',
          kind: 'mcq',
          prompt: '﴿وَكُنْتُمْ أَمْوَاتًا فَأَحْيَاكُمْ﴾ shows الْفَاء joining جُمْلَة to جُمْلَة, marking:',
          options: ['التَّرْتِيبُ الزَّمَانِيُّ', 'التَّرْتِيبُ الذِّكْرِيُّ', 'السَّبَبُ', 'التَّسْوِيَةُ'],
          correct: 0,
        },
        {
          title: 'ثُمَّ لِلتَّرْتِيبِ الذِّكْرِيِّ',
          kind: 'mcq',
          prompt: '﴿فَإِلَيْنَا مَرْجِعُهُمْ ثُمَّ اللَّهُ شَهِيدٌ عَلَىٰ مَا يَفْعَلُونَ﴾ illustrates ثُمَّ marking:',
          options: ['التَّرْتِيبُ الذِّكْرِيُّ — higher in rank, not later in time', 'التَّرْتِيبُ الزَّمَانِيُّ pure and simple', 'السَّبَبُ', 'الشَّكُّ'],
          correct: 0,
        },
        {
          title: 'حَتَّىٰ: آخِرُ جُزْءٍ بِالْقُوَّةِ',
          kind: 'mcq',
          prompt: 'مَاتَ النَّاسُ حَتَّى الْأَنْبِيَاءُ shows the مَعْطُوف being the last part حُكْمًا, by:',
          options: ['قُوَّةٌ — greatness at the top of the scale', 'ضَعْفٌ — insignificance at the bottom', 'زَمَانٌ', 'مَكَانٌ'],
          correct: 0,
        },
        {
          title: 'حَتَّىٰ: آخِرُ جُزْءٍ بِالضَّعْفِ',
          kind: 'mcq',
          prompt: 'قَدِمَ الْحُجَّاجُ حَتَّى الْمُشَاةُ shows the مَعْطُوف being the last part حُكْمًا, by:',
          options: ['ضَعْفٌ — insignificance at the bottom of the scale', 'قُوَّةٌ — greatness at the top', 'رُتْبَةٌ عَالِيَةٌ', 'زَمَانٌ'],
          correct: 0,
        },
        {
          title: 'حَتَّىٰ عَاطِفَةٌ أَمْ جَارَّةٌ؟',
          kind: 'mcq',
          prompt: 'صُمْتُ رَمَضَانَ حَتَّىٰ يَوْمِ الْفِطْرِ — حَتَّىٰ here must be:',
          options: ['جَارَّة, since الْعِيد is no جُزْء of الصَّوْم', 'عَاطِفَة, since الْعِيد is a جُزْء of it', 'Either reading works equally well', 'Neither — حَتَّىٰ is invalid here'],
          correct: 0,
        },
        {
          title: 'حَتَّىٰ عَاطِفَةً بِالنَّصْبِ',
          kind: 'mcq',
          prompt: 'صُمْتُ رَمَضَانَ حَتَّىٰ آخِرَ يَوْمٍ مِنْهُ — what does the نَصْب on آخِرَ tell you?',
          options: ['That حَتَّىٰ is عَاطِفَة here: the last day is part of Ramadan and shares its ruling', 'That حَتَّىٰ is جَارَّة here, as it always is with time words', 'That آخِرَ is a ظَرْف unconnected to حَتَّىٰ', 'That the last day is excluded from the fast'],
          correct: 0,
        },
        {
          title: 'غَايَةُ حَتَّىٰ: زَمَانٌ',
          kind: 'mcq',
          prompt: '﴿سَلَامٌ هِيَ حَتَّىٰ مَطْلَعِ الْفَجْرِ﴾ shows a غَايَة of which kind?',
          options: ['زَمَانٌ', 'مَكَانٌ', 'رُتْبَةٌ', 'عَدَدٌ'],
          correct: 0,
        },
        {
          title: 'أَوْ: الشَّكُّ بَعْدَ الْخَبَرِ',
          kind: 'mcq',
          prompt: "﴿وَإِنَّا أَوْ إِيَّاكُمْ لَعَلَىٰ هُدًى أَوْ فِي ضَلَالٍ مُبِينٍ﴾ illustrates أَوْ's use of:",
          options: ['الشَّكُّ بَعْدَ الْخَبَرِ', 'التَّخْيِيرُ بَعْدَ الْأَمْرِ', 'الْجَمْعُ بَعْدَ النَّفْيِ', 'التَّسْوِيَةُ'],
          correct: 0,
        },
        {
          title: 'أَوْ: التَّخْيِيرُ بَعْدَ الْأَمْرِ',
          kind: 'mcq',
          prompt: "﴿فَفِدْيَةٌ مِنْ صِيَامٍ أَوْ صَدَقَةٍ أَوْ نُسُكٍ﴾ illustrates أَوْ's use of:",
          options: ['التَّخْيِيرُ بَعْدَ الْأَمْرِ', 'الشَّكُّ بَعْدَ الْخَبَرِ', 'التَّسْوِيَةُ', 'طَلَبُ التَّعْيِينِ'],
          correct: 0,
        },
        {
          title: 'أَوْ بَعْدَ النَّهْيِ',
          kind: 'mcq',
          prompt: '﴿وَلَا تُطِعْ مِنْهُمْ آثِمًا أَوْ كَفُورًا﴾ — after a نَهْي, what does أَوْ do?',
          options: ['It joins like الْوَاو, so the prohibition covers both of them', 'It offers a free choice, so you may obey one of the two', 'It expresses doubt about which of them is meant', 'It equalises the two, as أَمْ would'],
          correct: 0,
        },
        {
          title: 'أَمْ: طَلَبُ التَّعْيِينِ',
          kind: 'mcq',
          prompt: "﴿أَأَرْبَابٌ مُتَفَرِّقُونَ خَيْرٌ أَمِ اللَّهُ الْوَاحِدُ الْقَهَّارُ﴾ illustrates أَمْ's use of:",
          options: ['طَلَبُ التَّعْيِينِ', 'التَّسْوِيَةُ', 'التَّخْيِيرُ', 'الشَّكُّ'],
          correct: 0,
        },
        {
          title: 'شَرْطُ لَا الْعَاطِفَةِ',
          kind: 'mcq',
          prompt: 'For لَا الْعَاطِفَة to strip the ruling off its مَعْطُوف, what must precede it?',
          options: ['إِثْبَاتٌ أَوْ أَمْرٌ', 'نَفْيٌ أَوْ نَهْيٌ', 'اسْتِفْهَامٌ', 'قَسَمٌ'],
          correct: 0,
        },
        {
          title: 'لَا تَتَكَرَّرُ: نَعْتٌ مَنْفِيٌّ',
          kind: 'mcq',
          prompt: '﴿لَا مَقْطُوعَةٍ وَلَا مَمْنُوعَةٍ﴾ shows لَا repeated with الْوَاو because it enters a:',
          options: ['نَعْتٌ مَنْفِيٌّ', 'خَبَرٌ مُثْبَتٌ', 'حَالٌ مُثْبَتَةٌ', 'مُبْتَدَأٌ'],
          correct: 0,
        },
        {
          title: 'لَا بَعْدَ نَفْيٍ',
          kind: 'mcq',
          prompt: 'Why is مَا جَاءَ زَيْدٌ لَا عَمْرٌو ill-formed as عَطْف بِلَا?',
          options: ['A نَفْي precedes, so the وَاو is obligatory and لَا is only زَائِدَة', 'لَا may never join two proper names', 'عَمْرو would have to be مَنْصُوب here', 'It is perfectly sound as it stands'],
          correct: 0,
        },
        {
          title: 'بَلْ بَعْدَ الْإِثْبَاتِ',
          kind: 'mcq',
          prompt: 'صُمِ الْيَوْمَ بَلْ غَدًا — what does بَلْ do to the ruling on الْيَوْمَ?',
          options: ['Strips it away (إِبْطَال) and hands it to غَدًا instead', 'Confirms it, and gives the opposite to غَدًا', 'Leaves it fully intact on both words', 'Negates الْيَوْم and غَدًا together'],
          correct: 0,
        },
        {
          title: 'بَلْ بَعْدَ النَّفْيِ',
          kind: 'mcq',
          prompt: 'لَا تَصُمِ الْيَوْمَ بَلْ غَدًا — what does بَلْ do here?',
          options: ['Confirms the ruling on الْيَوْمَ, and assigns the opposite to غَدًا', 'Strips the ruling off الْيَوْمَ entirely', 'Has no effect on either word', 'Turns the جُمْلَة into an اسْتِفْهَام'],
          correct: 0,
        },
        {
          title: 'شَرْطَا لَكِنْ',
          kind: 'mcq',
          prompt: 'What are the two conditions for لَكِنْ to be عَاطِفَة rather than زَائِدَة?',
          options: ['A نَفْي or نَهْي precedes it, and no وَاو accompanies it', 'An إِثْبَات precedes it, and a وَاو accompanies it', 'A قَسَم follows it immediately', 'It is repeated at least twice'],
          correct: 0,
        },
        {
          title: 'لَكِنْ مَعَ الْوَاوِ',
          kind: 'mcq',
          prompt: '﴿مَا كَانَ مُحَمَّدٌ أَبَا أَحَدٍ مِنْ رِجَالِكُمْ وَلَكِنْ رَسُولَ اللَّهِ﴾ — what puts رَسُولَ into النَّصْب?',
          options: ['الْوَاو, which is the actual حَرْف عَطْف here, لَكِنْ being زَائِدَة', 'لَكِنْ, coordinating as it normally does', 'A hidden بَلْ', 'Nothing — رَسُولَ opens a new جُمْلَة'],
          correct: 0,
        },
        {
          title: 'إِمَّا تَتَكَرَّرُ',
          kind: 'mcq',
          prompt: '﴿إِمَّا شَاكِرًا وَإِمَّا كَفُورًا﴾ shows إِمَّا:',
          options: ['occurring doubled, as it always must', 'occurring singly, exceptionally', 'acting as a حَرْف جَرّ', 'negating both شَاكِرًا and كَفُورًا'],
          correct: 0,
        },
        {
          title: 'أَوْ نَائِبَةً عَنْ إِمَّا',
          kind: 'mcq',
          prompt: 'الِاسْمُ إِمَّا مُذَكَّرٌ أَوْ مُؤَنَّثٌ — why is there only one إِمَّا here?',
          options: ['أَوْ is standing in for the second إِمَّا, which is the other pattern إِمَّا allows', 'إِمَّا may be used singly whenever the speaker wishes', 'The second إِمَّا is present but silent, being مَحْذُوفَة for no reason', 'إِمَّا is a حَرْف عَطْف here, so no second one is needed'],
          correct: 0,
        },
        {
          title: 'تَرْكِيب: تَصْنِيفُ الْأَحْرُفِ بِمَعْنَاهَا',
          kind: 'tarkeeb',
          instruction: 'Classify each حَرْف عَطْف by its core meaning.',
          source: 'الْوَاوُ / الْفَاءُ / ثُمَّ / حَتَّىٰ',
          words: ['الْوَاوُ', 'الْفَاءُ', 'ثُمَّ', 'حَتَّىٰ'],
          labels: ['الْجَمْعُ مُطْلَقًا', 'الْجَمْعُ مَعَ التَّرْتِيبِ وَالتَّعْقِيبِ', 'الْجَمْعُ مَعَ التَّرْتِيبِ وَالتَّرَاخِي', 'الْغَايَةُ وَالتَّدْرِيجُ'],
          distractors: ['الِاسْتِدْرَاكُ'],
        },
        {
          title: 'تَرْكِيب: إِعْرَابُ الْمَعْطُوفِ',
          kind: 'tarkeeb',
          instruction: 'Give the إِعْرَاب of each مَعْطُوف — it always matches its مَعْطُوف عَلَيْهِ.',
          source: 'جَاءَ زَيْدٌ وَعَمْرٌو / أَطِيعُوا اللَّهَ وَالرَّسُولَ / أَكَلْتُ السَّمَكَةَ حَتَّىٰ رَأْسَهَا / فِدْيَةٌ مِنْ صِيَامٍ أَوْ صَدَقَةٍ',
          words: ['وَعَمْرٌو', 'وَالرَّسُولَ', 'حَتَّىٰ رَأْسَهَا', 'أَوْ صَدَقَةٍ'],
          labels: ['مَرْفُوعٌ', 'مَنْصُوبٌ', 'مَنْصُوبٌ', 'مَجْرُورٌ'],
          distractors: ['مَجْزُومٌ'],
        },
        {
          title: 'تَرْكِيب: اسْتِعْمَالَاتُ أَوْ الثَّلَاثَةُ',
          kind: 'tarkeeb',
          instruction: 'Match each example to the use of أَوْ it illustrates.',
          source: '﴿وَإِنَّا أَوْ إِيَّاكُمْ لَعَلَىٰ هُدًى﴾ / ﴿فَفِدْيَةٌ مِنْ صِيَامٍ أَوْ صَدَقَةٍ أَوْ نُسُكٍ﴾ / ﴿وَلَا تُطِعْ مِنْهُمْ آثِمًا أَوْ كَفُورًا﴾',
          words: ['وَإِنَّا أَوْ إِيَّاكُمْ', 'صِيَامٍ أَوْ صَدَقَةٍ', 'آثِمًا أَوْ كَفُورًا'],
          labels: ['الشَّكُّ بَعْدَ الْخَبَرِ', 'التَّخْيِيرُ بَعْدَ الْأَمْرِ', 'الْجَمْعُ بَعْدَ النَّهْيِ'],
          distractors: ['التَّسْوِيَةُ'],
        },
        {
          title: 'تَرْكِيب: حَتَّىٰ عَاطِفَةٌ أَمْ جَارَّةٌ؟',
          kind: 'tarkeeb',
          instruction: 'Decide for each حَتَّىٰ whether it is عَاطِفَة or جَارَّة, reading the case on the word after it.',
          source: 'أَكَلْتُ السَّمَكَةَ حَتَّىٰ رَأْسَهَا / صُمْتُ رَمَضَانَ حَتَّىٰ آخِرَ يَوْمٍ مِنْهُ / صُمْتُ رَمَضَانَ حَتَّىٰ يَوْمِ الْفِطْرِ / مَشَيْتُ حَتَّىٰ بَابِ الْمَسْجِدِ',
          words: ['حَتَّىٰ رَأْسَهَا', 'حَتَّىٰ آخِرَ يَوْمٍ مِنْهُ', 'حَتَّىٰ يَوْمِ الْفِطْرِ', 'حَتَّىٰ بَابِ الْمَسْجِدِ'],
          labels: ['عَاطِفَةٌ', 'عَاطِفَةٌ', 'جَارَّةٌ', 'جَارَّةٌ'],
          distractors: ['زَائِدَةٌ'],
        },
        {
          title: 'تَرْكِيب: بَلْ بِحَسَبِ مَا قَبْلَهَا',
          kind: 'tarkeeb',
          instruction: 'Classify what بَلْ does to the first word in each example.',
          source: 'صُمِ الْيَوْمَ بَلْ غَدًا / لَا تَصُمِ الْيَوْمَ بَلْ غَدًا',
          words: ['صُمِ الْيَوْمَ بَلْ غَدًا', 'لَا تَصُمِ الْيَوْمَ بَلْ غَدًا'],
          labels: ['إِبْطَالُ حُكْمِ الْأَوَّلِ', 'تَثْبِيتُ حُكْمِ الْأَوَّلِ'],
          distractors: ['نَفْيُ كِلَيْهِمَا'],
        },
        {
          title: 'تَرْكِيب: عَاطِفَةٌ أَمْ زَائِدَةٌ؟',
          kind: 'tarkeeb',
          instruction: 'Classify each حَرْف: is it عَاطِف in the position described, or something else؟',
          source: 'إِمَّا (مُتَكَرِّرَةً) / لَكِنْ (بَعْدَ نَفْيٍ بِلَا وَاوٍ) / لَا (بَعْدَ نَفْيٍ مَعَ الْوَاوِ)',
          words: ['إِمَّا', 'لَكِنْ', 'لَا مَعَ الْوَاوِ بَعْدَ نَفْيٍ'],
          labels: ['لَيْسَتْ عَاطِفَةً عَلَى الْأَصَحِّ', 'عَاطِفَةٌ', 'زَائِدَةٌ وَالْوَاوُ هِيَ الْعَاطِفَةُ'],
          distractors: ['جَارَّةٌ'],
        },
      ],
    },
    // ---------------------------------------------------------------- L2
    {
      id: 'l2',
      title: 'أَحْرُفُ الْجَوَابِ',
      subtitle: 'Response Particles — the six أَحْرُف إِيجَاب, the two أَحْرُف نَفْي, and the three faces of كَلَّا',
      concepts: [
        {
          heading: 'فِئَتَا أَحْرُفِ الْجَوَابِ',
          tldr: 'أَحْرُف الْجَوَاب are eight in all: six أَحْرُف إِيجَاب and two أَحْرُف نَفْي, and not one of them governs anything.',
          body: `The second class of <bdi>الْحُرُوف غَيْر الْعَامِلَة</bdi> is <bdi>أَحْرُفُ الْجَوَابِ</bdi>, the particles a reply is built on. They divide into two categories. <bdi>أَحْرُفُ الْإِيجَابِ</bdi> are six: (1) <bdi>نَعَمْ</bdi>, (2) <bdi>بَلَىٰ</bdi>, (3) <bdi>إِي</bdi>, (4) <bdi>أَجَلْ</bdi>, (5) <bdi>إِنَّ</bdi>, (6) <bdi>جَيْرِ</bdi>. <bdi>أَحْرُفُ النَّفْيِ</bdi> are two: (1) <bdi>لَا</bdi>, (2) <bdi>كَلَّا</bdi>. None of the eight governs a thing — a حَرْف جَوَاب stands as a whole answer by itself, giving no إِعْرَاب and taking none.`,
          examples: [
            { ar: 'فَهَلْ وَجَدْتُمْ مَا وَعَدَ رَبُّكُمْ حَقًّا قَالُوا نَعَمْ', en: 'So have you found what your Lord promised to be true? They said: yes', note: 'نَعَمْ, a حَرْف إِيجَاب, is the entire reply — no verb is repeated after it.' },
            { ar: 'هَلْ تُبْغِضُ الصَّحَابَةَ؟ لَا', en: 'Do you hate the Companions? No', note: 'لَا here is the plain حَرْف نَفْي of the pair, not the لَا of عَطْف or of نَهْي.' },
            { ar: 'لَمْ يَقُمْ زَيْدٌ. بَلَىٰ', en: 'Zayd did not stand. — Yes he did', note: 'بَلَىٰ answering a negative خَبَر rather than a question; زَيْدٌ stays مَرْفُوع in the original, untouched by the reply.' },
          ],
          exercise: {
            prompt: `What are the two categories of أَحْرُف الْجَوَاب؟`,
            kind: 'mcq',
            options: ['أَحْرُف الْإِيجَاب, six of them, and أَحْرُف النَّفْي, two of them', 'أَحْرُف الِاسْتِفْهَام and أَحْرُف التَّمَنِّي', 'أَحْرُف الْعَطْف and أَحْرُف الشَّرْط', 'أَحْرُف عَامِلَة and أَحْرُف مُهْمَلَة only'],
            correct: 0,
          },
        },
        {
          heading: 'نَعَمْ وَبَلَىٰ',
          tldr: 'نَعَمْ endorses a question exactly as it was put, negation included; بَلَىٰ only ever overturns a نَفْي.',
          body: `<bdi>نَعَمْ</bdi> confirms whatever it answers with the polarity untouched. After an affirmative question it affirms the event. After a negative question it confirms the نَفْي, which is the opposite of the way English "yes" behaves. <bdi>بَلَىٰ</bdi> is the particle for <bdi>إِيجَابِ الْمَنْفِيِّ</bdi>: it always affirms what had been negated. It therefore never follows an affirmative question at all, since there is no نَفْي there for it to overturn. What it does follow is either a negative question or a plain negative <bdi>خَبَر</bdi>.`,
          examples: [
            { ar: 'أَسَافَرَ خَالِدٌ؟ نَعَمْ', en: 'Did Khālid travel? — Yes', note: 'The question was affirmative, so نَعَمْ endorses it as put: he did travel.' },
            { ar: 'أَمَا سَافَرَ خَالِدٌ؟ نَعَمْ', en: 'Did Khālid not travel? — Yes', note: 'The question was negative, so نَعَمْ endorses the نَفْي: he did NOT travel.' },
            { ar: 'أَلَسْتُ بِرَبِّكُمْ قَالُوا بَلَىٰ', en: 'Am I not your Lord? They said: yes indeed', note: 'بَلَىٰ overturns the نَفْي — You certainly are our Lord. نَعَمْ would have endorsed it instead.' },
          ],
          clarification: `The choice between the two is not a nicety of style. In <bdi>أَلَسْتُ بِرَبِّكُمْ</bdi> the question is framed as a نَفْي, so the reply alone decides what is being confessed. Saying <bdi>بَلَىٰ</bdi> overturns the نَفْي and affirms the lordship. Saying <bdi>نَعَمْ</bdi> would have endorsed the نَفْي and denied it. The same fork runs through the plain خَبَر: answering <bdi>لَمْ يَقُمْ زَيْدٌ</bdi> with بَلَىٰ means he did stand, while نَعَمْ means he did not.`,
          exercise: {
            prompt: `How does نَعَمْ work after a NEGATIVE question such as أَمَا سَافَرَ خَالِدٌ؟`,
            kind: 'mcq',
            options: ['It confirms the negation — the journey did NOT happen', 'It reverses the question, so the journey DID happen', 'It is invalid after a negative question', 'It turns the question into a command'],
            correct: 0,
          },
        },
        {
          heading: 'إِي وَأَجَلْ وَإِنَّ وَجَيْرِ',
          tldr: 'The remaining four أَحْرُف إِيجَاب are fixed by position: إِي before a قَسَم, أَجَلْ after a خَبَر, and إِنَّ and جَيْرِ answering a question.',
          body: `The other four أَحْرُف إِيجَاب are each tied to a particular slot. <bdi>إِي</bdi> comes immediately before a <bdi>قَسَم</bdi> and never stands without one. <bdi>أَجَلْ</bdi> endorses a <bdi>خَبَر</bdi> that has just been stated, rather than answering a question. <bdi>إِنَّ</bdi> and <bdi>جَيْرِ</bdi> are the two rare ones, and both answer a question put to you. Note that this إِنَّ is not the عَامِلَة إِنَّ of the نَوَاسِخ: as a حَرْف جَوَاب it governs nothing at all.`,
          examples: [
            { ar: 'وَيَسْتَنْبِئُونَكَ أَحَقٌّ هُوَ قُلْ إِي وَرَبِّي إِنَّهُ لَحَقٌّ', en: 'They ask you: is it true? Say: yes, by my Lord, it is surely true', note: 'إِي sits directly on the قَسَم وَرَبِّي — that adjacency is its signature.' },
            { ar: 'نُحِبُّ الْأَنْصَارَ. أَجَلْ', en: 'We love the Anṣār. — Indeed', note: 'أَجَلْ endorsing a خَبَر, not answering a question; that is what separates it from نَعَمْ.' },
            { ar: 'جَيْرِ لَأَتْبَعَنَّهُمْ', en: 'Yes indeed, I shall certainly follow them', note: 'جَيْرِ replying to هَلْ تَتَّبِعُ الرَّسُولَ وَأَصْحَابَهُ؛ it is مَبْنِيّ عَلَى الْكَسْرِ and never changes shape.' },
          ],
          exercise: {
            prompt: `Which حَرْف جَوَاب occurs specifically before a قَسَم؟`,
            kind: 'mcq',
            options: ['إِي', 'أَجَلْ', 'جَيْرِ', 'كَلَّا'],
            correct: 0,
          },
        },
        {
          heading: 'كَلَّا وَمَعَانِيهَا الثَّلَاثَةُ',
          tldr: 'كَلَّا is primarily حَرْف رَدْعٍ وَزَجْرٍ — rejecting what precedes and affirming what follows — but it can also carry التَّصْدِيق or الِاسْتِفْتَاح.',
          body: `<bdi>كَلَّا</bdi> is the second حَرْف نَفْي, and its core sense is <bdi>الزَّجْر</bdi>: it rejects what was just said and affirms what comes after it. For that reason it is named <bdi>حَرْفَ رَدْعٍ وَزَجْرٍ</bdi>. Two further readings are open where there is nothing before it worth rebuking: (1) <bdi>التَّصْدِيق</bdi>, plain affirmation, equal in force to أَجَلْ or إِي, (2) <bdi>الِاسْتِفْتَاح</bdi>, an opener alerting the listener, equal to أَلَا. Which of the three is meant is settled by context alone, since the form of كَلَّا never changes.`,
          examples: [
            { ar: 'قَالَ رَبِّ ارْجِعُونِ. لَعَلِّي أَعْمَلُ صَالِحًا فِيمَا تَرَكْتُ. كَلَّا', en: 'He says: my Lord, send me back, that I may do righteousness in what I left. — No indeed', note: 'الزَّجْر: the request just made is refused outright, and what follows it is affirmed.' },
            { ar: 'وَمَا هِيَ إِلَّا ذِكْرَىٰ لِلْبَشَرِ. كَلَّا وَالْقَمَرِ', en: 'And it is nothing but a reminder to mankind. — Truly, by the moon', note: 'التَّصْدِيق: nothing here is being rebuked, so كَلَّا reads as أَجَلْ, and a قَسَم follows it.' },
            { ar: 'عَلَّمَ الْإِنْسَانَ مَا لَمْ يَعْلَمْ. كَلَّا إِنَّ الْإِنْسَانَ لَيَطْغَىٰ', en: 'He taught man what he did not know. — Nay, man does transgress', note: 'الِاسْتِفْتَاح: كَلَّا opens the new statement in place of أَلَا.' },
          ],
          exercise: {
            prompt: `What is the primary meaning of كَلَّا, and what name does it earn from it؟`,
            kind: 'mcq',
            options: ['الزَّجْر, rejecting what precedes — hence حَرْف رَدْعٍ وَزَجْرٍ', 'التَّصْدِيق exclusively, with no other reading', 'الِاسْتِفْهَام, always opening a question', 'التَّمَنِّي, expressing a wish beyond reach'],
            correct: 0,
          },
        },
      ],
      quiz: [
        {
          q: 'How many أَحْرُف إِيجَاب are there؟',
          options: ['سِتَّةٌ', 'أَرْبَعَةٌ', 'خَمْسَةٌ', 'سَبْعَةٌ'],
          correct: 0,
        },
        {
          q: 'List the two أَحْرُف نَفْي among أَحْرُف الْجَوَاب.',
          options: ['لَا، كَلَّا', 'لَا، لَنْ', 'مَا، لَا', 'كَلَّا، لَاتَ'],
          correct: 0,
        },
        {
          q: '﴿أَلَسْتُ بِرَبِّكُمْ قَالُوا بَلَىٰ﴾ — بَلَىٰ here means:',
          options: ['Indeed You are our Lord', 'No, You are not our Lord', 'Perhaps You are our Lord', 'We do not know'],
          correct: 0,
        },
        {
          q: 'أَجَلْ is used as affirmation:',
          options: ['بَعْدَ الْخَبَرِ, endorsing a statement just made', 'قَبْلَ الْقَسَمِ only', 'بَعْدَ الْأَمْرِ only', 'بَعْدَ النَّهْيِ only'],
          correct: 0,
        },
        {
          q: '﴿عَلَّمَ الْإِنْسَانَ مَا لَمْ يَعْلَمْ. كَلَّا إِنَّ الْإِنْسَانَ لَيَطْغَىٰ﴾ — كَلَّا here serves as:',
          options: ['الِاسْتِفْتَاح, an opener standing in for أَلَا', 'الزَّجْر, a rebuke', 'التَّصْدِيق, plain affirmation', 'الِاسْتِفْهَام'],
          correct: 0,
        },
        {
          q: 'جَيْرِ لَأَتْبَعَنَّهُمْ, replying to هَلْ تَتَّبِعُ الرَّسُولَ؟, is:',
          options: ['a less common حَرْف إِيجَاب', 'a حَرْف نَفْي', 'a حَرْف عَطْف', 'a حَرْف تَنْبِيه'],
          correct: 0,
        },
      ],
      bank: [
        {
          title: 'السِّتَّةُ إِيجَابًا',
          kind: 'mcq',
          prompt: 'List the six أَحْرُف إِيجَاب.',
          options: ['نَعَمْ، بَلَىٰ، إِي، أَجَلْ، إِنَّ، جَيْرِ', 'نَعَمْ، لَا، كَلَّا، لَاتَ، مَا، لَنْ', 'نَعَمْ، بَلَىٰ، هَلْ، أَمْ، أَوْ، لَكِنْ', 'إِي، أَجَلْ، لَوْ، لَوْلَا، لَوْمَا، أَمَّا'],
          correct: 0,
        },
        {
          title: 'عَدَدُ أَحْرُفِ الْجَوَابِ',
          kind: 'mcq',
          prompt: 'Counting both categories together, how many أَحْرُف جَوَاب are there?',
          options: ['ثَمَانِيَةٌ', 'سِتَّةٌ', 'عَشَرَةٌ', 'خَمْسَةٌ'],
          correct: 0,
        },
        {
          title: 'نَعَمْ بَعْدَ سُؤَالٍ مُثْبَتٍ',
          kind: 'mcq',
          prompt: 'أَسَافَرَ خَالِدٌ؟ نَعَمْ — this means the journey:',
          options: ['happened', 'did not happen', 'is uncertain', 'will happen tomorrow'],
          correct: 0,
        },
        {
          title: 'نَعَمْ فِي الْقُرْآنِ',
          kind: 'mcq',
          prompt: '﴿فَهَلْ وَجَدْتُمْ مَا وَعَدَ رَبُّكُمْ حَقًّا قَالُوا نَعَمْ﴾ — نَعَمْ here does what to the question?',
          options: ['Endorses it exactly as put, since the question was affirmative', 'Reverses it, since نَعَمْ always contradicts', 'Leaves it open, adding nothing', 'Turns it into an oath'],
          correct: 0,
        },
        {
          title: 'نَعَمْ بَعْدَ سُؤَالٍ مَنْفِيٍّ',
          kind: 'mcq',
          prompt: 'أَمَا سَافَرَ خَالِدٌ؟ نَعَمْ — this means the journey:',
          options: ['did not happen', 'happened', 'happened twice', 'is still being arranged'],
          correct: 0,
        },
        {
          title: 'اخْتِيَارُ الْحَرْفِ',
          kind: 'mcq',
          prompt: 'You want to reply to أَمَا سَافَرَ خَالِدٌ؟ meaning "he DID travel". Which حَرْف do you need?',
          options: ['بَلَىٰ', 'نَعَمْ', 'أَجَلْ', 'إِي'],
          correct: 0,
        },
        {
          title: 'بَلَىٰ لِإِيجَابِ الْمَنْفِيِّ',
          kind: 'mcq',
          prompt: 'لَمْ يَقُمْ زَيْدٌ. بَلَىٰ — this means زَيْد:',
          options: ['did stand', 'did not stand', 'is standing right now', 'will never stand'],
          correct: 0,
        },
        {
          title: 'بَلَىٰ فِي جَوَابِ الِاسْتِفْهَامِ',
          kind: 'mcq',
          prompt: '﴿قَالَ أَوَلَمْ تُؤْمِنْ قَالَ بَلَىٰ﴾ — why بَلَىٰ rather than نَعَمْ here?',
          options: ['The question is negative, and بَلَىٰ overturns a نَفْي while نَعَمْ would confirm it', 'بَلَىٰ is obligatory whenever a prophet is addressed', 'نَعَمْ may not follow a فِعْل مُضَارِع', 'The two are interchangeable and either would do'],
          correct: 0,
        },
        {
          title: 'مَا لَا تَلْحَقُهُ بَلَىٰ',
          kind: 'mcq',
          prompt: 'Which of these can بَلَىٰ never answer?',
          options: ['An affirmative question, since there is no نَفْي in it to overturn', 'A negative question', 'A negative خَبَر', 'A question containing لَمْ'],
          correct: 0,
        },
        {
          title: 'إِي قَبْلَ الْقَسَمِ',
          kind: 'mcq',
          prompt: '﴿قُلْ إِي وَرَبِّي إِنَّهُ لَحَقٌّ﴾ shows إِي occurring:',
          options: ['immediately before a قَسَم', 'immediately before a نَفْي', 'after بَلَىٰ', 'inside a جُمْلَة شَرْط'],
          correct: 0,
        },
        {
          title: 'إِنَّ كَحَرْفِ جَوَابٍ',
          kind: 'mcq',
          prompt: 'Replying إِنَّهُ to هَلْ تُحِبُّ الصَّحَابَةَ؟ shows إِنَّ working as:',
          options: ['a less common حَرْف إِيجَاب, governing nothing', 'a حَرْف مُشَبَّه بِالْفِعْلِ only, never a جَوَاب', 'a حَرْف نَفْي', 'a حَرْف عَطْف'],
          correct: 0,
        },
        {
          title: 'جَيْرِ وَمِثَالُهَا',
          kind: 'mcq',
          prompt: 'جَيْرِ لَأَتْبَعَنَّهُمْ, replying to a question about following the Prophet ﷺ, illustrates:',
          options: ['جَيْرِ as a less common حَرْف إِيجَاب', 'جَيْرِ as a حَرْف نَفْي', 'جَيْرِ as a حَرْف شَرْط', 'جَيْرِ as a حَرْف عَطْف'],
          correct: 0,
        },
        {
          title: 'لَا جَوَابًا',
          kind: 'mcq',
          prompt: 'هَلْ تُبْغِضُ الصَّحَابَةَ؟ لَا — what is this لَا?',
          options: ['The plain حَرْف نَفْي among أَحْرُف الْجَوَاب', 'لَا الْعَاطِفَة', 'لَا النَّاهِيَة', 'لَا النَّافِيَة لِلْجِنْسِ'],
          correct: 0,
        },
        {
          title: 'كَلَّا: الزَّجْرُ',
          kind: 'mcq',
          prompt: '﴿قَالَ رَبِّ ارْجِعُونِ. لَعَلِّي أَعْمَلُ صَالِحًا فِيمَا تَرَكْتُ. كَلَّا﴾ — كَلَّا here means:',
          options: ['rejection of what precedes (الزَّجْر)', 'affirmation of what precedes', 'an opening attention-getter', 'a question'],
          correct: 0,
        },
        {
          title: 'كَلَّا وَمَا بَعْدَهَا',
          kind: 'mcq',
          prompt: 'In its core sense, كَلَّا rejects what precedes it. What does it do to what follows?',
          options: ['Affirms it', 'Negates it as well', 'Leaves it in doubt', 'Turns it into a question'],
          correct: 0,
        },
        {
          title: 'كَلَّا: التَّصْدِيقُ',
          kind: 'mcq',
          prompt: '﴿وَمَا هِيَ إِلَّا ذِكْرَىٰ لِلْبَشَرِ. كَلَّا وَالْقَمَرِ﴾ — كَلَّا here means:',
          options: ['التَّصْدِيق, affirmation on a par with أَجَلْ and إِي', 'الزَّجْر, rebuke', 'الِاسْتِفْتَاح, an opener', 'negation of الْقَمَر'],
          correct: 0,
        },
        {
          title: 'كَلَّا بِمَعْنَى أَلَا',
          kind: 'mcq',
          prompt: 'In its الِاسْتِفْتَاح reading, كَلَّا stands in for which particle?',
          options: ['أَلَا', 'أَجَلْ', 'بَلَىٰ', 'هَلْ'],
          correct: 0,
        },
        {
          title: 'اسْمُ كَلَّا الْوَصْفِيُّ',
          kind: 'mcq',
          prompt: 'كَلَّا, in its primary sense, is called:',
          options: ['حَرْفُ رَدْعٍ وَزَجْرٍ', 'حَرْفُ جَرٍّ أَصْلِيٍّ', 'حَرْفُ تَفْسِيرٍ', 'حَرْفُ تَنْبِيهٍ مَحْضٍ'],
          correct: 0,
        },
        {
          title: 'أَحْرُفُ النَّفْيِ فِي الْجَوَابِ',
          kind: 'mcq',
          prompt: 'Among أَحْرُف الْجَوَاب, لَا and كَلَّا belong to:',
          options: ['أَحْرُف النَّفْي', 'أَحْرُف الْإِيجَاب', 'أَحْرُف الْعَطْف', 'أَحْرُف الشَّرْط'],
          correct: 0,
        },
        {
          title: 'عَدَدُ مَعَانِي كَلَّا',
          kind: 'mcq',
          prompt: 'How many distinct meanings can كَلَّا carry — الزَّجْر plus how many others?',
          options: ['ثَلَاثَةٌ', 'اثْنَانِ', 'أَرْبَعَةٌ', 'خَمْسَةٌ'],
          correct: 0,
        },
        {
          title: 'تَرْكِيب: نَعَمْ أَمْ بَلَىٰ؟',
          kind: 'tarkeeb',
          instruction: 'Pick the حَرْف — نَعَمْ or بَلَىٰ — that fits each context.',
          source: 'أَسَافَرَ خَالِدٌ؟ ___ (تَقْرِيرٌ) / أَلَسْتُ بِرَبِّكُمْ؟ ___ (بَلَىٰ أَنْتَ رَبُّنَا)',
          words: ['أَسَافَرَ خَالِدٌ؟', 'أَلَسْتُ بِرَبِّكُمْ؟'],
          labels: ['نَعَمْ', 'بَلَىٰ'],
          distractors: ['إِي'],
        },
        {
          title: 'تَرْكِيب: مَاذَا يَعْنِي الْجَوَابُ؟',
          kind: 'tarkeeb',
          instruction: 'Say what each reply actually asserts about the journey.',
          source: 'أَسَافَرَ خَالِدٌ؟ نَعَمْ / أَمَا سَافَرَ خَالِدٌ؟ نَعَمْ / أَمَا سَافَرَ خَالِدٌ؟ بَلَىٰ',
          words: ['أَسَافَرَ خَالِدٌ؟ نَعَمْ', 'أَمَا سَافَرَ خَالِدٌ؟ نَعَمْ', 'أَمَا سَافَرَ خَالِدٌ؟ بَلَىٰ'],
          labels: ['سَافَرَ', 'لَمْ يُسَافِرْ', 'سَافَرَ'],
          distractors: ['لَا يُدْرَىٰ'],
        },
        {
          title: 'تَرْكِيب: مَوْقِعُ كُلِّ حَرْفٍ',
          kind: 'tarkeeb',
          instruction: 'Match each حَرْف إِيجَاب to the slot it occupies.',
          source: 'إِي / أَجَلْ / بَلَىٰ / نَعَمْ',
          words: ['إِي', 'أَجَلْ', 'بَلَىٰ', 'نَعَمْ'],
          labels: ['قَبْلَ الْقَسَمِ', 'بَعْدَ الْخَبَرِ', 'بَعْدَ النَّفْيِ', 'بَعْدَ الِاسْتِفْهَامِ'],
          distractors: ['بَعْدَ الشَّرْطِ'],
        },
        {
          title: 'تَرْكِيب: مَعَانِي كَلَّا الثَّلَاثَةُ',
          kind: 'tarkeeb',
          instruction: 'Match each example to the meaning of كَلَّا it illustrates.',
          source: '﴿قَالَ رَبِّ ارْجِعُونِ… كَلَّا﴾ / ﴿وَمَا هِيَ إِلَّا ذِكْرَىٰ لِلْبَشَرِ. كَلَّا وَالْقَمَرِ﴾ / ﴿عَلَّمَ الْإِنْسَانَ مَا لَمْ يَعْلَمْ. كَلَّا إِنَّ الْإِنْسَانَ لَيَطْغَىٰ﴾',
          words: ['كَلَّا بَعْدَ ارْجِعُونِ', 'كَلَّا وَالْقَمَرِ', 'كَلَّا إِنَّ الْإِنْسَانَ'],
          labels: ['الزَّجْرُ', 'التَّصْدِيقُ', 'الِاسْتِفْتَاحُ'],
          distractors: ['الِاسْتِفْهَامُ'],
        },
        {
          title: 'تَرْكِيب: إِيجَابٌ أَمْ نَفْيٌ؟',
          kind: 'tarkeeb',
          instruction: 'Classify each حَرْف: is it from أَحْرُف الْإِيجَاب or أَحْرُف النَّفْي؟',
          source: 'نَعَمْ / لَا / أَجَلْ / كَلَّا',
          words: ['نَعَمْ', 'لَا', 'أَجَلْ', 'كَلَّا'],
          labels: ['إِيجَابٌ', 'نَفْيٌ', 'إِيجَابٌ', 'نَفْيٌ'],
          distractors: ['شَرْطٌ'],
        },
        {
          title: 'تَرْكِيب: أَيُّ جَوَابٍ لِأَيِّ كَلَامٍ؟',
          kind: 'tarkeeb',
          instruction: 'Match each utterance to the حَرْف جَوَاب that answers it.',
          source: 'نُحِبُّ الْأَنْصَارَ / هَلْ تُحِبُّ الصَّحَابَةَ؟ / أَحَقٌّ هُوَ؟ / هَلْ تُبْغِضُ الصَّحَابَةَ؟',
          words: ['نُحِبُّ الْأَنْصَارَ', 'هَلْ تُحِبُّ الصَّحَابَةَ؟', 'أَحَقٌّ هُوَ؟', 'هَلْ تُبْغِضُ الصَّحَابَةَ؟'],
          labels: ['أَجَلْ', 'إِنَّهُ', 'إِي وَرَبِّي', 'لَا'],
          distractors: ['بَلَىٰ'],
        },
      ],
    },
    // ---------------------------------------------------------------- L3
    {
      id: 'l3',
      title: 'أَحْرُفُ التَّأْكِيدِ',
      subtitle: 'Emphasis Particles — the three لَامَات, نُونَا التَّأْكِيد, and the four faces of قَدْ',
      concepts: [
        {
          heading: 'أَحْرُفُ التَّأْكِيدِ الْخَمْسَةُ وَلَامُ الِابْتِدَاءِ',
          tldr: 'The five أَحْرُف تَأْكِيد غَيْر عَامِلَة are three لَامَات, نُونَا التَّأْكِيد and قَدْ; the first لَام enters the مُبْتَدَأ and leaves its رَفْع alone.',
          body: `The third class of <bdi>الْحُرُوف غَيْر الْعَامِلَة</bdi> is <bdi>أَحْرُفُ التَّأْكِيدِ</bdi>, also called أَحْرُف التَّوْكِيد. They are five: (1) <bdi>لَامُ الِابْتِدَاءِ</bdi>, (2) <bdi>اللَّامُ الْمُزَحْلَقَةُ</bdi>, (3) <bdi>اللَّامُ فِي جَوَابِ الْقَسَمِ</bdi>, (4) <bdi>نُونَا التَّأْكِيدِ</bdi>, (5) <bdi>قَدْ</bdi>. <bdi>إِنَّ</bdi> and <bdi>أَنَّ</bdi> emphasise as well, yet they are not counted here, because they govern and this whole بَاب is for the حُرُوف غَيْر عَامِلَة. <bdi>لَامُ الِابْتِدَاءِ</bdi> is the one that enters the <bdi>مُبْتَدَأ</bdi>, and it leaves that word's رَفْع exactly as it found it.`,
          examples: [
            { ar: 'وَلَدَارُ الْآخِرَةِ خَيْرٌ لِلَّذِينَ اتَّقَوْا', en: 'And the home of the Hereafter is better for those who fear Allah', note: 'دَارُ stays مَرْفُوع as the مُبْتَدَأ under the لَام — proof the لَام adds emphasis and no إِعْرَاب.' },
            { ar: 'قَدْ أَفْلَحَ الْمُؤْمِنُونَ', en: 'The believers have certainly succeeded', note: 'قَدْ, the fifth of the five, emphasising a فِعْل مَاضٍ; الْمُؤْمِنُونَ is مَرْفُوع as its فَاعِل, untouched by قَدْ.' },
          ],
          exercise: {
            prompt: `What does لَام الِابْتِدَاء enter upon؟`,
            kind: 'mcq',
            options: ['الْمُبْتَدَأ', 'الْخَبَر only', 'الْفِعْل الْمَاضِي', 'الْمُضَاف إِلَيْهِ'],
            correct: 0,
          },
        },
        {
          heading: 'اللَّامُ الْمُزَحْلَقَةُ وَلَامُ التَّوْكِيدِ',
          tldr: 'اللَّام الْمُزَحْلَقَة is لَام الِابْتِدَاء slid off the اسْم of إِنَّ onto its خَبَر, which is why the two together are called لَام التَّوْكِيد.',
          body: `<bdi>اللَّامُ الْمُزَحْلَقَةُ</bdi> is named for having been slid along: it began as لَام الِابْتِدَاء on the مُبْتَدَأ, then إِنَّ took that opening position and pushed the لَام forward onto the <bdi>خَبَر</bdi>. It enters the خَبَر of إِنَّ in three cases: (1) when that خَبَر is an <bdi>اسْم</bdi>, (2) when it is a <bdi>فِعْل مُضَارِع</bdi>, (3) when it is a <bdi>شِبْه جُمْلَة</bdi>. So لَام الِابْتِدَاء and اللَّام الْمُزَحْلَقَة are one emphasis in two different positions, and that is why they share the collective name <bdi>لَامُ التَّوْكِيدِ</bdi>.`,
          examples: [
            { ar: 'إِنَّ رَبِّي لَسَمِيعُ الدُّعَاءِ', en: 'Indeed my Lord is the Hearer of supplication', note: 'The خَبَر is an اسْم, and لَسَمِيعُ stays مَرْفُوع as خَبَر إِنَّ — the لَام is riding on it, not governing it.' },
            { ar: 'وَإِنَّ رَبَّكَ لَيَعْلَمُ مَا تُكِنُّ صُدُورُهُمْ', en: 'And indeed your Lord knows what their breasts conceal', note: 'The خَبَر is a فِعْل مُضَارِع, and لَيَعْلَمُ remains مَرْفُوع with its ضَمَّة intact.' },
            { ar: 'وَإِنَّكَ لَعَلَىٰ خُلُقٍ عَظِيمٍ', en: 'And indeed you are of a great character', note: 'The خَبَر is a شِبْه جُمْلَة; خُلُقٍ is مَجْرُور by عَلَىٰ, and the لَام sits on the whole phrase.' },
          ],
          exercise: {
            prompt: `Upon what does اللَّام الْمُزَحْلَقَة enter, and in which cases؟`,
            kind: 'mcq',
            options: ['Upon the خَبَر of إِنَّ, when it is an اسْم, a فِعْل مُضَارِع, or a شِبْه جُمْلَة', 'Upon the اسْم of إِنَّ exclusively', 'Upon any فِعْل مَاضٍ in the جُمْلَة', 'Upon a مُضَاف إِلَيْهِ only'],
            correct: 0,
          },
        },
        {
          heading: 'لَامُ جَوَابِ الْقَسَمِ وَنُونَا التَّأْكِيدِ',
          tldr: 'The third لَام answers a قَسَم, and the two نُونَا التَّأْكِيد differ only in shape — الثَّقِيلَة carries a شَدَّة, الْخَفِيفَة a سُكُون.',
          body: `The third لَام of the five is <bdi>اللَّامُ فِي جَوَابِ الْقَسَمِ</bdi>, and its tell is an oath standing just before it. <bdi>نُونَا التَّأْكِيدِ</bdi> are two nūns attached to the end of a فِعْل, and the whole difference between them is written on the letter itself: (1) <bdi>النُّونُ الثَّقِيلَةُ</bdi> carries a <bdi>شَدَّة</bdi>, (2) <bdi>النُّونُ الْخَفِيفَةُ</bdi> carries a <bdi>سُكُون</bdi>. One āyah famously carries both, one on each of its two verbs.`,
          examples: [
            { ar: 'تَاللَّهِ لَتُسْأَلُنَّ عَمَّا كُنْتُمْ تَفْتَرُونَ', en: 'By Allah, you will surely be questioned about what you used to invent', note: 'The قَسَم تَاللَّهِ is the tell: the لَام on لَتُسْأَلُنَّ is لَام جَوَاب الْقَسَم, and the verb also takes نُون التَّأْكِيد.' },
            { ar: 'لَيُسْجَنَنَّ وَلَيَكُونًا مِنَ الصَّاغِرِينَ', en: 'He will surely be imprisoned and will surely be among the debased', note: 'لَيُسْجَنَنَّ ends in النُّون الثَّقِيلَة, marked by the شَدَّة; لَيَكُونًا ends in النُّون الْخَفِيفَة, written as an أَلِف at the pause.' },
          ],
          exercise: {
            prompt: `What are the two نُونَا التَّأْكِيد, and what tells them apart on the page؟`,
            kind: 'mcq',
            options: ['الْخَفِيفَة and الثَّقِيلَة — the heavy one carries a شَدَّة, the light one a سُكُون', 'الْمُتَّصِلَة and الْمُنْفَصِلَة — one is attached, the other written apart', 'السَّاكِنَة and الْمُتَحَرِّكَة — one is fixed, the other takes any vowel', 'الْأَصْلِيَّة and الزَّائِدَة — one belongs to the root, the other is added'],
            correct: 0,
          },
        },
        {
          heading: 'قَدْ مَعَ الْمَاضِي وَالْمُضَارِعِ',
          tldr: 'With a فِعْل مَاضٍ قَدْ means التَّحْقِيق and nothing else; with a فِعْل مُضَارِع it ranges over four meanings, التَّقْلِيل predominating.',
          body: `<bdi>قَدْ</bdi> is the last of the five, and its meaning is decided by the tense of the verb after it. With a <bdi>فِعْل مَاضٍ</bdi> it carries one sense only, <bdi>التَّحْقِيق</bdi>: the event is asserted as realised. With a <bdi>فِعْل مُضَارِع</bdi> it ranges over four: (1) <bdi>التَّحْقِيق</bdi>, (2) <bdi>التَّوَقُّع</bdi>, expecting the event, (3) <bdi>التَّكْثِير</bdi>, doing it often, (4) <bdi>التَّقْلِيل</bdi>, doing it rarely. Of the four, <bdi>التَّقْلِيل</bdi> is the predominant reading, so much so that قَدْ before a مُضَارِع is often simply labelled حَرْف تَقْلِيل.`,
          examples: [
            { ar: 'قَدْ أَفْلَحَ الْمُؤْمِنُونَ', en: 'The believers have certainly succeeded', note: 'قَدْ before a مَاضٍ — التَّحْقِيق, the only reading available with that tense.' },
            { ar: 'قَدْ يَبْرَأُ الْمَرِيضُ', en: 'The sick man may well recover', note: 'قَدْ before a مُضَارِع — التَّوَقُّع, an event looked forward to rather than asserted.' },
            { ar: 'قَدْ يَصْدُقُ الْكَذُوبُ', en: 'Even the habitual liar sometimes tells the truth', note: 'التَّقْلِيل, the predominant reading with a مُضَارِع: it happens, but seldom.' },
          ],
          exercise: {
            prompt: `With الْمُضَارِع, which of قَدْ's four meanings predominates؟`,
            kind: 'mcq',
            options: ['التَّقْلِيل', 'التَّحْقِيق', 'التَّكْثِير', 'التَّوَقُّع'],
            correct: 0,
          },
        },
      ],
      quiz: [
        {
          q: 'How many أَحْرُف تَأْكِيد غَيْر عَامِلَة are there؟',
          options: ['خَمْسَةٌ', 'ثَلَاثَةٌ', 'أَرْبَعَةٌ', 'سِتَّةٌ'],
          correct: 0,
        },
        {
          q: '﴿إِنَّ رَبِّي لَسَمِيعُ الدُّعَاءِ﴾ shows اللَّام الْمُزَحْلَقَة entering a خَبَر that is:',
          options: ['اسْمٌ', 'فِعْلٌ مَاضٍ', 'شِبْهُ جُمْلَةٍ', 'حَرْفُ جَرٍّ'],
          correct: 0,
        },
        {
          q: 'لَام الِابْتِدَاء and اللَّام الْمُزَحْلَقَة share the collective name:',
          options: ['لَامُ التَّوْكِيدِ', 'لَامُ الْجُحُودِ', 'لَامُ الْأَمْرِ', 'لَامُ التَّعْلِيلِ'],
          correct: 0,
        },
        {
          q: '﴿لَيُسْجَنَنَّ وَلَيَكُونًا مِنَ الصَّاغِرِينَ﴾ contains:',
          options: ['both نُونَا التَّأْكِيد, the light and the heavy', 'only النُّون الثَّقِيلَة', 'only النُّون الْخَفِيفَة', 'neither نُون'],
          correct: 0,
        },
        {
          q: '﴿قَدْ أَفْلَحَ الْمُؤْمِنُونَ﴾ — قَدْ here, before a مَاضٍ, means:',
          options: ['التَّحْقِيقُ', 'التَّوَقُّعُ', 'التَّكْثِيرُ', 'التَّقْلِيلُ'],
          correct: 0,
        },
        {
          q: "قَدْ يَصْدُقُ الْكَذُوبُ illustrates قَدْ's meaning of:",
          options: ['التَّقْلِيلُ', 'التَّحْقِيقُ', 'التَّكْثِيرُ', 'التَّوَقُّعُ'],
          correct: 0,
        },
      ],
      bank: [
        {
          title: 'الْخَمْسَةُ بِالِاسْمِ',
          kind: 'mcq',
          prompt: 'List the five أَحْرُف تَأْكِيد غَيْر عَامِلَة.',
          options: ['لَامُ الِابْتِدَاءِ، اللَّامُ الْمُزَحْلَقَةُ، لَامُ جَوَابِ الْقَسَمِ، نُونَا التَّأْكِيدِ، قَدْ', 'لَامُ الِابْتِدَاءِ، لَامُ الْأَمْرِ، لَامُ الْجُحُودِ، لَامُ التَّعْلِيلِ، لَامُ الْقَسَمِ', 'نَعَمْ، بَلَىٰ، إِي، أَجَلْ، كَلَّا', 'الْوَاوُ، الْفَاءُ، ثُمَّ، حَتَّىٰ، لَكِنْ'],
          correct: 0,
        },
        {
          title: 'لِمَ لَا تُعَدُّ إِنَّ مِنْهَا؟',
          kind: 'mcq',
          prompt: 'إِنَّ and أَنَّ plainly emphasise. Why are they left out of these five?',
          options: ['Because they govern, and this whole بَاب is for the حُرُوف غَيْر عَامِلَة', 'Because their emphasis is weaker than that of the لَامَات', 'Because they may only enter a جُمْلَة فِعْلِيَّة', 'Because they are أَحْرُف جَوَاب, counted in the previous class'],
          correct: 0,
        },
        {
          title: 'مِثَالُ لَامِ الِابْتِدَاءِ',
          kind: 'mcq',
          prompt: '﴿وَلَدَارُ الْآخِرَةِ خَيْرٌ لِلَّذِينَ اتَّقَوْا﴾ shows لَام الِابْتِدَاء entering:',
          options: ['الْمُبْتَدَأ, دَارُ', 'الْخَبَر, خَيْرٌ', 'الْمُضَاف إِلَيْهِ', 'حَرْف الْجَرّ لِـ'],
          correct: 0,
        },
        {
          title: 'مَا الْفَرْقُ بَيْنَ اللَّامَيْنِ؟',
          kind: 'mcq',
          prompt: 'Two of the five لَامَات share the name لَام التَّوْكِيد. What separates them?',
          options: ['Position: one enters the مُبْتَدَأ, the other the خَبَر of إِنَّ', 'Meaning: one emphasises, the other negates', 'Governance: one causes نَصْب, the other جَرّ', 'Tense: one goes with الْمَاضِي, the other with الْمُضَارِع'],
          correct: 0,
        },
        {
          title: 'لِمَ سُمِّيَتْ مُزَحْلَقَةً؟',
          kind: 'mcq',
          prompt: 'Why is اللَّام الْمُزَحْلَقَة given that name?',
          options: ['It was لَام الِابْتِدَاء on the مُبْتَدَأ and إِنَّ slid it forward onto the خَبَر', 'Because it slides off the word entirely in recitation', 'Because it may be moved to any word in the جُمْلَة at will', 'Because it slid in from the جَوَاب of a قَسَم'],
          correct: 0,
        },
        {
          title: 'مَوَاضِعُ الْمُزَحْلَقَةِ الثَّلَاثَةُ',
          kind: 'mcq',
          prompt: 'Which list gives the three kinds of خَبَر إِنَّ that اللَّام الْمُزَحْلَقَة may enter?',
          options: ['اسْمٌ، فِعْلٌ مُضَارِعٌ، شِبْهُ جُمْلَةٍ', 'اسْمٌ، فِعْلٌ مَاضٍ، فِعْلُ أَمْرٍ', 'جُمْلَةٌ اسْمِيَّةٌ، جُمْلَةٌ فِعْلِيَّةٌ، قَسَمٌ', 'مُبْتَدَأٌ، خَبَرٌ، حَالٌ'],
          correct: 0,
        },
        {
          title: 'الْمُزَحْلَقَةُ: فِعْلٌ مُضَارِعٌ',
          kind: 'mcq',
          prompt: '﴿وَإِنَّ رَبَّكَ لَيَعْلَمُ مَا تُكِنُّ صُدُورُهُمْ﴾ shows اللَّام الْمُزَحْلَقَة entering a خَبَر that is:',
          options: ['فِعْلٌ مُضَارِعٌ', 'اسْمٌ مُفْرَدٌ', 'شِبْهُ جُمْلَةٍ', 'جُمْلَةٌ اسْمِيَّةٌ مَنْسُوخَةٌ'],
          correct: 0,
        },
        {
          title: 'الْمُزَحْلَقَةُ: شِبْهُ جُمْلَةٍ',
          kind: 'mcq',
          prompt: '﴿وَإِنَّكَ لَعَلَىٰ خُلُقٍ عَظِيمٍ﴾ shows اللَّام الْمُزَحْلَقَة entering a خَبَر that is:',
          options: ['شِبْهُ جُمْلَةٍ', 'اسْمٌ مُفْرَدٌ', 'فِعْلٌ مَاضٍ', 'فِعْلُ أَمْرٍ'],
          correct: 0,
        },
        {
          title: 'الْمُزَحْلَقَةُ بَعْدَ شِبْهِ جُمْلَةٍ مُقَدَّمَةٍ',
          kind: 'mcq',
          prompt: '﴿إِنَّ فِي ذَٰلِكَ لَآيَاتٍ﴾ — which لَام is on آيَاتٍ, and why is it there?',
          options: ['اللَّام الْمُزَحْلَقَة, on the خَبَر of إِنَّ, the شِبْه جُمْلَة having been fronted before it', 'لَام الِابْتِدَاء, since آيَاتٍ is the مُبْتَدَأ', 'لَام جَوَاب الْقَسَم', 'لَام الْجَرّ attached to آيَاتٍ'],
          correct: 0,
        },
        {
          title: 'لَامُ جَوَابِ الْقَسَمِ',
          kind: 'mcq',
          prompt: '﴿تَاللَّهِ لَتُسْأَلُنَّ عَمَّا كُنْتُمْ تَفْتَرُونَ﴾ shows a لَام standing in:',
          options: ['جَوَاب الْقَسَم', 'خَبَر إِنَّ', 'الْمُبْتَدَأ', 'الْفِعْل النَّاقِص'],
          correct: 0,
        },
        {
          title: 'فَرْقُ النُّونَيْنِ فِي الشَّكْلِ',
          kind: 'mcq',
          prompt: 'How do النُّون الثَّقِيلَة and النُّون الْخَفِيفَة differ as written?',
          options: ['The heavy one carries a شَدَّة, the light one a سُكُون', 'The heavy one is doubled in writing, the light one is dropped entirely', 'The heavy one only attaches to a مَاضٍ, the light one to a مُضَارِع', 'The heavy one is written with a وَاو, the light one with a يَاء'],
          correct: 0,
        },
        {
          title: 'أَيُّ الْفِعْلَيْنِ حَمَلَ الثَّقِيلَةَ؟',
          kind: 'mcq',
          prompt: 'In ﴿لَيُسْجَنَنَّ وَلَيَكُونًا مِنَ الصَّاغِرِينَ﴾, which verb carries النُّون الثَّقِيلَة?',
          options: ['لَيُسْجَنَنَّ', 'لَيَكُونًا', 'Both of them', 'Neither of them'],
          correct: 0,
        },
        {
          title: 'قَدْ مَعَ الْمَاضِي',
          kind: 'mcq',
          prompt: 'With a فِعْل مَاضٍ, how many meanings does قَدْ carry, and which?',
          options: ['One only — التَّحْقِيق', 'Two — التَّحْقِيق and التَّقْلِيل', 'Four, exactly as with الْمُضَارِع', 'None; قَدْ does not enter a مَاضٍ'],
          correct: 0,
        },
        {
          title: 'عَدَدُ مَعَانِي قَدْ مَعَ الْمُضَارِعِ',
          kind: 'mcq',
          prompt: 'How many meanings can قَدْ carry before a فِعْل مُضَارِع?',
          options: ['أَرْبَعَةٌ', 'اثْنَانِ', 'وَاحِدٌ', 'سِتَّةٌ'],
          correct: 0,
        },
        {
          title: 'قَدْ لِلتَّوَقُّعِ',
          kind: 'mcq',
          prompt: "قَدْ يَبْرَأُ الْمَرِيضُ illustrates قَدْ's meaning of:",
          options: ['التَّوَقُّعُ', 'التَّحْقِيقُ', 'التَّقْلِيلُ', 'التَّكْثِيرُ'],
          correct: 0,
        },
        {
          title: 'قَدْ لِلتَّكْثِيرِ',
          kind: 'mcq',
          prompt: "﴿قَدْ نَرَىٰ تَقَلُّبَ وَجْهِكَ فِي السَّمَاءِ﴾ illustrates قَدْ's meaning of:",
          options: ['التَّكْثِيرُ', 'التَّقْلِيلُ', 'التَّوَقُّعُ', 'التَّحْقِيقُ'],
          correct: 0,
        },
        {
          title: 'قَدْ لِلتَّحْقِيقِ مَعَ الْمُضَارِعِ',
          kind: 'mcq',
          prompt: "﴿قَدْ يَعْلَمُ اللَّهُ﴾ illustrates قَدْ's meaning of:",
          options: ['التَّحْقِيقُ', 'التَّقْلِيلُ', 'التَّكْثِيرُ', 'التَّوَقُّعُ'],
          correct: 0,
        },
        {
          title: 'الِاسْمُ الْجَامِعُ لِلَّامَيْنِ',
          kind: 'mcq',
          prompt: 'The name لَام التَّوْكِيد collectively covers:',
          options: ['لَام الِابْتِدَاء and اللَّام الْمُزَحْلَقَة', 'لَام الْأَمْر and لَام الْجُحُود', 'لَام جَوَاب الْقَسَم and لَام الِابْتِدَاء only', 'Every لَام without exception'],
          correct: 0,
        },
        {
          title: 'تَرْكِيب: مَوَاضِعُ الْمُزَحْلَقَةِ الثَّلَاثَةُ',
          kind: 'tarkeeb',
          instruction: 'Classify the kind of خَبَر each example shows اللَّام الْمُزَحْلَقَة entering.',
          source: '﴿إِنَّ رَبِّي لَسَمِيعُ الدُّعَاءِ﴾ / ﴿وَإِنَّ رَبَّكَ لَيَعْلَمُ مَا تُكِنُّ صُدُورُهُمْ﴾ / ﴿وَإِنَّكَ لَعَلَىٰ خُلُقٍ عَظِيمٍ﴾',
          words: ['لَسَمِيعُ الدُّعَاءِ', 'لَيَعْلَمُ', 'لَعَلَىٰ خُلُقٍ'],
          labels: ['اسْمٌ', 'فِعْلٌ مُضَارِعٌ', 'شِبْهُ جُمْلَةٍ'],
          distractors: ['فِعْلٌ مَاضٍ'],
        },
        {
          title: 'تَرْكِيب: أَيُّ حَرْفِ تَأْكِيدٍ فِي الْآيَةِ؟',
          kind: 'tarkeeb',
          instruction: 'Name the حَرْف تَأْكِيد at work in each example.',
          source: '﴿وَلَدَارُ الْآخِرَةِ خَيْرٌ﴾ / ﴿قَدْ أَفْلَحَ الْمُؤْمِنُونَ﴾ / ﴿لَيُسْجَنَنَّ﴾ / ﴿وَإِنَّكَ لَعَلَىٰ خُلُقٍ عَظِيمٍ﴾',
          words: ['وَلَدَارُ الْآخِرَةِ خَيْرٌ', 'قَدْ أَفْلَحَ الْمُؤْمِنُونَ', 'لَيُسْجَنَنَّ', 'وَإِنَّكَ لَعَلَىٰ خُلُقٍ عَظِيمٍ'],
          labels: ['لَامُ الِابْتِدَاءِ', 'قَدْ', 'النُّونُ الثَّقِيلَةُ', 'اللَّامُ الْمُزَحْلَقَةُ'],
          distractors: ['لَامُ الْأَمْرِ'],
        },
        {
          title: 'تَرْكِيب: ثَقِيلَةٌ أَمْ خَفِيفَةٌ؟',
          kind: 'tarkeeb',
          instruction: 'Identify which نُون تَأْكِيد each verb carries.',
          source: '﴿لَيُسْجَنَنَّ وَلَيَكُونًا مِنَ الصَّاغِرِينَ﴾',
          words: ['لَيُسْجَنَنَّ', 'وَلَيَكُونًا'],
          labels: ['النُّونُ الثَّقِيلَةُ', 'النُّونُ الْخَفِيفَةُ'],
          distractors: ['نُونُ النِّسْوَةِ'],
        },
        {
          title: 'تَرْكِيب: مَوْقِعُ كُلِّ لَامٍ',
          kind: 'tarkeeb',
          instruction: 'Match each لَام to the position it enters.',
          source: 'لَامُ الِابْتِدَاءِ / اللَّامُ الْمُزَحْلَقَةُ / لَامُ جَوَابِ الْقَسَمِ',
          words: ['لَامُ الِابْتِدَاءِ', 'اللَّامُ الْمُزَحْلَقَةُ', 'لَامُ جَوَابِ الْقَسَمِ'],
          labels: ['تَدْخُلُ عَلَى الْمُبْتَدَإِ', 'تَدْخُلُ عَلَىٰ خَبَرِ إِنَّ', 'تَدْخُلُ فِي جَوَابِ الْقَسَمِ'],
          distractors: ['تَدْخُلُ عَلَى الْمُضَافِ إِلَيْهِ'],
        },
        {
          title: 'تَرْكِيب: مَعَانِي قَدْ مَعَ الْمُضَارِعِ',
          kind: 'tarkeeb',
          instruction: 'Match each example to the meaning of قَدْ it illustrates.',
          source: '﴿قَدْ يَعْلَمُ اللَّهُ﴾ / قَدْ يَبْرَأُ الْمَرِيضُ / ﴿قَدْ نَرَىٰ تَقَلُّبَ وَجْهِكَ فِي السَّمَاءِ﴾ / قَدْ يَصْدُقُ الْكَذُوبُ',
          words: ['قَدْ يَعْلَمُ اللَّهُ', 'قَدْ يَبْرَأُ الْمَرِيضُ', 'قَدْ نَرَىٰ تَقَلُّبَ وَجْهِكَ', 'قَدْ يَصْدُقُ الْكَذُوبُ'],
          labels: ['التَّحْقِيقُ', 'التَّوَقُّعُ', 'التَّكْثِيرُ', 'التَّقْلِيلُ'],
          distractors: ['الِاسْتِفْهَامُ'],
        },
        {
          title: 'تَرْكِيب: تَصْنِيفُ أَحْرُفِ التَّأْكِيدِ',
          kind: 'tarkeeb',
          instruction: 'Classify each حَرْف: is it one of the five أَحْرُف تَأْكِيد or not؟',
          source: 'لَامُ الِابْتِدَاءِ / قَدْ / حَتَّىٰ / نُونَا التَّأْكِيدِ',
          words: ['لَامُ الِابْتِدَاءِ', 'قَدْ', 'حَتَّىٰ', 'نُونَا التَّأْكِيدِ'],
          labels: ['مِنْ أَحْرُفِ التَّأْكِيدِ', 'مِنْ أَحْرُفِ التَّأْكِيدِ', 'لَيْسَتْ مِنْهَا', 'مِنْ أَحْرُفِ التَّأْكِيدِ'],
          distractors: ['مِنْ أَحْرُفِ الْجَوَابِ'],
        },
      ],
    },
    // ---------------------------------------------------------------- L4
    {
      id: 'l4',
      title: 'أَحْرُفُ الشَّرْطِ غَيْرِ الْعَامِلَةِ',
      subtitle: 'Non-Governing Conditionals — لَوْ, لَوْلَا, لَوْمَا, and أَمَّا, none of which causes جَزْم',
      concepts: [
        {
          heading: 'الْأَرْبَعَةُ وَتَعْرِيفُ لَوْ',
          tldr: 'لَوْ، لَوْلَا، لَوْمَا، أَمَّا are conditional yet غَيْر عَامِلَة; لَوْ says the شَرْط did not occur and that it entails the جَوَاب.',
          body: `The fourth class of <bdi>الْحُرُوف غَيْر الْعَامِلَة</bdi> is <bdi>أَحْرُفُ الشَّرْطِ</bdi>, four in number: (1) <bdi>لَوْ</bdi>, (2) <bdi>لَوْلَا</bdi>, (3) <bdi>لَوْمَا</bdi>, (4) <bdi>أَمَّا</bdi>. Unlike إِنْ and its sisters, not one of the four puts a فِعْل into <bdi>جَزْم</bdi>, and that is exactly what "غَيْر عَامِلَة" is recording. <bdi>لَوْ</bdi> is classically defined as <bdi>امْتِنَاعُ الْجَوَابِ لِامْتِنَاعِ الشَّرْطِ</bdi>, the جَوَاب failing to occur because the شَرْط failed to occur. Ibn Hishām narrows that, and on his reading لَوْ asserts two things: (1) that the شَرْط did not occur, (2) that the شَرْط entails the جَوَاب. What it does not assert is that the جَوَاب itself failed to occur.`,
          examples: [
            { ar: 'لَوْ شِئْتَ أَهْلَكْتَهُمْ مِنْ قَبْلُ وَإِيَّايَ', en: 'Had You willed, You could have destroyed them before, and me', note: 'The classical reading in one line: the willing did not happen, so the destroying did not happen either.' },
            { ar: 'لَوْ تَابَ هَٰذَا الرَّجُلُ إِلَى اللَّهِ لَغَفَرَ اللَّهُ لَهُ', en: 'Had this man repented to Allah, Allah would have forgiven him', note: 'لَوْ tells you he did not repent and that repentance entails forgiveness; it does not tell you Allah withheld forgiveness.' },
          ],
          exercise: {
            prompt: `On Ibn Hishām's refinement, what does لَوْ indicate — and what does it NOT indicate؟`,
            kind: 'mcq',
            options: ['That the شَرْط did not occur and entails the جَوَاب, but NOT that the جَوَاب failed to occur', 'Only that the شَرْط occurred, and nothing about the جَوَاب', 'That the شَرْط and the جَوَاب both definitely failed to occur', 'That the جَوَاب occurred first, before the شَرْط'],
            correct: 0,
          },
        },
        {
          heading: 'لَوْ: زَمَنُهَا وَجَوَابُهَا',
          tldr: 'لَوْ throws the sentence into the past even over a مُضَارِع, and its affirmative جَوَاب usually — not always — carries the لَام.',
          body: `<bdi>لَوْ</bdi> points at the past. Entering a <bdi>فِعْل مُضَارِع</bdi>, it converts that verb's meaning to past however present its form may look. Its affirmative <bdi>جَوَاب</bdi> usually opens with a <bdi>لَام</bdi>, though the لَام may be dropped with no change of meaning. And the جَوَاب of لَوْ can in fact be true even where its شَرْط is false, which is precisely the point Ibn Hishām's refinement was protecting.`,
          examples: [
            { ar: 'لَوْ نَشَاءُ لَجَعَلْنَاهُ حُطَامًا', en: 'If We willed, We would surely make it debris', note: 'نَشَاءُ is مُضَارِع in form yet past in meaning under لَوْ, and the جَوَاب لَجَعَلْنَاهُ carries the لَام.' },
            { ar: 'لَوْ نَشَاءُ جَعَلْنَاهُ أُجَاجًا', en: 'If We willed, We would make it bitter', note: 'Nearly the same wording with no لَام on the جَوَاب — proof the لَام is usual, not obligatory.' },
            { ar: 'وَلَوْ أَنَّمَا فِي الْأَرْضِ مِنْ شَجَرَةٍ أَقْلَامٌ وَالْبَحْرُ يَمُدُّهُ مِنْ بَعْدِهِ سَبْعَةُ أَبْحُرٍ مَا نَفِدَتْ كَلِمَاتُ اللَّهِ', en: 'And if all the trees on earth were pens and the sea, with seven more seas behind it, were ink, the words of Allah would not be exhausted', note: 'The شَرْط is false — the trees are not pens — yet the جَوَاب is true regardless: the decisive text against the classical wording.' },
          ],
          exercise: {
            prompt: `Can the جَوَاب of لَوْ be true even though its شَرْط did NOT occur؟`,
            kind: 'mcq',
            options: ['Yes — ﴿وَلَوْ أَنَّمَا فِي الْأَرْضِ مِنْ شَجَرَةٍ أَقْلَامٌ… مَا نَفِدَتْ كَلِمَاتُ اللَّهِ﴾ is exactly that', 'No, the جَوَاب can never hold if the شَرْط failed to occur', 'Only where an اسْم follows لَوْ, never a فِعْل', 'Only in poetry, never in the Qurʾān'],
            correct: 0,
          },
        },
        {
          heading: 'لَوْ لِلتَّمَنِّي وَمَا يَتْبَعُهَا',
          tldr: 'لَوْ can also carry التَّمَنِّي, and a فِعْل must follow it — any اسْم that seems to follow belongs to an omitted verb.',
          body: `Besides the شَرْط, <bdi>لَوْ</bdi> can carry <bdi>التَّمَنِّي</bdi>, a wish for something now out of reach, and the tell is that no جَوَاب follows. Whatever its sense, a <bdi>فِعْل</bdi> has to come after it, since لَوْ never governs an اسْم directly. Where an اسْم appears to follow, one of two analyses restores the missing verb: (1) an explicit اسْم is the <bdi>مَعْمُول</bdi> of an omitted فِعْل which the following words explain, (2) an اسْم introduced by أَنَّ is the <bdi>فَاعِل</bdi> of an omitted فِعْل, تَقْدِيرُهُ لَوْ ثَبَتَ.`,
          examples: [
            { ar: 'فَلَوْ أَنَّ لَنَا كَرَّةً فَنَكُونَ مِنَ الْمُؤْمِنِينَ', en: 'If only we had a return, that we might be among the believers', note: 'No جَوَاب follows, so لَوْ here is لِلتَّمَنِّي rather than لِلشَّرْطِ.' },
            { ar: 'لَوْ زَيْدًا رَأَيْتُهُ لَأَكْرَمْتُهُ', en: 'Had I seen Zayd, I would have honoured him', note: 'زَيْدًا is مَنْصُوب, not مَرْفُوع, because it is the مَعْمُول of an omitted فِعْل explained by رَأَيْتُهُ — أَيْ لَوْ رَأَيْتُ زَيْدًا.' },
            { ar: 'وَلَوْ أَنَّهُمْ فَعَلُوا مَا يُوعَظُونَ بِهِ لَكَانَ خَيْرًا لَهُمْ', en: 'And had they done what they were exhorted to, it would have been better for them', note: 'The أَنَّ clause is the فَاعِل of an omitted ثَبَتَ, which is how لَوْ still gets the فِعْل it demands.' },
          ],
          exercise: {
            prompt: `What must follow لَوْ, and how is an apparent اسْم after it explained؟`,
            kind: 'mcq',
            options: ['A فِعْل must follow; any اسْم is really the مَعْمُول or the فَاعِل of an omitted فِعْل', 'An اسْم must always follow; a فِعْل is never valid after لَوْ', 'Nothing at all needs to follow لَوْ', 'Only a حَرْف جَرّ may follow لَوْ'],
            correct: 0,
          },
        },
        {
          heading: 'لَوْلَا وَلَوْمَا',
          tldr: 'لَوْلَا and لَوْمَا both mean امْتِنَاعُ الْجَوَابِ لِوُجُودِ الشَّرْطِ — the جَوَاب failed because the شَرْط was there, the mirror image of لَوْ.',
          body: `<bdi>لَوْلَا</bdi> is defined as <bdi>امْتِنَاعُ الْجَوَابِ لِوُجُودِ الشَّرْطِ</bdi>: the جَوَاب failed to happen precisely because the شَرْط was present. That is the mirror image of لَوْ, where the جَوَاب failed because the شَرْط was absent. لَوْلَا enters two clauses in a fixed shape: (1) first a <bdi>جُمْلَة اسْمِيَّة</bdi> whose خَبَر is obligatorily omitted, تَقْدِيرُهُ <bdi>مَوْجُودٌ</bdi>, (2) then a <bdi>جُمْلَة فِعْلِيَّة</bdi>, which is the جَوَاب. <bdi>لَوْمَا</bdi> carries the identical definition and works the same way.`,
          examples: [
            { ar: 'وَلَوْلَا فَضْلُ اللَّهِ عَلَيْكُمْ وَرَحْمَتُهُ مَا زَكَىٰ مِنْكُمْ مِنْ أَحَدٍ أَبَدًا', en: 'And were it not for the grace of Allah upon you and His mercy, not one of you would ever be purified', note: 'فَضْلُ is مَرْفُوع as مُبْتَدَأ, its خَبَر omitted with تَقْدِير مَوْجُودٌ; the grace exists, and that is why the جَوَاب was blocked.' },
            { ar: 'لَوْمَا التَّوْفِيقُ لَمَا عَمِلْنَا الصَّالِحَاتِ', en: 'Were it not for divine enabling, we would not have done good deeds', note: 'التَّوْفِيقُ is مَرْفُوع as مُبْتَدَأ on exactly the same pattern — لَوْمَا governs nothing.' },
          ],
          exercise: {
            prompt: `How does لَوْلَا's meaning differ from لَوْ's؟`,
            kind: 'mcq',
            options: ['لَوْلَا is امْتِنَاعُ الْجَوَابِ لِوُجُودِ الشَّرْطِ — the جَوَاب fails BECAUSE the شَرْط exists, the reverse of لَوْ', 'They mean exactly the same thing, with no difference at all', 'لَوْلَا only ever enters a جُمْلَة فِعْلِيَّة, never اسْمِيَّة', 'لَوْلَا always converts its فِعْل to الْمُضَارِع'],
            correct: 0,
          },
        },
        {
          heading: 'أَمَّا: وَظَائِفُهَا وَتَكْرَارُهَا',
          tldr: 'أَمَّا does three jobs at once — الشَّرْط, التَّفْصِيل, التَّوْكِيد — and is normally repeated once for each item being detailed.',
          body: `<bdi>أَمَّا</bdi> is a single حَرْف doing three jobs at once: (1) <bdi>الشَّرْط</bdi>, (2) <bdi>التَّفْصِيل</bdi>, spelling out items given beforehand in summary, (3) <bdi>التَّوْكِيد</bdi>. Its جَوَاب is always introduced by a <bdi>فَاء</bdi>. Because التَّفْصِيل is one of its jobs, أَمَّا is normally repeated, once for each item being spelled out. The repetition may still be dropped where one division carries the sense and the other is left understood.`,
          examples: [
            { ar: 'فَأَمَّا الَّذِينَ آمَنُوا فَيَعْلَمُونَ أَنَّهُ الْحَقُّ مِنْ رَبِّهِمْ وَأَمَّا الَّذِينَ كَفَرُوا فَيَقُولُونَ مَاذَا أَرَادَ اللَّهُ بِهَٰذَا مَثَلًا', en: 'As for those who believe, they know it is the truth from their Lord; and as for those who disbelieve, they say: what did Allah intend by this parable?', note: 'The three jobs together: a شَرْط sense, two groups detailed, and the whole assertion emphasised.' },
            { ar: 'كَذَّبَتْ ثَمُودُ وَعَادٌ بِالْقَارِعَةِ. فَأَمَّا ثَمُودُ فَأُهْلِكُوا بِالطَّاغِيَةِ. وَأَمَّا عَادٌ فَأُهْلِكُوا بِرِيحٍ صَرْصَرٍ عَاتِيَةٍ', en: 'Thamūd and ʿĀd denied the Striking Calamity. As for Thamūd, they were destroyed by the overpowering blast; and as for ʿĀd, they were destroyed by a screaming violent wind', note: 'Two items summarised first, then أَمَّا repeated once for each — التَّفْصِيل in its clearest form.' },
            { ar: 'فَأَمَّا الَّذِينَ آمَنُوا بِاللَّهِ وَاعْتَصَمُوا بِهِ فَسَيُدْخِلُهُمْ فِي رَحْمَةٍ مِنْهُ وَفَضْلٍ', en: 'As for those who believed in Allah and held fast to Him, He will admit them into mercy from Him and bounty', note: 'One أَمَّا only: the other division is understood, so the repetition is dropped.' },
          ],
          exercise: {
            prompt: `What three functions does أَمَّا combine؟`,
            kind: 'mcq',
            options: ['الشَّرْط، التَّفْصِيل، التَّوْكِيد', 'الْعَطْف، الِاسْتِثْنَاء، النِّدَاء', 'التَّمَنِّي، التَّرَجِّي، التَّشْبِيه', 'الْجَزْم، النَّصْب، الْجَرّ'],
            correct: 0,
          },
        },
        {
          heading: 'مَا بَيْنَ أَمَّا وَفَائِهَا وَامْتِنَاعُ الْجَزْمِ',
          tldr: 'Five things may stand between أَمَّا and its فَاء, and any نَصْب in that slot comes from some other عَامِل — none of this lesson\'s four particles governs at all.',
          body: `Between أَمَّا and the فَاء of its جَوَاب, one of five things may stand: (1) the <bdi>مُبْتَدَأ</bdi>, (2) the <bdi>خَبَر</bdi>, (3) a <bdi>جُمْلَة شَرْط</bdi>, (4) an اسْم governed by a word inside the جَوَاب, (5) an اسْم governed by an omitted word. The last two are the ones that put a مَنْصُوب noun in the slot, and that نَصْب never comes from أَمَّا itself. Which is the general rule of this whole lesson: لَوْ، لَوْلَا، لَوْمَا and أَمَّا govern nothing, and الْجَزْم stays with the أَدَوَات الشَّرْط الْعَامِلَة such as إِنْ and إِذْمَا.`,
          examples: [
            { ar: 'أَمَّا الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ فَلَهُمْ جَنَّاتُ الْمَأْوَىٰ', en: 'As for those who believed and did righteous deeds, theirs are the gardens of refuge', note: 'The مُبْتَدَأ الَّذِينَ fills the slot, and the فَاء then opens the جَوَاب.' },
            { ar: 'أَمَّا فِي الْبَيْتِ فَزَيْدٌ', en: 'As for in the house — Zayd is there', note: 'The خَبَر فِي الْبَيْتِ is fronted into the slot; زَيْدٌ after the فَاء is مَرْفُوع as the مُبْتَدَأ.' },
            { ar: 'فَأَمَّا الْيَتِيمَ فَلَا تَقْهَرْ', en: 'So as for the orphan, do not oppress him', note: 'الْيَتِيمَ is مَنْصُوب by تَقْهَرْ inside the جَوَاب, not by أَمَّا, which governs nothing.' },
          ],
          exercise: {
            prompt: `Do لَوْ، لَوْلَا، لَوْمَا and أَمَّا cause جَزْم the way إِنْ and its sisters do؟`,
            kind: 'mcq',
            options: ['No — they are غَيْر عَامِلَة; الْجَزْم stays with the أَدَوَات الشَّرْط الْعَامِلَة', 'Yes, all four cause جَزْم exactly as إِنْ does', 'Only أَمَّا causes جَزْم; the other three do not', 'They cause النَّصْب rather than الْجَزْم'],
            correct: 0,
          },
        },
      ],
      quiz: [
        {
          q: 'List the four أَحْرُف شَرْط غَيْر عَامِلَة.',
          options: ['لَوْ، لَوْلَا، لَوْمَا، أَمَّا', 'إِنْ، إِذْمَا، لَوْ، لَوْلَا', 'أَنْ، كَيْ، لَنْ، إِذَنْ', 'لَمْ، لَمَّا، لَامُ الْأَمْرِ، لَا النَّاهِيَةُ'],
          correct: 0,
        },
        {
          q: "Ibn Hishām's refined view of لَوْ says it does NOT indicate that:",
          options: ['the جَوَاب itself failed to occur', 'the شَرْط failed to occur', 'the شَرْط entails the جَوَاب', 'anything at all about the شَرْط'],
          correct: 0,
        },
        {
          q: '﴿لَوْ نَشَاءُ لَجَعَلْنَاهُ حُطَامًا﴾ shows لَوْ converting the مُضَارِع نَشَاءُ to:',
          options: ['past meaning', 'future meaning', 'imperative meaning', 'no change in meaning at all'],
          correct: 0,
        },
        {
          q: 'لَوْلَا is defined as:',
          options: ['امْتِنَاعُ الْجَوَابِ لِوُجُودِ الشَّرْطِ', 'امْتِنَاعُ الْجَوَابِ لِامْتِنَاعِ الشَّرْطِ', 'وُجُوبُ الْجَوَابِ لِوُجُودِ الشَّرْطِ', 'وُجُوبُ الشَّرْطِ لِوُجُودِ الْجَوَابِ'],
          correct: 0,
        },
        {
          q: '﴿فَأَمَّا الْيَتِيمَ فَلَا تَقْهَرْ﴾ shows what standing between أَمَّا and its فَاء?',
          options: ['An اسْم governed by a word inside the جَوَاب', 'الْمُبْتَدَأ', 'الْخَبَر', 'جُمْلَةُ الشَّرْطِ'],
          correct: 0,
        },
        {
          q: 'Do لَوْ، لَوْلَا، لَوْمَا and أَمَّا cause جَزْم?',
          options: ['No, all four are غَيْر عَامِلَة', 'Yes, all four do', 'Only لَوْ does', 'Only لَوْلَا and لَوْمَا do'],
          correct: 0,
        },
      ],
      bank: [
        {
          title: 'التَّعْرِيفُ التَّقْلِيدِيُّ لِلَوْ',
          kind: 'mcq',
          prompt: 'The classical one-line definition of لَوْ is:',
          options: ['امْتِنَاعُ الْجَوَابِ لِامْتِنَاعِ الشَّرْطِ', 'امْتِنَاعُ الْجَوَابِ لِوُجُودِ الشَّرْطِ', 'وُجُوبُ الْجَوَابِ لِوُجُودِ الشَّرْطِ', 'تَحَقُّقُ الشَّرْطِ وَالْجَوَابِ مَعًا'],
          correct: 0,
        },
        {
          title: 'مَا يُثْبِتُهُ لَوْ',
          kind: 'mcq',
          prompt: "On Ibn Hishām's refinement, which two things does لَوْ positively assert?",
          options: ['That the شَرْط did not occur, and that the شَرْط entails the جَوَاب', 'That the شَرْط occurred, and that the جَوَاب followed from it', 'That both the شَرْط and the جَوَاب failed to occur', 'That the جَوَاب occurred, whatever became of the شَرْط'],
          correct: 0,
        },
        {
          title: 'لَوْ شِئْتَ أَهْلَكْتَهُمْ',
          kind: 'mcq',
          prompt: '﴿لَوْ شِئْتَ أَهْلَكْتَهُمْ مِنْ قَبْلُ وَإِيَّايَ﴾ — what does لَوْ say about the destroying, on the classical reading?',
          options: ['It did not happen, because the willing did not happen', 'It happened, right after the willing', 'It may yet happen in the future', 'It happened without any willing at all'],
          correct: 0,
        },
        {
          title: 'لَوْ تَابَ هَٰذَا الرَّجُلُ',
          kind: 'mcq',
          prompt: 'لَوْ تَابَ هَٰذَا الرَّجُلُ إِلَى اللَّهِ لَغَفَرَ اللَّهُ لَهُ implies the man:',
          options: ['did not repent', 'did repent', 'was already forgiven', 'never sinned at all'],
          correct: 0,
        },
        {
          title: 'مَا لَا يُفِيدُهُ لَوْ',
          kind: 'mcq',
          prompt: 'لَوْ تَابَ هَٰذَا الرَّجُلُ إِلَى اللَّهِ لَغَفَرَ اللَّهُ لَهُ does NOT imply that Allah:',
          options: ['withheld forgiveness — He may forgive out of mercy regardless', 'exists', 'is capable of forgiving', 'created the man'],
          correct: 0,
        },
        {
          title: 'وُقُوعُ الْجَوَابِ مَعَ امْتِنَاعِ الشَّرْطِ',
          kind: 'mcq',
          prompt: "﴿وَلَوْ أَنَّمَا فِي الْأَرْضِ مِنْ شَجَرَةٍ أَقْلَامٌ… مَا نَفِدَتْ كَلِمَاتُ اللَّهِ﴾ shows that Allah's words:",
          options: ['are inexhaustible in fact, even though the hypothetical شَرْط never occurred', 'would be inexhaustible only if the trees really were pens', 'are limited in number', 'cannot be spoken of hypothetically at all'],
          correct: 0,
        },
        {
          title: 'جَوَابُ لَوْ بِاللَّامِ',
          kind: 'mcq',
          prompt: '﴿لَوْ نَشَاءُ لَجَعَلْنَاهُ حُطَامًا﴾ — what is the لَام on لَجَعَلْنَاهُ?',
          options: ['The لَام that usually enters the affirmative جَوَاب of لَوْ', 'لَام الِابْتِدَاء on a مُبْتَدَأ', 'لَام جَوَاب الْقَسَم', 'A لَام جَارَّة attached to the verb'],
          correct: 0,
        },
        {
          title: 'جَوَابُ لَوْ بِلَا لَامٍ',
          kind: 'mcq',
          prompt: '﴿لَوْ نَشَاءُ جَعَلْنَاهُ أُجَاجًا﴾ shows the affirmative جَوَاب of لَوْ:',
          options: ['without the usual لَام', 'with the usual لَام', 'turned into a question', 'negated outright'],
          correct: 0,
        },
        {
          title: 'لَوْ لِلتَّمَنِّي',
          kind: 'mcq',
          prompt: '﴿فَلَوْ أَنَّ لَنَا كَرَّةً فَنَكُونَ مِنَ الْمُؤْمِنِينَ﴾ shows لَوْ carrying the meaning of:',
          options: ['التَّمَنِّي', 'الشَّرْط الْمَحْض', 'التَّوْبِيخ', 'الِاسْتِفْهَام'],
          correct: 0,
        },
        {
          title: 'اسْمٌ صَرِيحٌ بَعْدَ لَوْ',
          kind: 'mcq',
          prompt: 'لَوْ زَيْدًا رَأَيْتُهُ لَأَكْرَمْتُهُ — زَيْدًا here is:',
          options: ['مَعْمُولٌ لِفِعْلٍ مَحْذُوفٍ يُفَسِّرُهُ مَا بَعْدَهُ', 'فَاعِلٌ لِفِعْلٍ مَحْذُوفٍ', 'مُبْتَدَأٌ', 'خَبَرٌ لِلَوْ'],
          correct: 0,
        },
        {
          title: 'اسْمٌ بِأَنَّ بَعْدَ لَوْ',
          kind: 'mcq',
          prompt: '﴿وَلَوْ أَنَّهُمْ فَعَلُوا مَا يُوعَظُونَ بِهِ لَكَانَ خَيْرًا لَهُمْ﴾ — أَنَّهُمْ here is:',
          options: ['فَاعِلٌ لِفِعْلٍ مَحْذُوفٍ, تَقْدِيرُهُ لَوْ ثَبَتَ', 'مَعْمُولٌ لِفِعْلٍ مَحْذُوفٍ', 'مُبْتَدَأٌ بِلَا خَبَرٍ', 'اسْمُ إِنَّ مُبَاشَرَةً'],
          correct: 0,
        },
        {
          title: 'إِعْرَابُ فَضْلُ بَعْدَ لَوْلَا',
          kind: 'mcq',
          prompt: 'In ﴿وَلَوْلَا فَضْلُ اللَّهِ عَلَيْكُمْ﴾, فَضْلُ is مَرْفُوع. What is it?',
          options: ['A مُبْتَدَأ of a جُمْلَة اسْمِيَّة whose خَبَر is omitted', 'A فَاعِل of an omitted فِعْل', 'The اسْم of لَوْلَا, which governs like إِنَّ', 'A مَفْعُول مُطْلَق'],
          correct: 0,
        },
        {
          title: 'لَوْلَا: تَقْدِيرُ الْخَبَرِ',
          kind: 'mcq',
          prompt: '﴿وَلَوْلَا فَضْلُ اللَّهِ عَلَيْكُمْ وَرَحْمَتُهُ مَا زَكَىٰ مِنْكُمْ مِنْ أَحَدٍ أَبَدًا﴾ — the omitted خَبَر of that first clause is taken to be:',
          options: ['مَوْجُودٌ', 'مَعْدُومٌ', 'مَذْكُورٌ', 'مُحْتَمَلٌ'],
          correct: 0,
        },
        {
          title: 'لَوْمَا وَمِثَالُهَا',
          kind: 'mcq',
          prompt: 'لَوْمَا التَّوْفِيقُ لَمَا عَمِلْنَا الصَّالِحَاتِ illustrates لَوْمَا meaning:',
          options: ['امْتِنَاعُ الْجَوَابِ لِوُجُودِ الشَّرْطِ', 'امْتِنَاعُ الْجَوَابِ لِامْتِنَاعِ الشَّرْطِ', 'تَحَقُّقُ الشَّرْطِ وَالْجَوَابِ مَعًا', 'التَّمَنِّي الْمَحْضُ'],
          correct: 0,
        },
        {
          title: 'أَمَّا: الْمُبْتَدَأُ بَيْنَهَا وَفَائِهَا',
          kind: 'mcq',
          prompt: '﴿أَمَّا الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ فَلَهُمْ جَنَّاتُ الْمَأْوَىٰ﴾ — what stands between أَمَّا and the فَاء?',
          options: ['الْمُبْتَدَأ, الَّذِينَ آمَنُوا', 'الْخَبَر', 'جُمْلَةُ الشَّرْطِ', 'An اسْم governed by an omitted word'],
          correct: 0,
        },
        {
          title: 'أَمَّا: جُمْلَةُ الشَّرْطِ بَيْنَهَا وَفَائِهَا',
          kind: 'mcq',
          prompt: '﴿فَأَمَّا إِنْ كَانَ مِنَ الْمُقَرَّبِينَ فَرَوْحٌ وَرَيْحَانٌ﴾ — what stands between أَمَّا and the فَاء?',
          options: ['جُمْلَةُ الشَّرْطِ, إِنْ كَانَ', 'الْمُبْتَدَأ', 'الْخَبَر', 'An اسْم governed by an omitted word'],
          correct: 0,
        },
        {
          title: 'أَمَّا: اسْمٌ بِعَامِلٍ مَحْذُوفٍ',
          kind: 'mcq',
          prompt: '﴿وَأَمَّا ثَمُودُ فَهَدَيْنَاهُمْ﴾, read with ثَمُودَ مَنْصُوبَة — what puts it into النَّصْب?',
          options: ['An omitted عَامِل, since أَمَّا itself governs nothing', 'أَمَّا, which governs النَّصْب on what follows it', 'The فَاء of the جَوَاب', 'هَدَيْنَاهُمْ, reaching across the فَاء'],
          correct: 0,
        },
        {
          title: 'تَكْرَارُ أَمَّا لِلتَّفْصِيلِ',
          kind: 'mcq',
          prompt: '﴿كَذَّبَتْ ثَمُودُ وَعَادٌ بِالْقَارِعَةِ. فَأَمَّا ثَمُودُ فَأُهْلِكُوا بِالطَّاغِيَةِ. وَأَمَّا عَادٌ فَأُهْلِكُوا بِرِيحٍ صَرْصَرٍ عَاتِيَةٍ﴾ shows أَمَّا repeated in order to:',
          options: ['detail (تَفْصِيل) two items summarised beforehand', 'negate both ثَمُود and عَاد', 'ask a question about both peoples', 'cast doubt on the punishment'],
          correct: 0,
        },
        {
          title: 'تَرْكُ التَّكْرَارِ',
          kind: 'mcq',
          prompt: '﴿فَأَمَّا الَّذِينَ آمَنُوا بِاللَّهِ وَاعْتَصَمُوا بِهِ فَسَيُدْخِلُهُمْ فِي رَحْمَةٍ مِنْهُ وَفَضْلٍ﴾ has only one أَمَّا. Why?',
          options: ['The repetition may be dropped where one division carries the sense and the other is understood', 'أَمَّا may never be repeated in the first place', 'Because the جَوَاب here is a فِعْل مُضَارِع', 'Because no summary was given before it'],
          correct: 0,
        },
        {
          title: 'هَٰذِهِ الْأَرْبَعَةُ غَيْرُ عَامِلَةٍ',
          kind: 'mcq',
          prompt: 'Do لَوْ، لَوْلَا، لَوْمَا and أَمَّا cause جَزْم, as إِنْ and إِذْمَا do?',
          options: ['No — they are غَيْر عَامِلَة', 'Yes, exactly as إِنْ does', 'Only أَمَّا does', 'Only لَوْلَا does'],
          correct: 0,
        },
        {
          title: 'تَرْكِيب: تَعْرِيفُ كُلِّ حَرْفٍ',
          kind: 'tarkeeb',
          instruction: 'Match each حَرْف to its defining formula.',
          source: 'لَوْ / لَوْلَا / أَمَّا',
          words: ['لَوْ', 'لَوْلَا', 'أَمَّا'],
          labels: ['امْتِنَاعُ الْجَوَابِ لِامْتِنَاعِ الشَّرْطِ', 'امْتِنَاعُ الْجَوَابِ لِوُجُودِ الشَّرْطِ', 'الشَّرْطُ وَالتَّفْصِيلُ وَالتَّوْكِيدُ'],
          distractors: ['الْجَمْعُ مُطْلَقًا'],
        },
        {
          title: 'تَرْكِيب: هَلْ وَقَعَ الْفِعْلُ؟',
          kind: 'tarkeeb',
          instruction: 'In لَوْ تَابَ هَٰذَا الرَّجُلُ لَغَفَرَ اللَّهُ لَهُ, say what لَوْ actually tells you about each.',
          source: 'لَوْ تَابَ هَٰذَا الرَّجُلُ إِلَى اللَّهِ لَغَفَرَ اللَّهُ لَهُ',
          words: ['التَّوْبَةُ', 'الْمَغْفِرَةُ'],
          labels: ['لَمْ تَقَعْ', 'لَا يَدُلُّ عَلَيْهَا الْكَلَامُ'],
          distractors: ['وَقَعَتْ يَقِينًا'],
        },
        {
          title: 'تَرْكِيب: الِاسْمُ بَعْدَ لَوْ',
          kind: 'tarkeeb',
          instruction: 'Classify the اسْم standing after لَوْ in each example.',
          source: 'لَوْ زَيْدًا رَأَيْتُهُ لَأَكْرَمْتُهُ / ﴿وَلَوْ أَنَّهُمْ فَعَلُوا مَا يُوعَظُونَ بِهِ﴾',
          words: ['زَيْدًا', 'أَنَّهُمْ فَعَلُوا'],
          labels: ['مَعْمُولٌ لِفِعْلٍ مَحْذُوفٍ', 'فَاعِلٌ لِفِعْلٍ مَحْذُوفٍ'],
          distractors: ['مُبْتَدَأٌ'],
        },
        {
          title: 'تَرْكِيب: جَوَابُ لَوْ بِاللَّامِ أَمْ بِدُونِهَا؟',
          kind: 'tarkeeb',
          instruction: 'Say whether the affirmative جَوَاب of لَوْ carries the لَام in each āyah.',
          source: '﴿لَوْ نَشَاءُ لَجَعَلْنَاهُ حُطَامًا﴾ / ﴿لَوْ نَشَاءُ جَعَلْنَاهُ أُجَاجًا﴾',
          words: ['لَجَعَلْنَاهُ حُطَامًا', 'جَعَلْنَاهُ أُجَاجًا'],
          labels: ['بِاللَّامِ', 'بِدُونِ اللَّامِ'],
          distractors: ['مَنْفِيٌّ بِمَا'],
        },
        {
          title: 'تَرْكِيب: مَا بَيْنَ أَمَّا وَفَائِهَا',
          kind: 'tarkeeb',
          instruction: 'Classify what stands between أَمَّا and its فَاء in each example.',
          source: '﴿أَمَّا الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ فَلَهُمْ جَنَّاتُ الْمَأْوَىٰ﴾ / أَمَّا فِي الْبَيْتِ فَزَيْدٌ / ﴿فَأَمَّا إِنْ كَانَ مِنَ الْمُقَرَّبِينَ فَرَوْحٌ وَرَيْحَانٌ﴾ / ﴿فَأَمَّا الْيَتِيمَ فَلَا تَقْهَرْ﴾',
          words: ['الَّذِينَ آمَنُوا', 'فِي الْبَيْتِ', 'إِنْ كَانَ', 'الْيَتِيمَ'],
          labels: ['الْمُبْتَدَأُ', 'الْخَبَرُ', 'جُمْلَةُ الشَّرْطِ', 'اسْمٌ بِعَامِلٍ فِي الْجَوَابِ'],
          distractors: ['اسْمٌ بِعَامِلٍ مَحْذُوفٍ'],
        },
        {
          title: 'تَرْكِيب: عَامِلَةٌ أَمْ غَيْرُ عَامِلَةٍ؟',
          kind: 'tarkeeb',
          instruction: 'Classify each أَدَاة شَرْط: does it cause جَزْم or not؟',
          source: 'لَوْ / إِنْ / أَمَّا / إِذْمَا',
          words: ['لَوْ', 'إِنْ', 'أَمَّا', 'إِذْمَا'],
          labels: ['غَيْرُ عَامِلَةٍ', 'عَامِلَةٌ', 'غَيْرُ عَامِلَةٍ', 'عَامِلَةٌ'],
          distractors: ['نَاصِبَةٌ'],
        },
      ],
    },
  ],
};
