// Module 06 — النَّوَاصِب وَالْجَوَازِم (Subjunctive- and Jussive-Forcing Letters)
//
// Content is adapted from a bilingual Anki deck
// (النَحْوُ__2 الْعَامِلِ وَغَيْرِ الْعَامِلِ__2 الْحَرْفِ__1 الْحَرْفِ الْعَامِلِ__3 الحرف العامل الى الفعل.apkg,
// 28 notes) and cross-checked against the Daram Learn material for the same
// chapter — the lesson `lessons/m1-bab2c.js` (نواصب الفعل وجوازمه, book
// pp. 72–80) and the game bank `game-bank/3-harf-amil.js` (§17 نواصب المضارع,
// §18 جوازم المضارع), from which several worked `examples`, the rationales
// folded into example notes, and a number of bank questions are drawn. Every
// Arabic word is fully vocalised: in a grammar text a wrong harakah teaches
// wrong grammar, and this chapter is entirely about the ending of a مضارع —
// فتحة or حذف النون for نصب, سكون or حذف حرف العلة / حذف النون for جزم.
// This is a smaller source deck than Modules 04–05 (28 notes vs. 62–129), so
// it divides into 3 lessons rather than 4–6 — the topic itself (عامل حروف
// that reach into الفعل, not الاسم) is simply narrower.
//
// The source deck covers الحرف العامل الى الفعل (§3 of الحرف العامل, itself
// §2 of الحرف, itself §2 of العامل وغير العامل): the four نواصب المضارع
// (أنْ، كي، لن، إذن) with the rules for إضمار أنْ, and جوازم المضارع — the
// four جازمة لفعل واحد (لم، لما، لام الأمر، لا الناهية) and the two جازمة
// لفعلين (إنْ، إذما) governing a شرط + جواب.

export default {
  id: '06',
  title: 'النَّوَاصِب وَالْجَوَازِم',
  heading: 'الْعَامِل وَغَيْر الْعَامِل',
  subheading: 'الْحَرْف الْعَامِل',
  blurb: 'The عَامِل حُرُوف that reach into the فِعْل rather than the اسْم: the four نَوَاصِب الْمُضَارِع (أَنْ، كَيْ، لَنْ، إِذَنْ) with the rules of إِضْمَار أَنْ, and the جَوَازِم — لَمْ، لَمَّا، لَامُ الْأَمْرِ، لَا النَّاهِيَةُ — plus إِنْ وَإِذْمَا governing a شَرْط and its جَوَاب.',
  lessons: [
    // ---------------------------------------------------------------- L1
    {
      id: 'l1',
      title: 'نَوَاصِب الْمُضَارِع: تَمْهِيد، أَنْ، وَكَيْ',
      subtitle: 'Subjunctive Particles — the two classes of حُرُوف that govern the فِعْل, then أَنِ النَّاصِبَة, كَيْ and لَنْ',
      concepts: [
        {
          heading: 'حُرُوفٌ تَعْمَلُ فِي الْفِعْلِ: النَّوَاصِبُ وَالْجَوَازِمُ',
          tldr: 'The حُرُوف that govern a فِعْل fall into two classes: النَّوَاصِب put the مُضَارِع in نَصْب, الْجَوَازِم put it in جَزْم.',
          body: `Every عَامِل حَرْف so far has reached into an <bdi>اسْم</bdi>; this class reaches into the <bdi>فِعْل</bdi>, and only ever into the <bdi>مُضَارِع</bdi>. They divide in two: (1) حُرُوف that put the مُضَارِع in <bdi>نَصْب</bdi> — <bdi>النَّوَاصِب</bdi>, (2) حُرُوف that put it in <bdi>جَزْم</bdi> — <bdi>الْجَوَازِم</bdi>. The نَوَاصِب are four: (1) <bdi>أَنْ</bdi>, (2) <bdi>كَيْ</bdi>, (3) <bdi>لَنْ</bdi>, (4) <bdi>إِذَنْ</bdi>. No حَرْف produces <bdi>رَفْع</bdi> on a مُضَارِع, because رَفْع is the state it is already in when nothing governs it. Read the ending, not just the particle: نَصْب shows as a <bdi>فَتْحَة</bdi>, or as <bdi>حَذْفُ النُّونِ</bdi> in الْأَفْعَال الْخَمْسَة.`,
          examples: [
            { ar: 'أَنْ يَغْفِرَ اللَّهُ لَكُمْ', en: 'that Allah forgive you', note: 'أَنْ is a نَاصِب — the فَتْحَة on يَغْفِرَ is the نَصْب it produced' },
            { ar: 'لَمْ يَلِدْ وَلَمْ يُولَدْ', en: 'He did not beget, nor was He begotten', note: 'لَمْ is a جَازِم — the سُكُون on يَلِدْ is the mark of جَزْم' },
            { ar: 'لَنْ يَخْلُقُوا ذُبَابًا', en: 'they will not create a fly', note: 'a فِعْل مِنَ الْأَفْعَالِ الْخَمْسَةِ shows نَصْب by حَذْفُ النُّونِ — يَخْلُقُونَ becomes يَخْلُقُوا' },
          ],
          exercise: {
            prompt: `A مُضَارِع is مَرْفُوع when nothing governs it. Which pair of states do the حُرُوف of this chapter produce on it instead?`,
            kind: 'mcq',
            options: ['النَّصْب and الْجَزْم', 'الرَّفْع and النَّصْب', 'الْجَرّ and النَّصْب', 'الرَّفْع and الْجَزْم'],
            correct: 0,
          },
        },
        {
          heading: 'أَنِ النَّاصِبَةُ (الْمَصْدَرِيَّةُ)',
          tldr: 'أَنِ النَّاصِبَة is a حَرْف مَصْدَرِيّ: it and the فِعْل after it read as one مَصْدَر, and that مُضَارِع carries the فَتْحَة of نَصْب.',
          body: `<bdi>أَنِ النَّاصِبَة</bdi> is a <bdi>حَرْف مَصْدَرِيّ</bdi>: أَنْ plus the فِعْل after it is read as a single <bdi>مَصْدَر</bdi>, so <bdi>أَنْ يَغْفِرَ</bdi> stands for <bdi>الْمَغْفِرَة</bdi>. That is why the phrase can fill a slot an اسْم fills, and why the مُضَارِع after it carries the فَتْحَة of نَصْب. The same two letters also spell <bdi>أَنِ الْمُخَفَّفَة</bdi>, lightened from <bdi>أَنَّ</bdi>, so the فِعْل standing before them is what settles which one you are looking at: (1) after a فِعْل قَلْب of certainty (<bdi>يَقِين</bdi>) it is الْمُخَفَّفَة, (2) after a فِعْل قَلْب of supposition (<bdi>ظَنّ</bdi>) both readings stand, (3) with no فِعْل قَلْب before it at all it is الْمَصْدَرِيَّة النَّاصِبَة. The ending confirms the call: after الْمُخَفَّفَة the فِعْل stays مَرْفُوع, after النَّاصِبَة it is مَنْصُوب.`,
          examples: [
            { ar: '﴿أَلَا تُحِبُّونَ أَنْ يَغْفِرَ اللَّهُ لَكُمْ﴾', en: 'Do you not love that Allah should forgive you?', note: 'أَنْ الْمَصْدَرِيَّة — يَغْفِرَ is مَنْصُوب by a فَتْحَة, and أَنْ يَغْفِرَ reads as الْمَغْفِرَة' },
            { ar: '﴿عَلِمَ أَنْ سَيَكُونُ مِنْكُمْ مَرْضَىٰ﴾', en: 'He knows that there will be among you some who are ill', note: 'عَلِمَ is a فِعْل يَقِين, so this أَنْ is الْمُخَفَّفَة — يَكُونُ stays مَرْفُوع, and the س of التَّنْفِيس separates them' },
            { ar: '﴿نَطْمَعُ أَنْ يَغْفِرَ لَنَا رَبُّنَا خَطَايَانَا﴾', en: 'we hope that our Lord will forgive us our sins', note: 'نَطْمَعُ is no فِعْل قَلْب, so أَنْ is الْمَصْدَرِيَّة النَّاصِبَة — hence يَغْفِرَ with a فَتْحَة' },
          ],
          clarification: `Why does certainty force the reading الْمُخَفَّفَة? أَنِ الْمَصْدَرِيَّة points its فِعْل at something still to come, so it does not sit under a فِعْل reporting a settled fact. عَلِمَ reports exactly that, so أَنْ after it cannot be الْمَصْدَرِيَّة. حَسِبَ only supposes, so it leaves both doors open. A second tell is visible on the page: أَنِ الْمُخَفَّفَة is often held off from its فِعْل by a separator — (1) <bdi>قَدْ</bdi>, (2) a <bdi>حَرْف تَنْفِيس</bdi> like the <bdi>س</bdi> of <bdi>سَيَكُونُ</bdi>, (3) a حَرْف نَفْي such as <bdi>لَمْ</bdi> or <bdi>لَا</bdi>. أَنِ النَّاصِبَة is never separated from its فِعْل that way.`,
          exercise: {
            prompt: `Two أَفْعَال قَلْب sit before أَنْ: عَلِمَ and حَسِبَ. What does each of them do to the reading of أَنْ after it?`,
            kind: 'mcq',
            options: ['عَلِمَ (يَقِين) forces الْمُخَفَّفَة; حَسِبَ (ظَنّ) leaves both readings open', 'Both force الْمُخَفَّفَة, with no difference between them', 'Both force الْمَصْدَرِيَّة, since a فِعْل قَلْب never affects أَنْ', 'عَلِمَ leaves both open; حَسِبَ forces الْمَصْدَرِيَّة'],
            correct: 0,
          },
        },
        {
          heading: 'كَيْ',
          tldr: 'كَيْ is a حَرْف مَصْدَرِيّ لِلتَّعْلِيل — it puts the مُضَارِع in نَصْب and names the purpose, with a لَام الْجَرّ before it, written or مُقَدَّرَة.',
          body: `<bdi>كَيْ</bdi> is a <bdi>حَرْف مَصْدَرِيّ لِلتَّعْلِيل</bdi>. It does the same مَصْدَر-making work as أَنْ, and adds to it the sense of purpose — the reason the first act was done at all. A <bdi>لَامُ الْجَرّ</bdi> stands before it in the analysis, in one of two shapes: (1) written out, as in <bdi>لِكَيْلَا</bdi>, (2) unwritten and <bdi>مُقَدَّرَة</bdi>, so that <bdi>كَيْ تَقَرَّ</bdi> is read as <bdi>لِكَيْ تَقَرَّ</bdi>. Either way the مُضَارِع after كَيْ takes the فَتْحَة of نَصْب.`,
          examples: [
            { ar: '﴿فَرَجَعْنَاكَ إِلَىٰ أُمِّكَ كَيْ تَقَرَّ عَيْنُهَا﴾', en: 'so We returned you to your mother, that her eye might be comforted', note: 'كَيْ gives the purpose of the returning; تَقَرَّ is مَنْصُوب by it, and the لَام before كَيْ is مُقَدَّرَة' },
            { ar: '﴿لِكَيْلَا يَعْلَمَ بَعْدَ عِلْمٍ شَيْئًا﴾', en: 'so that he may know nothing after having known', note: 'here the لَام الْجَرّ is written out — لِـ plus كَيْ plus لَا — and يَعْلَمَ still carries the فَتْحَة of نَصْب' },
          ],
          exercise: {
            prompt: `No لَام is written before كَيْ in ﴿كَيْ تَقَرَّ عَيْنُهَا﴾. How do the نُحَاة read the phrase?`,
            kind: 'mcq',
            options: ['As لِكَيْ, with the لَامُ الْجَرّ مُقَدَّرَة', 'As كَيْ with no لَام in the analysis at all', 'As أَنْ, with كَيْ merely standing in for it', 'As a كَيْ جَارَّة, which would make تَقَرَّ مَجْرُورًا'],
            correct: 0,
          },
        },
        {
          heading: 'لَنْ',
          tldr: 'لَنْ puts the مُضَارِع in نَصْب and emphatically negates the future; it means "never" only where a قَرِينَة says so.',
          body: `<bdi>لَنْ</bdi> is <bdi>لِتَأْكِيدِ النَّفْيِ فِي الْمُسْتَقْبَلِ</bdi> — it denies that a thing will happen, and denies it emphatically. Of the four نَوَاصِب it is the only one that is a <bdi>حَرْف نَفْي</bdi> as well as a نَاصِب. It is often read as <bdi>التَّأْبِيد</bdi>, a negation with no end to it, but that sense comes from the surrounding <bdi>قَرِينَة</bdi>, not from لَنْ itself. Taken alone لَنْ says "will not", not "will never".`,
          examples: [
            { ar: '﴿فَلَنْ أُكَلِّمَ الْيَوْمَ إِنْسِيًّا﴾', en: 'so I shall not speak to any human being today', note: 'أُكَلِّمَ carries the فَتْحَة of نَصْب, and الْيَوْمَ pins the نَفْي to a single day — no تَأْبِيد here' },
            { ar: '﴿لَنْ يَخْلُقُوا ذُبَابًا﴾', en: 'they will not create a fly', note: 'read as perpetual, but on the strength of the قَرِينَة; يَخْلُقُوا shows its نَصْب by حَذْفُ النُّونِ' },
          ],
          exercise: {
            prompt: `Both ﴿فَلَنْ أُكَلِّمَ الْيَوْمَ إِنْسِيًّا﴾ and ﴿لَنْ يَخْلُقُوا ذُبَابًا﴾ use لَنْ, yet only the second is read as perpetual. What accounts for that?`,
            kind: 'mcq',
            options: ['The قَرِينَة of the context supplies the تَأْبِيد, not لَنْ itself', 'لَنْ always means تَأْبِيد, and الْيَوْمَ in the first is merely redundant', 'لَنْ means تَأْبِيد only before a فِعْل مِنَ الْأَفْعَالِ الْخَمْسَةِ', 'The second negates the past, and a negated past can never be undone'],
            correct: 0,
          },
        },
      ],
      quiz: [
        {
          q: 'How many نَوَاصِب does the مُضَارِع have, and what state do they put it in?',
          options: ['أَرْبَعَة, and they put it in النَّصْب', 'ثَلَاثَة, and they put it in النَّصْب', 'أَرْبَعَة, and they put it in الْجَزْم', 'سِتَّة, and they put it in النَّصْب'],
          correct: 0,
        },
        {
          q: 'List the four نَوَاصِب الْمُضَارِع.',
          options: ['أَنْ، كَيْ، لَنْ، إِذَنْ', 'لَمْ، لَمَّا، لَا النَّاهِيَةُ، لَامُ الْأَمْرِ', 'إِنْ، إِذْمَا، لَوْ، لَوْلَا', 'هَلْ، مَا، لَا، أَمْ'],
          correct: 0,
        },
        {
          q: '﴿نَطْمَعُ أَنْ يَغْفِرَ لَنَا رَبُّنَا خَطَايَانَا﴾ — أَنْ here, with no فِعْل قَلْب before it, is:',
          options: ['مَصْدَرِيَّة نَاصِبَة', 'مُخَفَّفَة مِنْ أَنَّ', 'زَائِدَة', 'شَرْطِيَّة'],
          correct: 0,
        },
        {
          q: 'كَيْ is a حَرْف مَصْدَرِيّ carrying the added sense of:',
          options: ['التَّعْلِيل', 'التَّوَقُّع', 'الِاسْتِدْرَاك', 'التَّمَنِّي'],
          correct: 0,
        },
        {
          q: '﴿لِكَيْلَا يَعْلَمَ بَعْدَ عِلْمٍ شَيْئًا﴾ shows كَيْ preceded by an explicit:',
          options: ['لَامُ الْجَرِّ', 'لَامُ الْأَمْرِ', 'لَامُ الْقَسَمِ', 'لَامُ الِابْتِدَاءِ'],
          correct: 0,
        },
        {
          q: 'In ﴿فَلَنْ أُكَلِّمَ الْيَوْمَ إِنْسِيًّا﴾, what is the إِعْرَاب of أُكَلِّمَ and the sign carrying it?',
          options: ['مَنْصُوب, by a فَتْحَة', 'مَرْفُوع, by a ضَمَّة', 'مَجْزُوم, by a سُكُون', 'مَنْصُوب, by حَذْفِ النُّونِ'],
          correct: 0,
        },
      ],
      bank: [
        {
          title: 'نَوَاصِبُ أَمْ جَوَازِمُ؟',
          kind: 'mcq',
          prompt: 'The حُرُوف that put the مُضَارِع in نَصْب are called:',
          options: ['النَّوَاصِب', 'الْجَوَازِم', 'الْعَوَامِل الْجَازِمَة', 'حُرُوف الْعَطْفِ'],
          correct: 0,
        },
        {
          title: 'جَوَازِمُ أَمْ نَوَاصِبُ؟',
          kind: 'mcq',
          prompt: 'The حُرُوف that put the مُضَارِع in جَزْم are called:',
          options: ['الْجَوَازِم', 'النَّوَاصِب', 'حُرُوف التَّوْكِيدِ', 'حُرُوف الِاسْتِثْنَاءِ'],
          correct: 0,
        },
        {
          title: 'لِمَ لَا حَرْفَ لِلرَّفْعِ؟',
          kind: 'mcq',
          prompt: 'حُرُوف exist that put the مُضَارِع in نَصْب and in جَزْم, but none puts it in رَفْع. Why is that?',
          options: ['رَفْع is the state the مُضَارِع is already in when nothing governs it', 'رَفْع belongs to the اسْم alone and never to a فِعْل', 'A مُضَارِع is مَبْنِيّ, so رَفْع cannot appear on it', 'The حُرُوف of رَفْع exist but operate only on the مَاضِي'],
          correct: 0,
        },
        {
          title: 'أَنْ حَرْفُ مَصْدَرٍ',
          kind: 'mcq',
          prompt: '﴿أَلَا تُحِبُّونَ أَنْ يَغْفِرَ اللَّهُ لَكُمْ﴾ — أَنْ here is:',
          options: ['حَرْف مَصْدَرِيّ (النَّاصِبَة)', 'حَرْف نَفْيٍ', 'حَرْف جَوَابٍ', 'حَرْف تَنْبِيهٍ'],
          correct: 0,
        },
        {
          title: 'أَنْ وَفِعْلُهَا',
          kind: 'mcq',
          prompt: 'أَنْ النَّاصِبَة together with the فِعْل after it is read as:',
          options: ['a single مَصْدَر — أَنْ يَغْفِرَ standing for الْمَغْفِرَة', 'a جُمْلَة شَرْطِيَّة with its جَوَاب left out', 'a فِعْل أَمْر addressed to the hearer', 'a صِفَة describing what came before it'],
          correct: 0,
        },
        {
          title: 'عَلَامَةُ النَّصْبِ فِي يَغْفِرَ',
          kind: 'mcq',
          prompt: 'In ﴿أَنْ يَغْفِرَ اللَّهُ لَكُمْ﴾, what marks يَغْفِرَ as مَنْصُوب?',
          options: ['The فَتْحَة on its last letter', 'The سُكُون on its last letter', 'حَذْفُ النُّونِ from its end', 'حَذْفُ حَرْفِ الْعِلَّةِ from its end'],
          correct: 0,
        },
        {
          title: 'أَنْ بَعْدَ فِعْلِ يَقِينٍ',
          kind: 'mcq',
          prompt: '﴿عَلِمَ أَنْ سَيَكُونُ مِنْكُمْ مَرْضَىٰ﴾ — أَنْ here, after a فِعْل يَقِين, is:',
          options: ['مُخَفَّفَة مِنْ أَنَّ', 'مَصْدَرِيَّة نَاصِبَة', 'زَائِدَة', 'شَرْطِيَّة جَازِمَة'],
          correct: 0,
        },
        {
          title: 'الْفَاصِلُ بَعْدَ أَنِ الْمُخَفَّفَةِ',
          kind: 'mcq',
          prompt: 'A separator standing between أَنْ and its فِعْل is a tell that the أَنْ is الْمُخَفَّفَة. Which set names those separators?',
          options: ['قَدْ, a حَرْف تَنْفِيس, or a حَرْف نَفْي', 'A قَسَم, or a ظَرْف', 'A حَرْف عَطْف, or a حَرْف جَرّ', 'A فِعْل أَمْر, or a نِدَاء'],
          correct: 0,
        },
        {
          title: 'أَنْ بَعْدَ فِعْلِ ظَنٍّ',
          kind: 'mcq',
          prompt: '﴿وَحَسِبُوا أَلَّا تَكُونَ فِتْنَةٌ﴾ — after this فِعْل ظَنّ, أَنْ can be read as:',
          options: ['either الْمُخَفَّفَة or الْمَصْدَرِيَّة', 'الْمُخَفَّفَة only, never الْمَصْدَرِيَّة', 'الْمَصْدَرِيَّة only, never الْمُخَفَّفَة', 'Neither reading is available here'],
          correct: 0,
        },
        {
          title: 'بِلَا فِعْلِ قَلْبٍ',
          kind: 'mcq',
          prompt: 'When no فِعْل قَلْب at all stands before أَنْ, it is read as:',
          options: ['مَصْدَرِيَّة نَاصِبَة', 'مُخَفَّفَة مِنْ أَنَّ', 'زَائِدَة بِلَا مَعْنًى', 'نَافِيَة'],
          correct: 0,
        },
        {
          title: 'كَيْ لِلتَّعْلِيلِ',
          kind: 'mcq',
          prompt: '﴿فَرَجَعْنَاكَ إِلَىٰ أُمِّكَ كَيْ تَقَرَّ عَيْنُهَا﴾ illustrates which meaning of كَيْ?',
          options: ['التَّعْلِيل', 'التَّوَقُّع', 'الِاسْتِدْرَاك', 'التَّمَنِّي'],
          correct: 0,
        },
        {
          title: 'مَا تَزِيدُهُ كَيْ عَلَى أَنْ',
          kind: 'mcq',
          prompt: 'أَنْ and كَيْ are both حَرْف مَصْدَرِيّ and both give نَصْب. What does كَيْ add that أَنْ does not?',
          options: ['The sense of purpose, التَّعْلِيل', 'The sense of negation, النَّفْي', 'The sense of response, الْجَوَاب', 'The sense of condition, الشَّرْط'],
          correct: 0,
        },
        {
          title: 'لَامٌ مُقَدَّرَةٌ قَبْلَ كَيْ',
          kind: 'mcq',
          prompt: 'In ﴿كَيْ تَقَرَّ عَيْنُهَا﴾, the لَام before كَيْ is:',
          options: ['مُقَدَّرَة — the phrase is read as لِكَيْ', 'Written out in full', 'Impossible — no لَام ever precedes كَيْ', 'A لَام الْقَسَمِ'],
          correct: 0,
        },
        {
          title: 'كَيْ حَرْفَ جَرٍّ',
          kind: 'mcq',
          prompt: 'Some نُحَاة count كَيْ among the حُرُوف الْجَرّ. In which use?',
          options: ['When it means the لَام of reason and enters upon مَا الِاسْتِفْهَامِيَّة — كَيْمَهْ عَصَيْتَ اللَّهَ؟', 'Whenever a مُضَارِع مَنْصُوب follows it', 'Whenever the لَام is written before it', 'Whenever it opens the sentence'],
          correct: 0,
        },
        {
          title: 'لَنْ وَنَفْيُ الْمُسْتَقْبَلِ',
          kind: 'mcq',
          prompt: '﴿فَلَنْ أُكَلِّمَ الْيَوْمَ إِنْسِيًّا﴾ illustrates لَنْ:',
          options: ['emphasising the نَفْي of the future', 'negating the past', 'forbidding an act', 'expressing a hope'],
          correct: 0,
        },
        {
          title: 'لَنْ وَالتَّأْبِيدُ',
          kind: 'mcq',
          prompt: 'لَنْ indicates التَّأْبِيد only when:',
          options: ['a قَرِينَة in the context supports that reading', 'it is repeated twice in a row', 'it stands before a فِعْل أَمْر', 'a لَا زَائِدَة follows it'],
          correct: 0,
        },
        {
          title: 'النَّاصِبُ النَّافِي',
          kind: 'mcq',
          prompt: 'Which of the four نَوَاصِب is a حَرْف نَفْي as well as a نَاصِب?',
          options: ['لَنْ', 'أَنْ', 'كَيْ', 'إِذَنْ'],
          correct: 0,
        },
        {
          title: 'نَاصِبٌ بِنَفْسِهِ',
          kind: 'mcq',
          prompt: 'Which set lists حُرُوف that give نَصْب by themselves, rather than places where أَنْ is merely implied?',
          options: ['أَنْ، كَيْ، لَنْ، إِذَنْ', 'حَتَّى، لَامُ الْجُحُودِ، أَوْ، فَاءُ السَّبَبِيَّةِ', 'لَمْ، لَمَّا، لَامُ الْأَمْرِ، لَا النَّاهِيَةُ', 'إِنْ، إِذْمَا، لَوْ، لَوْلَا'],
          correct: 0,
        },
        {
          title: 'لَيْسَ مِنَ النَّوَاصِبِ',
          kind: 'mcq',
          prompt: 'Which of these is NOT one of the four نَوَاصِب, even though a مُضَارِع مَنْصُوب often follows it?',
          options: ['حَتَّى', 'أَنْ', 'كَيْ', 'إِذَنْ'],
          correct: 0,
        },
        {
          title: 'نَصْبُ الْأَفْعَالِ الْخَمْسَةِ',
          kind: 'mcq',
          prompt: 'In ﴿لَنْ يَخْلُقُوا ذُبَابًا﴾, what shows that يَخْلُقُوا is مَنْصُوب?',
          options: ['حَذْفُ النُّونِ, since it is مِنَ الْأَفْعَالِ الْخَمْسَةِ', 'The فَتْحَة on its last letter', 'The سُكُون on its last letter', 'The وَاو of الْجَمَاعَة attached to it'],
          correct: 0,
        },
        {
          title: 'تَرْكِيب: تَصْنِيفُ النَّوَاصِبِ الْأَرْبَعَةِ',
          kind: 'tarkeeb',
          instruction: 'Classify each حَرْف by its core meaning.',
          source: 'أَنْ / كَيْ / لَنْ / إِذَنْ',
          words: ['أَنْ', 'كَيْ', 'لَنْ', 'إِذَنْ'],
          labels: ['حَرْفٌ مَصْدَرِيٌّ', 'حَرْفٌ لِلتَّعْلِيلِ', 'تَأْكِيدُ نَفْيِ الْمُسْتَقْبَلِ', 'حَرْفُ جَوَابٍ'],
          distractors: ['حَرْفُ جَزْمٍ'],
        },
        {
          title: 'تَرْكِيب: أَنْ بَعْدَ أَفْعَالِ الْقُلُوبِ',
          kind: 'tarkeeb',
          instruction: 'Classify how أَنْ is read in each case.',
          source: '﴿عَلِمَ أَنْ سَيَكُونُ مِنْكُمْ مَرْضَىٰ﴾ / ﴿وَحَسِبُوا أَلَّا تَكُونَ فِتْنَةٌ﴾ / ﴿نَطْمَعُ أَنْ يَغْفِرَ لَنَا رَبُّنَا﴾',
          words: ['بَعْدَ عَلِمَ (يَقِينٌ)', 'بَعْدَ حَسِبُوا (ظَنٌّ)', 'بِلَا فِعْلِ قَلْبٍ'],
          labels: ['مُخَفَّفَةٌ مِنْ أَنَّ', 'كِلَا الْوَجْهَيْنِ', 'مَصْدَرِيَّةٌ نَاصِبَةٌ'],
          distractors: ['زَائِدَةٌ'],
        },
        {
          title: 'تَرْكِيب: نَاصِبٌ أَمْ جَازِمٌ؟',
          kind: 'tarkeeb',
          instruction: 'Classify each حَرْف: نَاصِب or جَازِم?',
          source: 'أَنْ / لَمْ / كَيْ / لَا النَّاهِيَةُ',
          words: ['أَنْ', 'لَمْ', 'كَيْ', 'لَا النَّاهِيَةُ'],
          labels: ['نَاصِبٌ', 'جَازِمٌ', 'نَاصِبٌ', 'جَازِمٌ'],
          distractors: ['حَرْفُ جَرٍّ'],
        },
        {
          title: 'تَرْكِيب: مَعْنَى كَيْ وَلَنْ',
          kind: 'tarkeeb',
          instruction: 'Match each حَرْف to what it does.',
          source: 'كَيْ / لَنْ',
          words: ['كَيْ', 'لَنْ'],
          labels: ['حَرْفٌ مَصْدَرِيٌّ لِلتَّعْلِيلِ', 'تَأْكِيدُ نَفْيِ الْمُسْتَقْبَلِ'],
          distractors: ['حَرْفُ جَوَابٍ بِثَلَاثَةِ شُرُوطٍ'],
        },
        {
          title: 'تَرْكِيب: عَلَامَةُ النَّصْبِ',
          kind: 'tarkeeb',
          instruction: 'Identify the sign of نَصْب on each مُضَارِع مَنْصُوب: فَتْحَة or حَذْفُ النُّونِ?',
          source: 'يَغْفِرَ / يَخْلُقُوا / تَقَرَّ / تُنْفِقُوا',
          words: ['يَغْفِرَ', 'يَخْلُقُوا', 'تَقَرَّ', 'تُنْفِقُوا'],
          labels: ['فَتْحَةٌ', 'حَذْفُ النُّونِ', 'فَتْحَةٌ', 'حَذْفُ النُّونِ'],
          distractors: ['سُكُونٌ', 'حَذْفُ حَرْفِ الْعِلَّةِ'],
        },
        {
          title: 'تَرْكِيب: كُلُّ نَاصِبٍ وَمِثَالُهُ',
          kind: 'tarkeeb',
          instruction: 'Match each Qurʾanic phrase to the نَاصِب at work in it.',
          source: '﴿أَنْ يَغْفِرَ اللَّهُ لَكُمْ﴾ / ﴿كَيْ تَقَرَّ عَيْنُهَا﴾ / ﴿فَلَنْ أُكَلِّمَ الْيَوْمَ إِنْسِيًّا﴾',
          words: ['أَنْ يَغْفِرَ اللَّهُ لَكُمْ', 'كَيْ تَقَرَّ عَيْنُهَا', 'فَلَنْ أُكَلِّمَ الْيَوْمَ إِنْسِيًّا'],
          labels: ['أَنِ الْمَصْدَرِيَّةُ', 'كَيْ لِلتَّعْلِيلِ', 'لَنْ لِتَأْكِيدِ النَّفْيِ'],
          distractors: ['إِذَنْ لِلْجَوَابِ'],
        },
      ],
    },
    // ---------------------------------------------------------------- L2
    {
      id: 'l2',
      title: 'إِذَنْ، وَإِضْمَار أَنْ',
      subtitle: "Iḏan and Hidden أَنْ — إِذَنْ's three conditions, and where أَنْ is hidden جَوَازًا or وُجُوبًا",
      concepts: [
        {
          heading: 'إِذَنْ: تَعْرِيفُهَا وَشُرُوطُهَا',
          tldr: 'إِذَنْ is the حَرْف of response, and it gives نَصْب only on three conditions: صَدْر الْكَلَام, a future فِعْل after it, and no separator but a قَسَم.',
          body: `<bdi>إِذَنْ</bdi> is the حَرْف <bdi>لِلْجَوَاب</bdi>: someone says <bdi>أُطِيعُ اللَّهَ</bdi> and you answer <bdi>إِذَنْ تَدْخُلَ الْجَنَّةَ</bdi>. It gives نَصْب only where three conditions hold together: (1) it stands at <bdi>صَدْرِ الْكَلَامِ</bdi>, opening the sentence, (2) the فِعْل after it is future in meaning, (3) nothing separates it from that فِعْل, except a <bdi>قَسَم</bdi>. Break the first condition and the نَصْب goes with it. After a <bdi>وَاو</bdi> or a <bdi>فَاء</bdi> both <bdi>الْإِعْمَال</bdi> and <bdi>الْإِهْمَال</bdi> are allowed, الْإِهْمَال being the commoner of the two. One more thing to recognise on the page: in the muṣḥaf إِذَنْ is written with an <bdi>أَلِف</bdi> — <bdi>﴿فَإِذًا﴾</bdi>.`,
          examples: [
            { ar: 'إِذَنْ تَدْخُلَ الْجَنَّةَ', en: 'In that case you will enter Paradise', note: 'all three conditions hold, so إِذَنْ governs — تَدْخُلَ carries the فَتْحَة of نَصْب' },
            { ar: 'أَنْتَ إِذَنْ تَدْخُلُ الْجَنَّةَ', en: 'You, in that case, will enter Paradise', note: 'أَنْتَ has taken صَدْر الْكَلَام from إِذَنْ, so it governs nothing — تَدْخُلُ is مَرْفُوع with a ضَمَّة' },
            { ar: 'إِذَنْ وَاللَّهِ أُكْرِمَكَ', en: 'In that case, by Allah, I will honour you', note: 'a قَسَم is the one tolerated separator — أُكْرِمَكَ stays مَنْصُوب' },
          ],
          exercise: {
            prompt: `In «أَنْتَ إِذَنْ تَدْخُلُ الْجَنَّةَ» the فِعْل is مَرْفُوع, not مَنْصُوب. Which of إِذَنْ's three conditions has been broken?`,
            kind: 'mcq',
            options: ['It has lost صَدْر الْكَلَام, since أَنْتَ stands before it', 'The فِعْل after it is not future in meaning', 'A قَسَم has come between it and the فِعْل', 'It has been repeated twice in one جُمْلَة'],
            correct: 0,
          },
        },
        {
          heading: 'إِضْمَارُ أَنْ جَوَازًا',
          tldr: 'أَنْ may be left unspoken in two places: after the لَام الْجَرّ when لَا is not joined to it, and after a حَرْف عَطْف following an explicit اسْم.',
          body: `A مُضَارِع can be مَنْصُوب with no نَاصِب written before it, because the نَاصِب is an <bdi>أَنْ مُضْمَرَة</bdi> — أَنْ present in the analysis but not spoken. In two places that hiding is optional (<bdi>جَوَازًا</bdi>): (1) after the <bdi>لَامُ الْجَرِّ</bdi> of reason, so long as <bdi>لَا النَّافِيَة</bdi> is not joined to it, (2) after a <bdi>حَرْف عَطْف</bdi> whose preceding اسْم is explicit and <bdi>غَيْرُ مُؤَوَّلٍ</bdi>. Joined to لَا, the لَام becomes <bdi>لِئَلَّا</bdi>, and there أَنْ has to be written out. Hiding أَنْ changes what is on the page, never the إِعْرَاب: the فِعْل is مَنْصُوب either way.`,
          examples: [
            { ar: '﴿لِيَغْفِرَ لَكَ اللَّهُ﴾', en: 'that Allah may forgive you', note: 'read as لِأَنْ يَغْفِرَ — أَنْ is hidden جَوَازًا after the لَام, and يَغْفِرَ keeps the فَتْحَة of نَصْب' },
            { ar: '﴿لِئَلَّا يَكُونَ لِلنَّاسِ عَلَيْكُمْ حُجَّةٌ﴾', en: 'so that people may have no argument against you', note: 'لِئَلَّا is لِـ plus أَنْ plus لَا — once لَا joins the لَام, أَنْ must be spoken' },
            { ar: '﴿إِلَّا وَحْيًا أَوْ مِنْ وَرَاءِ حِجَابٍ أَوْ يُرْسِلَ رَسُولًا﴾', en: 'except by revelation, or from behind a veil, or that He send a messenger', note: 'يُرْسِلَ is joined by أَوْ onto the explicit اسْم وَحْيًا through a hidden أَنْ, so it takes a فَتْحَة' },
          ],
          exercise: {
            prompt: `In ﴿أَوْ يُرْسِلَ رَسُولًا﴾ the فِعْل يُرْسِلَ is مَنْصُوب though no نَاصِب is written. What licenses that?`,
            kind: 'mcq',
            options: ['An أَنْ hidden جَوَازًا after أَوْ, the اسْم وَحْيًا before it being explicit', 'أَوْ itself, which is a نَاصِب in its own right', 'رَسُولًا being مَنْصُوب, which the فِعْل copies', 'The لَام of لِبَشَرٍ, which reaches across the whole آيَة'],
            correct: 0,
          },
        },
        {
          heading: 'إِضْمَارُ أَنْ وُجُوبًا',
          tldr: 'In five places أَنْ is hidden and may not be spoken at all: after حَتَّى, لَام الْجُحُود, أَوْ, وَاو الصَّرْف, and فَاء السَّبَبِيَّة.',
          body: `In five places أَنْ is hidden and may not be spoken (<bdi>وُجُوبًا</bdi>): (1) after <bdi>حَتَّى</bdi>, (2) after <bdi>لَامِ الْجُحُودِ</bdi>, (3) after <bdi>أَوْ</bdi> in the sense of إِلَىٰ أَنْ or إِلَّا أَنْ, (4) after <bdi>وَاوِ الصَّرْفِ</bdi> preceded by a نَفْي or a طَلَب, (5) after <bdi>فَاءِ السَّبَبِيَّةِ</bdi> preceded by a نَفْي or a طَلَب. Notice what حَتَّى actually is: a <bdi>حَرْف جَرّ</bdi>, which cannot govern a فِعْل at all, so the نَصْب after it must belong to the hidden أَنْ. <bdi>لَامُ الْجُحُودِ</bdi> announces itself too: a negated <bdi>كَانَ</bdi> — <bdi>مَا كَانَ</bdi> or <bdi>لَمْ يَكُنْ</bdi> — standing before the لَام.`,
          examples: [
            { ar: '﴿لَنْ تَنَالُوا الْبِرَّ حَتَّىٰ تُنْفِقُوا مِمَّا تُحِبُّونَ﴾', en: 'you will not attain righteousness until you spend from what you love', note: 'حَتَّى is a حَرْف جَرّ, so the نَصْب on تُنْفِقُوا — shown by حَذْفِ النُّونِ — is the work of a hidden أَنْ' },
            { ar: '﴿وَمَا كَانَ اللَّهُ لِيُضِيعَ إِيمَانَكُمْ﴾', en: 'and Allah would never let your faith go to waste', note: 'مَا كَانَ then لِـ is the signature of لَامِ الْجُحُودِ; يُضِيعَ is مَنْصُوب by أَنْ مُضْمَرَة وُجُوبًا' },
          ],
          clarification: `Both ﴿لِيَغْفِرَ لَكَ اللَّهُ﴾ and ﴿وَمَا كَانَ اللَّهُ لِيُضِيعَ إِيمَانَكُمْ﴾ open the فِعْل with a لَام, and in both the فِعْل is مَنْصُوب by an أَنْ that is not written. What separates them is what stands before the لَام. In the first, nothing does: it is the plain <bdi>لَامُ التَّعْلِيلِ</bdi>, and the hiding is جَوَازًا. In the second a negated كَانَ stands before it, which makes it <bdi>لَامَ الْجُحُودِ</bdi>, and the hiding is وُجُوبًا. So before naming the لَام, look at what precedes it for a مَا كَانَ or a لَمْ يَكُنْ.`,
          exercise: {
            prompt: `In how many مَوَاضِع is أَنْ hidden وُجُوبًا, and may it be written out in them?`,
            kind: 'mcq',
            options: ['خَمْسَة, and it may not be written out in any of them', 'خَمْسَة, and it may optionally be written out', 'ثَلَاثَة, and it may not be written out', 'سَبْعَة, and it may optionally be written out'],
            correct: 0,
          },
        },
        {
          heading: 'أَوْ (إِلَىٰ أَنْ / إِلَّا أَنْ)، وَوَاوُ الصَّرْفِ',
          tldr: 'أَوْ before a مُضَارِع مَنْصُوب means إِلَىٰ أَنْ or إِلَّا أَنْ, and وَاوُ الصَّرْفِ gives نَصْب only after a نَفْي or a طَلَب.',
          body: `<bdi>أَوْ</bdi> standing before a مُضَارِع مَنْصُوب carries one of two senses: (1) <bdi>إِلَىٰ أَنْ</bdi>, "until", (2) <bdi>إِلَّا أَنْ</bdi>, "unless". Both throw the فِعْل forward into the future, which is what makes room for a hidden أَنْ. <bdi>وَاوُ الصَّرْفِ</bdi>, also called <bdi>وَاوُ الْمَعِيَّةِ</bdi>, is the وَاو that with a hidden أَنْ puts the فِعْل after it in نَصْب instead of simply coupling it to the one before. It does that only after a <bdi>نَفْي</bdi> or a <bdi>طَلَب</bdi>. The ending is what gives it away: a وَاو عَاطِفَة would leave the second فِعْل copying the إِعْرَاب of the first, while وَاوُ الصَّرْفِ leaves it مَنْصُوب on its own account.`,
          examples: [
            { ar: 'لَأَسْتَسْهِلَنَّ الصَّعْبَ أَوْ أُدْرِكَ الْمُنَى', en: 'I shall surely make light of hardship until I attain what I long for', note: 'أَوْ here means إِلَىٰ أَنْ; أُدْرِكَ is مَنْصُوب by a hidden أَنْ' },
            { ar: 'كَسَرْتُ كُعُوبَهَا أَوْ تَسْتَقِيمَا', en: 'I broke its joints unless it should straighten', note: 'أَوْ here means إِلَّا أَنْ; تَسْتَقِيمَا is مَنْصُوب by a hidden أَنْ' },
            { ar: '﴿وَلَمَّا يَعْلَمِ اللَّهُ الَّذِينَ جَاهَدُوا مِنْكُمْ وَيَعْلَمَ الصَّابِرِينَ﴾', en: 'while Allah has not yet made known those of you who strive, and made known the steadfast', note: 'لَمَّا is the نَفْي, so the وَاو is وَاوُ الصَّرْفِ — the first يَعْلَمِ is مَجْزُوم, the second يَعْلَمَ مَنْصُوب' },
          ],
          exercise: {
            prompt: `In ﴿وَلَمَّا يَعْلَمِ اللَّهُ الَّذِينَ جَاهَدُوا مِنْكُمْ وَيَعْلَمَ الصَّابِرِينَ﴾ the first فِعْل is مَجْزُوم and the second مَنْصُوب. What made the difference?`,
            kind: 'mcq',
            options: ['The وَاو is وَاوُ الصَّرْفِ after a نَفْي, so a hidden أَنْ gives نَصْب', 'The وَاو is عَاطِفَة, so the second فِعْل simply copies the first', 'الصَّابِرِينَ is مَنْصُوب, and the فِعْل follows it', 'لَمَّا itself gives نَصْب to the second فِعْل'],
            correct: 0,
          },
        },
        {
          heading: 'فَاءُ السَّبَبِيَّةِ، وَالْأَمْثِلَةُ السَّمَاعِيَّةُ',
          tldr: 'فَاءُ السَّبَبِيَّةِ gives نَصْب by a hidden أَنْ after a نَفْي or one of seven kinds of طَلَب; a few further cases of hidden أَنْ are سَمَاعِيّ only.',
          body: `<bdi>فَاءُ السَّبَبِيَّةِ</bdi> is the فَاء that makes what follows it the result of what came before — do this, with the result that you enter. Like وَاوُ الصَّرْفِ it licenses نَصْب only after a <bdi>نَفْي</bdi> or a <bdi>طَلَب</bdi>, and الطَّلَب here covers seven kinds: (1) <bdi>الْأَمْر</bdi>, (2) <bdi>النَّهْي</bdi>, (3) <bdi>الِاسْتِفْهَام</bdi>, (4) <bdi>التَّمَنِّي</bdi>, (5) <bdi>التَّرَجِّي</bdi>, (6) <bdi>الْعَرْض</bdi>, (7) <bdi>التَّحْضِيض</bdi>. Beside all of these stands a short list of phrases in which أَنْ is hidden with no rule behind it. They are <bdi>سَمَاعِيَّة</bdi>, transmitted as heard from the Arabs and <bdi>لَيْسَتْ بِقِيَاسِيَّةٍ</bdi>. Quote them by all means, but do not build new sentences on their pattern.`,
          examples: [
            { ar: 'أَسْلِمْ فَتَدْخُلَ الْجَنَّةَ', en: 'Submit, and you will thereby enter Paradise', note: 'an أَمْر then the فَاء — تَدْخُلَ is مَنْصُوب by a hidden أَنْ; with a plain فَاء عَاطِفَة it would read تَدْخُلْ, مَجْزُوم' },
            { ar: '﴿لَا يُقْضَىٰ عَلَيْهِمْ فَيَمُوتُوا﴾', en: 'it is not decreed for them, that they should die', note: 'here the licence comes from a نَفْي rather than a طَلَب — يَمُوتُوا shows its نَصْب by حَذْفِ النُّونِ' },
            { ar: 'خُذِ اللِّصَّ قَبْلَ يَأْخُذَكَ', en: 'Seize the thief before he seizes you', note: 'a سَمَاعِيّ hiding of أَنْ after قَبْلَ — quotable, but not to be extended by analogy' },
          ],
          exercise: {
            prompt: `أَسْلِمْ فَتَدْخُلَ الْجَنَّةَ has تَدْخُلَ مَنْصُوبًا, where a plain فَاء عَاطِفَة would have left تَدْخُلْ مَجْزُومًا. What produced the نَصْب?`,
            kind: 'mcq',
            options: ['An أَنْ hidden after فَاءِ السَّبَبِيَّةِ, licensed by the أَمْر before it', 'The فَاء itself, which is a نَاصِب in its own right', 'الْجَنَّةَ being مَنْصُوب, which the فِعْل follows', 'أَسْلِمْ being مَبْنِيّ, which passes نَصْب on to the next فِعْل'],
            correct: 0,
          },
        },
      ],
      quiz: [
        {
          q: 'إِذَنْ is the حَرْف of:',
          options: ['الْجَوَاب', 'الشَّرْط', 'الِاسْتِثْنَاء', 'التَّعْلِيل'],
          correct: 0,
        },
        {
          q: 'How is إِذَنْ written in the muṣḥaf?',
          options: ['With an أَلِف — ﴿فَإِذًا﴾', 'Exactly as إِذَنْ', 'With a تَنْوِين and no letter after it', 'It never occurs in the muṣḥaf at all'],
          correct: 0,
        },
        {
          q: '﴿لِئَلَّا يَكُونَ لِلنَّاسِ عَلَيْكُمْ حُجَّةٌ﴾ — here أَنْ must:',
          options: ['be written out, not hidden', 'be hidden, never written out', 'be dropped along with لَا', 'become أَنَّ الْمُشَدَّدَة'],
          correct: 0,
        },
        {
          q: 'Which pair of مَوَاضِع allows إِضْمَار أَنْ جَوَازًا, rather than requiring it وُجُوبًا?',
          options: ['After لَامِ الْجَرِّ, and after a حَرْف عَطْف preceded by an explicit اسْم', 'After حَتَّى, and after لَامِ الْجُحُودِ', 'After أَوْ, and after فَاءِ السَّبَبِيَّةِ', 'After وَاوِ الصَّرْفِ, and after حَتَّى'],
          correct: 0,
        },
        {
          q: 'كَسَرْتُ كُعُوبَهَا أَوْ تَسْتَقِيمَا — أَوْ here means:',
          options: ['إِلَّا أَنْ', 'إِلَىٰ أَنْ', 'إِذْ ذَاكَ', 'حَتَّى أَنْ'],
          correct: 0,
        },
        {
          q: 'مُرْهُ يَحْفِرَهَا, with its hidden أَنْ, is an example that is:',
          options: ['سَمَاعِيّ, not extended by analogy', 'قِيَاسِيّ, freely extendable', 'شَرْطِيّ, and therefore جَازِم', 'one of the five مَوَاضِع of وُجُوب'],
          correct: 0,
        },
      ],
      bank: [
        {
          title: 'شُرُوطُ إِذَنْ الثَّلَاثَةُ',
          kind: 'mcq',
          prompt: 'إِذَنْ governs on three conditions. Which of these is one of them?',
          options: ['That it stand at صَدْرِ الْكَلَامِ', 'That a وَاو or a فَاء stand before it', 'That a فِعْل مَاضٍ follow it', 'That it be repeated in the same جُمْلَة'],
          correct: 0,
        },
        {
          title: 'الْفَصْلُ بِالْقَسَمِ',
          kind: 'mcq',
          prompt: 'إِذَنْ وَاللَّهِ أُكْرِمَكَ shows إِذَنْ separated from its فِعْل by:',
          options: ['a قَسَم, the one separator it tolerates', 'a حَرْف نَفْي', 'a حَرْف جَرّ', 'a ضَمِير مُنْفَصِل'],
          correct: 0,
        },
        {
          title: 'إِذَنْ بَعْدَ الْفَاءِ',
          kind: 'mcq',
          prompt: '﴿فَإِذًا لَا يُؤْتُونَ النَّاسَ نَقِيرًا﴾ — following a فَاء, إِذَنْ here shows:',
          options: ['الْإِهْمَال, which is the commoner choice after وَاو and فَاء', 'الْإِعْمَال, which is the only choice after وَاو and فَاء', 'Neither, since إِذَنْ cannot follow a فَاء at all', 'الْإِعْمَال, forced here by the نَفْي after it'],
          correct: 0,
        },
        {
          title: 'إِعْرَابُ يُؤْتُونَ',
          kind: 'mcq',
          prompt: 'In ﴿فَإِذًا لَا يُؤْتُونَ النَّاسَ نَقِيرًا﴾, what is the إِعْرَاب of يُؤْتُونَ, and what does it tell you?',
          options: ['مَرْفُوع by ثُبُوتِ النُّونِ — إِذَنْ has been left مُهْمَلَة here', 'مَنْصُوب by حَذْفِ النُّونِ — إِذَنْ has governed it', 'مَجْزُوم by حَذْفِ النُّونِ — لَا is النَّاهِيَة', 'مَنْصُوب by a فَتْحَة — إِذَنْ has governed it'],
          correct: 0,
        },
        {
          title: 'إِضْمَارُ أَنْ جَوَازًا: لَامُ الْجَرِّ',
          kind: 'mcq',
          prompt: '﴿لِيَغْفِرَ لَكَ اللَّهُ﴾ shows أَنْ hidden:',
          options: ['جَوَازًا, after لَامِ الْجَرِّ', 'وُجُوبًا, after حَتَّى', 'وُجُوبًا, after لَامِ الْجُحُودِ', 'جَوَازًا, after فَاءِ السَّبَبِيَّةِ'],
          correct: 0,
        },
        {
          title: 'عَلَامَةُ النَّصْبِ فِي يُرْسِلَ',
          kind: 'mcq',
          prompt: 'In ﴿أَوْ يُرْسِلَ رَسُولًا﴾, what is the إِعْرَاب of يُرْسِلَ and its sign?',
          options: ['مَنْصُوب by أَنْ مُضْمَرَة, its sign a فَتْحَة', 'مَرْفُوع by a ضَمَّة, since أَوْ is عَاطِفَة', 'مَجْزُوم by a سُكُون, in عَطْف onto a مَجْزُوم', 'مَجْرُور by أَوْ, which acts as a حَرْف جَرّ'],
          correct: 0,
        },
        {
          title: 'حَتَّى حَرْفُ جَرٍّ',
          kind: 'mcq',
          prompt: 'حَتَّى is by origin a حَرْف جَرّ. What does that tell you about the نَصْب on the فِعْل after it?',
          options: ['It comes from an أَنْ hidden وُجُوبًا, since a حَرْف جَرّ cannot govern a فِعْل', 'It comes from حَتَّى directly, which governs both أَسْمَاء and أَفْعَال', 'It comes from whatever نَاصِب opened the sentence', 'There is no نَصْب — the فِعْل after حَتَّى is مَجْرُور'],
          correct: 0,
        },
        {
          title: 'إِضْمَارُ أَنْ وُجُوبًا: حَتَّى',
          kind: 'mcq',
          prompt: '﴿لَنْ تَنَالُوا الْبِرَّ حَتَّىٰ تُنْفِقُوا مِمَّا تُحِبُّونَ﴾ shows أَنْ hidden وُجُوبًا after:',
          options: ['حَتَّى', 'لَامِ الْجُحُودِ', 'أَوْ', 'وَاوِ الصَّرْفِ'],
          correct: 0,
        },
        {
          title: 'عَلَامَةُ لَامِ الْجُحُودِ',
          kind: 'mcq',
          prompt: 'What marks a لَام as لَامَ الْجُحُودِ rather than the plain لَامَ التَّعْلِيلِ?',
          options: ['A negated كَانَ before it — مَا كَانَ or لَمْ يَكُنْ', 'A تَنْوِين on the word after it', 'A قَسَم before it', 'A نَفْي coming after it rather than before it'],
          correct: 0,
        },
        {
          title: 'إِضْمَارُ أَنْ وُجُوبًا: لَامُ الْجُحُودِ',
          kind: 'mcq',
          prompt: '﴿وَمَا كَانَ اللَّهُ لِيُضِيعَ إِيمَانَكُمْ﴾ shows أَنْ hidden وُجُوبًا after:',
          options: ['لَامِ الْجُحُودِ', 'حَتَّى', 'فَاءِ السَّبَبِيَّةِ', 'أَوْ'],
          correct: 0,
        },
        {
          title: 'أَوْ بِمَعْنَى إِلَىٰ أَنْ',
          kind: 'mcq',
          prompt: 'لَأَسْتَسْهِلَنَّ الصَّعْبَ أَوْ أُدْرِكَ الْمُنَى — أَوْ here means:',
          options: ['إِلَىٰ أَنْ', 'إِلَّا أَنْ', 'أَمْ', 'ثُمَّ'],
          correct: 0,
        },
        {
          title: 'وَاوُ الصَّرْفِ بَعْدَ نَفْيٍ',
          kind: 'mcq',
          prompt: '﴿وَلَمَّا يَعْلَمِ اللَّهُ الَّذِينَ جَاهَدُوا مِنْكُمْ وَيَعْلَمَ الصَّابِرِينَ﴾ shows وَاوَ الصَّرْفِ preceded by:',
          options: ['نَفْي — the لَمَّا at the head of the clause', 'طَلَب', 'قَسَم', 'اسْتِفْهَام'],
          correct: 0,
        },
        {
          title: 'وَاوُ الصَّرْفِ بَعْدَ طَلَبٍ',
          kind: 'mcq',
          prompt: '﴿يَا لَيْتَنَا نُرَدُّ وَلَا نُكَذِّبَ بِآيَاتِ رَبِّنَا وَنَكُونَ مِنَ الْمُؤْمِنِينَ﴾ shows وَاوَ الصَّرْفِ after which kind of طَلَب?',
          options: ['التَّمَنِّي — يَا لَيْتَنَا', 'الْأَمْر', 'النَّهْي', 'الِاسْتِفْهَام'],
          correct: 0,
        },
        {
          title: 'أَنْوَاعُ الطَّلَبِ',
          kind: 'mcq',
          prompt: 'Which list names the kinds of طَلَب that license نَصْب after فَاءِ السَّبَبِيَّةِ?',
          options: ['الْأَمْر، النَّهْي، الِاسْتِفْهَام، التَّمَنِّي، التَّرَجِّي، الْعَرْض، التَّحْضِيض', 'الْخَبَر، الْقَسَم، الشَّرْط، النِّدَاء', 'الْأَمْر وَالنَّهْي وَحْدَهُمَا', 'الِاسْتِفْهَام وَحْدَهُ'],
          correct: 0,
        },
        {
          title: 'فَاءُ السَّبَبِيَّةِ بَعْدَ نَهْيٍ',
          kind: 'mcq',
          prompt: '﴿وَلَا تَطْغَوْا فِيهِ فَيَحِلَّ عَلَيْكُمْ غَضَبِي﴾ shows فَاءَ السَّبَبِيَّةِ licensing نَصْب after:',
          options: ['النَّهْي', 'الْأَمْر', 'التَّرَجِّي', 'التَّحْضِيض'],
          correct: 0,
        },
        {
          title: 'فَاءُ السَّبَبِيَّةِ بَعْدَ اسْتِفْهَامٍ',
          kind: 'mcq',
          prompt: '﴿مَنْ ذَا الَّذِي يُقْرِضُ اللَّهَ قَرْضًا حَسَنًا فَيُضَاعِفَهُ لَهُ﴾ shows فَاءَ السَّبَبِيَّةِ licensing نَصْب after:',
          options: ['الِاسْتِفْهَام', 'الْأَمْر', 'النَّهْي', 'التَّمَنِّي'],
          correct: 0,
        },
        {
          title: 'فَاءُ السَّبَبِيَّةِ بَعْدَ نَفْيٍ',
          kind: 'mcq',
          prompt: '﴿لَا يُقْضَىٰ عَلَيْهِمْ فَيَمُوتُوا﴾ — what licenses the نَصْب on يَمُوتُوا here?',
          options: ['A نَفْي before the فَاء, not a طَلَب', 'An أَمْر before the فَاء', 'A تَحْضِيض before the فَاء', 'Nothing — يَمُوتُوا is مَرْفُوع here'],
          correct: 0,
        },
        {
          title: 'مِثَالٌ سَمَاعِيٌّ',
          kind: 'mcq',
          prompt: 'خُذِ اللِّصَّ قَبْلَ يَأْخُذَكَ, with its hidden أَنْ, is:',
          options: ['سَمَاعِيّ — heard from the Arabs, but not extended by analogy', 'قِيَاسِيّ — freely productive on its pattern', 'One of the five مَوَاضِع of وُجُوب', 'Not valid Arabic at all'],
          correct: 0,
        },
        {
          title: 'عَدَدُ مَوَاضِعِ الْجَوَازِ',
          kind: 'mcq',
          prompt: 'How many مَوَاضِع allow إِضْمَار أَنْ جَوَازًا?',
          options: ['اثْنَانِ', 'خَمْسَة', 'ثَلَاثَة', 'وَاحِد'],
          correct: 0,
        },
        {
          title: 'تَرْكِيب: إِضْمَارُ أَنْ جَوَازًا أَمْ وُجُوبًا؟',
          kind: 'tarkeeb',
          instruction: 'Classify each example: is أَنْ hidden جَوَازًا or وُجُوبًا?',
          source: '﴿لِيَغْفِرَ لَكَ اللَّهُ﴾ / ﴿حَتَّىٰ تُنْفِقُوا مِمَّا تُحِبُّونَ﴾ / ﴿وَمَا كَانَ اللَّهُ لِيُضِيعَ إِيمَانَكُمْ﴾',
          words: ['لِيَغْفِرَ لَكَ اللَّهُ', 'حَتَّىٰ تُنْفِقُوا', 'لِيُضِيعَ إِيمَانَكُمْ'],
          labels: ['جَوَازًا (لَامُ الْجَرِّ)', 'وُجُوبًا (حَتَّى)', 'وُجُوبًا (لَامُ الْجُحُودِ)'],
          distractors: ['جَوَازًا (بَعْدَ عَطْفٍ)'],
        },
        {
          title: 'تَرْكِيب: شُرُوطُ إِذَنْ',
          kind: 'tarkeeb',
          instruction: "Put إِذَنْ's three conditions in their order.",
          source: 'صَدْرُ الْكَلَامِ / فِعْلٌ مُسْتَقْبَلٌ بَعْدَهَا / لَا فَاصِلَ إِلَّا الْقَسَمُ',
          words: ['صَدْرُ الْكَلَامِ', 'فِعْلٌ مُسْتَقْبَلٌ', 'لَا فَاصِلَ إِلَّا الْقَسَمُ'],
          labels: ['شَرْطٌ أَوَّلُ', 'شَرْطٌ ثَانٍ', 'شَرْطٌ ثَالِثٌ'],
          distractors: ['شَرْطٌ رَابِعٌ'],
        },
        {
          title: 'تَرْكِيب: إِذَنْ — إِعْمَالٌ أَمْ إِهْمَالٌ؟',
          kind: 'tarkeeb',
          instruction: 'Classify each: does إِذَنْ govern here (إِعْمَال) or not (إِهْمَال)?',
          source: 'إِذَنْ تَدْخُلَ الْجَنَّةَ / أَنْتَ إِذَنْ تَدْخُلُ الْجَنَّةَ / إِذَنْ وَاللَّهِ أُكْرِمَكَ',
          words: ['إِذَنْ تَدْخُلَ الْجَنَّةَ', 'أَنْتَ إِذَنْ تَدْخُلُ الْجَنَّةَ', 'إِذَنْ وَاللَّهِ أُكْرِمَكَ'],
          labels: ['إِعْمَالٌ (نَصْبٌ)', 'إِهْمَالٌ (رَفْعٌ)', 'إِعْمَالٌ (نَصْبٌ)'],
          distractors: ['جَزْمٌ'],
        },
        {
          title: 'تَرْكِيب: مَا يَسْبِقُ وَاوَ الصَّرْفِ',
          kind: 'tarkeeb',
          instruction: 'Classify what precedes وَاوَ الصَّرْفِ in each example: نَفْي or طَلَب?',
          source: '﴿وَلَمَّا يَعْلَمِ اللَّهُ... وَيَعْلَمَ الصَّابِرِينَ﴾ / ﴿يَا لَيْتَنَا نُرَدُّ... وَنَكُونَ مِنَ الْمُؤْمِنِينَ﴾',
          words: ['وَلَمَّا يَعْلَمِ... وَيَعْلَمَ', 'يَا لَيْتَنَا نُرَدُّ... وَنَكُونَ'],
          labels: ['نَفْيٌ (لَمَّا)', 'طَلَبٌ (تَمَنٍّ)'],
          distractors: ['قَسَمٌ'],
        },
        {
          title: 'تَرْكِيب: مَا يَسْبِقُ فَاءَ السَّبَبِيَّةِ',
          kind: 'tarkeeb',
          instruction: 'Classify what licenses the نَصْب after the فَاء in each example.',
          source: 'أَسْلِمْ فَتَدْخُلَ الْجَنَّةَ / ﴿وَلَا تَطْغَوْا فِيهِ فَيَحِلَّ عَلَيْكُمْ غَضَبِي﴾ / ﴿لَا يُقْضَىٰ عَلَيْهِمْ فَيَمُوتُوا﴾',
          words: ['أَسْلِمْ فَتَدْخُلَ', 'وَلَا تَطْغَوْا فَيَحِلَّ', 'لَا يُقْضَىٰ فَيَمُوتُوا'],
          labels: ['أَمْرٌ', 'نَهْيٌ', 'نَفْيٌ'],
          distractors: ['اسْتِفْهَامٌ'],
        },
        {
          title: 'تَرْكِيب: قِيَاسِيٌّ أَمْ سَمَاعِيٌّ؟',
          kind: 'tarkeeb',
          instruction: 'Classify each hiding of أَنْ: قِيَاسِيّ or سَمَاعِيّ?',
          source: '﴿لِيَغْفِرَ لَكَ اللَّهُ﴾ / مُرْهُ يَحْفِرَهَا',
          words: ['لِيَغْفِرَ لَكَ اللَّهُ', 'مُرْهُ يَحْفِرَهَا'],
          labels: ['قِيَاسِيٌّ (لَامُ الْجَرِّ)', 'سَمَاعِيٌّ'],
          distractors: ['مُمْتَنِعٌ كُلِّيًّا'],
        },
      ],
    },
    // ---------------------------------------------------------------- L3
    {
      id: 'l3',
      title: 'جَوَازِم الْمُضَارِع',
      subtitle: 'Jussive Particles — لَمْ، لَمَّا، لَامُ الْأَمْرِ، لَا النَّاهِيَةُ, and إِنْ وَإِذْمَا governing a شَرْط',
      concepts: [
        {
          heading: 'ضَرْبَا جَوَازِمِ الْمُضَارِعِ',
          tldr: 'الْجَوَازِم are of two kinds: four that put a single فِعْل in جَزْم, and two that put a pair of أَفْعَال in جَزْم.',
          body: `The <bdi>جَوَازِم</bdi> divide into two ضَرْبَيْنِ: (1) حُرُوف that put a single فِعْل in جَزْم — four of them, <bdi>لَمْ</bdi>, <bdi>لَمَّا</bdi>, <bdi>لَامُ الْأَمْرِ</bdi> and <bdi>لَا النَّاهِيَةُ</bdi>, (2) حُرُوف that put two أَفْعَال in جَزْم — two of them, <bdi>إِنْ</bdi> and <bdi>إِذْمَا</bdi>. The second kind is what builds a شَرْط with its جَوَاب. الْجَزْم itself shows in one of three ways, according to the فِعْل: (1) a <bdi>سُكُون</bdi> on a sound فِعْل, (2) <bdi>حَذْفُ حَرْفِ الْعِلَّةِ</bdi> on a مُعْتَلّ الْآخِرِ, (3) <bdi>حَذْفُ النُّونِ</bdi> on الْأَفْعَال الْخَمْسَة.`,
          examples: [
            { ar: 'لَمْ يَلِدْ', en: 'He did not beget', note: 'a sound فِعْل, so its جَزْم shows as a سُكُون' },
            { ar: '﴿تَعَالَوْا أَتْلُ﴾', en: 'Come, I will recite', note: 'أَتْلُ is مُعْتَلّ الْآخِرِ — its جَزْم shows as حَذْفُ حَرْفِ الْعِلَّةِ, the وَاو of أَتْلُو being gone' },
            { ar: '﴿إِنْ تَجْتَنِبُوا كَبَائِرَ مَا تُنْهَوْنَ عَنْهُ﴾', en: 'if you avoid the major sins you are forbidden', note: 'تَجْتَنِبُوا is مِنَ الْأَفْعَالِ الْخَمْسَةِ, so its جَزْم shows as حَذْفُ النُّونِ' },
          ],
          exercise: {
            prompt: `The جَوَازِم fall into two ضَرْبَيْنِ. What separates one from the other?`,
            kind: 'mcq',
            options: ['One kind puts a single فِعْل in جَزْم, the other puts two', 'One governs an اسْم, the other a فِعْل', 'One is قِيَاسِيّ, the other سَمَاعِيّ', 'One is أَصْلِيّ, the other زَائِد'],
            correct: 0,
          },
        },
        {
          heading: 'لَمْ وَلَمَّا وَلَامُ الْأَمْرِ وَلَا النَّاهِيَةُ',
          tldr: 'لَمْ negates the مُضَارِع and throws its meaning into the past; لَمَّا does the same and adds that the act is still expected.',
          body: `<bdi>لَمْ</bdi> does three things at once to the مُضَارِع after it: (1) it negates it, (2) it turns its meaning to the past, (3) it puts it in جَزْم. <bdi>لَمَّا</bdi> does all three and adds one thing more — the act is still awaited, "not yet". Keep both apart from <bdi>لَنْ</bdi>, which is a نَاصِب and negates the future rather than the past. The other two single-verb جَوَازِم work on meaning rather than negation: <bdi>لَامُ الْأَمْرِ</bdi> turns the مُضَارِع into a command, and <bdi>لَا النَّاهِيَةُ</bdi> turns it into a prohibition. Do not read لَا النَّاهِيَة as لَا النَّافِيَة — the ending decides, since النَّافِيَة leaves the فِعْل مَرْفُوعًا and النَّاهِيَة leaves it مَجْزُومًا.`,
          examples: [
            { ar: '﴿لَمْ يَلِدْ وَلَمْ يُولَدْ﴾', en: 'He did not beget, nor was He begotten', note: 'لَمْ negates, throws the sense into the past, and gives جَزْم — hence the سُكُون on يَلِدْ' },
            { ar: '﴿وَلَمَّا يَدْخُلِ الْإِيمَانُ فِي قُلُوبِكُمْ﴾', en: 'and faith has not yet entered your hearts', note: 'لَمَّا leaves the door open, the entering being still expected; يَدْخُلِ is مَجْزُوم, its سُكُون broken to a كَسْرَة before الْإِيمَان' },
            { ar: '﴿فَلْيَعْمَلْ عَمَلًا صَالِحًا وَلَا يُشْرِكْ بِعِبَادَةِ رَبِّهِ أَحَدًا﴾', en: 'let him do righteous work and associate none in the worship of his Lord', note: 'لَامُ الْأَمْرِ on فَلْيَعْمَلْ and لَا النَّاهِيَة on يُشْرِكْ — both مَجْزُوم by a سُكُون' },
          ],
          exercise: {
            prompt: `The سُكُون on يُشْرِكْ in ﴿وَلَا يُشْرِكْ بِعِبَادَةِ رَبِّهِ أَحَدًا﴾ settles which لَا this is. Which is it, and on what grounds?`,
            kind: 'mcq',
            options: ['لَا النَّاهِيَة, because الْجَزْم is its mark — لَا النَّافِيَة would leave the فِعْل مَرْفُوعًا', 'لَا النَّافِيَة, because the آيَة merely reports that he associates no one', 'لَا النَّافِيَة لِلْجِنْسِ, which is why the ending is not a ضَمَّة', 'لَا الْعَاطِفَة, joining يُشْرِكْ to يَعْمَلْ before it'],
            correct: 0,
          },
        },
        {
          heading: 'الشَّرْطُ وَجَوَابُهُ: إِنْ وَإِذْمَا',
          tldr: 'إِنْ and إِذْمَا govern two أَفْعَال: the first is the شَرْط, the second the جَوَاب, also called الْجَزَاء, and both are مَجْزُومَانِ.',
          body: `<bdi>إِنِ الشَّرْطِيَّة</bdi> reaches over two أَفْعَال and gives جَزْم to both. Each has a name: (1) the first is the <bdi>شَرْط</bdi>, the condition, (2) the second is the <bdi>جَوَابُ الشَّرْطِ</bdi>, also called the <bdi>جَزَاء</bdi>. The order is fixed — condition first, then answer. <bdi>إِذْمَا</bdi> is the only other حَرْف that governs a pair like this, and it carries the meaning of إِنْ. Everything else in this chapter governs one فِعْل and stops.`,
          examples: [
            { ar: '﴿إِنْ تَجْتَنِبُوا كَبَائِرَ مَا تُنْهَوْنَ عَنْهُ نُكَفِّرْ عَنْكُمْ سَيِّئَاتِكُمْ﴾', en: 'if you avoid the major sins you are forbidden, We shall remit your misdeeds from you', note: 'تَجْتَنِبُوا is the شَرْط, مَجْزُوم by حَذْفِ النُّونِ; نُكَفِّرْ is the جَوَاب, مَجْزُوم by a سُكُون' },
            { ar: 'إِذْمَا تَتُبْ تُقْبَلْ تَوْبَتُكَ', en: 'if you repent, your repentance will be accepted', note: 'إِذْمَا carries the meaning of إِنْ — تَتُبْ and تُقْبَلْ are both مَجْزُوم by a سُكُون' },
          ],
          exercise: {
            prompt: `إِذْمَا تَتُبْ تُقْبَلْ تَوْبَتُكَ — what is إِذْمَا doing here?`,
            kind: 'mcq',
            options: ['Carrying the meaning of إِنْ and giving جَزْم to both أَفْعَال', 'Carrying the meaning of إِذَنْ and giving نَصْب to the فِعْل after it', 'Standing as a ظَرْف, leaving both أَفْعَال مَرْفُوعَيْنِ', 'Giving جَزْم to the first فِعْل only'],
            correct: 0,
          },
        },
        {
          heading: 'مَوَاضِعُ إِضْمَارِ إِنْ',
          tldr: 'إِنْ can be مُقَدَّرَة rather than spoken before a مُضَارِع مَجْزُوم after four things: طَلَب, اسْتِفْهَام, تَمَنٍّ, and عَرْض.',
          body: `Just as أَنْ can be hidden before a مَنْصُوب, <bdi>إِنِ الشَّرْطِيَّة</bdi> can be <bdi>مُقَدَّرَة</bdi> before a مَجْزُوم. That happens after four things: (1) a <bdi>طَلَب</bdi>, (2) an <bdi>اسْتِفْهَام</bdi>, (3) a <bdi>تَمَنٍّ</bdi>, (4) an <bdi>عَرْض</bdi>. In each the sense is conditional though no حَرْف شَرْط is written — "come, and if you come, I will recite". The جَزْم is the evidence that the hidden إِنْ is there: with no شَرْط understood, the فِعْل would have stayed مَرْفُوعًا.`,
          examples: [
            { ar: '﴿تَعَالَوْا أَتْلُ﴾', en: 'Come, I will recite', note: 'after a طَلَب, read as إِنْ تَتَعَالَوْا أَتْلُ; أَتْلُ is مَجْزُوم by حَذْفِ حَرْفِ الْعِلَّةِ' },
            { ar: 'هَلْ تَزُورُنَا نُكْرِمْكَ', en: 'Will you visit us? We will honour you', note: 'after an اسْتِفْهَام — تَزُورُنَا stays مَرْفُوع, but نُكْرِمْكَ is مَجْزُوم by the hidden إِنْ' },
            { ar: 'أَلَا تَنْزِلُ بِنَا تُصِبْ خَيْرًا', en: 'Will you not stop with us? You would come by some good', note: 'after an عَرْض — again the جَزْم falls on the second فِعْل, تُصِبْ, and not on the first' },
          ],
          exercise: {
            prompt: `In هَلْ تَزُورُنَا نُكْرِمْكَ the first فِعْل is مَرْفُوع and the second مَجْزُوم. What accounts for that جَزْم?`,
            kind: 'mcq',
            options: ['A hidden إِنْ after the اسْتِفْهَام, making نُكْرِمْكَ a جَوَاب شَرْط', 'هَلْ itself, which is one of the جَوَازِم', 'عَطْف onto تَزُورُنَا before it', 'The كَاف of the مَفْعُول, which builds the فِعْل on a سُكُون'],
            correct: 0,
          },
        },
        {
          heading: 'مَا الزَّائِدَةُ، وَتَوَافُقُ الْأَزْمِنَةِ',
          tldr: 'إِنْ plus مَا الزَّائِدَة gives إِمَّا, which adds تَوْكِيد and brings نُونَ التَّوْكِيدِ onto the شَرْط; the two أَفْعَال may pair their tenses in four ways.',
          body: `Add the redundant <bdi>مَا</bdi> after إِنْ and the two become <bdi>إِمَّا</bdi>. The مَا adds <bdi>تَوْكِيد</bdi>, and the فِعْل الشَّرْط then carries the <bdi>نُونَ التَّوْكِيدِ</bdi> with it. The two أَفْعَال of a شَرْط need not match in tense; four pairings occur: (1) both مُضَارِع, (2) both مَاضٍ, (3) مُضَارِع then مَاضٍ, (4) مَاضٍ then مُضَارِع, and in this last the مُضَارِع may take either جَزْم or رَفْع. A فِعْل مَاضٍ is مَبْنِيّ, so where one fills a slot its جَزْم is <bdi>فِي مَحَلِّ جَزْمٍ</bdi> and nothing shows on its ending.`,
          examples: [
            { ar: '﴿وَإِمَّا يَنْزَغَنَّكَ مِنَ الشَّيْطَانِ نَزْغٌ فَاسْتَعِذْ بِاللَّهِ﴾', en: 'and if an incitement from Satan should stir you, seek refuge in Allah', note: 'إِنْ plus مَا gives إِمَّا, and the شَرْط يَنْزَغَنَّكَ carries the نُون التَّوْكِيد' },
            { ar: '﴿وَإِنْ تَعُودُوا نَعُدْ﴾', en: 'and if you return, We shall return', note: 'both أَفْعَال مُضَارِع — تَعُودُوا مَجْزُوم by حَذْفِ النُّونِ, نَعُدْ by a سُكُون' },
            { ar: '﴿وَإِنْ عُدْتُمْ عُدْنَا﴾', en: 'and if you return, We shall return', note: 'both أَفْعَال مَاضٍ, and a مَاضٍ is مَبْنِيّ — so each is فِي مَحَلِّ جَزْمٍ with nothing showing on its end' },
          ],
          exercise: {
            prompt: `No sign of جَزْم appears on عُدْتُمْ or عُدْنَا in ﴿وَإِنْ عُدْتُمْ عُدْنَا﴾, yet إِنْ is الشَّرْطِيَّة. Why is that?`,
            kind: 'mcq',
            options: ['Both are مَاضٍ and so مَبْنِيّ — each stands فِي مَحَلِّ جَزْمٍ', 'إِنْ does not reach a فِعْل مَاضٍ at all', 'The جَزْم dropped away because the جَوَاب came first', 'Both are مَرْفُوع, إِنْ here not being الشَّرْطِيَّة'],
            correct: 0,
          },
        },
        {
          heading: 'الْفَاءُ قَبْلَ جَوَابِ الشَّرْطِ',
          tldr: 'Where the جَوَاب cannot itself be a فِعْل مَجْزُوم, a فَاء is put before it and إِنْ stops short of governing it.',
          body: `Some answers cannot be given جَزْم at all: (1) a <bdi>جُمْلَة اسْمِيَّة</bdi>, (2) a <bdi>طَلَب</bdi>, (3) a <bdi>فِعْل جَامِد</bdi>. In those cases a <bdi>فَاء</bdi> is set before the جَوَاب, and إِنْ does not govern what follows it — the جَوَاب keeps its own إِعْرَاب and the جَزْم stops at the شَرْط. The فَاء is the visible sign that the answer has been insulated. Do not confuse it with <bdi>فَاءِ السَّبَبِيَّةِ</bdi>: that one licenses نَصْب after a نَفْي or a طَلَب, while this one merely heads a جَوَاب شَرْط and licenses nothing.`,
          examples: [
            { ar: '﴿وَإِنْ يَمْسَسْكَ اللَّهُ بِضُرٍّ فَلَا كَاشِفَ لَهُ إِلَّا هُوَ﴾', en: 'and if Allah touches you with harm, none can remove it but He', note: 'يَمْسَسْكَ is مَجْزُوم by a سُكُون, but the جَوَاب is a جُمْلَة اسْمِيَّة — hence the فَاء, and no جَزْم in it' },
            { ar: '﴿وَإِمَّا يَنْزَغَنَّكَ مِنَ الشَّيْطَانِ نَزْغٌ فَاسْتَعِذْ بِاللَّهِ﴾', en: 'and if an incitement from Satan should stir you, seek refuge in Allah', note: 'here the جَوَاب is a طَلَب, فَاسْتَعِذْ, which cannot be given جَزْم either — so it too takes the فَاء' },
          ],
          exercise: {
            prompt: `In ﴿وَإِنْ يَمْسَسْكَ اللَّهُ بِضُرٍّ فَلَا كَاشِفَ لَهُ إِلَّا هُوَ﴾, why does a فَاء stand before the جَوَاب?`,
            kind: 'mcq',
            options: ['The جَوَاب is a جُمْلَة اسْمِيَّة and cannot take جَزْم, so the فَاء steps in and إِنْ stops at the شَرْط', 'The فَاء is سَبَبِيَّة, giving نَصْب to what comes after it', 'The فَاء is عَاطِفَة, joining the جَوَاب onto the شَرْط', 'A شَرْط in the مُضَارِع always demands a فَاء before its جَوَاب'],
            correct: 0,
          },
        },
      ],
      quiz: [
        {
          q: 'List the four جَوَازِم that give جَزْم to one فِعْل.',
          options: ['لَمْ، لَمَّا، لَامُ الْأَمْرِ، لَا النَّاهِيَةُ', 'إِنْ، إِذْمَا، لَوْ، لَوْلَا', 'أَنْ، كَيْ، لَنْ، إِذَنْ', 'هَلْ، مَا، لَا، أَمْ'],
          correct: 0,
        },
        {
          q: 'لَمْ negates the مُضَارِع and turns its meaning to:',
          options: ['الْمَاضِي', 'الْمُسْتَقْبَل', 'الْحَال الْمُسْتَمِرّ', 'الْأَمْر'],
          correct: 0,
        },
        {
          q: 'In a شَرْط بِفِعْلَيْنِ, the second فِعْل is called جَوَابُ الشَّرْطِ, and also:',
          options: ['الْجَزَاء', 'الْعِلَّة', 'التَّعْلِيل', 'التَّوْكِيد'],
          correct: 0,
        },
        {
          q: 'What is the sign of جَزْم on a فِعْل مُعْتَلّ الْآخِرِ such as أَتْلُ?',
          options: ['حَذْفُ حَرْفِ الْعِلَّةِ', 'السُّكُون', 'حَذْفُ النُّونِ', 'الْفَتْحَة'],
          correct: 0,
        },
        {
          q: 'When مَا الزَّائِدَة follows إِنْ, the فِعْل الشَّرْط takes:',
          options: ['نُونَ التَّوْكِيدِ', 'تَاءَ التَّأْنِيثِ', 'يَاءَ الْمُخَاطَبَةِ', 'وَاوَ الْجَمَاعَةِ'],
          correct: 0,
        },
        {
          q: 'Which pairing of شَرْط and جَوَاب leaves the second فِعْل free to take either جَزْم or رَفْع?',
          options: ['مَاضٍ then مُضَارِع', 'مُضَارِع then مُضَارِع', 'مَاضٍ then مَاضٍ', 'مُضَارِع then مَاضٍ'],
          correct: 0,
        },
      ],
      bank: [
        {
          title: 'جَازِمُ فِعْلٍ وَاحِدٍ',
          kind: 'mcq',
          prompt: 'Which of these جَوَازِم gives جَزْم to ONE فِعْل only?',
          options: ['لَمْ', 'إِنْ', 'إِذْمَا', 'Both إِنْ and إِذْمَا'],
          correct: 0,
        },
        {
          title: 'جَازِمَا فِعْلَيْنِ',
          kind: 'mcq',
          prompt: 'Which two جَوَازِم give جَزْم to TWO أَفْعَال?',
          options: ['إِنْ وَإِذْمَا', 'لَمْ وَلَمَّا', 'لَامُ الْأَمْرِ وَلَا النَّاهِيَةُ', 'لَنْ وَكَيْ'],
          correct: 0,
        },
        {
          title: 'عَلَامَاتُ الْجَزْمِ',
          kind: 'mcq',
          prompt: 'Which set names the three signs by which جَزْم appears on a مُضَارِع?',
          options: ['السُّكُون، حَذْفُ حَرْفِ الْعِلَّةِ، حَذْفُ النُّونِ', 'الْفَتْحَة، الْكَسْرَة، السُّكُون', 'السُّكُون، الْفَتْحَة، حَذْفُ النُّونِ', 'حَذْفُ النُّونِ، ثُبُوتُ النُّونِ، التَّنْوِين'],
          correct: 0,
        },
        {
          title: 'لَمْ يَلِدْ وَلَمْ يُولَدْ',
          kind: 'mcq',
          prompt: '﴿لَمْ يَلِدْ وَلَمْ يُولَدْ﴾ illustrates لَمْ:',
          options: ['negating the مُضَارِع and turning it to past meaning', 'negating a فِعْل أَمْر', 'negating a فِعْل مَاضٍ directly', 'making a request'],
          correct: 0,
        },
        {
          title: 'لَمْ أَمْ لَنْ؟',
          kind: 'mcq',
          prompt: 'لَمْ and لَنْ both negate a مُضَارِع. What separates them?',
          options: ['لَمْ gives جَزْم and negates the past; لَنْ gives نَصْب and negates the future', 'لَمْ gives نَصْب and negates the future; لَنْ gives جَزْم and negates the past', 'Both give جَزْم, and they differ only in emphasis', 'Both give نَصْب, and they differ only in emphasis'],
          correct: 0,
        },
        {
          title: 'لَمَّا وَتَوَقُّعُ الْحُصُولِ',
          kind: 'mcq',
          prompt: '﴿وَلَمَّا يَدْخُلِ الْإِيمَانُ فِي قُلُوبِكُمْ﴾ — لَمَّا here adds a sense of:',
          options: ['تَوَقُّع الْحُصُول — it has not happened yet, but is awaited', 'اسْتِحَالَة الْحُصُول — it can never happen', 'تَكْرَار الْحُصُول — it happens again and again', 'نَفْي التَّوَقُّع — it is expressly not awaited'],
          correct: 0,
        },
        {
          title: 'كَسْرَةُ الْتِقَاءِ السَّاكِنَيْنِ',
          kind: 'mcq',
          prompt: 'يَدْخُلِ in ﴿وَلَمَّا يَدْخُلِ الْإِيمَانُ﴾ is مَجْزُوم, yet it is read with a كَسْرَة. Why?',
          options: ['Its سُكُون of جَزْم was broken to a كَسْرَة to avoid two سَاكِنَيْنِ meeting', 'It is not مَجْزُوم at all — لَمَّا leaves the فِعْل مَجْرُورًا', 'الْإِيمَانُ is مُضَاف إِلَيْهِ, so the فِعْل before it takes جَرّ', 'The كَسْرَة is the regular sign of جَزْم on a sound فِعْل'],
          correct: 0,
        },
        {
          title: 'لَامُ الْأَمْرِ وَلَا النَّاهِيَةُ مَعًا',
          kind: 'mcq',
          prompt: '﴿فَمَنْ كَانَ يَرْجُو لِقَاءَ رَبِّهِ فَلْيَعْمَلْ عَمَلًا صَالِحًا وَلَا يُشْرِكْ بِعِبَادَةِ رَبِّهِ أَحَدًا﴾ contains both:',
          options: ['لَامُ الْأَمْرِ وَلَا النَّاهِيَةُ', 'لَمْ وَلَمَّا', 'إِنْ وَإِذْمَا', 'كَيْ وَلَنْ'],
          correct: 0,
        },
        {
          title: 'مَعْنَى اللَّامِ وَاللَّاءِ',
          kind: 'mcq',
          prompt: 'لَامُ الْأَمْرِ and لَا النَّاهِيَةُ both give جَزْم. What does each of them make of the مُضَارِع?',
          options: ['لَامُ الْأَمْرِ makes it a command; لَا النَّاهِيَةُ makes it a prohibition', 'لَامُ الْأَمْرِ makes it a prohibition; لَا النَّاهِيَةُ makes it a command', 'Both make it a command, differing only in politeness', 'Both negate it, differing only in tense'],
          correct: 0,
        },
        {
          title: 'الشَّرْطُ وَالْجَزَاءُ',
          kind: 'mcq',
          prompt: 'In ﴿إِنْ تَجْتَنِبُوا كَبَائِرَ مَا تُنْهَوْنَ عَنْهُ نُكَفِّرْ عَنْكُمْ سَيِّئَاتِكُمْ﴾, تَجْتَنِبُوا is the:',
          options: ['شَرْط', 'جَوَاب الشَّرْط, the الْجَزَاء', 'مُبْتَدَأ', 'حَال'],
          correct: 0,
        },
        {
          title: 'إِعْرَابُ تُقْبَلْ',
          kind: 'mcq',
          prompt: 'إِذْمَا تَتُبْ تُقْبَلْ تَوْبَتُكَ — what is the إِعْرَاب of تُقْبَلْ?',
          options: ['مَجْزُوم by a سُكُون, being جَوَابَ الشَّرْطِ', 'مَرْفُوع by a ضَمَّة, standing outside إِذْمَا\'s reach', 'مَنْصُوب by a فَتْحَة, إِذْمَا being a نَاصِب', 'مَجْزُوم by حَذْفِ النُّونِ, being مِنَ الْأَفْعَالِ الْخَمْسَةِ'],
          correct: 0,
        },
        {
          title: 'عَدَدُ مَوَاضِعِ إِضْمَارِ إِنْ',
          kind: 'mcq',
          prompt: 'After how many things may إِنْ be مُقَدَّرَة before a مُضَارِع مَجْزُوم?',
          options: ['أَرْبَعَة', 'اثْنَانِ', 'ثَلَاثَة', 'خَمْسَة'],
          correct: 0,
        },
        {
          title: 'إِنْ مُقَدَّرَة بَعْدَ طَلَبٍ',
          kind: 'mcq',
          prompt: '﴿تَعَالَوْا أَتْلُ﴾, read as إِنْ تَتَعَالَوْا أَتْلُ, shows إِنْ مُقَدَّرَة after:',
          options: ['طَلَب', 'اسْتِفْهَام', 'تَمَنٍّ', 'عَرْض'],
          correct: 0,
        },
        {
          title: 'دَلِيلُ إِنْ الْمُقَدَّرَةِ',
          kind: 'mcq',
          prompt: 'No حَرْف شَرْط is written in ﴿تَعَالَوْا أَتْلُ﴾. What is the evidence that one is understood?',
          options: ['The جَزْم on أَتْلُ, which nothing else in the sentence could have produced', 'The وَاو of الْجَمَاعَة on تَعَالَوْا', 'The absence of a فَاء before أَتْلُ', 'The فِعْل أَمْر at the head of the sentence, which is itself a جَازِم'],
          correct: 0,
        },
        {
          title: 'إِنْ مُقَدَّرَة بَعْدَ تَمَنٍّ',
          kind: 'mcq',
          prompt: 'لَيْتَكَ عِنْدِي أَخْدِمْكَ shows إِنْ مُقَدَّرَة after:',
          options: ['تَمَنٍّ', 'طَلَب', 'اسْتِفْهَام', 'عَرْض'],
          correct: 0,
        },
        {
          title: 'إِنْ مُقَدَّرَة بَعْدَ عَرْضٍ',
          kind: 'mcq',
          prompt: 'أَلَا تَنْزِلُ بِنَا تُصِبْ خَيْرًا shows إِنْ مُقَدَّرَة after:',
          options: ['عَرْض', 'اسْتِفْهَام', 'تَمَنٍّ', 'طَلَب'],
          correct: 0,
        },
        {
          title: 'مِمَّ تَتَرَكَّبُ إِمَّا؟',
          kind: 'mcq',
          prompt: 'The إِمَّا of ﴿وَإِمَّا يَنْزَغَنَّكَ مِنَ الشَّيْطَانِ نَزْغٌ﴾ is made up of:',
          options: ['إِنِ الشَّرْطِيَّة plus مَا الزَّائِدَة', 'إِنِ النَّافِيَة plus مَا الْمَصْدَرِيَّة', 'إِنَّ الْمُشَدَّدَة plus مَا الْكَافَّة', 'أَمَّا التَّفْصِيلِيَّة with its أَلِف dropped'],
          correct: 0,
        },
        {
          title: 'كِلَا الْفِعْلَيْنِ مُضَارِعٌ',
          kind: 'mcq',
          prompt: '﴿وَإِنْ تَعُودُوا نَعُدْ﴾ shows the شَرْط and the جَوَاب as:',
          options: ['both مُضَارِع', 'both مَاضٍ', 'مُضَارِع then مَاضٍ', 'مَاضٍ then مُضَارِع'],
          correct: 0,
        },
        {
          title: 'كِلَا الْفِعْلَيْنِ مَاضٍ',
          kind: 'mcq',
          prompt: '﴿وَإِنْ عُدْتُمْ عُدْنَا﴾ shows the شَرْط and the جَوَاب as:',
          options: ['both مَاضٍ', 'both مُضَارِع', 'مُضَارِع then مَاضٍ', 'مَاضٍ then مُضَارِع'],
          correct: 0,
        },
        {
          title: 'مَتَى تَلْزَمُ الْفَاءُ؟',
          kind: 'mcq',
          prompt: 'Which kind of جَوَاب has to have a فَاء placed before it?',
          options: ['One that cannot take جَزْم — a جُمْلَة اسْمِيَّة, a طَلَب, or a فِعْل جَامِد', 'One whose شَرْط is a فِعْل مَاضٍ', 'One made of a مُضَارِع مَجْزُوم', 'One introduced by إِذْمَا rather than إِنْ'],
          correct: 0,
        },
        {
          title: 'تَرْكِيب: تَصْنِيفُ الْجَوَازِمِ',
          kind: 'tarkeeb',
          instruction: 'Classify each جَازِم: does it give جَزْم to one فِعْل or to two?',
          source: 'لَمْ / لَا النَّاهِيَةُ / إِنْ / إِذْمَا',
          words: ['لَمْ', 'لَا النَّاهِيَةُ', 'إِنْ', 'إِذْمَا'],
          labels: ['فِعْلًا وَاحِدًا', 'فِعْلًا وَاحِدًا', 'فِعْلَيْنِ', 'فِعْلَيْنِ'],
          distractors: ['ثَلَاثَةَ أَفْعَالٍ'],
        },
        {
          title: 'تَرْكِيب: لَمْ وَلَمَّا',
          kind: 'tarkeeb',
          instruction: 'Classify each حَرْف by what it adds beyond plain نَفْي.',
          source: 'لَمْ / لَمَّا',
          words: ['لَمْ', 'لَمَّا'],
          labels: ['نَفْيٌ وَقَلْبٌ لِلْمَاضِي فَقَطْ', 'نَفْيٌ وَقَلْبٌ لِلْمَاضِي مَعَ تَوَقُّعِ الْحُصُولِ'],
          distractors: ['نَفْيُ الْمُسْتَقْبَلِ'],
        },
        {
          title: 'تَرْكِيب: مَوَاضِعُ إِضْمَارِ إِنْ الْأَرْبَعَةُ',
          kind: 'tarkeeb',
          instruction: 'Match each example to the مَوْضِع of إِضْمَار إِنْ it illustrates.',
          source: '﴿تَعَالَوْا أَتْلُ﴾ / هَلْ تَزُورُنَا نُكْرِمْكَ / لَيْتَكَ عِنْدِي أَخْدِمْكَ / أَلَا تَنْزِلُ بِنَا تُصِبْ خَيْرًا',
          words: ['تَعَالَوْا أَتْلُ', 'هَلْ تَزُورُنَا نُكْرِمْكَ', 'لَيْتَكَ عِنْدِي أَخْدِمْكَ', 'أَلَا تَنْزِلُ بِنَا تُصِبْ'],
          labels: ['طَلَبٌ', 'اسْتِفْهَامٌ', 'تَمَنٍّ', 'عَرْضٌ'],
          distractors: ['نَهْيٌ'],
        },
        {
          title: 'تَرْكِيب: تَوَافُقُ الْأَزْمِنَةِ بَعْدَ إِنْ',
          kind: 'tarkeeb',
          instruction: 'Classify the tense pairing of شَرْط and جَوَاب in each example.',
          source: '﴿وَإِنْ تَعُودُوا نَعُدْ﴾ / ﴿وَإِنْ عُدْتُمْ عُدْنَا﴾ / مَنْ يَقُمْ لَيْلَةَ الْقَدْرِ غُفِرَ لَهُ / ﴿مَنْ كَانَ يُرِيدُ حَرْثَ الْآخِرَةِ نَزِدْ لَهُ فِي حَرْثِهِ﴾',
          words: ['وَإِنْ تَعُودُوا نَعُدْ', 'وَإِنْ عُدْتُمْ عُدْنَا', 'مَنْ يَقُمْ... غُفِرَ لَهُ', 'مَنْ كَانَ يُرِيدُ... نَزِدْ لَهُ'],
          labels: ['مُضَارِعٌ ثُمَّ مُضَارِعٍ', 'مَاضٍ ثُمَّ مَاضٍ', 'مُضَارِعٌ ثُمَّ مَاضٍ', 'مَاضٍ ثُمَّ مُضَارِعٍ'],
          distractors: ['أَمْرٌ ثُمَّ مُضَارِعٍ'],
        },
        {
          title: 'تَرْكِيب: عَلَامَةُ الْجَزْمِ',
          kind: 'tarkeeb',
          instruction: 'Identify the sign of جَزْم on each فِعْل مَجْزُوم.',
          source: 'يَلِدْ / أَتْلُ / تَجْتَنِبُوا / تُقْبَلْ',
          words: ['يَلِدْ', 'أَتْلُ', 'تَجْتَنِبُوا', 'تُقْبَلْ'],
          labels: ['سُكُونٌ', 'حَذْفُ حَرْفِ الْعِلَّةِ', 'حَذْفُ النُّونِ', 'سُكُونٌ'],
          distractors: ['فَتْحَةٌ', 'ثُبُوتُ النُّونِ'],
        },
        {
          title: 'تَرْكِيب: الشَّرْطُ أَمِ الْجَوَابُ؟',
          kind: 'tarkeeb',
          instruction: 'Label each فِعْل: is it the شَرْط or the جَوَاب?',
          source: '﴿إِنْ تَجْتَنِبُوا... نُكَفِّرْ عَنْكُمْ﴾ / إِذْمَا تَتُبْ تُقْبَلْ تَوْبَتُكَ',
          words: ['تَجْتَنِبُوا', 'نُكَفِّرْ', 'تَتُبْ', 'تُقْبَلْ'],
          labels: ['شَرْطٌ', 'جَوَابٌ', 'شَرْطٌ', 'جَوَابٌ'],
          distractors: ['فَاعِلٌ'],
        },
      ],
    },
  ],
};
