// Module 10 — حذف العامل
//
// Content is adapted from the closing ("خاتم") deck of the العامل وغير
// العامل chapter (النَحْوُ__2 الْعَامِلِ وَغَيْرِ الْعَامِلِ__4 خاتم.apkg,
// 73 notes, all of them here). This module ties off the whole العامل وغير
// العامل chapter (modules 2-8) with: التنازع (two عوامل contending over
// one معمول), the جائز/واجب divide in حذف العامل, and the concrete places
// where deletion of the عامل is obligatory — عامل المفعول المطلق (سماعي
// وقياسي), عامل المفعول به (its five places: التحذير، الإغراء، الاختصاص،
// الاشتغال، النداء — with النداء's own حروف, إعراب, ياء المتكلم, الترخيم,
// الاستغاثة, نداء التعجب, and الندبة all folded in as its extensions), and
// عامل الحال.

export default {
  id: '10',
  title: 'حذف العامل',
  heading: 'العامل وغير العامل',
  subheading: 'خاتم',
  blurb: 'التنازع بين عاملين على معمول واحد, الحذف الجائز والواجب للعامل, حذف عامل المفعول المطلق (السماعي والقياسي), التحذير والإغراء والاختصاص والاشتغال, أركان النداء وحروفه وإعرابه وياء المتكلم والترخيم, and الاستغاثة والندبة وحذف عامل الحال.',
  lessons: [
    // ---------------------------------------------------------------- L1
    {
      id: 'l1',
      title: 'التنازع وحذف العامل',
      subtitle: "Contending Governors and the Two Kinds of Deletion — التنازع, الحذف الجائز, and الحذف الواجب's three أضرب",
      concepts: [
        {
          heading: 'التنازع: تعريفه ومن يتولى العمل',
          body: `<bdi>التَّنَازُع</bdi> is when two <bdi>عَامِلَانِ</bdi> (governors) both compete to govern a single <bdi>مَعْمُول</bdi> that comes after both of them — its other name is <bdi>الْإِعْمَال</bdi>. Either governor may be the one that actually governs the معمول: it is permissible for the first or the second عامل to take the credit, so the choice is not fixed to one side.`,
          sample: `التنازع — عاملان يتنازعان معمولا واحدا يأتي بعدهما؛ يسمى أيضا الإعمال<br>من يتولى العمل؟ — يجوز أن يُعمَل الأول أو الثاني`,
          exercise: {
            prompt: `What is التنازع, and which of the two contending عاملان is allowed to govern the معمول؟`,
            kind: 'mcq',
            options: ['Two عاملان competing over one معمول after both of them; either one may govern it', 'One عامل governing two معمولات at once', 'A معمول that has no عامل at all', 'Two معمولات competing over a single عامل before both of them'],
            correct: 0,
          },
        },
        {
          heading: 'أمثلة التنازع: فعلان، اسمان، وأكثر من عاملين',
          body: `التنازع happens between two <bdi>أَفْعَال</bdi>, as in <bdi>﴿كُلُوا وَاشْرَبُوا مِنْ رِزْقِ اللَّهِ﴾</bdi>, or between two <bdi>أَسْمَاء</bdi>, as in <bdi>﴿وَإِنْ أَدْرِي أَقَرِيبٌ أَمْ بَعِيدٌ مَا تُوعَدُونَ﴾</bdi>. More than two عوامل can even contend over the same معمول — a hadith has three verbs contending over <bdi>ثَلَاثًا وَثَلَاثِينَ</bdi>: <bdi>«تُسَبِّحُونَ وَتَحْمَدُونَ وَتُكَبِّرُونَ دُبُرَ كُلِّ صَلَاةٍ ثَلَاثًا وَثَلَاثِينَ مَرَّةً»</bdi>.`,
          sample: `تنازع فعلين — ﴿كلوا واشربوا من رزق الله﴾<br>تنازع اسمين — ﴿وإن أدري أقريب أم بعيد ما توعدون﴾<br>أكثر من عاملين — «تسبحون وتحمدون وتكبرون... ثلاثا وثلاثين»`,
          exercise: {
            prompt: `Can more than two عوامل contend over a single معمول? Which example shows this؟`,
            kind: 'mcq',
            options: ['Yes — a hadith has three verbs (تسبحون وتحمدون وتكبرون) contending over one معمول', 'No, التنازع is strictly limited to exactly two عوامل', 'Only two أسماء can contend, never أفعال', 'Only in poetry, never in hadith or Qur’an'],
            correct: 0,
          },
        },
        {
          heading: 'حذف العامل: الجائز',
          body: `<bdi>حَذْفُ الْعَامِل</bdi> (deleting the governor while keeping its معمول) falls into two categories: <bdi>الْحَذْفُ الْجَائِز</bdi> and <bdi>الْحَذْفُ الْوَاجِب</bdi>. Deletion is permissible when a <bdi>قَرِينَةُ السِّيَاق</bdi> (contextual clue) makes the deleted عامل recoverable, as in <bdi>﴿مَاذَا أَنْزَلَ رَبُّكُمْ قَالُوا خَيْرًا﴾</bdi> — the answer implies <bdi>أَنْزَلَ خَيْرًا</bdi>, so <bdi>خَيْرًا</bdi> is منصوب as the مفعول به of that understood, deleted verb.`,
          sample: `الحذف الجائز — بقرينة السياق: ﴿ماذا أنزل ربكم قالوا خيرا﴾، أي أنزل خيرا<br>إعراب خيرا — مفعول به لفعل محذوف جوازا (أنزل)`,
          exercise: {
            prompt: `In ﴿قَالُوا خَيْرًا﴾, why is خيرا منصوب, and what kind of deletion does this illustrate؟`,
            kind: 'mcq',
            options: ['It’s مفعول به of a permissibly (جوازا) deleted verb أنزل, recoverable from context', 'It’s مفعول به of an obligatorily deleted verb', 'It’s حال منصوبة with no deleted عامل at all', 'It’s منصوب because it follows إنّ'],
            correct: 0,
          },
        },
        {
          heading: 'الحذف الواجب: أضربه الثلاثة',
          body: `<bdi>الْحَذْفُ الْوَاجِب</bdi> (obligatory deletion) of the عامل occurs in three <bdi>أَضْرُب</bdi> (types): the عامل of <bdi>الْمَفْعُول الْمُطْلَق</bdi>, of <bdi>الْمَفْعُول بِهِ</bdi>, and of <bdi>الْحَال</bdi>. Deletion of عامل المفعول به specifically is obligatory in five places: (1) <bdi>التَّحْذِير</bdi> (2) <bdi>الْإِغْرَاء</bdi> (3) <bdi>الِاخْتِصَاص</bdi> (4) <bdi>الِاشْتِغَال</bdi> (5) <bdi>النِّدَاء</bdi> — the rest of this module works through each of these three أضرب in turn.`,
          sample: `الحذف الواجب: ثلاثة أضرب — عامل المفعول المطلق، عامل المفعول به، عامل الحال<br>مواضع وجوب حذف عامل المفعول به الخمسة — التحذير، الإغراء، الاختصاص، الاشتغال، النداء`,
          exercise: {
            prompt: `الحذف الواجب of the عامل occurs in three أضرب. What are they؟`,
            kind: 'mcq',
            options: ['عامل المفعول المطلق, عامل المفعول به, and عامل الحال', 'عامل الفاعل, عامل المبتدأ, and عامل الخبر', 'عامل الحال فقط, with no other ضرب', 'عامل الجار والمجرور فقط'],
            correct: 0,
          },
        },
      ],
      quiz: [
        { q: 'What is the other name for التنازع؟', options: ['الإعمال', 'الإهمال', 'الإغراء', 'الاختصاص'], correct: 0 },
        { q: '﴿كُلُوا وَاشْرَبُوا مِنْ رِزْقِ اللَّهِ﴾ illustrates التنازع between:', options: ['two أفعال', 'two أسماء', 'a فعل and an اسم', 'two حروف'], correct: 0 },
        { q: 'In التنازع, which عامل is permitted to govern the معمول؟', options: ['Either the first or the second, freely', 'Only the first, never the second', 'Only the second, never the first', 'Neither — the معمول is left without إعراب'], correct: 0 },
        { q: 'حذف العامل falls into two categories:', options: ['الحذف الجائز and الحذف الواجب', 'الحذف السماعي and الحذف القياسي only', 'التنازع and الإعمال', 'الحذف اللفظي and الحذف المحلي'], correct: 0 },
        { q: 'In ﴿مَاذَا أَنْزَلَ رَبُّكُمْ قَالُوا خَيْرًا﴾, خيرا is منصوب as:', options: ['مفعول به of the permissibly deleted فعل أنزل', 'فاعل of a deleted فعل', 'حال منصوبة with no deleted عامل', 'مفعول مطلق مؤكد'], correct: 0 },
        { q: 'الحذف الواجب of the عامل has three أضرب: عامل المفعول المطلق, عامل الحال, and:', options: ['عامل المفعول به', 'عامل الفاعل', 'عامل المبتدأ', 'عامل الجار والمجرور'], correct: 0 },
      ],
      bank: [
        { title: 'تعريف التنازع', kind: 'mcq', prompt: 'التنازع is defined as:', options: ['Two عاملان contending over one معمول that follows both of them', 'One عامل governing two معمولات', 'A معمول with two متعلقات', 'A عامل that governs nothing at all'], correct: 0 },
        { title: 'اسم آخر للتنازع', kind: 'mcq', prompt: 'التنازع is also known by the name:', options: ['الإعمال', 'الإهمال', 'التوكيد', 'الاستثناء'], correct: 0 },
        { title: 'تنازع اسمين', kind: 'mcq', prompt: '﴿وَإِنْ أَدْرِي أَقَرِيبٌ أَمْ بَعِيدٌ مَا تُوعَدُونَ﴾ shows التنازع between:', options: ['two أسماء', 'two أفعال', 'a حرف and an اسم', 'three أفعال'], correct: 0 },
        { title: 'تنازع أكثر من عاملين', kind: 'mcq', prompt: 'The hadith «تُسَبِّحُونَ وَتَحْمَدُونَ وَتُكَبِّرُونَ... ثَلَاثًا وَثَلَاثِينَ» shows how many عوامل contending over ثلاثا وثلاثين؟', options: ['Three', 'Two', 'Four', 'Only one, with no real تنازع'], correct: 0 },
        { title: 'حرية اختيار العامل', kind: 'mcq', prompt: 'When two عاملان contend in التنازع, the rule is that:', options: ['governing by the first or the second is equally permissible', 'only the nearer عامل is ever allowed to govern', 'only the farther عامل is ever allowed to govern', 'neither عامل is allowed to govern — the معمول stays without إعراب'], correct: 0 },
        { title: 'قرينة السياق في الحذف الجائز', kind: 'mcq', prompt: 'What licenses الحذف الجائز of an عامل؟', options: ['A قرينة السياق (contextual clue) that makes it recoverable', 'The عامل being a فعل أمر specifically', 'The معمول being a مصدر specifically', 'Nothing licenses it — الحذف الجائز never actually happens'], correct: 0 },
        { title: 'إعراب خيرا', kind: 'mcq', prompt: 'In ﴿قَالُوا خَيْرًا﴾, خيرا is:', options: ['مفعول به of a جوازا-deleted فعل (أنزل)', 'فاعل of a stated فعل', 'حال with no deleted عامل', 'مبتدأ خبره محذوف'], correct: 0 },
        { title: 'أضرب الحذف الواجب الثلاثة', kind: 'mcq', prompt: 'Which three أضرب does الحذف الواجب of the عامل fall into?', options: ['عامل المفعول المطلق, عامل المفعول به, عامل الحال', 'عامل الفاعل, عامل النائب عن الفاعل, عامل الحال', 'عامل المبتدأ, عامل الخبر, عامل الحال', 'عامل التمييز, عامل المستثنى, عامل البدل'], correct: 0 },
        { title: 'مواضع المفعول به الخمسة', kind: 'mcq', prompt: 'Deletion of عامل المفعول به is obligatory in how many places, and what are they؟', options: ['Five: التحذير، الإغراء، الاختصاص، الاشتغال، النداء', 'Three: التحذير، الإغراء، النداء', 'Five, but النداء is not one of them', 'Two: الاختصاص والاشتغال only'], correct: 0 },
        { title: 'الفرق بين الجائز والواجب', kind: 'mcq', prompt: 'What distinguishes الحذف الواجب from الحذف الجائز؟', options: ['الواجب must be deleted in its fixed places; الجائز is only optionally deleted when context allows it', 'الجائز only ever applies to أفعال, الواجب only to أسماء', 'الواجب applies only to حروف الجر', 'There is no real difference between them'], correct: 0 },
        {
          title: 'تركيب: جائز أم واجب؟',
          kind: 'tarkeeb',
          instruction: 'Classify each case of حذف العامل: الجائز or الواجب؟',
          source: '﴿ماذا أنزل ربكم قالوا خيرا﴾ / عامل المفعول المطلق في مواضعه الأربعة',
          words: ['قالوا خيرا', 'عامل المفعول المطلق'],
          labels: ['الحذف الجائز', 'الحذف الواجب'],
          distractors: ['التنازع'],
        },
        {
          title: 'تركيب: أضرب الحذف الواجب',
          kind: 'tarkeeb',
          instruction: 'Match each عامل to the ضرب of الحذف الواجب it belongs to.',
          source: 'عامل صبرا في صبرا لا جزعا / عامل خيرا في التحذير / عامل مستيقنا في دعائي ربي مستيقنا',
          words: ['عامل مصدر النهي', 'عامل التحذير', 'عامل الحال'],
          labels: ['عامل المفعول المطلق', 'عامل المفعول به', 'عامل الحال'],
          distractors: ['عامل الفاعل'],
        },
        {
          title: 'تركيب: تنازع فعلين أم اسمين؟',
          kind: 'tarkeeb',
          instruction: 'Classify each مثال of التنازع.',
          source: '﴿كلوا واشربوا من رزق الله﴾ / ﴿وإن أدري أقريب أم بعيد ما توعدون﴾',
          words: ['كلوا واشربوا', 'أقريب أم بعيد'],
          labels: ['تنازع فعلين', 'تنازع اسمين'],
          distractors: ['تنازع حرفين'],
        },
      ],
    },
    // ---------------------------------------------------------------- L2
    {
      id: 'l2',
      title: 'حذف عامل المفعول المطلق',
      subtitle: 'Deleting the Governor of the Absolute Object — سماعي and قياسي deletion, and قياسي’s four places',
      concepts: [
        {
          heading: 'نوعا حذف عامل المفعول المطلق: سماعي وقياسي',
          body: `Obligatory deletion of عامل المفعول المطلق comes in two kinds: <bdi>سَمَاعِيّ</bdi> (attested by hearing — memorized as fixed expressions, not extendable by rule to new cases) and <bdi>قِيَاسِيّ</bdi> (extendable by analogy to any case matching one of its defined places).`,
          sample: `نوعا حذف عامل المفعول المطلق — سماعي (يُسمع ولا يُقاس عليه) وقياسي (يُقاس عليه في مواضعه)`,
          exercise: {
            prompt: `Obligatory deletion of عامل المفعول المطلق comes in which two kinds؟`,
            kind: 'mcq',
            options: ['سماعي and قياسي', 'جائز and واجب only', 'لفظي and محلي', 'مفرد and مركب'],
            correct: 0,
          },
        },
        {
          heading: 'القياسي: أربعة مواضع',
          body: `The قياسي obligatory deletion occurs in four places: (1) a <bdi>مَصْدَر</bdi> functioning as a <bdi>نَهْي</bdi> following a مصدر intended as an <bdi>أَمْر</bdi> (2) after an <bdi>اسْتِفْهَام</bdi> intended as <bdi>تَوْبِيخ</bdi> (rebuke) (3) after <bdi>إِمَّا</bdi> giving <bdi>تَفْصِيل</bdi> of a preceding <bdi>مُجْمَل</bdi> (4) a مصدر confirming the content of the sentence (<bdi>مُؤَكِّدٌ لِمَضْمُونِ الْجُمْلَة</bdi>).`,
          sample: `المواضع القياسية الأربعة — (1) مصدر نهي بعد مصدر أمر (2) بعد استفهام التوبيخ (3) بعد إما تفصيلا لمجمل (4) مصدر مؤكد لمضمون الجملة`,
          exercise: {
            prompt: `List the four قياسي places where عامل المفعول المطلق is obligatorily deleted.`,
            kind: 'mcq',
            options: ['نهي بعد أمر, استفهام توبيخ, إما تفصيلا لمجمل, مؤكد لمضمون الجملة', 'نداء, تحذير, إغراء, اختصاص', 'شرط, جواب شرط, قسم, جواب قسم', 'حال, تمييز, مستثنى, بدل'],
            correct: 0,
          },
        },
        {
          heading: 'مثالا الأمر والنهي، والتوبيخ',
          body: `<bdi>صَبْرًا لَا جَزَعًا</bdi> means <bdi>اِصْبِرْ صَبْرًا وَلَا تَجْزَعْ جَزَعًا</bdi> — a نهي مصدر paired with the preceding أمر مصدر it echoes. For استفهام التوبيخ: <bdi>أَجُرْأَةً عَلَى الْمَعَاصِي؟</bdi> ("Such audacity toward sins?!") — the استفهام here is not a real question, it is rebuke.`,
          sample: `أمر ونهي — صبرا لا جزعا، أي اصبر صبرا ولا تجزع جزعا<br>توبيخ — أجرأة على المعاصي؟`,
          exercise: {
            prompt: `صَبْرًا لَا جَزَعًا illustrates which قياسي موضع؟`,
            kind: 'mcq',
            options: ['A نهي مصدر following an أمر مصدر', 'استفهام intended as توبيخ', 'إما giving تفصيل لمجمل', 'A مصدر مؤكد لمضمون الجملة'],
            correct: 0,
          },
        },
        {
          heading: 'إما تفصيلا لمجمل، والمؤكد لمضمون الجملة',
          body: `<bdi>﴿فَشُدُّوا الْوَثَاقَ فَإِمَّا مَنًّا بَعْدُ وَإِمَّا فِدَاءً﴾</bdi> — <bdi>مَنًّا</bdi> and <bdi>فِدَاءً</bdi> detail the preceding مجمل. And <bdi>حَقًّا</bdi> in <bdi>﴿أُولَٰئِكَ هُمُ الْمُؤْمِنُونَ حَقًّا﴾</bdi> is a مصدر مؤكد لمضمون الجملة, whose عامل is obligatorily (قياسا) deleted.`,
          sample: `إما تفصيلا لمجمل — ﴿فشدوا الوثاق فإما منا بعد وإما فداء﴾<br>مؤكد لمضمون الجملة — ﴿أولئك هم المؤمنون حقا﴾`,
          exercise: {
            prompt: `Why is حقا منصوب in ﴿أُولَٰئِكَ هُمُ الْمُؤْمِنُونَ حَقًّا﴾؟`,
            kind: 'mcq',
            options: ['It’s a مفعول مطلق مؤكد لمضمون الجملة with an obligatorily deleted عامل', 'It’s a حال with a deleted عامل', 'It’s a تمييز with no deleted عامل', 'It’s a مفعول به of a stated verb'],
            correct: 0,
          },
        },
        {
          heading: 'أمثلة سماعية لحذف عامل المفعول المطلق',
          body: `Examples of the سماعي deletion include <bdi>سُبْحَانَ اللَّهِ</bdi>, <bdi>مَعَاذَ اللَّهِ</bdi>, <bdi>عَجَبًا لَكَ</bdi>, <bdi>حَمْدًا وَشُكْرًا لَا كُفْرًا</bdi>, and <bdi>لَبَّيْكَ</bdi> and its sisters. Because these are سماعي rather than قياسي, they are memorized as fixed expressions rather than extended to new, unattested cases.`,
          sample: `سماعي — سبحان الله، معاذ الله، عجبا لك، حمدا وشكرا لا كفرا، لبيك وأخواتها`,
          exercise: {
            prompt: `سُبْحَانَ اللَّهِ and مَعَاذَ اللَّهِ are examples of which kind of عامل deletion؟`,
            kind: 'mcq',
            options: ['سماعي — attested and not extended by rule to new cases', 'قياسي — extended by rule to any matching case', 'الحذف الجائز, not الواجب', 'A case where the عامل is not actually deleted'],
            correct: 0,
          },
        },
      ],
      quiz: [
        { q: 'Obligatory deletion of عامل المفعول المطلق comes in which two kinds؟', options: ['سماعي and قياسي', 'جائز and واجب only', 'لفظي and محلي', 'مفرد and مركب'], correct: 0 },
        { q: 'How many قياسي places does obligatory deletion of عامل المفعول المطلق occur in؟', options: ['Four', 'Two', 'Six', 'Three'], correct: 0 },
        { q: 'صَبْرًا لَا جَزَعًا illustrates:', options: ['A نهي مصدر following an أمر مصدر', 'استفهام intended as توبيخ', 'إما giving تفصيل لمجمل', 'A مصدر مؤكد لمضمون الجملة'], correct: 0 },
        { q: '﴿فَشُدُّوا الْوَثَاقَ فَإِمَّا مَنًّا بَعْدُ وَإِمَّا فِدَاءً﴾ illustrates a مصدر:', options: ['giving إما تفصيلا لمجمل', 'confirming مضمون الجملة', 'following a نهي', 'after استفهام التوبيخ'], correct: 0 },
        { q: 'حقا in ﴿أُولَٰئِكَ هُمُ الْمُؤْمِنُونَ حَقًّا﴾ is:', options: ['مصدر مؤكد لمضمون الجملة', 'حال', 'تمييز', 'مفعول به'], correct: 0 },
        { q: 'سُبْحَانَ اللَّهِ is an example of the ___ deletion of عامل المفعول المطلق.', options: ['سماعي', 'قياسي', 'الجائز غير الواجب', 'no deletion at all'], correct: 0 },
      ],
      bank: [
        { title: 'نوعا الحذف الواجب لعامل المفعول المطلق', kind: 'mcq', prompt: 'نوعا الحذف الواجب لعامل المفعول المطلق هما:', options: ['سماعي وقياسي', 'جائز وواجب فقط', 'مفرد ومركب', 'لفظي ومحلي'], correct: 0 },
        { title: 'أجرأة على المعاصي', kind: 'mcq', prompt: 'أَجُرْأَةً عَلَى الْمَعَاصِي؟ illustrates:', options: ['استفهام intended as توبيخ', 'نهي following an أمر', 'إما giving تفصيلا لمجمل', 'مصدر مؤكد لمضمون الجملة'], correct: 0 },
        { title: 'حمدا وشكرا لا كفرا', kind: 'mcq', prompt: 'حَمْدًا وَشُكْرًا لَا كُفْرًا is:', options: ['سماعي', 'قياسي', 'مثال على الحذف الجائز', 'مثال لا يتضمن حذف عامل أصلا'], correct: 0 },
        { title: 'عجبا لك', kind: 'mcq', prompt: 'عَجَبًا لَكَ is:', options: ['سماعي', 'قياسي', 'إما تفصيلا لمجمل', 'مؤكد لمضمون الجملة'], correct: 0 },
        { title: 'لبيك وأخواتها', kind: 'mcq', prompt: 'لَبَّيْكَ وَأَخَوَاتُهَا belong to which kind of حذف عامل المفعول المطلق؟', options: ['السماعي', 'القياسي', 'الجائز فقط', 'لا يوجد حذف فيها'], correct: 0 },
        { title: 'الأصل غير المحذوف', kind: 'mcq', prompt: 'صَبْرًا لَا جَزَعًا, once its deleted عامل is restored, reads:', options: ['اصبر صبرا ولا تجزع جزعا', 'أجرأة على المعاصي', 'أولئك هم المؤمنون حقا', 'فشدوا الوثاق'], correct: 0 },
        { title: 'معاذ الله', kind: 'mcq', prompt: 'مَعَاذَ اللَّهِ is:', options: ['سماعي', 'قياسي', 'مثال على استفهام التوبيخ', 'مثال على إما تفصيلا لمجمل'], correct: 0 },
        { title: 'منّا وفداء', kind: 'mcq', prompt: '﴿فَإِمَّا مَنًّا بَعْدُ وَإِمَّا فِدَاءً﴾ — منّا وفداء are:', options: ['مفعولان مطلقان بعاملين محذوفين قياسا, giving تفصيلا لمجمل', 'حالان منصوبان', 'مفعولان به', 'تمييزان'], correct: 0 },
        { title: 'الفرق العملي بين السماعي والقياسي', kind: 'mcq', prompt: 'Unlike السماعي, the قياسي deletion can be:', options: ['extended by rule to any new case matching its defined مواضع', 'only memorized, never extended', 'applied to الفاعل rather than المفعول المطلق', 'applied only within Qur’anic Arabic'], correct: 0 },
        { title: 'التمييز بين مواضع القياسي', kind: 'mcq', prompt: 'Which of these is NOT one of the four قياسي مواضع of عامل المفعول المطلق؟', options: ['التحذير', 'نهي بعد أمر', 'استفهام التوبيخ', 'إما تفصيلا لمجمل'], correct: 0 },
        {
          title: 'تركيب: سماعي أم قياسي؟',
          kind: 'tarkeeb',
          instruction: 'Classify each example: السماعي or القياسي؟',
          source: 'سبحان الله / صبرا لا جزعا / عجبا لك / أجرأة على المعاصي',
          words: ['سبحان الله', 'صبرا لا جزعا', 'عجبا لك', 'أجرأة على المعاصي'],
          labels: ['السماعي', 'القياسي', 'السماعي', 'القياسي'],
          distractors: ['الحذف الجائز'],
        },
        {
          title: 'تركيب: المواضع القياسية الأربعة',
          kind: 'tarkeeb',
          instruction: 'Match each مثال to the قياسي موضع it illustrates.',
          source: 'صبرا لا جزعا / أجرأة على المعاصي؟ / ﴿فإما منا وإما فداء﴾ / المؤمنون حقا',
          words: ['صبرا لا جزعا', 'أجرأة على المعاصي؟', 'فإما منا وإما فداء', 'المؤمنون حقا'],
          labels: ['نهي بعد أمر', 'استفهام توبيخ', 'إما تفصيلا لمجمل', 'مؤكد لمضمون الجملة'],
          distractors: ['تحذير'],
        },
      ],
    },
    // ---------------------------------------------------------------- L3
    {
      id: 'l3',
      title: 'التحذير والإغراء',
      subtitle: 'Warning and Urging — التحذير and الإغراء, their أركان, and how the عامل is dropped',
      concepts: [
        {
          heading: 'التحذير: تعريفه وأركانه',
          body: `<bdi>التَّحْذِير</bdi> is the نصب of a noun by a deleted verb conveying a warning against something disliked, so that the addressee avoids it. It has four <bdi>أَرْكَان</bdi>: (1) the implied verb of warning — <bdi>اِحْذَرْ، بَاعِدْ، تَجَنَّبْ، قِ، تَوَقَّ</bdi> or similar (2) <bdi>الْمُحَذِّر</bdi> — the warner, the speaker (3) <bdi>الْمُحَذَّر</bdi> — the one warned, the addressee (4) <bdi>الْمُحَذَّرُ مِنْهُ</bdi> — the thing warned against.`,
          sample: `تعريف التحذير — نصب اسم بفعل محذوف فيه تحذير من مكروه ليتجنبه المخاطب<br>أركانه الأربعة — الفعل المحذوف (احذر...)، المحذِّر، المحذَّر، المحذَّر منه`,
          exercise: {
            prompt: `Define التحذير and name its four أركان.`,
            kind: 'mcq',
            options: ['The نصب of a noun by a deleted verb conveying تحذير; its أركان are the implied verb, المحذِّر, المحذَّر, and المحذَّر منه', 'The رفع of a noun by a stated verb conveying ترغيب; its أركان are المغري, المغرَى, and المغرَى به only', 'The جر of a noun by a deleted حرف جر', 'The نصب of a noun by a stated, non-deleted governing حرف'],
            correct: 0,
          },
        },
        {
          heading: 'وجوه التحذير: بالضمير المنفصل إياك',
          body: `التحذير has three <bdi>وُجُوه</bdi> (forms). One mentions المحذَّر with the detached منصوب pronoun <bdi>إِيَّاكَ</bdi>, in three ways: with عطف of المحذَّر منه, as in <bdi>إِيَّاكَ وَالْحَسَدَ</bdi>; without عطف, repeating the pronoun, as in <bdi>إِيَّاكَ إِيَّاكَ الْمِرَاءَ</bdi>; or with جر by <bdi>مِنْ</bdi>, overt as in <bdi>إِيَّاكَ مِنَ الْحَسَدِ</bdi> or implied as in <bdi>إِيَّاكَ أَنْ تَحْسُدَ</bdi>.`,
          sample: `الوجه الأول — إياك (ضمير منفصل منصوب)<br>بالعطف — إياك والحسد<br>بالتكرار دون عطف — إياك إياك المراء<br>بالجر بمن — إياك من الحسد / إياك أن تحسد`,
          exercise: {
            prompt: `Parse إِيَّاكَ وَالْحَسَدَ.`,
            kind: 'mcq',
            options: ['إياك: المحذَّر, a detached pronoun منصوب by an obligatorily-deleted verb; والحسد: المحذَّر منه معطوف عليه', 'إياك: المحذِّر, the speaker; والحسد: the implied verb', 'إياك: مبتدأ; والحسد: خبره', 'إياك: فاعل a stated verb; والحسد: مفعول به ثانٍ'],
            correct: 0,
          },
        },
        {
          heading: 'وجوه التحذير: بالاسم الظاهر، وبذكر المحذَّر منه وحده',
          body: `The second وجه mentions المحذَّر with an overt noun (<bdi>اسْمٌ ظَاهِر</bdi>): alone, as in <bdi>نَفْسَكَ</bdi>; repeated, as in <bdi>نَفْسَكَ نَفْسَكَ</bdi>; or with المحذَّر منه conjoined, as in <bdi>نَفْسَكَ وَالْحَسَدَ</bdi>. The third وجه mentions only المحذَّر منه, either repeated — <bdi>اللَّهَ اللَّهَ</bdi> — or with a second item conjoined, as in <bdi>﴿نَاقَةَ اللَّهِ وَسُقْيَاهَا﴾</bdi>. التحذير can also occur without deleting the verb of warning at all: <bdi>﴿قُوا أَنْفُسَكُمْ وَأَهْلِيكُمْ نَارًا﴾</bdi> states قوا outright.`,
          sample: `الوجه الثاني (اسم ظاهر) — وحده: نفسَك؛ مكررا: نفسَك نفسَك؛ معطوفا عليه المحذر منه: نفسَك والحسد<br>الوجه الثالث (المحذر منه وحده) — مكررا: اللهَ اللهَ؛ بمعطوف: ﴿ناقة الله وسقياها﴾<br>بلا حذف الفعل — ﴿قوا أنفسكم وأهليكم نارا﴾`,
          exercise: {
            prompt: `Can التحذير occur without deletion of the verb of warning? Give the Qur’anic example.`,
            kind: 'mcq',
            options: ['Yes: ﴿قُوا أَنْفُسَكُمْ وَأَهْلِيكُمْ نَارًا﴾, where قوا is stated outright', 'No, deletion of the verb is always obligatory in التحذير', 'Only in poetry, never in the Qur’an', 'Only when المحذَّر منه is repeated'],
            correct: 0,
          },
        },
        {
          heading: 'الإغراء: تعريفه وأركانه',
          body: `<bdi>الْإِغْرَاء</bdi> is the نصب of a noun by a deleted verb conveying encouragement and enticement (<bdi>التَّرْغِيبُ وَالتَّشْوِيق</bdi>) toward something desirable, so that the addressee does it. Its four أركان: (1) the implied verb of urging — <bdi>الْزَمْ، اطْلُبْ، خُذْ، افْعَلْ</bdi> or similar (2) <bdi>الْمُغْرِي</bdi> — the urger, the speaker (3) <bdi>الْمُغْرَى</bdi> — the one urged, the addressee (4) <bdi>الْمُغْرَى بِهِ</bdi> — the thing urged toward.`,
          sample: `تعريف الإغراء — نصب اسم بفعل محذوف فيه ترغيب وتشويق ليفعله المخاطب<br>أركانه الأربعة — الفعل المحذوف (الزم...)، المغري، المغرَى، المغرَى به`,
          exercise: {
            prompt: `Define الإغراء and name its four أركان.`,
            kind: 'mcq',
            options: ['The نصب of a noun by a deleted verb conveying ترغيب وتشويق; its أركان are the implied verb, المغري, المغرَى, and المغرَى به', 'The نصب of a noun by a deleted verb conveying تحذير من مكروه', 'The رفع of a noun by a stated verb', 'The جر of a noun by a deleted حرف جر'],
            correct: 0,
          },
        },
        {
          heading: 'مواضع وجوب الحذف في الإغراء، وعدم الحذف',
          body: `Deletion of the عامل is obligatory in الإغراء in two cases: when المغرى به is repeated, as in <bdi>الصَّبْرَ الصَّبْرَ</bdi>, or when something is conjoined to it, as in <bdi>الْعِلْمَ وَالْحِلْمَ</bdi>. Like التحذير, الإغراء can also occur without deleting the verb: <bdi>﴿يَا يَحْيَىٰ خُذِ الْكِتَابَ بِقُوَّةٍ﴾</bdi> states خذ.`,
          sample: `وجوب الحذف في الإغراء — بتكرار المغرى به: الصبرَ الصبرَ؛ أو بعطف عليه: العلمَ والحلمَ<br>بلا حذف الفعل — ﴿يا يحيى خذ الكتاب بقوة﴾`,
          exercise: {
            prompt: `When is deletion of the عامل obligatory in الإغراء؟`,
            kind: 'mcq',
            options: ['When المغرى به is repeated, or when something is conjoined to it', 'Only when the verb is a فعل أمر', 'Only in Qur’anic examples', 'Deletion is never obligatory in الإغراء'],
            correct: 0,
          },
        },
        {
          heading: 'الملحقات بالتحذير والإغراء',
          body: `Two expressions are attached (<bdi>يُلْحَقُ</bdi>) to التحذير والإغراء with their own implied verbs: <bdi>مَرْحَبًا</bdi> and <bdi>أَهْلًا وَسَهْلًا</bdi> — with the implied verb <bdi>أَصَبْتَ</bdi> — and <bdi>امْرَأً وَنَفْسَهُ</bdi> — with the implied verb <bdi>دَعْ</bdi>.`,
          sample: `الملحقات — مرحبا، أهلا وسهلا (والفعل المقدر: أصبتَ)<br>امرأً ونفسه (والفعل المقدر: دعْ)`,
          exercise: {
            prompt: `مَرْحَبًا and أَهْلًا وَسَهْلًا are attached to التحذير والإغراء with which implied verb؟`,
            kind: 'mcq',
            options: ['أصبتَ', 'احذر', 'الزم', 'دعْ'],
            correct: 0,
          },
        },
      ],
      quiz: [
        { q: 'التحذير is defined as:', options: ['The نصب of a noun by a deleted verb conveying a warning against something disliked, so the addressee avoids it', 'The رفع of a noun by a stated verb conveying ترغيب', 'The جر of a noun by a deleted حرف جر', 'The نصب of a noun by a stated governing حرف'], correct: 0 },
        { q: 'إِيَّاكَ وَالْحَسَدَ shows المحذَّر expressed with:', options: ['a detached pronoun (إياك), معطوفا عليه المحذر منه', 'an overt noun repeated', 'only the المحذَّر منه, without إياك', 'a stated verb, without any حذف'], correct: 0 },
        { q: '﴿قُوا أَنْفُسَكُمْ وَأَهْلِيكُمْ نَارًا﴾ shows that التحذير:', options: ['can occur without deleting the verb of warning', 'always requires deletion of the verb', 'is only ever expressed by إياك', 'never takes a stated فعل'], correct: 0 },
        { q: 'الإغراء is defined as:', options: ['The نصب of a noun by a deleted verb conveying encouragement and enticement toward something desirable', 'The نصب of a noun by a deleted verb conveying a warning against something disliked', 'The جر of a noun by a governing حرف', 'The رفع of a noun by a stated verb'], correct: 0 },
        { q: 'الصَّبْرَ الصَّبْرَ illustrates obligatory deletion in الإغراء because:', options: ['المغرى به is repeated', 'a حرف جر precedes it', 'it is a Qur’anic example', 'the verb خُذْ is stated'], correct: 0 },
        { q: 'مَرْحَبًا and أَهْلًا وَسَهْلًا are ملحقات attached with the implied verb:', options: ['أصبتَ', 'احذر', 'الزم', 'دعْ'], correct: 0 },
      ],
      bank: [
        { title: 'أركان التحذير الأربعة', kind: 'mcq', prompt: 'List the four أركان of التحذير.', options: ['الفعل المحذوف, المحذِّر, المحذَّر, المحذَّر منه', 'الفعل المذكور, المغري, المغرَى, المغرَى به', 'الفعل المحذوف, الفاعل, المفعول به, الحال', 'المحذِّر, المحذَّر, الفاعل, النائب عن الفاعل'], correct: 0 },
        { title: 'وجوه التحذير الثلاثة', kind: 'mcq', prompt: 'How many وجوه does التحذير have, and what are they؟', options: ['Three: بالضمير المنفصل, بالاسم الظاهر, وبذكر المحذر منه وحده', 'Two: بالضمير فقط وبالاسم الظاهر فقط', 'Four, matching its four أركان', 'One only: بالضمير المنفصل إياك'], correct: 0 },
        { title: 'التكرار دون عطف', kind: 'mcq', prompt: 'إِيَّاكَ إِيَّاكَ الْمِرَاءَ illustrates التحذير expressed by:', options: ['repeating إياك without عطف', 'عطف المحذر منه على إياك', 'جر المحذر منه بمن', 'ذكر المحذر منه وحده'], correct: 0 },
        { title: 'إياك من الحسد', kind: 'mcq', prompt: 'إِيَّاكَ مِنَ الْحَسَدِ illustrates التحذير by إياك expressed with:', options: ['جر المحذر منه بمن (ظاهرة)', 'عطف المحذر منه على إياك', 'تكرار إياك دون عطف', 'ذكر المحذر منه وحده'], correct: 0 },
        { title: 'نفسَك نفسَك', kind: 'mcq', prompt: 'نَفْسَكَ نَفْسَكَ illustrates التحذير expressed by:', options: ['اسم ظاهر مكرر', 'ضمير منفصل معطوف عليه', 'ذكر المحذر منه فقط', 'فعل مذكور غير محذوف'], correct: 0 },
        { title: 'اللهَ اللهَ', kind: 'mcq', prompt: 'اللَّهَ اللَّهَ illustrates التحذير expressed by:', options: ['ذكر المحذَّر منه وحده, مكررا', 'ضمير منفصل إياك', 'اسم ظاهر معطوف عليه المحذر منه', 'فعل مذكور غير محذوف'], correct: 0 },
        { title: 'ناقة الله وسقياها', kind: 'mcq', prompt: '﴿نَاقَةَ اللَّهِ وَسُقْيَاهَا﴾ illustrates التحذير by mentioning المحذَّر منه:', options: ['with a second item conjoined to it', 'repeated with no عطف', 'preceded by إياك', 'preceded by a stated verb of warning'], correct: 0 },
        { title: 'أركان الإغراء الأربعة', kind: 'mcq', prompt: 'List the four أركان of الإغراء.', options: ['الفعل المحذوف, المغري, المغرَى, المغرَى به', 'الفعل المحذوف, المحذِّر, المحذَّر, المحذَّر منه', 'الفاعل, المفعول به, الحال, التمييز', 'المغري, المغرَى, الفاعل, النائب عن الفاعل'], correct: 0 },
        { title: 'العلمَ والحلمَ', kind: 'mcq', prompt: 'الْعِلْمَ وَالْحِلْمَ illustrates obligatory deletion in الإغراء because:', options: ['something is conjoined to المغرى به', 'المغرى به is repeated', 'the verb الزم is stated outright', 'a حرف جر precedes المغرى به'], correct: 0 },
        { title: 'الإغراء بلا حذف', kind: 'mcq', prompt: '﴿يَا يَحْيَىٰ خُذِ الْكِتَابَ بِقُوَّةٍ﴾ shows that الإغراء:', options: ['can occur with the verb خذ stated, not deleted', 'always requires the verb to be deleted', 'is only ever expressed by تكرار المغرى به', 'never occurs in Qur’anic Arabic'], correct: 0 },
        { title: 'ملحق امرأ ونفسه', kind: 'mcq', prompt: 'امْرَأً وَنَفْسَهُ is a ملحق attached with the implied verb:', options: ['دعْ', 'أصبتَ', 'احذر', 'الزم'], correct: 0 },
        {
          title: 'تركيب: أركان التحذير',
          kind: 'tarkeeb',
          instruction: 'Match each term to its role among أركان التحذير.',
          source: 'إياك (في إياك والحسد) / والحسد (في إياك والحسد) / احذر (المقدر)',
          words: ['إياك', 'والحسد', 'احذر (المقدر)'],
          labels: ['المحذَّر', 'المحذَّر منه', 'الفعل المحذوف'],
          distractors: ['المحذِّر'],
        },
        {
          title: 'تركيب: أركان الإغراء',
          kind: 'tarkeeb',
          instruction: 'Match each term to its role among أركان الإغراء.',
          source: 'الصبرَ (في الصبرَ الصبرَ) / الزم (المقدر) / المخاطب',
          words: ['الصبرَ', 'الزم (المقدر)', 'المخاطب'],
          labels: ['المغرَى به', 'الفعل المحذوف', 'المغرَى'],
          distractors: ['المغري'],
        },
        {
          title: 'تركيب: تحذير أم إغراء؟',
          kind: 'tarkeeb',
          instruction: 'Classify each example: التحذير (warning against) or الإغراء (urging toward)؟',
          source: 'إياك والحسد / الصبر الصبر / اللهَ اللهَ / العلمَ والحلمَ',
          words: ['إياك والحسد', 'الصبر الصبر', 'اللهَ اللهَ', 'العلمَ والحلمَ'],
          labels: ['التحذير', 'الإغراء', 'التحذير', 'الإغراء'],
          distractors: ['الاختصاص'],
        },
        {
          title: 'تركيب: وجوه التحذير الثلاثة',
          kind: 'tarkeeb',
          instruction: 'Match each مثال to the وجه of التحذير it illustrates.',
          source: 'إياك والحسد / نفسَك نفسَك / اللهَ اللهَ',
          words: ['إياك والحسد', 'نفسَك نفسَك', 'اللهَ اللهَ'],
          labels: ['بالضمير المنفصل', 'بالاسم الظاهر', 'بذكر المحذر منه وحده'],
          distractors: ['بفعل مذكور'],
        },
      ],
    },
    // ---------------------------------------------------------------- L4
    {
      id: 'l4',
      title: 'الاختصاص والاشتغال',
      subtitle: 'Specification and Preoccupation — الاختصاص and الاشتغال, and how المشغول عنه is declined',
      concepts: [
        {
          heading: 'الاختصاص: تعريفه ومثاله',
          body: `<bdi>الِاخْتِصَاص</bdi> is the نصب of a noun by a deleted verb — such as <bdi>أَخُصُّ</bdi> or <bdi>أَعْنِي</bdi> — which specifies the intended referent of a pronoun mentioned before it. In <bdi>﴿رَحْمَتُ اللَّهِ وَبَرَكَاتُهُ عَلَيْكُمْ أَهْلَ الْبَيْتِ﴾</bdi>, <bdi>أَهْلَ الْبَيْتِ</bdi> is منصوب by an implied أخص/أعني, specifying who كُمْ refers to.`,
          sample: `تعريف الاختصاص — نصب اسم بفعل محذوف (أخص/أعني) يخصص المقصود بضمير قبله<br>مثال — ﴿رحمت الله وبركاته عليكم أهل البيت﴾، أهل البيت منصوبة بأخص/أعني مقدرة`,
          exercise: {
            prompt: `Define الاختصاص and explain what أَهْلَ الْبَيْتِ does in ﴿رَحْمَتُ اللَّهِ وَبَرَكَاتُهُ عَلَيْكُمْ أَهْلَ الْبَيْتِ﴾.`,
            kind: 'mcq',
            options: ['The نصب of a noun by a deleted verb (أخص/أعني) specifying the referent of a preceding ضمير — here, specifying كُمْ', 'The رفع of a noun by a deleted verb specifying the فاعل', 'The جر of a noun by a deleted حرف جر', 'The نصب of a noun by a stated, non-deleted verb like أعني'],
            correct: 0,
          },
        },
        {
          heading: 'الاختصاص بأيها وأيتها',
          body: `الاختصاص can also be expressed with <bdi>أَيُّهَا</bdi>/<bdi>أَيَّتُهَا</bdi> without <bdi>يَا</bdi>, following the same rules as <bdi>النِّدَاء</bdi>. Example: <bdi>«وَنَهَى رَسُولُ اللَّهِ ﷺ الْمُسْلِمِينَ عَنْ كَلَامِنَا أَيُّهَا الثَّلَاثَةُ»</bdi>.`,
          sample: `الاختصاص بأيها/أيتها — بلا يا، على قواعد النداء: «...عن كلامنا أيها الثلاثة»`,
          exercise: {
            prompt: `Can الاختصاص be expressed with أَيُّهَا and أَيَّتُهَا? What rules apply؟`,
            kind: 'mcq',
            options: ['Yes, without يا, and it follows the rules of النداء', 'No, أيها/أيتها are exclusive to النداء', 'Yes, but only when preceded by يا', 'Yes, but it follows the rules of الاشتغال instead'],
            correct: 0,
          },
        },
        {
          heading: 'الاشتغال: تعريفه وأركانه',
          body: `<bdi>الِاشْتِغَال</bdi> is when a noun precedes a verb which governs a pronoun referring back to that noun, such that if the verb were freed from governing that pronoun, it would place the fronted noun in نصب — as in <bdi>﴿وَرُسُلًا قَدْ قَصَصْنَاهُمْ عَلَيْكَ﴾</bdi>. Its three أركان: (1) <bdi>الْمَشْغُول</bdi> — the عامل itself, also called <bdi>الْمُشْتَغِل</bdi> (2) <bdi>الْمَشْغُولُ بِهِ</bdi> — the pronoun referring back to the fronted noun (3) <bdi>الْمَشْغُولُ عَنْهُ</bdi> — the fronted noun itself.`,
          sample: `تعريف الاشتغال — اسم يتقدم فعلا يعمل في ضمير يعود عليه, بحيث لو تخلى الفعل عن ضميره لنصب الاسم المتقدم: ﴿ورسلا قد قصصناهم عليك﴾<br>أركانه الثلاثة — المشغول (العامل)، المشغول به (الضمير)، المشغول عنه (الاسم المتقدم)`,
          exercise: {
            prompt: `Define الاشتغال and name its three أركان.`,
            kind: 'mcq',
            options: ['A fronted noun preceding a verb that governs a pronoun referring back to it; its أركان are المشغول, المشغول به, and المشغول عنه', 'A fronted verb preceding a noun; its أركان are الفاعل والمفعول به فقط', 'A pronoun preceding its own antecedent noun', 'A noun preceded by a deleted فعل, with no pronoun involved'],
            correct: 0,
          },
        },
        {
          heading: 'الاسم الوصفي للاشتغال، وإعراب المشغول عنه',
          body: `الاشتغال’s traditional descriptive name is <bdi>مَا أُضْمِرَ عَامِلُهُ عَلَىٰ شَرِيطَةِ التَّفْسِير</bdi> — "that whose governor is concealed on condition of interpretation." المشغول عنه generally has two possible إعراب options: <bdi>رَفْع</bdi> (as مبتدأ) or <bdi>نَصْب</bdi> (by a deleted verb), as in <bdi>﴿وَالْمَوْتَىٰ يَبْعَثُهُمُ اللَّهُ﴾</bdi>, which allows either reading.`,
          sample: `الاسم الوصفي للاشتغال — ما أضمر عامله على شريطة التفسير<br>إعراب المشغول عنه عموما — رفع (مبتدأ) أو نصب (بفعل محذوف): ﴿والموتى يبعثهم الله﴾`,
          exercise: {
            prompt: `What two إعراب options exist in general for المشغول عنه? Give the Qur’anic example.`,
            kind: 'mcq',
            options: ['رفع (as مبتدأ) or نصب (by a deleted verb): ﴿وَالْمَوْتَىٰ يَبْعَثُهُمُ اللَّهُ﴾', 'جر only, never رفع or نصب', 'رفع only, never نصب', 'نصب only, never رفع'],
            correct: 0,
          },
        },
        {
          heading: 'وجوب الرفع أو النصب في المشغول عنه',
          body: `رفع of المشغول عنه is obligatory when it falls after a particle specific to nouns, such as <bdi>إِذَا الْفُجَائِيَّة</bdi>: <bdi>خَلَقَ اللَّهُ الْإِنْسَانَ وَأَنْعَمَ عَلَيْهِ فَإِذَا الشَّيْطَانُ يَتْبَعُهُ</bdi>. نصب is obligatory when it falls after a particle specific to verbs, such as <bdi>التَّحْضِيض</bdi> — <bdi>هَلَّا الْجَنَّةَ طَلَبْتَهَا</bdi> — or <bdi>الشَّرْط</bdi> — <bdi>إِنِ الْجَنَّةَ تُرِدْهَا فَاعْمَلْ صَالِحًا</bdi>.`,
          sample: `وجوب الرفع — بعد حرف يختص بالأسماء (إذا الفجائية): فإذا الشيطانُ يتبعه<br>وجوب النصب — بعد حرف يختص بالأفعال (التحضيض، الشرط): هلا الجنةَ طلبتَها؛ إن الجنةَ تردْها فاعمل صالحا`,
          exercise: {
            prompt: `When is رفع of المشغول عنه obligatory, and when is نصب obligatory؟`,
            kind: 'mcq',
            options: ['رفع is obligatory after a particle specific to nouns (إذا الفجائية); نصب is obligatory after a particle specific to verbs (التحضيض, الشرط)', 'رفع is always obligatory, نصب is never used', 'نصب is always obligatory, رفع is never used', 'Both are obligatory simultaneously in every case'],
            correct: 0,
          },
        },
        {
          heading: 'ترجيح النصب، والفعل المرادف',
          body: `نصب of المشغول عنه is preferred (<bdi>يُتَرَجَّح</bdi>) in three cases: (1) the عامل is a verb of <bdi>طَلَب</bdi>, as in <bdi>اللَّهَ اعْبُدْهُ وَرَسُولَهُ اتَّبِعْهُ</bdi> (2) a جملة فعلية precedes the معمول, as in <bdi>أَعْبُدُ اللَّهَ وَرَسُولَهُ أَتَّبِعُهُ</bdi> (3) a particle that mostly precedes verbs comes first, e.g. <bdi>مَا النَّافِيَة</bdi> or <bdi>هَمْزَةُ الِاسْتِفْهَام</bdi>: <bdi>﴿أَبَشَرًا مِنَّا وَاحِدًا نَتَّبِعُهُ﴾</bdi>. The deleted verb in الاشتغال need not be the same word as the stated one — it may be a <bdi>مُرَادِف</bdi> (synonym), as in <bdi>﴿وَالظَّالِمِينَ أَعَدَّ لَهُمْ عَذَابًا أَلِيمًا﴾</bdi>, where the implied verb is like <bdi>أَوْعَدَ</bdi>.`,
          sample: `النصب مترجَّح — عامل طلب: اللهَ اعبدْه ورسولَه اتبعْه؛ جملة فعلية سابقة: أعبد الله ورسولَه أتبعه؛ حرف غالبا يسبق الأفعال: ﴿أبشرا منا واحدا نتبعه﴾<br>الفعل المحذوف قد يكون مرادفا — ﴿والظالمين أعد لهم عذابا أليما﴾ (أوعد مقدرة)`,
          exercise: {
            prompt: `Can the deleted verb in الاشتغال be a synonym rather than the exact stated verb? Give the example.`,
            kind: 'mcq',
            options: ['Yes — a verb مرادف to the stated عامل: ﴿وَالظَّالِمِينَ أَعَدَّ لَهُمْ عَذَابًا أَلِيمًا﴾, implying أوعد', 'No, the deleted verb must always be identical to the stated one', 'Only when the stated verb is a فعل أمر', 'Only in the three cases where نصب is obligatory'],
            correct: 0,
          },
        },
      ],
      quiz: [
        { q: 'الاختصاص is defined as:', options: ['The نصب of a noun by a deleted verb (أخص/أعني) specifying the intended referent of a preceding ضمير', 'The رفع of a noun by a deleted verb specifying the فاعل', 'The جر of a noun by a deleted حرف جر', 'The نصب of a noun by a stated verb, always'], correct: 0 },
        { q: 'الاختصاص can be expressed with أيها/أيتها:', options: ['without يا, following the rules of النداء', 'only with يا preceding them', 'only inside الاشتغال', 'never — أيها/أيتها belong only to النداء'], correct: 0 },
        { q: 'الاشتغال’s three أركان are:', options: ['المشغول, المشغول به, المشغول عنه', 'المغري, المغرَى, المغرَى به', 'المحذِّر, المحذَّر, المحذَّر منه', 'الفاعل, المفعول به, الحال'], correct: 0 },
        { q: 'The descriptive name of الاشتغال is:', options: ['ما أضمر عامله على شريطة التفسير', 'ما دل على معنى في نفسه مقترن بزمن', 'كل لفظ دل على معنى مفرد', 'ما نصب المفعول به بفعل محذوف دائما'], correct: 0 },
        { q: 'رفع of المشغول عنه is obligatory when it falls after:', options: ['a particle specific to nouns, such as إذا الفجائية', 'a particle specific to verbs, such as الشرط', 'any حرف جر at all', 'a فعل أمر specifically'], correct: 0 },
        { q: 'نصب of المشغول عنه is preferred (يترجح) when:', options: ['the عامل is a verb of طلب', 'the عامل is a اسم فاعل', 'المشغول عنه is مبني', 'no جملة فعلية precedes it'], correct: 0 },
      ],
      bank: [
        { title: 'الفعل المقدر في الاختصاص', kind: 'mcq', prompt: 'The deleted verb in الاختصاص is typically:', options: ['أخص or أعني', 'احذر or باعد', 'اعبدْ or اتبعْ', 'أدعو'], correct: 0 },
        { title: 'أهل البيت في مثال الاختصاص', kind: 'mcq', prompt: 'In ﴿رَحْمَتُ اللَّهِ وَبَرَكَاتُهُ عَلَيْكُمْ أَهْلَ الْبَيْتِ﴾, أهل البيت specifies the referent of:', options: ['the ضمير كُمْ', 'the ضمير هُ in بركاته', 'the اسم الله', 'nothing — it specifies no ضمير at all'], correct: 0 },
        { title: 'أيها الثلاثة', kind: 'mcq', prompt: '«...عَنْ كَلَامِنَا أَيُّهَا الثَّلَاثَةُ» illustrates الاختصاص expressed:', options: ['with أيها, following rules of النداء, without يا', 'with أخص stated outright', 'with أعني stated outright', 'with a حرف جر, not a فعل محذوف'], correct: 0 },
        { title: 'المشغول والمشغول به', kind: 'mcq', prompt: 'In الاشتغال, المشغول به refers to:', options: ['the pronoun that refers back to the fronted noun', 'the fronted noun itself', 'the عامل / المشتغِل itself', 'a completely unrelated noun'], correct: 0 },
        { title: 'المشغول عنه', kind: 'mcq', prompt: 'In الاشتغال, المشغول عنه refers to:', options: ['the fronted noun itself', 'the pronoun referring back to it', 'the عامل / المشتغِل itself', 'a deleted verb with no fronted noun'], correct: 0 },
        { title: 'شريطة التفسير', kind: 'mcq', prompt: 'ما أضمر عامله على شريطة التفسير is the traditional descriptive name for:', options: ['الاشتغال', 'الاختصاص', 'التحذير', 'الإغراء'], correct: 0 },
        { title: 'رفع بعد إذا الفجائية', kind: 'mcq', prompt: 'خَلَقَ اللَّهُ الْإِنْسَانَ وَأَنْعَمَ عَلَيْهِ فَإِذَا الشَّيْطَانُ يَتْبَعُهُ shows المشغول عنه obligatorily رفوع because it follows:', options: ['إذا الفجائية, a particle specific to nouns', 'التحضيض, a particle specific to verbs', 'الشرط, a particle specific to verbs', 'a حرف جر'], correct: 0 },
        { title: 'نصب بعد التحضيض', kind: 'mcq', prompt: 'هَلَّا الْجَنَّةَ طَلَبْتَهَا shows المشغول عنه obligatorily منصوب because it follows:', options: ['حرف تحضيض, specific to verbs', 'حرف اختصاص, specific to nouns', 'إذا الفجائية', 'ما النافية'], correct: 0 },
        { title: 'ترجيح النصب بعامل الطلب', kind: 'mcq', prompt: 'اللَّهَ اعْبُدْهُ وَرَسُولَهُ اتَّبِعْهُ shows نصب preferred because:', options: ['the عامل is a verb of طلب', 'a جملة اسمية precedes it', 'إذا الفجائية precedes it', 'a حرف جر governs it'], correct: 0 },
        { title: 'ترجيح النصب بجملة فعلية سابقة', kind: 'mcq', prompt: 'أَعْبُدُ اللَّهَ وَرَسُولَهُ أَتَّبِعُهُ shows نصب preferred because:', options: ['a جملة فعلية precedes the معمول', 'the عامل is a اسم فاعل', 'إذا الفجائية precedes it', 'the sentence has no ضمير at all'], correct: 0 },
        { title: 'الفعل المرادف في الاشتغال', kind: 'mcq', prompt: '﴿وَالظَّالِمِينَ أَعَدَّ لَهُمْ عَذَابًا أَلِيمًا﴾ shows the implied deleted verb as:', options: ['a مرادف (synonym) to the stated verb, like أوعد', 'the exact same word أعدّ, repeated', 'a فعل أمر', 'a فعل مضارع'], correct: 0 },
        {
          title: 'تركيب: أركان الاشتغال',
          kind: 'tarkeeb',
          instruction: 'Match each term to its role among أركان الاشتغال in ﴿ورسلا قد قصصناهم عليك﴾.',
          source: 'رسلا / هم (الضمير في قصصناهم) / قصصنا',
          words: ['رسلا', 'هم', 'قصصنا'],
          labels: ['المشغول عنه', 'المشغول به', 'المشغول'],
          distractors: ['المحذَّر منه'],
        },
        {
          title: 'تركيب: رفع أم نصب واجب؟',
          kind: 'tarkeeb',
          instruction: 'Classify the required إعراب of المشغول عنه after each kind of particle.',
          source: 'بعد إذا الفجائية / بعد حرف التحضيض / بعد حرف الشرط',
          words: ['إذا الفجائية', 'حرف التحضيض', 'حرف الشرط'],
          labels: ['رفع واجب', 'نصب واجب', 'نصب واجب'],
          distractors: ['جر واجب'],
        },
        {
          title: 'تركيب: اختصاص أم اشتغال؟',
          kind: 'tarkeeb',
          instruction: 'Classify each example: الاختصاص or الاشتغال؟',
          source: '﴿رحمت الله وبركاته عليكم أهل البيت﴾ / ﴿ورسلا قد قصصناهم عليك﴾',
          words: ['أهل البيت', 'ورسلا قد قصصناهم'],
          labels: ['الاختصاص', 'الاشتغال'],
          distractors: ['التحذير'],
        },
      ],
    },
    // ---------------------------------------------------------------- L5
    {
      id: 'l5',
      title: 'النداء: أركانه وحروفه وإعرابه',
      subtitle: 'The Vocative — النداء’s أركان, its seven particles, when they’re deleted, and how المنادى is declined',
      concepts: [
        {
          heading: 'تعريف النداء وأركانه',
          body: `<bdi>النِّدَاء</bdi> is calling out with a particle that stands in the place of the verb <bdi>أَدْعُو</bdi>, as in <bdi>يَا زَيْدُ</bdi>. Its three أركان: (1) the deleted verb of calling — <bdi>أَدْعُو</bdi> or similar (2) the particle of النداء standing in its place, e.g. <bdi>يَا</bdi> (3) <bdi>الْمُنَادَى</bdi> — the one called, e.g. <bdi>زَيْد</bdi>.`,
          sample: `تعريف النداء — دعوة بحرف ينوب عن الفعل أدعو: يا زيد<br>أركانه الثلاثة — الفعل المحذوف (أدعو)، حرف النداء (يا)، المنادى (زيد)`,
          exercise: {
            prompt: `Define النداء and name its three أركان.`,
            kind: 'mcq',
            options: ['Calling out with a particle standing in for أدعو; its أركان are the deleted verb, the particle, and المنادى', 'Calling out with a stated verb only, never a particle', 'A form of التحذير expressed with يا', 'A form of الاشتغال with a fronted noun'],
            correct: 0,
          },
        },
        {
          heading: 'حروف النداء السبعة',
          body: `The seven particles of النداء and their uses: <bdi>الْهَمْزَة</bdi> and <bdi>أَيْ</bdi> — for the near, as in <bdi>أَعَبْدَ اللَّهِ</bdi>, <bdi>أَيْ عَبْدَ اللَّهِ</bdi>; <bdi>يَا، آ، أَيَا، هَيَا</bdi> — for the far, as in <bdi>يَا عَبْدَ اللَّهِ</bdi>; and <bdi>وَا</bdi> — for <bdi>النَّدْبَة</bdi> (lament/grief).`,
          sample: `للقريب — الهمزة، أي: أعبد الله، أي عبد الله<br>للبعيد — يا، آ، أيا، هيا: يا عبد الله<br>للندبة — وا`,
          exercise: {
            prompt: `List the seven particles of النداء and what each group is used for.`,
            kind: 'mcq',
            options: ['الهمزة وأي (للقريب), يا وآ وأيا وهيا (للبعيد), وا (للندبة)', 'ما ولا وإنْ (نافية فقط)', 'الفاء والواو وثم (عاطفة فقط)', 'كي وأنْ وأنَّ (مصدرية فقط)'],
            correct: 0,
          },
        },
        {
          heading: 'حذف حرف النداء: متى يجوز ومتى يمتنع',
          body: `The particle of النداء may be deleted when المنادى is <bdi>مُضَاف</bdi>, as in <bdi>﴿اعْمَلُوا آلَ دَاوُودَ شُكْرًا﴾</bdi>, or a <bdi>عَلَم</bdi>, as in <bdi>﴿يُوسُفُ أَعْرِضْ عَنْ هَٰذَا﴾</bdi>. It may NOT be deleted with <bdi>لَفْظُ الْجَلَالَة</bdi> (الله) or with a <bdi>نَكِرَة مَقْصُودَة</bdi>, as in <bdi>يَا رَجُلُ</bdi>.`,
          sample: `يجوز حذف حرف النداء — مع المضاف: ﴿اعملوا آل داود شكرا﴾؛ ومع العلم: ﴿يوسف أعرض عن هذا﴾<br>يمتنع حذفه — مع لفظ الجلالة، ومع النكرة المقصودة: يا رجلُ`,
          exercise: {
            prompt: `With which منادى may the particle of النداء NOT be deleted؟`,
            kind: 'mcq',
            options: ['With لفظ الجلالة (الله) and with a نكرة مقصودة', 'With any مضاف منادى', 'With any علم منادى', 'The particle can always be deleted, with no exception'],
            correct: 0,
          },
        },
        {
          heading: 'إعراب المنادى: أصله، ومتى ينصب لفظا',
          body: `The underlying إعراب of المنادى is that of a مفعول به of the deleted أدعو — منصوب either <bdi>لَفْظًا</bdi> (overtly) or <bdi>مَحَلًّا</bdi> (in position). It is منصوب لفظا in three cases with examples: (1) <bdi>مُضَاف</bdi>: <bdi>يَا عَبْدَ اللَّهِ</bdi> (2) <bdi>شَبِيهٌ بِالْمُضَاف</bdi> — a noun governing what follows it: <bdi>يَا غَافِرًا ذُنُوبَنَا</bdi> (3) <bdi>غَيْرُ مُعَيَّن</bdi> (unspecified): <bdi>يَا غَافِلًا وَالْمَوْتُ يَطْلُبُهُ</bdi>.`,
          sample: `أصل إعراب المنادى — مفعول به للفعل المحذوف أدعو، منصوب لفظا أو محلا<br>ينصب لفظا في ثلاث — مضاف: يا عبد الله؛ شبيه بالمضاف: يا غافرا ذنوبَنا؛ غير معين: يا غافلا والموت يطلبه`,
          exercise: {
            prompt: `When is the منادى منصوب لفظا? Give the three cases.`,
            kind: 'mcq',
            options: ['مضاف, شبيه بالمضاف, and غير معين', 'مفرد معرفة, مفرد نكرة مقصودة, and مثنى فقط', 'Only ever when it is مضاف', 'Only ever when preceded by لفظ الجلالة'],
            correct: 0,
          },
        },
        {
          heading: 'المنادى المبني: متى ولماذا',
          body: `The <bdi>مُفْرَد</bdi> منادى (non-مضاف and non-شبيه بالمضاف) that is <bdi>مَعْرِفَة</bdi> or <bdi>نَكِرَة مَقْصُودَة</bdi> is <bdi>مَبْنِيّ</bdi> (منصوب محلا) — it is built on the sign it would take in رفع, as in <bdi>يَا زَيْدُ، يَا رَجُلُ، يَا رَجُلَانِ، يَا مُسْلِمُونَ</bdi>. That is why one says <bdi>يَا مُسْلِمُونَ</bdi> rather than <bdi>يَا مُسْلِمِينَ</bdi>: a مفرد definite منادى is built on its رفع sign — here الواو — even though it is منصوب محلا.`,
          sample: `المنادى المبني — المفرد المعرفة أو النكرة المقصودة: يا زيدُ، يا رجلُ، يا رجلان، يا مسلمون<br>لماذا يا مسلمون لا يا مسلمين؟ — لأنه يُبنى على علامة رفعه (الواو) وإن كان منصوبا محلا`,
          exercise: {
            prompt: `Why do we say يَا مُسْلِمُونَ and not يَا مُسْلِمِينَ؟`,
            kind: 'mcq',
            options: ['A مفرد definite منادى is built on the sign it takes in رفع — here الواو — though it is منصوب محلا', 'مسلمين is simply ungrammatical Arabic in any context', 'Because النداء always requires رفع, never نصب', 'Because مسلمون is مضاف here'],
            correct: 0,
          },
        },
        {
          heading: 'المنادى المضاف إلى ياء المتكلم',
          body: `Four forms are permitted for a منادى annexed to <bdi>يَاءُ الْمُتَكَلِّم</bdi>: (1) deleting the ياء, sufficing with the كسرة: <bdi>﴿يَا عِبَادِ فَاتَّقُونِ﴾</bdi> (2) retaining the ياء quiescent: <bdi>﴿يَا عِبَادِيَ لَا خَوْفٌ عَلَيْكُمُ الْيَوْمَ﴾</bdi> (3) retaining the ياء with فتحة: <bdi>﴿يَا عِبَادِيَ الَّذِينَ أَسْرَفُوا عَلَىٰ أَنْفُسِهِمْ﴾</bdi> (4) turning the كسرة into فتحة and the ياء into ألف: <bdi>﴿يَا حَسْرَتَىٰ﴾</bdi>.`,
          sample: `الصور الأربع للمنادى المضاف لياء المتكلم — حذف الياء والاكتفاء بالكسرة: ﴿يا عبادِ فاتقون﴾؛ إثبات الياء ساكنة: ﴿يا عباديْ لا خوف عليكم اليوم﴾؛ إثباتها مفتوحة: ﴿يا عباديَ الذين أسرفوا﴾؛ قلب الكسرة فتحة والياء ألفا: ﴿يا حسرتى﴾`,
          exercise: {
            prompt: `What are the four permitted forms for a منادى annexed to ياء المتكلم؟`,
            kind: 'mcq',
            options: ['Deleting the ياء (كسرة alone), retaining it ساكنة, retaining it بفتحة, or turning كسرة+ياء into فتحة+ألف', 'Only ever deleting the ياء, with no alternative', 'Only ever retaining the ياء ساكنة', 'Turning the ياء into واو in every case'],
            correct: 0,
          },
        },
      ],
      quiz: [
        { q: 'النداء is defined as:', options: ['Calling out with a particle standing in the place of the verb أدعو', 'Calling out with أدعو stated outright, never a particle', 'A نصب construction unrelated to any deleted فعل', 'A form exclusive to لفظ الجلالة'], correct: 0 },
        { q: 'الهمزة and أَيْ are used for:', options: ['النداء للقريب', 'النداء للبعيد', 'الندبة فقط', 'الاستغاثة فقط'], correct: 0 },
        { q: 'With which منادى may the particle of النداء NOT be deleted؟', options: ['لفظ الجلالة and النكرة المقصودة', 'Any مضاف منادى', 'Any علم منادى', 'It may always be deleted, without exception'], correct: 0 },
        { q: 'يَا غَافِرًا ذُنُوبَنَا shows المنادى منصوب لفظا because it is:', options: ['شبيه بالمضاف', 'مضاف', 'غير معين', 'معرفة مفردة'], correct: 0 },
        { q: 'A مفرد معرفة منادى (like زيد) is:', options: ['مبني, built on the sign of its رفع', 'منصوب لفظا always', 'مجرور always', 'مرفوع لفظا, not محلا'], correct: 0 },
        { q: '﴿يَا عِبَادِ فَاتَّقُونِ﴾ shows a منادى annexed to ياء المتكلم with:', options: ['the ياء deleted, sufficing with الكسرة', 'the ياء retained ساكنة', 'the ياء retained مفتوحة', 'the كسرة turned into فتحة and ياء into ألف'], correct: 0 },
      ],
      bank: [
        { title: 'أركان النداء الثلاثة', kind: 'mcq', prompt: 'List the three أركان of النداء.', options: ['الفعل المحذوف (أدعو), حرف النداء, المنادى', 'المحذِّر, المحذَّر, المحذَّر منه', 'المغري, المغرَى, المغرَى به', 'المشغول, المشغول به, المشغول عنه'], correct: 0 },
        { title: 'حروف البعيد', kind: 'mcq', prompt: 'يَا، آ، أَيَا، هَيَا are used for:', options: ['النداء للبعيد', 'النداء للقريب', 'الندبة فقط', 'الاستغاثة فقط'], correct: 0 },
        { title: 'حرف الندبة', kind: 'mcq', prompt: 'Which حرف نداء is used specifically for الندبة؟', options: ['وا', 'يا', 'الهمزة', 'أي'], correct: 0 },
        { title: 'حذف الحرف مع المضاف', kind: 'mcq', prompt: '﴿اعْمَلُوا آلَ دَاوُودَ شُكْرًا﴾ shows the particle of النداء deleted because المنادى is:', options: ['مضاف', 'نكرة مقصودة', 'لفظ الجلالة', 'شبيه بالمضاف'], correct: 0 },
        { title: 'حذف الحرف مع العلم', kind: 'mcq', prompt: '﴿يُوسُفُ أَعْرِضْ عَنْ هَٰذَا﴾ shows the particle of النداء deleted because المنادى is:', options: ['a علم', 'a نكرة مقصودة', 'لفظ الجلالة', 'مضاف'], correct: 0 },
        { title: 'أصل إعراب المنادى', kind: 'mcq', prompt: 'What is the underlying إعراب of المنادى؟', options: ['مفعول به of the deleted فعل أدعو', 'فاعل of the deleted فعل أدعو', 'مبتدأ with a deleted خبر', 'مضاف إليه of a deleted مضاف'], correct: 0 },
        { title: 'يا عبد الله: مضاف', kind: 'mcq', prompt: 'يَا عَبْدَ اللَّهِ shows المنادى منصوب لفظا because it is:', options: ['مضاف', 'شبيه بالمضاف', 'غير معين', 'مفرد معرفة'], correct: 0 },
        { title: 'يا غافلا: غير معين', kind: 'mcq', prompt: 'يَا غَافِلًا وَالْمَوْتُ يَطْلُبُهُ shows المنادى منصوب لفظا because it is:', options: ['غير معين', 'مضاف', 'شبيه بالمضاف', 'نكرة مقصودة'], correct: 0 },
        { title: 'يا رجلان: البناء', kind: 'mcq', prompt: 'يَا رَجُلَانِ shows a مبني منادى built on:', options: ['علامة رفعه (الألف)', 'الفتحة, like a normal منصوب', 'الكسرة, as if مجرور', 'السكون دائما'], correct: 0 },
        { title: 'الفرق بين المضاف وشبيه المضاف', kind: 'mcq', prompt: 'What distinguishes شبيه بالمضاف from مضاف in المنادى?', options: ['شبيه بالمضاف governs what follows it without being formally مضاف إليه to it', 'There is no real difference; they are the same category', 'شبيه بالمضاف is always مبني, unlike مضاف', 'مضاف never occurs with النداء at all'], correct: 0 },
        { title: 'يا عباديَ: إثبات الياء مفتوحة', kind: 'mcq', prompt: '﴿يَا عِبَادِيَ الَّذِينَ أَسْرَفُوا عَلَىٰ أَنْفُسِهِمْ﴾ shows ياء المتكلم:', options: ['retained with فتحة', 'deleted entirely', 'retained ساكنة', 'turned into ألف'], correct: 0 },
        { title: 'يا حسرتى: قلب الياء ألفا', kind: 'mcq', prompt: '﴿يَا حَسْرَتَىٰ﴾ shows which treatment of ياء المتكلم؟', options: ['كسرة turned into فتحة and ياء into ألف', 'الياء retained ساكنة', 'الياء deleted, كسرة alone kept', 'الياء retained مفتوحة without change'], correct: 0 },
        {
          title: 'تركيب: قريب أم بعيد؟',
          kind: 'tarkeeb',
          instruction: 'Classify each حرف نداء: للقريب or للبعيد؟',
          source: 'الهمزة / أي / يا / أيا',
          words: ['الهمزة', 'أي', 'يا', 'أيا'],
          labels: ['للقريب', 'للقريب', 'للبعيد', 'للبعيد'],
          distractors: ['للندبة'],
        },
        {
          title: 'تركيب: لفظا أم محلا؟',
          kind: 'tarkeeb',
          instruction: 'Classify the نصب of each منادى: لفظا or محلا؟',
          source: 'يا عبدَ الله (مضاف) / يا زيدُ (مفرد معرفة)',
          words: ['يا عبدَ الله', 'يا زيدُ'],
          labels: ['منصوب لفظا', 'منصوب محلا'],
          distractors: ['مجرور لفظا'],
        },
        {
          title: 'تركيب: صور المنادى المضاف لياء المتكلم',
          kind: 'tarkeeb',
          instruction: 'Match each مثال to the treatment of ياء المتكلم it shows.',
          source: '﴿يا عبادِ فاتقون﴾ / ﴿يا عباديَ الذين أسرفوا﴾ / ﴿يا حسرتى﴾',
          words: ['يا عبادِ فاتقون', 'يا عباديَ الذين أسرفوا', 'يا حسرتى'],
          labels: ['حذف الياء والاكتفاء بالكسرة', 'إثبات الياء مفتوحة', 'قلب الكسرة فتحة والياء ألفا'],
          distractors: ['إثبات الياء ساكنة'],
        },
      ],
    },
    // ---------------------------------------------------------------- L6
    {
      id: 'l6',
      title: 'الترخيم، الاستغاثة، الندبة، وحذف عامل الحال',
      subtitle: 'Truncation, Appeals, and Lament — الترخيم, الاستغاثة, نداء التعجب, الندبة, and deleting عامل الحال',
      concepts: [
        {
          heading: 'الترخيم: تعريفه وما يجوز ترخيمه',
          body: `<bdi>التَّرْخِيم</bdi> is deleting the end of المنادى for lightness (<bdi>التَّخْفِيف</bdi>), as in <bdi>يَا فَاطِمَ</bdi> (for <bdi>فَاطِمَة</bdi>). Only two kinds of nouns may undergo it: nouns ending in the <bdi>تَاء</bdi>, as in <bdi>يَا عَائِشَ</bdi>, and a masculine <bdi>عَلَم</bdi> of more than three letters that is not compound, as in <bdi>يَا جَعْفَ</bdi> (for <bdi>جَعْفَر</bdi>) — unlike <bdi>زَيْنَب، زَيْد، عَبْدُ اللَّه</bdi>.`,
          sample: `تعريف الترخيم — حذف آخر المنادى تخفيفا: يا فاطمَ (لفاطمة)<br>ما يجوز ترخيمه — المختوم بتاء: يا عائشَ؛ العلم المذكر فوق ثلاثة أحرف غير المركب: يا جعفَ (لجعفر)؛ لا يجوز مع زينب وزيد وعبد الله`,
          exercise: {
            prompt: `Which nouns may undergo الترخيم؟`,
            kind: 'mcq',
            options: ['Nouns ending in تاء, and a masculine علم of more than three letters that is not compound', 'Any منادى whatsoever, with no restriction', 'Only أسماء ending in ألف', 'Only compound أعلام like عبد الله'],
            correct: 0,
          },
        },
        {
          heading: 'الترخيم: الوزنان الجائزان في آخر المرخَّم',
          body: `Two vowelings are permitted on the end of the <bdi>مُرَخَّم</bdi> منادى: keeping the original vowel it had before truncation, as in <bdi>يَا حَارِ</bdi> (for <bdi>حَارِث</bdi>), or giving it the <bdi>ضَمَّة</bdi>, as in <bdi>يَا حَارُ</bdi>.`,
          sample: `الوزنان الجائزان في آخر المرخَّم — إبقاء الحركة الأصلية: يا حارِ (لحارث)؛ أو الضمة: يا حارُ`,
          exercise: {
            prompt: `What two vowelings are permitted on the end of the مرخَّم منادى؟`,
            kind: 'mcq',
            options: ['Keeping the original vowel, or giving it the ضمة', 'Only the فتحة, with no alternative', 'Only the كسرة, with no alternative', 'The سكون only, in every case'],
            correct: 0,
          },
        },
        {
          heading: 'اللهم ودلالتها',
          body: `<bdi>اللَّهُمَّ</bdi> is a vocative form (<bdi>صِيغَةُ نِدَاء</bdi>) for لفظ الجلالة. Before <bdi>إِلَّا</bdi>, it signals the rarity (<bdi>نُدْرَة</bdi>) of the مستثنى, as in <bdi>اللَّهُمَّ إِلَّا أَنْ يَكُونَ كَذَا</bdi>. Before <bdi>نَعَمْ</bdi>, it signals the responder’s certainty (<bdi>تَيَقُّن</bdi>) of the answer, as in <bdi>اللَّهُمَّ نَعَمْ</bdi>.`,
          sample: `اللهم — صيغة نداء للفظ الجلالة<br>قبل إلا — ندرة المستثنى: اللهم إلا أن يكون كذا<br>قبل نعم — تيقن المجيب: اللهم نعم`,
          exercise: {
            prompt: `What does اللَّهُمَّ signify before إِلَّا, and what does it signify before نَعَمْ؟`,
            kind: 'mcq',
            options: ['Before إلا, the rarity (ندرة) of the مستثنى; before نعم, the responder’s certainty (تيقن)', 'Before إلا, certainty; before نعم, rarity', 'It signifies exactly the same thing in both positions', 'It has no distinct meaning in either position'],
            correct: 0,
          },
        },
        {
          heading: 'الاستغاثة: تعريفها وأركانها',
          body: `<bdi>الِاسْتِغَاثَة</bdi> is a type of نداء: the caller calls a منادى to come to the aid of another. Its three أركان: (1) the particle of الاستغاثة — which is <bdi>يَا</bdi> only (2) <bdi>الْمُسْتَغَاث</bdi> — the one called for help, i.e. المنادى (3) <bdi>الْمُسْتَغَاثُ لَهُ</bdi> / <bdi>لِأَجْلِهِ</bdi> — the one for whose sake help is sought.`,
          sample: `تعريف الاستغاثة — نداء يُدعى فيه المنادى ليغيث آخر<br>أركانها الثلاثة — حرف الاستغاثة (يا فقط)، المستغاث، المستغاث له/لأجله`,
          exercise: {
            prompt: `Define الاستغاثة and name its three أركان.`,
            kind: 'mcq',
            options: ['A نداء calling المستغاث to come to another’s aid; its أركان are حرف الاستغاثة (يا), المستغاث, and المستغاث له', 'A نداء expressing grief with no أركان of its own', 'A form of التحذير calling for help', 'A form of الترخيم shortening المستغاث'],
            correct: 0,
          },
        },
        {
          heading: 'أحكام اللام في الاستغاثة',
          body: `A <bdi>لَام جَارَّة</bdi> with <bdi>فَتْحَة</bdi> attaches to المستغاث, as in <bdi>يَا لَلَّهِ</bdi>; an <bdi>أَلِف</bdi> may substitute for it at the end, as in <bdi>يَا زَيْدَا، يَا زَيْدَاهْ</bdi>. When a second مستغاث is conjoined without repeating يا, its لام takes <bdi>كَسْرَة</bdi>, as in <bdi>يَا لَلْأَمِيرِ وَلِلْمُسْلِمِينَ لِلْمَظْلُومِينَ</bdi>. A لام جارة with كسرة also attaches to المستغاث له, as in <bdi>يَا لَلَّهِ لِلْمُسْلِمِينَ</bdi>.`,
          sample: `لام المستغاث — فتحة: يا لَلّهِ؛ أو ألف بدلها: يا زيدَا، يا زيدَاهْ<br>لام المستغاث الثاني المعطوف دون تكرار يا — كسرة: يا لَلأمير ولِلمسلمين للمظلومين<br>لام المستغاث له — كسرة: يا لَلّه لِلمسلمين`,
          exercise: {
            prompt: `What لام attaches to المستغاث, and what may substitute for it?`,
            kind: 'mcq',
            options: ['A لام جارة with فتحة; an ألف at its end may substitute for it', 'A لام جارة with كسرة only, with no substitute', 'No لام attaches to المستغاث at all', 'A لام جارة with ضمة'],
            correct: 0,
          },
        },
        {
          heading: 'نداء التعجب والندبة',
          body: `<bdi>نِدَاءُ التَّعَجُّب</bdi> is calling out to that which one marvels at; it is treated like الاستغاثة, with المتعجب منه taking the place of المستغاث, as in <bdi>يَا لَلْقُرْآنِ، يَا قُرْآنَاهْ</bdi>, or the place of المستغاث له with المستغاث deleted, as in <bdi>يَا لِلْقُرْآنِ</bdi>. <bdi>الْنَّدْبَة</bdi> is a type of نداء expressing grief (<bdi>إِظْهَارُ الْحُزْن</bdi>), expressed with <bdi>وَا</bdi> — <bdi>وَا أَبَتَاهْ</bdi> — or with <bdi>يَا</bdi> when confusion with plain نداء is not feared, as in <bdi>يَا زَيْدُ</bdi>. المنادى in الندبة is parsed exactly as in ordinary نداء — <bdi>وَا زَيْدُ، وَا عَبْدَ اللَّهِ</bdi> — and may take <bdi>أَلِفُ النَّدْبَة</bdi> at its end, as in <bdi>وَا زَيْدَا</bdi>, or <bdi>هَاءُ السَّكْت</bdi> after that ألف when pausing, as in <bdi>وَا رَأْسَاهْ، وَا وَيْلَاهْ</bdi>.`,
          sample: `نداء التعجب — كالاستغاثة: المتعجب منه محل المستغاث (يا للقرآن، يا قرآناه) أو محل المستغاث له مع حذف المستغاث (يا للقرآن)<br>الندبة — إظهار الحزن؛ بوا: وا أبتاه؛ أو بيا إذا أُمن اللبس: يا زيد<br>إعراب منادى الندبة — كالنداء العادي: وا زيدُ، وا عبدَ الله<br>ألف الندبة وهاء السكت — وا زيدَا؛ وا رأسَاهْ، وا ويلَاهْ`,
          exercise: {
            prompt: `Define الندبة, and what may be attached to its منادى؟`,
            kind: 'mcq',
            options: ['نداء expressing grief; its منادى may take ألف الندبة at its end, and هاء السكت after that ألف when pausing', 'نداء calling for help against an enemy; its منادى takes لام الاستغاثة', 'A form of الترخيم exclusive to أعلام ending in تاء', 'A silent form of نداء with no particle at all'],
            correct: 0,
          },
        },
        {
          heading: 'حذف عامل الحال: أربعة مواضع قياسية',
          body: `Deletion of the عامل of الحال is obligatory by rule (<bdi>قِيَاسًا وُجُوبًا</bdi>) in four places: (1) الحال stands in for the خبر, as in <bdi>دُعَائِي رَبِّي مُسْتَيْقِنًا</bdi> (2) الحال indicates gradual increase or decrease, as in <bdi>تَصَدَّقْ بِدِرْهَمٍ فَصَاعِدًا</bdi> (3) preceded by an استفهام of توبيخ, as in <bdi>أَقَاعِدًا وَقَدْ أُقِيمَتِ الصَّلَاةُ؟</bdi> (4) الحال confirms the content of the sentence, as in <bdi>﴿وَهُوَ الْحَقُّ مُصَدِّقًا لِمَا مَعَهُمْ﴾</bdi>. سماعي examples also occur, like <bdi>هَنِيئًا لَكَ</bdi> and <bdi>سَالِمًا غَانِمًا</bdi>.`,
          sample: `المواضع القياسية الأربعة لحذف عامل الحال — الحال سادة مسد الخبر: دعائي ربي مستيقنا؛ الحال للزيادة أو النقصان تدريجا: تصدق بدرهم فصاعدا؛ بعد استفهام التوبيخ: أقاعدا وقد أقيمت الصلاة؟؛ الحال مؤكدة لمضمون الجملة: ﴿وهو الحق مصدقا لما معهم﴾<br>سماعي — هنيئا لك، سالما غانما`,
          exercise: {
            prompt: `In which four places is deletion of the عامل of الحال obligatory by rule (قياسا وجوبا)؟`,
            kind: 'mcq',
            options: ['الحال سادة مسد الخبر, الحال للتدرج, بعد استفهام التوبيخ, والحال المؤكدة لمضمون الجملة', 'التحذير, الإغراء, الاختصاص, الاشتغال', 'مضاف, شبيه بالمضاف, غير معين, ونكرة مقصودة', 'قبل القسم, بعد أنْ المصدرية, مع الواو بعد نفي, وقبل الاستفهام'],
            correct: 0,
          },
        },
      ],
      quiz: [
        { q: 'الترخيم is defined as:', options: ['حذف آخر المنادى تخفيفا (deleting the end of المنادى for lightness)', 'حذف حرف النداء تخفيفا (deleting the particle of النداء for lightness)', 'حذف المستغاث له بالكامل (deleting المستغاث له entirely)', 'إثبات آخر المنادى ساكنا دائما (always keeping the end of المنادى quiescent)'], correct: 0 },
        { q: 'يَا حَارِ (for حارث) illustrates one of the two permitted vowelings on a مرخَّم’s end, namely:', options: ['keeping the original vowel it had before truncation', 'the ضمة', 'the تنوين', 'the سكون always'], correct: 0 },
        { q: 'اللَّهُمَّ before إِلَّا signals:', options: ['ندرة المستثنى', 'تيقن المجيب', 'التعجب', 'الندبة'], correct: 0 },
        { q: 'الاستغاثة’s particle is:', options: ['يا only', 'أيا only', 'وا only', 'any of the seven حروف النداء'], correct: 0 },
        { q: 'الندبة is defined as a type of نداء that expresses:', options: ['إظهار الحزن (grief)', 'الترغيب (encouragement)', 'التحذير (warning)', 'الاستفهام (a question)'], correct: 0 },
        { q: 'Deletion of عامل الحال is obligatory by rule when الحال:', options: ['stands in for the خبر', 'is a حال مؤكدة for something not yet mentioned', 'follows a فعل أمر', 'is مجرور by a حرف جر'], correct: 0 },
      ],
      bank: [
        { title: 'ترخيم عائشة', kind: 'mcq', prompt: 'يَا عَائِشَ (for عائشة) illustrates الترخيم applied to a noun ending in:', options: ['التاء', 'الألف', 'الياء', 'الواو'], correct: 0 },
        { title: 'ما لا يجوز ترخيمه', kind: 'mcq', prompt: 'Why can زَيْنَب not undergo الترخيم the way جعفر can?', options: ['الترخيم of a masculine علم requires more than three letters and no compounding, conditions زينب doesn’t meet the same way', 'الترخيم is banned for all female names outright', 'زينب already ends in a تاء, which blocks it', 'الترخيم only applies to الأسماء الموصولة'], correct: 0 },
        { title: 'اللهم قبل نعم', kind: 'mcq', prompt: 'اللَّهُمَّ نَعَمْ illustrates اللهم signaling:', options: ['the responder’s تيقن (certainty) of the answer', 'the rarity (ندرة) of a مستثنى', 'grief (الحزن)', 'a request for aid (استغاثة)'], correct: 0 },
        { title: 'حرف الاستغاثة الوحيد', kind: 'mcq', prompt: 'The particle used for الاستغاثة is:', options: ['يا, and no other حرف نداء', 'أي, and no other حرف نداء', 'وا, and no other حرف نداء', 'any of the seven حروف النداء equally'], correct: 0 },
        { title: 'يا للّه: لام المستغاث', kind: 'mcq', prompt: 'يَا لَلَّهِ shows the لام attached to المستغاث with:', options: ['فتحة', 'كسرة', 'ضمة', 'سكون'], correct: 0 },
        { title: 'الألف بدل اللام', kind: 'mcq', prompt: 'يَا زَيْدَا shows what substituting for the لام of المستغاث؟', options: ['An ألف at its end', 'A هاء السكت', 'A ياء', 'Nothing — the لام is simply dropped with no substitute'], correct: 0 },
        { title: 'لام المستغاث الثاني', kind: 'mcq', prompt: 'يَا لَلْأَمِيرِ وَلِلْمُسْلِمِينَ لِلْمَظْلُومِينَ shows the لام of a second, conjoined مستغاث taking:', options: ['كسرة', 'فتحة', 'ضمة', 'سكون'], correct: 0 },
        { title: 'نداء التعجب كالاستغاثة', kind: 'mcq', prompt: 'يَا لَلْقُرْآنِ illustrates نداء التعجب treating المتعجب منه like:', options: ['المستغاث', 'المستغاث له, with المستغاث stated', 'المحذَّر منه', 'المشغول عنه'], correct: 0 },
        { title: 'الندبة بيا', kind: 'mcq', prompt: 'الندبة may be expressed with يا instead of وا when:', options: ['confusion with plain نداء is not feared', 'the منادى is لفظ الجلالة', 'the منادى undergoes الترخيم', 'never — الندبة is always with وا'], correct: 0 },
        { title: 'ألف الندبة وهاء السكت', kind: 'mcq', prompt: 'وَا رَأْسَاهْ shows الندبة’s منادى taking:', options: ['ألف الندبة followed by هاء السكت when pausing', 'لام الاستغاثة', 'ياء المتكلم', 'الترخيم, dropping its final letter'], correct: 0 },
        { title: 'الحال سادة مسد الخبر', kind: 'mcq', prompt: 'دُعَائِي رَبِّي مُسْتَيْقِنًا shows مستيقنا منصوب because it is:', options: ['a حال سادة مسد الخبر, with its عامل obligatorily deleted', 'a حال مؤكدة لمضمون الجملة', 'a تمييز, not a حال at all', 'a حال preceded by استفهام التوبيخ'], correct: 0 },
        { title: 'الحال للتدرج', kind: 'mcq', prompt: 'تَصَدَّقْ بِدِرْهَمٍ فَصَاعِدًا shows فصاعدا منصوب because it indicates:', options: ['gradual increase (زيادة بتدريج)', 'confirmation of the sentence’s content', 'a استفهام توبيخ', 'a سماعي case with no rule behind it'], correct: 0 },
        { title: 'الحال بعد استفهام التوبيخ', kind: 'mcq', prompt: 'أَقَاعِدًا وَقَدْ أُقِيمَتِ الصَّلَاةُ؟ shows قاعدا منصوب because it follows:', options: ['an استفهام intended as توبيخ', 'a حرف تحضيض', 'a حرف عرض', 'a حرف تنبيه'], correct: 0 },
        { title: 'الحال المؤكدة لمضمون الجملة', kind: 'mcq', prompt: '﴿وَهُوَ الْحَقُّ مُصَدِّقًا لِمَا مَعَهُمْ﴾ shows مصدقا منصوب because it is:', options: ['a حال مؤكدة لمضمون الجملة, with an obligatorily deleted عامل', 'a حال سادة مسد الخبر', 'a حال indicating تدرج', 'a مفعول به of a stated فعل'], correct: 0 },
        { title: 'أمثلة سماعية لحذف عامل الحال', kind: 'mcq', prompt: 'هَنِيئًا لَكَ and سَالِمًا غَانِمًا are examples of حذف عامل الحال that is:', options: ['سماعي, not extended by rule', 'قياسي, extended to any matching case', 'واحد من مواضع الاستغاثة', 'غير صحيح نحويا'], correct: 0 },
        {
          title: 'تركيب: ما يجوز ترخيمه',
          kind: 'tarkeeb',
          instruction: 'Classify each اسم: يجوز ترخيمه or لا يجوز ترخيمه؟',
          source: 'عائشة (منتهية بتاء) / جعفر (علم مذكر فوق ثلاثة أحرف) / زيد (ثلاثة أحرف فقط)',
          words: ['عائشة', 'جعفر', 'زيد'],
          labels: ['يجوز ترخيمه', 'يجوز ترخيمه', 'لا يجوز ترخيمه'],
          distractors: ['يجب ترخيمه'],
        },
        {
          title: 'تركيب: أركان الاستغاثة',
          kind: 'tarkeeb',
          instruction: 'Match each term in يا للّه للمسلمين to its ركن of الاستغاثة.',
          source: 'يا / اللّه / المسلمين',
          words: ['يا', 'اللّه', 'المسلمين'],
          labels: ['حرف الاستغاثة', 'المستغاث', 'المستغاث له'],
          distractors: ['المستغيث'],
        },
        {
          title: 'تركيب: مواضع حذف عامل الحال الأربعة',
          kind: 'tarkeeb',
          instruction: 'Match each مثال to the قياسي موضع of حذف عامل الحال it illustrates.',
          source: 'دعائي ربي مستيقنا / تصدق بدرهم فصاعدا / أقاعدا وقد أقيمت الصلاة؟ / وهو الحق مصدقا لما معهم',
          words: ['دعائي ربي مستيقنا', 'تصدق بدرهم فصاعدا', 'أقاعدا وقد أقيمت الصلاة؟', 'وهو الحق مصدقا لما معهم'],
          labels: ['سادة مسد الخبر', 'للتدرج', 'بعد استفهام التوبيخ', 'مؤكدة لمضمون الجملة'],
          distractors: ['سماعية'],
        },
        {
          title: 'تركيب: ترخيم أم استغاثة أم ندبة؟',
          kind: 'tarkeeb',
          instruction: 'Classify each example.',
          source: 'يا فاطمَ (لفاطمة) / يا للّه للمسلمين / وا زيدَا',
          words: ['يا فاطمَ', 'يا للّه للمسلمين', 'وا زيدَا'],
          labels: ['الترخيم', 'الاستغاثة', 'الندبة'],
          distractors: ['الاختصاص'],
        },
      ],
    },
  ],
};
