// Module 13 — الجملة وشبه الجملة: مواضعهما، أحكام واو الحال وفاء الجواب، والقسم
//
// Content is adapted from the second subsection's second deck (النَحْوُ__3
// المعمول وغير المعمول__2 الجملة + شبه الجملة.apkg, 54 notes, all of them
// here). Where modules 11-12 worked through المعمول of الاسم and الفعل,
// this module closes the المعمول وغير المعمول chapter — and the whole
// نحو course — with الجملة (which sentences have a محل من الإعراب and
// which don't, in exhaustive detail: مرفوعة، منصوبة، مجرورة، مجزومة،
// معمولة بالتبعية, the eight أنواع with no محل, واو الحال's rules, فاء
// جواب الشرط's rules, and القسم) and شبه الجملة (all of it معمول: الظرف
// اللغو and المستقر, and the deck's own closing "خاتمة" notes on شبه
// الجملة after معرفة/نكرة, plus المنصوب بنزع الخافض).

export default {
  id: '13',
  title: 'الجملة وشبه الجملة',
  heading: 'المعمول وغير المعمول',
  subheading: 'الجملة وشبه الجملة',
  blurb: 'الجملة التي لها محل من الإعراب (مرفوعة، منصوبة، مجرورة، مجزومة، ومعمولة بالتبعية), أحكام واو الحال وفاء جواب الشرط, الجملة التي لا محل لها من الإعراب بأنواعها الثمانية, أركان القسم وجوابه, and شبه الجملة: الظرف اللغو والمستقر, and المنصوب بنزع الخافض.',
  lessons: [
    // ---------------------------------------------------------------- L1
    {
      id: 'l1',
      title: 'الجملة ذات المحل: تعريفها ومواضعها المرفوعة والمنصوبة',
      subtitle: 'The Sentence with a Grammatical Position — where it is مرفوعة and where منصوبة',
      concepts: [
        {
          heading: 'تعريف الجملة ذات المحل',
          body: `The معمول sentence is called <bdi>الْجُمْلَةُ الَّتِي لَهَا مَحَلٌّ مِنَ الْإِعْرَاب</bdi> — the sentence that has a grammatical position, as though it were a single word standing in that إعراب slot.`,
          sample: `تعريف الجملة المعمولة — الجملة التي لها محل من الإعراب`,
          exercise: {
            prompt: `What is the معمول sentence called?`,
            kind: 'mcq',
            options: ['الجملة التي لها محل من الإعراب', 'الجملة التي لا محل لها من الإعراب', 'شبه الجملة', 'الجملة الابتدائية'],
            correct: 0,
          },
        },
        {
          heading: 'مواضع الجملة المرفوعة بالأصالة',
          body: `A sentence is مرفوعة بالأصالة in two positions: (1) <bdi>خَبَرُ الْمُبْتَدَأ</bdi>, as in <bdi>﴿وَاللَّهُ يُحِبُّ الْمُحْسِنِينَ﴾</bdi> — <bdi>يُحِبُّ الْمُحْسِنِينَ</bdi> is the خبر clause — (2) <bdi>خَبَرُ إِنّ</bdi>, as in <bdi>﴿إِنَّ اللَّهَ يُحِبُّ الْمُحْسِنِينَ﴾</bdi>.`,
          sample: `مرفوعة — خبر المبتدأ: ﴿والله يحب المحسنين﴾؛ خبر إن: ﴿إن الله يحب المحسنين﴾`,
          exercise: {
            prompt: `In which two positions is a sentence مرفوعة بالأصالة?`,
            kind: 'mcq',
            options: ['خبر المبتدأ and خبر إن', 'مفعول به and مفعول له', 'الحال and التمييز', 'صلة الموصول and المعترضة'],
            correct: 0,
          },
        },
        {
          heading: 'مواضع الجملة المنصوبة بالأصالة',
          body: `A sentence is منصوبة بالأصالة in four positions: (1) <bdi>الْمَفْعُولُ بِهِ</bdi>, as in <bdi>﴿قَالَ اللَّهُ هَٰذَا يَوْمُ يَنفَعُ الصَّادِقِينَ صِدْقُهُمْ﴾</bdi> (2) <bdi>الْمَفْعُولُ لَه</bdi>, as in <bdi>﴿وَاتَّقُوا اللَّهَ لَعَلَّكُمْ تُفْلِحُونَ﴾</bdi> (3) <bdi>الْحَال</bdi>, as in <bdi>طَافَ رَسُولُ اللَّهِ ﷺ بِالْبَيْتِ وَهُوَ يُلَبِّي</bdi> (4) <bdi>خَبَرُ الْفِعْلِ النَّاقِص</bdi>, as in <bdi>﴿كَانُوا يَعْمَلُونَ﴾</bdi>.`,
          sample: `منصوبة (٤ مواضع) — مفعول به: ﴿قال الله...﴾؛ مفعول له: ﴿واتقوا الله لعلكم تفلحون﴾؛ حال: طاف رسول الله وهو يلبي؛ خبر الفعل الناقص: ﴿كانوا يعملون﴾`,
          exercise: {
            prompt: `In which four positions is a sentence منصوبة بالأصالة?`,
            kind: 'mcq',
            options: ['المفعول به, المفعول له, الحال, and خبر الفعل الناقص', 'الفاعل, المبتدأ, الخبر, and الحال', 'المضاف إليه, البدل, النعت, and المعطوف', 'خبر المبتدأ, خبر إن, صلة الموصول, and المعترضة'],
            correct: 0,
          },
        },
        {
          heading: 'الجملة مفعولا به لقول: أسماؤها',
          body: `A sentence functioning as المفعول به of a verb of saying is called <bdi>مَقُولًا</bdi>, <bdi>مَقُولَ الْقَوْل</bdi>, and <bdi>مَقُولَة</bdi>.`,
          sample: `أسماء الجملة المفعول به لقول — مقول، مقول القول، مقولة`,
          exercise: {
            prompt: `What is the sentence functioning as مفعول به of a verb of saying called?`,
            kind: 'mcq',
            options: ['مقول, مقول القول, and مقولة', 'الجملة التعليلية', 'الجملة الحالية', 'صلة الموصول'],
            correct: 0,
          },
        },
        {
          heading: 'الجملة مفعولا له: الجملة التعليلية',
          body: `A sentence functioning as المفعول له is called <bdi>الْجُمْلَةُ التَّعْلِيلِيَّة</bdi>, as in <bdi>﴿وَاتَّقُوا اللَّهَ لَعَلَّكُمْ تُفْلِحُونَ﴾</bdi>.`,
          sample: `الجملة مفعولا له — الجملة التعليلية: ﴿واتقوا الله لعلكم تفلحون﴾`,
          exercise: {
            prompt: `What is the sentence functioning as مفعول له called? Give the example.`,
            kind: 'mcq',
            options: ['الجملة التعليلية: ﴿وَاتَّقُوا اللَّهَ لَعَلَّكُمْ تُفْلِحُونَ﴾', 'مقول القول', 'الجملة الحالية', 'الجملة الابتدائية'],
            correct: 0,
          },
        },
      ],
      quiz: [
        { q: 'الجملة التي لها محل من الإعراب is the definition of:', options: ['the معمول sentence', 'the غير معمول sentence', 'شبه الجملة', 'الجملة الابتدائية'], correct: 0 },
        { q: '﴿وَاللَّهُ يُحِبُّ الْمُحْسِنِينَ﴾ shows يحب المحسنين as a sentence that is:', options: ['خبر المبتدأ, مرفوعة بالأصالة', 'مفعول به, منصوبة بالأصالة', 'صلة الموصول, لا محل لها', 'الجملة الحالية'], correct: 0 },
        { q: 'طَافَ رَسُولُ اللَّهِ ﷺ بِالْبَيْتِ وَهُوَ يُلَبِّي shows وهو يلبي as a sentence that is:', options: ['حال, منصوبة بالأصالة', 'خبر المبتدأ, مرفوعة', 'مفعول له, منصوبة', 'مضاف إليه, مجرورة'], correct: 0 },
        { q: 'A sentence functioning as مفعول به of a verb of saying is called:', options: ['مقول القول', 'الجملة التعليلية', 'الجملة الحالية', 'الجملة الابتدائية'], correct: 0 },
        { q: '﴿وَاتَّقُوا اللَّهَ لَعَلَّكُمْ تُفْلِحُونَ﴾ shows لعلكم تفلحون as:', options: ['الجملة التعليلية, مفعول له', 'مقول القول', 'خبر إن', 'صلة الموصول'], correct: 0 },
        { q: '﴿كَانُوا يَعْمَلُونَ﴾ shows يعملون as:', options: ['خبر الفعل الناقص, منصوبة بالأصالة', 'خبر المبتدأ, مرفوعة', 'مفعول به, منصوبة', 'مضاف إليه, مجرورة'], correct: 0 },
      ],
      bank: [
        { title: 'خبر إن', kind: 'mcq', prompt: '﴿إِنَّ اللَّهَ يُحِبُّ الْمُحْسِنِينَ﴾ shows يحب المحسنين as:', options: ['خبر إن, مرفوعة بالأصالة', 'اسم إن', 'مفعول به', 'صلة الموصول'], correct: 0 },
        { title: 'الجملة مفعولا به', kind: 'mcq', prompt: '﴿قَالَ اللَّهُ هَٰذَا يَوْمُ يَنفَعُ الصَّادِقِينَ صِدْقُهُمْ﴾ shows the sentence after قال as:', options: ['مقول القول, مفعول به منصوب', 'خبر إن', 'الجملة الحالية', 'صلة الموصول'], correct: 0 },
        { title: 'الجملة التعليلية اسمها', kind: 'mcq', prompt: 'الجملة التعليلية is the name for a sentence functioning as:', options: ['المفعول له', 'المفعول به', 'الحال', 'خبر الفعل الناقص'], correct: 0 },
        { title: 'مقولة اسم بديل', kind: 'mcq', prompt: 'مَقُولَة is an alternative name for a sentence that is:', options: ['مقول القول', 'الجملة الحالية', 'صلة الموصول', 'المعترضة'], correct: 0 },
        { title: 'أربعة مواضع النصب', kind: 'mcq', prompt: 'Which of these is NOT one of the four مواضع of الجملة المنصوبة بالأصالة؟', options: ['خبر المبتدأ', 'المفعول به', 'الحال', 'خبر الفعل الناقص'], correct: 0 },
        {
          title: 'تركيب: مرفوعة أم منصوبة؟',
          kind: 'tarkeeb',
          instruction: 'Classify each جملة by its موضع من الإعراب.',
          source: '﴿والله يحب المحسنين﴾ / ﴿واتقوا الله لعلكم تفلحون﴾',
          words: ['يحب المحسنين', 'لعلكم تفلحون'],
          labels: ['مرفوعة (خبر المبتدأ)', 'منصوبة (مفعول له)'],
          distractors: ['مجرورة'],
        },
        {
          title: 'تركيب: مواضع النصب الأربعة',
          kind: 'tarkeeb',
          instruction: 'Match each مثال to the موضع of الجملة المنصوبة it illustrates.',
          source: '﴿قال الله هذا...﴾ (مقول) / ﴿واتقوا الله لعلكم تفلحون﴾ / وهو يلبي / ﴿كانوا يعملون﴾',
          words: ['مقول القول', 'لعلكم تفلحون', 'وهو يلبي', 'كانوا يعملون'],
          labels: ['مفعول به', 'مفعول له', 'حال', 'خبر الفعل الناقص'],
          distractors: ['مضاف إليه'],
        },
      ],
    },
    // ---------------------------------------------------------------- L2
    {
      id: 'l2',
      title: 'الجملة الحالية: أحكام الواو',
      subtitle: "The حال Clause — when واو is obligatory, forbidden, or optional",
      concepts: [
        {
          heading: 'مواضع وجوب واو الحال الثلاثة',
          body: `الواو of الجملة الحالية is obligatory in three cases: (1) the clause has no pronoun linking to صاحب الحال, as in <bdi>﴿لَئِنْ أَكَلَهُ الذِّئْبُ وَنَحْنُ عُصْبَةٌ﴾</bdi> (2) it is a nominal clause beginning with صاحب الحال’s own pronoun, as in <bdi>﴿وَلَا تَقْرَبُوا الصَّلَاةَ وَأَنتُمْ سُكَارَىٰ﴾</bdi> (3) it is a مضارع clause with <bdi>قَدْ</bdi>, as in <bdi>﴿لِمَ تُؤْذُونَنِي وَقَدْ تَعْلَمُونَ أَنِّي رَسُولُ اللَّهِ إِلَيْكُمْ﴾</bdi>.`,
          sample: `وجوب الواو (٣) — لا رابط بينها وبين صاحبها: ﴿ونحن عصبة﴾؛ اسمية بادئة بضمير صاحبها: ﴿وأنتم سكارى﴾؛ مضارعة مقترنة بقد: ﴿وقد تعلمون﴾`,
          exercise: {
            prompt: `In which three cases is the واو of the جملة حالية obligatory؟`,
            kind: 'mcq',
            options: ['No pronoun links it to صاحب الحال; it’s a nominal clause beginning with صاحب الحال’s pronoun; or it’s a مضارع clause with قد', 'Only ever when the clause is ماضٍ', 'Only ever when negated by لا', 'It is never obligatory, only optional'],
            correct: 0,
          },
        },
        {
          heading: 'مواضع امتناع واو الحال السبعة',
          body: `الواو of الجملة الحالية is prohibited in seven cases: (1) after a عاطف, as in <bdi>﴿أَوْ هُمْ قَائِلُونَ﴾</bdi> (2) the clause is مؤكدة for its preceding clause, as in <bdi>﴿ذَٰلِكَ الْكِتَابُ لَا رَيْبَ فِيهِ﴾</bdi> (3) a ماضي clause after <bdi>إِلَّا</bdi>, as in <bdi>﴿إِلَّا كَانُوا بِهِ يَسْتَهْزِئُونَ﴾</bdi> (4) a ماضي clause before <bdi>أَوْ</bdi>, as in <bdi>أَنْصِفِ النَّاسَ أَنْصَفُوكَ أَوْ ظَلَمُوكَ</bdi> (5) an affirmative مضارع clause without قد, as in <bdi>﴿وَلَا تَمْنُنْ تَسْتَكْثِرُ﴾</bdi> (6) a مضارع clause negated by <bdi>مَا</bdi>, as in <bdi>عَهِدْتُكَ مَا تَصْبِرُ عَلَى الشَّدَائِدِ</bdi> (7) a مضارع clause negated by <bdi>لَا</bdi>, as in <bdi>﴿وَمَا لِيَ لَا أَعْبُدُ الَّذِي فَطَرَنِي﴾</bdi>.`,
          sample: `امتناع الواو (٧) — بعد عاطف: ﴿أو هم قائلون﴾؛ مؤكدة لما قبلها: ﴿لا ريب فيه﴾؛ ماضية بعد إلا: ﴿إلا كانوا به يستهزئون﴾؛ ماضية قبل أو: أنصفوك أو ظلموك؛ مضارعة مثبتة بلا قد: ﴿ولا تمنن تستكثر﴾؛ مضارعة منفية بما: ما تصبر؛ مضارعة منفية بلا: ﴿لا أعبد الذي فطرني﴾`,
          exercise: {
            prompt: `In which seven cases is the واو of the جملة حالية prohibited؟`,
            kind: 'mcq',
            options: ['After a عاطف; when مؤكدة; ماضٍ after إلا or before أو; مضارع مثبت without قد; and مضارع negated by ما or لا', 'Only ever when the clause is nominal', 'Only ever when the clause has a pronoun linking to صاحبها', 'It is never prohibited, only sometimes optional'],
            correct: 0,
          },
        },
        {
          heading: 'الوجهان مع لم، وترجيح الواو مع لمّا',
          body: `For a مضارع حال clause negated by <bdi>لَمْ</bdi>, both are allowed: with واو, as in <bdi>﴿قُلْ أُوحِيَ إِلَيَّ وَلَمْ يُوحَ إِلَيْهِ شَيْءٌ﴾</bdi>, or without, as in <bdi>﴿فَانقَلَبُوا بِنِعْمَةٍ مِّنَ اللَّهِ وَفَضْلٍ لَّمْ يَمْسَسْهُمْ سُوءٌ﴾</bdi>. For الحال clause negated by <bdi>لَمَّا</bdi>, الواو is preferred, as in <bdi>﴿وَلَمَّا يَعْلَمِ اللَّهُ الَّذِينَ جَاهَدُوا مِنكُمْ﴾</bdi>.`,
          sample: `مع لم — الوجهان جائزان: بالواو ﴿ولم يوح إليه شيء﴾؛ بدونها ﴿لم يمسسهم سوء﴾<br>مع لمّا — الواو أرجح: ﴿ولما يعلم الله الذين جاهدوا منكم﴾`,
          exercise: {
            prompt: `What is preferred for the حال clause negated by لمّا؟`,
            kind: 'mcq',
            options: ['الواو', 'حذف الواو دائما', 'كلاهما ممتنع', 'اللام'],
            correct: 0,
          },
        },
        {
          heading: 'الاسمية غير البادئة بالضمير',
          body: `The rule for the nominal (اسمية) حال clause NOT starting with صاحبها’s pronoun: predominantly with واو, as in <bdi>﴿وَلَقَدْ نَصَرَكُمُ اللَّهُ بِبَدْرٍ وَأَنتُمْ أَذِلَّةٌ﴾</bdi>, sometimes without it, as in <bdi>﴿وَقُلْنَا اهْبِطُوا بَعْضُكُمْ لِبَعْضٍ عَدُوٌّ﴾</bdi>.`,
          sample: `اسمية غير بادئة بضمير صاحبها — غالبا بالواو: ﴿وأنتم أذلة﴾؛ أحيانا بدونها: ﴿بعضكم لبعض عدو﴾`,
          exercise: {
            prompt: `What is the rule for the nominal (اسمية) حال clause not starting with صاحبها’s pronoun؟`,
            kind: 'mcq',
            options: ['Predominantly with واو, sometimes without it', 'Always with واو, with no exception', 'Always without واو, with no exception', 'It is entirely forbidden as a حال clause'],
            correct: 0,
          },
        },
        {
          heading: 'أحكام الماضي المثبت حالا',
          body: `For the affirmative ماضي حال clause: predominantly with واو and قد, as in <bdi>﴿وَقَدْ هَدَانِ﴾</bdi>; sometimes واو alone, as in <bdi>﴿وَاتَّبَعَكَ الْأَرْذَلُونَ﴾</bdi>; sometimes neither, as in <bdi>﴿رُدَّتْ إِلَيْنَا﴾</bdi> (i.e. <bdi>هَٰذِهِ بِضَاعَتُنَا رُدَّتْ إِلَيْنَا﴾).`,
          sample: `الماضي المثبت حالا — غالبا بالواو وقد: ﴿وقد هداني﴾؛ أحيانا بالواو وحدها: ﴿واتبعك الأرذلون﴾؛ أحيانا بلا واو ولا قد: ﴿ردت إلينا﴾`,
          exercise: {
            prompt: `What are the rules for the affirmative ماضي حال clause?`,
            kind: 'mcq',
            options: ['Predominantly واو and قد together; sometimes واو alone; sometimes neither', 'Always واو and قد together, with no exception', 'Always neither واو nor قد', 'Only قد alone, never واو'],
            correct: 0,
          },
        },
      ],
      quiz: [
        { q: '﴿لَئِنْ أَكَلَهُ الذِّئْبُ وَنَحْنُ عُصْبَةٌ﴾ shows واو الحال obligatory because:', options: ['the clause has no pronoun linking to صاحب الحال', 'it is a مضارع clause with قد', 'it follows إلا', 'it follows a عاطف'], correct: 0 },
        { q: '﴿أَوْ هُمْ قَائِلُونَ﴾ shows واو الحال prohibited because it follows:', options: ['a عاطف', 'إلا', 'أو with a ماضٍ clause', 'a نفي بما'], correct: 0 },
        { q: 'For a مضارع حال clause negated by لم, the rule is:', options: ['both واو and no-واو are allowed', 'واو is obligatory', 'واو is forbidden', 'the clause cannot be حال at all'], correct: 0 },
        { q: 'For الحال clause negated by لمّا, what is preferred?', options: ['الواو', 'no واو', 'both equally, with no preference', 'neither — لمّا cannot introduce a حال clause'], correct: 0 },
        { q: '﴿وَلَقَدْ نَصَرَكُمُ اللَّهُ بِبَدْرٍ وَأَنتُمْ أَذِلَّةٌ﴾ shows an اسمية حال clause not starting with the pronoun, using:', options: ['واو, predominantly', 'no واو, predominantly', 'a لام مزحلقة', 'a نون توكيد'], correct: 0 },
        { q: '﴿وَقَدْ هَدَانِ﴾ illustrates the predominant pattern for the affirmative ماضي حال clause:', options: ['واو and قد together', 'واو alone', 'neither واو nor قد', 'قد alone, without واو'], correct: 0 },
      ],
      bank: [
        { title: 'اسمية بادئة بالضمير', kind: 'mcq', prompt: '﴿وَلَا تَقْرَبُوا الصَّلَاةَ وَأَنتُمْ سُكَارَىٰ﴾ shows واو الحال obligatory because the clause is:', options: ['اسمية بادئة بضمير صاحبها', 'فعلية ماضوية', 'مسبوقة بعاطف', 'مؤكدة لما قبلها'], correct: 0 },
        { title: 'مضارعة بقد', kind: 'mcq', prompt: '﴿وَقَدْ تَعْلَمُونَ أَنِّي رَسُولُ اللَّهِ إِلَيْكُمْ﴾ shows واو الحال obligatory because the clause is:', options: ['مضارعة مقترنة بقد', 'ماضوية بلا رابط', 'اسمية غير بادئة بالضمير', 'مؤكدة لما قبلها'], correct: 0 },
        { title: 'مؤكدة لما قبلها', kind: 'mcq', prompt: '﴿ذَٰلِكَ الْكِتَابُ لَا رَيْبَ فِيهِ﴾ shows واو الحال prohibited because the second جملة is:', options: ['مؤكدة for the preceding clause', 'مضارعة بقد', 'اسمية بادئة بالضمير', 'لا رابط بينها وبين صاحبها'], correct: 0 },
        { title: 'ماضية بعد إلا', kind: 'mcq', prompt: '﴿إِلَّا كَانُوا بِهِ يَسْتَهْزِئُونَ﴾ shows واو الحال prohibited because the clause is:', options: ['ماضية following إلا', 'مضارعة منفية بلا', 'مضارعة مثبتة بلا قد', 'اسمية بادئة بضمير صاحبها'], correct: 0 },
        { title: 'مضارعة منفية بما', kind: 'mcq', prompt: 'عَهِدْتُكَ مَا تَصْبِرُ عَلَى الشَّدَائِدِ shows واو الحال prohibited because the clause is:', options: ['مضارعة منفية بما', 'مضارعة منفية بلا', 'ماضية بعد إلا', 'مؤكدة لما قبلها'], correct: 0 },
        { title: 'مثبتة بلا قد', kind: 'mcq', prompt: '﴿وَلَا تَمْنُنْ تَسْتَكْثِرُ﴾ shows واو الحال prohibited because the clause is:', options: ['مضارعة مثبتة without قد', 'مضارعة منفية بما', 'ماضية قبل أو', 'مسبوقة بعاطف'], correct: 0 },
        { title: 'الوجهان مع لم بالمثال الثاني', kind: 'mcq', prompt: '﴿فَانقَلَبُوا بِنِعْمَةٍ مِّنَ اللَّهِ وَفَضْلٍ لَّمْ يَمْسَسْهُمْ سُوءٌ﴾ shows a مضارع حال clause negated by لم:', options: ['without واو, one of the two allowed options', 'with واو, obligatorily', 'with واو and قد together', 'in a form that is entirely forbidden'], correct: 0 },
        { title: 'ماضٍ بلا واو ولا قد', kind: 'mcq', prompt: '﴿رُدَّتْ إِلَيْنَا﴾ (i.e. هذه بضاعتنا ردت إلينا) illustrates the affirmative ماضي حال clause appearing:', options: ['with neither واو nor قد', 'with واو and قد together', 'with واو alone', 'this is never a valid حال pattern'], correct: 0 },
        {
          title: 'تركيب: وجوب أم امتناع واو الحال؟',
          kind: 'tarkeeb',
          instruction: 'Classify each مثال.',
          source: '﴿ونحن عصبة﴾ / ﴿لا ريب فيه﴾ / ﴿وأنتم سكارى﴾ / ﴿أو هم قائلون﴾',
          words: ['ونحن عصبة', 'لا ريب فيه', 'وأنتم سكارى', 'أو هم قائلون'],
          labels: ['وجوب', 'امتناع', 'وجوب', 'امتناع'],
          distractors: ['جواز'],
        },
        {
          title: 'تركيب: أسباب امتناع الواو',
          kind: 'tarkeeb',
          instruction: 'Match each مثال to the reason واو الحال is prohibited.',
          source: '﴿إلا كانوا به يستهزئون﴾ / عهدتك ما تصبر / ﴿ولا تمنن تستكثر﴾',
          words: ['إلا كانوا به يستهزئون', 'عهدتك ما تصبر', 'ولا تمنن تستكثر'],
          labels: ['ماضية بعد إلا', 'مضارعة منفية بما', 'مضارعة مثبتة بلا قد'],
          distractors: ['مسبوقة بعاطف'],
        },
      ],
    },
    // ---------------------------------------------------------------- L3
    {
      id: 'l3',
      title: 'الجملة المجرورة والمجزومة: أحكام فاء جواب الشرط',
      subtitle: 'The جر and جزم Positions, and when فاء the جواب needs is obligatory, optional, or forbidden',
      concepts: [
        {
          heading: 'الجملة المجرورة: مضافا إليه',
          body: `A sentence is مجرورة بالأصالة as <bdi>مُضَافٌ إِلَيْه</bdi>, as in <bdi>﴿هَٰذَا يَوْمُ يَنفَعُ الصَّادِقِينَ صِدْقُهُمْ﴾</bdi>, where <bdi>يَنفَعُ الصَّادِقِينَ صِدْقُهُمْ</bdi> is مضاف إليه to <bdi>يَوْم</bdi>.`,
          sample: `مجرورة — مضاف إليه: ﴿هذا يوم ينفع الصادقين صدقهم﴾`,
          exercise: {
            prompt: `In which position is a sentence مجرورة بالأصالة? Give the example.`,
            kind: 'mcq',
            options: ['As مضاف إليه: ﴿هَٰذَا يَوْمُ يَنفَعُ الصَّادِقِينَ صِدْقُهُمْ﴾', 'As مفعول به', 'As حال', 'As خبر إن'],
            correct: 0,
          },
        },
        {
          heading: 'الجملة المجزومة: جواب الشرط الجازم برابطة',
          body: `A sentence is مجزومة بالأصالة as the جواب of a jazm-conditional (<bdi>شَرْطٌ جَازِم</bdi>), PROVIDED it is linked by a <bdi>رَابِطَة</bdi> — the <bdi>فَاء</bdi> or <bdi>إِذَا الْفُجَائِيَّة</bdi> — as in <bdi>﴿مَن يُضْلِلِ اللَّهُ فَلَا هَادِيَ لَهُ﴾</bdi>.`,
          sample: `مجزومة — جواب شرط جازم مرتبط برابطة (الفاء أو إذا الفجائية): ﴿من يضلل الله فلا هادي له﴾`,
          exercise: {
            prompt: `In which position is a sentence مجزومة بالأصالة, and what is required؟`,
            kind: 'mcq',
            options: ['As جواب of a jazm-conditional, provided it is linked by a رابطة — الفاء or إذا الفجائية', 'As مضاف إليه, with no further condition', 'As حال, provided it starts with واو', 'A sentence can never be مجزومة'],
            correct: 0,
          },
        },
        {
          heading: 'الفاء الواجبة في جواب الشرط',
          body: `الفاء is obligatory in جواب الشرط when الجواب is: (1) جملة اسمية, as in <bdi>﴿وَإِن يَمْسَسْكَ بِخَيْرٍ فَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ﴾</bdi> (2) فعلية with a jāmid verb, as in <bdi>﴿إِن تَرَنِ أَنَا أَقَلَّ مِنكَ مَالًا وَوَلَدًا... فَعَسَىٰ رَبِّي﴾</bdi> (3) <bdi>طَلَبِيَّة</bdi> — أمر, as in <bdi>﴿إِن كُنتُمْ تُحِبُّونَ اللَّهَ فَاتَّبِعُونِي﴾</bdi>, or نهي, as in <bdi>﴿فَإِنْ عَلِمْتُمُوهُنَّ مُؤْمِنَاتٍ فَلَا تَرْجِعُوهُنَّ إِلَى الْكُفَّارِ﴾</bdi> (4) ماضٍ affirmative with قد — overt or implied, as in <bdi>﴿إِن يَسْرِقْ فَقَدْ سَرَقَ أَخٌ لَّهُ مِن قَبْلُ﴾</bdi> (5) negated by <bdi>مَا</bdi>, as in <bdi>﴿وَإِن لَّمْ تَفْعَلْ فَمَا بَلَّغْتَ رِسَالَتَهُ﴾</bdi> (6) مضارع with a <bdi>تَنْفِيس</bdi> particle, as in <bdi>﴿فَسَيَحْشُرُهُمْ إِلَيْهِ جَمِيعًا﴾</bdi> (7) negated by <bdi>لَنْ</bdi>, as in <bdi>﴿وَمَا يَفْعَلُوا مِنْ خَيْرٍ فَلَن يُكْفَرُوهُ﴾</bdi> (8) opening with <bdi>كَأَنَّمَا</bdi>, as in <bdi>﴿وَمَن يُشْرِكْ بِاللَّهِ فَكَأَنَّمَا خَرَّ مِنَ السَّمَاءِ﴾</bdi> (9) opening with a conditional particle, as in <bdi>﴿وَإِن كَانَ كَبُرَ عَلَيْكَ إِعْرَاضُهُمْ فَإِنِ اسْتَطَعْتَ...﴾</bdi>.`,
          sample: `الفاء واجبة إذا كان الجواب — اسمية؛ فعلية بفعل جامد؛ طلبية (أمر أو نهي)؛ ماضية مثبتة بقد ظاهرة أو مقدرة؛ منفية بما؛ مضارعة بحرف تنفيس؛ منفية بلن؛ مفتتحة بكأنما؛ مفتتحة بأداة شرط أخرى`,
          exercise: {
            prompt: `List the cases in which الفاء is obligatory in جواب الشرط (name several).`,
            kind: 'mcq',
            options: ['When الجواب is جملة اسمية, فعلية بفعل جامد, طلبية, ماضية مثبتة بقد, منفية بما أو لن, أو مفتتحة بأداة أخرى', 'Only ever when الجواب is فعلية بفعل مضارع', 'Only ever when الجواب is منفية بلا', 'الفاء is never obligatory, only ever optional'],
            correct: 0,
          },
        },
        {
          heading: 'جواز الفاء مع المضارع',
          body: `الفاء is optional (<bdi>جَائِزَة</bdi>) in جواب الشرط when الجواب is a مضارع: affirmative without تنفيس — with فاء, as in <bdi>﴿وَمَنْ عَادَ فَيَنتَقِمُ اللَّهُ مِنْهُ﴾</bdi>, or without, as in <bdi>﴿إِن يَكُن مِّنكُمْ عِشْرُونَ صَابِرُونَ يَغْلِبُوا مِائَتَيْنِ﴾</bdi>; or negated by <bdi>لَا</bdi>, as in <bdi>﴿وَمَن يَعْمَلْ مِنَ الصَّالِحَاتِ وَهُوَ مُؤْمِنٌ فَلَا يَخَافُ ظُلْمًا وَلَا هَضْمًا﴾</bdi> — or without الفاء.`,
          sample: `جواز الفاء — مضارعة مثبتة بلا تنفيس: بها ﴿فينتقم الله منه﴾؛ بدونها ﴿يغلبوا مائتين﴾؛ منفية بلا: ﴿فلا يخاف ظلما ولا هضما﴾، أو بدونها`,
          exercise: {
            prompt: `When is الفاء optional (جائزة) in جواب الشرط?`,
            kind: 'mcq',
            options: ['When الجواب is a مضارع — affirmative without تنفيس, or negated by لا', 'When الجواب is جملة اسمية', 'When الجواب is ماضٍ مثبت بقد', 'الفاء is never optional'],
            correct: 0,
          },
        },
        {
          heading: 'امتناع الفاء، وبديلها إذا الفجائية',
          body: `الفاء is prohibited in جواب الشرط when الجواب is a ماضٍ without قد — لفظا, as in <bdi>﴿إِنْ أَحْسَنتُمْ أَحْسَنتُمْ لِأَنفُسِكُمْ﴾</bdi>, or معنى (i.e. past-meaning <bdi>لَمْ</bdi> + مضارع), as in <bdi>إِنْ خَرَجْتَ لَمْ أَخْرُجْ</bdi>. What may replace الفاء as رابطة is <bdi>إِذَا الْفُجَائِيَّة</bdi> — after إن and إذا — as in <bdi>﴿وَإِن تُصِبْهُمْ سَيِّئَةٌ بِمَا قَدَّمَتْ أَيْدِيهِمْ إِذَا هُمْ يَقْنَطُونَ﴾</bdi>.`,
          sample: `امتناع الفاء — ماضٍ بلا قد، لفظا: ﴿أحسنتم أحسنتم لأنفسكم﴾؛ أو معنى (لم+مضارع): إن خرجت لم أخرج<br>بديلها — إذا الفجائية: ﴿إذا هم يقنطون﴾`,
          exercise: {
            prompt: `What may replace الفاء as رابطة of الجواب?`,
            kind: 'mcq',
            options: ['إذا الفجائية, after إن and إذا', 'اللام المزحلقة', 'نون التوكيد', 'قد وحدها'],
            correct: 0,
          },
        },
      ],
      quiz: [
        { q: '﴿هَٰذَا يَوْمُ يَنفَعُ الصَّادِقِينَ صِدْقُهُمْ﴾ shows ينفع الصادقين صدقهم as:', options: ['مضاف إليه, مجرورة بالأصالة', 'مفعول به, منصوبة', 'خبر إن, مرفوعة', 'حال, منصوبة'], correct: 0 },
        { q: 'For a sentence to be مجزومة as جواب الشرط, it must:', options: ['be linked by a رابطة — الفاء or إذا الفجائية', 'always start with الفاء', 'always be a جملة اسمية', 'never contain a pronoun'], correct: 0 },
        { q: '﴿وَإِن يَمْسَسْكَ بِخَيْرٍ فَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ﴾ shows الفاء obligatory because الجواب is:', options: ['جملة اسمية', 'جملة فعلية ماضوية', 'مضارعة بتنفيس', 'منفية بلن'], correct: 0 },
        { q: 'الفاء is جائزة (optional) when الجواب is a مضارع:', options: ['affirmative without تنفيس, or negated by لا', 'negated by ما', 'مفتتحة بكأنما', 'ماضٍ without قد'], correct: 0 },
        { q: '﴿إِنْ أَحْسَنتُمْ أَحْسَنتُمْ لِأَنفُسِكُمْ﴾ shows الفاء prohibited because الجواب is:', options: ['a ماضٍ without قد', 'a جملة اسمية', 'a مضارع with تنفيس', 'negated by لن'], correct: 0 },
        { q: 'What may replace الفاء as رابطة of الجواب?', options: ['إذا الفجائية', 'اللام المزحلقة', 'نون التوكيد', 'قد'], correct: 0 },
      ],
      bank: [
        { title: 'رابطة الجواب المجزوم', kind: 'mcq', prompt: '﴿مَن يُضْلِلِ اللَّهُ فَلَا هَادِيَ لَهُ﴾ shows الجواب مجزوما because it is linked by:', options: ['الفاء', 'إن الشرطية alone', 'a redundant واو', 'نون التوكيد'], correct: 0 },
        { title: 'الفاء مع الفعل الجامد', kind: 'mcq', prompt: '﴿إِن تَرَنِ أَنَا أَقَلَّ مِنكَ مَالًا وَوَلَدًا... فَعَسَىٰ رَبِّي﴾ shows الفاء obligatory because الجواب is فعلية with a:', options: ['jāmid verb (عسى)', 'مضارع verb with تنفيس', 'ماضٍ verb with قد', 'أمر verb'], correct: 0 },
        { title: 'الفاء مع الطلبية أمرا', kind: 'mcq', prompt: '﴿إِن كُنتُمْ تُحِبُّونَ اللَّهَ فَاتَّبِعُونِي﴾ shows الفاء obligatory because الجواب is:', options: ['طلبية (أمر)', 'جملة اسمية', 'ماضية بلا قد', 'منفية بلن'], correct: 0 },
        { title: 'الفاء مع الماضي المثبت بقد', kind: 'mcq', prompt: '﴿إِن يَسْرِقْ فَقَدْ سَرَقَ أَخٌ لَّهُ مِن قَبْلُ﴾ shows الفاء obligatory because الجواب is:', options: ['ماضٍ affirmative with قد', 'مضارع with تنفيس', 'جملة اسمية', 'منفية بلا'], correct: 0 },
        { title: 'الفاء مع حرف تنفيس', kind: 'mcq', prompt: '﴿فَسَيَحْشُرُهُمْ إِلَيْهِ جَمِيعًا﴾ shows الفاء obligatory because الجواب is a مضارع with:', options: ['a حرف تنفيس (سـ)', 'قد', 'a نفي بلا', 'a نفي بما'], correct: 0 },
        { title: 'الفاء مع كأنما', kind: 'mcq', prompt: '﴿وَمَن يُشْرِكْ بِاللَّهِ فَكَأَنَّمَا خَرَّ مِنَ السَّمَاءِ﴾ shows الفاء obligatory because الجواب opens with:', options: ['كأنما', 'أداة شرط أخرى', 'ما النافية', 'لن'], correct: 0 },
        { title: 'الفاء الجائزة بلا', kind: 'mcq', prompt: '﴿وَمَن يَعْمَلْ مِنَ الصَّالِحَاتِ وَهُوَ مُؤْمِنٌ فَلَا يَخَافُ ظُلْمًا وَلَا هَضْمًا﴾ shows الفاء as:', options: ['جائزة, since الجواب is a مضارع negated by لا', 'واجبة, with no alternative', 'ممتنعة, since it should not appear at all', 'مستبدلة بإذا الفجائية'], correct: 0 },
        { title: 'امتناع الفاء معنى', kind: 'mcq', prompt: 'إِنْ خَرَجْتَ لَمْ أَخْرُجْ shows الفاء prohibited because الجواب is:', options: ['past in meaning (لم + مضارع), though not لفظا ماضٍ', 'a جملة اسمية', 'a طلبية', 'مفتتحة بكأنما'], correct: 0 },
        {
          title: 'تركيب: مجرورة أم مجزومة؟',
          kind: 'tarkeeb',
          instruction: 'Classify each جملة.',
          source: '﴿هذا يوم ينفع الصادقين صدقهم﴾ / ﴿من يضلل الله فلا هادي له﴾',
          words: ['ينفع الصادقين صدقهم', 'فلا هادي له'],
          labels: ['مجرورة (مضاف إليه)', 'مجزومة (جواب شرط)'],
          distractors: ['منصوبة'],
        },
        {
          title: 'تركيب: واجبة أم جائزة أم ممتنعة الفاء؟',
          kind: 'tarkeeb',
          instruction: 'Classify each جواب شرط by حكم الفاء فيه.',
          source: '﴿فهو على كل شيء قدير﴾ / ﴿يغلبوا مائتين﴾ (بلا فاء) / ﴿أحسنتم أحسنتم لأنفسكم﴾',
          words: ['فهو على كل شيء قدير', 'يغلبوا مائتين', 'أحسنتم أحسنتم لأنفسكم'],
          labels: ['واجبة', 'جائزة (بدونها)', 'ممتنعة'],
          distractors: ['مستبدلة بإذا'],
        },
      ],
    },
    // ---------------------------------------------------------------- L4
    {
      id: 'l4',
      title: 'الجملة معمولة بالتبعية، وأنواع غير المعمولة الأولى',
      subtitle: 'The Sentence as a تابع, and the First of the Eight محل-less Types',
      concepts: [
        {
          heading: 'الجملة معمولة بالتبعية: طرقها الثلاث، وشرطا النعتية',
          body: `A sentence is معمولة بالتبعية in three ways: (1) <bdi>نَعْت</bdi>, as in <bdi>﴿مِن قَبْلِ أَن يَأْتِيَ يَوْمٌ لَّا بَيْعٌ فِيهِ﴾</bdi> (2) <bdi>بَدَل</bdi> (3) <bdi>مَعْطُوفَة</bdi> on a sentence that has a محل. The جملة النعتية has two conditions: it must contain a pronoun returning to المنعوت — overt or implied — and المنعوت must be a نكرة (محضة or غير محضة), as in <bdi>﴿عَلَيْهَا مَلَائِكَةٌ غِلَاظٌ شِدَادٌ لَّا يَعْصُونَ اللَّهَ مَا أَمَرَهُمْ﴾</bdi>, or definite but في حكم النكرة, as in <bdi>﴿كَمَثَلِ الْحِمَارِ يَحْمِلُ أَسْفَارًا﴾</bdi>.`,
          sample: `طرق التبعية الثلاث — نعت: ﴿لا بيع فيه﴾؛ بدل؛ معطوفة على جملة لها محل<br>شرطا الجملة النعتية — ضمير عائد على المنعوت (لفظا أو تقديرا)؛ المنعوت نكرة (محضة أو غير محضة) أو معرفة في حكم النكرة`,
          exercise: {
            prompt: `In which three ways is a sentence معمولة بالتبعية?`,
            kind: 'mcq',
            options: ['نعت, بدل, and معطوفة on a sentence that has a محل', 'مرفوعة, منصوبة, and مجرورة', 'ابتدائية, مستأنفة, and معترضة', 'قسم, شرط, and جواب'],
            correct: 0,
          },
        },
        {
          heading: 'جملة البدل، وجملة معطوفة',
          body: `A جملة بدل may substitute from a مفرد, as in <bdi>﴿أَفَلَا يَنظُرُونَ إِلَى الْإِبِلِ كَيْفَ خُلِقَتْ﴾</bdi> — <bdi>كَيْفَ خُلِقَتْ</bdi> is بدل from <bdi>الْإِبِل</bdi> — or from a sentence that has a محل, as in <bdi>﴿نَجَّيْنَاكُم مِّنْ آلِ فِرْعَوْنَ يَسُومُونَكُمْ سُوءَ الْعَذَابِ يَذْبَحُونَ أَبْنَاءَكُمْ﴾</bdi> — <bdi>يَذْبَحُونَ أَبْنَاءَكُمْ</bdi> is بدل from <bdi>يَسُومُونَكُمْ</bdi>. A جملة معطوفة on a sentence with a محل: <bdi>«الصَّلَاةُ نُورٌ وَالصَّدَقَةُ بُرْهَانٌ»</bdi> — <bdi>وَالصَّدَقَةُ بُرْهَانٌ</bdi> is معطوفة on a clause that has a محل.`,
          sample: `جملة بدل من مفرد — ﴿كيف خلقت﴾ بدل من الإبل<br>جملة بدل من جملة لها محل — ﴿يذبحون أبناءكم﴾ بدل من ﴿يسومونكم﴾<br>جملة معطوفة على جملة لها محل — «والصدقة برهان» معطوفة على «الصلاة نور»`,
          exercise: {
            prompt: `From what may a جملة بدل be substituted? Give examples.`,
            kind: 'mcq',
            options: ['From a مفرد, or from a sentence that has a محل', 'Only ever from another sentence with no محل', 'Only ever from a مفرد, never a sentence', 'It can never be substituted from anything'],
            correct: 0,
          },
        },
        {
          heading: 'تعريف الجملة غير المعمولة، وعدد أنواعها',
          body: `The غير معمولة sentence is called <bdi>الْجُمْلَةُ الَّتِي لَا مَحَلَّ لَهَا مِنَ الْإِعْرَاب</bdi>. There are eight types of it.`,
          sample: `تعريف الجملة غير المعمولة — الجملة التي لا محل لها من الإعراب؛ ثمانية أنواع`,
          exercise: {
            prompt: `What is the غير معمولة sentence called, and how many types are there?`,
            kind: 'mcq',
            options: ['الجملة التي لا محل لها من الإعراب; eight types', 'الجملة التي لها محل من الإعراب; five types', 'شبه الجملة; two types', 'الجملة التعليلية; one type only'],
            correct: 0,
          },
        },
        {
          heading: 'الأنواع الثمانية للجملة غير المعمولة',
          body: `The eight sentences that have no محل من الإعراب: (1) <bdi>الِابْتِدَائِيَّة</bdi> (2) <bdi>الْمُسْتَأْنَفَة</bdi> (3) <bdi>صِلَةُ الْمَوْصُول</bdi> (4) <bdi>الْمُعْتَرِضَة</bdi> (5) <bdi>التَّفْسِيرِيَّة</bdi> (6) <bdi>جَوَابُ الْقَسَم</bdi> (7) <bdi>جَوَابُ الشَّرْطِ غَيْرِ الْجَازِم</bdi> (or the jazm-conditional's جواب without a رابطة) (8) <bdi>التَّابِعَةُ لِمَا لَا مَحَلَّ لَه</bdi>.`,
          sample: `الأنواع الثمانية — الابتدائية، المستأنفة، صلة الموصول، المعترضة، التفسيرية، جواب القسم، جواب الشرط غير الجازم (أو الجازم بلا رابطة)، التابعة لما لا محل له`,
          exercise: {
            prompt: `List the eight sentences that have no محل من الإعراب (name several).`,
            kind: 'mcq',
            options: ['الابتدائية, المستأنفة, صلة الموصول, المعترضة, التفسيرية, جواب القسم, جواب الشرط غير الجازم, and التابعة لما لا محل له', 'مرفوعة, منصوبة, مجرورة, مجزومة, and four others', 'نعت, بدل, عطف بيان, معطوف, and four others', 'حقيقية, سببية, مؤسسة, مؤكدة, and four others'],
            correct: 0,
          },
        },
        {
          heading: 'الابتدائية والمستأنفة، وحروف الاستئناف',
          body: `<bdi>الْجُمْلَةُ الِابْتِدَائِيَّة</bdi> is the sentence with which speech begins, as in <bdi>﴿إِنَّا أَنزَلْنَاهُ فِي لَيْلَةِ الْقَدْرِ﴾</bdi>. <bdi>الْمُسْتَأْنَفَة</bdi> is the sentence occurring mid-speech but disconnected in إعراب (<bdi>مُنْقَطِعَة إِعْرَابًا</bdi>) from what precedes it — معطوفة on a sentence with no محل, as in <bdi>اِجْتَهَدَ زَيْدٌ وَنَجَحَ</bdi>, or غير معطوفة, as in <bdi>﴿وَمَا أُبَرِّئُ نَفْسِي إِنَّ النَّفْسَ لَأَمَّارَةٌ بِالسُّوءِ﴾</bdi>. <bdi>جَوَابُ النِّدَاء</bdi> belongs to المستأنفة too, as in <bdi>﴿يَا أَيُّهَا النَّاسُ اعْبُدُوا رَبَّكُمْ﴾</bdi> — and indeed the term المستأنفة may also be applied to الابتدائية itself. The <bdi>حُرُوفُ الِاسْتِئْنَاف</bdi>: <bdi>الْوَاو، ثُمَّ، حَتَّىٰ، أَمِ الْمُنْقَطِعَة، بَلِ الِانْتِقَالِيَّة، أَوْ بِمَعْنَىٰ بَل، لَٰكِنِ الْمُجَرَّدَة عَنِ الْوَاو</bdi>.`,
          sample: `الابتدائية — أول جملة تبدأ بها الكلام: ﴿إنا أنزلناه في ليلة القدر﴾<br>المستأنفة — منقطعة إعرابا عما قبلها، معطوفة (اجتهد زيد ونجح) أو غير معطوفة (﴿إن النفس لأمارة بالسوء﴾)؛ جواب النداء منها: ﴿اعبدوا ربكم﴾؛ وقد تُطلق على الابتدائية نفسها<br>حروف الاستئناف — الواو، ثم، حتى، أم المنقطعة، بل الانتقالية، أو بمعنى بل، لكن المجردة عن الواو`,
          exercise: {
            prompt: `Define الجملة المستأنفة, and give an example.`,
            kind: 'mcq',
            options: ['The sentence occurring mid-speech but disconnected in إعراب from what precedes it, whether معطوفة or غير معطوفة', 'The very first sentence speech begins with', 'A sentence forming a relative clause', 'A sentence interposed between two connected elements'],
            correct: 0,
          },
        },
        {
          heading: 'صلة الموصول، والمعترضة',
          body: `<bdi>صِلَةُ الْمَوْصُول</bdi> is the sentence forming the relative clause, as in <bdi>﴿اعْبُدُوا رَبَّكُمُ الَّذِي خَلَقَكُمْ﴾</bdi> — <bdi>خَلَقَكُمْ</bdi> has no محل. <bdi>الْجُمْلَةُ الْمُعْتَرِضَة</bdi> is the sentence interposed between two connected elements, as in <bdi>﴿فَإِن لَّمْ تَفْعَلُوا وَلَن تَفْعَلُوا فَاتَّقُوا النَّارَ﴾</bdi> — <bdi>وَلَن تَفْعَلُوا</bdi> is معترضة.`,
          sample: `صلة الموصول — الجملة التي تكوّن الصلة: ﴿الذي خلقكم﴾، خلقكم لا محل لها<br>المعترضة — تتوسط بين متلازمين: ﴿ولن تفعلوا﴾`,
          exercise: {
            prompt: `Define the جملة المعترضة, and give the example.`,
            kind: 'mcq',
            options: ['The sentence interposed between two connected elements: ﴿فَإِن لَّمْ تَفْعَلُوا وَلَن تَفْعَلُوا فَاتَّقُوا النَّارَ﴾', 'The sentence forming a relative clause', 'The sentence explaining what precedes it', 'The very first sentence of speech'],
            correct: 0,
          },
        },
      ],
      quiz: [
        { q: 'A sentence is معمولة بالتبعية in three ways:', options: ['نعت, بدل, and معطوفة on a sentence with a محل', 'مرفوعة, منصوبة, and مجرورة', 'ابتدائية, مستأنفة, and معترضة', 'حقيقية, سببية, and مؤسسة'], correct: 0 },
        { q: '﴿مِن قَبْلِ أَن يَأْتِيَ يَوْمٌ لَّا بَيْعٌ فِيهِ﴾ shows the sentence لا بيع فيه as:', options: ['نعت, معمولة بالتبعية', 'بدل', 'معطوفة', 'صلة الموصول'], correct: 0 },
        { q: 'الجملة التي لا محل لها من الإعراب has how many types?', options: ['Eight', 'Five', 'Three', 'Twelve'], correct: 0 },
        { q: 'الجملة الابتدائية is defined as:', options: ['the sentence with which speech begins', 'a sentence forming a relative clause', 'a sentence interposed between two connected elements', 'a sentence explaining what precedes it'], correct: 0 },
        { q: '﴿اعْبُدُوا رَبَّكُمُ الَّذِي خَلَقَكُمْ﴾ shows خلقكم as:', options: ['صلة الموصول, no محل', 'المعترضة', 'التفسيرية', 'الابتدائية'], correct: 0 },
        { q: 'جواب النداء belongs to which type of الجملة غير المعمولة?', options: ['المستأنفة', 'الابتدائية only, never المستأنفة', 'صلة الموصول', 'التفسيرية'], correct: 0 },
      ],
      bank: [
        { title: 'شرط النكرة في النعتية', kind: 'mcq', prompt: '﴿عَلَيْهَا مَلَائِكَةٌ غِلَاظٌ شِدَادٌ لَّا يَعْصُونَ اللَّهَ مَا أَمَرَهُمْ﴾ shows الجملة النعتية modifying a منعوت that is:', options: ['نكرة', 'معرفة صريحة', 'ضمير', 'اسم علم'], correct: 0 },
        { title: 'بدل من مفرد', kind: 'mcq', prompt: '﴿أَفَلَا يَنظُرُونَ إِلَى الْإِبِلِ كَيْفَ خُلِقَتْ﴾ shows كيف خلقت as بدل from:', options: ['a مفرد (الإبل)', 'a جملة لها محل', 'a جملة لا محل لها', 'nothing — it is not a بدل'], correct: 0 },
        { title: 'بدل من جملة لها محل', kind: 'mcq', prompt: '﴿نَجَّيْنَاكُم مِّنْ آلِ فِرْعَوْنَ يَسُومُونَكُمْ سُوءَ الْعَذَابِ يَذْبَحُونَ أَبْنَاءَكُمْ﴾ shows يذبحون أبناءكم as بدل from:', options: ['a جملة لها محل (يسومونكم)', 'a مفرد', 'a جملة لا محل لها', 'nothing at all'], correct: 0 },
        { title: 'حروف الاستئناف السبعة', kind: 'mcq', prompt: 'Which of these is one of the حروف الاستئناف?', options: ['ثم', 'إنّ', 'لولا', 'كي'], correct: 0 },
        { title: 'المستأنفة قد تُطلق على الابتدائية', kind: 'mcq', prompt: 'What relationship holds between المستأنفة and الابتدائية?', options: ['المستأنفة may also be applied to الابتدائية', 'They are entirely unrelated terms', 'الابتدائية is a subtype of صلة الموصول', 'المستأنفة never applies to the first sentence of speech'], correct: 0 },
        { title: 'الصلاة نور والصدقة برهان', kind: 'mcq', prompt: '«الصَّلَاةُ نُورٌ وَالصَّدَقَةُ بُرْهَانٌ» shows والصدقة برهان as:', options: ['معطوفة on a sentence that has a محل', 'بدل from a مفرد', 'صلة الموصول', 'المعترضة'], correct: 0 },
        {
          title: 'تركيب: نعت أم بدل أم معطوفة؟',
          kind: 'tarkeeb',
          instruction: 'Classify each جملة معمولة بالتبعية.',
          source: '﴿لا بيع فيه﴾ / ﴿كيف خلقت﴾ (بدل من الإبل) / والصدقة برهان',
          words: ['لا بيع فيه', 'كيف خلقت', 'والصدقة برهان'],
          labels: ['نعت', 'بدل', 'معطوفة'],
          distractors: ['صلة الموصول'],
        },
        {
          title: 'تركيب: أي نوع من الثمانية؟',
          kind: 'tarkeeb',
          instruction: 'Classify each مثال by نوعه من الجملة غير المعمولة.',
          source: '﴿إنا أنزلناه في ليلة القدر﴾ / ﴿الذي خلقكم﴾ / ﴿ولن تفعلوا﴾',
          words: ['إنا أنزلناه في ليلة القدر', 'الذي خلقكم', 'ولن تفعلوا'],
          labels: ['الابتدائية', 'صلة الموصول', 'المعترضة'],
          distractors: ['التفسيرية'],
        },
      ],
    },
    // ---------------------------------------------------------------- L5
    {
      id: 'l5',
      title: 'الجملة التفسيرية، والقسم وجوابه',
      subtitle: 'The Explanatory Clause, and القسم — its أركان, ما يُصدَّر به جوابه, and نون التوكيد',
      concepts: [
        {
          heading: 'الجملة التفسيرية وصورتاها',
          body: `<bdi>الْجُمْلَةُ التَّفْسِيرِيَّة</bdi> is the sentence explaining what precedes it. It has two forms: with a <bdi>حَرْفُ تَفْسِير</bdi>, as in <bdi>﴿وَنَادَيْنَاهُ أَنْ يَا إِبْرَاهِيمُ﴾</bdi>, or without one, as in <bdi>﴿مَسَّتْهُمُ الْبَأْسَاءُ وَالضَّرَّاءُ﴾</bdi> (explaining what precedes it).`,
          sample: `الجملة التفسيرية — تفسر ما قبلها؛ بحرف تفسير: ﴿أن يا إبراهيم﴾؛ بدون حرف: ﴿مستهم البأساء والضراء﴾`,
          exercise: {
            prompt: `Define the جملة التفسيرية and its two forms.`,
            kind: 'mcq',
            options: ['The sentence explaining what precedes it, either with a حرف تفسير or without one', 'The very first sentence of speech', 'A sentence forming a relative clause', 'A sentence disconnected in إعراب from what precedes it'],
            correct: 0,
          },
        },
        {
          heading: 'أركان القسم الثلاثة',
          body: `القسم has three أركان: (1) <bdi>فِعْلُ الْقَسَم</bdi> (e.g. <bdi>أُقْسِمُ</bdi> / <bdi>أَحْلِفُ</bdi> — usually deleted) (2) <bdi>الْمُقْسَمُ بِه</bdi> — together these two form القسم proper (3) <bdi>الْمُقْسَمُ عَلَيْه</bdi> — which is جواب القسم.`,
          sample: `أركان القسم — فعل القسم (أقسم/أحلف، يُحذف غالبا)، المقسم به (يشكلان معا القسم)، المقسم عليه (وهو جواب القسم)`,
          exercise: {
            prompt: `What are the three أركان of القسم?`,
            kind: 'mcq',
            options: ['فعل القسم, المقسم به, and المقسم عليه', 'المستغاث, المستغاث له, and حرف الاستغاثة', 'المحذِّر, المحذَّر, and المحذَّر منه', 'المشغول, المشغول به, and المشغول عنه'],
            correct: 0,
          },
        },
        {
          heading: 'اللام الموطئة تدل على قسم محذوف',
          body: `A deleted قسم before الجواب is indicated by the لام of القسم (<bdi>اللَّامُ الْمُوَطِّئَةُ لِلْقَسَم</bdi> / <bdi>لَامُ الْقَسَم</bdi>) entering الجواب, as in <bdi>﴿وَلَسَوْفَ يُعْطِيكَ رَبُّكَ فَتَرْضَىٰ﴾</bdi> — i.e. a قسم is implied.`,
          sample: `اللام الموطئة للقسم — تدل على قسم محذوف: ﴿ولسوف يعطيك ربك فترضى﴾`,
          exercise: {
            prompt: `What indicates a deleted قسم before الجواب? Give the example.`,
            kind: 'mcq',
            options: ['اللام الموطئة للقسم entering الجواب: ﴿وَلَسَوْفَ يُعْطِيكَ رَبُّكَ فَتَرْضَىٰ﴾', 'نون التوكيد alone, with no لام', 'إذا الفجائية', 'اللام المزحلقة alone'],
            correct: 0,
          },
        },
        {
          heading: 'ما يُصدَّر به جواب القسم',
          body: `جواب القسم may be opened (<bdi>يُصَدَّر</bdi>) with: <bdi>إِنَّ الْمُشَدَّدَة</bdi>, as in <bdi>﴿إِنَّ رَبَّكَ لَبِالْمِرْصَادِ﴾</bdi>; <bdi>إِنَّ الْمُخَفَّفَة</bdi>, as in <bdi>﴿إِنْ كُنَّا لَفِي ضَلَالٍ مُّبِينٍ﴾</bdi>; <bdi>قَدْ</bdi>, as in <bdi>﴿قَدْ أَفْلَحَ مَن زَكَّاهَا﴾</bdi>; <bdi>اللَّامُ الْمَفْتُوحَة</bdi>, as in <bdi>﴿لَنَسْأَلَنَّهُمْ أَجْمَعِينَ﴾</bdi>; <bdi>مَا النَّافِيَة</bdi>, as in <bdi>﴿مَا وَدَّعَكَ رَبُّكَ وَمَا قَلَىٰ﴾</bdi>; and <bdi>لَا النَّافِيَة</bdi>, as in <bdi>﴿لَا يَبْعَثُ اللَّهُ مَن يَمُوتُ﴾</bdi>.`,
          sample: `يُصدَّر جواب القسم بـ — إن المشددة: ﴿إن ربك لبالمرصاد﴾؛ إن المخففة: ﴿إن كنا لفي ضلال مبين﴾؛ قد: ﴿قد أفلح من زكاها﴾؛ اللام المفتوحة: ﴿لنسألنهم أجمعين﴾؛ ما النافية: ﴿ما ودعك ربك وما قلى﴾؛ لا النافية: ﴿لا يبعث الله من يموت﴾`,
          exercise: {
            prompt: `With what may جواب القسم be opened (يُصدَّر)?`,
            kind: 'mcq',
            options: ['إن المشددة, إن المخففة, قد, اللام المفتوحة, ما النافية, or لا النافية', 'Only ever اللام المفتوحة, with no alternative', 'Only ever نون التوكيد', 'It is never opened with anything at all'],
            correct: 0,
          },
        },
        {
          heading: 'نون التوكيد في جواب القسم: وجوبها وامتناعها',
          body: `نون التوكيد is obligatory in جواب القسم when الجواب is affirmative (<bdi>مُثْبَت</bdi>) and not separated from اللام, as in <bdi>﴿وَتَاللَّهِ لَأَكِيدَنَّ أَصْنَامَكُمْ﴾</bdi>. It is prohibited (1) when الجواب is not affirmative, as in <bdi>﴿لَا يَبْعَثُ اللَّهُ مَن يَمُوتُ﴾</bdi> (2) when it has no لام, as in <bdi>﴿تَاللَّهِ تَفْتَأُ تَذْكُرُ يُوسُفَ﴾</bdi> (3) when separated from اللام, as in <bdi>﴿وَلَسَوْفَ يُعْطِيكَ رَبُّكَ﴾</bdi>.`,
          sample: `وجوب نون التوكيد — الجواب مثبت وغير مفصول عن اللام: ﴿لأكيدنَّ أصنامكم﴾<br>امتناعها — غير مثبت: ﴿لا يبعث الله من يموت﴾؛ بلا لام: ﴿تفتأ تذكر يوسف﴾؛ مفصول عن اللام: ﴿ولسوف يعطيك ربك﴾`,
          exercise: {
            prompt: `When is نون التوكيد obligatory in جواب القسم?`,
            kind: 'mcq',
            options: ['When الجواب is affirmative (مثبت) and not separated from اللام', 'Whenever a قسم is mentioned, with no other condition', 'Only when الجواب is negated', 'Only when there is no لام at all'],
            correct: 0,
          },
        },
        {
          heading: 'اجتماع القسم والشرط: من يستحق الجواب',
          body: `When قسم and شرط combine, الجواب belongs to whichever came first (<bdi>السَّابِق</bdi>); the other's جواب is deleted, indicated by the mentioned one. In <bdi>﴿لَئِنْ أُخْرِجُوا لَا يَخْرُجُونَ مَعَهُمْ﴾</bdi>, <bdi>لَا يَخْرُجُونَ</bdi> is not مجزوم because it is جواب القسم (the implied قسم precedes الشرط), not جواب الشرط. When قسم precedes شرط, the فعل after the conditional particle must be ماضٍ — لفظا, as in <bdi>وَاللَّهِ إِنْ أَتَيْتَنِي لَأُكْرِمَنَّكَ</bdi>, or معنى (<bdi>لَمْ</bdi> + مضارع), as in <bdi>وَاللَّهِ إِنْ لَمْ تَأْتِنِي لَأَهْجُرَنَّكَ</bdi>.`,
          sample: `الجواب للسابق منهما — الآخر يُحذف جوابه ويدل عليه المذكور<br>﴿لئن أخرجوا لا يخرجون معهم﴾ — لا يخرجون جواب القسم لا الشرط، فلا يُجزم<br>إذا سبق القسم الشرط — يكون الفعل بعد أداة الشرط ماضيا لفظا (والله إن أتيتني لأكرمنك) أو معنى (والله إن لم تأتني لأهجرنَّك)`,
          exercise: {
            prompt: `When قسم and شرط combine, which gets الجواب?`,
            kind: 'mcq',
            options: ['الجواب belongs to whichever came first (السابق); the other’s جواب is deleted', 'الجواب always belongs to الشرط, never القسم', 'الجواب always belongs to القسم, never الشرط', 'Both get separate, independent جوابات'],
            correct: 0,
          },
        },
      ],
      quiz: [
        { q: 'الجملة التفسيرية has two forms:', options: ['with a حرف تفسير, or without one', 'مرفوعة and منصوبة only', 'ابتدائية and مستأنفة only', 'لفظية and معنوية only'], correct: 0 },
        { q: 'The three أركان of القسم are:', options: ['فعل القسم, المقسم به, and المقسم عليه', 'الفاعل, الفعل, and المفعول به', 'المحذِّر, المحذَّر, and المحذَّر منه', 'المشغول, المشغول به, and المشغول عنه'], correct: 0 },
        { q: '﴿وَلَسَوْفَ يُعْطِيكَ رَبُّكَ فَتَرْضَىٰ﴾ shows a deleted قسم indicated by:', options: ['اللام الموطئة للقسم', 'نون التوكيد', 'إن المشددة', 'ما النافية'], correct: 0 },
        { q: 'جواب القسم may be opened with:', options: ['إن المشددة, قد, اللام المفتوحة, ما النافية, or لا النافية', 'Only ever اللام المفتوحة', 'Only ever نون التوكيد', 'It is never opened with anything'], correct: 0 },
        { q: 'نون التوكيد is prohibited in جواب القسم when:', options: ['الجواب is not affirmative, has no لام, or is separated from اللام', 'الجواب is affirmative and not separated from اللام', 'a قسم is implied rather than stated', 'الجواب opens with إن المشددة'], correct: 0 },
        { q: '﴿لَئِنْ أُخْرِجُوا لَا يَخْرُجُونَ مَعَهُمْ﴾ shows لا يخرجون not مجزوم because it is:', options: ['جواب القسم, not جواب الشرط', 'جواب الشرط, not جواب القسم', 'neither جواب القسم nor جواب الشرط', 'مجزوم after all, contrary to the question’s premise'], correct: 0 },
      ],
      bank: [
        { title: 'التفسيرية بحرف تفسير', kind: 'mcq', prompt: '﴿وَنَادَيْنَاهُ أَنْ يَا إِبْرَاهِيمُ﴾ shows الجملة التفسيرية expressed:', options: ['with a حرف تفسير (أن)', 'without any حرف تفسير', 'as صلة الموصول instead', 'as المعترضة instead'], correct: 0 },
        { title: 'فعل القسم المحذوف', kind: 'mcq', prompt: 'فعل القسم (like أقسم or أحلف) is typically:', options: ['محذوف', 'مذكور دائما', 'مبنيا للمجهول دائما', 'منصوبا'], correct: 0 },
        { title: 'إن المخففة تصدر الجواب', kind: 'mcq', prompt: '﴿إِنْ كُنَّا لَفِي ضَلَالٍ مُّبِينٍ﴾ shows جواب القسم opened with:', options: ['إن المخففة', 'إن المشددة', 'قد', 'ما النافية'], correct: 0 },
        { title: 'اللام المفتوحة تصدر الجواب', kind: 'mcq', prompt: '﴿لَنَسْأَلَنَّهُمْ أَجْمَعِينَ﴾ shows جواب القسم opened with:', options: ['اللام المفتوحة', 'ما النافية', 'لا النافية', 'إن المخففة'], correct: 0 },
        { title: 'نون التوكيد الواجبة', kind: 'mcq', prompt: '﴿وَتَاللَّهِ لَأَكِيدَنَّ أَصْنَامَكُمْ﴾ shows نون التوكيد obligatory because الجواب is:', options: ['مثبت and غير مفصول عن اللام', 'غير مثبت', 'بلا لام أصلا', 'مفصول عن اللام'], correct: 0 },
        { title: 'امتناع النون بلا لام', kind: 'mcq', prompt: '﴿تَاللَّهِ تَفْتَأُ تَذْكُرُ يُوسُفَ﴾ shows نون التوكيد prohibited because:', options: ['الجواب has no لام', 'الجواب is مثبت وغير مفصول', 'a قسم is implied, not stated', 'الجواب opens with قد'], correct: 0 },
        { title: 'الفعل ماضيا لفظا بعد سبق القسم', kind: 'mcq', prompt: 'وَاللَّهِ إِنْ أَتَيْتَنِي لَأُكْرِمَنَّكَ shows the فعل after إن as:', options: ['ماضٍ لفظا', 'مضارع مجزوم', 'أمر', 'ماضٍ معنى فقط, not لفظا'], correct: 0 },
        {
          title: 'تركيب: أركان القسم',
          kind: 'tarkeeb',
          instruction: 'Match each term to its ركن من أركان القسم.',
          source: 'أقسم (المقدر) / بالله (في والله) / لأكيدنَّ أصنامكم',
          words: ['أقسم (المقدر)', 'بالله', 'لأكيدنَّ أصنامكم'],
          labels: ['فعل القسم', 'المقسم به', 'المقسم عليه (جواب القسم)'],
          distractors: ['المحذَّر منه'],
        },
        {
          title: 'تركيب: وجوب أم امتناع نون التوكيد؟',
          kind: 'tarkeeb',
          instruction: 'Classify each جواب قسم بحسب حكم نون التوكيد.',
          source: '﴿لأكيدنَّ أصنامكم﴾ / ﴿لا يبعث الله من يموت﴾ / ﴿تفتأ تذكر يوسف﴾',
          words: ['لأكيدنَّ أصنامكم', 'لا يبعث الله من يموت', 'تفتأ تذكر يوسف'],
          labels: ['وجوب', 'امتناع (غير مثبت)', 'امتناع (بلا لام)'],
          distractors: ['جواز'],
        },
      ],
    },
    // ---------------------------------------------------------------- L6
    {
      id: 'l6',
      title: 'بقية غير المعمولة، وشبه الجملة: خاتمة الكتاب',
      subtitle: 'The Remaining محل-less Types, and شبه الجملة — الظرف اللغو, المستقر, and المنصوب بنزع الخافض',
      concepts: [
        {
          heading: 'جوابا الشرط بلا محل، والتابعة لما لا محل له',
          body: `Two more جوابات الشرط have no محل من الإعراب: جواب of a non-jazm conditional (<bdi>لَوْ، لَوْلَا، إِذَا...</bdi>), as in <bdi>﴿وَلَوْ شِئْنَا لَرَفَعْنَاهُ بِهَا﴾</bdi>, and جواب of a jazm-conditional NOT linked by الفاء or إذا الفجائية, as in <bdi>إِنْ تَجْتَهِدْ تَنْجَحْ</bdi>. The eighth type, <bdi>التَّابِعَة لِمَا لَا مَحَلَّ لَه</bdi>, is a sentence that is تابع (e.g. معطوفة) to a sentence having no محل, as in <bdi>﴿وَاتَّقُوا الَّذِي أَمَدَّكُم بِمَا تَعْلَمُونَ ۝ أَمَدَّكُم بِأَنْعَامٍ وَبَنِينَ ۝ وَجَنَّاتٍ وَعُيُونٍ﴾</bdi> — the second أمدكم-clause follows الصلة, which itself has no محل.`,
          sample: `جواب الشرط غير الجازم — ﴿ولو شئنا لرفعناه بها﴾<br>جواب الجازم بلا رابطة — إن تجتهد تنجحْ<br>التابعة لما لا محل له — الجملة الثانية معطوفة على صلة الموصول التي لا محل لها`,
          exercise: {
            prompt: `Define the eighth type: التابعة لما لا محل له. Give the example.`,
            kind: 'mcq',
            options: ['A sentence that is تابع to a sentence having no محل, as in ﴿أَمَدَّكُم بِأَنْعَامٍ وَبَنِينَ ۝ وَجَنَّاتٍ وَعُيُونٍ﴾ following صلة الموصول', 'The very first sentence of speech', 'A sentence forming a relative clause on its own', 'A sentence interposed between two connected elements'],
            correct: 0,
          },
        },
        {
          heading: 'شبه الجملة كلها معمول، ونوعا الظرف',
          body: `All شبه جملة is معمول — none of it is غير معمول. الظرف (in the شبه الجملة sense) has two types: <bdi>الظَّرْفُ اللَّغْو</bdi> — attached (<bdi>مُتَعَلِّق</bdi>) to a mentioned عامل — and <bdi>الظَّرْفُ الْمُسْتَقِرّ</bdi> — attached to an obligatorily deleted general عامل (<bdi>كَائِن</bdi> / <bdi>اسْتَقَرَّ</bdi>).`,
          sample: `شبه الجملة كلها معمول، لا غير معمول فيها<br>نوعا الظرف — اللغو (متعلق بعامل مذكور)؛ المستقر (متعلق بعامل عام محذوف وجوبا: كائن/استقر)`,
          exercise: {
            prompt: `What is the ruling of شبه الجملة regarding العمل?`,
            kind: 'mcq',
            options: ['All شبه جملة are معمول — none is غير معمول', 'Half are معمول and half are غير معمول', 'All شبه جملة are غير معمول', 'It depends entirely on context, with no general rule'],
            correct: 0,
          },
        },
        {
          heading: 'مواضع الظرف اللغو: المرفوع والمنصوب',
          body: `الظرف اللغو is مرفوع محلا in a single position: <bdi>نَائِبُ الْفَاعِل</bdi>, as in <bdi>﴿وَجِيءَ يَوْمَئِذٍ بِجَهَنَّمَ﴾</bdi>. It is منصوب محلا in seven positions: <bdi>الْمَفْعُولُ الْمُطْلَق</bdi>, as in <bdi>﴿يَعْرِفُونَهُ كَمَا يَعْرِفُونَ أَبْنَاءَهُمْ﴾</bdi>; <bdi>الْمَفْعُولُ بِه</bdi>, as in <bdi>﴿عَفَا اللَّهُ عَنكَ﴾</bdi>; <bdi>الْمَفْعُولُ فِيه</bdi>, as in <bdi>﴿وَلَقَدْ نَصَرَكُمُ اللَّهُ بِبَدْرٍ﴾</bdi>; <bdi>الْمَفْعُولُ لَه</bdi>, as in <bdi>﴿يَجْعَلُونَ أَصَابِعَهُمْ فِي آذَانِهِم مِّنَ الصَّوَاعِقِ﴾</bdi>; <bdi>الْمَفْعُولُ مَعَه</bdi>, as in <bdi>هَاجَرَ النَّبِيُّ ﷺ مَعَ أَبِي بَكْرٍ</bdi>; <bdi>الْحَال</bdi>, as in <bdi>﴿ادْخُلُوهَا بِسَلَامٍ آمِنِينَ﴾</bdi>; and <bdi>التَّمْيِيز</bdi>, as in <bdi>﴿تَرَىٰ أَعْيُنَهُمْ تَفِيضُ مِنَ الدَّمْعِ﴾</bdi>.`,
          sample: `اللغو مرفوعا محلا — نائب الفاعل: ﴿وجيء يومئذ بجهنم﴾ (موضع واحد)<br>اللغو منصوبا محلا (٧ مواضع) — مفعول مطلق، مفعول به، مفعول فيه، مفعول له، مفعول معه، حال، تمييز`,
          exercise: {
            prompt: `In which single position is the ظرف اللغو مرفوع محلا? Give the example.`,
            kind: 'mcq',
            options: ['نائب الفاعل: ﴿وَجِيءَ يَوْمَئِذٍ بِجَهَنَّمَ﴾', 'المفعول به, alongside six other positions', 'الحال, alongside six other positions', 'It is never مرفوع محلا, only منصوب'],
            correct: 0,
          },
        },
        {
          heading: 'مواضع الظرف المستقر، ومعموليته بالتبعية',
          body: `الظرف المستقر is مرفوع بالأصالة in two positions: <bdi>خَبَرُ الْمُبْتَدَأ</bdi>, as in <bdi>إِنَّمَا الْعِلْمُ عِندَ اللَّهِ</bdi>, and <bdi>خَبَرُ إِنّ</bdi>, as in <bdi>﴿إِنَّ اللَّهَ مَعَنَا﴾</bdi>. It is منصوب بالأصالة in two positions: <bdi>خَبَرُ الْفِعْلِ النَّاقِص</bdi>, as in <bdi>﴿وَكُنتُمْ عَلَىٰ شَفَا حُفْرَةٍ مِّنَ النَّارِ﴾</bdi>, and <bdi>الْحَال</bdi>, as in <bdi>أَسْأَلُ اللَّهَ بِرَجَاءِ الْفِرْدَوْسِ فِي الْجَنَّةِ</bdi>. It can also be معمول بالتبعية, as <bdi>نَعْت</bdi>, as in <bdi>﴿أُولَٰئِكَ عَلَىٰ هُدًى مِّن رَّبِّهِمْ﴾</bdi> — <bdi>مِن رَّبِّهِمْ</bdi> is a نعت of <bdi>هُدًى</bdi>.`,
          sample: `المستقر مرفوعا — خبر المبتدأ: إنما العلم عند الله؛ خبر إن: ﴿إن الله معنا﴾<br>المستقر منصوبا — خبر الفعل الناقص: ﴿على شفا حفرة من النار﴾؛ حال: أسأل الله برجاء الفردوس في الجنة<br>معمول بالتبعية — نعت: ﴿على هدى من ربهم﴾`,
          exercise: {
            prompt: `How can a ظرف مستقر be معمول بالتبعية? Give the example.`,
            kind: 'mcq',
            options: ['As نعت: ﴿أُولَٰئِكَ عَلَىٰ هُدًى مِّن رَّبِّهِمْ﴾', 'Only ever as خبر المبتدأ', 'Only ever as حال', 'It can never be معمول بالتبعية'],
            correct: 0,
          },
        },
        {
          heading: 'حذف الموصوف مع شبه الجملة، وخاتمة: بعد معرفة، نكرة، ونكرة غير محضة',
          body: `A موصوف may be deleted, leaving its صفة, when الصفة is a ظرف مستقر with <bdi>مِنْ</bdi> or <bdi>فِي</bdi>, as in <bdi>﴿وَإِن مِّنكُمْ إِلَّا وَارِدُهَا﴾</bdi> (i.e. <bdi>وَإِنْ أَحَدٌ كَائِنٌ مِّنكُمْ</bdi>). As a closing note (<bdi>خَاتِمَة</bdi>): a شبه جملة after a معرفة is parsed as حال, as in <bdi>أَسْأَلُ اللَّهَ الْفِرْدَوْسَ فِي الْجَنَّةِ</bdi> — <bdi>فِي الْجَنَّةِ</bdi> is حال of الفردوس. After a نكرة, it is نعت, as in <bdi>أَسْأَلُ اللَّهَ بَيْتًا فِي الْجَنَّةِ</bdi> — unless الشبه جملة precedes the noun, in which case it is حال: <bdi>أَسْأَلُ اللَّهَ فِي الْجَنَّةِ بَيْتًا</bdi>. After a نكرة غير محضة, both are allowed — حال or نعت, as in <bdi>﴿وَقَالَ رَجُلٌ مُّؤْمِنٌ مِّنْ آلِ فِرْعَوْنَ﴾</bdi>.`,
          sample: `حذف الموصوف — إذا كانت الصفة ظرفا مستقرا بمن أو في: ﴿وإن منكم إلا واردها﴾<br>خاتمة — بعد معرفة: حال (في الجنة حال من الفردوس)؛ بعد نكرة: نعت — إلا إن تقدمت شبه الجملة فحال؛ بعد نكرة غير محضة: الوجهان جائزان`,
          exercise: {
            prompt: `How is a شبه جملة after a نكرة parsed?`,
            kind: 'mcq',
            options: ['As نعت — unless the شبه جملة precedes the noun, in which case it is حال', 'As حال, always, with no exception', 'As مضاف إليه, always', 'It cannot follow a نكرة at all'],
            correct: 0,
          },
        },
        {
          heading: 'المنصوب بنزع الخافض',
          body: `<bdi>الْمَنْصُوبُ بِنَزْعِ الْخَافِض</bdi> is a noun placed in نصب by removal of the preposition: نصب لفظا, as in <bdi>﴿لَأَقْعُدَنَّ لَهُمْ صِرَاطَكَ الْمُسْتَقِيمَ﴾</bdi> (i.e. <bdi>عَلَىٰ صِرَاطِكَ</bdi>), or نصب محلا, as in <bdi>﴿أَوَعَجِبْتُمْ أَن جَاءَكُمْ ذِكْرٌ مِّن رَّبِّكُمْ﴾</bdi> (i.e. <bdi>مِنْ أَنْ جَاءَكُمْ</bdi>). The removal of الخافض is also called <bdi>الْحَذْف</bdi>, <bdi>الْإِيصَال</bdi>, and <bdi>الِاتِّسَاع</bdi>.`,
          sample: `المنصوب بنزع الخافض — نصب لفظا: ﴿صراطك المستقيم﴾، أي على صراطك؛ نصب محلا: ﴿أن جاءكم ذكر﴾، أي من أن جاءكم<br>أسماء أخرى لنزع الخافض — الحذف، الإيصال، الاتساع`,
          exercise: {
            prompt: `What is المنصوب بنزع الخافض? Give both examples.`,
            kind: 'mcq',
            options: ['A noun placed in نصب by removal of the preposition — نصب لفظا or نصب محلا', 'A noun always مجرور by an implied preposition', 'A sentence with no محل من الإعراب', 'A حال clause negated by لا'],
            correct: 0,
          },
        },
      ],
      quiz: [
        { q: '﴿وَلَوْ شِئْنَا لَرَفَعْنَاهُ بِهَا﴾ shows جواب الشرط with no محل because الشرط is:', options: ['غير جازم (لو)', 'جازم ومرتبط بالفاء', 'جازم ومرتبط بإذا الفجائية', 'a قسم, not a شرط'], correct: 0 },
        { q: 'All شبه جملة are:', options: ['معمول, with no exception', 'partly معمول and partly not', 'entirely غير معمول', 'irrelevant to العمل altogether'], correct: 0 },
        { q: 'الظرف اللغو is مرفوع محلا in which single position?', options: ['نائب الفاعل', 'الحال', 'التمييز', 'المفعول به'], correct: 0 },
        { q: 'خبر الفعل الناقص and الحال are positions where الظرف المستقر is:', options: ['منصوب بالأصالة', 'مرفوع بالأصالة', 'مجرور بالأصالة', 'معمول بالتبعية فقط'], correct: 0 },
        { q: 'A شبه جملة after a معرفة is parsed as:', options: ['حال', 'نعت', 'مضاف إليه', 'مبتدأ'], correct: 0 },
        { q: 'المنصوب بنزع الخافض is also called:', options: ['الحذف, الإيصال, and الاتساع', 'التنازع and الإعمال', 'الجائز and الواجب', 'الحقيقي and السببي'], correct: 0 },
      ],
      bank: [
        { title: 'جواب جازم بلا رابطة', kind: 'mcq', prompt: 'إِنْ تَجْتَهِدْ تَنْجَحْ shows جواب الشرط with no محل because:', options: ['it is not linked by الفاء or إذا الفجائية', 'الشرط is غير جازم', 'a قسم precedes it', 'it is معطوفة on صلة الموصول'], correct: 0 },
        { title: 'التابعة لصلة الموصول', kind: 'mcq', prompt: '﴿أَمَدَّكُم بِأَنْعَامٍ وَبَنِينَ ۝ وَجَنَّاتٍ وَعُيُونٍ﴾ shows the second clause as:', options: ['التابعة لما لا محل له, following صلة الموصول', 'الابتدائية', 'جواب القسم', 'المعترضة'], correct: 0 },
        { title: 'اللغو منصوبا محلا: المفعول به', kind: 'mcq', prompt: '﴿عَفَا اللَّهُ عَنكَ﴾ shows عنك as ظرف لغو منصوب محلا as:', options: ['المفعول به', 'المفعول المطلق', 'الحال', 'التمييز'], correct: 0 },
        { title: 'اللغو منصوبا محلا: الحال', kind: 'mcq', prompt: '﴿ادْخُلُوهَا بِسَلَامٍ آمِنِينَ﴾ shows بسلام as ظرف لغو منصوب محلا as:', options: ['الحال', 'المفعول له', 'المفعول معه', 'المفعول فيه'], correct: 0 },
        { title: 'المستقر خبر المبتدأ', kind: 'mcq', prompt: 'إِنَّمَا الْعِلْمُ عِندَ اللَّهِ shows عند الله as ظرف مستقر:', options: ['مرفوع بالأصالة, خبر المبتدأ', 'منصوب بالأصالة, خبر الفعل الناقص', 'معمول بالتبعية, نعت', 'مجرور بالأصالة'], correct: 0 },
        { title: 'حذف الموصوف مع من', kind: 'mcq', prompt: '﴿وَإِن مِّنكُمْ إِلَّا وَارِدُهَا﴾ shows a موصوف deleted, leaving:', options: ['a ظرف مستقر (منكم) as its صفة', 'a ظرف لغو', 'a جملة تفسيرية', 'a نعت سببي'], correct: 0 },
        { title: 'شبه الجملة بعد نكرة متقدمة', kind: 'mcq', prompt: 'أَسْأَلُ اللَّهَ فِي الْجَنَّةِ بَيْتًا shows في الجنة parsed as حال (not نعت) because:', options: ['شبه الجملة precedes the نكرة noun بيتا', 'بيتا is actually معرفة', 'the verb is مبني للمجهول', 'the sentence has no ذو حال at all'], correct: 0 },
        { title: 'نصب لفظا بنزع الخافض', kind: 'mcq', prompt: '﴿لَأَقْعُدَنَّ لَهُمْ صِرَاطَكَ الْمُسْتَقِيمَ﴾ shows صراطك منصوبا بنزع الخافض:', options: ['لفظا (i.e. على صراطك)', 'محلا (i.e. من صراطك)', 'as a ظرف لغو, not نزع خافض', 'as a ظرف مستقر'], correct: 0 },
        {
          title: 'تركيب: اللغو أم المستقر؟',
          kind: 'tarkeeb',
          instruction: 'Classify each مثال of الظرف.',
          source: '﴿وجيء يومئذ بجهنم﴾ / إنما العلم عند الله',
          words: ['يومئذ', 'عند الله'],
          labels: ['اللغو', 'المستقر'],
          distractors: ['لا محل له'],
        },
        {
          title: 'تركيب: شبه الجملة بعد معرفة أم نكرة؟',
          kind: 'tarkeeb',
          instruction: 'Classify each مثال بحسب حكم شبه الجملة فيه.',
          source: 'أسأل الله الفردوس في الجنة / أسأل الله بيتا في الجنة',
          words: ['في الجنة (بعد الفردوس)', 'في الجنة (بعد بيتا)'],
          labels: ['حال (بعد معرفة)', 'نعت (بعد نكرة)'],
          distractors: ['مضاف إليه'],
        },
        {
          title: 'تركيب: نصب لفظا أم محلا بنزع الخافض؟',
          kind: 'tarkeeb',
          instruction: 'Classify each مثال.',
          source: '﴿صراطك المستقيم﴾ (أي على صراطك) / ﴿أن جاءكم ذكر﴾ (أي من أن جاءكم)',
          words: ['صراطك المستقيم', 'أن جاءكم ذكر'],
          labels: ['نصب لفظا', 'نصب محلا'],
          distractors: ['رفع محلا'],
        },
      ],
    },
  ],
};
